### ISSUE TITLE
auto-revert-check-vc-info and tramp are not compatible

### ISSUE THREAD

**Issue by tarsius** [magit/magit#1205]
Well, unless you don't mind these messages being printed every five seconds:

```
Tramp: Checking `vc-registered' for TRAMP-FILE...done
Tramp: Inserting `TRAMP-FILE'...done

```

The problem is that when `auto-revert-check-vc-info` is non-nil, then `auto-revert-handler` calls `vc-find-file-hook`, which for remote files prints the above noise (and is costly).

To work around this it is probably necessary to buffer-locally set `auto-revert-check-vc-info` to nil when visiting a file inside a remote repository.

**Comment by blaenk** [comment]
Woah I was running into this issue and realized it was incredibly difficult to find any information on. Eventually I realized it was because I had `auto-revert-check-vc-info` on and that led me here.

I do realize it's not a Magit issue, but I'm curious what you think about my workaround. I basically do what you said:

``` elisp
(setq auto-revert-check-vc-info t)

(defun my-disable-auto-revert-vc-in-tramp ()
  (when (and buffer-file-name (file-remote-p buffer-file-name))
    (setq-local auto-revert-check-vc-info nil)))

(add-hook 'find-file-hook #'my-disable-auto-revert-vc-in-tramp)
```

I checked the `find-file-hook` and I do notice that that function I added appears before the `vc-refresh-state` function, which from the help pages it seems like it replaced `vc-find-file-hook`.

The fact that my function comes before vc's gave me the impression that `auto-revert-check-vc-info` would be set to nil by the time vc kicked in, but in fact I do still see this message emitted once, and I do observe a noticeable lag before the file is opened, presumably because it's transmitting to/from the host:

```
Tramp: Checking ‘vc-registered’ for /scp:host:/some/file/here...done
```

This is still better than without this workaround, in which case it would run continuously, but I was wondering if you knew of a better way of doing this so that this wouldn't run at all.
