### ISSUE TITLE
magit-wip shouldn't take emacs down with it when it fails

### ISSUE THREAD

**Issue by expez** [magit/magit#1413]
While using cider, on win7, I jumped into a jar file to read some source.  That broke emacs to the point where I  had to restart it.  

`Error in post-command-hook (global-magit-wip-save-mode-check-buffers): (error ".../" isn't an existing directory`  

At that point **nothing** works.

**Comment by tarsius** [comment]
@expez said on #1885:

In a refactoring tool I'm working on I communicate with a subprocess which moves a bunch of files around.  This resulted in the following error being triggered:

`Error in post-command-hook (global-magit-wip-save-mode-check-buffers): (error "/a/deleted/directory/" isn't an existing directory`

I was under the impression that failure in a `post-command-hook` would be temporary (i.e. the hook gets cleaned after repeated errors) but emacs just spams that error upon every instruction now.

**Comment by tarsius** [comment]
Okay this is no longer a mystery to me. Since I have said the above, `next` developed the same symptoms and I have fixed them there.

The problem is that we call `git rev-parse [--show-cdup|--show-toplevel} in the file-visiting buffer's `default-directory`, and that this directory does not exist anymore. Emacs doesn't like that at all.

> I was under the impression that failure in a `post-command-hook` would be temporary (i.e. the hook gets cleaned after repeated errors) but emacs just spams that error upon every instruction now.

I thought so too, apparently it's more complicated than that.

Anyway on `next` this was by fixed by adjusting `default-directory` until we end up in a directory which actually still exists.

I am not going to backport that fix to `master` because `2.1.0` is just around the corner, and the backporting would be risky. Please update to `next`. Note that `global-magit-wip-save-mode` has been replaced with three new wip modes. They are less leaky and much faster. But documentation about these modes is sparse. That also applies to documentation in general, which is pretty much the only remaining reason why `2.1.0` hasn't been released yet.

**Comment by expez** [comment]
Thanks @tarsius!
