### ISSUE TITLE
make magit supporting delete remote tags 

### ISSUE THREAD

**Issue by jixiuf** [magit/magit#1505]
on next branch 
I called magit-show-refs-popup and select origin/master ,
it list remote tags , but when I call magit-discard I got 

```
user-error: Cannot discard this change
```

so could you make it support

```
git push origin :refs/tags/TAG
```

**Comment by lev-kusanagi** [comment]
Hi @tarsius, 
I tried magit-tag-prune and it returns the message "Same tags exist locally and remotely", whereas origin still contains multiple branches that are not present in the github remote, according to magit-show-refs-popup.
Perhaps I misunderstood how it works.
Thank you for any help and for this awesome package.

**Comment by tarsius** [comment]
`magit-tag-prune` exists because git does not differentiate between local and remote tags the same way it does for branches. To delete a remote branch just delete the respective "remote tracking" branch explicitly. In a sense a branch like `refs/remotes/origin/feature` is a local branch, but if you delete that using magit, then that also deletes `refs/heads/feature` on the actual `origin` repository. With git you have to "push nothing" (`git push origin :feature`) to delete a branch from a remote.

(Please don't ask for help on old issues. This way you are the only one who benefits. If you had asked on Stackoverflow instead, then others would see my answer too.)
