### ISSUE TITLE
When going to another representation or revision of the same thing go to correct position

### ISSUE THREAD

**Issue by tarsius** [magit/magit#1566]
Currently it just jumps to an essentially random position in the file in the working tree. For unstaged and staged changes, and for changes in HEAD that actually is the right thing to do (sans the random part of course).

Maybe jump to a different commit depending on whether we are on a added or removed line. Also make sure we really jump to the correct place inside the working tree file, that only is guaranteed for unstaged changes right now, for staged and HEAD changes that might very well not be the case, due to the unstaged (and in the latter case also the staged) changes.

**Comment by phil-s** [comment]
It would probably be nice if `default-directory` was set appropriately in the old-revision buffers? I frequently find myself using `dired-jump` or `find-file` from these buffers, only to find I'm in the wrong place.

Similarly if the likes of `vc-revision-other-window` just worked in those buffers.

On a related note, I'd also like to see a way to trivially jump from the old-revision buffer to the working copy file, so that instead of going back to the diff and using `<C-return>`, there's a single-step action to get me where I wanted to be. 

I thought this functionality would have been part of `vc`, but I can't see anything similar there either.

**Comment by tarsius** [comment]
What always works correctly is jumping from a diff showing *unstaged* changes to the appropriate position in the file in the worktree. The position might be off when jumping from *staged* changes to the file (when there are also *unstaged* changes "above" the place we are trying to jump to).

I have changed the title of this issue because it really also is about other "diff-like" things (e.g. ediff buffers) to other "file-like" things (e.g. blobs). *And* it should also work the other way around.

I won't implement any of this until I have implemented `git-handler.git` a file-handler for git blobs and trees.

**Comment by tarsius** [comment]
Also improve jumping from blamed files. Re #1860.

**Comment by tarsius** [comment]
Tabula rasa

Closing, to avoid pressuring myself into implementing this before the prerequisites are fully ready, just because there's an open issue for this but not the prerequisites.

Also see the [`3.1.0`](https://github.com/magit/magit/milestones) milestone (click on "more").
