### ISSUE TITLE
with-editor: continue to work after sshing to a remote

### ISSUE THREAD

**Issue by tarsius** [magit/magit#1638]
In `shell-mode` and `term-mode` buffers `with-editor` does support editing remote files on behalf of "child" processes running on a remote machine. But this is only the case if the `default-directory` is a tramp path.

What does not work is to create such a buffer whose `default-directory` is a local directory and then use `ssh` to connect to a remote. It is not enough to export the variable again, any attempt to use "the editor" to edit a remote file would result in a local file being edited. This is because we use `default-directory` to determine whether a local or remote file should be edited and the use of `ssh` does not change it.

**Comment by tarsius** [comment]
A few packages have been suggested here and in the first of the linked to SX questions. Unfortunately none of them really are sufficient.

* `remote-emacsclient` uses port forwarding and I don't think it addresses our problem at all
* `tramp-term` and `ssh` might solve our problem in a way, or not. But they expect that the user creates a new shell/term dedicated to a remote host. What we want is to start a local shell/term, and *ssh* to a remote by typing `ssh host` into that shell, then later exit again and ssh to a different remote, still in the same shell/term buffer.
* `dirtrack-mode` does "almost" what we want, except that it doesn't implement that one thing which we *really* need, the remote part of the filename.

`dirtrack-mode` is an alternative to `shell-dirtrack-mode`. The latter is enabled by default, but it also isn't aware of the existence of `ssh`, `sudo`, `su`, and a later `exit`.

----

However looking at it's implementation I have come to the conclusion that it would not be hard to extend it to do what we want, or to implement an additional `shell-hosttrack-mode` which behaves very much the same implementing just the missing part.

I have created a stub for this at https://github.com/tarsius/shell-hosttrack. The boilerplate is there, now someone just has to fill in the actual handling of these shell commands.

I think this should first be implemented as a separate package, so that we can start using it now. And then it should be merged with `dirtrack`, so that `hosttrack` can be deprecated once Emacs 25.1 is released.

----

For `term` I also found existing code which does directory tracking: `term-handle-ansi-terminal-messages`. Unfortunately it assumes that the use of `ange-ftp` instead of `tramp`. But it should be fairly simple to adapt it to `tramp` instead.

Here too I think that it would be best to first create a new package which simply redefines that function, and then later get that merged into Emacs (maybe the latter will require implementing a version which supports either `ange-ftp` or `tramp`. A stub is at https://github.com/tarsius/term-dirtrack.

----

In both cases I don't think that `with-editor` should automatically re-export a local editor variable after sshing to a remote. Instead the user should add `with-editor-export-editor` or similar to the new hooks `shell-process-ssh-hook`, `term-ssh-hook` etc.

----

Maybe someone else would like to implement this? I will eventually get to this, but while I would like `with-editor.el` to be "done" (which requires these things to work, even though it's not really that closely related, we just depend on some functionality which really ought to exist elsewhere), I also don't want to implement this before Magit 2.1.0 is released. I have done the research, and now implementing it should not be that much work -- then again one can never be absolutely sure that no complications show up, which is why I cannot to this myself now.

@Silex Maybe you could give it a go?

**Comment by Silex** [comment]
Awesome research! :astonished: 

The more I get to know TRAMP's inside and the more scared I am. The whole thing is very fragile and I'm wondering if creating a package based on sshfs would not solve a lot of issues.

About the current topic, I think it should be feasible but at the same point I realise it _will_ be broken in some scenarios, e.g if you ssh twice in a row (ssh to one box and from there ssh to another one). I mean, sure theorically you could make a multi-hop TRAMP path but it starts to sound sketchy. The whole idea of running shells _and then_ SSHing to a remote and expecting TRAMP to work looks a bit weird to me, but I guess it's mostly because `shell`/`term`/`TRAMP` have so many issues on their own that trying weird scenarios looks "dangerous" :laughing: 

Also the idea of monitoring commands instead of asking where we are with `pwd` looks very fragile... I know that's how `shell-dirtrack-mode` works and it seems to work fine (dirtrack-mode is even more fragile), but why doens't it simply set `default-directory` to `pwd` after every commands? Same for host detection, why not check for `SSH_*` variables (http://unix.stackexchange.com/questions/9605/how-can-i-detect-if-the-shell-is-controlled-from-ssh) ?

Anyway, I'm kinda busy at the moment but I'll try to give a shot at `shell-hosttrack`, maybe with my `pwd` idea (except if you foresee a problem with it). The thing is that I also said so for other issues (for example in projectile), and it's been a while I don't make any progress there... but the scope is also much larger, while `shell-hosttrack` is hackable in little spare time so there's hope!

**Comment by tarsius** [comment]
I am closing this as it is beyond the scope of `with-editor`. The stub repositories still exist, and I might eventually find the time to implement these packages, but this does not belong on the Magit TODO list.
