### ISSUE TITLE
magit-rebase-step error

### ISSUE THREAD

**Issue by QiBaobin** [magit/magit#1703]
Thanks for writing such a great package, I am using magit-20141228.1413, when I submitted the editing I got below error:

```
error in process sentinel: magit-get-top-dir: ...git/android/.git/rebase-merge/ isn't an existing directory
```

Please let me know if you need more details?

**Comment by tarsius** [comment]
Do you get that a lot? Because if not, then I don't really want to investigate this. I am currently trying to get a new release out which will be based on `next`, not `master` like the version you are using. So basically I would have to debug obsolete code. See #1645 for more information.

In any case this issue is not fatal, just press `g` and everything is as it would have been without the error.

**Comment by QiBaobin** [comment]
Fair enough, thanks.
