### ISSUE TITLE
Permissions to use `magit-popup.el'

### ISSUE THREAD

**Issue by Silex** [magit/magit#1716]
Hello,

I'm creating a mode and I need to display popups. 

At the moment I use `magit-define-popup` and it is great, it's simple to use and works nicely.

I'm not yet at the state where I can publish the code (many things are not working at all), but I thought that I could already ask you for permission to use it :)

If you're interested I'll ping you when I start publishing the package so you can have a look.

**Comment by tarsius** [comment]
Of course you have my permission -- not that you need it, but thanks that you asked I guess :-)

A more important question is whether I recommend that you do so. I still intend you replace with a yet-to-be-written package, but that actually makes it safer to use `magit-popup.el` -- I don't intend to make any substantial changes, and will instead start from scratch. So even after I have written `idefix.el`, and then *later* switched Magit to use that, `magit-popup.el` can live on in it's current form.

Though at that time it would probably be a good idea to rename it :-) Speaking of which, since `magit-popup` does not depend on any other Magit package, it could be distributed as a separate Elpa package. If your package does not depend on Magit itself, then you have my permission to add this library as a separate package to Melpa, similar to how that is done for `with-editor`.

**Comment by Silex** [comment]
Okay, great :+1: 

I was simply thinking of copying `magit-popup.el` to my package, but making it a MELPA package is a good idea... should I still name it magit-popup tho?

**Comment by tarsius** [comment]
Yes, let's stick to that name for now. Actually I am gonna put it on Melpa myself sometime later today. I first have to add a note to the commentary about the Melpa version of Magit not using it yet, and also have to add package.el specific header keywords.

**Comment by Silex** [comment]
Alright, thanks!
