### ISSUE TITLE
Rebasing doesn't work anymore with dirty submodules on 'next'

### ISSUE THREAD

**Issue by whirm** [magit/magit#1719]
I get "cannot continue rebase with unstaged changes".
It used to work just fine in the last release.

Thanks a lot for magit! I'm in love with it :D

**Comment by tarsius** [comment]
Unfortunately (for you) I am going on vacation tomorrow, so I won't be able to investigate myself. I had a quick look and to my surprise `git rebase` does not have `--ignore-submodule` or similar, that would have been an easy fix. Submodules are not even mentioned in the rebase manpage. You might want to check `git-config(1)` maybe there's a useful variable in there, didn't see anything when I took a quick look though.

**Comment by whirm** [comment]
Heh, no worries, have a lot of fun!

How come it works with the stable release?

**Comment by tarsius** [comment]
Ah, the problem is that `magit-anything-unstaged-p` doesn't use `--ignore-submodule`. That's probably correct in most cases, but here it prevents a perfectly safe operation. As a workaround you comment that out in `magit-sequencer-continue`. I will probably add a IGNORE-SUBMODULES argument to the predicate when I get back.

**Comment by whirm** [comment]
Great, thanks a lot.
