### ISSUE TITLE
Commit-mode buffer starts without empty line

### ISSUE THREAD

**Issue by Bruce-Connor** [magit/magit#1720]
I recently switched to the `next` branch.
When I hit `c c` to commit, a new window pops up for me to write the commit message.
This window has a few lines of comments. All of that is fine and usual.

However, unlike before, there's no empty line at the top of the buffer (where I would normallyu write the commit message). Instead the comments start at the very first line, and I have to hit `C-o` a couple of times to move them away.

Upon some investigation, I've found that the empty line at the top is getting deleted after the buffer is created. I can tell that happens because the buffer is marked as modified, and hitting `undo` restores the empty line.

I'm not aware of any hooks or advices I may have that might be causing this, so I thought I'd report it here. Do you have any suggestions on where I could look?

**Comment by tarsius** [comment]
Unfortunately (for you) I am going on vacation tomorrow, so I won't be able to investigate myself. One thing you should check is whether that only happens with 25.0.50, then it likely is due to a change in `log-edit`. But I doubt that. Then make sure you have really uninstalled the old `git-commit-mode.el` (and `git-rebase-mode.el`).

As for working around this issue, have a look at `git-commit-setup`. The last thing it does is run `git-commit-setup-hook` and that should work just fine for adding a kludge. Also check whether any of the default hook functions is causing this.

**Comment by Bruce-Connor** [comment]
Thanks, that hook led me to the culprit. Sorry to bother!
