### ISSUE TITLE
magit-section-forward much slower than magit-goto-next-section

### ISSUE THREAD

**Issue by abo-abo** [magit/magit#1724]
With current `master`, I can simply hold <kbd>n</kbd> and the scrolling is almost fluid.

For the same repository, on `next`, the speed of <kbd>n</kbd> is *much* lower, to the
point where holding it is not an option.

Still, when typing <kbd>n</kbd> in rapid succession, the speed is close to acceptable.
Maybe there was some canceling mechanism in `master` that prevented hangups, and this
mechanism didn't make it into `next`.

**Comment by tarsius** [comment]
> For the same repository, on `next`, the speed of <kbd>n</kbd> is *much* lower, to the
point where holding it is not an option.

I think that's mostly because it does more, most importantly it recreates the diff buffer for every commit on the way. What I do when moving to a far away commit is to use just regular `next-line` which bypasses updating the diff buffer and the other functions on `magit-section-movement-hook`.

**Comment by abo-abo** [comment]
> What I do when moving to a far away commit is to use just regular
> next-line which bypasses updating the diff buffer and the other
> functions on magit-section-movement-hook.

But I like updating the diff buffer - it's a great feature.  Maybe you
could add some caching or lazy font-locking or something.

Although it's already supposed to be fast:

    time git log HEAD^..HEAD > temp && git diff HEAD^..HEAD >>temp
    
    real    0m0.004s
    user    0m0.004s
    sys     0m0.000s

**Comment by tarsius** [comment]
> Maybe you could add some caching or lazy font-locking or something.

Doing it asynchronously using font-lock or like font-lock is a long time goal. For now we are stuck with what we have. Caching would introduce a lot of unnecessary complexity I am afraid - the approach I want to take is to make it fast, not work around it being slow.

> Maybe there was some canceling mechanism in `master` that prevented hangups, and this
mechanism didn't make it into `next`.

I believe there never was such a mechanism. This might be more feasible than caching.

> But I like updating the diff buffer - it's a great feature.

I like and use it all the time too and have so far considered the slow down you are reporting to be a documentation issue; having to use <kbd>C-n</kbd> instead of <kbd>n</kbd> when moving across many commits doesn't appear to be a big deal to me. Press <kbd>SPC</kbd> when you have arrived at the last commit.

> Although it's already supposed to be fast:

That's Git not Magit - the parsing is what takes long when displaying a diff.

> Still, when typing <kbd>n</kbd> in rapid succession, the speed is close to acceptable.

I have noticed that too and am puzzled by it. So there *might* be something else at play - did you try removing functions from `magit-section-movement-hook`?

This is a low priority issue for me right now, but if you can pin down the issue more precisely I would certainly be interested and try to address it soon.

**Comment by fjl** [comment]
Don't know whether the following is significant for this issue, but moving with C-n is also slow when navigating large diffs with magit from the next branch. I have profiled a bit and it looks like it's rehighlighting the diff on whenever I move in and out of a section: 

    - magit-section-update-highlight                                 4466  94%
     - run-hook-with-args-until-success                              2460  52%
      - magit-diff-highlight                                         2460  52%
       + magit-diff-highlight-recursive                              2460  52%
     - mapc                                                          2006  42%
      + #<lambda 0x1fb9f851d13c35d>                                  1145  24%
      + #<lambda 0x1fb9f851d13c35d>                                   832  17%
      + #<lambda 0x1fb9f851d13c35d>                                    19   0%
      + #<lambda 0x1fb9f851d13c35d>                                     7   0%
      + #<lambda 0x1fb9f851d13c35d>                                     2   0%
      + #<lambda 0x1fb9f851d13c35d>                                     1   0%

**Comment by tarsius** [comment]
It's more related to #1581.

**Comment by fjl** [comment]
Note that the profile does not include the smerge, *-refine-hunk functions at all. It's magit-update-highlight all the way down.

**Comment by tarsius** [comment]
See https://github.com/magit/magit/issues/1581#issuecomment-77744886. It takes about refinement but the same applies to highlighting.

**Comment by fjl** [comment]
Thank you.

**Comment by tarsius** [comment]
> moving with C-n is also slow when navigating inside large diffs

This has been addressed in #1830.

**Comment by tarsius** [comment]
> For the same repository, on `next`, the speed of <kbd>n</kbd> is *much* lower, to the
point where holding it is not an option.

The general case should be addressed by #1830.

> Still, when typing <kbd>n</kbd> in rapid succession, the speed is close to acceptable.

Still no idea why that might be.

> Maybe there was some canceling mechanism in `master` that prevented hangups, and this
mechanism didn't make it into `next`.

I tried implementing such a mechanism for logs:

```diff
diff --git a/magit-log.el b/magit-log.el
index c18e544..d72c4bb 100644
--- a/magit-log.el
+++ b/magit-log.el
@@ -810,6 +810,8 @@ (defun magit-log-maybe-show-more-commits (section)
     (forward-line -1)
     (magit-section-forward)))
 
+(defvar magit-log-follow-timer nil)
+
 (defun magit-log-maybe-show-commit (&optional section)
   "Automatically show commit at point in another window.
 If the section at point is a `commit' section and the value of
@@ -828,7 +830,17 @@ (defun magit-log-maybe-show-commit (&optional section)
                (magit-diff-auto-show-p 'blame-follow)
                (get-buffer-window magit-revision-buffer-name-format)
                (magit-blame-chunk-get :hash)))
-    (magit-show-commit it t)))
+    (when magit-log-follow-timer (cancel-timer magit-log-follow-timer))
+    (setq magit-log-follow-timer
+          (run-at-time 0.1 0.01
+                       `(lambda (buffer)
+                          (with-current-buffer buffer
+                            (unless (input-pending-p)
+                              (cancel-timer magit-log-follow-timer)
+                              (setq magit-log-follow-timer nil)
+                              (message "show %s" ,it)
+                              (magit-show-commit ,it t))))
+                       (current-buffer)))))
 
 (defun magit-log-goto-same-commit ()
   (--when-let
```

It does not work. If the delay is 0 then it has no effect - moving through the log by holding <kbd>n</kbd> still shows all the commits on the way. If it is bigger then ... well then there is a delay (when just moving down one commit). Using a very sort delay didn't do the trick.

Do you have any suggestions on how this could be done?

**Comment by abo-abo** [comment]
I just tried the next branch, I guess that `magit-goto-next-section` was renamed to `magit-section-forward`? In any case, it's still very slow.

> Do you have any suggestions on how this could be done?

Yes. Recently, I wrote [counsel-git-grep](https://github.com/abo-abo/swiper/blob/master/counsel.el) which basically just calls `git grep` after each key stroke.  For huge repositories, like Emacs, `git grep` isn't fast enough to follow my key strokes. So I've wrapped it all in a `while-no-input` loop.  I'm guessing that it uses some internal Emacs timer, and does nothing while there is input. I didn't have any problems with it so far, and it's reasonably snappy.

How it could work for magit:

- just wrap your `shell-command` or `start-process` in `while-no-input`.
- the old calls can be allowed to finish, but `while-no-input` will prevent you from creating too many new calls.
- each time you find that `while-no-input` interrupted you, just call `forward-line` instead of the planned `magit-section-forward`.

**Comment by tarsius** [comment]
> I just tried the next branch, I guess that `magit-goto-next-section` was renamed to `magit-section-forward`? In any case, it's still very slow.

"Everywhere" or just in logs?

**Comment by abo-abo** [comment]
> "Everywhere" or just in logs?

Just in logs.

**Comment by tarsius** [comment]
> `while-no-input`

That relies on `input-pending-p` too and from my experiment I get the impression that just holding a key does not ensure that there is pending input. Strange, isn't it. I will have to investigate further.

In any case if that macro would work then my approach would work too (unless it has some bug), and in that case my approach would be preferable because it does not even start to do something which would then be aborted.

**Comment by tarsius** [comment]
Ah wait, missed the `with-local-quit` - have to look into that.

**Comment by tarsius** [comment]
Okay so I tried `while-no-input` and there seems to be some canceling going on. However it is unusable because I cannot see the cursor and the highlighting move inside the log buffer while pressing `n`/`p`. So I end up at some random commit.

So I once more think we are down to two options:

* use `C-n`/`C-p` instead of `n`/`p`
* remove from `magit-log-maybe-show-commit`

I would like to be proven wrong - but I have serious doubts there is anything that can be done about this and therefor close this issue. I think having to use `C-n`/`C-p` is acceptable.

**Comment by abo-abo** [comment]
> unusable because I cannot see the cursor and the highlighting move inside the log buffer while pressing n/p

You should wrap `while-no-input` only around the time-consuming stuff (like `call-process`). The fast stuff, like updating the pointer you should do outside `while-no-input`.
I can look into this if I ever switch to next.
