### ISSUE TITLE
Support for commit grooming

### ISSUE THREAD

**Issue by jsyjr** [magit/magit#1729]
My company tries to mimic the Linux kenrel workflow of applying carefully prepared patch series.  Often once I have a modification worked out in my workspace I want to turn that into a small sequence of groomed local commits.

Given magit's support for staging and unstaging hunks it feels like this could be a natural extension.  Would it be possible to provide support for moving hunks forwards and back through the current local commits?

**Comment by npostavs** [comment]
Have you looked at https://github.com/magit/magit/wiki/History-Manipulation?

**Comment by phil-s** [comment]
jsyjr: How would this be different to (soft-)resetting to a previous commit (if necessary), and then just staging and committing hunks in the sequence you want? I don't understand why any special additional magit support is needed in this scenario.

**Comment by jsyjr** [comment]
npostavs:  Yes I did see that page.  The processes described are aimed at recovering from mistakes.  They definitely do not rise the the level of helpful support for common workflow.

phil-s:  Staging and committing in order is indeed possible but error-prone.  It definitely does not support any sort of iterative process.  Here is effectively the work flow I, my company and I would think more or less the entire Linux kernel community (to name just one) follow:
* Create a feature branch.
* With many WIP commits along the way develop the feature until it is functionally complete (no commitment yet to bisectability).
* Squash the feature branch down to a single commit.
* Append to the feature branch an initial set of empty commits (clean ups, renames, declaration of new interfaces, implementation of new interfaces, cut over existing code to use new interfaces, etc).
* Iteratively triage the hunks from the base squashed commit to the new commits.  Notice that a single hunk in the base commit may get teased apart into multiple hunks in distinct new commits.
* Probably discover along the way that proper exposition of the feature branch's contents requires introduction of additional commits (*e.g.* stumble across a forgotten rename).
* Delete base commit once it becomes empty.
* Confirm bisectability (our CI infrastructure automates this).
* Submit the commits for review (typically be extracting a patch series).

Initially edits resulting from review feedback will result in a new tip commit.  But then that commit's contents needs to be properly disseminated to the feature branch's earlier commits.

To me this feels like rebase --interactive on steroids in that it is manipulating history not at the commit level but rather the hunk and sub-hunk.  Magit already knows how to unstage and stage both hunks and selections.  Having identified a hunk or selection instead of simply unstaging it my proposal is for magit to allow me to target that hunk or selection to some other commit on my branch.

**Comment by phil-s** [comment]
So you're talking about doing a *single* manual pass through all the changes, during which you 'tag' each hunk in turn as being for any one of a series of known/planned commits; rather than doing multiple passes through the changes (one per commit; during which you stage only the hunks relevant to that commit) ?

I would suspect that would be a major piece of work. Git only has a single index for staging to, so Magit would presumably need to jump through a lot of hoops to provide such functionality.

Perhaps it could be facilitated with a convenient/quick way to *instantly commit* the current hunk using one of a series of pre-defined fixup messages. Then, once everything has been committed, you can rebase all of those fixups.

**Comment by Silex** [comment]
When I find myself in that situation (which I try to avoid and I prefer to simply create `fixup` commits as I go) I sometimes do this:

* do a temporary `tag` at the end of all my wip commits
* soft reset so the base
* create my base commits, without caring much about if I forgot something
* add what I forgot with `fixup` commits to the correct base ones
* finish with a big rebase
* `git diff master..mytag` to ensure I didn't forget any data

**Comment by jsyjr** [comment]
phil-s: My use of 'target' was not to suggest that magit should remember a complex mapping of hunks to diverse new commits.  Rather it was to contrast with today's more limited reverse operation which has no sense of why it is being executed nor of what it to become of the hunk once reversed.  Having identified a hunk I want to specify a target commit and have magit choreograph an appropriate sequence of steps along the lines of those described in the [wiki's History Manipulation page](https://github.com/magit/magit/wiki/History-Manipulation).

Here is a proposal using a dired-like workflow:
* User initiates the new workflow (migrate?).
* User marks hunks and/or selections to be migrated to a common destination commit.
* User requests execution of the pending migrate.
* Magit prompts for a target commit within the branch (distinct from HEAD).
* Magit goes through the necessary gyrations to migrate the identified hunks and/or selections to the chosen commit.
* Magit moves back to the original HEAD.

Does that feel any closer to realistic?

**Comment by phil-s** [comment]
Well, to me that now sounds a bit like:

* User stages hunks and/or selections to be migrated to a common destination commit.
* User performs a "fixup" commit (using `c f`, and then interactively choosing the existing destination commit).

Repeat as necessary, then do a single rebase to squash the fixups into their respective parents.

I guess I still don't see a particular need for anything new, but maybe I'm missing something. (It's also possible that tarsius will tell me that there's a bunch of functionality in Magit for doing all the things I'm suggesting would be hard, so I should probably bow out at this point, in case I'm putting you wrong.)

**Comment by tarsius** [comment]
First a general comment about breaking up a single commit into many: When not correcting mistakes but splitting up work into atomic commits then I recommend starting with a soft reset, so that all changes are uncommitted and unstaged. Having to revert in order to commit comes with a mental overhead which becomes an issue when you have to do it more than once or twice to fix a mistake.

Another general remark is that I suspect that most Linux (and Git) developers use the command line almost exclusively, so it cannot be all that bad to do this sort of thing with the tools provided by Git itself, on top of which Magit's current utilities are built. (Then again even just staging individual hunks is annoying with plain Git, so I guess we are just not hardcore enough, to need nothing else :-)

(Assuming starting with all changes unstaged is acceptable) I think that the functionality @jsyjr misses boils down to a command which (1) stages the current hunk, (2) instantly creates a new commit with just that change, and then instantly squashes that into (possibly preselected) commit.

I believe [stgit](http://procode.org/stgit) provides such functionality and [magit-stgit](https://github.com/magit/magit-stgit) integrates that into Magit. There also is an Emacs package dedicated to stgit. /cc @llvilanova

In the past I have looked into StGit a bit and think that implementing similar functionality directly in Magit might be more useful than wrapping StGit. But I have never used StGit except for testing and am not sure I would actually find it or something similar very useful.

The hypothetical command above, plus a "select target commit" (i.e. "patch" in stgit-speak) would be a minimal viable version of this. I won't implement that or something more complex before the next release. But it shouldn't be to hard to implement something like this by wrapping `magit-stage` and `magit-commit-fixup` (for now as a separate package) - but first investigate whether StGit and `magit-stgit` already provide what you need.

**Comment by jsyjr** [comment]
Thanks for the thoughtful reply.

On reflection I buy your argument on the merits of starting with a soft reset.  And I agree that your suggestion of a single magit command that:
* stages the current hunk
* turns that into a new commit
* immediately squashes that new commit into a (possibly preselected) commit

does indeed capture the essence of my work flow.

My first reaction - given my current experience on a high-end desktop equipped with SSDs - was to worry that git's commit churning might be sufficiently sluggish for me to want a way to select and process multiple hunks at once.  Happily I believe a careful exposition of your proposed functionality could make this very natural.  The starting point would be a magit operation that implements the last two steps of the above 3-step sequence (turn contents of staging area into a new commit and then squash immediately).  That would allow one to batch multiple hunks all targeted to the same commit, incurring the commit and squash overhead only once.  If the UI made choosing the target commit sufficiently easy (probably offering the most recently chosen commit as a default) that would suffice.  As an extension you could might add an operation that performed all three steps (though to me at this point that feels like overkill).

I understand and am entirely supportive of getting the current release wrapped up.  So thanks for taking the time to reply.

I will investigate magit-stgit and get back to you.

**Comment by tarsius** [comment]
> The starting point would be a magit operation that implements the last two steps of the above 3-step sequence (turn contents of staging area into a new commit and then squash immediately).

That already exists: <kbd>cF</kbd>.

**Comment by tarsius** [comment]
You will then have to select the target commit, but I am considering to teach how to optionally remember that commit for subsequent invocations.

**Comment by tarsius** [comment]
Probably gonna do something like this, but after the release.

**Comment by phil-s** [comment]
jsyjr: On a related note, make sure you're aware of git's `rebase.autosquash=true` config option. The "fixup" commit messages that magit generates are designed to work with that, so that when you initiate a rebase, git automatically does the right thing with all of the fixups.

**Comment by tarsius** [comment]
With the next branch that's not really necessary. The squash/fixup rebase (`rf`) and commit+rebase (`c{f,s,F,S}`) variants use it automatically (even without that setting or the respective argument set in the popup). Regular rebase (`rr`) does not use it by default, but `--autosquash` is available as an argument from the popup. I recommend using that instead and not setting it as a default or even setting `rebase.autosquash=true`. If you did the latter you would lose the possibility to rebase without squashing, which too can sometimes be handy. Better yet just use the rebase variant intended to perform the squashing (`rf`) and only use `r-ar` in rare cases when you want to perform the squashing and in the same go also make other modifications (though here I would usually just do two rebases `rf` and then `rr`.

**Comment by phil-s** [comment]
Ah. There are some options there which I am unfamiliar with. I've always used interactive rebasing (previously `E`, now `e e`) when squashing commits, and am used to having that "confirmation screen" showing me exactly what's going to happen (in which situation the autosquash config streamlines things). I'll have to experiment with these other approaches.

**Comment by llvilanova** [comment]
> (Assuming starting with all changes unstaged is acceptable) I think that the functionality @jsyjr misses boils down to a command which (1) stages the current hunk, (2) instantly creates a new commit with just that change, and then instantly squashes that into (possibly preselected) commit.

magit-stgit does indeed provide support for that. You stage the hunks you want, and refresh the selected StGit patch to include them (`Yg`). But it also does more, since its objective is to provide a simpler interface to develop patch series for projects that work with a patch review system and integrate "clean" patches instead of merge requests with multiple internal commits to fix things based on the reviews.

This makes it provide more featuers, like sending a mail thread with a sequence of commits, simplifying the process of reordering commits, rebasing with an upstream that might have integrated some of them, jumping to a worktree with the specified commit, etc (note that StGit uses the term patch and patch series, instead of commits).

**Comment by jsyjr** [comment]
@llvilanova
> But it also does more, since its objective is to provide a simpler interface to develop patch series for projects that work with a patch review system and integrate "clean" patches instead of merge requests with multiple internal commits to fix things based on the reviews.

This is indeed what we practice.  Our reviewing is based on [gerrit](https://code.google.com/p/gerrit/) which (concretely) works with git commits, not patches.  It is a developer's responsibility to submit a coherent, well structured set of commits for review.  We rebase accepted commits to obtain a clean linear history.

> note that StGit uses the term patch and patch series, instead of commits

Indeed.  That terminology is rooted in a mental model of email patches.  Foisting essentially redundant terminology on users who interact solely with commits and who potentially have never used an email patch only lengthens learning curves.

**Comment by tarsius** [comment]
So we have imagined these two possible commands:

1. stage + create fixup commit + rebase
2. create fixup commit + rebase (with memorized target commit)

I don't think (1) is a good idea because it would be to expensive to "apply" one hook at a time like this. (2) is already implemented `cF`, except for the memorization part. However that is not feasible because applying a fixup to a target commit changes its hash, so there is nothing that could easily be remembered. Remembering such things is quite involved which is why there are packages dedicated to it, e.g. StGit and magit-stgit. If you want such functionality then use such an existing tool (there also exists magit-topgit).

So there is nothing left that I could implement without just reimplementing these packages, and I am therefor closing this feature request as *wontadd*.

**Comment by phil-s** [comment]
I was [reminded](https://emacs.stackexchange.com/q/37055) of this issue, and noticed my [comment](#issuecomment-74586586) here:
<blockquote>Git only has a single index for staging to</blockquote>
and was in turn reminded that, as per #2760, this isn't actually true -- it is in fact possible to use multiple indexes.

None of this is on the magit road map as I understand it, but I thought I'd cross-reference the two things while I was thinking about them.
