### ISSUE TITLE
Suggestion: make double-prefixed push's set upstream default to no

### ISSUE THREAD

**Issue by ryantm** [magit/magit#1736]
For my typical workflow, I'm pushing my branches to a few different remotes and I use the double-prefix push (C-u C-u P P), which asks three questions: 1. what remote to push to, 2. the remote branch name, and 3. if upstream should be set to this location.

I think that it would be nice to set the default answer to the last question to be "no." Currently, there is no default. The other two questions have a default.

**Comment by npostavs** [comment]
You're using `master`, right? magit is currently in feature freeze (see #1645), so that behaviour isn't going to be changed.

On `next`, you would do `P e` (e is for "elsewhere"), which asks 1. which local branch to push (default to current) 2. the remote branch name (default to upstream or `origin/<branch>` with some `<other-remote>/<branch>` as completion candidates). The `--set-upstream` can set as an option before hitting `e` (`P - u e`); It defaults to off, and the default can be changed. For myself I have added

```el
    (defadvice magit-push-popup (around magit-push-arguments-maybe-upstream
                                        activate)
      "Enable --set-upstream switch if there isn't a current upstream."
      (let ((magit-push-arguments
             (if (magit-get-remote) magit-push-arguments
               (cons "--set-upstream" magit-push-arguments))))
        ad-do-it))
```

**Comment by ryantm** [comment]
Sorry for not saying what version I'm using. I am using the latest version on MELPA. Cool, that workflow on next will cover this suggestion, so closing. Thanks!
