### ISSUE TITLE
Trying to discard changes in a binary file fails

### ISSUE THREAD

**Issue by Silex** [magit/magit#1742]
Hello,

When trying to discard changes in an unstaged binary files, magit fails erroring with something about "cannot apply patch because of invalid characters" or something.

It'd be really easy to reproduce, but don't hesitate to ask if you want a proper backtrace.

**Comment by tarsius** [comment]
The problem is that Magit currently prepares a patch and then feeds it to `git apply` even when discarding a complete file, instead of simply using `git reset HEAD <file>`.

This let's us treat files the same way as hunks and regions, but doesn't work for binary files. So this should probably be changed. I *think* that the real reason why files are treated like hunks is that the old backup mechanism worked by saving patch files, so we had to use patches here to, or discarding a complete file would not create a backup. Now that we create a stash before certain actions (not just apply) we don't need to do it this way anymore, but I am not sure whether there are other benefits that we would loose when switching to `git reset`.

**Comment by tarsius** [comment]
There is another quite crucial benefit: doing it by applying a patch in reverse allows discarding just the staged changes, while leaving the unstaged changes alone. For binary files with staged changes we have to use `git reset --hard` but because that also discards the unstaged changes we need a bigger brighter warning. Also I don't know how to ask Git "do you consider this a binary file?".

**Comment by tarsius** [comment]
I'll get to this once I know the answer to http://stackoverflow.com/questions/28879578/how-to-ask-git-whether-it-considers-a-file-to-be-binary.

**Comment by Silex** [comment]
`git checkout HEAD -- somebinaryfile` sounds more sensible than `git reset --hard` no?

**Comment by Silex** [comment]
The first answer at http://stackoverflow.com/questions/6119956/how-to-determine-if-git-handles-a-file-as-binary-or-as-text gives some git tricks to check wether a file is binary.

**Comment by tarsius** [comment]
> `git checkout HEAD -- somebinaryfile` sounds more sensible than `git reset --hard` no?

That only discards the unstaged changes, we want to discard the staged changes (and also the unstaged changes, because we cannot just discard the staged changes for binary files).

```
$ git status
On branch next
Your branch is up-to-date with 'origin/next'.
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        modified:   binary

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   binary

```

We cannot use `git reset HEAD binary` (without `--hard`) because that just *unstages* the changes. We want to discard the changes, which means to also remove them from the work tree.

Well, we could also decide that when the user requested that the staged changes to a binary file, be discarded, just unstage them instead would be the lesser evil. In either case discard (which really is "discard this and only this" would not really do what the user wanted. But there's no way around doing either "instead of discard, unstage" or "discard this and also that other thing".
```

> some git tricks

I was hoping I would not have to rely on hacks like those...

**Comment by tarsius** [comment]
I now tend to think "instead of discard, unstage" is better, but there never-the-less has to be a warning, because it's not what the user requested.

**Comment by Silex** [comment]
Ah, yes you're right I forgot about the staged changes. In my workflow I almost never have staged binary files when I want to discard them.

**Comment by tarsius** [comment]
I am gonna go with "refuse to discard, suggest unstage instead". It's least dangerous, consistent with  we deal with requests for "impossible actions" in other places.
