### ISSUE TITLE
git add -p support

### ISSUE THREAD

**Issue by pharpend** [magit/magit#1744]
`git add -p` is a way of selectively staging hunks in the working directory, so each commit only contains one change. Magit currently has no support for this (or at least I can't find any). The only option is to stage or unstage entire files.

Could you add support for `git add -p`?

Thanks!

**Comment by tarsius** [comment]
> The only option is to stage or unstage entire files.

No no no no. Magit has something which is *much* better than `git add -p`. And that feature is probably the main reason why people like Magit.

You probably have noticed that sections, including the files listed in the staged and unstaged changes sections can by expanded using <kbd>TAB</kbd>. When you do that you can see the full diffs. Then you can move to an individual hunk using <kbd>n</kbd> and <kbd>p</kbd> and then stage just the current hunk using <kbd>s</kbd>. If you first mark just part of a single hunk, you can stage just the region, again simply by pressing <kbd>s</kbd>.

You might want to read the manual. It's a bit dated and some new functionality is not documented, but such essential features have existed since the beginning and are properly documented.

**Comment by pharpend** [comment]
There isn't a way to split the hunks, as far as I can see. Could you add that functionality?

**Comment by tarsius** [comment]
We rely on Git to come up with the hunks. It's possible to tell Git to create smaller ones using showing less context lines using <kbd>-</kbd>.

**Comment by afrepues** [comment]
@pharpend you can mark line(s) of an unstaged hunk and stage it using <kbd>s</kbd>, inversely, you can mark line(s) of a staged hunk and unstage it using <kbd>u</kbd>.

**Comment by pharpend** [comment]
@afrepues Thank you, I figured it out!
