### ISSUE TITLE
Can I add a minor mode to magit-mode-hook without calling (require 'magit)?

### ISSUE THREAD

**Issue by cpitclaudel** [magit/magit#1746]
Hi,

Installing magit from MELPA doesn't significantly delay my startup, and seems to work very nicely. However, unless I explicitly `'(require magit)`, I can't add the following code in my startup file.

```
(add-to-list 'magit-mode-hook (lambda () (turn-on-visual-line-mode))) 
```

Is there a way to register`visual-line-mode` with magit without paying a 1 second delay at each startup?

Thanks!

**Comment by tarsius** [comment]
Never use `add-to-list` to add a function to a hook, always use `add-hook` and friends to do so.

Also avoid adding lambdas to a hook - that makes it much harder to remove it again and is less meaningful when looking at the value of the hook variable, especially if the lambda ends up being byte-compiled. Here it is entirely unnecessary to use a lambda, because `turn-on-visual-line-mode` is a function which takes no arguments and can therefor be added directly to the hook.

And, unless you use an old version of Emacs, don't use `turn-on-some-mode` functions, it's now possible to use just `some-mode`, that no longer turns off the mode if it is already turned on.

So

```lisp
(add-hook 'magit-mode-hook 'visual-line-mode)
```

In the future please use the [Magit tag on the Emacs Stackexchange Site](http://emacs.stackexchange.com/questions/tagged/magit) to get help, and the issue tracker only for bugs and feature requests.

**Comment by cpitclaudel** [comment]
Thanks for the stackexchange pointer. Sorry for the use of `add-to-list`; this had been lying around my .emacs for a while; it's obvious in retrospect. 
Thanks for the great work on magit!
