### ISSUE TITLE
"git send-email" from magit

### ISSUE THREAD

**Issue by unhammer** [magit/magit#1747]
We already have "git send-email", but this requires adding various settings to ~/.gitconfig and installing perl scripts; it'd be much nicer if I could just press something like "N m" and it makes a format-patch out of the unpushed commits and puts it into a new email in message-mode.

**Comment by tarsius** [comment]
I don't remember - do we already have that on `master`? If so, and that's what you are using, please update to `next` and try whether that satisfies your needs.

**Comment by Silex** [comment]
On `next`, try the `W` key (`magit-patch-popup`)

**Comment by unhammer** [comment]
"W p" runs format-patch, but without putting it into an email, while "W r" does request pull (which assumes I have some remote to push to first). I was talking about putting the format-patch into a compose-mail, so I can just fill in the To-field and hit send.

**Comment by andschwa** [comment]
:+1:

**Comment by andschwa** [comment]
If one were to try implementing `send-email` on next, should send-email be a sub-command, like "W s" or a new command, `magit-email-popup`? Git `send-email` has at least one required option, `--to`, and the range.

Can a particular Magit popup action make a certain option required (and prompt for it) when it's not otherwise, or should the to field just be asked for in interactive?

**Comment by tarsius** [comment]
(Good questions. Generally speaking users either hate the popups (luckily just a few) or think they are totally awesome - but this goes straight to the limitations of the current implementation :-)

Ah, yes that's another reason why I am hesitating to add additional arguments to the patch popup: if we add send-mail to that popup, would the additional arguments still make sense. In the case of what you suggested in #1754, I am *guessing* that would be useful here too.

More likely though this needs a new popup. Look at blaming for an example of such a popup-with-just-one-action.

(For `idefix` the successor to `magit-popup` I plan to make it possible to define such things with just one command, by making it more like prefix arguments (except that they are *infix* arguments) and then optionally merge multiple commands that have such arguments into a shared popup (but it would still be possible to invoke the individual commands directly with just their own arguments shown in their own popup).

> Can a particular Magit popup action make a certain option required (and prompt for it) when it's not otherwise, or should the to field just be asked for in interactive?

Generally speaking this should be done inside `interactive`. If we go with a separate popup, then using visible arguments might also make sense. That should work with `--to` without any problems, but for positional arguments like "the range" there is no explicit support. It should be possible to fake it though. You would then have to post-process the arguments inside `interactive` and maybe even add a "helper mode", like for the "sequence popups".

Since everything else is ready now, I am going to concentrate on documentation now, and prioritize writing answers to questions that come up. So you might want to wait a little until I have written something more structured on the matter. Or go for it right away and come up with some other questions :-)

**Comment by andschwa** [comment]
Thanks for the reply @tarsius! It's way past my bedtime, I'll get back to this later.

**Comment by andschwa** [comment]
Yes, #1754 would be useful here. Git `send-email` and `format-patch` share a lot (but not all) of the same options, which is making me lean toward a new (or nested?) popup.

The actual `send-email` is not what @unhammer is looking for; his need would probably be better solved with a switch that adds `--stdout` to format-patch and redirects the output to an email buffer.

But I would still be happy to have `send-email` as it's one of the common Git commands I use that Magit does not (yet) support.

The popup successor sounds intriguing, but I couldn't find any reference to `idefix` on next.

I'm having fun with Lisp, and understand that Magit is under active development :smile:

**Comment by tarsius** [comment]
> I couldn't find any reference to `idefix` on next.

There ain't any code yet. Searching the issues for "idefix" might provide some hints.

**Comment by tarsius** [comment]
Closing in favor of #1800.
