### ISSUE TITLE
dependency versions

### ISSUE THREAD

**Issue by holomorph** [magit/magit#1758]
In `magit-pkg.el`, dash 2.8 is required, but in other files in magit, later versions of dash are required. It seems odd to me that the overall package should require an earlier version of a library than certain parts of it.  I thought I'd mention it.

Also, I was wondering about git-modes; I saw that the version headers were removed.  Is there a reason for that? For instance, git-modes being absorbed by magit?

I should probably mention that I came upon these questions when playing with `package-install-file`'s new act-on-a-directory features.

**Comment by tarsius** [comment]
> dash version

While they are part of the magit repository, these libraries are not actually part of the magit package as far as `package.el` is concerned.

The reason they specify different minimal version of dash, is that I checked what the current dash version was when I created these libraries/packages, but did not update the version elsewhere. I have now bumped it everywhere to the latest version. Currently older versions probably work just fine, but there were some additions in the last two releases, which I intend to make use of eventually.

> library versions

I used to have version header keywords in all libraries/packages I maintain. I removed them because the are only ever correct for a very short period of time, i.e. right after the release. When I made a new release I bumped the version, committed that change, and created a tag. For some time I then went on appending "-cvs", "-dev", "-git", or "+" to the version string in the very next commit. But usually I forgot, and when I did not, I was annoyed having to do that.

So in practice a version N didn't really mean "exactly release N" but "the last release was N, N+1 hasn't been released yet, and there might or might not have been commits since N".

So eventually I stopped. We aren't supposed to check version string into git anyway. `package.el` happens to disagree, and should be patched. `package-install-file` (or some function it uses) could be taught to use `git describe` in git repositories, similarly in repositories of different kinds. It should then convert e.g. `1.1-15-gojjsdfd` (15 commits after `1.1`) into `1.1.0.15` (injecting `.0` because some people use major and minor versions like `1.0` and `1.1` but still make subminor releases like `1.1.1`).

**Comment by holomorph** [comment]
> library versions

I see.  Unfortunately, it's not always `git describe` (or anything predictable) to get a meaningful string, and I don't know how that would be done programmatically.  For instance, `mpv` uses a release branch model and one actually has to do some work to get `0.8.2-264-g90adf29`.  Perhaps a good behavior for `package.el` to learn would be to realize "Hey, the package we're installing is in its foo repository!" and appending -foo (or something else appropriate, "snapshot" is valid according to `version-to-list`) to the installed version to indicate it's a snapshot.

Personally, I don't think keeping the headers there and changing only with a new release is too troublesome.  It would be nice if they were there, but it's easy enough for me to add them for my own purposes.

Thanks!

**Comment by tarsius** [comment]
Unfortunately all the suffixes understood by `version-to-list` are effectively pre-releases. For suffixes like "-snapshot" and "-git" that's not what I would expect. But it cannot do better than that because it uses an insufficient internal format. I have addressed this seven years ago in an alternative implementation: https://github.com/tarsius/vcomp/blob/master/vcomp.el#L24 :-)

So even if I could be convinced to go through the trouble of appending some suffix after every release, it would not work. I am not willing to increase the version itself at the same time, because at that time I cannot possibly know what the next version will be. It might be a major, minor, or subminor release, depending, among other things, on whether bugs are found and how severe they are.

> it's easy enough for me to add them for my own purposes.

Something like this seems reasonable:

```diff
diff --git a/lisp/emacs-lisp/package.el b/lisp/emacs-lisp/package.el
index de1158d..dd0f0a5 100644
--- a/lisp/emacs-lisp/package.el
+++ b/lisp/emacs-lisp/package.el
@@ -348,6 +348,16 @@ (defcustom package-selected-packages nil
   :group 'package
   :type '(repeat symbol))
 
+(defcustom package-fallback-version "99999999"
+  "Version used for packages which fail to specify one.
+If a package does not specify its version in the library header
+or the \"PACKAGE-pkg.el\" file then the value of this variable is
+used as fallback.  It has to be a valid version string, or nil
+in which case the lack of an explicit version causes an error."
+  :group 'package
+  :type '(choice (const  :tag "no fallback" nil)
+                 (string :tag "fallback")))
+
 (defvar package--default-summary "No description available.")
 
 (cl-defstruct (package-desc
@@ -1323,12 +1333,16 @@ (defun package--prepare-dependencies (deps)
                  (t dep)))
               deps))))
 
-(defun package-buffer-info ()
+(defun package-buffer-info (&optional fallback-version)
   "Return a `package-desc' describing the package in the current buffer.
 
 If the buffer does not contain a conforming package, signal an
 error.  If there is a package, narrow the buffer to the file's
-boundaries."
+boundaries.
+
+If the buffer does not specify the version and optional
+`fallback-version' is non-nil, then use that.  Otherwise the
+lack of a version is an error."
   (goto-char (point-min))
   (unless (re-search-forward "^;;; \\([^ ]*\\)\\.el ---[ \t]*\\(.*?\\)[ \t]*\\(-\\*-.*-\\*-[ \t]*\\)?$" nil t)
     (error "Package lacks a file header"))
@@ -1382,7 +1396,8 @@ (defun package-tar-file-info ()
 
 (defun package-dir-info ()
   "Find package information for a directory.
-The return result is a `package-desc'."
+The return result is a `package-desc'.
+If necessary use `package-fallback-version' (which see)."
   (cl-assert (derived-mode-p 'dired-mode))
   (let* ((desc-file (package--description-file default-directory)))
     (if (file-readable-p desc-file)
@@ -1395,7 +1410,8 @@ (defun package-dir-info ()
           (with-temp-buffer
             (insert-file-contents (pop files))
             ;; When we find the file with the data,
-            (when (setq info (ignore-errors (package-buffer-info)))
+            (when (setq info (ignore-errors
+                              (package-buffer-info package-fallback-version)))
               ;; stop looping,
               (setq files nil)
               ;; set the 'dir kind,
@@ -1429,7 +1445,9 @@ (defun package-install-from-buffer ()
 description file is not mandatory, in which case the information
 is derived from the main .el file in the directory.
 
-Downloads and installs required packages as needed."
+Downloads and installs required packages as needed.
+
+If necessary use `package-fallback-version' (which see)."
   (interactive)
   (let* ((pkg-desc
           (cond
@@ -1438,11 +1456,11 @@ (defun package-install-from-buffer ()
              ;; desc-kind can be created.  Such packages can't be
              ;; uploaded or installed from archives, they can only be
              ;; installed from local buffers or directories.
-             (package-dir-info))
+             (package-dir-info package-fallback-version))
             ((derived-mode-p 'tar-mode)
              (package-tar-file-info))
             (t
-             (package-buffer-info))))
+             (package-buffer-info package-fallback-version))))
          (name (package-desc-name pkg-desc)))
     ;; Download and install the dependencies.
     (let* ((requires (package-desc-reqs pkg-desc))
```
