### ISSUE TITLE
new dependency on ido-ubiquitous on next branch

### ISSUE THREAD

**Issue by dabrahams** [magit/magit#1763]
I don’t have ido-ubiquitous, but I use ido, so the next branch can’t get past go.

**Comment by tarsius** [comment]
Ido has some bugs and misses some features essential for completing anything but files and buffers, and ido-ubiquitous addresses most of them. Without these fixes it would for example not be possible to make a branch no longer track another branch, because `ido-completing-read` doesn't do the last part of the following (taken from the doc-string of regular `completing-read` which the ido variant should be able to replace):

> If the input is null, `completing-read' returns DEF, or the first element of the list of default values, or an empty string if DEF is nil, regardless of the value of REQUIRE-MATCH.

I understand your employer is giving you a hard time with regards to free software, but the alternative would be to copy great parts of `ido-ubiquitous` into magit, which just isn't very appealing.

You might also not want to use `ido-ubiquitous` elsewhere, and you don't have to - unless you enable `ido-ubiquitous-mode` it will only be used by magit.

You can add the following to your init file to avoid this dependency altogether, but then you have to live with the somewhat suboptimal result:

```lisp
(provide 'ido-ubiquitous)
(fset 'completing-read-ido 'ido-completing-read)
```
