### ISSUE TITLE
Is it practical to limit magit-revert-buffers to known affected buffers?

### ISSUE THREAD

**Issue by phil-s** [magit/magit#1807]
I'm posing this as a query because clearly applying the brute-force auto-revert hammer in all situations is the simple way to be certain of being in the correct state, and not doing that seems like a potential can of worms.

OTOH there may be significant performance benefits to be gained by looking into this.

The issue is that `magit-auto-revert-mode` is the biggest culprit for me when magit actions are slow. (I'm using the `next` branch; currently 9ffd7a5 from Apr 7 2015.)

In my current repo, without auto-revert, staging or unstaging takes ~0.4 seconds (which feels very responsive, but probably without a huge margin remaining).

With auto-revert processing 72 buffers (which I would suggest isn't an especially large number), staging or unstaging takes 2.7 seconds which, while not *unusable* by any stretch, is still well beyond the point of frustration when trying to build commits.

ELP shows me the following performance results:

    magit-stage               1           2.70008108    2.70008108
    magit-run-git             1           2.6999679370  2.6999679370
    magit-refresh             1           2.637550241   2.637550241
    magit-revert-buffers      1           2.277339453   2.277339453
    magit-revert-buffer       72          1.9534885929  0.0271317860

Spending two seconds checking all 72 of those buffers for possible changes after I stage or unstage part of one single file is not only super inefficient, but it might be the most annoying instance of slowness in the program at present.

This prompted me to wonder whether magit has easy access to the set of affected files when staging or unstaging? Or at least does it know if only a single file was involved? If so, and it was able to auto-revert only that one buffer, this would be nice and speedy.

Or maybe we can reliably refrain from triggering the auto-revert behaviour *at all* for staging and unstaging operations? Offhand I'm not seeing why that's necessary at all for these operations (albeit noting again the simplicity of the brute-force approach, which seems the most likely explanation).

I guess there are two questions here:

a) Is it practical to look at making the auto-revert behaviour smarter in general, so that it knows when to check everything and when it can restrict itself to a known set of affected buffers? (I suspect this would add considerable complexity.)

b) For the specific case of staging and unstaging (which would benefit so much from the performance boost), is it safe/practical to avoid/limit the auto-revert behaviour? If this is a low-hanging fruit which could be picked, it might well be worth considering, even if the general case of (a) is rejected.

**Comment by tarsius** [comment]
It's not practical to do something about this now (feature freeze and all). For the time being we are stuck with the brute force approach. Handling "each command" explicitly would indeed be quite a complication. Only handling staging (well all the "apply variants" as I call them) would be an option. I will consider that after the release of `2.1.0`. Everything that goes beyond that is a long time goal. (It *is* a goal, and has been for a while now, but it's in the fare distance, because it would touch on many things and has quite a few prerequisites.

**Comment by phil-s** [comment]
All good. In the meantime, I'll implement my own suggestion (at least in a basic way) via advice in the interim, and see how that works out:

    (defadvice magit-stage (around my-no-magit-auto-revert--stage)
      (let ((magit-auto-revert-mode nil))
        ad-do-it))
    (ad-activate 'magit-stage)

    (defadvice magit-unstage (around my-no-magit-auto-revert--unstage)
      (let ((magit-auto-revert-mode nil))
        ad-do-it))
    (ad-activate 'magit-unstage)

**Comment by tarsius** [comment]
Actually that's a good idea I thing. I might do it.

But I am afraid there is something else going on in your case, and I would like to fix that first.

Let's start by checking if third-party packages have added to `magit-after-revert-hook` and `magit-not-reverted-hook`.

Could you please elp again

**Comment by phil-s** [comment]
No, both of those are `nil`. I don't think I have anything interfering with magit, save for some key bindings and face customisations, but I'll do a test with a more bare-bones config.

**Comment by tarsius** [comment]
So what do we learn from this?

1. There is constant overhead of 0.5s. Which isn't great but not what this issue is about.

2. Determining whether a file needs to be reverted doesn't take lone (0.02s), but it sums up.

   I don't think we can make "checking whether a file has to be reverted" faster, which leaves three options.

* Avoid unnecessary checking as suggested above and very hard to do (except for a subset of some very specific cases such as staging).
* Do the checking asynchronously like `auto-revert-mode` does.
* Live with the fact that this feature does take time by either living with the delay or turning of the feature.

I'll look into the second option.

**Comment by tarsius** [comment]
We now avoid reverting after running git commands that are known not to make any changes to the worktree. A few might have slipped through.

Maybe in the future we'll also revert asynchronously, but that's a different issue.

**Comment by phil-s** [comment]
That looks really excellent, tarsius. Thank you!
