### ISSUE TITLE
Magit not refreshing information properly

### ISSUE THREAD

**Issue by eazar001** [magit/magit#1808]
After installing Magit 1.4.1, I've noticed that switching branches via magit-branch-manager will not refresh and show the proper branch on the emacs status bar. The branch will switch properly, but the changes will not be reflected visually on the status bar. I've also noticed that doing a `magit-reset-head-hard` will not show a refresh in the buffer either. I'm not sure if any of this is reproducible.

**Comment by eazar001** [comment]
Sorry, I neglected to inform you that I installed `magit` via `marmalade`.

**Comment by phil-s** [comment]
FYI with a fresh install of Magit 1.4.1 from Marmalade on Emacs 24.3.1 and Git 2.3.5, I can't replicate this issue.

**Comment by eazar001** [comment]
@phil-s Thanks for the data point. Yea, I had to downgrade to version 1.2.1, this seems to be working for me at the moment (I installed via AUR packages repo in Arch Linux). I'm also using Git 2.3.5 and emacs 24.4.1

**Comment by phil-s** [comment]
I've just checked with 24.4.1 as well, and see no issue there either. This is on Ubuntu 12.04 with Emacs and Git compiled from source, and a blank-slate Emacs config prior to installing Magit in each test.

Then I'm just visiting a repo, running `M-x magit-status`; `b v` to open the branch manager; visiting a tracked file; arranging visible windows for all three buffers; then changing back and forth between branches (selecting them with `RET` in the branch manager) and observing all three buffers reacting to the change.

If I disable `magit-auto-revert-mode` then the file-visiting buffer does not react to the branch change, but the mode lines (and buffer content) for the branch manager and magit status buffers are updated upon each switch.

**Comment by tarsius** [comment]
Indeed `magit-auto-revert-mode` is key here. The information in the mode-line is provided by the VC package not Magit. But if that mode is on, then `magit-revert-buffer` (which is the function doing the mode's job), calls `vc-find-file-hook`, which causes VC to refresh the mode-line.

That `magit-revert-buffer` *could* call `vc-find-file-hook` but that wouldn't make sense. Either it would not have an effect because VC did notice that the buffer is not up-to-date. Or if VC is a bit stupid about it the mode-line would be updated and essentially say "this buffer *would* be un-/modified, *if* you did revert it to what's on disk".

If you leave `magit-auto-revert-mode` off, and then manually revert when appropriate, then that would trigger `vc-find-file-hook` to be called, I believe.

**Comment by eazar001** [comment]
Ah, I did not know that the auto-revert mode was disabled by default. That would explain it.

**Comment by tarsius** [comment]
It's not disabled by default, but there's a discussion about it going on right now: #1809.

**Comment by tarsius** [comment]
Please reopen if you are still having issues.
