### ISSUE TITLE
Error initialising a new git repo

### ISSUE THREAD

**Issue by purcell** [magit/magit#1815]
Seems like a recent minor regression:

- Create new dir `/tmp/foo`
- `C-u C-u M-x magit-status RET /tmp/foo`

Result is:

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  directory-file-name(nil)
  magit-mode-get-buffer("*magit: %t*" magit-status-mode)
  magit-refresh()
  magit-run-git("init" "/tmp/foo/")
  magit-init("/tmp/foo/")
  #[(dir &optional switch-function) "[snip]" [dir topdir default-directory mode-symb12419 toplevel12420 init-args12421 magit-save-some-buffers magit-get-top-dir yes-or-no-p format "There is no Git repository in %s.  Create one? " magit-init magit-status-mode magit-refresh-status magit-mode-display-buffer apply magit-mode-init user-error "Not inside a Git repository" magit-status-buffer-name switch-function magit-status-buffer-switch-function buf-symb12422] 5 ("/Users/steve/.emacs.d/elpa/magit-90150116/magit.elc" . 192411) (list (if current-prefix-arg (magit-read-top-dir (> (prefix-numeric-value current-prefix-arg) 4)) (or (magit-get-top-dir) (magit-read-top-dir nil))))]("/tmp/foo/" nil)
  ad-Advice-magit-status(#[(dir &optional switch-function) "[snip]" [dir topdir default-directory mode-symb12419 toplevel12420 init-args12421 magit-save-some-buffers magit-get-top-dir yes-or-no-p format "There is no Git repository in %s.  Create one? " magit-init magit-status-mode magit-refresh-status magit-mode-display-buffer apply magit-mode-init user-error "Not inside a Git repository" magit-status-buffer-name switch-function magit-status-buffer-switch-function buf-symb12422] 5 ("/Users/steve/.emacs.d/elpa/magit-90150116/magit.elc" . 192411) (list (if current-prefix-arg (magit-read-top-dir (> (prefix-numeric-value current-prefix-arg) 4)) (or (magit-get-top-dir) (magit-read-top-dir nil))))] "/tmp/foo/")
  apply(ad-Advice-magit-status #[(dir &optional switch-function) "[snip]" [dir topdir default-directory mode-symb12419 toplevel12420 init-args12421 magit-save-some-buffers magit-get-top-dir yes-or-no-p format "There is no Git repository in %s.  Create one? " magit-init magit-status-mode magit-refresh-status magit-mode-display-buffer apply magit-mode-init user-error "Not inside a Git repository" magit-status-buffer-name switch-function magit-status-buffer-switch-function buf-symb12422] 5 ("/Users/steve/.emacs.d/elpa/magit-90150116/magit.elc" . 192411) (list (if current-prefix-arg (magit-read-top-dir (> (prefix-numeric-value current-prefix-arg) 4)) (or (magit-get-top-dir) (magit-read-top-dir nil))))] "/tmp/foo/")
  magit-status("/tmp/foo/")
  funcall-interactively(magit-status "/tmp/foo/")
  #<subr call-interactively>(magit-status nil nil)
  ad-Advice-call-interactively(#<subr call-interactively> magit-status nil nil)
  apply(ad-Advice-call-interactively #<subr call-interactively> (magit-status nil nil))
  call-interactively(magit-status nil nil)
  command-execute(magit-status)
```

**Comment by tarsius** [comment]
You are using `1.4.*`, right?

**Comment by purcell** [comment]
Sorry, should have provided that info. It's whatever is the latest in MELPA.

**Comment by purcell** [comment]
90150116, actually. Whatever that means. Thought I'd just have the latest snapshot.

**Comment by purcell** [comment]
I don't even see the current MELPA version (20150411.1731) in the package list of my recent Emacs HEAD snapshot -- just "90150116" with status "dependency". Hey @Malabarba, any idea why that would be? I'd have expected the MELPA version to also be listed.

**Comment by Malabarba** [comment]
Once a package is installed, only versions higher than the installed one are listed on the menu. I think that's always been the case (at least it's been the case since before I started messing around with package.el). That's why you don't see the Melpa version, because it's lower than the one you have installed.

As for the dependency. You probably have a package which depends on Magit. When we introduced dependency managing, we had to decide which already-installed packages would be marked as "explicitly installed" (listed as `installed`) and which wouldn't be (listed as `dependency`).
Obviously there was no perfect solution here. Emacs had no way of knowing which packages were instaled explicitly in the past. 
The decision was to mark as "explicitly installed" anything that wasn't required by another package (it was either that, or just marking everything). So, when this feature was introduced, if you had a package which required Magit, it wasn't marked as explicitly installed.

You can mark a dependency as explicitly installed by hitting `i x` on it (just as if you were installing it).

**Comment by purcell** [comment]
> Once a package is installed, only versions higher than the installed one are listed on the menu. I think that's always been the case (at least it's been the case since before I started messing around with package.el). That's why you don't see the Melpa version, because it's lower than the one you have installed.

But that version couldn't have come from MELPA, and so the (lower-numbered) MELPA version should still be listed somewhere in the `*Packages*` list, right, because it's in a different archive? And it isn't, so I can't opt to install it automatically. It seems like something is wrong.

**Comment by Malabarba** [comment]
> But that version couldn't have come from MELPA, and so the (lower-numbered) MELPA version should still be listed somewhere in the *Packages* list, right, because it's in a different archive?

Nope. Versions older than the one you have installed are never displayed, regardless of the archive.
Note how the Melpa-stable version of a package stops showing up after you install the Melpa version.

> And it isn't, so I can't opt to install it automatically. 

True. You'll need to delete the current version first, then you'll be able to see all available versions.
Since it seems you have some other package that depends on Magit, you'll have to remove that package as well (the package menu won't let you remove Magit otherwise, but you can get around that if you want by manually deleting the Magit directory).

**Comment by purcell** [comment]
@Malabarba Thanks, yes, that did it. I guess it would be nice to see in the package list what versions of installed packages are available in other archives, since all available versions are shown for uninstalled packages.

@tarsius I get the same problem with the MELPA snapshot package, fwiw.

**Comment by Malabarba** [comment]
Yes, it would be nice to have a key to temporarily disable hiding. Specially now that I'm about to introduce even more hiding. :-)

**Comment by tarsius** [comment]
In case you are wondering why there were `901NNNNN` "releases": When Melpa-Stable was created I had to do something to prevent `1.2.N` from being considered the latest stable release. It wasn't - it was an obsolete release and there was no current release.

So I started tagging the last commit on `master` with `901NNNNN`. I could have used `1.2.50` but choose the former, because it is bigger than `201NNNNN` and so Melpa-Stable users did not have to fiddle with pinning to use it.

That was a mistake I should have used `1.2.50`. But not there's nothing that can be done about it. So there are probably quite a few Melpa-Stable users who are stuck on `901NNNNN`. That's okay, `2.1.0` will be releases soon. It's update instructions will tell users to unintall Magit and dependencies, restart Emacs, and only then re-install Magit. That will be necessary regardless of this issue anyway, because the names of some dependencies change.

----

@purcell Since we ended up talking about something else. If you still have the original issue after updating to `1.4.2` or `2015NNNN`, then please open a new issue.

**Comment by Malabarba** [comment]
By the way, @purcell , I just pushed a commit to “Implement displaying obsolete packages”. It's off by default, but you can toggle it with `(` a-la `dired-hide-details`.

**Comment by purcell** [comment]
@tarsius It's working for me now, thanks.

@Malabarba It's not really about showing obsolete packages, for me: I'd like to see the latest package version available in every package archive. It currently seems to do that if you haven't yet installed the package, but once you have (as discussed here), then the packages in *other* archives are hidden. In the case discussed here, I hadn't installed the `901*` version from MELPA, but the MELPA `2015*` version was hidden nonetheless, and so I didn't even have the option of manually switching from one version to the other.

**Comment by Malabarba** [comment]
@purcell In that topic, You can now switch to a lower version number that's on a different archive by displaying it with `(` and then installing it. 
At least, that's the intention.

**Comment by purcell** [comment]
Ah, great -- I'll have to check it out!
