### ISSUE TITLE
magit-auto-revert-mode stopped working

### ISSUE THREAD

**Issue by ef4** [magit/magit#1821]
Using 20150411.1731 with Emacs 25.0.50.1, buffers do not get reverted even with magit-auto-revert-mode enabled.

**Comment by tarsius** [comment]
Also relevant here: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=20299. But you beat  Sean McAfee (@grimnebulin) to reporting it here.

It appears that `25.0.50` switched to rely on file (modification) notifications from the os. Maybe something is broken there. Or - and according to the linked report that is more likely - magit uses some functions from `autorevert.el` that are considered to be "internal" and those changes broke the magit functionality build on top of those functions.

The next release of magit, which is due soon, no longer relies on `autorevert.el` so you should be safe. Magit's `next` branch is mostly stable, so you should be safe to use that - and since you use Emacs's development version, you might as well use Magit's. Alternatively stay with the stable versions of both Emacs and Magit.

I don't think I'll fix this in `1.4.*` - Emacs `25.1` hasn't been released yet, and by the time it is Magit `2.1.0` will have been released too. Unless of course someone investigates this and provides a clean and sufficiently described patch. I won't do it - I *know* building on top of `autorevert.el` was a mistake and have *already* fixed it on `next`, but I no longer backport to `1.4.*` since the next release is due soon (and doing so would further delay it).

**Comment by ef4** [comment]
Sounds good, I'm happy to try using the next branch.

**Comment by ef4** [comment]
I can confirm that magit-auto-revert-mode is working using `next`.

**Comment by tarsius** [comment]
Should be fixed now on `master` too.
