### ISSUE TITLE
Magit 1.4 -> 2.x (next), missing features

### ISSUE THREAD

**Issue by Ganneff** [magit/magit#1829]
Hi

it may be just me being too dumb to find them, but from my workflow I am missing two things in magit from the next branch that the 1.4 version offered:

l r l and then telling magit to show log between branch X and Y.

And "Interactive rebase" branch X onto branch Y - old magit simply shown you all commits from the branch there (ie what git rebase -i master (while being in $otherbranch does), while magit now shows me a long list of commits "to select from". Huhwah? What do I need to do in magit-next to have the same behaviour as before?

Thanks for the magit btw, its great. Colleagues who prefer vim really envy me and that interface :)

Joerg

**Comment by Ganneff** [comment]
Hi

and playing a bit more, l r l can be done by l o and then entering master..branch (or whichever two). Thats not really as nice an interface as l r l gave, but works.

Joerg

**Comment by tarsius** [comment]
> Thats not really as nice an interface as l r l gave, but works.

The problem with reading two branches separately is that you cannot specify what kind of range you want `A..B` or `A...B`. That's not very relevant here but for e.g. diff it is. And the various commands that read a range should do it the same way. Have you noticed that you can use completion for A, then type "..", and then use completion again for B?

> And "Interactive rebase" branch X onto branch Y 

Do you really want to rebase commit from one branch to another and *at the same time* modify some of these commits (beyond what you might have to do to resolve conflicts)?

`r e` is for editing commits on the current branch. The log-like view is were you select which commit to start with (using `C-c C-c` or `.`).

`r r` is for rebasing onto another branch, defaulting to the upstream branch, but you can pick another. It rebases all commits since the merge-base.

`r o` is like `r r` but let's you additionally pick what commit to begin with.

**Comment by tarsius** [comment]
Some nice things you can do are described here: https://github.com/magit/magit/wiki/History-Manipulation

**Comment by Ganneff** [comment]
>> And "Interactive rebase" branch X onto branch Y
> Do you really want to rebase one branch to another and at the same time modify some of these rebased commits (beyond what you might have to do to resolve conflicts)?

Yes, I do. Workflow is basically a non-interactive rebase followed by an interactive rebase against the master branch. In which we want to edit the commits from the branch we are in.

Background: In our puppet every branch is an environment. So we use branches a lot to develop features and test changes. That means lots of small commits while you develop. As master doesnt stop to live, one randomly does a merge from master to get those newest commits.
When a feature is ready, there first is the non-interactive rebase which "moves" the branch start point to the latest master commit.
Then an interactive rebase is done for all commits in the branch where they get modified. Mostly that is "fixup" and "reword" and a bit of resorting.
And then a merge into master follows.
Followed by a deletion of the feature branch, as its history is uninteresting now.

So yes, I want a "rebase against this other branch and show me all commits from my branch, i want to rewrite them". I sure can go and find out that commit, then select it and work on it, but heck, this is software and its emacs and magit - its meant to make life easier, not harder. :)

> r o is like r r but let's you additionally pick what commit to begin with.

And that picking is annoying and not really neccessary IMO.

And thanks for the link.

**Comment by tarsius** [comment]
>>> And "Interactive rebase" branch X onto branch Y

>> Do you really want to rebase one branch to another and at the same time modify some of these rebased commits (beyond what you might have to do to resolve conflicts)?

> Yes, I do. Workflow is basically a non-interactive rebase followed by an interactive rebase against the master branch. In which we want to edit the commits from the branch we are in.

So in other words; *no*. You first do a non-interactive rebase and when that is done you *then* do *another* rebase, this time an interactive rebase. I.e. `r r RET` and then `r e n.... C-c C-c n/p/M-n/M-p/e/f/s... C-c C-c`.

> I sure can go and find out that commit, then select it and work on it,

So you want to skip the `n... C-c C-c` part. That would indeed be useful after rebasing onto master. And since master is being merged into the feature branch, it makes sense for the rebase to come before the interactive rebase. However if you *don't* merge master into feature branches, then it makes more sense to cleanup the feature branch before rebasing it onto master, and in that case it is useful to limit the range to something smaller than `<upstream>..HEAD`.

When point is on a commit when pressing `r e` then the `n... C-c C-c` step is skipped. You still have to select what commit to start with and the key sequence becomes `n... r e`, but it is easier to select what commit to begin with if you do it like this (just move to the end of the "Unpushed changes" section. That's what I usually do.

But there is room for improvement here - I'll think about it. Generally speaking the current way of doing interactive rebases it is more flexible than what you are used too. But in this particular use case it is less convenient than the old way.

>> r o is like r r but let's you additionally pick what commit to begin with.

> And that picking is annoying and not really neccessary IMO.

That's the one feature which "rebase onto" offers over "rebase", so if you don't  want that, then just don't use it. "Onto" is a misnomer inherited from git - all non-interactive rebases attach commits "onto" another branch. What differs when `--onto` is used, is that one can specify the range of commits that are to be rebased explicitly, e.g. `<start>~..HEAD` instead of `<other-branch>..HEAD`. I am considering to rename it to "Rebase from". I don't use this often but it's useful.

**Comment by npostavs** [comment]
> r e is for editing commits on the current branch.

Small note: `e e` does the same as `r e`, slightly easier to type.

**Comment by kyleam** [comment]
> Small note: e e does the same as r e, slightly easier to type.

This isn't true as of 6dae9199bf355efd3b258d7063abea33a043b6ba.  Now 'e' is bound to `magit-ediff-dwim`.

**Comment by tarsius** [comment]
Yep, there just ain't enough enough keys for command to get two of them. But it does take some time getting used to `r e`. I am still not their yet and try to type `e e` a lot, but luckily one notices after the first `e` that one made a mistake ;-)

**Comment by tarsius** [comment]
@Ganneff this should give you the behavior you want (on `r l`):

```lisp
(defun magit-rebase-unpushed (commit &optional args)
  "Start an interactive rebase sequence over all unpushed commits.
\n(git rebase -i COMMIT[^] [ARGS])"
  (interactive (let ((commit (magit-get-tracked-branch)))
                 (list (and commit (concat commit "^"))
                       (magit-rebase-arguments))))
  (if (setq commit (magit-rebase-interactive-assert commit))
      (magit-run-git-sequencer "rebase" "-i" commit args)
    (magit-log-select
      `(lambda (commit)
         (magit-rebase-interactive (concat commit "^") (list ,@args))))))

(magit-define-popup-action 'magit-rebase-popup ?l "Rebase unpushed"
  'magit-rebase-unpushed)
```

I don't know yet whether I am going to add something like this.

**Comment by tarsius** [comment]
I have added it.

**Comment by Ganneff** [comment]
Thanks.

Its not entirely the same but it comes near to it, so I now need to retrain my fingers to go the new ways for what I want :)
