### ISSUE TITLE
Refined background does not disappear when selecting region

### ISSUE THREAD

**Issue by uu1101** [magit/magit#1848]
Refined background highlight (that of the word SHOW in the screenshot) remains even when outside the selected region, where before it was removed as well. Compare following screenshots of 3eb8982 (where it disapeared) and late `next`:

You have mentioned in https://github.com/magit/magit/issues/1581#issuecomment-99816426 that it might be related to a recent removal of `'priority 2`.

Before:

![before](https://cloud.githubusercontent.com/assets/552356/7592377/469fd4d8-f8d3-11e4-97f6-8ebedc84e188.png)

After:

![after](https://cloud.githubusercontent.com/assets/552356/7592384/4de6051e-f8d3-11e4-9602-706b6c97d9c5.png)

Thank you for your effort.  Best regards,
uu1101.

**Comment by tarsius** [comment]
> You have mentioned in https://github.com/magit/magit/issues/1581#issuecomment-99816426 that it might be related to a recent removal of `'priority 2`.

Actually setting the priority does work, so I have done that now.

However it does not work if the theme sets `inverse-video`. Each face property is considered individually when constructing the final face while taking `priority` into account. When `inverse-video` is involved then that leads to strange result and because I only tested with the face I use which happens to do that, I though setting the priority does not work.

Both zenburn and solarized are guilty of that. I will propose fixes upstream, but first have to make sure that it doesn't break `diff-mode`. Also might end up having to define magit variants for the `diff-refine-*` faces.

In any case you can fix it for your theme by only setting the `:background`.

**Comment by uu1101** [comment]
Thank you!  This works nicely here (I'm using the default theme).  Thank you for your kindness!

**Comment by tarsius** [comment]
Since it works for the default theme now I am closing this. For the solarized themes I have fixed this (but not upstreamed yet) and for zenburn I will do the same. I don't expect there to be many more, if any, themes that do what the mentioned themes do.
