### ISSUE TITLE
Could use more consistency with the 'k' command

### ISSUE THREAD

**Issue by jwiegley** [magit/magit#1858]
I've noticed that 'k' doesn't always mean "kill/undo the thing under point".  Sometimes it does, as with changes to a file, but sometimes it doesn't, as with stashes when it prompts you for the stash.  I'd love to see this option return to the 1.x consistency, as I find myself typing 'y' automatically at the stash prompt a bit too often... :)

**Comment by tarsius** [comment]
> I find myself typing 'y' automatically at the stash prompt

I guess you mean `RET`.

Please read these excerpts from the manual:

Dangerous operations which may lead to data loss, by default have to
be confirmed.  With a multi-section selection this is done using
questions which can be answered with yes or no.  When the region isn't
active or if it doesn't constitute a valid section selection, then
such commands instead read a single item in the minibuffer.  When the
value of the current section is among the possible choices, then that
is presented as default choice.  **To confirm the action on a single
item the user has to answer ~RET~ (instead of "yes") and to abort ~C-g~
(instead of "no").  But alternatively the user may also select another
item, just like if the command had been invoked with no suitable
section at point at all.**

(This also applies to #1864).

So this *is* consistent, but just not with the same thing it used to be consistent with. Killing one stash/branch requires confirmation - just like killing more than one. And killing a stash/branch always let's the user choose what stash/branch to kill - even when there is a stash/branch at point (but then it defaults to that).

**Comment by tarsius** [comment]
It should also be noted that this is a compromise which takes into account some very opposing view points. E.g. some people think such commands should by default act on the "current thing" (e.g. the current branch) while others think they should act on the thing at point. Some people think the user should always have to confirm, others think for every confirmation there should be an option to disable having to confirm. There is disagreement on what the default of such options should be. And I don't consider such options a compromise, but the worst possible outcome. Keeping all this, and much more opposing viewpoints into account, I think the current behavior is a quite fine compromise.

Also this isn't just about these to commands, many other commands behave like this now. So this is consistent - just not with the thing it used to be consistent with. I think the new consistency is more important.

Just think of `RET` as "yes" and appreciate the possibility to select something else then it turns out you did not actually want to act on the thing at point (or if there is not thing at point, the "current thing").
