### ISSUE TITLE
Sometimes I have to re- ssh-add my private key

### ISSUE THREAD

**Issue by mhavard999** [magit/magit#1861]
I'm part of an organization, Org, that has a secret repo, SecretRepo.  If I am working on SecretRepo with magit, but then I go to work on another, personal repo called MyRepo, and then I try to push changes for MyRepo, I get this error: `ERROR: Permission denied to mhavard999/MyRepo.git denied to Org/SecretRepo`.

If I do `ssh-add ~/.ssh/id_rsa` the problem is fixed.

I've discussed the error with various parties including GitHub support, the main owner of Org/SecretRepo, and various people on irc and I couldn't get a solid explanation for this, so I think it has to be magit that is causing it because it only happens when I am using magit.

**Comment by tarsius** [comment]
Please try to push from the command line first. If that also doesn't work until you used `ssh-add` then this clearly hasn't anything to do with Magit. Otherwise it is less clear, but I am fairly certain that Magit is only incidental to the issue.

Git when run as a child process of Emacs by Magit appears to have problems to locate the appropriate `ssh-agent` or it can see the right agent but that doesn't know about the appropriate key. You might want to try my [keychain-environment](https://github.com/tarsius/keychain-environment) package to work around this issue.

**Comment by tarsius** [comment]
I am afraid you'll have to narrow this down yourself.
