### ISSUE TITLE
magit-pkg.el is outdated

### ISSUE THREAD

**Issue by Malabarba** [magit/magit#1867]
The version number described in there (on the next branch) is `2.0.50`, but there are lots of variables that claim `:package-version '(magit . "2.1.0")` and there's even a Melpa package (orgit) which depends on magit `2.1`.

**Comment by tarsius** [comment]
Well `2.1.0` hasn't been released yet. On Melpa the version string doesn't matter because it uses timestamps which are always higher than a normal version string. And Melpa-Stable and Marmalade (and actually also Melpa) are still on `1.4.*`.

I doubt I would have forgotten about it, but to make sure I have added "Make sure to bump all version strings." to the release steps outlined in #1645.

The information in the orgit is not quite correct, the last time I checked it still worked with `1.4.*`. But I am not 100% sure so I'll leave it at that.

**Comment by Malabarba** [comment]
Still, in the current situation, a user who downloaded the next branch can't install orgit with package.el. 
If version 2.1 doesn't exist, could orgit's dependency be changed to 2.0? This way it can still be installed with the next branch but you won't be making any promises about 1.4.

**Comment by tarsius** [comment]
> a user who downloaded the next branch can't install orgit with package.el.

Changing `2.1` to `2.0` won't change anything. When the user has installed (whatever version of) Magit by hand, then `package.el` cannot install `orgit` because that package depends on `magit` and `package.el` does not know about manually installed packages.

One could of course additionally install Magit `2015****` from Melpa to satisfy the dependency. And since `2015****` is larger than `2` (only slightly less so than when compared to `2.1`) the number in `magit-pkg.el` won't make a difference (when using Melpa one is installing the `2015****` pseudo version, not `2.*.*`).

But note that installing two versions of Magit in parallel voids all warranties. So a user of Magit's `next` branch effectively has to get `orgit` from Git too.

Maybe I am missing something, then you have to be more explicit about why the `.1` matters. (But I will be offline for a week or so. Feel free to adjust `orgit`s recipe, if you think that will help, but I strongly doubt that the version string is even relevant).

**Comment by Malabarba** [comment]
>> a user who downloaded the next branch can't install orgit with package.el.
>
> Changing 2.1 to 2.0 won't change anything. When the user has installed (whatever version of) Magit by hand, then package.el cannot install orgit because that package depends on magit and package.el does not know about manually installed packages.

Yes it does. By properly configuring the `package-directory-list` variable, package.el will integrate seamlessly with manually installed packages.

So, on my computer, I do in fact have Magit 2.0.50 installed. And package.el sees that. That allows me to install any Melpa package that depends on Magit, with the exception of orgit because it depends on 2.1.

**Comment by tarsius** [comment]
Didn't know that.

Please update  the `orgit` recipe yourself. I am on a very aweful internet connection (I have already spend half an hour on the 20 second task of telling github about a new ssh key and still not done).
