### ISSUE TITLE
git-commit-setup modifies COMMIT_EDITMSG, but does not save it

### ISSUE THREAD

**Issue by dato** [magit/magit#1877]
I am experiencing the following issue:

  - stage some hunks
  - commit with `c c`
  - Emacs prompts me to save COMMIT_EDITMSG before magit brings up the diff window

This is happening because:

  - `magit-diff-auto-show` includes _'commit_
  - `git-commit-setup` calls `(open-line 1)`, but does not save the buffer
  - Magit wants buffers saved before auto-showing the diff window

I can send a pull request with the following contents, but I’m not sure if there’d be any problems with this simple approach:

```diff
--- git-commit.el
+++ git-commit.el
@@ -370,7 +370,8 @@ (defun git-commit-setup ()
     (goto-char (point-min))
     (when (= (line-beginning-position)
              (line-end-position))
-      (open-line 1)))
+      (open-line 1)
+      (save-buffer)))
   (run-hooks 'git-commit-setup-hook))

 (defun git-commit-setup-font-lock ()
```

In the meantime, I’ve solved it locally by adding `save-buffer` to `git-commit-setup-hook`.

**Comment by tarsius** [comment]
> Emacs prompts me to save COMMIT_EDITMSG before magit brings up the diff window

We need to figure out why that is so, but your analysis of why it happens doesn't seem right.

> Magit wants buffers saved before auto-showing the diff window

Magit itself should only save *tracked* files and `COMMIT_EDITMSG` isn't even in the work tree. So my guess is that either a bug in how Magit determines the files it might want to revert (unlikely), or that some other code kicks in. Do you have `global-auto-revert-mode` enabled?

> `+(save-buffer)`

That's a kludge to work around the issue, it should not be required. We should not do it because in rare cases when something else goes wrong this might cause the commit to be created when the user actually wanted to abort. Hm, actually that's probably not the case - still it feels wrong.

We might want to consider the use of `set-buffer-modified-p` though. Not to work around this issue, but to make sure the buffer isn't "modified" yet, when the user has not actually done anything yet (not that it really matter, or rather *should* matter).

**Comment by dato** [comment]
> > Emacs prompts me to save COMMIT_EDITMSG before magit brings up the diff window
>
> We need to figure out why that is so, but your analysis of why it happens doesn't seem right.

Ah, damn, I just realized when this started happening.

This is in a repository with `--separate-git-dir`, and the Git directory is somewhere under the working tree itself (say, hypothetically, _.metadata/repos/main.git_).

**Comment by tarsius** [comment]
And I got once more confused about Magit's "auto save" and "auto revert" features. Magit wants to save all files in the work tree, not just tracked ones.

**Comment by dato** [comment]
I confirm that this solves the issue.

Thanks!
