### ISSUE TITLE
Magit buffer: solarized colors and changes counter

### ISSUE THREAD

**Issue by manuel-uberti** [magit/magit#1881]
Hi,

first of all thanks for one of the greatest Emacs package out there.
I know this may sound silly and you (rightly) have more important issues to take care of, but anyway:

- How did you get solarized colors in the Magit buffer you have at [magit.vc](http://magit.vc)?
- How did you get the counter between parens next to the items, i.e.: Unstaged changes (2)?

![top](https://cloud.githubusercontent.com/assets/8199224/7863511/161954ec-055d-11e5-8fc8-b39081db8621.png)

If what I need is just the ```next``` branch, I apologize and go get that.

This is how it looks on my setup.

![emacsshot](https://cloud.githubusercontent.com/assets/8199224/7863554/55febb74-055d-11e5-97a6-5c57a2373b36.png)

**Comment by tarsius** [comment]
> If what I need is just the ```next``` branch, I apologize and go get that.

You'll have to start with that and then ...


> How did you get solarized colors in the Magit buffer you have at [magit.vc](http://magit.vc)?

That's uses my personal [fork](https://github.com/tarsius/solarized-emacs) of the theme, it will be merged upstream but not now (as the changes are not compatible with the current release). Note that I consider the changes in my fork "patches" and that I sometimes tweak them and then rebase onto `origin/master`. So instead of pulling you should just fetch and then do a hard reset.

- How did you get the counter between parens next to the items, i.e.: Unstaged changes (2)?

Customize `magit-section-show-child-count`.

**Comment by manuel-uberti** [comment]
Perfect, thank you very much for the explanation.
