### ISSUE TITLE
magit-section-backward from point-max moves to first heading instead of last

### ISSUE THREAD

**Issue by abo-abo** [magit/magit#1882]
This is a regression from `master`, where it works fine.

**Comment by tarsius** [comment]
Hm, cannot reproduce this. I can imagine to cases: `point-max` and text before it is visible, or not. In both cases it works for me. Please post the last few visible lines of a buffer in which this doesn't work as expected.

**Comment by abo-abo** [comment]
Head:     38d266e magit-make-margin-overlay: work around Emacs issue
    Tag:      1.4.1 (2217)
    
    Stashes:
    stash@{0} On master: noiswitchb
    stash@{1} On master: foo
    stash@{2} On master: magit-dired-patch
    $
    |

Point is `|`.

**Comment by tarsius** [comment]
And what's that stray `$`? That shouldn't be there. Or did you insert that manually to indicate an emtpy line?

**Comment by abo-abo** [comment]
> And what's that stray $?

It's from `whitespace-mode`. Just an empty line.

**Comment by tarsius** [comment]
Never mind I can reproduce this in all cases now (must have used another command before or something).

**Comment by tarsius** [comment]
Turns out it's a regression introduced this month,  when a new (not so) special case was introduced with prevented the eob special case from being used when appropriate.

Note that this remains a special case and the behavior isn't exactly the same as elsewhere. Point doesn't move to the beginning of a section but to where the `$` is. I think that's acceptable for now. Maybe I will improve it at some point.
