### ISSUE TITLE
Support new git 2.5 feature, "multiple working trees"

### ISSUE THREAD

**Issue by catern** [magit/magit#1887]
The feature was added by this commit https://github.com/git/git/commit/68a2e6a2c80303144807c8c91a087427e3c8e727 and this Stack Overflow answer summarizes some information about it: http://stackoverflow.com/a/30185564

On latest magit 1.4.0 from MELPA, trying to run magit-status on a git working directory created by git checkout --to=directory, magit does not detect that the directory is a git working directory and prompts to create a new git repository in that directory. (!)

(Any simple workaround in the short term? I'm really enjoying this new feature and want to use it with magit :))

**Comment by tarsius** [comment]
This might just work when using magit's `next` branch, or not.

**Comment by catern** [comment]
Nope, fails with next branch as well.

**Comment by tarsius** [comment]
I just tried myself with `next` and there was no problem.

**Comment by tarsius** [comment]
Are you sure you were using the `next` branch? That would normally involve uninstalling the previous installation first as described in the update instructions.

It's really quite unlikely that this wouldn't just work without requiring any changes to magit, because on the `next` branch we just ask Git itself whether we are in a repository and such things.
