### ISSUE TITLE
Region selection regression for both next and master branch

### ISSUE THREAD

**Issue by wasamasa** [magit/magit#1890]
I used to be able to select a specific piece of code to stage by using the region, then hitting `s` to stage it. An upgrade to the latest MELPA release broke that functionality which manifests itself in deactivating the region upon finishing the selection (and when run with the rest of my setup, transfered itself to other buffers, can't reproduce it with `-Q` though). Switching to the `next` branch still exhibits this issue.

I managed to come up with a workaround though. Select the region, hit `s` before finishing the selection, finish the selection, hit `s` again after confirming it's still there.

**Comment by npostavs** [comment]
What does "finishing the selection" mean?

> (and when run with the rest of my setup, transfered itself to other buffers, can't reproduce it with -Q though)

The bug only happens without `-Q` or just the "transferred itself to other buffers" (?) happens without `-Q`?

**Comment by tarsius** [comment]
I suspect that's only the case when using the mouse to mark the region. I have noticed that before and only just now learned that the fix is surprisingly simple. (There can be some flickering of the hunk header when dragging the mouse, but that's not such a big deal (also I have no idea why that happens)).

I tried reproducing this on `master` to but here it already worked just fine. Also I cannot remember having changed anything here, that could make it suddenly stop working. Anyway `next` will hit melpa soon.

**Comment by wasamasa** [comment]
Yes, it's a mouse-only thing. The fix reminds me of a conceptually similiar bug (triple-clicking deselected the line) [in Circe](https://github.com/jorgenschaefer/circe/issues/98), the [upstream ticket](http://debbugs.gnu.org/cgi/bugreport.cgi?bug=20260) confirms that it's not present in Emacs HEAD.
