### ISSUE TITLE
magit-popup: integer options not working?

### ISSUE THREAD

**Issue by Silex** [magit/magit#1899]
Hello,

The following doesn't seem to work:

``` elisp
(magit-define-popup docker-containers-restart-popup
  "Popup for restarting containers."
  'docker-containers-popups
  :man-page "docker-restart"
  :options '((?t "Timeout" "--time=" 'read-number))
  :actions  '((?R "Restart" docker-containers-restart-selection)))
```

The timeout is still read as a string...
I mean the final option looks like `--time="10"` instead of `--time=10`. Any idea?

Thanks for the awesome package!

**Comment by Silex** [comment]
My bad, it's actually without the quote.

It still quotes it wrong tho.

**Comment by Silex** [comment]
Bah, actually I don't *really* need it to be `--time=10` anymore, so you can close this. Maybe you find it interesting and want to solve something about it so I'll let it open.

**Comment by tarsius** [comment]
The arguments that suffix commands receive are a list of strings and each string is the concatenation of the argument and its value. The quotes that are shown in the popup buffer are not part of these strings. In the case of numeric values that is a bit distracting but still "correct" - on the command line everything is a string too and unnecessary quotes around numeric strings don't break anything.

I plan to implement more complex "argument types" in `transient.el` but for `magit-popup.el` this will have to do.

But I noticed a releated issue, which I fixed in bfffc5a271fabca63fe6fa5702e54e86efd82fd3.

**Comment by Silex** [comment]
Thanks. On what version should I depend on for magit-popup? 2.1.0?

**Comment by Silex** [comment]
Here's what I'm talking about: https://github.com/Silex/docker.el/blob/master/docker-pkg.el

**Comment by tarsius** [comment]
It's probably better to depend on `2.0.50` see #1867.

**Comment by Silex** [comment]
Thanks!
