### ISSUE TITLE
staging/opening diffs slow on osx

### ISSUE THREAD

**Issue by dscherger** [magit/magit#1907]
Does anyone else have this problem? 

Viewing a long list of unstaged files, hit tab on one file to review the diffs takes ~3 seconds to open the diff display, hitting s to stage the file takes another ~3 seconds. After doing this for a while it feels *extremely* slow. While waiting for these things to happen the kernel_task cpu usage goes up to 100% or so and goes back to 5% or so after they complete.

This is running on OSX 10.10.3 on a Mid-2014 retina macbook pro 2.8 GHz core i7, 16GB 1600 MHz DDR3 ram, 500GB apple SSD with FileVault enabled.

GNU Emacs 24.5.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21) of 2015-04-10 
on builder10-9.porkrind.org

Thanks,
Derek

**Comment by tarsius** [comment]
Are you using magit-1.4.*? 2.1.0 will be released in a week and is much faster.

**Comment by dscherger** [comment]
I'm currently using magit 20150509.1613 from melpa. I see there's an upgrade 20150608.1139 available so I'll install that and see if it's any better.

I' m looking forward to 2.1.0 and I'll update this once it's available.

Thanks for you efforts on magit!

**Comment by tarsius** [comment]
> from melpa

That's 1.4.* then. I am closing since 2.1.0 should address this. If not, then please reopen once you have updated.

**Comment by alexander-yakushev** [comment]
@dscherger Chiming in because I just had a similar problem.

1.4 was fast as lightning, but 2.1.0 was hell too slow in status buffer. Simply navigating between unstaged files was slow, without even toggling to show the diff.

As it turned out via profiling, `linum-relative-mode` were to blame. It was enabled globally, and with each step it recalculated a lot of *hidden* lines inside magit-status buffer.

I disabled global linum-mode and now enable it via hooks for prog-mode. Everything is fast again.

**Comment by tarsius** [comment]
I have heard reports about `linum-mode` making magit slow several times now, and am wondering whether that mode can be enabled "partially". I.e. the line numbers are not actually being displayed but still being calculated. I cannot see how having `linum-mode` enabled in magit buffers can be useful. So I would expect users to turn it of in magit buffers. This is what lead to my speculation about the mode being "partially enabled".

**Comment by alexander-yakushev** [comment]
I didn't enable it for magit (and it is useless there), but I enabled it globally for all major modes. I think it will be helpful to mention this mode in FAQ that one should control where it is enabled.

**Comment by tarsius** [comment]
Do I get this right: `global-linum-mode` is a problem by itself, and `linum-relative-mode` makes matters worse?

Often globalized modes come with an option to prevent the local mode to be turned on in certain major modes. Not here:

```
(define-globalized-minor-mode global-linum-mode linum-mode linum-on)

(defun linum-on ()
  (unless (minibufferp)
    (linum-mode 1)))
```

I suppose I could advise that to not have an effect in buffers whose major-mode derives from `magit-mode`.

**Comment by alexander-yakushev** [comment]
I think exactly `linum-relative` is to blame because it does a recalculations when you navigate up and down. It is fast in regular modes because it only recalculates what's on screen. Although, in magit, when you have separate big unstaged files with a lot of changes, to `linum-relative` they are all *on-screen* (even though they are collapsed). Hence the extra computation and delay.

However, maybe `linum-mode` alone is also slow with Magit, I haven't tried.

**Comment by dscherger** [comment]
What version of emacs are you looking at? I have 24.5.1 and can't find
anything about linum-relative in apropos linum. Afaict I have
global-linum-mode disabled. I see a linum-version that is set to 0.9x

Cheers,
Derek

**Comment by alexander-yakushev** [comment]
24.4.1, linum-relative is installed explicitly.

You can try profiling the magit to see what's going on. Enter `magit-status` buffer, then do `M-x profiler-start`, move around, and do `M-x profiler-stop`. You should see what causes the biggest performance drop.

**Comment by dscherger** [comment]
Just upgraded to 2.1.0 and it seems to be *way* faster, nice work! Now I
need to figure out the new ui and get used to it.

Cheers,
Derek
