### ISSUE TITLE
Provide instructions for specifying dash.el location

### ISSUE THREAD

**Issue by scottjad** [magit/magit#1914]
Since 'make lisp' requires dash, if someone is not using package.el then it won't be found afaict and make will fail. I didn't find any mention of DASH_DIR in the installation instructions.

I added it via the wiki, feel free to revert or edit if you don't like.

https://github.com/magit/magit/wiki/Installation/e516bd5ba59dc03bec2adc6c8266ebcf3fde3524

**Comment by tarsius** [comment]
I have removed the `next` instructions from that page and instead link to the `2.1.0` instructions in the manual. The `master` instructions I have improved a bit, and have also adjusted the `2.1.0` instructions accordingly.

**Comment by scottjad** [comment]
Thanks.

The config.mk method seems to be slightly more work than specifying DASH_DIR but I guess you have a good reason for preferring that method.

I did just notice the part about magit/../dash being checked automatically. If you expanded that to support magit/../dash.el then I think that would cover more cases. The dash repo is named dash.el so I would guess the most common folder name would be dash.el not dash.

I don't know the correct way to handle only dash and dash.el folder names in default.mk on `DASH_DIR = $(TOP)../dash` but if you do then I'd recommend adjusting that to support dash.el. Note using dash* will fail since there are other packages starting with dash.

On a different issue, I think the "these" link in README.md in the following text is broken:

```
To install the 2.0.50 pre-release now, follow these instructions. Note that until 2.1.0 has been released you have to install directly from the development repository.
```

**Comment by tarsius** [comment]
> The config.mk method seems to be slightly more work than specifying DASH_DIR but I guess you have a good reason for preferring that method.

Yes I have. Doing it once is *less* work than doing it after every pull.

>  did just notice the part about magit/../dash being checked automatically. If you expanded that to support magit/../dash.el then I think that would cover more cases. The dash repo is named dash.el so I would guess the most common folder name would be dash.el not dash.

Well, that would probably keep a few people from having to edit `config.mk`. But there's no good reason to have a local directory with a suffix intended for a certain *file* type. On Github it *does* make sense to use suffixes or prefixes that indicate the "project type" - because Github does not provide any other way of "grouping" repositories.

So I don't think it is worth supporting `../dash.el`. Most users who install all packages by cloning a repository, like I do, probably use the package name as the name of the top-level directory. And users who install most packages using Elpa should really install `dash` that way too (since so many packages depend on it).

> the "these" link in README.md in the following text is broken:

Yep, I used `[these](install)` when I should have used `[these][install]`.
