### ISSUE TITLE
Bind magit-show-refs back to "b v"

### ISSUE THREAD

**Issue by tuhdo** [magit/magit#1942]
I really love branch manager. I use it daily. In magit 2.1, `b v` to show branch manager was removed. I think `magit-show-refs` replaced it, but currently it has no key binding. It should be assigned back to `b v` for such a great feature.

**Comment by kyleam** [comment]
magit-show-refs-popup is bound to `y`, and magit-show-refs-head is its
default action.

**Comment by tuhdo** [comment]
Good to know. However, currently pressing `RET` open the latest commit, not checking the branch out. Should we revert back to this behaviour?

**Comment by tarsius** [comment]
> In magit 2.1, `b v` to show branch manager was removed.

Back in the days when the branch manager was available from the branching popup, the popup featured some arguments which were only suitable for the former, but not any of the other actions.

So I created a separate popup just for this action and moved it to a separate top-level binding. Later (I believe) I changed the "popup" to default to just invoking the default action without showing the popup, because that's usually what users want anyway. `C-u y` shows the popup.

Also making the refs popup available from the branch and remote popups again, would be inconsistent. If we did that, then we would also have to duplicate other top-level bindings here, for example `m` (I actually sometimes start with the branch popup when I intend to merge. But that's probably just me and doesn't mean that key should be added).

> However, currently pressing `RET` open the latest commit, not checking the branch out. 

All branch sections displayed in any context now have the same section type `branch`, so all keys behave the same on a branch regardless of where it is displayed. Branches are sometimes displayed in lists (usually logs) whose other elements are of type `commit`. Therefore it is important that `branch` sections behave the same as `commit` sections whenever possible.

To show the log for the branch at point, you now have to type `l o RET`. I admit, that's not as nice as before - but sometimes compromises have to be made to achieve overall consistency.

**Comment by tarsius** [comment]
Oh wait, `RET` used to checkout the branch! You can do that with `b b RET` now.

(And I should also note that binding `RET` to the checkout command was a bad idea in the first place - everywhere else this just *visits* something).

**Comment by shreevatsa** [comment]
I may be mistaken, but I seem to remember "b v" only showed local branches, while "y" takes a couple of seconds to load and show all 900-odd remote branches in my repository. 

Is there a way to configure "y" to only show local branches? And how about maybe binding "b v" to that again?

**Comment by tuhdo** [comment]
The old `b v` did show remote branches. I was using it to checkout all the time.

**Comment by kyleam** [comment]
> Is there a way to configure "y" to only show local branches?

You can customize `magit-refs-sections-hook`.

**Comment by shreevatsa** [comment]
That worked (customizing `magit-refs-sections-hook`), thanks a lot.
