### ISSUE TITLE
Initial point in COMMIT_EDITMSG

### ISSUE THREAD

**Issue by purcell** [magit/magit#1954]
Hey Jonas, since Magit 2.1.0 I'm once again seeing the behaviour where the initial point in a fresh commit message buffer is not at the start of the buffer. Instead, the point is in the `#` comment text, presumably due to the point being restored from the last time a commit message was edited. IIRC this was due to something like `session.el`, and you did something to suppress it. Please correct me if I'm wrong!

**Comment by tarsius** [comment]
> IIRC this was due to something like session.el, and you did something to suppress it.

That is so, but that kludge was already remove two years ago, in a1448b2b694da588e945c43fde82e4f9fd4cbe0c.

I'm gonna move this package to the orphanage, adjust recipe, and fix the issue mentioned in that commit.

**Comment by tarsius** [comment]
Actually `session.el` seems to be maintained again and it was you who got the mentioned issue fixed: http://sourceforge.net/p/emacs-session/bugs/4/. But melpa still gets the package from the emacsmirror. Please fix that. And I should probably resume updating this package on the emacsmirror.

Unfortunately I cannot just revert 6a97ea0703438a7f8767180f298553a36930a74a, since `git-commit-mode` no longer is a major-mode.

**Comment by npostavs** [comment]
I recall something with `saveplace`, a search found magit/git-modes#31 which talks about `pointback`.

**Comment by tarsius** [comment]
> And I should probably resume updating this package on the emacsmirror.

It seems that upstream only provides a tarball but no repository. So melpa cannot get it directly. The emacsmirror also no longer supports importing from release tarballs (only single elisp files, with no version suffix). So the only way to get an up-to-date version into the emacsmirror and melpa is to convince upstream to provide a public repository. (Since sourceforge has turned evil, he should at the same time be convinced to move to e.g. github.)

**Comment by tarsius** [comment]
So @purcell probably has added something like https://github.com/magit/git-modes/issues/31#issuecomment-24477167 locally and it no longer works because `git-commit-mode` no longer is a major-mode. But the kludge can easily be adjusted.

And the FAQ entry about point issues is back on the table.

**Comment by purcell** [comment]
I actually don't have `pointback` or `saveplace` enabled these days, or any workaround as in the comment you linked to. It must be `session.el`, as you suggest.

> But melpa still gets [session.el] from the emacsmirror. Please fix that. And I should probably resume updating this package on the emacsmirror.

There's no VCS link on the sourceforge project page, so we can't build from there directly. :-(

**Comment by purcell** [comment]
I worked around this in https://github.com/purcell/emacs.d/commit/53da53df7f78a638b0162f40a06c4d921db55fd2, so feel free to close the issue and/or note it in the FAQ.

**Comment by tarsius** [comment]
> There's no VCS link on the sourceforge project page,

Yeah, I was hoping you (or someone else) could give the maintainer a nudge.

> note it in the FAQ.

I've added something.

**Comment by purcell** [comment]
I've emailed the `session.el` maintainer...
