### ISSUE TITLE
Can't install when `dash` is installed with `el-get

### ISSUE THREAD

**Issue by enzochiau** [magit/magit#1982]
`dash` is installed with `el-get` in my environment. It cause your package can't compile. 

    Compiling with-editor.el
    In toplevel form:
    with-editor.el:82:1:Error: Cannot open load file: No such file or directory, dash
    make: *** [with-editor.elc] Error 1

I have to change your `find` command to let search `dash` under `.emacs.d/el-get` directory with pattern as `.*/dash`.

Do you have plan to make it support to be installed by `el-get`?

**Comment by npostavs** [comment]
Please report el-get bugs in its [issue tracker][1]. Anyway, I will fix this in el-get.

[1]: https://github.com/dimitri/el-get/issues

**Comment by enzochiau** [comment]
@npostavs, I don't think this is `el-get` issue. Because when I clone this repo and run `make` manually, I will get that error too. Because it can't locate the `dash` package.

Anyway, that will be great if you could fix it in el-get.

**Comment by npostavs** [comment]
> I don't think this is el-get issue. Because when I clone this repo and run make manually, I will get that error too.

If you install magit via el-get as well, then it should work because it doesn't use the make file to compile the lisp files (only the documentation). If installing magit via el-get doesn't work, then open an el-get issue.

If you're installing dash via el-get and magit manually then you should just add a `config.mk` in the magit directory with contents `DASH_DIR = ~/.emacs.d/el-get/dash`.
