### ISSUE TITLE
This particular feature isn't documented

### ISSUE THREAD

**Issue by DamienCassou** [magit/magit#2000]
The (great) new Magit manual lacks a section explaining the new Todo list section of the status buffer. What can we do in this list? What does "gone" mean as a label for a commit in this list?

**Comment by tarsius** [comment]
> The (great) new Magit manual lacks a section explaining the new Todo list section of the status buffer. 

Yeah, I should document that.

Generally speaking, it lists the commits which still have to be applied and (but only in case of rebase because otherwise Git does not provide that information) the commits that have already been applied. Sometimes there are additional commits displayed "in between" these two parts, see below.

> What can we do in this list?

The main purpose is to inform you what has already happened and what still has to happen. Otherwise the commits in this list behave like any commit in a list of commits (e.g. in the "Unpulled commits" section or the log buffer). All commands that can do something with the commit at point can do it here too.

> What does "gone" mean as a label for a commit in this list?

"gone" means "this commit was in the original list of commits to be applied, and we don't know what has happened to it". That would usually happen if you stop at a commit and then amend to it. This changes the patch-id and you will see something like:

```
pick 4985cdc show meaningful errors when an ancient Git is used
gone 0d93588 silence byte-compiler
done f596235 silence byte-compiler
done e06b2cd show meaningful errors when an ancient Git is used
```

Note that that two commits with the message "silence byte-compiler" are displayed. The commit hash as well as the patch-id (a hash of just the changes but ignoring any metadata) differ, so Git/Magit can no longer know whether these commits are "pretty much the same commit". So there's now one commit which has disappeared and one new commit which has appeared "out of nowhere". The prefix of the second commit is displayed in blue because it is the current `HEAD` commit.

Yeah, it's a bit complicated and maybe confusing. But it's just *additional* information, you can ignore it, until I have fully documented this.

----

You should ask such questions on the Emacs Stackexchange site. But since this is issue #2000, I didn't want to reply with "take this elsewhere" :-)

**Comment by tarsius** [comment]
The issue title was way to generic, to the point that it wasn't true anymore :-)

**Comment by tarsius** [comment]
This is documented now.
