### ISSUE TITLE
magit-show-refs-popup does not show a popup?

### ISSUE THREAD

**Issue by bastianbeischer** [magit/magit#2018]
When pressing <kbd>y</kbd> a new buffer opens which contains the magit-refs buffer.

Shouldn't it open a popup which contains various options? Looking at the code I find this:

```
;;;###autoload (autoload 'magit-show-refs-popup "magit" nil t)
(magit-define-popup magit-show-refs-popup
  "Popup console for `magit-show-refs'."
  'magit-refs
  :man-page "git-branch"
  :switches '((?m "Merged to HEAD"            "--merged")
              (?M "Merged to master"          "--merged=master")
              (?n "Not merged to HEAD"        "--no-merged")
              (?N "Not merged to master"      "--no-merged=master"))
  :options  '((?c "Contains"   "--contains="  magit-read-branch-or-commit)
              (?m "Merged"     "--merged="    magit-read-branch-or-commit)
              (?n "Not merged" "--no-merged=" magit-read-branch-or-commit))
  :actions  '((?y "Show refs, comparing them with HEAD"
                  magit-show-refs-head)
              (?c "Show refs, comparing them with current branch"
                  magit-show-refs-current)
              (?o "Show refs, comparing them with other branch"
                  magit-show-refs))
  :default-action 'magit-show-refs-head
  :use-prefix 'popup)
```

**Comment by tarsius** [comment]
The last line can be read as "don't show a popup unless a prefix is used" the second to last indicates what happens if no prefix is use.

You can change such properties:

```lisp
(setq magit-show-refs-popup (plist-put magit-show-refs-popup :use-prefix nil))
```

**Comment by seh** [comment]
The documentation for the variable `magit-popup-use-prefix-argument` says that setting its value to `default` will present the popup, and use the default action if invoked with a prefix argument. The code snippet above shows that that variable isn't taken into account for `magit-show-refs-popup`. Why deviate from the documented behavior here?

**Comment by tarsius** [comment]
Ah yes, that should be mentioned in the docs of course.

**Comment by bastianbeischer** [comment]
BTW, how does one find out which action is the 'default action' in general for a popup? The only way I can see at the moment is reading the source?

**Comment by tarsius** [comment]
Yep. But if a the popup command itself is bound to `X` and in the popup `X` is bound to an action, then that's a strong indication that this action is the default. In most (all?) other popups which don't have such a binding, there's no default action.

I don't really think the default has to be visualized. It is mostly intended for cases such as `magit-refs-show-popup` where the default action is invoked by default, instead of the popup.

(And for people who think that the popups are stupid in the first place (they exist, but I hope they are getting fewer) and therefor set `magit-popup-use-prefix-argument` to `popup`. For everybody else `X X` isn't really much worse than `C-u X` - sure the popup buffer flashes up briefly, but buhu.)

**Comment by tarsius** [comment]
> that should be mentioned in the docs of course.

done

**Comment by tarsius** [comment]
> how does one find out which action is the 'default action' in general for a popup?

I'm considering adding an option to somehow highlight the default.

**Comment by tarsius** [comment]
It's now possible to make the default action bold, using:

```lisp
(button-type-put 'magit-popup-action-button 'format " %k %D")
```
