### ISSUE TITLE
Extracting magit-section to its own independent package

### ISSUE THREAD

**Issue by DamienCassou** [magit/magit#2055]
I'm trying to write an IDE and I thought Magit sections could be really useful. For example, a section could be a class and its methods could be subsections (that's not exactly how I want to do it, but you get the idea).

It would be nice to extract magit-section to its own package. If you agree, I can have a look at separating magit and section.

**Comment by tarsius** [comment]
:+1: (A more differentiated response will follow.)

**Comment by DamienCassou** [comment]
I had a detailed look at the magit-section implementation and extracting it will require:

1. renaming all variables and methods (e.g., `magit-section` to `section`) to remove the `magit` prefix (provided we call the new library `section`)
2. renaming some methods not having the `magit-section` prefix (e.g., `magit-insert-heading` -> `section-insert-heading`)
1. changing some default values of variables (e.g., `magit-section-highlight-hook` includes `magit-diff-highlight` by default). We might need 2 variables (one for section and one for magit)
3. reviewing the API regarding section insertion outside the execution of the root's `magit-insert-section` (e.g., `(let ((magit-insert-section--parent magit-root-section)) (magit-insert-section ...))` in `magit-process`)
4. refactoring some huge functions/macros (e.g., `magit-insert-section`)
4. writing automated tests for each feature
5. integrating `imenu` to facilitate navigation in sections

**Comment by tarsius** [comment]
Renaming the libraries and symbols can wait until later. We should first concentrate on packaging the library as a separate package, similar to how this is done for `magit-popup`. As you mentioned we have to do something about the hooks. Additionally the dependency on `magit-utils.el` has to be removed.

What other functions/macros functions do you consider huge in addition to `magit-insert-section`? I am against splitting up that macro for the sake of splitting it up. In the past the functionality provided by that macro was spread across various functions and macros, which lead to the very unfortunate result that these internal functions were used in various combinations which let to a lot of inconsistency (around `1.2`). Having just one big blob (and it's not really that big) at least has the advantage that it cannot be abused. I am not per se against splitting it up, but there has to a good reason to do it.

The current implementation was written with the assumption that all sections would be created at once and in order, and then not modified anymore. In process buffers we update existing sections and insert new sections at the end of the top section's children. But that is a hack and is buggy. Sometimes inserting a section ends up messing up the nesting. I suspect that's because text properties are not adjusted carefully enough when injecting new sections. I haven't fixed that yet because it is a heisenbug. I would like proper support for injecting and modifying sections and if that means that we need to split up `magit-insert-section`, then that's not a problem, but the reason to do it, which I insist on.

I welcome your intentions to work on this, but suggest you start by getting your hands dirty instead of renaming things. Finishing the decoupling of the library from the rest of Magit, fixing the injection bug and writing tests would be most useful at this point. Also you should start using the existing code in your package, and once you are ready to make that publicly available, then we can create a `magit-section` package.

I like the idea of using classes - that's something I wanted to do for a long time too. But for Magit itself `magit-section` works well enough for the time being. So such refactorings have to bring something to the table before they can be integrated into `master`. Also I am quite swamped right now, so I will be concentrating on other things for quite some time.

**Comment by tarsius** [comment]
Regarding the *later* label: feel free to get started with this now, but I don't have much time for it right now.

**Comment by tarsius** [comment]
Are you still interested in working on this at some point? Then we can reopen this, otherwise I just keep this on my in-mind todo-list of things that I indent to work on at some point in the future. (It has been on that list before you brought this up.)

**Comment by DamienCassou** [comment]
Yes I am. I'm on holidays though and will start working on it at the end of the month.

**Comment by DamienCassou** [comment]
@tarsius I'm sorry but I can't allocate time on that. I don't plan to implement the major mode I would like to work on because of other projects with more impact. As a result, extracting magit-section is not on my priority todo list anymore. I'm sorry because I really wanted to do it...

**Comment by tarsius** [comment]
@DamienCassou No worries, eventually I'll get to this myself. But I'll first focus on fixing known bugs and implementation wards before making the functionality available to other packages. There's a short note about this in the [roadmap](https://github.com/magit/magit/issues/2180), which will have to do for now.

**Comment by DamienCassou** [comment]
Thank you so much @tarsius!! Another gift to the Emacs community.

**Comment by tarsius** [comment]
You are welcome!
