### ISSUE TITLE
Staging / unstaging by selected region is confusing

### ISSUE THREAD

**Issue by kzar** [magit/magit#2063]
Hi again,

Apart from #2062 my only issue with "the big upgrade" to 2.1 has been that I now find it very confusing to partially stage / unstage a hunk by selecting a region.

I _think_ it works basically as before except now I can't see the region that I've selected. If so perhaps the region the user has selected should be highlighted in some visible way?

I might be wrong there, not sure but as this is something quite common it should be as intuitive as possible. Someone who doesn't understand the new model for how these hunks and cursors and regions work (me!) should still be able to highlight and stage a region.

Cheers, Dave.

**Comment by tarsius** [comment]
> If so perhaps the region the user has selected should be highlighted in some visible way?

You are likely using a theme which does only set the foreground color of hunk lines. But the background should also be set.

**Comment by tarsius** [comment]
The region isn't shown because what is being selected, using mark and point, is actually larger than the region. Say mark is in the middle of one line and ends at the very beginning of another line. In that case all changes on both of these lines, and of course all in between, are part of the "selected area", and `s` would stage all of that.

So that area, which is larger than the region, is being visualized instead of the region. This is done by removing the added/removed/contact background color of lines outside that area (which of course doesn't change anything if these lines don't have such a background color in the first place). Additionally there are thin lines shown right above and right below the selected area (but that doesn't work in a terminal).

**Comment by kzar** [comment]
Oh I see, hitting `C-SPACE` moves one horizontal bar and then I can move the cursor down to move the other horizontal bar before hitting `s` to stage. It's actually pretty easy in fairness, just quite different from what I was expected and hence my confusion!

Perhaps _also_ highlighting the region between the two horizontal bars would help to illustrate what is happening and avoid the confusion?

**Comment by tarsius** [comment]
> Perhaps also highlighting the region between the two horizontal bars would help to illustrate what is happening and avoid the confusion?

That would hide hunk refinements, so no.
