### ISSUE TITLE
2.1.0 makes it easy to push a topic branch to master by accident

### ISSUE THREAD

**Issue by greghendershott** [magit/magit#2076]
Maybe I'm an idiot but these changes discussed in #2009 seem really dangerous for people used to <2.1.0.

The very bad thing I just did:

- Use `b c` to create a topic branch based off master.
- Realize it didn't switch there automatically. Use `b v` to switch to `topic`.
- Make a commit.
- `P P` to push.

And guess what? **I've just pushed to fricking master.** Ouch.

Worse, still not noticing the remote was `master`, I did a `P -f P` to force-push an amended commit for a trivial mistake -- hey it's just a topic branch -- and have Travis CI to re-test.

**So I ended up force-pushing to master on a public project.** Ouch^2

[I switched back to master, and did a force push of _that_. Which hopefully resolved things, and hopefully no one tried to pull during the 10 minutes this was fubared.]

This is with `magit-version` `"20150713.2244"`

---

Again, maybe I am idiot but this seems like a pretty huge UX issue for people upgrading, especially as it results in a kind of data "loss" (or at least "mess-up-age" and embarrassment.)

Although this seems related to #2009 I think this specific scenario is worth calling out on its own.

**Comment by greghendershott** [comment]
In case it helps, here's the `*magit-process*` from what I did:

```
  0 git … branch --track travis-emacs-versions origin/master
Branch travis-emacs-versions set up to track remote branch master from origin.

  0 git … checkout travis-emacs-versions
Switched to branch 'travis-emacs-versions'
Your branch is up-to-date with 'origin/master'.

  0 git … apply --reverse -p0 --unidiff-zero --ignore-space-change -
  0 git … add -u -- .travis.yml
  0 git … commit --
Waiting for Emacs...
[travis-emacs-versions ef963f6] Test against Emacs 24.3 and Emacs snapshot
 1 file changed, 58 insertions(+), 37 deletions(-)
 rewrite .travis.yml (81%)

  0 git … push -v origin travis-emacs-versions:refs/heads/master
Pushing to git@github.com:greghendershott/racket-mode.git
Counting objects: 3, done.
Writing objects: 100% (3/3), 777 bytes | 0 bytes/s, done.
Total 3 (delta 1), reused 0 (delta 0)
To git@github.com:greghendershott/racket-mode.git
   bc3152a..ef963f6  travis-emacs-versions -> master
updating local tracking ref 'refs/remotes/origin/master'

  0 git … add -u -- .travis.yml
  0 git … add -u -- makefile
  0 git … commit --amend
Waiting for Emacs...
[travis-emacs-versions cd9680f] Test against Emacs 24.3 and Emacs snapshot
 Date: Wed Jul 15 08:48:48 2015 -0400
 2 files changed, 63 insertions(+), 40 deletions(-)
 rewrite .travis.yml (81%)

  0 git … push -v --force-with-lease origin travis-emacs-versions:refs/heads/master
Pushing to git@github.com:greghendershott/racket-mode.git
Counting objects: 4, done.
Writing objects: 100% (4/4), 921 bytes | 0 bytes/s, done.
Total 4 (delta 2), reused 0 (delta 0)
To git@github.com:greghendershott/racket-mode.git
   ef963f6..cd9680f  travis-emacs-versions -> master
updating local tracking ref 'refs/remotes/origin/master'
```

My cleanup:

```
  0 git … checkout master
Switched to branch 'master'
Your branch is behind 'origin/master' by 1 commit, and can be fast-forwarded.
  (use "git pull" to update your local branch)

  0 git … push -v --force-with-lease origin master:refs/heads/master
Pushing to git@github.com:greghendershott/racket-mode.git
Total 0 (delta 0), reused 0 (delta 0)
To git@github.com:greghendershott/racket-mode.git
   cd9680f..bc3152a  master -> master
updating local tracking ref 'refs/remotes/origin/master'
```

**Comment by greghendershott** [comment]
Maybe I should adopt the attitude that magit 2.1.0 is a completely new package and not assume anything about how it works.

In that spirit, I made a sandbox repo to play in. I need to experiment more. Meanwhile:

- IIUC this issue boils down to the fact that in `*magit-branch-popup*`, ` -t Set upstream configuration (--track)` is enabled by default. I think this should be disabled by default. That way, people won't accidentally create topic branches that will end up getting pushed to master.

- I'm no git god. I have a simple workflow. I use GitHub and Travis CI.  I very frequently create topic branches, and I want to push them -- to their _own_ branch! -- on GitHub and let Travis CI run. (Eventually I will merge most to master. Before I merge, I might do an interactive rebase, and force push that -- to its own branch! -- for Travis CI to check.)  That's about it.

  magit 1.x was really simple and fast for this workflow. magit 2.1.0 is (AFAICT) not. In fact it's a bit "dangerous" if people assume otherwise, like I did. 

  1. Changing the `--track` default would make it less "dangerous".

  2. Even with that change, it would still be less convenient (for this workflow). It would be great to have a `*magit-branch-popup*` "create branch" variant that does what magit 1.x did -- so that a simple `P P` later "does the right thing" (for this workflow). Is that possible?

  Now, as a human being, I naturally feel like my simple workflow is likely to be a common one. :)  So I'm probably biased. But seriously, I imagine a lot of magit users also have this sort of simple GitHub/Travis/push-topic-branch workflow. I don't know how many of those people have upgraded, yet, but when they do, I imagine this is going to come up frequently?  [And that's why I'm doing this as an Issue here, rather than support over on emacs SE.]

**Comment by greghendershott** [comment]
To follow-up:

- As I mentioned, I changed my own default -- by the way, the ability to do that is awesome! -- to have `--track` _disabled_ in the branch popup.
- I also changed the push popup to default `-u` _enabled_.
- With those changes, I'm prompted on the first push to provide the name. With completion, doing `origin/<topic-branch-name>` isn't too bad, once you understand that's what you need to do.

I think this is correct?  If so, it's only slightly less convenient than 1.x.  Which is fine for me, and I'm continuing to love magit.

**However** I would still suggest that  **the defaults should be changed**, to prevent grief among the remaining wave of people who will upgrade. (Sure, there could be a big fat warning about this, in the README and package blurb. But people updating packages from inside Emacs, are likely to miss that.)

**Comment by johnmastro** [comment]
For those following along at home, what code did you use to change the defaults as you described? I think the same changes would make sense for my workflow.

**Comment by greghendershott** [comment]
I used the UI:

- In magit-branch-popup, I typed <kbd>-t</kbd> disabling, then <kbd>C-c C-c</kbd> set defaults, and <kbd>C-x C-s</kbd>.
- In magit-push-popup, likewise <kbd>-u</kbd> enabling, then  <kbd>C-c C-c</kbd> set defaults, and <kbd>C-x C-s</kbd>.

This plops in your init.el:

```
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(magit-branch-arguments nil)
 '(magit-push-arguments (quote ("--set-upstream"))))
```

So I believe you could also just manually edit init.el to add:

```
(setq magit-branch-arguments nil)
(setq magit-push-arguments '("--set-upstream"))
```

In one of the usual places like a `use-package` `:config` or a magit-mode-hook,

**Comment by greghendershott** [comment]
For example with `use-package` I now have:

```cl
(use-package magit
  :ensure t
  :bind (("C-x g" . magit-status))
  :config (progn
            (setq magit-last-seen-setup-instructions "1.4.0")
            ;; The following two are critical for making magit 2.1.0 work more
            ;; like 1.x for me: WITHOUT these, creating a new topic branch
            ;; defaults its remote to master -- and pushing the topic branch
            ;; pushes to master (?!?). WITH these, you're prompted on the
            ;; first push, and need to supply origin/<topic-branch-name>, but
            ;; thereafter it's set and all is well.
            (setq magit-branch-arguments '()) ;do NOT want --track
            (setq magit-push-arguments '("--set-upstream")))) ;aka -u
```

**Comment by tarsius** [comment]
I want to avoid installing any emergency "fixes" at this point. This should also be confusing and potentially dangerous. Just to other users - those who have already adapted to the new ways of doing things. Also I have already installed some emergency changes, only to have them revert them, because it turned out I did not think them through enough. I have started toward "pushing like Git would" and the "publish remote" (see #2080).

Also note that just not setting `--track` is not enough to prevent the new branch from automatically tracking a remote branch it is created from:

```shell
$ git branch feature origin/master
Branch feature set up to track remote branch master from origin.
```

That's the default way of creating a branch with git. In magit it is `magit-branch`, which now used git's default way of creating a branch by default.

**Comment by tarsius** [comment]
Mentioning #1485, because the point raised here is yet another point I have to remember when tackling that.

**Comment by greghendershott** [comment]
I understand and agree that a rushed "fix" is a bad idea.

I think the need is explanation and documentation. magit 1.x users want to know how to do common tasks in 2.x and get the same result.

Actually, the first point is alerting them that they even _need_ to know something, at all. There will be people like me who don't realize how significantly magit has changed. Some will upgrade through MELPA, rely on muscle memory, and ... that may turn out badly.

And then the second thing is telling folks what they need to know.

I think it's great that magit 2.x aims to support more of git in all its complexity, and to do so with an overhauled code design. It's a good goal, and I'm sure you've had a vocal cohort of power users pushing for that.

At the same time, I imagine many, many magit users have a simple workflow like the one I described. What they already love about magit 1.x is how they can fly through these frequent steps, quickly. (If they need to hit the command line for something unusual, that's OK.)

If you want to keep those 1.x people from having some nasty surprises, and keep them still loving magit, I think you need to give them a better bridge and show them how to walk over it.

---

I realize you don't get paid nearly enough for working on magit, and I feel weird giving you advice. I would understand if you disagree with me. I would definitely understand if you don't like me right now.

I also feel like a schmuck because what I want to do, instead of writing this comment, is submit a PR giving you the very docs and README that I'm proposing. Don't talk about it, just do it. But I'm not able to, yet. For example, I think you're saying the config I'm using is still not 100% correct -- and I don't yet understand how/why. So for now I'm taking notes, trying to work out what I still need to learn about magit 2.x and/or git, and leaving you this comment. Sorry.

**Comment by tarsius** [comment]
Reopening for "op is making a real effort" :-)

**Comment by greghendershott** [comment]
Sorry!! I love magit. I've just seen too many 2.0 releases where average users are confused, the developers' hard work seems unappreciated, and everyone gets frustrated. I'm worried that might be in the wind here and want to help nip it in the bud.

AFAICT I'm 100% all set with magit 2.1.0 now. I've been using it on a variety of projects, with no surprises. Personally I have no complaint now.  I'm trying to figure out how to get other, future upgraders to that good point, faster and much less painfully than I did.

**Comment by Jell** [comment]
preamble: I've just upgrade to magit 2 and it's awesome! I'd just like to mention that like @greghendershott I use magit 99% of the time for a simple workflow, that looked like this with version 1.0:

- create a branch from master (get checked out after creation)
- small code change
- commit
- push with tracking
- make a PR on github
- repeat the above on average every hour

Now I also have to:
- checkout the branch I just created
- type the name of the remove branch I want to push to

I know this seems like nothing at all, but I'll be repeating that many times per day, and an error on either of these two steps is really annoying to correct.

In the philosophy of DWIM, I think defaulting the behaviour of 2.0 to that of 1.0 with regard to creating a branch and pushing to remote would be best.

But again, great work! I just tried out the new rebase mode, it's awesome!

**Comment by tarsius** [comment]
> Sorry!! I love magit.

Don't worry, it's all good.

> I've just seen too many 2.0 releases where average users are confused, the developers' hard work seems unappreciated, and everyone gets frustrated.

That's why I went straight to 2.1 :-) Seriously though, this is happening to some extend. The main areas where users seem to have issues with are branching, pushing, and "what happened to the region?".

> I'm trying to figure out how to get other, future upgraders to that good point, faster and much less painfully than I did.

The biggest problem is that most users won't even notice that they are installing a major update. I have put quite some work into the upgrade going smooth anyway. The only thing I could not automate away was the requirement to uninstall `git-{commit,rebase}-mode`. But maybe that's a good thing - it's a strong hint that something changed "in big ways". Not every user will then go check if she can find additional information but some might.

But many users, possibly most, won't see any of the provided update notes. So improving these notes is of limited use - not saying we shouldn't do, just that it won't prevent all potential misunderstandings and surprises due to changed behavior.

One thing I tried with the `1.4.0` release was to show a warning about an important change, in order to force users to think about it and then make a decision by editing a variable. I got *very negative* feedback about that.

I can do any of

1. Never make any changes which could take anyone by surprise
2. Force users to take note
3. Hope users notice
4. Hope users notice, but also try to increase the odds

(1) is out of question. I tried (2) but this attempt to protect users from surprising and potentially dangerous changes, was perceived as "needlessly making it harder for them". I think I am doing (4) and you are arguing for that, but there are limits to it. Without doing (2) there is no way everyone will notice when something changed.

So I think we should add something about these changes in the FAQ and mention that in the FAFAQ (the thing with the hands pointing at it).

----

Somewhere above you were surprised that simple not using `--track` is not enough. You have to additionally change the value of `branch.autoSetupMerge`. And yes, Magit should always respect that variable and allow overriding it, but that's not as simple as it might sound. *Especially* because that would once more require changing how certain commands behave.

**Comment by greghendershott** [comment]
> One thing I tried with the 1.4.0 release was to show a warning about an important change, in order to force users to think about it and then make a decision by editing a variable. I got very negative feedback about that.

I was about to suggest doing that again, for 2.1.0. Even if some people found that annoying for 1.4 (I didn't) it seems justified for a major version change where many basic operations have changed.

I mean, you're going to get negative feedback, either way. Such is your reward for spending so much time to give people a great tool. :)

---

> Somewhere above you were surprised that simple not using `--track` is not enough. You have to additionally change the value of `branch.autoSetupMerge`. And yes, Magit should always respect that variable and allow overriding it, but that's not as simple as it might sound. Especially because that would once more require changing how certain commands behave.

So I just checked the git-config man on `branch.autoSetupMerge`. IIUC what you describe is N/A for the (I think common) workflow where people create local topic branches, and only push them to GitHub -- but never fetch/pull them. So I think my config is OK for that workflow. Is that correct?

[I understand that `--track` might not be enough for other workflows, and you have to think about that, too. Here I'm just asking selfishly about my own workflow. :)]

---

It would be more convenient for me (and I think folks like @Jell and @johnmastro) if that first push -- where we're prompted to supply the remote name -- could default to `origin/<branch>`. We'd still need to press <kbd>RET</kbd>, but that's OK. Other people would have to type some other name, but that's OK, they already need to.

If that seems like a reasonable feature request, let me know if you'd prefer I create a new Issue for it?

Although I haven't looked at the code yet, maybe that's something where I could actually submit a PR to help.

**Comment by greghendershott** [comment]
@Jell 

> Now I also have to:
>
> -  checkout the branch I just created

You can use <kbd>b B</kbd> to create-and-checkout.

> -  type the name of the remove branch I want to push to

You can type <kbd>o</kbd> and <kbd>TAB</kbd> to complete that to `origin/`, then type your branch name (completion might help here, too). I'm finding that not too bad.  But in my comment just above I did ask if the name could default for us. If we just have to press <kbd>RET</kbd> to accept it, that's basically as convenient as 1.4 for me.

**Comment by Jell** [comment]
ah damn! I should have read the manual eh? sorry about that! +1 on the default name though!

**Comment by npostavs** [comment]
> If we just have to press RET to accept it, that's basically as convenient as 1.4 for me.

You can get that with ido completion. I started adding a default, so it would work with normal completion as well, but I got bogged down with `magit-push-read-args`, see https://github.com/magit/magit/issues/2009#issuecomment-119553054

**Comment by phil-s** [comment]
> I tried (2) but this attempt to protect users from surprising and potentially dangerous changes, was perceived as "needlessly making it harder for them".

FWIW I still think it was the best approach. I have a really hard time believing that the sub-set of users who are disgruntled by such an approach wouldn't get over it very quickly once they had followed the instructions and customized the appropriate variable(s).

**Comment by tarsius** [comment]
Users now have to opt-in to the new behavior.

**Comment by tarsius** [comment]
> Personally I still think that's the best approach for those kinds of changes. You can't make everyone happy, but I just have a hard time believing that the sub-set of users who are disgruntled by such an approach wouldn't get over it very quickly once they had followed the instructions and customized the appropriate variable(s), if they knew that "this is the way it's going to be".

As much as I wish this would be true, and as much as I agree that it is more important to provide a safety net for users who missed that the push behavior has changed in backward-incompatible ways, I hesitated to make this change, because I *knew* I would be attacked and insulted for doing so.

Some of you probably thought I was exaggerating. Well, here is the first instance of exactly that happening ("thanks" to the *creativecommits* twitter spam bot):

> @lunaryorn said in https://github.com/lunaryorn/.emacs.d/commit/b674d8d904d622959f26645367f4462cc4c1e23d : Fuck you Magit, can you never be silent?

Obviously he did not read, or worse choose to ignore, this part of `magit-push-always-verify`s doc-string:

> This has taken a few users by surprise, and they suggested that
> we force users to opt-in to this behavior.  Unfortunately adding
> this option means that now other users will complain about us
> needlessly forcing them to set an option.  But what can you do?
> **(I am not making this up.  This has happened in the past and it
> is very frustrating.)**

@syl20bnr @bbatsov @purcell @eschulte and other maintainers of starter-kits: Sooner or later some user will probably come along and ask you to add this to your starter-kit:

```lisp
(setq magit-push-always-verify nil)
```

**Please don't to that.** The purpose of this option is to protect users from shooting themselves in the foot. Adding this setting to a starter-kit goes completely against that intention.

People like @lunaryorn will attack me because I am forcing them to set an option, and maybe some of them will even attack you, for refusing to set the option for everyone, so that they don't have to do it themselves.

Users who attack me for -- oh the horror -- forcing them to set an option are irrational and either don't care for the needs of less experienced users or have difficulties imagining what it is like to be in their shoes. Except in this particular case (because it comes from a prominent community member) it is easier to ignore such attacks than the justified criticism by users who managed to shoot themselves in the foot, because of the changes I have made to the pushing commands.

Above you find reports from users who have unintentionally pushed to master, and they take part of the blame. Other users might be less forgiving and blame it all on me. While I don't think that doing so would be fair, I would take that much more to heart, than the egoistic and shortsighted complain about having to set an option.

---

This is one of those situations where whatever I do, someone will think I have picked the wrong option. This is the most frustrating part of maintaining Magit; whatever you do and how much you try to come up with compromises that take the diverse and often mutually exclusive needs and opinions of all users into account, there's always someone who has nothing but his own interest in mind, and however small the inconvenience of not going with what is exactly right for him might be, take that as a reason to attack and insult.

**Comment by tarsius** [comment]
Okay. Probably should not have mixed these two things, which boil down to:

1. If there is an option whose raison d'etre is that users make an informed decision, then please don't override my decision to force users to do so in your starter kit. I usually only add such opt-in switches after the new behavior has proven to be problematic for some and I have been asked to add a safety net.

2. If something isn't like you think it should be and that annoys you, then maybe it is the way it is because others have different needs. I am sitting in the middle in between users with opposing view points, and they all talk to me, not each other. That's no fun. So when you use strong language to criticize my decision to help another group of users and cause you some minor inconvenience, then I might at times get frustrated and snap at you.

**Comment by syl20bnr** [comment]
I take note of this I will try to remember to not touch this variable. I doubt that Spacemacs users will find the default behavior annoying, it brings just a helm popup so validating the selected entry is quick.

> One thing I tried with the 1.4.0 release was to show a warning about an important change, in order to force users to think about it and then make a decision by editing a variable. I got very negative feedback about that.

I do exactly that in Spacemacs where important breaking changes are displayed on the welcome screen, people can toggle it on and off in a persistent way but any new install of Spacemacs will show these notes again. This is no different that what you did in 1.4.0, better than this, you gave me the idea to do it for Spacemacs. I saw this 1.4.0 release note as something smart that other maintainers should try to do if they can. FWIW I don't get any negative feedback yet on the important release notes displayed on the welcome screen.

**Comment by davidw** [comment]
FWIW, I'm much more bothered by accidentally pushing to master than by any sort of popup or reminder or something pointing out that the behavior has changed radically.  Luckily in my case it was not a major problem, but that'll likely happen to someone sooner or later.

**Comment by davidw** [comment]
Here's a random idea: magit could highlight, in the regular magit status buffer, differences between the Head: and Upstream: names.  I suppose that could annoy people who often use different names, but it'd be an extra warning for the rest of us who normally mirror the name.
