### ISSUE TITLE
Add a template for new issues to CONTRIBUTING.md ?

### ISSUE THREAD

**Issue by phil-s** [magit/magit#2086]
I imagine this would be helpful in obtaining key information from users (such as Magit, Emacs, and Git version details) when they are submitting a new issue. This seems especially pertinent now that Magit 2 is released.

As I understand it, CONTRIBUTING.md is the closest thing in Github to providing any kind of issue template, so I'm just envisioning some content that users could copy & paste into the issue textarea, and then edit in the appropriate values.

(I did notice https://github.com/kentcdodds/issue-template but I don't know how that's supposed to work. It says it was written for the AngularJS project, but https://github.com/angular/angular.js/issues/new doesn't present any kind of template, so that's not a ringing endorsement.)

**Comment by tarsius** [comment]
Unfortunately, I am under the impression that this won't make a big difference, if any. I mean, I have just recently added a "frequently asked, frequently asked questions" thingy to the readme and wiki front page. With two hands pointing to it... Many users just don't read instructions.

I think the only technical solution to this issue would be if Github allowed developers to style the note which asks users to read the contribution guidelines before they open a new issue. Currently it pretty much looks like this:

> Please review the [**guidelines for contributing**](https://github.com/magit/magit/blob/master/CONTRIBUTING.md) to this repository.

Sure the background is a light yellow and the link is bold, but that simply ain't enough to get the attention of many users. If I could, then I would add geocity-style animated rainbow lines, pointing fingers, and dancing babies around that box.

----

You also seem to imply that users should be instructed to report what versions they are using. That request is indeed missing from the instructions and *maybe* it should be added. But I have a feeling that those users who would read the instructions do mention the used version when appropriate, even when not told to do so. While the behavior of users who don't read instructions are not affected by instructions they haven't read.

Also I think that I am usually quite good at spotting when a user is talking about some old version. A bigger problem is when I explicitly ask about it and then get an incorrect answer. We had a similar problem after starting to involve the Emacsclient in the committing process. I ended up (sadly much to late) writing a debugging function (`with-editor-debug`) which answered my questions, so that I did not have to rely on answers which were not actually verified by the user providing them.

I tried something similar with `magit-version` but it isn't working so well. So far I have received more bug reports *concerning that function*, than the function helped my address. The latest example of that is #2070. I think that in order for this function to actually help me, instead of causing me *more* work, I have replace the message "Cannot determine Magit's version" with a message buffer, which reports information similar to what `with-editor-debug` provides. Of course the code above is also rather wacky, but I hesitate to change it, just to make it prettier.

**Comment by tarsius** [comment]
Oh, and off-topic (but not entirely!): please add an entry to Magit's `.mailmap` to substitute your real name and email for `phil-s <phil-s@users.noreply.github.com>`. You might also want to update your user metadata on Github, so that this sort of thing does not happen anymore:

```
$ git show --format=full be86f0de65a316ceabd953eca18e82831b9cae65
commit be86f0de65a316ceabd953eca18e82831b9cae65
Author: phil-s <phil-s@users.noreply.github.com>
Commit: phil-s <phil-s@users.noreply.github.com>

    magit-rebase-unpushed: start from merge-base
    
    Replica of the magit-rebase-autosquash fix from commit
    f1afebf6b6e6128c701f87f6bfa3d9ffca938de3. See #2011.

diff --git a/lisp/magit-sequence.el b/lisp/magit-sequence.el
index 42f0caa..0b608cf 100644
--- a/lisp/magit-sequence.el
+++ b/lisp/magit-sequence.el
@@ -360,7 +360,8 @@ (defun magit-rebase-interactive (commit &optional args)
 (defun magit-rebase-unpushed (commit &optional args)
   "Start an interactive rebase sequence of all unpushed commits.
 \n(git rebase -i UPSTREAM [ARGS])"
-  (interactive (list (magit-get-tracked-branch)
+  (interactive (list (--when-let (magit-get-tracked-branch)
+                       (magit-git-string "merge-base" it "HEAD")) 
                      (magit-rebase-arguments)))
   (if (setq commit (magit-rebase-interactive-assert commit))
       (magit-run-git-sequencer "rebase" "-i" commit args)
```

Uuhh, and I just noticed that change added trailing whitespace too :-/

**Comment by phil-s** [comment]
Ack. Sorry about that. I briefly wondered how on earth that happened, as I have trailing whitespace highlighted by default for all programming modes. Then I realised that I had created that patch directly in Github's web UI, not through Emacs, as that seemed like a time-saver at the time for a trivial little copy/paste job :(

**Comment by npostavs** [comment]
> Sure the background is a light yellow and the link is bold, but that simply ain't enough to get the attention of many users.

See also, https://en.wikipedia.org/wiki/Banner_blindness

**Comment by tarsius** [comment]
So uuhm. Thanks for the suggestion, but I am keeping this as is, at least for now. Closing, but feel free to comment more.

**Comment by phil-s** [comment]
That's fine; I just wanted to ensure you'd considered it, in case was going to help.

The only thing I'll add is that even if you're confident that you can determine and remember which version(s) an issue pertains to, other people do not have that same ability, and sometimes it's helpful for people who are reviewing existing issues (to see whether their own problem has already been described and/or resolved) to know whether or not a given issue is likely to be relevant to them.

I figure that encouraging people to include version details would be useful from that perspective, even if you're less concerned about it yourself.
