### ISSUE TITLE
"reword" keybinding mismatch

### ISSUE THREAD

**Issue by mgalgs** [magit/magit#2087]
During interactive rebasing, `r` is used to request a reword of a commit.

In the committing popup, it's `w`.

In old magit it was `r` everywhere.  Maybe we should just move it back to `r` in the committing popup for the sake of consistency?  I know I've fumbled a few times trying to remember which key it's on in which mode...

**Comment by npostavs** [comment]
Or change the rebase reword to `w` as well? I seem to recall there was some conflict with using `r` for reword, but I can't remember what it was.

**Comment by tarsius** [comment]
There are *three* places where a "reword" command is available the committing popup and the rebase-file buffer, which you mentioned, and additionally the *rebasing popup*. In that last popup `r` is already used for something else: regular rebase. I want to keep that binding.

We could however bind `w` in the rebase-file buffer too, in addition to `r`. However should remain the advertised key binding, because without the help of `git-rebase.el` one would just edit the file using generic file editing commands, and replace the first word, which constitutes the command, with another command. In this case pick => reword. Git also understands one character abbreviations of these commands, in the case of "reword" that is "r". That's why I want to keep that binding as the default here. 

So in addition to binding an additional key, we also have to set the commands `:advertised-binding` property. Finally `git-rebase-mode-show-keybindings` has to show the bindings actually in use (possibly after further user customization) by using `\[COMMAND]`. These things are documented in `(elisp)Keys in Documentation`.

Who would like to make these changes?

**Comment by tarsius** [comment]
I have added an label `easy` for feature requests which would easily be implemented by people who would like to get started contributing to Magit.

**Comment by mgalgs** [comment]
Part of #2093.  Also added the keybinding to the help comments in the rebase mode buffer.
