### ISSUE TITLE
behavior of magit-mode-bury-buffer

### ISSUE THREAD

**Issue by holomorph** [magit/magit#2096]
Just a heads up for some behavior I noticed when trying to solve a similar problem in an interface of my own <https://github.com/holomorph/transmission>.  Because `magit-mode-bury-buffer` stores and restores the window configuration: making changes to the window configuration, then doing "q" in the magit status buffer will destroy those intermediate changes to the window configuration.  For example:

1. `M-x magit-status RET`
2. Go back to the other window (`C-x o`)
3. Split it (`C-x 3` or similar)
4. Go back to the magit buffer (`M-2 C-x o`)
5. Quit magit `q`.

Only one window remains, when the two from the split should be there, IMO.  I found this behavior undesirable, so I sought another solution. This is the code I ended up writing to delete the window if the bringing up the buffer created the window, otherwise just to bury it.

``` elisp
(defun transmission-quit ()
  "Quit and bury the buffer."
  (interactive)
  (let ((buffer (current-buffer)))
    (if (seq-filter (lambda (b) (not (eq buffer b)))
                    (mapcar #'car (window-prev-buffers))
        (quit-window)
      (if (one-window-p)
          (bury-buffer)
        (delete-window)))))
```

**Comment by johnmastro** [comment]
Setting `magit-restore-window-configuration` to `nil` may also do the trick

**Comment by tarsius** [comment]
Is this a workaround for what Magit does (in which case just doing what @johnmastro suggested, should work too) or is this a suggestion for a similar feature intended to replace the current mechanism of saving and restoring the window configuration?

**Comment by holomorph** [comment]
Just a similar feature, without the behavior I described. Setting `magit-restore-window-configuration` to `nil` just reduces the function to `(quit-window)`, which is too simple.

**Comment by holomorph** [comment]
For funsies I've monkeypatched `magit-mode-bury-buffer` to test how my code gets along with magit (except with `cl-lib` instead of `seq`).

**Comment by tarsius** [comment]
@holomorph Actually I strongly agree with you that the current behavior is to aggressive.

When the "restore previous winconf on bury" functionality was originally suggested I had very strong reservations, but the author of the original implementation was very persistent about it being right for everyone, always. So I gave in but made it optional. Then users started turning it on and I had to do the same to be able to fix the numerous bugs.

Once I had fixed the bugs I kept it turned on as I kind of liked it by then. Probably Stockholm syndrome. But lately it has gotten on my nerves.

I probably won't be able to remove the winconf stuff completely, but I intend to implement something similar to what you are suggesting and making that the default. For now I have only begun factoring out the winconf stuff.

> For funsies I've monkeypatched magit-mode-bury-buffer

It's probably best you do that using `fset` instead of using an advise. I intend to add a variable `magit-quit-window-function`, but I am not sure yet about the name, so I am delaying that.

**Comment by holomorph** [comment]
Nice!
> I probably won't be able to remove the winconf stuff completely, but I intend to implement something similar to what you are suggesting and making that the default. For now I have only begun factoring out the winconf stuff.

Yeah, some degree of keeping track of what buffers magit is creating with the winconf or similar will be needed. Using my implementation (now with `fset`!) has made it clear why the current winconf was in place (so magit could clean up all the windows/buffers it's making; e.g. from status to navigating a log), and that what I wrote is a bit too simple for magit, as I only am operating in one window with transmission.el.

**Comment by tarsius** [comment]
I have just pushed my implementation to #2193. Along with other feature branches it is available from `pu`. Please give it a try, it might still need some fine-tuning.
