### ISSUE TITLE
magit-show-commit quite slow on certain repositories/commits

### ISSUE THREAD

**Issue by catern** [magit/magit#2097]
Using a clone of Linux and running M-x magit-log master, moving between commits so that they show in an adjacent window is quite slow. It takes 5-10 seconds to show each one, during which time Emacs is unresponsive. On smaller repos, and even some larger ones, showing the commits is much faster. A clone of git only takes half a second to a second, and smaller repos are instant.

magit is byte-compiled and I'm using magit 2.1 (20150707.544 from MELPA).

**Comment by johnmastro** [comment]
Related to #1425

**Comment by npostavs** [comment]
Sounds like it's the diff display that's slow, not the graphing in particular so it's more related to #1947 and #2048. Is it also slow on to show small commits in the large repo?

**Comment by catern** [comment]
Diff display is slow for any commit at all.

**Comment by phil-s** [comment]
FYI I just cloned the Linux repository from https://github.com/torvalds/linux and tried this for myself using Magit 2.1.0-72-g36b32e4-dirty, Git 2.3.5, Emacs 24.5.1 (and with an otherwise bare Emacs config, to get default performance behaviour). This version of magit is about a week and a half old, from Git.

Opening the log buffer was fairly slow (4 seconds), but once open, and with a diff in the other window, moving between log entries with `n` and `p` (with the other window being updated each time) is taking just over half a second (0.56).

So not the speediest; but dramatically better than catern is experiencing. My system specs (below) are good, but I would not expect them to be responsible for such a discrepency.

System specs:
Intel Core i7 CPU 870 @ 2.93GHz × 8
8G RAM
Kernel Linux 3.2.0-65-generic
Ubuntu 12.04 (precise) 64-bit

**Comment by catern** [comment]
phil-s <notifications@github.com> writes:

> FYI I just cloned the Linux repository from https://github.com/torvalds/linux and tried this for myself using Magit 2.1.0-72-g36b32e4-dirty, Git 2.3.5, Emacs 24.5.1 (and with an otherwise bare Emacs config, to get default performance behaviour). This version of magit is about a week and a half old, from Git.
>
> Opening the log buffer was fairly slow (4 seconds), but once open, and with a diff in the other window, moving between log entries with `n` and `p` (with the other window being updated each time) is taking just over half a second (0.56).

That is good news; I'll try out a similar test as well when I get a
chance.

**Comment by tarsius** [comment]
> This version of magit is a couple of days younger than yours

What I have changed, is that when you hold `n` or `p`, then not every commit along the way is "shown" (not actually visible to the user, as redisplay does not happen until later) and then immediately replaced with another commit.

This does however come at a cost. Emacs does not support key down events, and there is no way of knowing whether a user just quickly types a key or holds it down. So we have to use a timer. This timer also has an effect when just quickly typing `n` or `p`, and defaults to 0.2 seconds. See 106e195e04576c3ce8f868a2fd48af48ad11fc49.

> Opening the log buffer was fairly slow (4 seconds),

FWIW that's Git's mistake. There's a constant overhead when showing a log with graphs, which does not depend on how many commits are actually shown, but how many are reachable. In the Linux repositories that are quite a few :)

**Comment by tarsius** [comment]
I am closing this because:

1. "Moving around in log buffer (which updates the diff buffer) is slow" has been addressed.
2. There is nothing Magit can do about drawing graphs - at least nothing that hasn't been done already:

   * `--graph` comes with a overhead which does not depend on how many commits are shown but how many commits are reachable.

   * `--color --graph` is even slower because the code from Emacs which we use to control sequences into faces is slow. This has been addressed by adding `--color` to the log popups and not enabling it by default. (I will also add a note about this in the manual.)

Also see http://magit.vc/manual/magit/Performance.html.

**Comment by tarsius** [comment]
Ps: I have updated the manual with a note about these things and will push that in an hour or so.
