### ISSUE TITLE
architectural suggestion: create diffs on demand

### ISSUE THREAD

**Issue by jsyjr** [magit/magit#2105]
Two events recently have caused me to wonder whether a big part of magit's performance problem is caching diffs:

* Recently I was looking at a diff in a magit-status buffer showing an unstaged change that was nothing more than corrupted indentation.  I collapsed the diff, editted the file, returned to the status buffer, re-expanded the diff and saw that magit's diff did not yet reflect my edit.  (Note to self: mental model must include the fact that magit caches diffs; I am responsible for refreshing that cache.)
* Issue [2048](https://github.com/magit/magit/issues/2048) can be read as a discussion of the cost of eagerly filling that cache of diffs.

Part of what makes command-line git's status so much faster than magit-status is that git only attempts to determine which files have changed, not the individual diffs.  Magit could do much the same, only holding on to diffs while they are expanded, discarding them when they get collapsed and re-computing them when next expanded.  This would have at least the following benefits:

* It would overcome my minor initial surprise at having to internalize magit's caching.
* It probably would improve the performance of bring up a magit-status buffer in a large repository with lots of changes.

**Comment by tarsius** [comment]
Diffs are *not* being "cached". Every time a buffer containing diffs is refreshed, the diffs are recreated from scratch. In the long run I would like to avoid the latter, but probably not by using a cache. Instead we should selectively refresh only the parts of the buffer which should possibly need refreshing, not blindly everything.

> Recently I was looking at a diff in a magit-status buffer showing an unstaged change that was nothing more than corrupted indentation.

If I understand this correctly the thing that was corrupted was the actual file, not how it was displayed in the magit status buffer. In that case, instead of manually removing the faulty changes by editing the file manually, you should just discard them from the status buffer using `k`.

> the fact that magit caches diffs; I am responsible for refreshing that cache.

It doesn't cache anything. What it does is to *not* automatically refresh the magit buffers when a buffer visiting a file in the same repository is saved to the visited file. In the future once refreshing has gotten a lot smarter, as described above, we might do that. For now it is way to costly.

> Issue 2048 can be read as a discussion of the cost of eagerly filling that cache of diffs.

`s/cache/parse and paint before visible/`

We already avoid part of the work that is required to display a diff until its body actually becomes visible. We could and should delay work until really needed. I have already said that at the end of #2048.

> Magit could do much the same, only holding on to diffs while they are expanded, discarding them when they get collapsed and re-computing them when next expanded.

Discarding them means we have to later recreate them even if nothing changed. For the time being the best we can do is the initial parsing until actually needed.

> It would overcome my minor initial surprise at having to internalize magit's caching.

What you call caching (and I call "refreshing at certain points in time" (after running a magit command in the buffer)), is what we have been doing for the last five years. I agree that we can do better, but this is a large project for a variety of reasons.

**Comment by jsyjr** [comment]
Hi Jonas,

I am delighted with magit!  I do hope that you receive my contribution as a
token of my gratitude.

IIUC currently the magit-status buffer contains all possible display text,
some of which is hidden.  In particular this means that diffs for all
listed files get performed before the buffer becomes fully operational.
This is costly if there are many files, and all the more so the fewer diffs
a user chooses to expand.  Once you implement more automated refreshing any
up-front work spent computing a hidden diff that later gets refreshed prior
to ever being displayed is totally wasted.

If instead a magit-status buffer allowed lazy computation of a file's diff
then the logic at the time of displaying that diff could be something like:

   - if a diff is present but out of date then drop it from the buffer
   - if no diff is present evaluate it and insert it into the buffer
   - display the diff

In this model a magit-status buffer becomes a scaffold to which diffs get
attached on demand.

/john

**Comment by tarsius** [comment]
I am closing this, not because I have already implemented it or decided that I won't, but because this is already covered in the Roadmap issue (#2180), which continues to link back here, even now that it is closed.

And admittedly I also don't really want to discuss this in depth before I am actually ready to tackle it (i.e. when I am done with other things (again see the roadmap).

**Comment by jsyjr** [comment]
Makes sense to me.
