### ISSUE TITLE
Rebasing against root commit fails

### ISSUE THREAD

**Issue by bo0ts** [magit/magit#2126]
When trying to rebase against the root commit with magit the following error is produced in the `magit-process`:

> 1 git … rebase -i 10ee808^
> fatal: Needed a single revision
> invalid upstream 10ee808^

To reproduce:

    mkdir -p /tmp/foo && cd /tmp/foo
    git init
    echo "Bla" > foo1.txt
    git add foo.txt && git commit -m "foo1"
    echo "Bla" > foo1.txt
    git commit -a -m "foo2"
    # Now try to interactively rebase foo2 on foo1 in magit

To rebase against against the root commit of a repository it is necessary to use:

    git rebase [-i] --root $tip

This feature has been introduced in [git 1.7.12](https://raw.githubusercontent.com/git/git/master/Documentation/RelNotes/1.7.12.txt). Magit should try to recognize this situation and do the right thing.

**Comment by Silex** [comment]
IMHO it'd be better to have `--root` as an option in the rebase popup.

**Comment by bo0ts** [comment]
@Silex Totally fine with me.

**Comment by tarsius** [comment]
I have started working on this. Because this has quite a few prerequisite this won't make it into v2.2.0.

> IMHO it'd be better to have `--root` as an option in the rebase popup.

I have chosen to automatically use the `--root` argument when necessary for two reasons. It's actually easier to do it that way because we have to cannot just add that argument, we also have to drop UPSTREAM. And we already use different semantics than Git itself. The first commit Git rebases is the one *after* the one selected by the user, but Magit starts with the commit selected by the user (by passing `SELECTED^` to `git rebase`. Adding the `--root` argument instead of appending "^" to the commit, when the commit is a root commit, is a logical extension of that.

**Comment by tarsius** [comment]
Implemented in #2187. This branch has been merged into `pu` and will be merged into `master` before `v2.3` is released.
