### ISSUE TITLE
RFE: support --no-merges when running git log

### ISSUE THREAD

**Issue by jsynacek** [magit/magit#2137]
Git repos that have pull-request-based workflows have a lot of merge commits that make viewing the commit log hard. Git-log has --no-merge options for this and it would be great to support it directly in magit.

**Comment by tarsius** [comment]
See #2141.

**Comment by nshi** [comment]
After evaluating the following statement, `l -m l` shows `(empty)` in the log view.

```elisp
(magit-define-popup-switch 'magit-log-popup
                           ?m "Omit merge commits" "--no-merge")
```

**Comment by npostavs** [comment]
It's `--no-mergeS`:
```elisp
(magit-define-popup-switch 'magit-log-popup
                           ?m "Omit merge commits" "--no-merges")
```

**Comment by tarsius** [comment]
fixed the wiki page

**Comment by dankessler** [comment]
This is my top google hit for `magit log --no-merges`, so for anyone who comes along later (perhaps including me if I forget), the answers above are no longer relevant and most of the links are dead (presumably due to `magit-popup` being superseded by `transient`.

The good news is that `--no-merges` [*is* available](https://github.com/magit/magit/blob/28bcd29db547ab73002fb81b05579e4a2e90f048/lisp/magit-log.el#L448) from the `magit-log` transient, but by default it's hidden away.

Here's the TLDR version:
1. bring up magit log transient (e.g., with `M-x magit-log RET`)
2. `C-x a` will show suffixes (including infixes) at *all* levels
3. `=m` will toggle `--no-merges`

 For more info, see this [SE answer](https://emacs.stackexchange.com/questions/66160/log-with-first-parent-option) RE `--first-parent`, but the same approach will expose `--no-merges`.
