### ISSUE TITLE
No margin in magit status buffer

### ISSUE THREAD

**Issue by jaroslawr** [magit/magit#2160]
To make the issue clearly visible, execute:

```lisp
(setq-default left-margin-width 10 right-margin-width 10)
```

Every new buffer will now have a huge margin, except the magit status buffer right after executing (magit-status), where the text nearly overlaps the edge of the screen, or the scrollbar of the neighbouring window. Surprisingly, if you switch from the status buffer to another buffer, and then back to the status buffer, the margin is shown correctly.

**Comment by tarsius** [comment]
> Surprisingly, if you switch from the status buffer to another buffer, and then back to the status buffer, the margin is shown correctly.

The same happened to me for other buffers including Dired buffers and file-visiting buffers. Without diving any further into this I think the problem is that one is not supposed to set the global value of these variables but instead has to set it for each window individually. I come to that conclusion because the doc-string of `left-margin-width` contains "Automatically becomes buffer-local when set.". Please read the respective parts of the elisp manual to figure out whether this is supposed to work.

**Comment by jaroslawr** [comment]
@tarsius setq-default is the standard approach for defining default values for those automatically-buffer-local variables, from the Elisp manual:
> (setq-default [VAR VALUE]...)
> Set the default value of variable VAR to VALUE.
> [...]
> The default value of a variable is seen in buffers that do not have their own values for the variable.
It works for me just fine both with dired and with magit 1.4.0.

**Comment by tarsius** [comment]
Yes, that's how variables work, but these are special variables with are treated in a special way. I couldn't find documentation that explicitly sais "don't rely on setting the global value" but everything indicates that this is what you are supposed to work.

The node "Displaying in the Margins" also contains this:

> Setting these variables does not immediately affect the window.
> These variables are checked when a new buffer is displayed in the
> window.  Thus, you can make changes take effect by calling
> `set-window-buffer`.

But note that Magit uses the margin to display information related to the commit on the same line. That's what margins are intended for: displaying related information. You appear to want to use it to reimplement the whiteroom and similar package (you might want to just use one of those instead). That is fine, but since you want to use this for an unintended purpose you will run into issue and it is your job what the issues are and implement a workaround. Once you have done that I might merge it.

**Comment by jaroslawr** [comment]
@tarsius I am sure nothing in the Emacs manual explicitly prohibits doing what Magit currently does, I just think it isn't very standard, I used dozens of different Emacs packages and I have never run into one that would do this. I attach a screenshot to make the issue more clear:

http://i.imgur.com/NOcR2Eu.png?1

I am in fact using this feature for its intended purpose: to have blank margins around the main text of all my buffers, the manual says:

> A buffer can have blank areas called display margins on the left and on the right. 

The value of 10 was just a bold example, the main issue is just that currently the text in the magit status and magit log buffers nearly overlaps user interface elements which looks strange. All other modes I used so far respect this setting, one example is dired as shown in the screenshot. I also do not know of any other way to have padding around the text in the buffer.

I think the feature of displaying things in the margin was meant for things like line numbers, or breakpoint indicators for debuggers, not for putting large amounts of text in it. For example, Emacs standard vc-annotate which implements a similar display of content in columns does not use the margin for this. Anyway, YMMV.

**Comment by tarsius** [comment]
> All other modes I used so far respect this setting, 

That's because these modes do not already use the margin for their own purposes. You are therefore free to use it for your purpose. Magit and other packages do use the margin for their own purposes and when you then try to use them for something else there, then there will be a conflict.

The point I was trying to make is that it should be you who figures out how to resolve that conflict and provided some pointers. To be more explicit: `magit-set-buffer-margin` already makes a very rudimentary attempt to avoid a conflict, it tries to leave the left margin alone because it doesn't use that itself. However the right margin it overrides completely, disregarding anything that has been set by something else. That's the first thing you have to "fix", you have to make that function aware of your other use of the margin.

Then you have to figure out whether setting the default values of `left-margin-width` and `right-margin-width` really is supposed to work. I very strongly doubt that, because the margins are a window local settings (not buffer local variables). This is implemented in C and I doubt that Emacs mirrors changes to the global values of these variables. You are much better of using the functions `set-window-margins` and `window-margins`.

You say that your settings are honored by buffers whose major-mode isn't some magit mode. Even though that's not what happened when I tried it, I believe you. I think that it depends on  circumstances whether this works (most importantly whether that window previously displayed another buffer and already displayed the margins then). Because window margins are local to windows these other modes appear to respect the global setting because "something" "somehow" triggered the local values to be set based on the global values. In the case of Magit this does not work because it explicitly set's it's own values.

Which brings me to the last point: there might be places in Magit besides `magit-set-buffer-margin` that make changes to the margins. You have to find and adjust those too.
