### ISSUE TITLE
Interactive rebase onto a different branch in 2.1

### ISSUE THREAD

**Issue by rgarcia** [magit/magit#2163]
Is this still possible in magit 2.1? I just upgraded and can't figure out how to do this. Things I've tried:

* `C-u` before invoking `r e`
* moving cursor over other branch before invoking `r e`

My use case is rebasing a feature branch onto master before merging, which is a pretty common git flow.

**Comment by npostavs** [comment]
You can non-interactively rebase onto a different branch `r r`, and interactive rebase on the unmerged commits after `r e` and select, or possibly `r l` (`magit-rebase-unpushed`). See: #1829.

**Comment by aspiers** [comment]
What if you already know that the rebase will cause conflicts and that you can avoid those by editing or dropping certain commits during the rebase?  Or if you simply want to drop some commits as part of the rebase onto the other branch?  It seems like a regression to force the user to have to do this in two steps.  Or am I missing something?

BTW I hope I don't sound ungrateful here.  2.1.0 is a stunningly cool, quantum leap improvement over 1.x :-)

**Comment by npostavs** [comment]
You could always do `(magit-define-popup-switch 'magit-rebase-popup ?i "Interactive" "--interactive")`

**Comment by tarsius** [comment]
I'll have a look later. Cannot promise anything.

**Comment by tarsius** [comment]
Personally I never felt compelled to do these things in one step, and I am rebasing *a lot*. It feels much safer to this in two steps. If I make a mistake and have to start over, then there is less I have to redo. I also feel it is less confusing to do just one thing at once, so I will make less mistakes.

> Or if you simply want to drop some commits as part of the rebase onto the other branch?

Here I would definitely prefer doing it in two steps. First drop the commits using an interactive rebase and then rebase what remains onto the other branch. If a conflict occurs during the first step then I know that this is so because I removed changes that a later commit depends on. If it occurs during the second step, then I know it's because two independent branches of development conflict. If I do everything at once, then it is much harder to figure out what's going on. Worst case scenario is when both kinds of conflicts occur while re-applying the same commit.

> What if you already know that the rebase will cause conflicts and that you can avoid those by editing or dropping certain commits during the rebase?

Does that actually ever happen? Sure there might be a commit on the branch to be rebased, which you don't want to keep and which would also conflict with the branch you intend to rebase onto. But does this ever happen in a way, which could not be addressed as above, i.e. by first removing the commit and then in a second step doing the "transplanting" rebase?

**Comment by tarsius** [comment]
Anyway, here's a command that does what you want

```lisp
(defun magit-rebase-interactive-onto (commit upstream)
  "Start a non-interactive rebase sequence starting at COMMIT onto UPSTREAM."
  (interactive (list (magit-commit-at-point)
                     (magit-completing-read
                      "Rebase onto" (magit-list-refnames)
                      nil nil nil 'magit-revision-history)))
  (magit-rebase-interactive-1 commit
    "Type %p on a commit to rebase it and all commits above it,"
    nil (list "--onto" upstream)))
```

**Comment by emosesSfdc** [comment]
This is a very common part of my (git-flow-ish) workflow at work.  I finish a feature on a branch, have it peer-reviewed, then squash/rebase it onto our master branch, so I have one commit based off the tip.  On the command line, I very often run ```git rebase -i master``` from my current branch, which means 

a) I don't have to explicitly select a commit, git rebase automatically chooses the last commit on the current branch that's ahead of the merge-base, and 
b) I can do everything I need to do in one step.

Magit 1.x had this functionality, I'd love to see it back.

**Comment by aspiers** [comment]
> But does this ever happen in a way, which could not be addressed as above, i.e. by first removing the commit and then in a second step doing the "transplanting" rebase?

Maybe not.  But that requires manually selecting a base commit for the first rebase, and also two steps can definitely be overkill in many cases (i.e. when the rebases don't involve many commits). You make a good point about the advantages of splitting it into two rebases, but the tool should be the servant of the user, not the other way around, so I think it should avoid being too opinionated and forcing the user into a particular workflow.  Thanks a lot for being open to discussing this.

**Comment by tarsius** [comment]
I have added the `--interactive` argument to the popup. You can now use that without having to add it yourself (which is an act we consider to be on the same level as adding a key binding) together with the non-interactive variants `rr` and `ro`. This allows you to do the things you asked for, try it and let us know if you have problems with it.

The commit can be found on the `jb/rebase-fixup` branch and also `pu`. I have not definitely decided whether I want to add this. Sure it makes it easier for you guys, but it will also confuse others ("why is there an interactive argument and an interactive action?").
