### ISSUE TITLE
magit-section-forward and magit-section-backward do not set point min after point moved

### ISSUE THREAD

**Issue by aaa707** [magit/magit#2164]
Hi,

Point position on magit-rev buffer remains like this:

![screencast](https://cloud.githubusercontent.com/assets/1144815/9218466/c261a916-410d-11e5-8bf1-0b364db60f16.gif)

I tried to solve this bug, but unfortunately I can't figure out magit section behavior.

Regards,

**Comment by tarsius** [comment]
That's not really a bug. We don't actually try to go back to the beginning of the buffer, we try to focus the reincarnation of the section that was current before the refresh, or otherwise some other "related section". In this case the final fallback unfortunately is the "back" button. I have added a special case to avoid that and instead go to the beginning of the buffer.

**Comment by aaa707** [comment]
Hi @tarsius,

I almost got it.
Your 'back' button fix is enough for me. Thanks a lot.
