### ISSUE TITLE
references buffer capitalises remote names

### ISSUE THREAD

**Issue by aspiers** [magit/magit#2175]
If I have a remote called `github` configured for my repo, the references buffer will display it as `Github`.  Similarly a remote called `adamspiers.org` will be displayed as `Adamspiers.Org`.

**Comment by npostavs** [comment]
It seems to be on purpose: https://github.com/magit/magit/blob/492c7aab19d215b2330bdd9b1498d41bb3274290/lisp/magit.el#L824

Do you think it's a bug?

**Comment by aspiers** [comment]
Yes, definitely a bug.  I don't see any good reason to tamper with these identifiers, especially given that `git-remote(1)` treats them as case-sensitive. If the user wants them to be capitalized, they will configure it that way in git.

**Comment by tarsius** [comment]
I did this intentionally after thinking about the consequences, so definitely no bug.

It's really not all that important and I could go either way - so I stick with what we already have.

You mentioned the downside of this; the upside is that by capitalizing the remote names here, all top-level sections everywhere begin with a capital letter.

> If the user wants them to be capitalized, they will configure it that way in git.

This is about how the name is displayed, not what the actual identifier is. I don't see any good reason why anyone would want to use an identifier that begins with a capital letter, especially because it is harder to type.

> given that git-remote(1) treats them as case-sensitive

Just because Git is case-sensitive here, that doesn't make it a good idea to have two remotes named `origin` and `Origin`. Even if someone did that, the two remotes could still be told apart in the refs buffer because the url is displayed after the capitalized name.

**Comment by aspiers** [comment]
Sorry but I think you're possibly missing my point. It's a lossy transformation, and what you're doing is (in an extremely mild way of course) is corrupting user data. This means that for example if the user gets the list of remotes from the references buffer, and then wants to invoke a command in the CLI or other UI outside magit, they don't immediately know whether they should reference 'Foo' or 'foo'. You are assuming that the user already knows which it is, and that both don't exist, and while I agree that the latter is a reasonable assumption, I don't think the former is, since the user may not have set up the remotes themself.  Therefore to my mind, any visual niceties (which are a matter of taste; personally I don't find the capitalised version any nicer to look at, and significantly uglier in the Adamspiers.Org case) should be trumped by a desire to avoid data corruption. But of course I understand if you agree to disagree.
