### ISSUE TITLE
magit-popup access to infix argument

### ISSUE THREAD

**Issue by domtronn** [magit/magit#2181]
Hi there, I'm playing around with `magit-popup`s and was wondering if there was any way or any use case to call the `:action` commands with arguments or at least have access to the infix arguments from within the commands, similarly to the `SHORTNAME-arguments` functions which supplies the last execution prefix args.

Here's a snippet of code I was playing with.
```elisp
(defvar example-list-of-actions '("run" "start" "stop" "restart"))

(defun example-func ()
  (interactive)
  (message "%s" (example-arguments)))

(magit-define-popup example-popup
  "Example popup"
  :switches
  `((?s "Stack" "--stack")
    (?v "Verbose" "--verbose"))
  
  :actions
  (funcall #'(lambda ()
               (let* ((char 96))
                 (mapcar #'(lambda (action)
                             (setq char (+ char 1))
                             (list char action 'example-func))
                         example-list-of-actions)))))
```
This will produce a popup containing all of the actions from the `example-list-of-actions` list, the idea would be that this list is dynamic, hence the dynamic creation of actions as a result. But I'd like to be able to reference the _action_ from inside `example-func`, so say you called the `start` action, I'd like to be able to use `start` as a string or something inside of `example-func`.

I tried to pass the `action` argument to `example-func` but this seems to conflict with the idea that they're commands rather than lisp functions. Basically, is there a way to get the infix arguments like you can get the prefix arguments? Or does this not really make sense? I appreciate I may be abusing `magit-popup` a little bit here :P

Part of me feels that the ability to do this wouldn't make sense behaviourally since you aren't given a consistent set of action mappings based on the dynamic list, but I was just curious as this would allow me to easily set prefix arguments before each execution of an action.

Any help/information would be greatly appreciated!

**Comment by tarsius** [comment]
> Basically, is there a way to get the infix arguments like you can get the prefix arguments? Or does this not really make sense?

That makes perfect sense, the infix arguments were modeled after the prefix arguments and that will only get more so. (And like with prefix arguments you should usually get them inside `interactive`.)

> This will produce a popup containing all of the actions from the `example-list-of-actions` list,

This is fine but you should write it as:

```lisp
(let ((char 96))
  (mapcar (lambda (action)
            (setq char (+ char 1))
            (list char action 'example-func))
          example-list-of-actions))
```

> the idea would be that this list is dynamic, hence the dynamic creation of actions as a result.

What do you mean by "dynamic"? "Generated once" or "generated everytime the popup is invoked, so that some external state can be taken into account"? It seems you mean the former:

> But I'd like to be able to reference the _action_ from inside `example-func`,

Looks like all you want to do is to avoid writing boilerplate code `example-run`, `example-start` etc. You shouldn't do that, you would lose the ability to document each action individually (which can be shown using `?X`, where X is the key used to invoke the action. Instead write it like this:

```lisp
(defun example-run (args)
  "documentation"
  (interactive (list (example-arguments)))
  (example-internal "run" args))

(defun example-start (args)
  "documentation"
  (interactive (list (example-arguments)))
  (example-internal "start" args))

(defun example-stop (args)
  "documentation"
  (interactive (list (example-arguments)))
  (example-internal "stop" args))

(defun example-restart (args)
  "documentation"
  (interactive (list (example-arguments)))
  (example-internal "restart" args))

(defun example-internal (subcmd args)
  (many lines of common code))
```

That way you have to write only three lines of boilerplate per action/command (plus the documentation).

**Comment by domtronn** [comment]
Hi @tarsius,

> What do you mean by "dynamic"? "Generated once" or "generated everytime the popup is invoked, so that some external state can be taken into account"?

I think I'm actually more of the latter. It might help if I explain my actual use case. I'd like to make a popup  for running grunt tasks _(if you're unfamiliar with it, it's a task runner similar to ant maven etc.)_ and use the prefix arguments for command line flags like `--verbose`. The problem is, the list of tasks is parsed and created at runtime and changes based on projects that it's run in which is why I'd like to create a dynamic list of actions in the popup that map to these tasks.

> Looks like all you want to do is to avoid writing boilerplate code

Not really, I can't write a function for each potential task, they're basically anonymous from my perspective. The kind of flow I would like is

* `grunt-exec` _(the command to start the process)_
* calculate the available tasks
* recreate a dynamic popup that contains these tasks & `grunt` command line flags as prefix arguments
* On selection, call `grunt-run` with the selected task and prefix arguments
* Construct the command line command to run.

e.g.
```elisp
(defun grunt-run (task)
   (let ((cmd (build-cmd task (grunt-arguments))))
     (start-process-shell-command cmd))
```

I'm not fussed about the documentation aspect since it's dynamic.

I suppose one solution would be to create the popup with the prefix arguments and a single action that calls through to the interactive `grunt-exec` command. But this would be an extra keypress I was looking to avoid :P But that way, users would be able to complete the tasks using `ido` which might be a nicer experience altogether.

**Comment by tarsius** [comment]
In that case you should not set `:actions`. Instead you should set `MODE`. Something similar is done for "sequence" popups, like the rebasing popup, which show different actions depending on whether a sequence is already in progress or not.

So see `magit-popup-sequence-mode` for an example. Basically the mode is responsible for changing the value of `magit-popup-setup-hook`. (Since setting that hook is all that these derived modes are used for I will likely replace the `MODE` argument with a `:setup-function` argument. But for now you have to use a mode.

The setup function should generate the list of actions. The third element of each action can be a dynamically generated lambda, but it has to be a command, i.e.:

```lisp
(lambda (args)
  "you can generate the doc-string too"
  (interactive (list (grunt-arguments)))
  (grunt-run ...))
```

The action cannot get its own "identity", so you have to "inject" that:

```lisp
`(lambda (args)
   ,(generate-the-docstring)
   (interactive (list (grunt-arguments)))
   (grunt-run ,(generate-the-identity) args)))
```

If you don't know what the **`** and **,** do, then you have to learn about [backquotes](http://www.gnu.org/software/emacs/manual/html_node/elisp/Backquote.html).

**Comment by domtronn** [comment]
Fantastic! Thanks @tarsius, that's been really helpful and plenty for me to read up on and experiment with. I appreciate the help!
