### ISSUE TITLE
Can't install magit from melpa w/ Emacs 24.5.1

### ISSUE THREAD

**Issue by gleb** [magit/magit#2194]
Getting: "package-compute-transaction: Package `emacs-24.4' is unavailable" when trying to install from package interface.

Both melpa and melpa-stable

GNU Emacs 24.5.1 (i686-pc-linux-gnu, GTK+ Version 3.4.1)  modified by Debian

I am guessing this is because magit has a dependency "Requires: emacs-24.4" and emacs 24.5 does not provide this fake package.

**Comment by tarsius** [comment]
Magit does indeed depend on Emacs v24.4, but since N always means >=N in Elpa land, v24.5 should satisfy that too. Since you are the first one reporting this I assume that this is a problem with your installation.

* Double check what `M-x emacs-version` reports, and
* make sure you are using the `package.el` that came with v24.4 (use `M-x find-library RET package RET` and then verify whether that took you to the file one would expect).

**Comment by gleb** [comment]
Doh.   It was the second one - local old copy of package.el.   I thought it was strange that I couldn't Google this error.   This explains it.

Thanks!

**Comment by scottanderson42** [comment]
I'm having this issue as well. 24.5.1, find-library brings me to the package.el.gz that came with this version of emacs.
