### ISSUE TITLE
diffstat is fixed width regardless of window width

### ISSUE THREAD

**Issue by greenrd** [magit/magit#2200]
This means that long filenames are truncated with an elipsis substituted for some directories, making it difficult to know what the filename actually is. Also due to #2199 I can't find out the filename by jumping to the diff by pressing j, because j doesn't work either.

I suggest that a more appropriate width (e.g. window width) should be passed to git-diff via the `--stat=` option. Alternatively, the ability to manually add the `--stat=` option could be provided.

**Comment by tarsius** [comment]
I won't do that because I am considering some fairly big changes here and the proposes sub-feature might not survive that transition. When I remove a small feature there's always someone who complains, so I try to avoid that by not adding features I expect to remove again and/or implement in another fashion at some point.
