### ISSUE TITLE
magit-clone complains that I am "not inside a git repository"

### ISSUE THREAD

**Issue by djg123** [magit/magit#2203]
I opened an empty directory in dired. I would like to clone a repository from GitHub into the opened directory.

So I did: `M-x magit-clone`, then put down the address of the repository and hit enter.
Under `Clone to:` it defaulted to `CWD/NAME_OF_REPOSITORY`, and I hit enter.

The mini buffer than quickly displayed `Cloning Into` and then quickly switched to saying `Not inside a Git repository`. The repository was not installed in the directory.

I tried again on the command line and which worked.

I am using `GNU Emacs 24.4.1`, `Git 2.5.0`, `Ubuntu 14.04` and `magit 20150824.1010` from Melpa.

**Comment by tarsius** [comment]
You probably mistyped the url. I just reproduced this by accident. I mistyped the url and got the same error as you got. They I tried again this time making sure the url was correct and it worked. The reason you get an error about not being inside a repository is that after failing to clone the repository, magit goes on trying to show the status of the non-existent clone. I'll fix that so that it stops after failing to clone, which will give a more meaningful error message.
