### ISSUE TITLE
Unclear documentation of commit types

### ISSUE THREAD

**Issue by DamienCassou** [magit/magit#2204]
The documentation (both inline and in the manual) of the different commit actions (e.g., `fixup`, `Squash`, `Augment`, `Instant Fixup`) are not explicit enough I think. For example, for `Instant Fixup`:

```
(magit-commit-instant-fixup &optional COMMIT ARGS)

Create a fixup commit and instantly rebase.

(git commit --no-edit --fixup=COMMIT ARGS;
 git rebase -i COMMIT^ --autosquash --autostash)
```

When should I use it? What is the difference with `fixup`?

**Comment by kyleam** [comment]
> When should I use it?

When you want to instantly rebase.

> What is the difference with `fixup`?

magit-commit-fixup stops at making the commit.  You will have rebase it
yourself later.

Is the confusion that "instant" refers to the rebase, but you're trying
to figure out what it would mean for a commit to not be "instant"?  I
think if the user compares the docstrings side-by-side the difference
should pop out.

**Comment by DamienCassou** [comment]
Kyle Meyer <notifications@github.com> writes:

>> When should I use it?
>
> When you want to instantly rebase.


I was thinking about something like: "Use this when you have some staged
changes that should have been part of a commit you already did. This
will recreate the commit of your choice with this additional changes and
rewrite the recent history on top of the new commit."


>> What is the difference with `fixup`?
>
> magit-commit-fixup stops at making the commit.  You will have rebase it
> yourself later.


then, what is the difference between `magit-commit-fixup` and
`magit-commit`?


> Is the confusion that "instant" refers to the rebase, but you're
> trying to figure out what it would mean for a commit to not be
> "instant"? I think if the user compares the docstrings side-by-side
> the difference should pop out.

I disagree that looking both docstrings solve any problem as I did it
and didn't get the point. Moreover, the user should not have to read the
documentation of several functions to understand one. Finally, if you
disagree with the last sentence, a minimum would be to include a "See
also `this-function`" sentence at the end.

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by kyleam** [comment]
> I was thinking about something like: "Use this when you have some staged
> changes that should have been part of a commit you already did. This
> will recreate the commit of your choice with this additional changes and
> rewrite the recent history on top of the new commit."

I'd have to step back and look at what Magit does elsewhere, but my
feeling is that, if there is specific git terminology that can be used
to describe an action, that tends to be used instead of a more verbose
description.

> then, what is the difference between `magit-commit-fixup` and
> `magit-commit`?

I'm assuming you're trying to make the point that you'd have to consult
yet another docstring and/or you don't think "-fixup" would mean a lot
to many users.

> I disagree that looking both docstrings solve any problem as I did it
> and didn't get the point. Moreover, the user should not have to read
> the documentation of several functions to understand one.  Finally, if
> you disagree with the last sentence, a minimum would be to include a
> "See also `this-function`" sentence at the end.

Yes, I agree that the docstring should give a good sense of what a
particular function does without having to click around to other
functions for context.  But if your question is what is the *difference*
between two functions (and you feel the names don't give you a clear
idea), I think it is hard to get around looking at and comparing both
the doc-strings.  (The manual is also a good way to get a view of all
the commands side-by-side.)

In any case, it is good to know you and probably a good number of other
users find this unclear.  I wouldn't be surprised if this varies a good
deal among users then, because I feel the names alone for these commands
are a good indication of what the commands do (magit-commit-augment is
the command whose name I find least informative).  Perhaps the main
factor is whether the user is familiar with git's --fixup/--squash
functionality.

**Comment by tarsius** [comment]
When I wrote the new manual I had the choice between seeding it with doc-strings *or* git manpages. It wasn't possible to do both due to a license conflict (GPL v3+ vs. GPL v2-only). (The old manual had to be discarded because its license conflicted with both.)

I choose the doc-strings so that from now on documentation can flow freely between the manual and doc-strings. Unfortunately that means that I cannot copy parts of git manpages into the manual. So we have to write all these introductions and concept descriptions from scratch. That's a lot of work and it will never get finished if I am essentially the only one who works on it. Meanwhile we link to the relevant git manpages and hope that over time users contribute to the documentation.

So I completely agree that the manual doesn't describe the commit variants sufficiently (and neither do the doc-strings). I was already aware of that, by which I don't only mean that I was aware that this area is one of those which are not sufficiently documented, but also that this is an area where that would lead to more confusion than in other equally insufficiently documented areas.

There's not really much good in keeping this issue open. I hope someone - maybe you - contributes better documentation in this area, and if that doesn't happen, then I will probably get around to do it eventually. But we don't need an issue to remind us that this particular area is one of the many areas which are not sufficiently documented.

(If more issues are being opened about particular areas not being sufficiently documented, then I will create a new "yes I know" issue similar to #1096. By the way, there's nothing wrong with you having opened this issue, I just don't want to keep it open.)

> I was thinking about something like: "Use this when you have some staged changes that should have been part of a commit you already did. This will recreate the commit of your choice with this additional changes and rewrite the recent history on top of the new commit."

That's not precise enough, its even incorrect actually. History is not rewritten on top of "the new commit". It cannot be the same commit because it was moved back in time, giving it a new parent, which turns it into another commit. But it is okay to be imprecise about that. However there's not even a commit with the same patch-id anymore. The fixup commit gets combines with the target commit, and referring to that union commit as "the same commit as the fixup commit", contradicts the essential idea of what fixup commits are for and what their fate is.

That's another reason why the current documentation is often overly concise: longer descriptions are much more work than one initially anticipates if one wants to make sure not to tell any half-truths. Personally I prefer overly concise or even incomplete documentation over partially incorrect documentation which puts me on the wrong track.

**Comment by grothesque** [comment]
I add a message here instead of opening a new issue in order to avoid noise and to preserve context.

I have a particular problem with `M-x magit-commit-augment` or `c A`: I keep forgetting what it does!  Then, every other year when I look it up in the documentation, this is not quite enough to refresh my memory, I have to try it out.  I am someone who knows git very well, having been using it intensely since at least 2009.

In my opinion, the problem is not just the terse documentation.  For me that documentation would be sufficient if magit would not seem to introduce a seemingly new concept (“augment”), that is otherwise unknown in git-world.

Perhaps one could rename `magit-commit-augment` to something like `magit-commit-squash-augmented`?  This would help me (and perhaps others) by making it clear that this is just about a squash commit, and not some strange new concept.
