### ISSUE TITLE
Additional actions when doing a commit?

### ISSUE THREAD

**Issue by hatschipuh** [magit/magit#2207]
It would be nice to have the possiblity to conditionally prevent a commit or take some action on commit. Something like a hook for functions that would be called before a commit is being executed. So one can  conditionally stop the commit execution or execute additional commands. Is that possible ? How could I achieve that?

**Comment by tarsius** [comment]
Git itself has hooks intended for this purpose. Use those. These hooks are documented in `githooks(5)`.

**Comment by hatschipuh** [comment]
I know that, but it would nicer interact with my workflow in Emacs so I could run Elisp functions and use packages like https://github.com/wasamasa/firestarter to take actions on a per file basis.

**Comment by tarsius** [comment]
You can still do that, just use emacsclient in the hook script to connect to the current emacs instance. Sounds adventurous, but now that `with-editor` is mature, this actually works very reliably.

That being said, you can of course advise magit's commit commands to run some hook. And once you have written something useful that depends on that hack, you can show it to me, and I might then reconsider. But also note that this has been suggested before and so far nobody could or was willing to demonstrate why such an emacs hook was necessary. Saying that it is necessary to do X using Y isn't enough (because then I would have to investigate whether that is true), instead you should present some working and useful code. In order to write that code you might have to patch magit (likely advising or redefining functions should be enough).

**Comment by hatschipuh** [comment]
Ok, If I come up with something useful I will make a pull request :)

Thanks for your time and for your work on Magit in general!
