### ISSUE TITLE
commit-popup console is not triggered

### ISSUE THREAD

**Issue by vspinu** [magit/magit#2222]
I just upgraded and `c` in magit status buffer has no effect. Looking at the code, `magit-commit-popup` simply switches to the current buffer.

**Comment by tarsius** [comment]
> Looking at the code, `magit-commit-popup` simply switches to the current buffer.

No, it switches to the existing commit-message-editing-buffer, provided that exists. If that buffer does not exist, then it shows the popup.

> no effect

None at all? I am guessing that the buffer does exist, but thata due to your Emacs and/or X11 window-management configuration, the existing buffer is not switched to in a way you can see (it might for example appear on another workspace).

**Comment by vspinu** [comment]
The (magit-commit-message-buffer) always returns the current buffer for me. So I am always switched to the current buffer.

**Comment by tarsius** [comment]
I have reverted the commit which probably caused this.

**Comment by vspinu** [comment]
It actually was me. I accidentally bound git-comit-mode globally in my .emacs. Sorry for the noise. Hope it's not much trouble to put back that commit.

**Comment by tarsius** [comment]
I didn't revert it because of this issue, just thought it might have been the cause of this.
