### ISSUE TITLE
FIle-based magit workflow - magit-global

### ISSUE THREAD

**Issue by gleb** [magit/magit#2236]
For some commonly used commands, I want to be able to use Magit without switching to status buffer. In particular I want to be able to invoke commands like log and diff on the current file with minimum number of keystrokes.

Code:
https://github.com/gleb/magit/blob/magit-global/lisp/magit-global.el

Screencast:
https://youtu.be/eTpWVo-M260

The MVP here is this:
``` elisp
(global-set-key [(control x) (g) (g)] 'magit-status)
(global-set-key [(control x) (g) ($)] 'magit-process)
(global-set-key [(control x) (g) (l)] 'magit-global-log)
(global-set-key [(control x) (g) (=)] 'magit-global-diff)
```
So, really just -log and -diff.  I'd focus on these 2, the rest of interactive commands are not as fully thought-out yet.

I've been using a version of these for years.   The implementation became much cleaner after I rebased on top of magit 2.x.

The code is early, but I hope it's good enough to show the general approach and solicit feedback.

Related:
* #2219 
* #1766
* http://stackoverflow.com/questions/17798109/how-can-i-diff-a-single-file-with-magit

**Comment by tarsius** [comment]
> The code is early, but I hope it's good enough to show the general approach and solicit feedback.

It's enough to see that you don't only want to bypass the status buffer but also want to avoid the popups and implement an alternative way to specify arguments to be passed to git. But beyond that there's not much I could provide feedback on. The main takeaway should be this:

> To roll our own MVP all that's needed is the right completion function to use in completing read.  Something like read-file-name-internal but that can handle other text before the filename. You'd think it would be simple, but it's currently beyond me.

You are massively underestimating what it will take to get you where you want to go. Beyond that I really don't see what I could comment on at this point.

You will have to implement these things yourself, and getting there will involve a lot of code reading. I recommend that you don't even worry about git/magit at this point, but start by implementing your "read arbitrary arguments and files in the minibuffer"-idea as an independent library.

In #2219 I wrote:

> So I am closing this issue, but if you make some progress, then feel free to inform me about it here.

I meant something that has progressed a little further than this, and by "inform me here" I meant "mention it in this issue". I don't have the time to guide you to through the steps required to implement this. And since this is neither a request for a Magit-feature nor a report about a Magit-bug, I am closing this.
