### ISSUE TITLE
`with-editor-cancel' has no effect when commit message exists

### ISSUE THREAD

**Issue by Alexander-Shukaev** [magit/magit#2258]
Do

```
git commit
```

in terminal.  When brought to the `git-commit` buffer in Emacs, type some commit message (one character is enough).  Run `M-x with-editor-cancel RET`.  Go back to terminal and see how the commit succeeds.

Does everybody have this issue or did I miss anything?

**Comment by tarsius** [comment]
Could you please ask this on the Emacs Stackexchange side please. See https://github.com/magit/magit/blob/master/CONTRIBUTING.md, which was linked to when you opened this issue.

Don't forget to post the relevant configuration.

**Comment by tarsius** [comment]
This works for me:

```shell
emacs -Q -L ~/.emacs.d/lib/dash -L ~/.emacs.d/lib/magit/lisp -l git-commit --daemon
GIT_EDITOR="emacsclient" git commit
```

in Emacs I then type a message but abort using <kbd>C-c C-k</kbd>, and `git` exits with 1 and does not create a commit.

Why do you mention `M-x with-editor-cancel RET`? Did you not know about the binding or was it not available? In the latter case that probably means that `git-commit.el` is not in use. Possibly because you didn't load it. If it looks like it is in use because of syntax highlighting, then check whether you have only `git-commit.el` installed and not also the predecessor `git-commit-mode.el`.

**Comment by Alexander-Shukaev** [comment]
I know about the binding, I just don't use default key bindings.  Anyway, this does not matter in this case as `M-x with-editor-cancel RET` should work equally well.  Although I understand rationale behind your `emacs -Q ...` experiment, could you confirm that `M-x with-editor-cancel RET` with your daily Emacs configuration indeed works as <kbd>C-c C-k</kbd>?  I can confirm that `git-commit` is properly loaded and I got rid of `git-commit-mode` long ago.

**Comment by npostavs** [comment]
> could you confirm that M-x with-editor-cancel RET with your daily Emacs configuration indeed works as C-c C-k?

Works for me.

**Comment by tarsius** [comment]
> could you confirm that `M-x with-editor-cancel RET` with your daily Emacs configuration indeed works as <kbd>C-c C-k</kbd>

I have confirmed that it does. You should do same as that might show warning that indicate what is wrong (multiple emacs instances running, no server running, the server not being found, etc.).

That's the relevant code: https://github.com/magit/magit/blob/41247039a0a47063ae0c7d55303408557862d7b3/lisp/with-editor.el#L288-L295. In all likelihood the behavior you are seeing means that `client` is nil here. And that in turn means that there is a misconfiguration on your end with regards to server-client communication.

**Comment by tarsius** [comment]
Or are you actually using `emacs` as `$GIT_EDITOR`/`$EDITOR`?

**Comment by Alexander-Shukaev** [comment]
I'm using `emacsclientw.exe` (on Windows) as `$EDITOR`.  I will try to investigate this now.

**Comment by Alexander-Shukaev** [comment]
Here is what I got in the `git-commit` buffer:

> `server-buffer-clients` is a variable defined in \`server.el'.
> Its value is `(#<process server <127.0.0.1:51923>>)`
> Local in buffer `COMMIT_EDITMSG`; global value is `nil`

so I still don't understand where is the problem.  By the way, doing the same experiment but with `magit-commit` works fine indeed, so the problem is really with client/server thingy.

**Comment by Alexander-Shukaev** [comment]
OK, so the problem turns out to be quite simple.  Why do you call `save-buffer` when `cancel` is non-`nil`?  This causes `git` to recognize and accept `COMMIT_EDITMSG`, what eventually results in commit.  So the first step is to get rid of `save-buffer` when `cancel` is non-`nil`.  Secondly, there would be inconsistency between behaviors when `cancel` is `nil` and `cancel` is non-`nil`.  In particular, the latter will ask for an annoying confirmation, while the former does not (due to `save-buffer`).  I assume that was the reason why you added `save-buffer` when `cancel` is non-`nil` in the first place.  Clearly, that's not how it should be done.

I created different implementation and tested it.  It looks like it's more robust then the previous one (no need for `delete-process` magic as well).  Here is the code:

```
    (cond (cancel
           (set-buffer-modified-p nil)
           (dolist (process (process-list))
             (when (eq (process-buffer process) (current-buffer))
               (set-process-query-on-exit-flag process nil)))
           (dolist (client clients)
             (ignore-errors
               (server-send-string client "-error Canceled by user"))))
          (t
           (save-buffer)))
    (if clients
        (server-done)
      (kill-buffer))
```

> **NOTE**  
By the way, I'm still scratching my head about whether you do `(server-send-string client "-error Canceled by user")`.  I mean, what's the benefit and where is it visible?

Please, give it a shot and let me know if you'd like to incorporate it upstream.  Looking forward to your feedback.

**Comment by tarsius** [comment]
I'll answer that more or less in opposite order.

> I'm still scratching my head about whether you do `(server-send-string client "-error Canceled by user")`.

This causes the emacsclient to exit with non-zero exit status, which tells git that the user aborted and the commit should not be created.

> (no need for `delete-process` magic as well)

As far as git is concerned it's over after the above, but this is necessary to cleanup inside emacs.

> [using `save-buffer`] causes `git` to recognize and accept `COMMIT_EDITMSG`, what eventually results in commit.

Not if the above works as intended.

> Why do you call `save-buffer` when `cancel` is non-`nil`?

To save the buffer :-) Just because the user aborts the commit doesn't necessarily mean she also wants to discard the commit message.

Also just not saving the buffer doesn't prevent git from creating the commit. Git itself might have inserted a message template (e.g when merging) or an old message (e.g. when amending) into the file. In some cases it would be very unfortunate if we had to communicate with git by emptying the file, which is why we use `(server-send-string client "-error ...")` instead.

**Comment by npostavs** [comment]
> By the way, I'm still scratching my head about whether you do (server-send-string client "-error Canceled by user"). I mean, what's the benefit and where is it visible?

When using `emacsclient.exe` that message will show up:
```
C:\Users\npostavs\src\magit>set EDITOR="c:\Program Files\Emacs\bin\emacsclient.e
xe"

C:\Users\npostavs\src\magit>git commit
Waiting for Emacs...
*ERROR*: Canceled by user
error: There was a problem with the editor '"c:\Program Files\Emacs\bin\emacscli
ent.exe"'.
Please supply the message using either -m or -F option.
```

When using `emacsclientw.exe` the `*ERROR*: Canceled by user` message gets lost (I guess `emacsclientw.exe` detaches from the terminal), but the commit is still canceled.

```
C:\Users\npostavs\src\magit>set EDITOR="c:\Program Files\Emacs\bin\emacsclientw.
exe"

C:\Users\npostavs\src\magit>git commit
error: There was a problem with the editor '"c:\Program Files\Emacs\bin\emacscli
entw.exe"'.
Please supply the message using either -m or -F option.
```

 It seems there is something strange with your configuration.

**Comment by tarsius** [comment]
@Alexander-Shukaev you never said whether you can reproduce the issue with

```shell
emacs -Q -L ~/.emacs.d/lib/dash -L ~/.emacs.d/lib/magit/lisp -l git-commit --daemon
GIT_EDITOR="emacsclient" git commit
```

**Comment by npostavs** [comment]
Windows doesn't implement `--daemon`, so it would be more like

```
"c:\Program Files\Emacs\bin\emacs.exe" -Q -L dash.el -L magit\lisp -l git-commit -f server-start
set GIT_EDITOR="c:\Program Files\Emacs\bin\emacsclient.exe"
git commit
```

**Comment by tarsius** [comment]
Reopen when you have more information.

**Comment by Alexander-Shukaev** [comment]
Finally had time to make this test.  In my case I had to tweak it, but the idea is the same.  So, first

```
emacs -Q -L packages/elpa/dash-20150829.433/ -L packages/elpa/with-editor-20150910.1352/ -L packages/elpa/git-commit-20150903.1204/ -l git-commit -f server-start
set GIT_EDITOR=emacsclient
git commit
```

then type something in Emacs and

```
M-x with-editor-cancel
```

The problem still remains; I get a commit rather than abortion.  This, I believe, confirms the problem that I've pointed out originally and the solution that I've proposed to fix it.  If I can do something else for you, for instance, in terms of testing, let me know.  Looking forward to your feedback.

**Comment by tarsius** [comment]
I am sorry but I simply cannot reproduce this. @npostavs also wasn't able to reproduce it - on Windows.

I have already explained why your proposed "fix" is undesirable.

This you really `set GIT_EDITOR=emacsclient`? Not `set GIT_EDITOR=emacsclient --alternate-editor emacs`. Also make sure `ALTERNATE_EDITOR` isn't set.

I suspect what is happening is that due to configuration issues a *new* emacs instance is started instead of the emacsclient connecting to an existing instance. You can verify this by checking the value of `emacs-pid` a first time before invoking the commit from the command line, and then again in the `COMMIT_EDITMSG` buffer.

**Comment by tarsius** [comment]
I've installed a kludge which should "fix" this for you. I still think there's something wrong with your configuration and suggest you investigate as suggested in my previous reply. If you need help with that then please get it on the Emacs Stackexchange site.

**Comment by tarsius** [comment]
The issue in this case was a wrapper script, see https://github.com/magit/magit/issues/2284#issuecomment-144822527.

**Comment by mentalisttraceur** [comment]
So I've been wasting time rewriting carefully crafted commit messages because one person one time had a bug no one else could reproduce?

(And because I have a habit of running `:w` and `:q` as two separate commands instead of `:wq`, but that's a good and useful habit.)

On the one hand, it's genuinely heartwarming to know that @tarsius cares about users enough to put in a workaround even for users whose bugs are persistently alleged despite inability to reproduce. As a user, this makes me feel positive things and confident that if I have a problem it will be addressed.

On the other hand, I've now lost precise, long, carefully crafted commit messages, *several times*, seemingly because of this, and that's super frustrating.

Can we *please* put in a toggle to disable this workaround? (Personally, for lack of repro, I would even recommend making the workaround off by default, but maybe that's too late to change now for backwards compatibility reasons.)

**Comment by mentalisttraceur** [comment]
I've tried self-servicing this with an `(advice-add ... :around ...)` to wraps `with-editor-return` or even `with-editor-cancel` in a `(let ((delete-file 'ignore)) ...)` form, and verified that the`delete-file` which I put into dynamic scope with that `let` *does* get executed, but the file still gets deleted.

This is while using the sleeping editor.

So maybe I'm misunderstanding where deletion is happening?

Or maybe I have a bigger misunderstanding about why I'm losing commit messages on a cancel? Sorry if this commentary was premature, but so far digging into this I came upon `delete-file` in `with-editor-return` with a link to this issue, so it seems like that's at least part of it.

(I know I could use `magit` and then it would provide separate commit message history that I could recover with `M-p` or whatever, and that's super cool and helpful (thank you!), but I'm hoping to have this solved independently of the choice to install `magit`, and for other files besides git-specific ones.)

**Comment by mentalisttraceur** [comment]
Okay, in the meantime this is how I've solved it (un-"fixed" it; worked around the workaround) in my config:

```elisp
    (defun fixed-with-editor-return (with-editor-return &rest arguments)
        (unwind-protect
            (progn
                (advice-add 'delete-file :around 'ignore)
                (apply with-editor-return arguments))
            (advice-remove 'delete-file 'ignore)))
    (advice-add 'with-editor-return :around 'fixed-with-editor-return)
```

I'm not sure if there's a better way or if I missed any problems. Improvements welcomed.

Still really hoping for a `(setq with-editor-cancel-deletes-file nil)`-style solution, please.
