### ISSUE TITLE
Bind `magit-log-select-mode` in the log buffer

### ISSUE THREAD

**Issue by expez** [magit/magit#2279]
Hi

After hitting <kbd>ll</kbd> to popup the magit log I can't find a way to select multiple commits.  My use-case is to revert several commits.

I propose we introduce a binding for `magit-log-select-mode` in the log buffer.

**Comment by tarsius** [comment]
You can act on multiple commits by marking them using the region.


`magit-log-select` is intended for a different purpose: it's used to select a *single* commit, which is then returned to the caller. So it's a bit  like `completing-read`, except that it uses a regular buffer and that the item is selected by moving to it instead of typing it's name.
