### ISSUE TITLE
Improve the "Reverting" docs

### ISSUE THREAD

**Issue by expez** [magit/magit#2280]
I want to revert two commits and I can't figure out how to do it.  I'll give you guys a complete rundown so you can improve to docs to the point where even I can understand them.

This is what I'm trying, from the magit status window:

<kbd>ll</kbd> to popup the log buffer. <kbd> M-x magit-log-select-mode </kbd> to select the two commits. <kbd>V</kbd> to access the reverting popup and finally <kbd>v</kbd> to indicate that I just want the reverted changes applied to the working tree, instead of creating 'revert commits' right away.

This is where the confusion starts:

I now see a prompt, which isn't mentioned in the readme, asking `Revert changes: ` with a completing read of every ref in the repo (the head of all branches, github pull requests etc).  I have no idea what to select here.  I've tried selecting the current branch, as well as HEAD.

Selecting HEAD there is now a Reverting section in magit status with two lines `work` and `onto` which both point to the current HEAD which is not one of the previously selected commits.

If I now hit `V` again I can select `skip` `abort` or `continue` but that I have to do that at all, or what these do in the context I'm in now isn't documented in the README either.  I hit `skip` because I certainly don't want to revert the commit at HEAD.

At this point I was pretty pissed I spent 5 minutes trying to do in magit what takes 5 seconds on the command line.

Hopefully this look into the mind of one of your 'dumb users' was helpful.  Magit is otherwise wonderful and version 2.x is every bit as wonderful as we'd hoped!

**Comment by tarsius** [comment]
You can get the documentation of any popup argument or action using <kbd>?...</kbd>. In the `magit-revert-popup` for example you could press <kbd>?-v</kbd> to learn about `--signoff` or <kbd>?V</kbd> to learn about the action "Revert commit(s)" (the `magit-revert` command). Which gives you:

> Revert COMMIT by creating a new commit.
> Prompt for a commit, defaulting to the commit at point.  If
> the region selects multiple commits, then revert all of them,
> without prompting.

That also covers what you asked in the other issue.

> isn't documented in the README either

The readme isn't the right place to document things like that. But we also provide a manual (three actually): http://magit.vc/manual/index.html. (The main manual is 87 pages long when printed out, which is why we don't put the same information in the readme.)
