### ISSUE TITLE
b B tracks the wrong upstream branch?

### ISSUE THREAD

**Issue by expez** [magit/magit#2292]
After doing `b B`, to checkout and create a new branch and selecting `master` as the branch's starting point I get the following output from `git branch -vv`:

```
$ git branch -vv
  master                       0da5124 [origin/master: behind 1] Ditch -some->
* test                         0da5124 [master] Ditch -some->
```

Why is this branch tracker `master` instead of `origin/test`?  Magit is slow as molasses on Windows so I've been doing half the operations with Magit and half on the command line.  Magit prompts to select a branch to push up stream, which has apparently been saving my ass up to now, but when I do `git push origin test` it just pushes the commit straight to the master branch.  This has caused me to force push updates intended for branch straight to `master`, as well as pushing what I intended to go into a pull request right to `master`.

**Comment by tarsius** [comment]
> After doing `b B`, to checkout and create a new branch and selecting `master` as the branch's starting point ... Why is this branch tracker `master` instead of `origin/test`?

Because that's what you requested. Git doesn't actually allow using a non-existent remote branch as the upstream branch when creating a branch. A lot of users seem to be unhappy about that and related issues (see #2009) and I will soon tackle this area - v2.4 will be specifically about branching and pushing (also see #1485 and #2180).

> Magit is slow as molasses on Windows

It shouldn't be much slower on Windows anymore. Did you recently update to Git v2.1, that might have caused bit of a slowdown but we are working on it (see #2259). The reason for the slowness more likely is that you work inside somewhat huge repositories and that Magit's diffing support isn't really up to that. That will be addressed in v2.5.

**Comment by Malabarba** [comment]
I'm not sure I understand. If I create the branch from `master` (not `origin/master`) and the `Upstream:` at the top even says `master` (instead of `origin/master`) is it alright that when I push it pushes to `origin/master`?

**Comment by tarsius** [comment]
I don't think Git does that:

```
$ git init origin
Initialized empty Git repository in /tmp/origin/.git/
$ cd origin 
$ cd ..
$ rm origin -rf
$ git init --bare origin
Initialized empty Git repository in /tmp/origin/
$ git clone origin fork
Cloning into 'fork'...
warning: You appear to have cloned an empty repository.
done.
$ cd fork 
$ touch file
$ git add file
$ git commit -m init
[master (root-commit) a14b56c] init
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 file
$ git push -u origin master
Counting objects: 3, done.
Writing objects: 100% (3/3), 202 bytes | 0 bytes/s, done.
Total 3 (delta 0), reused 0 (delta 0)
To /tmp/origin
 * [new branch]      master -> master
Branch master set up to track remote branch master from origin
$ git checkout --track -b feature master
Branch feature set up to track local branch master.
Switched to a new branch 'feature'
$ echo feature > file
$ git add file
$ git commit -m feature
[feature 584d905] feature
 1 file changed, 1 insertion(+)
$ git push
fatal: The upstream branch of your current branch does not match
the name of your current branch.  To push to the upstream branch
on the remote, use

    git push . HEAD:master

To push to the branch of the same name on the remote, use

    git push . feature

128 $ git config push.default
simple
$ git config push.default upstream
$ git push                        
Total 0 (delta 0), reused 0 (delta 0)
To .
   a14b56c..584d905  feature -> master
$ git log --decorate=full --branches --remotes --oneline
584d905 (HEAD -> refs/heads/feature, refs/heads/master) feature
a14b56c (refs/remotes/origin/master) init
```

**Comment by Malabarba** [comment]
I see. So it's the `push.default` option that causes that.
Thanks for explaning Jonas.

**Comment by jasonm23** [comment]
Seeing a different behaviour here, that's more alarming.

    b B branch-name

Upstream is set to the parent branch instead of `origin/branch-name` 

It doesn't appear that this is configurable, and definitely not default git behaviour.  Expectation based on git usage is that NO upstream would be set, and the `origin/branch-name` would be prompted at a subsequent push.

**Comment by jasonm23** [comment]
Please note I realise this is documented in the Manual at:

> Create a new branch. The user is asked for a branch or arbitrary revision to use as the starting point of the new branch. When a branch name is provided, then that becomes the upstream branch of the new branch. The name of the new branch is also read in the minibuffer.

However, this isn't in line with the Git concept of upstream.

**Comment by jasonm23** [comment]
(note git manual https://git-scm.com/book/en/v2/Git-Basics-Working-with-Remotes#Pushing-to-Your-Remotes)

Upstream is synonymous with remote, not parent branch.

**Comment by tarsius** [comment]
> However, this doesn't appear to be in-line with the Git concept of upstream.

I don't think that Git's terminology and concepts are that good in this area, and following it strictly is not a priority and would actually hinder progress. See #1485 and the blog posts it links to for more information.

I do intend to follow Git's idea of how that is supposed to work more closely as far as that is necessary to avoid surprises.

I do intend to do that in one go. As I said above I will deal with the whole branching/pushing issue in v2.4. All releases starting with v2.1 now have a slogan and  for this release  it is: "Deal with the fact that everyone has a different opinion on how branching and pushing should work." I do not want to make incremental changes, because each of the intermediate steps could be one user's "and now you completely broke it moment".

I will implement what I feel is the right thing to do, and document it, including discussions of many of the issues which have been raised since the release of v2.1. Users can then comment on that, and a few revisions later it will be merged to `master`.

**Comment by jasonm23** [comment]
If that's your intention, so be it, but surely the best solution is to make the outcome flexible/configurable?

I'm a bit late upgrading so many changes have hit me all at once. (I appear to have hit a MELPA version 90150116 a LONG time ago so new upgrades weren't kicking in.)  As such I'm maybe 2 years out of date in the land of Magit.

That said, **Upstream** really feels incredibly wrong as a parent brach to me, since I would literally never push to a parent, because that's what merge (and rebase) are for.  The usual action of Push is always to remotes.

I hope you could agree that making this behavior configurable is the best way forward, and pull requests to this end would be considered.

**Comment by jasonm23** [comment]
Hopefully things that have become widely used in different ways will be configurable.

(deleted my previous verbose comment in favor of a one liner.)

**Comment by tarsius** [comment]
Yes. These these things will be configurable.

**Comment by jasonm23** [comment]
Is there an open issue covering this already, or is this part of a huge development branch?

**Comment by npostavs** [comment]
Isn't this already configurable via `(setq magit-branch-arguments (remove "--track" magit-branch-arguments))`?
https://github.com/magit/magit/issues/2009#issuecomment-120326318
https://github.com/magit/magit/issues/2009#issuecomment-122024689

**Comment by jasonm23** [comment]
@npostavs that would just turn off branch tracking, right?

**Comment by jasonm23** [comment]
I'm concerned that the default should be no tracking at all.  Configurable to track the commonly used working styles.

**Comment by tarsius** [comment]
I really very strongly recommend you read them two blob posts I have been mentioning:

1. https://felipec.wordpress.com/2013/09/01/advanced-git-concepts-the-upstream-tracking-branch.
2. https://felipec.wordpress.com/2014/05/11/git-triangular-workflows

**Comment by npostavs** [comment]
> that would just turn off branch tracking, right?

It prevents setting the parent branch as upstream, if it's not a remote (i.e. git default behaviour).

**Comment by jasonm23** [comment]
@tarsius I read them already.  

It definitely doesn't help that Felipe's fork is not likely to ever merge into Git core.

I don't have any argument with including such a workflow as an optional config, but as a default it seems out of place.
