### ISSUE TITLE
Commit workflow silently aborts when user.name+user.email are defined in git

### ISSUE THREAD

**Issue by MikeSanMichel2** [magit/magit#2308]
I use separate accounts for different uses and as a precaution have no default
set in ~/.gitconfig. I often forget to set name/email before trying to commit my first commit.
In the shell this results in a clear error message but magit silently aborts the commit
without any hint to the user what the problem is.

Repro:
1) unset global user/email
2) create new repo
3) stage something
4) Status/Commit/Commit

Result: 
back in the status window instead of commit message editor, no warning
in minibuffer or otherwise.

**Comment by kyleam** [comment]
When I try this, I see the message

    empty ident name not allowed ... [See buffer *magit-process: /tmp/noname/* for details]

and the process buffer displays

    128 git … commit --

    *** Please tell me who you are.

    Run

      git config --global user.email "you@example.com"
      git config --global user.name "Your Name"

    to set your account's default identity.
    Omit --global to set the identity only in this repository.

**Comment by kyleam** [comment]
When I try this, I see the message

    empty ident name not allowed ... [See buffer *magit-process: /tmp/noname/* for details]

and the process buffer displays

    128 git … commit --

    *** Please tell me who you are.

    Run

      git config --global user.email "you@example.com"
      git config --global user.name "Your Name"

    to set your account's default identity.
    Omit --global to set the identity only in this repository.

**Comment by MikeSanMichel2** [comment]
Ok, bad interaction with a git-filenotify hook which clobbers that message. 

The minibuffer message is a bit cryptic, and magit *could* simply ask for the missing
information, perhaps as part of a "Config" popup.

If the maintainers don't agree, feel free to close.

**Comment by tarsius** [comment]
> Ok, bad interaction with a git-filenotify hook which clobbers that message.

`magit-filenotify`? I recommend against using it. Also you might want to set `magit-revert-buffers` to `silent`.

> The minibuffer message is a bit cryptic,

We just pass on what git had to say on the matter.

> and magit could simply ask for the missing information, perhaps as part of a "Config" popup.

It's not quite that simple. This is different from a password prompt where git is waiting for us to provide some information. Instead it has already failed due to invalid configuration. What *you* could do however, is to advice the pushing commands to assert that these variables are set, before attempting to push.

> If the maintainers don't agree, feel free to close.

Yes. I don't think we should do anything here.

> I use separate accounts for different uses

What's a "use"? Do you assume different identities within the same repository? If not, and you just want to use a different name and/or email in certain repositories, then just configure those things on a per-repository level instead of globally.

**Comment by MikeSanMichel2** [comment]
> What's a "use"? 

occasion.

> you might want to set  magit-revert-buffers to silent.

I did want to, thanks.  

> just configure those things on a per-repository level instead of globally.

I do, as mentioned this in the OP. It's when I forget to add the missing locally *and* 
there's no global default, that I got bit by filenotify->revert-buffers>clobbering the error
message from git.
