### ISSUE TITLE
Cannot determine a suitable Emacsclient on OS X built with mac homebrew

### ISSUE THREAD

**Issue by jasonblewis** [magit/magit#2318]
Hi,

I have just rebuilt emacs on OS X using mac homebrew and I updated to the latest package of magit

    Magit 20151003.2156, Git 2.3.8 (Apple Git-58), Emacs 25.0.50.1

I see this message when I start emacs:

```
Warning (with-editor): Cannot determine a suitable Emacsclient

Determining an Emacsclient executable suitable for the
current Emacs instance failed.  For more information
please see https://github.com/magit/magit/wiki/Emacsclient.
```

I built and installed emacs with

    brew install emacs --HEAD --use-git-head --with-cocoa --srgb

and after building I copied the app to /Applications as this is the only way I have found to make it show up in spotlight.

emacsclient ends up being here:

    /usr/local/Cellar/emacs/HEAD/bin/emacsclient

**Comment by tarsius** [comment]
Please also see http://magit.vc/manual/with-editor/Debugging.html.

**Comment by jasonblewis** [comment]
Thanks, output from with-editor-debug is:
```
    /Applications/Emacs.app/Contents/MacOS (t)
    /usr/bin (t)
      /usr/bin/emacsclient (22.1)
    /bin (t)
    /usr/sbin (t)
    /sbin (t)
    /usr/local/Cellar/emacs/HEAD/libexec/emacs/25.0.50/x86_64-apple-darwin15.0.0 (t)
```

also emacsclient appears to be installed to /usr/local/bin:
```
/usr/local/bin/emacsclient --version
emacsclient 25.0.50
```

**Comment by jguenther** [comment]
Is `/usr/local/bin` in your `PATH` environment variable?

**Comment by tarsius** [comment]
@jasonblewis There should have been more output than that.

**Comment by jasonblewis** [comment]
@tarsius that was all the output there was.
@jguenther yes, /usr/local/bin is in the path. at least in the path according to emacs when i do a (getenv "PATH"). I usually run emacs from spotlight, which means it ends up with a slightly different path than if I run it from the cli

**Comment by tarsius** [comment]
Have a look at the definition of `with-editor-debug` - it's unlikely that what you posted is the complete output. It probably is the end of the output and the beginning of the buffer was scrolled "off-window".

**Comment by tarsius** [comment]
> after building I copied the app to /Applications as this is the only way I have found to make it show up in spotlight.

Overlooked that so far.

That's not a good idea. (And since you were suspecting that it might be the cause it would have been a good idea to revert that and try, instead of first involving us.)

Moving installed files around like this after the fact, can cause all kinds of issues. For starters it will confuse the package manager which expects the files to be where it put it. Also some paths might get hard-coded in binaries and other files at compile time and if you move the files then those values won't be correct anymore.

Finally it breaks the hacks that `with-editor` uses to find the `emacsclient` executable, even though Emacs is in most cases packaged in a very un-unix-y way on OS X. (The general assumption would be that if `emacs` is in `/path/to/some/bin` then `emacsclient` is in that same directory. Unfortunately that's not the case for most Emacs packages for OS X.)

So move Emacs.app back to where it came from and instead use a symlink to tell spotlight about it. Alternatively you can set `with-editor-emacsclient-executable` manually. Search `Emacs.app` (which is a directory) for `emacsclient` and use that as value. That will fix the issue with Magit but does not address the other potential issues.
