### ISSUE TITLE
Add option to show process buffer whenever Git exits with nonzero status

### ISSUE THREAD

**Issue by timclassic** [magit/magit#2322]
After using Magit in anger for some time, I find myself wanting to see the Magit process buffer automatically when a Git command fails, and otherwise respect the usual Magit Process Popup Time setting.

If this is already supported, I have not yet found the option.

Thanks!

**Comment by tarsius** [comment]
Not quite what you are asking for, but Magit actually shows the error in the echo area. Problem is that you usually don't get to see that because the message gets shadowed by other messages about buffers being reverted. Set `magit-revert-buffers` to `silent` and you should usually see the error message from git.

**Comment by tarsius** [comment]
I hope that's good enough for you.

**Comment by timclassic** [comment]
@tarsius Yes, I think that will do nicely!  I will give it a shot.

I will let you decide the fate of this ticket.

P.S. Thank you for such an excellent tool.  Magit is a pleasure to use.

**Comment by tarsius** [comment]
> I will let you decide the fate of this ticket.

I am a bit trigger happy .... so close!

Feel free to reopen if the above turns out not to satisfy you, but note that I might not get to this soon in that case. The whole process log thing has to be overhauled a bit and I would like to do it in one go (and also don't feel it's urgent).

> P.S. Thank you for such an excellent tool. Magit is a pleasure to use.
