### ISSUE TITLE
Save part of change to index file by 3-way magit-ediff cause coding-system changed

### ISSUE THREAD

**Issue by aligua** [magit/magit#2326]
Magit 20151006.1359, Git 2.5.3, Emacs 24.5.1

my file in git is utf-8-unix, while I have (setq buffer-file-coding-system 'utf-8-dos) in init file.

after copy part change from unstaged buffer to index buffer, and choose y when quit from ediff to save content change to index file. Then after magit status refresh and commit, will see the commit message include every line of whole file because of coding-system changed to utf-8-dos.

if I (setq-default buffer-file-coding-system 'utf-8-unix), or if all the change from unstaged buffer is copied to index buffer, then this issue is not seen.

100% reproducing at my side.

**Comment by tarsius** [comment]
If you do not explicitly set the coding system and eol style in either Emacs or Git, then both of them have to guess and usually they both get it right. If you do explicitly instruct one of them to use something else, then you will have to do the same for the other.

It's probably easiest to go back to not configure this at all. Otherwise learn about both sides at http://www.gnu.org/software/emacs/manual/html_node/emacs/Coding-Systems.html *and* http://git-scm.com/docs/git-config (`core.eol`, `core.safecrlf`,...).

**Comment by aligua** [comment]
Seems you are right, after remove both of bellow in my init file the report issue is not seen. 
(setq buffer-file-coding-system 'utf-8-dos)
(prefer-coding-system 'utf-8-dos) ;;this line need remove also because itself can cause emacs to set "buffer-file-coding-system” global value to utf-8-dos -- my observation.

 I should have no coding system configuration in git side.

I will settle to current "none configuration" at all for a while until I see anything incompatible. Maybe in years before there is some reason cause me to explicitly set coding system... 
if you want to close this report and I will be fine :). thanks for help!

**Comment by tarsius** [comment]
You're welcome.
