### ISSUE TITLE
How to setup with-editor-mode inside editor buffer

### ISSUE THREAD

**Issue by domtronn** [magit/magit#2336]
Hi, I'm looking to use `with-editor` with [`ghi`](https://github.com/stephencelis/ghi) to open new GitHub issues, which I've got working and uses the current emacsclient as the EDITOR. However, it behaves differently to the `git-commit` style one in that it doesn't have the `with-editor-mode` bindings or the font lock styles...

I'd like to enable `with-editor-mode` and run `git-commit-setup-font-lock` inside the `GHI_ISSUE` editor buffer but don't know how to or whether there are hooks I'm expected to use?

So far, I've copied magit's implementation for [`magit-commit`](https://github.com/magit/magit/blob/master/lisp/magit-commit.el#L127-L136) and ended up with something like this...
```lisp
(defun magit-gh-issues-start-ghi (&rest args)
  "Use magits process to run ghi ARGS with an editor."
  (run-hooks 'magit-pre-start-git-hook)
      (process-buffer
       (apply #'magit-start-process magit-gh-issues-ghi-executable nil
              (-flatten args))))

(defun magit-gh-issues-open-issue ()
  "Open an issue using ghi."
  (interactive)
  (with-editor "GIT_EDITOR"
    (let ((magit-process-popup-time -1))
      (magit-gh-issues-start-ghi "open"))))
```
_(the full package I'm working on is available [here](https://github.com/domtronn/magit-gh-issues.el), and still very much just playing around!)_

But I'm unsure where/when/how I can start interacting with the `EDITOR` buffer that gets created... Would anyone be able to advise on this? Any information would be greatly appreciated!

**Comment by tarsius** [comment]
You'll have to arrange for `with-editor-mode` to be enabled when Emacs opens the file. You have to use some mechanism which is triggered when a file is opened. Look at `git-rebase.el` and `git-commit.el` for examples.

`git-rebase.el` arranges for the major-mode `git-rebase-mode` to be used for files whose name match `"/git-rebase-todo\\'"` by adding an entry to `auto-mode-alist`. `git-rebase-mode` turns on the minor-mode `with-editor-mode`.

`git-commit.el` cannot use `auto-mode-alist` because `git-commit-mode` is a minor mode. So it implements a global-mode `global-git-commit-mode` which adds `git-commit-setup-check-buffer` to `find-file-hook`. That function then checks whether it is appropriate to turn on `with-editor-mode` for a given buffer, whenever a file is being opened. If so it calls `git-commit-setup`, which turns on `with-editor-mode` and does a bunch of other things.

**Comment by domtronn** [comment]
I considered using the `auto-mode-alist` but defining a major-mode seemed a little overkill.. But that's definitely enough information for me to play with and see which solution I like.

Thank you for the help @tarsius!

**Comment by tarsius** [comment]
I had a (very) quick look at your code, and would like to suggest that you fix the numerous whitespace errors.
