### ISSUE TITLE
Advanced integration with Helm

### ISSUE THREAD

**Issue by ghost** [magit/magit#2359]
I've been working on a helm wrapper for git(log,refs,tags,foo) which I'd like to use as a replacement for both magit's completing-read and log-select.

With Helm you get the following for free:
1. List of all commits (magit-log-select provides this, completing-read does not)
2. Easily configure commit display format, including multi-lines per entries (to see commit bodies)
3. Filtering/search (neither provides this), with (2) this can be according to author, date, subject or commit message body.
4. A ready-made UI convention for treating multiple "sources": commits, branches, tags.
These appear as individual sections within the helm buffer.

Two issues emerged when I tried to force magit to use this:
1. Magit isn't consistent about its use of log-select vs. completing-read for choosing a [commit-ish](https://stackoverflow.com/a/23303550) ("r r" launches git select, "A A" launches a completing-read for example).
2. Magit uses completing-read to prompt the user for various kinds of *things*: commit, branch, remote and unless the completion handler sniffs the prompt I've not found an easy way to figure out what kind of thing magit is prompting for, so I can prompt the user with the most relevent list first.

```
> ag magit-completing-read 
lisp/magit-commit.el
325:    (magit-completing-read prompt keys nil nil nil 'magit-gpg-secret-key-hist

lisp/magit.el
977:    (magit-completing-read
1244:           (magit-completing-read (format "Reset %s to" branch)
1341:     (list branch (magit-completing-read
1484:   (let ((file (magit-completing-read "Checkout file"
1650:    (magit-completing-read prompt choices nil t nil nil
1674:    (_ (magit-completing-read
1828:   (list (magit-completing-read "Set notes ref"
1852:   (list (magit-completing-read "Set additional notes ref(s)"
1877:  (magit-completing-read prompt (nconc (list "refs/" "refs/notes/")
1967:   (list (magit-completing-read "Deinit module" (magit-get-submodules)
2233:             (reply (magit-completing-read "Git repository" repos)))

lisp/magit-diff.el
659:                (let ((main (magit-completing-read "View changes along"

lisp/magit-ediff.el
98:     (list (magit-completing-read "Resolve file" unmerged nil t nil nil
127:   (list (magit-completing-read "Selectively stage file" nil
<...>
```

Could magit provide hooks that would help me implement nicer completion? One possible solutions would be to have a dedicated `(defun magit-complete-things (types ...))` that delegates to `magit-completing-read` but which is overridable through a var or by redefining it.

Just to show you it could be quite nice, here's a gratuitous Screenshot:
![helm-git-log2](https://cloud.githubusercontent.com/assets/14960200/10700941/cf14a6e6-79c9-11e5-8756-74f8cad9d6df.png)

**Comment by tarsius** [comment]
> A ready-made UI convention for treating multiple "sources": commits, branches, tags. These appear as individual sections within the helm buffer.

That sounds useful, I could see myself using that and current users of both Helm and Magit will certainly love it.

---

The completing-read vs. log-select issue is secondary, which is why I changed the title of this issue. But let's get that out of the way first:

Emacs standard completion interface cannot be used for what `magit-log-select` is used for. There's no inconsistency when just taking features available in vanilla Emacs into account. This function does *not* allow the user to select an arbitrary commit ("with completion") it show a log (ordered list) of the commits leading to HEAD. In fact I don't think of it as a completion function at all, which explains why it has "log" in it's name, but not "complete".

Helm's completion UI looks quite similar to that of Magit's log-select functionality, so it could be used to implement that. But since Helm isn't part of Emacs, Magit doesn't do that.

I think it would *not* be desirable to narrow down the available "candidates", as Helm usually does, when the user types some characters. This feature is really used for "going back a few commits and selecting one of them" and I feel that it makes sense to keep showing all the commits because even though just one commit is selected what then happens is that Magit acts on *all* commits from the beginning of the buffer to point (at least their hashes will change).

So I would suggest you focus on completion first and handle this case later. Anyway it shouldn't be much harder than simply redefining `magit-log-select`. That redefinition could be a simple wrapper around your completion function. (Well except that you might want to avoid the narrowing as I suggested and I don't know how easy that would be in Helm.)

---

As far as I know most of the commands provided by Helm are *substitutes* for command in Emacs and third-party packages. There is no general mechanism in Emacs which would be flexible enough to just plug in Helm or some other completion package. For Ido that kinda works, but Helm departs further from standard completion (i.e. the "multiple sections of different types" thing). So it is to be expected that it's not trivial to add Helm support for some package, there's no standard way to hook into existing code to do this sort of thing.

But Magit does make this easier, not as much as you appear to have hoped, but still. All completion goes through `magit-completing-read` which uses the function specified by `magit-completing-read-function` to do it's job. So there is a single place to plug in your variant - you won't find that in many other packages.

You mention that your function would have to sniff the prompts to figure out what kind of completion is taking place. Similarly you could use `this-command`. I don't really see an alternative to such an approach and it doesn't sound all that terrible to me actually.

**Comment by MikeSanMichel2** [comment]
> Emacs standard completion interface cannot be used for what magit-log-select is used for. There's 
> no inconsistency when just taking features available in vanilla Emacs into account. <...> I don't think
> of it as completion [because it doesn't allow arbitrary commits]

I disagree. Completion as an interaction is a distinct issue from having a closed list of candidates or not. reading-complete should show information about the commit like log-select does. log-select
should let you filter and search like a completing-read does (in helm, anyway).

Of course it's vanilla emacs doesn't provide this. but helm does. The question is only will magit make it easier to provide this functionality by using to more generic interfaces internally.

So, perhaps a secondary issue (to you) but having a single consistent UI for both would be a win.

> I think it would not be desirable to narrow down the available "candidates"
> <...>
> So I would suggest you focus on completion first and handle this case later. 

Actually, I care about it, and I want to have it. Which is why I've already implemented it. But I agree that users who don't want this shouldn't be forced to. 
Also note there's no such thing as "no narrowing" in helm afaict, it's a narrowing framework.
This isn't a problem either,  unless what youre saying is that you want to absolutely **forbid** this from users (which I would dutifully ignore). If not, that's just a premature argument about defaults. Users should have the choice. 'nuff said.

> You mention that your function would have to sniff the prompts to figure out what kind of 
> completion is taking place. Similarly you could use `this-command`. I don't really see an alternative > to such an approach and it doesn't sound all that terrible to me actually.

The problem with this approach is that means each new command and new prompt require modifying the package. Any change in prompt can break the package. Any rename of internal function can break the package. It's a PITA in terms of maintenance which is only there because
magit isn't cooperative and was written with vanilla emacs in mind, hence tightly-coupled to its notion of how things works. Making some minor changes would allow for more flexibility.

What do you think about the solution I proposed, which is to simply add another layer of indirection
that carries the exact information I now have to sniff and guess for? If that information is part of the API, no extra effort will be needed to support new versions of magit.

**Comment by stardiviner** [comment]
`read-completing` is good. Helm can use it.

**Comment by npostavs** [comment]
> read-completing is good. Helm can use it.

You mean `completing-read`?

Notice that Emacs has both `completing-read` for reading a general string and `read-file-name` for reading a certain kind of string (and `read-directory-name` for a slightly different one).  IMO, it's a good idea for magit to distinguish between the different kinds of string it's reading (whether that happens through an extra arg, or using different completing functions).

**Comment by MikeSanMichel2** [comment]
Helm does override completing read, yes. All the issues I noted still apply though.

**Comment by tarsius** [comment]
> Completion as an interaction is a distinct issue from having a closed list of candidates or not. reading-complete should show information about the commit like log-select does. log-select
should let you filter and search like a completing-read does (in helm, anyway).
>
> Of course it's vanilla emacs doesn't provide this. but helm does

Agreed, that could be useful. In a way I am already doing this now sometimes. I use Isearch to quickly go to a commit based on commit summary. Of course that means that there is no narrowing (which I prefer, because I still see "how far back" I am going) but narrowing obviously has other advantages, e.g. the consistency you brought up.

So I have no objects to you doing that, but I would appreciate if you could add an option for this, because I could see myself using the helm completion for other things, but probably not in this particular case. 

> So, perhaps a secondary issue (to you) but having a single consistent UI for both would be a win.

By calling it a secondary issue I really just intended to first tackle the other issue which is a prerequisite for this one. Regardless if I make any changes to accommodate your needs concerning the other issue (see below) there's really not much to be done here. You made it sound like big changes were needed here too, which I think is the case. So I said "let's concentrate on the other thing, because there is need for discussion". The question here is only whether I will provide a `magit-log-select-function` option. If not, then you have to add this:

```lisp
(defvar helm-magit-use-helm-for-log-select t)

(defun helm-magit--magit-log-select (fn pick &optional msg quit branch)
  (if helm-magit-use-helm-for-log-select
      ;; Translate from `magit-log-select' to `magit-completing-read'.
      ;; Alternatively you could call `helm-magit', or whatever your
      ;; entry point is directly.
      (magit-completing-read msg
                             (helm-magit--ordered-list-of-commits branch)
                             nil t)
    (apply fn args)))

(advice-add 'magit-log-select :around #'helm-magit--magit-log-select)
```

Yes, this still has the issue that you need to somehow derive meaning from MSG, but that's really the other issue, which is why I called this one "secondary" and said that we should first talk about the other.

If I add a hook then this gets slightly easier:

```lisp
(defun helm-magit-log-select (pick &optional msg quit branch)
  (magit-completing-read msg
                         (helm-magit--ordered-list-of-commits branch)
                         nil t))

(setq magit-log-select-function 'helm-magit-log-select)
```

Just one last thing: you have to make sure the commits are presented in the correct order. Candidate narrowing will then hide some commits, but initially all recent commits should be visible in the correct order.

**Comment by tarsius** [comment]
> Which is why I've already implemented it.

Could I please get access to your code? Then I would not have to make assumptions about it.

**Comment by tarsius** [comment]
> > I don't really see an alternative to [the sniffing] approach and it doesn't sound all that terrible to me actually.

> The problem with this approach is that every new command [in magit] that prompts with a new prompt requires a modification to the [helm-magit] package.

Likewise every new select-from-a-specific-set-of-candidates function in magit will require changes to helm-magit, and so does every change (bugfix, improvement) to every such function. I think that whatever approach we take you will have to adjust your code in responses to changes in magit. 

> Basically, It's a PITA in terms of maintenance which is only there because magit was written with vanilla emacs in mind, hence is tightly-coupled to emacs' notion of how things work. A bit of refactoring would provide more flexibility. ...  If that information is part of the API, no extra effort will be needed to support new versions of magit.

This is not "a bit" of refactoring but a *major* effort. You are downplaying the difficulties of designing a suitable interface and the work involved in making all existing code conform to it.

I actually think this is much more difficult and much more work, then what is involved in then using that interface in `helm-magit`.  So is is true if I do this, then you get a lot of things "with no extra effort", but force a lot of "extra effort" on *me*. Since you are the one who wants advanced helm support now, you should share a lot of that effort.

I have thought about advanced helm support too in the past and would also like to have it. Currently I am using Ido (with `ido-vertical`) which is good enough for me, but I would also like to have different "sections" for tags, branches etc.

I just don't think this is essential and have decided to work on other, in my eyes more important things first, exactly because I expect this to be a lot of work

> What do you think about the solution I proposed, which is to simply add another layer of indirection

This is very abstract. Keeping it similarly abstract and vague I would say that I generally avoid "adding another layer of indirection" as doing that often ends up increases complexity instead of reducing it as intended.

> that carries the exact information I now have to sniff and guess for?

Please let me see that code, so that I can see what problems this is causing for you. I mean I can totally see how that's inconvenient, but it might help your case if I got to see *how* inconvenient exactly (also I might, or not, have tips on making it less inconvenient). 

> If that information is part of the API, no extra effort will be needed to support new versions of magit.

As I currently understand it you want me to replace each and every call to `magit-completing-read` into a separate named function. Is that correct, or what would that api you are talking about look like.

The best course of action would probably be if you created a fork of magit in which you implemented a proof-of-concept. I expect that you would find that this is much more difficult than you expected, but I would love to be wrong about. Maybe don't start with a complete api and in a first step just make a few (simple and complex) uses of `magit-completing-read` conform to your idea of how this api should look.

**Comment by tarsius** [comment]
> As I currently understand it you want me to replace each and every call to `magit-completing-read` into a separate named function. Is that correct, or what would that api you are talking about look like.

If that actually is what you had in mind, then you will pleased to hear that I have actually worked toward that goal in the past - see the various "read branch (or some kind) and/or commit" functions. Unfortunately it then turned out that these functions were oversimplifications, a lot of commands that used these have since been changed back to use `magit-completing-read` directly. This really ain't trivial, there simply isn't some fairly small set and final set of completion-sets that we just have to extract and put a name on, in order to provide a stable api.

**Comment by MS-M2** [comment]
Please forgive me for abruptly shifting avatars. I've decided to leave Github but it just seemed too rude to simply leave in the middle of a conversation but I'll be dropping this and will simply hack something locally instead.

To set the record straight:
1. no special effort is needed to present commits in order with helm, that's how it works.
2. no special knob needed to "disable narrowing". Helm buffers also work as a list you can navigate.

Now, for hte last misunderstanding between us, you wrote:
> every new select-from-a-specific-set-of-candidates function in magit will require changes to 
> helm-magit, and so does every change (bugfix, improvement) to every such function.
> <...later...>
> As I currently understand it you want me to replace each and every call to magit-completing-read > into a separate named function. If that actually is what you had in mind <...>

It isn't. In the OP I suggested that
> One possible solution would be to have a dedicated (defun magit-complete-things (types ...))

My emphasis was on an additional `types` argument, which I imagine as a list drawn from the finite, stable list of git `things` (`:git-commit`, `:git-branch`, `:git-ref`, etc'). This solutions would inflict minimal maintenance burden for a `magit-helm-complete` package, short of the rare addition to git taxonomy.  You claim I underestimate the effort involved to do this on magit's side, I still think this is a day's work followed by an inevitable period of light clean up duty. I would have helped. Of course you're in a far better position to judge.

Thank you again (and again...)  for your remarkable work on magit and your superhuman patience when dealing with users and their endless stream of strong opinion.

[Exeunt]

**Comment by tarsius** [comment]
> Please forgive me for abruptly shifting avatars.

Heh. That was indeed a bit surprising, but I did not realize you deleted your account, just thought you renamed yourself to @ghost and picked an appropriate avatar. Surprised to hear it's possible to keep commenting after deleting one's account - how does that work!?

> In the OP I suggested that

Indeed I forgot about that.

> My emphasis was on an additional `types` argument, which I imagine as a list drawn from the finite, stable list of git `things` (`:git-commit`, `:git-branch`, `:git-ref`, etc').

I can work toward that goal, though I will probably prefer basic wrappers like `magit-read-THING`. Such functions already exist for some things, but they are not used consistently. Also there should probably be a basic layer (as you suggest, I think) of such functions, which support all the arguments that `magit-completing-read` supports. Currently these functions are more specialized than that.

**Comment by tarsius** [comment]
> I'll be dropping this and will simply hack something locally instead.

I am closing this issue in response. But I'll keep this in the back of my head and there will probably be improvements in this area. But it will take some time. Feel free to send a reminder after a while, if nothing happens.

Have a nice day!
