### ISSUE TITLE
Instant Fixup should reset head on abort

### ISSUE THREAD

**Issue by ghost** [magit/magit#2362]
When Instant Fixup results in a conflict and the user aborts the final state is that head
has moved forward to a new fixup! commit. This is consistent with what git does but the behaviour
is something I always found annoying because I usually need to remove a hunk before trying again.

Would you consider changing it?

**Comment by tarsius** [comment]
I think this would be quite hard to implement (how would `magit-rebase-abort` know that is part of a failed instant fixup?) so I do not think this is worth the effort.

**Comment by tarsius** [comment]
Also I feel that this would only be useful when one picked the wrong commit as target to begin with. What is more likely is that the correct commit was picked, that unexpectedly resulted in conflicts, and one doesn't want to deal with it right now. In that case I would find it much more useful with the fixup commit is preserved, so that one can go on creating new commits from the not yet committed changes, and only then rebase again, this time with the intention to deal with the conflicts.

**Comment by tarsius** [comment]
Does op want to further argue in favor of the proposed change? Or does anyone want that change? Otherwise I am going to close this.
