### ISSUE TITLE
Magit v2.3.0 leaks information to remote servers without user opt-in

### ISSUE THREAD

**Issue by DolphinDancer** [magit/magit#2369]
https://github.com/magit/magit/blob/c0a8521e5b1e9e3684d56b2f77a82dbaab615f59/Documentation/RelNotes/2.3.0.txt#L78

I don't like the fact that Microsoft records my actions and installed software and sends it to their servers without my knowledge, so I don't use their software.
I don't like the fact that google tracks me as I visit websites they do not own anywhere on the web,
so I have blockers that disable google analytics.
I don't like the fact the facebook "Like" button pings facebook whenever I visit a page anywhere,
which is why I block that as well.

A new feature in Magit 2.3.0 will phone gravatar.com everytime I view a diff, It does not ask me
whether it should and it is on by default.

What I do on my computer is my own business and inless I explicitly ask it to or agree to it, the software I use shouldn't access the network without my knowledge to tell a 3rd anyone what I'm studying/working/interested/thinking on/in/about.

Emacs is a historical piece of software that sits at the heart of the free software movement. It's a sad surprise to discover I must audit high-progfile Emacs packages like magit to protect myself against such violations.

Please know that this is not a personal attack against you or your values. I do want you to know I care deeply about this and that to me it constitues a violation of an unspoken agreement, a dangerous precedent, and a departure from the culture norms and the respect for users I've become accustomed to in savy Emacs developers. 

Please reconsider this decision and turn the feature off by default.

**Comment by tarsius** [comment]
This feature, like many other new and more harmless features, was enabled by default, because many users don't notice new optional features if they are disabled by default, because they don't read documentation and release notes. The idea is that users who don't like the new feature, will notice and won't have much problems disabling it, while users who don't know that there is a new feature won't go looking for it. But I guess in this case the privacy concerns outweigh this logic.
