### ISSUE TITLE
Potential dependency misconfiguration

### ISSUE THREAD

**Issue by Ecno92** [magit/magit#2386]
I just tried to download the latest packages with Cask and it failed with the following output:

```
../.cask/bin/cask
Dependency magit failed to install: Need package `with-editor-20151111', but only 20151028.1203 is available
Output:
```

Also when I look at Melpa and click on the `with-editor 20151111` dependency I see that I get forwarded to `with-editor 20151028.1203` (You can try out here: http://melpa.org/#/magit) 

I have the idea that there was a misconfiguration in the following commit:
https://github.com/magit/magit/commit/890fa78c82caee710eec909cad6e0cc338df4ef9

Can someone have a look at this?

**Comment by tarsius** [comment]
It takes several hours for Melpa to build all packages from the Magit repository because they are neatly distributed across the alphabet. There's nothing I can do about it, except adding a FAQ entry, which I will do shortly. When we bump "internal dependencies", then the packages on Melpa break for a few hours. This is something that would have to be addresses on the Melpa side.

**Comment by purcell** [comment]
Or just generally making the MELPA build faster or more parallel. In any case, this sort of issue will be a rare occurrence which I don't think we should write extra code to mitigate.

**Comment by tarsius** [comment]
> Or just generally making the MELPA build faster or more parallel.

He! Or  as I just said on a completely unrelated issue (expect that it also was about performance): "I am always in favor of fixing the real issues instead of adding kludges that work around the issue". So I totally understand you would rather do the former here too :-)

> In any case, this sort of issue will be a rare occurrence which I don't think we should write extra code to mitigate.

Actually *every* time I make a release *at least* one user reports that the dependencies are broken. Since I am getting better at releasing often, this is starting to be an issue for me.
