### ISSUE TITLE
Windows performance

### ISSUE THREAD

**Issue by fommil** [magit/magit#2395]
Somewhat related to #2104 I've been using magit at work recently, forced to use git 2.1 on windows 7. It is unfortunately incredibly slow, I guess due to a fixed overhead in talking to the git process.

I was wondering if windows performance is on your roadmap.

This is something I'd be willing to fund (£1,000 ish budget) as it impacts me so much. Maybe we can get others to join the fund?

It might be possible to use appveyor to automate performance testing, plus local copies of virtual box running windows 7. I've created a windows XP image that you are welcome to use, but I'd really like the create a windows 7 for for my own testing of ensime.

**Comment by fommil** [comment]
(see #2219 for a partial workaround)

**Comment by Silex** [comment]
Just curious, is git from the command line "fast"?

**Comment by fommil** [comment]
once file caching and so on is added, its pretty fast yes. Not instant, but maybe 1 second for a git status, which is reasonable given how gigantic my project is.

**Comment by tarsius** [comment]
@fommil Thanks for the offer. But it's hard for me to accept it, because while I intend to turn my focus toward performance once v2.4 is released, I also expect that progress will be slow.

I will do some benchmarking and maybe that will reveal some low-hanging fruit, but generally I expect that major architectural changes will be necessary to really get anywhere. I am still doubtful that Windows is the issue here and testing performance in a virtual machine seems suboptimal. In any case I intend to first make improvements that effect all systems before I turn to Windows specific tweaks (which I currently believe builds down to "call git less often", which is something I would want to avoid (it would complicate the code, which in turn would complicate refactoring) if not absolutely necessary (i.e. if the other improvements are good enough).

So I cannot accept this offer in its current form at the current time. I would still appreciate a (likely smaller) donation of course :-) I might get back to you on this offer some time in the future though.

**Comment by fommil** [comment]
OK. Yeah I suspect there in a fixed overhead in calling git on windows. I will still let you know about the virtual image because some things are just broken on windows and I should file reports for them.

**Comment by fommil** [comment]
FYI I found the root upstream cause of this: https://github.com/git-for-windows/git/issues/596

In terms of magit performance on windows, it may make sense to write a shell script that does various "slow" operations like all the `magit-status` calls. Then it could be possible to rewrite that script natively and get a big performance boost for all platforms (but Windows will always win the "best improved" award)

**Comment by kjeremy** [comment]
`git gui` on Win 7 x64 constantly freezes for seconds at a time and I wonder if it's related.
