### ISSUE TITLE
Why does magit-popup turn on async-bytecomp-package-mode?

### ISSUE THREAD

**Issue by Malabarba** [magit/magit#2404]
Hi Tarsius

I'm referring to this snippet:

    (and (require 'async-bytecomp nil t)
         (memq 'magit (bound-and-true-p async-bytecomp-allowed-packages))
         (fboundp 'async-bytecomp-package-mode)
         (async-bytecomp-package-mode 1))

I have the `async` package installed for use in Paradox, but I don't
want to use `async-bytecomp-package-mode`. I also don't think everyone
who has the async package installed will want to use this mode.

This mode has side-effects well beyond the Magit package, so I think
it shouldn't be enabled without the user's knowledge.

Cheers

**Comment by npostavs** [comment]
See #2156.

**Comment by tarsius** [comment]
As explained in the issue linked to by Noam, I just don't see an alternative in the short-run.

I've noticed that `package.el` from `master` and `emacs-25` now attempts to avoid old code leaking into new byte-compiled files (I haven't checked yet how successful it is at doing that though). That's nice and all, but it doesn't help users who don't use an Emacs development versions. It also doesn't help maintainers of third-party packages, because they have to support actually released Emacs versions.

I have also noticed that you have gotten active on emacs-devel and have made changes to the built-in `package.el`, so I am mentioning this here, in the hope you take it to emacs-devel: 

Please add a backport of `master`s `package.el` to GNU Elpa. That way maintainers of third-party packages can require the appropriate version of the `package` package, when they feel that it is necessary to do so to avoid leakage.

**Comment by Malabarba** [comment]
Thanks for the link. I'll have to read it later in the week.

On a side-note. If this is supposed to avoid problems upgrading from 1.x to 2.x, am I supposed to be seeing this code on the 2.x package?

> As explained in the issue linked to by Noam, I just don't see an alternative in the short-run.

I might be able to suggest a cleaner alternative after reading the thread. I ran into a similar problem with Names and solved it without using async.

> I've noticed that package.el from master and emacs-25 now attempts to avoid old code leaking into new byte-compiled files.
> Please add a backport of masters package.el to GNU Elpa. That way maintainers of third-party packages can require the appropriate version of the package package, when their experience tells them that it is necessary that leakage is actively avoided.

That's something I tried doing a while ago (it would be nice to expose to users not just the bug fixes but the new features as well), but it's not easy. The current implementation of package.el relies on some details of the Emacs build that didn't exist in 24.1.

However, I am currently thinking of another option. Maybe releasing a `package-compat` package which simply patches one or two functions in package.el, solely for the purpose of bug-fixing. Then packages like Magit could depend on this package.

**Comment by tarsius** [comment]
> Maybe releasing a `package-compat` package which simply patches one or two functions in package.el, solely for the purpose of bug-fixing. Then packages like Magit could depend on this package.

That would only work if loading `package-compat` would do no harm if loaded along with any `package.el` used in the wild, because `package.el` does not support conditional dependencies.

It would be nice if `package.el` supported something like:

```lisp
;; Package-Requires: ((or (emacs "25") (package-compat "1")) ...)
```

(Is `package` already a separate package? I would actually prefer this:)

```lisp
;; Package-Requires: ((or (package "2") (package-compat "1")) ...)
```

But even if a new version gained support for that, it would not help here because the old version of `package` which would have to install `package-compat` in order to understand `(or A B)` would have to already understand `(or A B)` do so without the help of `package-compat`, which obviously can't work.

So if you decide to go with the `package-compat` idea, then that would force every package (which wants to ensure that either a recent version of `package`, or some old version together with `package-compat`, be used) to install `package-compat`, even if `package` is at the very latest version.

So - without knowing anything about the complications in doing so - I would recommend backporting `package` itself instead. (And that conditional dependencies are implemented soon, so that we can start assuming their support in a few years. ;-)

**Comment by Malabarba** [comment]
> That would only work if loading package-compat would do no harm if loaded along with any package.el used in the wild, because package.el does not support conditional dependencies.

Yes, the file would be written in a way to only patch package.el if it needs patching, so it's always safe to just require `(package-compat "1")`. No need for complications.

For now this means the package wouldn't do anything if emacs-version >= 25. But, in the future, it could include other fixes for bugs we don't know now. Everything would be on a case-by-case basis.

**Comment by tarsius** [comment]
Looking forward to that. Thanks for the info.

**Comment by Stebalien** [comment]
It has now been five years since this issue. Can this be disabled?

**Comment by tarsius** [comment]
I still believe that the only way to *really* prevent an older loaded implementation to leak into the new byte-code is use a separate emacs instance for compiling. `package.el` still does not do that, so no.

**Comment by Stebalien** [comment]
Unfortunately, this breaks other packages. For example, I compile `lsp` with `lsp-use-plists` but async-bytecomp ends up compiling lsp in a fresh environment which doesn't have that variable set. This causes all kinds of errors at runtime.

Now, I can (and do) fix this issue by disabling async-bytecomp. But having a third party package unilaterally enable a minor mode because it's "more correct" is very frustrating.

On the other hand, I understand that this was the fastest way to fix magit, and I generally do agree that this behavior is "more correct". It's just really frustrating and totally undocumented. The only way to discover this behavior is by grepping the source of all installed emacs packages to figure out which one enabled async-bytecomp.

**Comment by tarsius** [comment]
In that case I am willing to reconsider.

I think we should have this discussion in a new issue in async's issue tracker.
