### ISSUE TITLE
Detect renaming of files/folders

### ISSUE THREAD

**Issue by f0086** [magit/magit#2407]
If I rename a file or folder, it will displayed as one file deleted and one untracked. If I stage the new file, it remain "new". In the commit message it will be shown as "renamed" (which comes from git). So It would be nice if the magit UI will also detect the renaming process.

**Comment by npostavs** [comment]
Dup of #1904 (already implemented).

**Comment by tarsius** [comment]
To do that set the respective switches when showing a diff (<kbd>d</kbd>) or in an existing diff buffer or in the diff buffer set them using the "change the diff arguments" popup which you can bring up using <kbd>D</kbd>.

```
 =m Detect renames (-M)
 =c Detect copies (-C)
```

You can also customize the switches to be enabled *by default*. Bring up the popup using <kbd>D</kbd>, change all the arguments to you liking, and then press <kbd>w</kbd>. Note that these arguments are not enabled by default because they affect performance, which is why they are not enabled by default.

**Comment by f0086** [comment]
Ah nice! Thanks for the detailed explanation!
