### ISSUE TITLE
Consider allowing customization of the prefix key for commit commands

### ISSUE THREAD

**Issue by kevinushey** [magit/magit#2424]
I'm sure that this is a somewhat rare use case, but I use Emacs + Evil, with `C-c` bound to behave more like the escape key through bindings in the `key-translation-map`. This, of course, does not bode well for the bindings generated by Magit, since many of them are prefixed with `C-c`, and this prefix is, as far as I can see, not customizable.

Would it be possible to make the prefix customizable? For example, projectile allows users to set the [`projectile-keymap-prefix`](https://github.com/bbatsov/projectile/blob/5773d28036c81f44468da58402a32463b278ee1f/projectile.el#L164-L167) to control this; would it be possible for Magit to gain something like `magit-keymap-prefix`?

I could try opening a pull request if this is something the Magit maintainers would consider merging.

Thanks!

**Comment by tarsius** [comment]
Please give https://github.com/justbur/evil-magit a try.

@justbur what is `evil-magit` doing about this?

**Comment by justbur** [comment]
`evil-magit` doesn't have anything with this yet, but I added [this](https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Bsource-control/git/packages.el#L307-L313) to spacemacs which makes `,c` commit and `,a` abort.

**Comment by justbur** [comment]
and I'd happily add custom `with-editor` keybindings to `evil-magit` if someone wants to suggest some.

**Comment by tarsius** [comment]
The situation isn't the same for magit as for projectile.

The `C-c C-c` and `C-c C-k` bindings and commands are defined in `with-editor.el`. So that would have to be changed there and would then affect all other packages which use it. Currently that's only `git-rebase.el`, I think, and someone who wants to change these bindings in `git-commit` would probably also want them to change in other users of `with-editor` anyway.

But `C-c C-c` is a very standard binding for "do it". It's not a binding one should fight with, because it's a fight that would have to carried out many times. The only users who would want to not use `C-c` as a prefix are those who use bindings that depart very very far from the default - which boils down to users of Evil. So these bindings should be changed in `evil-magit`, not here.

Projectile's `C-c p` is a dedicated prefix. That makes it easy to provide an option which allows using another prefix. `C-c` on the other hand is a standard prefix, which various magit libraries add bindings to in various places. Magit just assumes that `C-c` is always available and that's a safe assumption, except when Evil is involved.

**Comment by kevinushey** [comment]
Thanks -- I agree I am going against the grain here so I understand the onus is not on Magit to make this work.

@justbur, thanks for adding this to Spacemacs -- `,c` and `,a` feel quite natural.
