### ISSUE TITLE
Branch popup with lots of remotes

### ISSUE THREAD

**Issue by TheBB** [magit/magit#2432]
![](http://i.imgur.com/SWcQXnk.png)

This is a little ridiculous for my taste. I merge PRs from many contributors so it's handy to have many remotes. I know the popup isn't supposed to stay visible for long but still.

I tried changing to `nil` [here](https://github.com/magit/magit/blob/master/lisp/magit.el#L1581) and cycling with `p` still worked without problems (with feedback in the echo area). Can we maybe introduce something similar, possibly with a `magit-max-remotes` variable?

**Comment by tarsius** [comment]
I have just added `(toggle-truncate-lines t)` to `magit-popup-mode`, not just because of the issue you brought up but also to avoid breaking the arrangement in the Actions section when the window is a little to small.

Is that good enough for you?

You might also  want to consider not adding so many remotes. What I use instead is `magit-branch-pull-request` from my `magit-rockstar` package. That allows conveniently fetching a pull-request branch and creating a local branch from it, without having to add forks as remotes (which usually contain several outdated branches, making e.g. `lb` unreadable).

**Comment by TheBB** [comment]
That works for me, thanks. :+1:

I have tried `magit-gh-pulls` before, which kinda works but was disappointingly lacking. I assume yours is higher quality, so I'll have a look at it.

**Comment by tarsius** [comment]
> I have tried `magit-gh-pulls` before, which kinda works but was disappointingly lacking.

I completely agree and intend to write something better eventually.

> I assume yours is higher quality, so I'll have a look at it.

Well "higher quality" might be the wrong term. It's a tiny function, really not much more than the minimal viable implementation. But that could be seen as a strength. It's good enough for me at this time, and it might be for you too. Or not.
