### ISSUE TITLE
What happened to push quickly?

### ISSUE THREAD

**Issue by yamadapc** [magit/magit#2441]
I recently updated my installation of `magit` and found that `Pq` no longer worked. What happened? Are there plans to restore it?

**Comment by kyleam** [comment]
Please see #2414 and #2435 .

**Comment by yamadapc** [comment]
I don't really get it...
Is there a way to create a new branch and push/set the upstream quickly?

This is what I was using `P-uq` for after creating a new branch.

**Comment by kyleam** [comment]
To set and push to an upstream, you can now do
'P-ue <remote>/<current-local-branch>'.  The first entries of the prompt
will be your remotes with a branch name matching your current one, so
often this will just be 'P-ue RET'.  From then on, you can push with
'Pu'.

Another option is to set remote.pushDefault once for the repo ('b M-r').
Then, instead of the sequence above, you can use 'Pp'.  (If you want to
also set the upstream, you can add the -u in there on the first push.)
