### ISSUE TITLE
possible windows performance solution: jgit

### ISSUE THREAD

**Issue by fommil** [magit/magit#2442]
The problem with Windows is not entirely related to creating lots of git processes. Fundamentally, git is slow on Windows for operations such as rebasing and there is nothing magit can do about it.

Short of a rewrite of git on Windows (actually, it's not short of that at all...) a possible solution would be to use the Java implementation of git

  https://eclipse.org/jgit/

there is no CLI to jgit that I know of, but it should be possible to write one. The question is, what exactly is needed for magit to work or must it be a full 100% compatible CLI with all the bells and whistles?

**Comment by fommil** [comment]
oh, wow, turns out there is a CLI! https://wiki.eclipse.org/JGit/User_Guide#Building_the_JGit_CLI

OK, so this ticket really is then "please support the jgit binary".

**Comment by tarsius** [comment]
How is running `jgit` many times going to be faster than running `git` many times?

**Comment by tarsius** [comment]
But that's not what you are suggesting. It think that you are suggesting that Magit should communicate with a long-running Jgit instance in order to avoid having to start many processes. That might avoid a rewrite of Git but it would amount to a rewrite of Magit. This is not going to happen.

Instead I will focus on performance issues that affect all systems, starting next year.

**Comment by fommil** [comment]
um, no, that's not what I'm suggesting.

I'm suggesting using command line jgit, yes, but you're making a lot of assumptions about startup time for java processes (and Java processes in general, probably going back to same bad experiences in 1995). First of all, Java process startup is now very fast and can be improved further with nailgun (and you don't even need to know about how that works) and secondly the major performance problems on Windows are related to process forking **inside** git, not necessarilly from magit, so jgit does have the potential to hugely outperform git.

What I'm asking is for magit to be able to support the jgit set of commands, and not assume that its calling the official git binary.

**Comment by fommil** [comment]
Most importantly, nothing that you do to improve performance of magit is really going to impact Windows users because of the poor performance of git itself.

**Comment by Silex** [comment]
@fommil: can you run a few benchmarks (or link to some) comparing git vs jgit performances?

Except if I'm missing something, if it's really just a matter of using the jgit CLI instead of git, then it's just a matter of `(setq magit-git-executable "jgit")` which you can already test yourself.

**Comment by fommil** [comment]
Yes, but I'm not sure if jgit has 100% compatibility so I'd like to know what magit actually uses.

**Comment by fommil** [comment]
Yes I'd like to do some benchmarks, but it may be some time as the true test is on my work machine and they have strict controls about software. I'll try to do something on a VirtualBox over the holidays.

**Comment by tarsius** [comment]
I suspected that the `jgit` command only features very few porcelain commands. I don't have `jgit` installed, could you please list what it does offer?

**Comment by fommil** [comment]
https://github.com/eclipse/jgit I need to wait a few weeks to get it approved at work.

**Comment by tarsius** [comment]
By "list of porcelain commands" I meant "list of subcommands of the `jgit` command line utility", not "link to repository on github". I did use google. The best I could find was [this](http://wiki.eclipse.org/JGit/User_Guide#Running_the_JGit_CLI).

```
prompt$ ./jgit
jgit --git-dir GIT_DIR --help (-h) --show-stack-trace command [ARG ...]

The most commonly used commands are:
 branch   List, create, or delete branches
 clone    Clone a repository into a new directory
 commit   Record changes to the repository
 daemon   Export repositories over git://
 diff     Show diffs
 fetch    Update remote refs from another repository
 init     Create an empty git repository
 log      View commit history
 push     Update remote repository from local refs
 rm       Stop tracking a file
 tag      Create a tag
 version  Display the version of jgit
```

Note that this list of "the most commonly used commands" does include `daemon` but not `pull`, `merge`, or `rebase`. It's not a stretch to assume that when a list of "most commonly used commands" does contain `daemon` but not the other commands I mentioned, that those commands also aren't members of the complete list.

> I need to wait a few weeks to get it approved at work.

Assuming that you privately own a computer, you could save yourself, your employer, and me some work by installing JGit on you own machine first. Instead of installing JGit, you could also dive into the repository you linked to and try to compile the list of available commands from that.

For what it's worth, I strongly doubt that JGit would fulfill Magit's needs in a Git implementation. (Even versions of Git before v1.9.4 don't.) I would rather confirm this now than to wait a few weeks for the legal department of your employer. I think that hoping that `jgit` supports rebasing, is more wishful thinking than anything else. It cannot hurt to double check, but the odds are dim.

By the way, I am considering to use `libgit2` for some things. But that's a long shot; there isn't even an Emacs release with a ffi yet. But even if and when Magit started to use `libgit2`, it would continue to use subprocesses to perform rebases and merges. (As I am not actually interested in re-implementing large parts of Git just to improve performance. It's also highly unlikely that I would succeed at doing so if I tried.) So the use of `libgit2` would not actually address the particular issue you have brought up. Just mentioning this so that you know that I am evaluating the options and am planning ahead. I just don't think that JGit is among the viable options.

A long time ago and in a different context I have taken a closer look at JGit. I don't remember anything about feature parity being a goal, certainly not for `jgit`. I do however remember an interesting blog post by the maintainer in which he explains why certain nifty and highly effective performance tweaks used by the C implementation simply aren't possible in Java.

Please excuse the somewhat sarcastic tone.

**Comment by tarsius** [comment]
> you're making a lot of assumptions

So are you, and the odds stack up high against them.

> Java process startup is now very fast and can be improved further with nailgun (and you don't even need to know about how that works)

Sure I do. That thing might work for most users out of the box, but among the users who cannot and/or don't want to figure it out on their own, there would be some who would expect the Magit maintainers to handhold them through the process.

The same has happened with `Emacs.app`, Cygwin's insane path handling, not knowing anything about `$PATH`, `load-path`, `ssh-agent`, `git config`, and a variety of other things. To a large extend Magit is only incidental to such issues, i.e. we rely on the system being configured correctly, but doing that should fall into the responsibly of the user.

Never-the-less we maintainers have invested huge amounts of time helping these users anyway. We do care for our users and do realize that while such issues might not be our fault but for some users happen to only be relevant in combination with Magit. (We even have *written packages* (`ssh-agency`, `with-editor`) whose main purposes are to allow users to forgo configuring their system.) But that's not exactly fun and I don't want to open Pandora's box (e.g. I don't want to fix user's `$CLASS_PATH`).

**Comment by tarsius** [comment]
In summary, even if what you are proposing were possible - which I strongly doubt - I would not want to do it because the implementation cost and the potential for breakage and increased support requirements are *huge*.

**Comment by fommil** [comment]
This is how startup time is optimised http://www.martiansoftware.com/nailgun/ but I don't care about invocation times until I can get feature parity for the bits that magit needs.

It would be good if you had an explicit list of the commands that magit requires, as I'd be prepared to implement them in jGit if there is any chance of this working. Alternatively, if I could log a typical session, I could reverse engineer the approach.

I believe jGit does pretty much everything that git does (including rebasing) but the command line interface is not actively used, so is lacking in many parts. jGit is used by Eclipse, so anything users want to do in a GUI is supported.

I don't really care about super-optimised performance hacks that are possible in C on Linux. If you used git to do a rebase on a large project on Windows, you'd see why an alternative is required. It's typically 30 seconds to a minute to do operations that are instant on Linux (and I mean git, not magit).

**Comment by fommil** [comment]
ok, so you're basically saying that you're not going to do anything inside magit and it's the responsibility of jgit to be fully compatible. That's probably a noble goal for them anyway, but it would be useful to have an explicit list of the flags that are required and output formatting should also be 100% compatible.

**Comment by tarsius** [comment]
> It's typically 30 seconds to a minute to do operations that are instant on Linux (and I mean git, not magit).

That's ... really?!

> It would be good if you had an explicit list of the commands that magit requires, as I'd be prepared to implement them in jGit if there is any chance of this working.

That would be a lot of work to create and be out of date quickly. But why not just start with rebase and then other subcommands that are implemented as scripts.

For rebase the list is: --keep-empty --preserve-merges --committer-date-is-author-date --autosquash --autostash --interactive --onto --root --continue --skip --edit-todo --abort.

**Comment by fommil** [comment]
@tarsius yes, **really**! Why do you think I'm so desperate? :smile:

**Comment by tarsius** [comment]
Regarding output: Stdout is irrelevant but the correct control files have to be created inside `.git`.

**Comment by fommil** [comment]
ok, that's incredibly useful to know. I wasn't aware of that.

**Comment by tarsius** [comment]
What git version are you using?

Also make sure you don't use `git.cmd`. As far as I know that is a wrapper whose main purpose is to make everything much slower. Try `git shell` and run `rebase` in that - is that just as slow?

**Comment by fommil** [comment]
that's just as slow, the biggest problem is the internal forking on rebase operations and I don't think it addresses that.

**Comment by tarsius** [comment]
Yes, I realize that. I was just hoping that the issue is limited to the `git.cmd` wrapper and that using bash by means of `git shell` (which I assume prevents `git.cmd` from being) used, would serve as a quick way to demonstrate that. Apparently not.

**Comment by phil-s** [comment]
fommil: I don't know whether you getting this approved at work would be a pipedream, but when I had a Windows workstation at an old job, I hosted a Linux VM on it, and worked inside that. You can run a local X display (Cygwin provides one), and install the likes of the Ubuntu Server on the VM (i.e. something with no desktop environment), and get all the many benefits with very few downsides.

I would also hazard a guess that perhaps you have some kind of anti-malware app clawing through every file operation, to be suffering from performance that poor?! (I've seen that sort of thing being the cause of horrific filesystem performance in the past.)

**Comment by fommil** [comment]
That would definitely be a pipe dream. There have even been dreams of ram disks.

**Comment by Silex** [comment]
> It's typically 30 seconds to a minute to do operations that are instant on Linux (and I mean git, not magit).

Back when I was on windows git was never *that* slow... I suspect your git installation is somewhat weird or something like http://stackoverflow.com/questions/4485059/git-bash-is-extremely-slow-in-windows-7-x64 or https://github.com/git-for-windows/git/issues/193 is going on.

**Comment by fommil** [comment]
Its an extremely large repository. Is not a weird setup, git is just fundamentally non-scalable on Windows. I have colleagues working on equivalent sized projects in other organisations and they experience the same.

**Comment by Silex** [comment]
Oh, large projects... the kind where you put-all-projects-in-the-same-directory?

**Comment by fommil** [comment]
No, the kind where 500+ developers have been contributing to 5+ year mono repository projects.

**Comment by Silex** [comment]
Nice numbers. I wonder if we could maybe use the linux kernel as an example repo for performance testing, something we could automate with vagrant or docker.

**Comment by tarsius** [comment]
@fommil Can I close this? (But even if I do, please use this to inform about progress.)

**Comment by fommil** [comment]
Sure. But I'll open a fresh one if I need you to do anything.
