### ISSUE TITLE
Committing a subset of staged files instead of the entire index

### ISSUE THREAD

**Issue by zmwangx** [magit/magit#2459]
It has happened to us all: staged too much and need to split into multiple commits, or a related problem surfaces that calls for a quick fix and commit, separate from the work in progress that is already staged.

Am I right in stating that currently there's no way to commit a proper subset of staged files within magit, short of possibly setting `magit-commit-arguments`? If so, please consider this a feature suggestion.

**Comment by kyleam** [comment]
So the idea is to add functionality similar to the patch flag of git
commit?

This would avoid having to unstage the changes you don't want for the
current commit and then re-stage the changes for the later commit(s),
but I think, in order to do so, it would introduce a good amount of
complexity in terms of the code and user interface.  At least at first
glance, it doesn't seem worth it to me.

**Comment by zmwangx** [comment]
Not necessarily the patch flag, that would be very complex. Granularity on the per-file basis is enough, which would be equivalent to `git commit file1 file2 ...` on the command line. Please ignore it if you think that's still too complex.

**Comment by npostavs** [comment]
You can unstage some subsets of files, by marking them using the region. This only works for consecutive files though, see also #2384.

**Comment by kyleam** [comment]
For the frequency that I would use it, I'm still not sure if it's
worth adding per-file action to the commit popup.  What do others
think?

However, even if we don't add anything for this, it should be
straightforward to add a small command to your configuration that
works outside of the commit popup and runs 
`(magit-run-git-with-editor "commit" file0 file1 ...)`.

**Comment by kyleam** [comment]
> You can unstage some subsets of files, by marking them using the region. 

I think the request is to be able to avoid this unstaging.

**Comment by npostavs** [comment]
> I think the request is to be able to avoid this unstaging.

Oh right, missed that.

> I'm still not sure if it's
> worth adding per-file action to the commit popup.

Yeah, I don't think it's useful enough to give it a separate action. Mabye we could add region support to existing commit actions?

> add a small command to your configuration that
> works outside of the commit popup and runs
> (magit-run-git-with-editor "commit" file0 file1 ...).

Should be just `(magit-commit file0 file1 ...)`, no?

**Comment by kyleam** [comment]
>> I'm still not sure if it's
>> worth adding per-file action to the commit popup.

> Yeah, I don't think it's useful enough to give it a separate action.

Sorry, I was sloppy with my wording here.  I was actually thinking of a file option rather than a separate action, but, at any rate, I agree.

> Mabye we could add region support to existing commit actions?

Yeah, but then we're complicating commit actions to add limited support for a functionality that, even if fully supported, wouldn't be used very often.

> Should be just (magit-commit file0 file1 ...), no?

Right, that's better.

**Comment by zmwangx** [comment]
I agree that this isn't used often enough to warrant anything new, and even without a wrapper I can shell out anyway. Thanks for the discussion.
