### ISSUE TITLE
No --set-upstream option in magit-push-popup

### ISSUE THREAD

**Issue by ptrv** [magit/magit#2468]
There is no `--set-upstream` and `--unset-upstream` option anymore in magit-push-popup. probably since commit b2ef8f1935f311df45991b7b69f754ed94d71742.

I have set `magit-push-current-set-remote-if-missing` to `nil` in order to have these options, as suggested by the doc.

How can I set my upstream in push popup?

**Comment by tarsius** [comment]
> How can I set my upstream?

Restart Emacs. Only after you have done that `--set-upstream` argument appears again in the push popup. (As mentioned in `magit-push-current-set-remote-if-missing`s doc-string.) The push popup never featured an `--unset-upstream` argument because `git push` does not actually supports such an argument (and rightfully so, that wouldn't make any sense).

You can also set the upstream from the branch popup. Press <kbd>b</kbd> to bring up the popup, and then <kbd>? u</kbd> to read the documentation on how that is done.

----

Please also note that the README.md file begins with this very noticeable request:

> When something doesn't work as expected, then please first consult the FAQ and ask a search engine. If that doesn't solve your problem, then please ask for help on Emacs.Stackexchange.

If you had done that, then you might have come across several pages on the Emacs Stackexchange site where I am answering similar questions in more depth. E.g. http://emacs.stackexchange.com/a/6023/306.

**Comment by ptrv** [comment]
No `--set-upstream` option after restart.

I did restart Emacs before I reported the issue.

**Comment by tarsius** [comment]
I cannot reproduce this - try updating Magit to the latest Melpa snapshot.

I just tried myself and setting the variable worked as expected for me:
```
Switches
 -f Force (--force-with-lease)
 -h Disable hooks (--no-verify)
 -d Dry run (--dry-run)
 -u Set upstream (--set-upstream)

Push feature to
 e elsewhere

...
```

**Comment by ptrv** [comment]
I am on latest melpa. This is really strange. For some reason  the option does not show up. Need to investigate.

I know it should work as you described. It was working on my home computer. But for some reason on my machine at work the option does not show up.

**Comment by ptrv** [comment]
Found the problem:

I was setting `magit-push-current-set-remote-if-missing` in my init file (with lazy loading `eval-after-load`). Setting it via customize interface made the option appear again.

Now it makes sense why it was not working.

I would say this is 50% user error and 50% not clearly documented.

Sorry for the noise and thanks for you help.

**Comment by npostavs** [comment]
> I was setting `magit-push-current-set-remote-if-missing` in my init file (with lazy loading `eval-after-load`). Setting it via customize interface made the option appear again.

If you `setq` it eagerly *before* loading magit it should also work.

**Comment by ptrv** [comment]
@npostavs True. Key point here is setting the variable before magit gets loaded.

**Comment by tarsius** [comment]
> I would say this is 50% user error and 50% not clearly documented.

I'll look into either making this clearer or adding some ugly kludge to make this unnecessary.

**Comment by ptrv** [comment]
@tarsius Thank you!
