### ISSUE TITLE
Make `f` and `F` consistent with `p` regarding remote and upstream

### ISSUE THREAD

**Issue by syl20bnr** [magit/magit#2469]
I love the new UX under `p` to be able to push to remote under `p p` and upstream under `p u`.
We should have the same UX under `f` and `F` with `f f`, `f u`, and `F f` (`F F` ?), `F u`.

**Comment by tarsius** [comment]
To me that sounds like you want to go back to the *old* consistency at the cost of the new consistency. I assume you see that differently because Evil changes the picture. I was planning to suggest making some changes to the Evil bindings. So lets get started with that. /cc @justbur

The old consistency was "pressing the same key twice invokes the most useful variant in a popup". (Which at the time was to push to <kbd>P P</kbd> / fetch from <kbd>f f</kbd> / pull  from <kbd>F F</kbd> the upstream. But now that there is support for the push-remote in addition to the upstream, the most useful action is to act on the push-remote, in those cases. But not in all cases, so I don't think <kbd>* p</kbd> should not be made more convenient than <kbd>* u</kbd> by replacing `p` with whatever `*` stands for for a particular popup.

The new consistency is "<kbd>p</kbd> always acts on the **p**ush-remote, <kbd>u</kbd> always acts on the **u**pstream, and <kbd>e</kbd> acts on some other branch/remote". I am currently working on a blog post which explains this in more detail and also contains instructions on how users who don't agree with this approach can customize the bindings to their liking. I have rehashed this over and over again over the last few weeks and hope to put out an explanation which can put an end to that. So I'll not dive into this any further at this point.

I am pleasantly surprised to see you talk about <kbd>p p</kbd> as opposed to <kbd>P p</kbd>, which would be the binding when not using Evil/Spacemacs. The biggest complain from users of regular Emacs bindings was that they could no longer press <kbd>P P</kbd> to push to "the obvious place". Because I want to maintain the "new consistency" described above I cannot bring that back, at least not as the default. But for me this actually wasn't much of a change, I always used <kbd>p p</kbd> to push to the most obvious place. I was able to do that because I use <kbd>[modifier-]{jikl}</kbd> for basic navigation, which is similar to Vi's <kbd>hjkl</kbd>, so I was free to use <kbd>p</kbd> for something else.

So I was going to suggest that <kbd>p</kbd> should be bound to `magit-push-popup`. What you said above implies that you already do that, but I had a look at `evil-magit` (which I believe Spacemacs uses now) and according to its documentation <kbd>p</kbd> and <kbd>n</kbd> are used for section navigation. If you found some more vi-ish bindings for that and thus freed <kbd>p</kbd> for use for the push popup, that would be great.

**Comment by justbur** [comment]
@tarsius I'd just like to mention that I'm quite happy with the new approach since it follows nicely from how you'd describe the action, so I have no trouble remembering it. 

<kbd>p</kbd> is available for push in evil-magit. The only place I've changed the behavior of <kbd>p</kbd> is in the rebase buffer, where it's pick (as you suggested I think). <kbd>n</kbd> is repurposed for cycling through search matches as in vim, but <kbd>p</kbd> is mostly unused. 

I think I'll just put push on <kbd>p</kbd> and <kbd>P</kbd> for the moment, and then possibly do something different on the latter in the future. I don't want people to be too surprised coming from the default magit bindings to evil-magit.

**Comment by syl20bnr** [comment]
> The new consistency is "p always acts on the push-remote, u always acts on the upstream, and e acts on some other branch/remote".

I'm fine with this, so maybe I will say a dumb thing now but let's go:
Can we get `f p`, `f u` and `F p`, `F u` like for `p` ? I only see `f u` and `F u` available.

**Comment by justbur** [comment]
@syl20bnr I think you need to set the push remote for your repo. I have `f p` and `F p`

**Comment by syl20bnr** [comment]
Ok ok !! My bad :-(
Thank you @justbur 

I guess my request reduces to that `f p` pushRemove, after setting that is not displayed in both `f` and `F` popups.

**Comment by tarsius** [comment]
When the upstream and the push-remote are both unset, then the push popup would show this:

```
Push master to
 p pushRemote, after setting that
 u @{upstream}, after setting that
 e elsewhere
```

This is not done for the fetch and pull popups where you would see

```
Fetch from
 e elsewhere
 a all remotes
```

```
Pull into master from
 e elsewhere
```

That's because the commands which `p` and `u` are bound to in these popups are not capable of setting the upstream/push-remote. The respective git commands also cannot do that, and at least for `git fetch` that wouldn't even be possible.

I think that is reasonable, but more about that in the blob post.

**Comment by tarsius** [comment]
But when the upstream and push-remote are set, then you should see something like:

```
Fetch from
 p tarsius
 u origin
 e elsewhere
 a all remotes
```

```
Pull into master from
 p tarsius/master
 u origin/master
 e elsewhere
```

If that's not the case then please update Magit and try again.

**Comment by syl20bnr** [comment]
I found it suprising and inconsistent, I want to map my push and upstream globally and use them wherever I need to interact with remotes.
I understand that fetch command does not provide the switches to do it atomically, is there any other command to be able to set the push and upstream ?

**Comment by tarsius** [comment]
Not in the fetch and pull popups, but in the branch popup (<kbd>b</kbd>). That's the preferred method actually.

**Comment by syl20bnr** [comment]
Ok I see, I'm OK with this solution but you have still the inconsistency to offer to user an `after setting that` in only push popup. Actually git itself is inconsistent in this regard, but at the Magit level you have the possibility to fix this.

**Comment by syl20bnr** [comment]
But overall I really like the new UX :+1:

**Comment by tarsius** [comment]
The reason that the fetch and pull popups do not provide means to set the remotes is simple. After a transitional period it won't be necessary anymore. Magit should be configured to automatically configure the remotes when a new branch is created (the blog post will explain how to do that), so there seldom will be a need to explicitly configure the remotes.

But since these settings aren't in effect yet, there currently exist branches which are not fully configured yet.

I have decided to allow setting the remotes to be consistent with Git (which allows this here at least for the upstream) and because users are used to this being possible.

**Comment by tarsius** [comment]
> But overall I really like the new UX

Thanks. It is impossible to make everyone 100% happy. For example if I made it possible to set the remotes wherever one could argue that doing so might make sense, then that would not satisfy those users who feel there should only be one way of doing it. So I provide two ways of doing it as a compromise :-)

**Comment by syl20bnr** [comment]
I see, thank you for the explanation!
