### ISSUE TITLE
magit-not-reverted-hook gone?

### ISSUE THREAD

**Issue by dgutov** [magit/magit#2491]
This [breaks integration with diff-hl](https://github.com/dgutov/diff-hl/issues/60#issuecomment-171936084), again.

**Comment by tarsius** [comment]
Magit's auto-revert feature is once more implemented on top of the generic implementation in Emacs' `autorevert` library. Doing that was necessary because the independent, magit-specific implementation that I added in v2.1 was too inefficient when there are many open buffers and/or tracked files.

As you can see [here](https://github.com/magit/magit/blob/master/lisp/magit-autorevert.el) the new implementation is quite trivial, at least on the Magit side. Whether a file is being tracked is "cached" by turning on the local `auto-revert-mode` using `magit-turn-on-auto-revert-mode-if-desired`. That function is called by `magit-auto-revert-mode` and some staging commands. The reverts are triggered explicitly by calling `magit-auto-revert-buffers` in `magit-refresh` (which in turn is called when git was run for side-effects).

Magit turns on `auto-revert-mode` in some buffers and it kicks of reverts by calling `auto-revert-buffers`. Everything else is beyond Magit's control.

Since you already add something to `after-revert-hook`, buffers that are actually being reverted are already being taken care of. But unfortunately I don't see anything in `autorevert` that could be used as a replacement for `magit-not-reverted-hook`. The problem isn't just that it doesn't implement such a hook, there simply isn't a place where such a hook could be called.

Instead you could use `magit-pre-refresh-hook` to call a function which compiles a list of all buffers in the repository which do *not* have to be reverted and then update the `diff-hl` information in each of these buffers. But if you do that, then you would effectively reinstate one of the bottlenecks which I have just removed from Magit.

Unfortunately many users would blame that on Magit and not `diff-hl`, so I would like to ask you to make that feature opt-in and to warn users that it might impact performance. In small repositories or when there exist only few file-visiting buffers, then the impact would be minimal, but under certain conditions the impact is very noticeable.

**Comment by tarsius** [comment]
@syohex, @nonsequitur This might affect your `git-gutter` implementations too. (Off topic: I am still hoping that you will one day merge your implementations.)

**Comment by dgutov** [comment]
> But unfortunately I don't see anything in autorevert that could be used as a replacement for magit-not-reverted-hook.

That's why VC defines `vc-checkin-hook`, and calls it independent of whether `auto-revert-mode` is being used. If Magit wants to be a comparable piece of infrastructure, I think it should have something analogous as well.

> Unfortunately many users would blame that on Magit and not diff-hl, so I would like to ask you to make that feature opt-in and to warn users that it might impact performance.

Of course, I'm not going to do that. The whole point of using such hooks is to make `diff-hl` performance-efficient. Otherwise, I could just as well add a timer that would refresh the status of each visible buffer over a small interval.

**Comment by tarsius** [comment]
> That's why VC defines `vc-checkin-hook`

But that only covers one out of many situation in which `diff-hl` should update its overlays right? I guess I could add a comparable hook so that Magit doesn't lag behind VC in this area, but that won't help with any of the other situations.

**Comment by tarsius** [comment]
> Otherwise, I could just as well add a timer that would refresh the status of each visible buffer over a small interval.

Maybe `vc-refresh-state` could be made more efficient and be called "more often" (possibly using a timer). Then `vc-mode-line-hook` could be  used for this purpose I believe.

**Comment by dgutov** [comment]
> But that only covers one out of many situation in which diff-hl should update its overlays right?

Indeed, but it's the main, frequent case where the user expects to see the changed reflected.

> but that won't help with any of the other situations.

Yes, it won't help after e.g. non-hard `git reset`. I haven't received any complaints about that behavior yet, though.

**Comment by dgutov** [comment]
> Maybe vc-refresh-state could be made more efficient and be called "more often" (possibly using a timer).

I suppose it could be, but that's up to VC, not `diff-hl`. Using `vc-mode-line-hook` in that case is an interesting proposition, but not if it'll just come down to calling `diff-hl-update` every time the timer fires.

**Comment by tarsius** [comment]
> Indeed, but it's the main, frequent case where the user expects to see the changed reflected.

That should do the trick then:

```diff
diff --git a/lisp/magit-apply.el b/lisp/magit-apply.el
index 554a195..2746510 100644
--- a/lisp/magit-apply.el
+++ b/lisp/magit-apply.el
@@ -213,6 +213,7 @@ (defun magit-stage-modified (&optional all)
 (defun magit-stage-1 (arg &optional files)
   (magit-wip-commit-before-change files " before stage")
   (magit-run-git "add" arg (if files (cons "--" files) "."))
+  (run-hook 'magit-post-stage-hook)
   (when magit-auto-revert-mode
     (mapc #'magit-turn-on-auto-revert-mode-if-desired files))
   (magit-wip-commit-after-apply files " after stage"))
@@ -231,6 +232,7 @@ (defun magit-stage-untracked ()
     (magit-wip-commit-before-change files " before stage")
     (when plain
       (magit-run-git "add" "--" plain)
+      (run-hook 'magit-post-stage-hook)
       (when magit-auto-revert-mode
         (mapc #'magit-turn-on-auto-revert-mode-if-desired plain)))
     (dolist (repo repos)
```

**Comment by dgutov** [comment]
It should be after the commit is made, not just after the file is staged.

**Comment by tarsius** [comment]
Instead or also?

**Comment by dgutov** [comment]
Instead. Although I don't know if `magit-post-stage-hook` could turn out to be useful as well later.

**Comment by tarsius** [comment]
> Although I don't know if `magit-post-stage-hook` could turn out to be useful as well later.

> Instead. Although I don't know if `magit-post-stage-hook` could turn out to be useful as well later.

In that case I won't add `magit-post-stage-hook` until it is actually needed. As you know the removal of a hook usually isn't appreciated, and I want to reduce the risk of that happening :-)

> It should be after the commit is made,

That's a bit more complicated because the hook cannot be called instantly after the user pressed `C-c C-c`. We have to give Git some time to actually create the commit. Maybe a constant delay using a timer could work. Or the pre-commit HEAD hash could be safed and the timer could wait until HEAD's hash has changed.

**Comment by tarsius** [comment]
Err... actually using the process sentinel would make more sense.

**Comment by dgutov** [comment]
> In that case I won't add magit-post-stage-hook until it is actually needed. As you know the removal of a hook usually isn't appreciated, and I want to reduce the risk of that happening :-)

Sure. And I'm well familiar. :)

> actually using the process sentinel would make more sense.

Yup! If you're doing commits asynchronously, of course.

**Comment by tarsius** [comment]
Actually there already exists a hook, `with-editor-post-finish-hook` which I could used for this purpose. Currently it is run 0.1 seconds after instructing the editor process to finish. I'll just use that for now, but this doesn't appear very safe. Please let me know if you experience any problems because of this.

Using that hook is a bit odd, because you have to use another hook to add a function to that hook:

```lisp
(add-hook 'git-commit-setup-hook
          (lambda ()
            (add-hook 'with-editor-post-finish-hook 'diff-hl-update t)))
```

I'll have to think about this some more and then probably make this safer and more convenient. That might take a while though, so I recommend you use the above snippet for the time being.

**Comment by dgutov** [comment]
Doesn't `git-commit-setup-hook` run in the message editing buffer? `with-editor-post-finish-hook`, apparently, too. I need a hook that runs in each committed file's buffer.

Or, failing that, a way to get the list of committed files from `with-editor-post-finish-hook`.

**Comment by tarsius** [comment]
You can get a list of changed files using `(magit-changed-files "HEAD")` and the get the buffers using `find-buffer-visiting`. But note that listing files is extremely slow over Tramp when there are thousands of files because the file names are separated using \0 and Tramp ends up using `looking-back` on a very long line.

**Comment by dgutov** [comment]
When you're committing a file, either Magit or git-commit tracks which files you are committing, right? Can I have access to that list?

**Comment by tarsius** [comment]
No, Magit just call `git commit` without any arguments.

**Comment by tarsius** [comment]
The tramp vs. long line issue actually doesn't matter much in this case (unless the commit changes thousands of files).

**Comment by dgutov** [comment]
All right. Can I rely on `magit-changed-files` not to go away?

**Comment by tarsius** [comment]
Not 100%, at some point (likely in v3.1) I want to name low-level functions more consistently. But that will be a big, announced change.

**Comment by nonsequitur** [comment]
@tarsius Luckily, we're not affected. `git-gutter` has no Magit dependencies, `git-gutter+` just uses `magit-status-refresh-hook`.

**Comment by dgutov** [comment]
@tarsius 

> magit-status-refresh-hook

Hmm, should I use it as well? As long as I'm going to have to call `magit-changed-files` anyway.

> At some point (likely in v3.1)... But that will be a big, announced change.

You might want to put it through a period of obsoletion first, like customary in Emacs.

**Comment by tarsius** [comment]
>  `git-gutter+` just uses `magit-status-refresh-hook`.

You should use `magit-pre-refresh-hook` instead, unless you really want to tie the outcome to the existence of the status buffer.

> Hmm, should I use it as well?

See the last two paragraphs of my initial response.

**Comment by dgutov** [comment]
> See the last two paragraphs of my initial response.

Are you saying that just calling `magit-changed-files` will not work?

**Comment by tarsius** [comment]
That returns files but you want buffers. It probably isn't that costly to map files to buffers but still, this is something to keep in mind.

However actually "re-diffing" the buffers is costly and it might be a good idea to suspend doing so when user input arrives and to later resume using a timer, similar to how `auto-revert-buffers` avoids blocking Emacs.

**Comment by dgutov** [comment]
I was mostly asking whether to use `magit-status-refresh-hook` or `with-editor-post-finish-hook`.

> It probably isn't that costly to map files to buffers but still, this is something to keep in mind.

It's basically O(M*N) complexity, but I don't this Emacs offers any alternative, so far. It could make `find-buffer-visiting` or `get-find-buffer` backed by a hashtable in the future, however.

> However actually "re-diffing" the buffers is costly and it might be a good idea to suspend doing so when user input arrives and to later resume using a timer

That could be a good idea for later, but I think it's okay to do synchronously anyway if we're sure that the user isn't actually typing right now, and could imagine why Emacs is being slow. "Right after commit", or revert, or reset, should satisfy this condition.

**Comment by tarsius** [comment]
> I was mostly asking whether to use `magit-status-refresh-hook` or `with-editor-post-finish-hook`.

If you only want to emulate `vc-checkin-hook`, then use `with-editor-post-finish-hook`. If you want to re-diff whenever that might be necessary because Magit did run Git for side-effects, then use **`magit-pre-refresh-hook`**. (Not `magit-status-refresh-hook`, because that hook is only run when there actually exists a status buffer which doesn't have to be the case.)

> It's basically O(M*N) complexity,

You would be surprised how big M and N can be for some users (thousands of files, hundreds of buffers).

> That could be a good idea for later, but I think it's okay to do synchronously anyway

I thought so too but due to all the reports about decreased performance in v2.1, I know now that it's not okay for users who regularly have hundreds of buffers open at the same time.

> if we're sure that the user isn't actually typing right now

`magit-pre-refresh-hook` is run every time the user invokes any command which runs Git for side-effects. For example a user might press `s` twice to stage two hunks. There shouldn't be a delay in between.

> [the user] could imagine why Emacs is being slow

Based on past experience s/he would likely assume that it is Magit's fault. So I would appreciate it if you made this either asynchronous or opt-in.

Bad performance is the number one complain about Magit and I am finally ready to tackle this huge issue. But this is a major undertaking and so I am a bit sensitive if these efforts are counteracted by packages which hook into Magit, especially when it is not obvious to users that it is not actually Magit which is responsible for the (additional) slowdown.

**Comment by tarsius** [comment]
Something like this would likely suffice:

```lisp
(defvar diff-hl-backlog nil)
(defvar diff-hl-timer nil)
(defvar diff-hl-interval 5)

(defun diff-hl-reset-timer ()
  (when (timerp diff-hl-timer)
    (cancel-timer diff-hl-timer))
  (setq diff-hl-timer
        (and diff-hl-backlog
             (run-with-timer diff-hl-interval
                             diff-hl-interval
                             'diff-hl-update-buffers))))

(defun diff-hl-update-buffers (&optional buffers)
  (setq buffers (nconc buffers
                       (--filter (not (memq it buffers)) diff-hl-backlog)))
  (while (and buffers (not (input-pending-p)))
    (let ((buf (pop buffers)))
      (when (buffer-live-p buf)
        (with-current-buffer buf
          (diff-hl-update)))))
  (setq diff-hl-buffers-backlog buffers)
  (diff-hl-reset-timer))
```

**Comment by tarsius** [comment]
I have [added `magit-post-refresh-hook`](https://github.com/magit/magit/commit/8352705c0e519fea6ee4c32e9f7bc0da3fc2aaac) and [deprecated the redundant `magit-status-refresh-hook`](https://github.com/magit/magit/commit/7f5177cb72e73041d9fa6981acaaa7c60daa78e7).

**Comment by dgutov** [comment]
> If you only want to emulate vc-checkin-hook, then use with-editor-post-finish-hook.

Thanks, I'll keep this tradeoff in mind.

> You would be surprised how big M and N can be for some users (thousands of files, hundreds of buffers).

That's surprising, yes, but my point was that this is a bad complexity anyway. We'd want O(number of changed files).

> For example a user might press s twice to stage two hunks. There shouldn't be a delay in between.

At some point there, you have to calculate all "changed" files anyway, right? Could you call a hook and pass it that list? That would cut down on that particular call I'd have to make. Alternatively, `magit-changed-files` could cache its return value between invocations.

> So I would appreciate it if you made this either asynchronous or opt-in.

Installing `diff-hl` is opt-in anyway. I haven't received any performance complaints so far, which is surprising, given your experience, because MELPA shows that it's been downloaded 25% as much as Magit has.

If you do receive complaints because of `diff-hl`, please don't hesitate to send them my way (or summon me to the issues).

Doing `diff-hl-update` asynchronously would be fine (if a little more complicated), but I'd rather avoid the manual workload shuffling you've written above, using timers and `input-pending-p`. Using `diff-hl-interval` that's above 50ms would make *my* package look sluggish instead, and I don't want that (and 5 seconds is an eternity).

Further, if there are a zillion open buffers visiting changed files, and we're distribute the workload like that, the actual buffers that are currently displayed might never get around to being highlighted.

I see two alternative strategies for improving performance:

* Debouncing `diff-hl-update` so it can only call `git diff-index` once per user command.
* If the buffer which needs to have its info updated is not visible, I can add the update to `window-configuration-change` hook instead, so it's only performed after the user switches to that buffer. Which means that we only call `git diff-index` for a few files at a time. `magit-changed-files` could still be a bottleneck, though.

And about that. Going by your example, you want me to update *all* buffers managed by Magit, continuously, instead of calling Git for the list of those that have changes and those that don't. That doesn't seem like a very good idea if the user has lots of buffers open.

(I have to go now, will be back tonight.)

**Comment by tarsius** [comment]
> [various ideas on how performance could be improved]

(some of which I have been considering myself)

Since I am now beginning my journey into the land of performance tweaks anyway: sure I will look into the things you are suggesting :-) But since I am trying to get a release out right now (it already looks like I won't be able to pull it off today), I will delay that until after the release.

**Comment by dgutov** [comment]
FWIW, the latter "trick" has been used by js2-mode for some time.

**Comment by tarsius** [comment]
What about this: https://github.com/magit/magit/compare/jb/refresh-files-hook?expand=1

**Comment by tarsius** [comment]
I think #2523 is the best that can be done about this on Magit's side at this point. (It still needs documenting, testing, and probably bugfixing though.)

Like you requested it provides a "list of buffers where you might have to do something" hook. Additionally it tries to limit that list as much as possible according to `diff-hl`s needs (and hopefully that of other packages which would want such a list). It assumes that `revert-buffer-hook` is also used.
