### ISSUE TITLE
shortcut to sync upstream?

### ISSUE THREAD

**Issue by glyph** [magit/magit#2526]
In my git configuration, I have an alias, `down`, which is `merge --ff --ff-only @{upstream}`.  (IMHO this is what most people mean when they type `git pull`).  I'd like something similar to be easily accessible, in the same way that `f u` fetches upstream, perhaps `m u` could merge upstream.

Is there an existing, recommended way to set up a shortcut like this in magit?

**Comment by glyph** [comment]
Right now what I'm doing is:

```elisp
(magit-define-popup-action 'magit-merge-popup ?u
         "Catch Up To Upstream"
         (lambda ()
           (interactive)
           (magit-merge "@{upstream}" `("--ff" "--ff-only"))))
```

**Comment by kyleam** [comment]
Yeah, that's a fine way to add it.  (I think the `--ff` is pointless there though.)  I've had something similar in my config for a long time and have found it useful.

(This seems to be more of a configuration question than a feature request.  Please use stackexchange or the mailing list for these sorts of questions.)

**Comment by tarsius** [comment]
Merging its upstream into the current branch is usually not the right thing to do.

If you get into this situation

```
* [master] new feature
| * [origin/master] fix a bug
|/
* some old stuff
```

You should *not* merge the upstream to get this

```
* [master] Merge remote-tracking branch 'origin/master'
|\
| * [origin/master] fix a bug
* | new feature
|/
* some old stuff
```

because you should not merge the mainline into something else. You should do it the other way around by merging new features into the mainline. That's why there is no "merge the upstream" command - it's almost never the right thing to do.

There is a "pull its upstream into the current branch" command because that is a reasonable thing to do, provided `branch.<name>.rebase` is `true`. Given the original situation that would give you:

```
* [master] new feature
* [origin/master] fix a bug
* some old stuff
```

Alternatively, if you think history rewriting is evil then you could instead spin off a feature branch using `b s`, checkout `master` again, and finally merge the newly created feature branch:

```
* [master] Merge branch 'feature'
|\
| * [feature] new feature
* | [origin/master] fix a bug
|/
* some old stuff
```

**Comment by glyph** [comment]
I think rewriting history is definitely evil and your advice here about what is "the right thing to do" is exactly backwards from my perspective :). The whole reason DVCSes have a graph and parent history is to enable merging mainline back into your branch if that's the workflow you're following.

Nevertheless, what I'm talking about *here* is just updating a local branch which has not diverged from upstream, but is just out of date.  Hence the `--ff --ff-only` options. I do agree that the fact that github calls both operations "merging" is bizarre; "update from upstream" and "merge in master" are two radically different kinds of operations and I try to keep them separate; this is why I have aliases on the command line, I never want to type 'merge'.

**Comment by kyleam** [comment]
> what I'm talking about here is just updating a local branch which has not diverged from upstream, but is just out of date.

Right, I also commonly do fast-forward merges of the upstream
(https://github.com/magit/magit/pull/2414#issuecomment-162332405) and don't think this can be considered wrong in any workflow.

**Comment by mohkale** [comment]
Was re-reviewing this today. While I agree with Tarsius's recommendation about not merging from remotes and instead rebasing to keep the commit graph clean, depending on the projects you work on this might not always be the best course. For example if you're reviewing code on Github instead of through mailing lists rebasing and force push would basically reset all the open conversions on a GitHub PR and make it harder to distinguish changes across reviews. In mailing list workflows my experience is people generally review from scratch on each iteration. On Github people generally review increments or diffs between increments which becomes a lot harder with the rebase workflow because potentially everything is reset everytime you rebase. I'd suggest rebasing when initially opening a PR as draft but once you get past the first review you should prefer merging to avoid extra work on the reviewers part.

Anyway, Kyleams comment from above is no longer applicable to modern magit which uses transient instead of magit-popup. I did some adjustments of magit-rebase-* to create equivalent helpers for magit-merge. This may be useful to others who also stumble on this issue.

```elisp
(transient-define-suffix magit-merge-from-pushremote+ (args nocommit)
  "Merge into the current branch from its push-remote branch.

When the push-remote is either not configured or unusable, then let
the user first configure the push-remote. With a prefix argument
skip generating a merge commit."
  :if #'magit-get-current-branch
  :description #'magit-pull--pushbranch-description
  (interactive (list (magit-merge-arguments) current-prefix-arg))

  (pcase-let ((`(,branch ,remote)
               (magit--select-push-remote "merge from this")))
    (magit-merge-assert)
    (magit-run-git-async "merge" (if nocommit "--no-commit" "--no-edit")
                         args (concat remote "/" branch))))

(transient-define-suffix magit-merge-from-upstream+ (args nocommit)
  "Merge the current branch from its upstream branch.

When the upstream is either not configured or unusable, then let
the user first configure the upstream. With a prefix argument
skip generating a merge commit."
  :if #'magit-get-current-branch
  :description #'magit-pull--upstream-description
  (interactive (list (magit-merge-arguments) current-prefix-arg))

  (let* ((branch (or (magit-get-current-branch)
                     (user-error "No branch is checked out")))
         (upstream (magit-get-upstream-branch branch)))
    (unless upstream
      (setq upstream
            (magit-read-upstream-branch
             branch (format "Set upstream of %s and rebase onto that" branch)))
      (magit-set-upstream-branch branch upstream))
    (magit-merge-assert)
    (magit-run-git-async "merge" (if nocommit "--no-commit" "--no-edit")
                         args upstream)))

(transient-suffix-put 'magit-merge '(1 1 "p") :key "v")

(transient-insert-suffix 'magit-merge '(1 0 0) '("p" magit-merge-from-pushremote+))
(transient-append-suffix 'magit-merge '(1 0 0) '("u" magit-merge-from-upstream+))
(transient-remove-suffix 'magit-merge '(1 1 1)) ; Remove blank separator

;; Move the absorb suffix to the next column
(transient-remove-suffix 'magit-merge '(1 0 "a"))
(transient-append-suffix 'magit-merge '(1 1 0) '("a" "Absorb" magit-merge-absorb))

;; Add a configure setting like `magit-push'.
(transient-append-suffix 'magit-merge '(-1)
  ["Configure" ("C" "Set variables..."  magit-branch-configure)])
```

This should turn the merge popup into something like this:

![Screenshot_20240905_235333](https://github.com/user-attachments/assets/94d8b6be-c3aa-4b83-9213-ebc90d8b285f)
