### ISSUE TITLE
`Symbol's function definition is void: magit-invoke-popup-variable` when trying to set remote branch in magit-branch-popup

### ISSUE THREAD

**Issue by Crazy-Owl** [magit/magit#2528]
The title is self-explanatory - when I press `RET` on the line with `branch.mybranch.remote      unset` nothing happens but message: `Symbol's function definition is void: magit-invoke-popup-variable`.

The following magit packages are installed:

```
  magit              20160127.1232
  magit-popup        20160119.1409
```

**Comment by tarsius** [comment]
Please update `magit-popup`. No idea why updating `magit` did not also update `magit-popup`.

**Comment by Crazy-Owl** [comment]
Latest `magit-popup` version for me is `20160119.1409`, I use the following repos:

```
             '("marmalade" . "http://marmalade-repo.org/packages/")
             '("tromey" . "http://tromey.com/elpa/")
             '("melpa" . "http://melpa.milkbox.net/packages/")
```

**Comment by tarsius** [comment]
> Latest `magit-popup` version for me is `20160119.1409`

Indeed. There's something strange. Will investigate.

> I use the following repos

That's probably unrelated to the issue at hand, but you should remove `tromey` and possibly also `marmalade`. The former is definitely obsolete, the latter just very poorly maintained. You might want to use `melpa-stable` instead of these two. Also make sure you add the `gnu` archive back.

**Comment by tarsius** [comment]
> when I press RET on the line

Meanwhile you can just type the key displayed on that line instead.
