### ISSUE TITLE
with-edit.org cannot be found with the link in the project homepage

### ISSUE THREAD

**Issue by saccohuo** [magit/magit#2560]
<https://raw.githubusercontent.com/magit/magit/master/Documentation/with-editor.org>
This link at <http://magit.vc/> is void.
Please repair it.

**Comment by tarsius** [comment]
Thanks for pointing this out.

I have removed the links to Org files from the "Current release" section, because these links did not actually point to the versions of these files for the current release, they pointed to the versions for the development version.

Also I have updated the `with-editor` link in "Recent development snapshots".
