### ISSUE TITLE
Is it ok that magit shows "GitError!" when a commiting is canceled?

### ISSUE THREAD

**Issue by debug-ito** [magit/magit#2586]
I'm used to magit 1.2.0, and recently start trying magit 2.5.0.

Steps to reproduce:

- Open `magit-status`
- Stage some changes.
- Hit `c c` to open the commit log editor.
- Hit `C-c C-k` to close the editor.
- Then you'll see an alarming message of `GitError! There was a problem with the editor '/usr/bin/emacsclient.emacs24 --socket-name=/tmp/emacs1000/server'.` at the top of `magit-status` buffer.

I wonder if this is the expected behavior. I think it is not an error to abort `git commit` by the user's explicit cancallation.

My environment:

- Xubuntu Linux 16.04 (X Window mode)
- emacs: installed from Ubuntu repository, version 24.5+1-1ubuntu7
- magit: installed from Git repository, version "2.5.0-54-gaa2f4f1"
- dash: installed from Ubuntu repository, version 2.12.1-1
- with-editor: installed from Ubuntu repository, version 2.5.0-1

**Comment by kyleam** [comment]
It's the expected behavior.  An error is shown when the exit code
isn't zero, and git commit has a nonzero exit when a message is
aborted.  If you hit `$` to see the process buffer, it should tell you
something like

    Waiting for Emacs...
    *ERROR*: Canceled by user
    error: There was a problem with the editor '/usr/bin/emacsclient'.
    Please supply the message using either -m or -F option.

While I agree that it's not helpful in this case to display the
`GitError` banner, I don't think it's worth the effort to handle this
in a special way.  You can safely ignore it, and it will go away the
next time the status buffer refreshes.

**Comment by debug-ito** [comment]
Thanks for your quick reply.

I agree. It's tricky to handle this case properly because cancellation is actually handled by `git` process.
