### ISSUE TITLE
Teach more commands to switch repository when called outside repository

### ISSUE THREAD

**Issue by jojojames** [magit/magit#2590]
Calling magit-log returns -> "magit-log-read-revs: Wrong type argument: stringp, nil"

whereas calling magit-status lets the user pick a list of repositories to use magit-status on.

Using magit-20160312.2307.

**Comment by tarsius** [comment]
The status buffer is special in that it can be used as a "project overview" and that most users invoke most commands from their. So it does make a lot of sense to teach it to "switch projects". While I would like to support workflows that are not centered around that buffer better, I don't think teaching every command how to ask the user in which repository it should do its thing is really a good option.

Granted this can lead to strange error messages, as it does in this case, but the alternative of modifying the interactive form of every command to perform this check and if necessary let the user select a repository isn't very appealing. Also if that does happen, then we would be forced to change the repository while still inside the interactive form (so that we could then read the other arguments) but interactive forms should not have any side-effects.

So while I understand the sentiment, I don't think we can easily do anything about this and also that it is not really necessary (just a bit inconvenient and potentially confusing if we don't).

**Comment by jojojames** [comment]
Thanks. Makes sense.
