### ISSUE TITLE
Pulling with rebasing just once

### ISSUE THREAD

**Issue by mbunkus** [magit/magit#2597]
Hey,

as a long time user of magit < 2 I was very used to being able to do the occasional rebasing pull. I usually do not want to rebase when pulling, but sometimes I do. This used to be possible with the `F r` combination in magit < 2 which ran something like `git pull --rebase`.

Now with magit at 20160219.1502 I can still rebase while pulling, but it actually sets a configuration variable instead of adding an argument. The result is that all subsequent pulls will implicitly rebase, too, leading to confusion and unwanted behavior. The old workflow is now significantly harder to achieve: open pull menu, enable rebasing, pull, edit `.git/config`, remove variable manually.

Please add back a way to rebase with only the current pull action. Thanks for considering it.

**Comment by tarsius** [comment]
You can use one of `r p`, `r u`, or `r e`, whatever is appropriate, to do the rebase. Of course you first have to fetch in a separate step, which you might find a bit inconvenient. I decided to remove `--rebase` from the pull popup because having a variable and an argument could be rather confusing.

**Comment by mbunkus** [comment]
Of course there are multiple ways to achieve what I want, but none is as convenient as the workflow offered by earlier versions of magit.

Additionally: to me having a variable in the pull operation instead of a switch was hugely confusing, especially as a long-time user of magit. I just checked the other operations I use regularly (fetching, pushing, merging, rebasing, creating/switching branches, logging, remoting, cherry picking) and none of those operations feature variables – instead all of them still feature switches that only affect the current operation. Pulling is really the odd man out here; without reading the manual about variables you'd never expect such a behavior.

I'd be really happy to have `--rebase` back as a switch. If you consider this too confusing for users then please consider making it configurable at least with it defaulting to off. Thanks.

**Comment by tarsius** [comment]
You can easily add the switch like this:

```lisp
(magit-define-popup-switch 'magit-pull-popup ?r "Rebase" "--rebase")
```

This isn't much more involved than defining a regular key binding, so this already is configurable.

You can also remove the variable if you wish:

```lisp
(magit-remove-popup-key 'magit-pull-popup :variable ?r)
```

(Actually there was a small problem, so you'll have to pull first or wait for Melpa to grab the latest commit.)

For more information see [this](http://magit.vc/manual/magit-popup/Customizing-existing-popups.html).

The reason I have opted to replace the switch with an argument is that, at least in my experience, it is likely that one wants to always rebase or merge. There are exceptions where one usually merged but rebases this one time, but because these are exceptions at least I think of it as "rebase" not "pull using the rebase variant" and so I naturally press <kbd>r ...</kbd>, not <kbd>F ...</kbd>, without thinking about it.

**Comment by mbunkus** [comment]
Thanks for the pointers. Adding options manually is sufficient for me. I wasn't aware the popups can be modified so easily; I'm still rather new to magit v2.
