### ISSUE TITLE
pulling from upstream doesn't pull tags

### ISSUE THREAD

**Issue by mbunkus** [magit/magit#2599]
Magit 20160325.1054, Git 2.7.2, Emacs 24.5.1

Pulling from upstream by hitting `F u` doesn't pull tags from the repository. I have to fetch from upstream with `f u`. magit < 2 used to fetch tags when pulling, too. A simple `git pull` fetches tags, too.

The configuration option `remote.mosu.tagOpt` is not set.

The `*magit-process:…*` buffer contains the following after the two actions:

      0 git … pull mosu master
    From github.com:mbunkus/mkvtoolnix
     * branch            master     -> FETCH_HEAD
    Already up-to-date.

      0 git … fetch mosu
    remote: Counting objects: 1, done.
    Unpacking objects: 100% (1/1), done.
    From github.com:mbunkus/mkvtoolnix
     * [new tag]         release-9.0.0 -> release-9.0.0

**Comment by tarsius** [comment]
The "Pull from {upstream}" command doesn't use `git pull` because while that *usually* pulls from the upstream it actually might not, depending on a good dozen Git variables. So we explicitly use `git pull {upstream-remote} {upstream-branch}` instead, but unfortunately that doesn't pull tags.

We could use `git pull --tags {upstream-remote} {upstream-branch}`, but users who have have `remote.<name>.tagOpt` to `--no-tags` would not like that.

So, because otherwise this would be inconsistent, we would have to add `--tag` *and* `--no-tag` to the popup because there is no support for a single key to toggle between `--SOMETHING` and `--no-SOMETHING`. But what if the user enables both `--tag` *and* `--no-tag`?

So we would have to instead add the *variable* `remote.<name>.tagOpt` to the popup. But you already said that you don't like when such variables are used because you might want to enable/disable an optional feature this once only instead of for all future invocations. In this particular case I too wouldn't want to use the variable.

Furthermore do I think that one should usually avoid pulling anyway. I think it is a good idea to fetch instead, inspect the incoming changes, and then *decide* whether you still want to merge/rebase after seeing what that would bring in. Of course you might not agree with that and that's okay, but given the above problems I don't think there's a good way for Magit to pull a branch and at the same time fetch all tags (as well as other branches which might have changed).

I recommend that you add the `--tag` argument to the popup and configure it to be used by default, which you can do by enabling it and then typing `C-x C-s`.

**Comment by npostavs** [comment]
Might it make sense to add `magit-pull-implicitly`, analogous to `magit-push-implicitly`?

**Comment by tarsius** [comment]
Sure. But like `magit-push-implicitly` it would have to be added explicitly :-)

**Comment by tarsius** [comment]
Actually, I don't think what I and @mbunkus have said is true. I just looked at the documentation and it seems that those tags which are reachable from the fetched branch(es) are also fetched. The documentation doesn't say anything about tags not being fetched when the remote and or refspecs are given explicitly.

```
       remote.<name>.tagOpt
           Setting this value to --no-tags disables automatic tag following
           when fetching from remote <name>. Setting it to --tags will fetch
           every tag from remote <name>, even if they are not reachable from
           remote branch heads. Passing these flags directly to git-fetch(1)
           can override this setting. See options --tags and --no-tags of git-
           fetch(1).
```

So I don't think Magit's behavior actually changed.

**Comment by mbunkus** [comment]
I'm pretty certain magit < 2 did pull tags when issuing the normal pull command `F F`. I've been using that workflow for years. I have programs for which I have multiple repositories on the same machine all working with the same upstream. Why? Because I'm doing cross-platform development. One repo for Linux, one for 32bit Windows (cross compiled), one for 64bit Windows, and one in which I always have a pristine working tree in order to always have binaries around for comparison.

I regularly push from one of those repos to the upstream one and pull (really pull) from the others. I most certainly did not pull tags manually. I'm pretty sure magit used to simply call `git pull` without any refspec or with only a remote's name in version < 2. So yes, this is a change in behavior.

If you want I can dig up my copy of magit from before my update to >= 2 and check whether or not this is the case.

**Comment by tarsius** [comment]
I shouldn't have read the documentation... my memory was right, not the documentation.

```
$ git init remote
Initialized empty Git repository in /tmp/remote/.git/
$ cd remote 
$ git commit --allow-empty -m 1
[master (root-commit) 8e0ffe6] 1

$ cd ..
$ git clone remote local1
Cloning into 'local1'...
done.
$ git clone remote local2
Cloning into 'local2'...
done.
$ git clone remote local3
Cloning into 'local3'...
done.

$ cd remote      
$ git commit --allow-empty -m 2
[master c74dbc9] 2
$ git tag v2

$ cd ../local1
$ git pull
remote: Counting objects: 1, done.
remote: Total 1 (delta 0), reused 0 (delta 0)
Unpacking objects: 100% (1/1), done.
From /tmp/remote
   8e0ffe6..c74dbc9  master     -> origin/master
 * [new tag]         v2         -> v2
Updating 8e0ffe6..c74dbc9
Fast-forward

$ cd ../local2
$ git pull origin
remote: Counting objects: 1, done.
remote: Total 1 (delta 0), reused 0 (delta 0)
Unpacking objects: 100% (1/1), done.
From /tmp/remote
   8e0ffe6..c74dbc9  master     -> origin/master
 * [new tag]         v2         -> v2
Updating 8e0ffe6..c74dbc9
Fast-forward

$ cd ../local3   
$ git pull origin master
remote: Counting objects: 1, done.
remote: Total 1 (delta 0), reused 0 (delta 0)
Unpacking objects: 100% (1/1), done.
From /tmp/remote
 * branch            master     -> FETCH_HEAD
   8e0ffe6..c74dbc9  master     -> origin/master
Updating 8e0ffe6..c74dbc9
Fast-forward
```

**Comment by tarsius** [comment]
I might be able to do something about this but I am currently on a break (which has started to fizzle out to much for my taste over the last week or so) and as a result it might take a while until I get to it.

**Comment by mbunkus** [comment]
I'd appreciate it, thanks. Don't worry about the time frame; it's definitely not urgent.

**Comment by npostavs** [comment]
Ah, looks like this was discussed before in #1995 (I kind of thought it seemed familiar), start from https://github.com/magit/magit/issues/1995#issuecomment-174195805 to see magit v2+ discussion.

**Comment by tarsius** [comment]
I have `magit-pull-from-upstream` to use `git pull REMOTE`. See fd40b3a981d29327fe1ca1c24e65a6049b55997f for why I changed my mind.
