### ISSUE TITLE
Is there a way to export git logs to Org-mode format?

### ISSUE THREAD

**Issue by stardiviner** [magit/magit#2600]
I have a situation need to export git logs to Org-mode file.

- export commit message as org-mode headline.
- export commit code diff as org-mode src code block `#+BEGIN_SRC diff`.

Does magit have relative functions to export this?

**Comment by kyleam** [comment]
You could provide a custom washer function to `magit-git-wash` to get
the output in the form you want, but perhaps something like this is
easier:

```elisp
(defun magit-org-log (range)
  (interactive (list (magit-read-range "Range")))
  (let ((ids (magit-git-lines "rev-list" range)))
    (with-current-buffer (get-buffer (generate-new-buffer "*Magit Org log*"))
      (insert (format "Commits in %s for %s\n\n" (magit-toplevel) range))
      (dolist (id ids)
        (magit-git-insert "show" "-s" "--format=* %h (%s)\n" id)
        (insert "#+BEGIN_SRC diff\n")
        (magit-git-insert "diff" (format "%s^..%s" id id))
        (insert "#+END_SRC\n\n"))
      (goto-char (point-min))
      (org-mode)
      (display-buffer (current-buffer)))))
```

**Comment by stardiviner** [comment]
I tried this function, `[M-x magit-org-log]`. Then input range with `HEAD..HEAD~5`, but it only shows:
```
Commits in /home/stardiviner/.emacs.d/ for HEAD..HEAD~5
```
No other ouput.

And Is there any `magit-git-wash` function example for reference?

And does wash function support for region selected commits export ?

**Comment by kyleam** [comment]
The range `HEAD..HEAD~N` contains zero commits.  Reverse the arguments.

**Comment by kyleam** [comment]
> And Is there any `magit-git-wash` function example for reference?

magit-git-wash is a low-level function for inserting git output and then
transforming that into the output you want.  It's used for generating
parts of several Magit buffers, including diffs and logs.
magit-insert-bisect-log may be the easiest example to look at as a
reference.

> And does wash function support for region selected commits export ?

No, that's outside the scope of magit-git-wash or the supplied washer
function.  If you want to extend the example above to do that, have a
look at magit-format-patch's interactive form.

I'm closing this because I don't think a command that does this belongs
in core Magit.  The example I posted should give you a good start on
writing a command that does what you want.

**Comment by stardiviner** [comment]
@kyleam Thanks, this is great.

Do you know about this two question?

- Is there any magit-git-wash function example for reference?
-  Does wash function support for region selected commits export ?
