### ISSUE TITLE
invalid-read-syntax

### ISSUE THREAD

**Issue by dithomasrc** [magit/magit#2605]
When I try to do a magit status I get this error (I enabled debug-on-error after seeing a similar ticket):

```
Debugger entered--Lisp error: (invalid-read-syntax ") or . in a vector")
  read(get-file-char)
  edebug--read(read get-file-char)
  apply(edebug--read read get-file-char)
  #[128 "\300\301\302#\207" [apply edebug--read read nil] 5 nil](get-file-char)
  require(magit-diff)
  byte-code("\300\301!\210\300\302!\210\300\303!\210\300\304!\210\300\305!\210\300\306!\210\300\307!\210\300\310!\210\300\311!\210\300\312\313\314#\207" [require cl-lib dash with-editor git-commit magit-core magit-diff magit-apply magit-log format-spec package nil t] 4)
  autoload-do-load((autoload "magit" "Show the status of the current Git repository in a buffer.\nWith a prefix argument prompt for a repository to be shown.\nWith two prefix arguments prompt for an arbitrary directory.\nIf that directory isn't the root of an existing repository\nthen offer to initialize it as a new repository.\n\n(fn &optional DIRECTORY)" t nil) magit-status)
  command-execute(magit-status)
```

Any ideas? 

Thanks in advance

Edit: Im using: Spacemacs on windows 
GNU Emacs 25.0.91.1 (i686-pc-mingw32) of 2016-02-29

**Comment by glucas** [comment]
I'm seeing the same error. I'm also on Windows but I'm not using Spacemacs. (GNU Emacs 25.0.92.1), running with emacs -Q and only loading magit and its requirements. 

I get the error evaluating (require 'magit-diff). If I open magit-diff call (eval-buffer), then everything seems to start working.

**Comment by justbur** [comment]
I'm seeing the same issue, also on windows with a recent build from the emacs-25 branch. 

From what I can tell it only happens to me when magit gets updated from melpa. For magit-diff.el if I eval the buffer (like @glucas), delete the .elc file, or recompile the issue seems to go away. Perhaps it's something about the context that the file gets compiled in when updating from melpa?

**Comment by tarsius** [comment]
> Perhaps it's something about the context that the file gets compiled in when updating from melpa?

The `magit` package on Melpa depends on `async` to prevent issues like that. Unless of course you do something to make [this](https://github.com/magit/magit/blob/master/lisp/magit-popup.el#L56) ineffective. I believe Spacemacs does that.

And of course this code has to be run before compiling any library. I suspect that because I have moved `with-editor` (which contains the same code as `magit-popup` above) to a separate repository and because I no longer bumping the dependency on `magit-popup` when creating a new `magit` release, this code is no longer guaranteed to run before compiling any Magit libraries. I think `package.el` compiles in alphabetic order in which case `magit-diff` comes before `magit-popup`.

I have to rethink that hack before the next release, resp. before I make changes to a macro again. This time around it is probably [this commit](https://github.com/magit/magit/commit/71a863ff3068f2ad96dc53a5842aea6961b6fcb7) that causes the issue.

I don't think I can do much about this issue now. But fixing it locally should be easy: uninstall `magit`, restart Emacs, and then reinstall `magit`.

**Comment by justbur** [comment]
@tarsius Thank you. FWIW I am not using spacemacs at the moment. This was occurring for me after updating through `list-packages`.

**Comment by tarsius** [comment]
[This commit](https://github.com/magit/magit/commit/2822d18b7a1c0d86e0ab0c0334b73a618e2cbefd) will hopefully help users who install `magit` from Melpa (non-stable). For Melpa-Stable users I cannot do anything until the next release.

The idea behind this commit is that `git-rebase.el` should be the first library from the `magit` package that is being compiled by `package.el` (since `git-commit.el` is distributed as a separate package). When using `make` then the libraries get compiled in a [carefully determined order](https://github.com/magit/magit/blob/master/lisp/Makefile#L8) but try to tell `package.el` about that. Funny enough in that case `git-rebase.el` gets compiled *last*, but what can you do.

**Comment by dithomasrc** [comment]
Do you know how I can get this change for spacemacs? :)

**Comment by tarsius** [comment]
No. But with Spacemacs too you should be able to uninstall `magit` and then restart. The only difference would be that `magit` would then automatically get reinstalled (I believe).

**Comment by dithomasrc** [comment]
Ok it finally worked:

```
cd ~/.emacs.d/elpa
rm -rf magit*
rm -rf orgit*
rm -rf evil-magit*
restart spacemacs

```
Thanks!

**Comment by justbur** [comment]
@tarsius I'm still reliably getting this error every time magit gets updated through `list-packages`. I can also reliably go to magit-diff.el, recompile, and the error goes away.

**Comment by justbur** [comment]
@tarsius and others on this thread, it appears that my problem was caused by [this memory allocation bug in the windows version of emacs](https://github.com/emacs-mirror/emacs/commit/ab849b7fac5f7a4bb301eb830fa0acc3ad18c18f). Rebuilding emacs seems to have resolved this issue for me.

**Comment by tarsius** [comment]
Thanks for the heads up.
