### ISSUE TITLE
Teach magit-rebase-subset to pick a range to rebase from region

### ISSUE THREAD

**Issue by gleber** [magit/magit#2618]
Currently magit-rebase-subset asks user two questions about where to start the rebased range and where the range should be rebased.

It would be nice to be able to select the range of commits with a region in Emacs in a magit-log buffer.

I am using evil mode, which allows to select line regions with `V`. In my case the workflow would be the following:

1. `SPC g l` - runs `magit-log-all`
2. Move to the cursor to the edge of the range I want to rebase, let's say it's commit `aaaaaa`
3. `V` to start line region selection
4. Move to the cursor to another edge of the range I want to rebase, let's say it's head of branch `feature-x`
5. `r s` - runs `magit-rebase-subset`
6. Magit asks for where to rebase and I type `master`.
7. Magit runs `git rebase --onto master aaaaaa^ feature-x`

Please note that it would add `^` to the executed command, since region selection is visually inclusive, yet the command specified the beginning of the range to be rebased exclusively.

I am not yet sure about how this should work if neither edges of the range point to a branch.

What do you think?

**Comment by npostavs** [comment]
Seems to me this is somewhat abusing region selection, because you're not actually selecting a range of commits, you just happen to want 2 items.

> I am not yet sure about how this should work if neither edges of the range point to a branch.

What if both edges point to a branch?

**Comment by tarsius** [comment]
> Seems to me this is somewhat abusing region selection, because you're not actually selecting a range of commits, you just happen to want 2 items.

That's okay, we do the same to show the diff for a range.

**Comment by tarsius** [comment]
> Move to the cursor to another edge of the range I want to rebase, let's say it's head of branch feature-x

Git always rebases `<some-commit>..HEAD`, you cannot rebase something else. You have to checkout the branch whose commits near the tip you want to rebase. Maybe you want to cherry-pick instead?

You can first move to the the first commit that is to be rebased in a log and only then trigger the rebase. Once in the rebase buffer point is automatically placed on that commit, so you can just press `C-c C-c` (or `.`) here. But the buffer cannot be avoided.

**Comment by phil-s** [comment]
> you're not actually selecting a range of commits, you just happen to want 2 items

Surely the two items are then used by git to identify the exact same sequence of commits which were selected? It seems entirely analogous to me.

**Comment by npostavs** [comment]
> I would think that if the two items are then used by git to identify the exact same sequence of commits which were selected in Emacs

But they're not. The rebasing range is `<edge1>..HEAD`. The second edge is just used as the branch to affect.

**Comment by phil-s** [comment]
Oh, maybe I misunderstood. I had thought the question contained a misapprehension about being able to rebase within any arbitrary range of commits, rather than using one edge to select a branch. I had commented on account of the cherry-picking response from tarsius, as cherry-picking an arbitrary range of commits on top of some other branch is a thing that could be done. Sorry for any added confusion :)

**Comment by gleber** [comment]
@npostavs This is not entirely correct. You can safely do `git rebase --onto master 01234f branch` and it will effectively check out `branch` and do the rebase.

In general there seem to be multiple cases:

1. `<edge1>..HEAD` onto `X`
2. `<edge1>..branch1` onto `X`
3. `<edge1>..<edge2>` onto `X`
4. `branch0..branch1` onto `X`

where `X` can by any commit-ish

These could transform into something like:

1. `git rebase --onto X <edge1>^ HEAD` - i.e. rebase current branch starting from descendant of `<edge1>` onto `X`. This would work out of the box
2. Checkout `<branch`> and rebase it starting from parent of `<edge1>` onto `X`, i.e. `git rebase --onto X <edge1>^ <branch1>`. This would work out of the box with one git command.
3. Cherry pick range (inclusive) `<edge1>..<edge2>` on top of `X`. This can be treated as:

    1. cherry-picking range of commits to X. This can be done as (among few other solutions; ignoring error handling here for brevity):

            TMP=`git rev-parse X`
            git checkout -f X <edge2>
            git rebase --onto $(echo $TMP) <edge1>^ X

    2.  cherry-picking range of commits to a detached head. This can be done as, which would lead to a detached head state:

            git rebase --onto X <edge1>^ <edge2>

    3.  cherry-picking range of commits to a new branch, which we'll have to ask user about. This can be done as, which would lead to a detached head state:

            git checkout new-branch <edge2>
            git rebase --onto X <edge1>^ new-branch

4. Is the same as case 2.

Are there any other cases?

Number 3 is the most interesting part. I prefer solution 3.ii., where this would result into one `git rebase --onto` command and would lead to a detached state, as it seem to be most consistent with `git rebase --onto` behavior.

What do you think?

**Comment by npostavs** [comment]
> This is not entirely correct. You can safely do git rebase --onto master 01234f branch and it will effectively check out branch and do the rebase.

Hmm, I think I may have overlooked the fact that "check out branch" implies `HEAD == branch`. Oops.

**Comment by gleber** [comment]
Ping for the triage. If you, as maintainers, agree with one of the options, I'll give it a try to implement it.

**Comment by tarsius** [comment]
I'm afraid that while I tried understanding this a few times by now, I always zone out rather quickly. It might help if you explain what you want to do. Please draw before and after diagrams like in the `git rebase` man page and explain what is shown in those two diagrams. Also talk about it in term of e.g. "I have a feature branch... and now I want...", i.e. why not what.

You talk about cherry-picking but then use `git rebase` to do it. Are you aware that there is `git cherry-pick`? Also you seem to be found of rebasing onto a detached HEAD. Why is that useful?

**Comment by gleber** [comment]
First to answer your last question. I am using "rebasing" and "cherry-picking of range of commits" interchangeably, since they are equivalent from the point of view of intended results in terms of resulting commit graph.

In short, I want to have a graphical interface for `git rebase --onto`. `git --help rebase` describes all of it. Let me explain how graphical selection would translate into commands.

Let's say we work with the following `magit-log-all` buffer:
```
01ab * [[feature-branch-A]] fixed latent bug
23cd * finalize new feature
45ef * implement proof of concept of the feature
67ba | * [devel] minor-post-release fixes
     |/
89dc * [master] Release v0.1
10ba * final fixes before release
```

Let's consider three cases in three separate posts which will follow.

**Comment by gleber** [comment]
#### Case 1: `<edge1>..HEAD` onto X ####

In this case user would do the mark the following way:
```
01ab * [[feature-branch-A]] fixed latent bug <-- first marked line
23cd * finalize new feature
45ef * implement proof of concept of the feature <-- last marked line
67ba | * [devel] minor-post-release fixes
     |/
89dc * [master] Release v0.1
10ba * final fixes before release
```
and would select/type `devel` as the destination to rebase onto. This would case `git rebase --onto devel 45ef^ HEAD` or `git rebase --onto devel 45ef^ feature-branch-A` (AFAIU these are equivalent).

The result would be the following:
```
ba01   * [[feature-branch-A]] fixed latent bug
dc32   * finalize new feature
fe54   * implement proof of concept of the feature
01ab * | [ORIG_HEAD] fixed latent bug
23cd * | finalize new feature
45ef * | implement proof of concept of the feature
67ba | * [devel] minor-post-release fixes
     |/
89dc * [master] Release v0.1
10ba * final fixes before release
```

**Comment by gleber** [comment]
#### Case 2: `<edge1>..branch1` onto X

Actually if you consider this case, it's exactly the same as previous, except that one starts with a different current branch.

In this case user would do the mark the following way. Please note that in contrast to previous case `[[master]]` is currently checked out branch:
```
01ab * [feature-branch-A] fixed latent bug <-- first marked line
23cd * finalize new feature
45ef * implement proof of concept of the feature <-- last marked line
67ba | * [devel] minor-post-release fixes
     |/
89dc * [[master]] Release v0.1
10ba * final fixes before release
```
and would select/type `devel` as the destination to rebase onto. This would case `git rebase --onto devel 45ef^ feature-branch-A` (in this case the branch needs to be named explicitly, since it is not the currently checked out branch).

The result would be the following:
```
ba01   * [[feature-branch-A]] fixed latent bug
dc32   * finalize new feature
fe54   * implement proof of concept of the feature
01ab * | [ORIG_HEAD] fixed latent bug
23cd * | finalize new feature
45ef * | implement proof of concept of the feature
67ba | * [devel] minor-post-release fixes
     |/
89dc * [master] Release v0.1
10ba * final fixes before release
```

Git would automatically checkout `feature-branch-A`. Old head of it (`01ab`) might be or might not be marked as `ORIG_HEAD`, I am not sure here.

**Comment by gleber** [comment]
#### Case 3: `<edge1>..<edge2>` onto X

We start with the following setup:
```
00ff * [feature-branch-A] fixed yet another old bug <-- first marked line
01ab * fixed latent bug <-- last marked line
23cd * finalize new feature
45ef * implement proof of concept of the feature
67ba | * [[devel]] minor-post-release fixes
     |/
89dc * [master] Release v0.1
10ba * final fixes before release
```

Let's say user would like to get commits `00ff` and `01ab` applied on top of `devel` and start developing a new feature in a new branch.

In this case user would mark the region as on the example above and would select/type `devel` as the destination to rebase onto. This would case `git rebase --onto devel 01ab^ 00ff`.

The result would be the following:
```
ff00   * @ fixed yet another old bug
ba01   * fixed latent bug
00ff * | [feature-branch-A] fixed yet another old bug
01ab * | fixed latent bug
23cd * | finalize new feature
45ef * | implement proof of concept of the feature
67ba | * [devel] minor-post-release fixes
     |/
89dc * [master] Release v0.1
10ba * final fixes before release
```

This would lead to a detached head. Here user could easily do `M-x magit-branch-and-checkout` and type `feature-branch-B` to start a new branch with two new commits and start working on it.


What do you think?

**Comment by tarsius** [comment]
#### Case 1:

This already works now and you do not even have to mark the commits to be rebases: `r e <target> RET`. If `devel` is configured as the upstream of `feature-branch-A`, then it's just `r u`.

#### Case 2:

> Actually if you consider this case, it's exactly the same as previous, except that one starts with a different current branch.

And I think it is okay that you first have to checkout the "branch to be rebase" in a separate step. After you have done that proceed like in (1).

#### Case 3:

> I am using "rebasing" and "cherry-picking of range of commits" interchangeably, since they are equivalent from the point of view of intended results in terms of resulting commit graph.

I think it helps tremendously to keep the two operations separate. To rebase means to "apply commits from here to over there", while to cherry-pick mean to "apply commits from over there here".

> This would lead to a detached head. Here user could easily do `M-x magit-branch-and-checkout` and type `feature-branch-B` to start a new branch with two new commits and start working on it.

Instead of first rebasing and ending up with a detached HEAD which you then turn into a new branch, you could also first create a new branch and then cherry-pick the same commits.

* Create the branch `b c RET feature-branch-B RET`.
* Mark commits `00ff` and `01ab`.
* Cherry-pick `A A`

> What do you think?

Yes, cherry-picking does already support "act on commits in region"! I think that here that makes a lot of sense. In the case of rebasing, not so much.

**Comment by tarsius** [comment]
I think the problem is that you used `r s` when you should have used `r e` (or `r p` and `r u`). "Rebase subset" is intended for special cases.

**Comment by gleber** [comment]
#### Case 1

This is not true in general, if I would like to rebase only top N comments of branch `feature-branch-A` to `<target>`, then `r e <target> RET` won't work. Current implementation of `r s` requires more keystrokes and is not general enough.

#### Case 2

You are suggesting solution which requires more keystrokes than what can be done with region marking and with mechanisms which `git rebase --onto` provides.

#### Case 3

This way of thinking about rebase and cherry-pick makes sense. Thanks.

That's nice to know that cherry-picking provides "act on commits in region", it might be handy in future. But these are not equivalent, since cherry-picking does not switch git to rebase mode, hence in case of conflicts you are on your own (at least as far as my current magit version) and magit doesn't give you rebase continue / skip / abort interface.

I still see a distinct value of providing a graphical interface to mechanisms of `git rebase --onto` over existing capabilities which magit provides. This would make working with complicated trees of branches much faster IMO. Also it would just provide a direct interface to what git command line tool provides, hence a user does not have to learn any new concepts.

**Comment by tarsius** [comment]
> But these are not equivalent, since cherry-picking does not switch git to rebase mode, hence in case of conflicts you are on your own (at least as far as my current magit version) and magit doesn't give you rebase continue / skip / abort interface.

Since rebase != cherry-pick the rebase popup <kbd>r</kbd> indeed does not allow to continue/skip/abort a cherry-pick -- however the cherry-pick popup <kbd>A</kbd> does.

**Comment by gleber** [comment]
I did test it, and it didn't work for me. Now I re-tested it and it did work. I think when I was testing it I must have used `A a` instead of `A A`.

Looks like this reduces benefits of the proposal to the following two use cases.

1. Rebase top N commits of a current branch onto another branch.
2. Rebase a range of commits - when outermost edge of the range is not a branch - onto another commit, which results in a detached head.

First one seem to be possible with `r s`. In this case the difference is in number of keystrokes and, subjectively, it's more natural to convey my intent to magit. I am a visually-inclined person, so visual selection of the range of CLs to be rebased is very natural way to represent it.

The latter is not possible in one step with existing magit functionality. One might argue it is not very useful, but then why was it included into `git rebase --onto`?

I argue the proposed feature is still useful.

**Comment by tarsius** [comment]
I think (2) is an anti-pattern. Instead start with creating a new branch whose tip is the "edge". Only then rebase.

> One might argue it is not very useful, but then why was it included into `git rebase --onto`?

I don't know, but I suspect it's this kind of thing that makes some users complain about git's command line interface. I don't think it is a good idea to provide this feature in Magit just because "you can do it with Git too".

Once we have decided that we do not insist on one end being the HEAD (and I don't think you will be able to convince me otherwise), it no longer makes sense to use the region based selection. Because one of the ends is predefined (HEAD), only the other can be selected which can be done by moving the cursor there without first marking the other end. (Which by the way would require moving to both ends, i.e. "more keystrokes".)

So we just have to teach the `interactive` form of `magit-rebase-subset` to start rebasing with the commit at point.

There are two problems with that.

1. I would like the user to confirm that commit. The user would be asked something like "Start rebasing with <commit> (y or n)" and would then have to press `y`. (An option could be added so that users could choose whether confirmation should be required or not. But, but due to how this currently behaves, the default should be that confirmation is required.) Compared to what we currently have this has the disadvantage, that you can only confirm or abort, what would be lost is the ability to choose another commit at this point. (Originally no buffer with a log of recent commits was shown, instead minibuffer completion was used to let the user select the commit.) Instead of using `C-c C-c` to confirm the default choice (or another choice) you can also use `.` (which is bound to the same command), i.e. exactly the same amount of keystrokes as pressing `y` would be.

2. Currently the commit/branch at point is used as the default choice for the target onto which the subset is rebased. We cannot use the commit/branch at point as the default for both the target as well as the beginning of the subset (actually this isn't true, see below). I had the choice between these two options and went with using the commit/branch at point as the default target because `magit-rebase` behaves the same way.

Also if I had gone the other way, and used the commit at point as the beginning of the subset (possibly even without requiring confirmation), then I still would have had to implement I mechanism to select the starting point later, because otherwise I would have forced users to first navigate to a log before being able to initiate a subset rebase.

One thing that could be done though is to determine whether the commit/branch at point should be used as the default choice for the target or as default choice for the beginning of the subset based on whether that commit is reachable from the HEAD.

In fact we already do that, for the most part. The commit/branch at point is *always* offered as the default choice when selecting the target, even if that commit is reachable from HEAD. This could be avoided, but doing so would actually remove a (somewhat obscure) feature. (A subset rebase can be used to remove commits from the current branch. Doing so requires that a reachable commit is selected as the target. Not offering the commit at point as the default choice for target selection would make doing that harder.)

That same commit is then also offered as the default choice when selecting the beginning of the subset, *provided that the commit is reachable from HEAD*. This is done by putting point on that commit in the `*magit-log-select: <repo>*` buffer. That default can then be confirmed by typing `C-c C-c` (or `.`).

If you really want region-based subset-rebase selection, then you can implement that locally - it shouldn't be to hard to create an adjusted variant of `magit-rebase-subset`. I do not intend to add something like this to Magit, sorry.

**Comment by gleber** [comment]
Thanks for writing the detailed answer. Looks like we have very different way of thinking about git workflows.
