### ISSUE TITLE
File name gets cut off in magit log --patch

### ISSUE THREAD

**Issue by fice-t** [magit/magit#2622]
If you do a log with --patch and **without --graph** then the first 2 characters of the file name get cut off.

Here's an example of a test log (with only --patch) in a repo in which I created `test.el` in one commit, then edited it in the 2nd:

```
ce5a28c New line!
modified   st.el
@@ -0,0 +1 @@
+(message "new line here!")

158f2be New file
new file   st.el

```

This is reproduced under `emacs -Q` and `Magit 20160416.825, Git 2.5.5, Emacs 24.5.1, gnu/linux`

As an aside, why is the `--patch` switch on `-u` and not `-p`? Was there another command that was on `-p` before?

**Comment by kyleam** [comment]
> As an aside, why is the --patch switch on -u and not -p? Was there
> another command that was on -p before?

I'm not sure, but I don't think it's because of previous a conflict.
`-u`, `-p`, and `--patch` are all equivalent flags to `git log`.  The
`--patch` flag was originally introduced as the short flag `-u` in
18d8fce.  At that time, there was a `P`, but no lower case `p`.  Then,
in d2e209f it was changed to the longer `--patch`.

**Comment by fice-t** [comment]
Ah, I see. I'm not sure what `-u` would stand for then. I'd say that `-p` is much more intuitive.

Thanks.

**Comment by kyleam** [comment]
I believe  it stands for "unified", as in `diff -u`.
