### ISSUE TITLE
Completion of rebase interactive does not refresh the log buffer

### ISSUE THREAD

**Issue by jsyjr** [magit/magit#2626]
I want to make a small change to an earlier commit:
* I initiate a rebase interactive (r i).
* I mark the appropriate commit as for edit (e).
* An @ marker appears in my log buffer and the list of cmmits to be replayed shows up in my status buffer.
* I make my change, save, stage (s) and complete my rebase via (r r) in the status buffer.
* My status buffer gets refreshed.
* My log buffer continues to display the @ marker.

If I refresh (g) or request a display of the log (l l) the @ disappears.

[Time for an MVC (Model-View-Controller) architecture? :-)]

**Comment by tarsius** [comment]
This is expected. After running a Magit command which might require that Magit buffers are refreshed the current Magit buffer is refreshed as well as the status buffer. But only those, and in most cases the status buffer is the current buffer.

Refreshing Magit buffers is fairly expensive because they are recreated from scratch. So we don't refresh all Magit buffers. In the long run, i.e. once it is possible to only refresh those parts of a buffer which actually need to be refreshed and a cache is being used, then we will likely start refreshing all buffers.

By the way, you can refresh any Magit buffer with <kbd>g</kbd>.
