### ISSUE TITLE
Can't discard changes from magit-file-popup's "diff DWIM"

### ISSUE THREAD

**Issue by johnmastro** [magit/magit#2627]
To reproduce:

1. `cd ~/src/magit`
2. `make emacs-Q`
3. `C-x C-f [some file with uncommitted changes] RET`
4. `M-: (require 'magit) RET`
5. `M-x magit-file-popup RET`
6. `dd`
7. Move point to a hunk header
8. `k`

Expected result: The hunk's changes are discarded
Actual result: The hunk's changes are not discarded and "Cannot discard committed changes" is displayed in the echo area.

The result is the same if the file is staged or unstaged. The same series of steps succeeds if you use `du` (diff unstaged) instead of `dd` (diff DWIM) at step 6. It also succeeds if you start from `magit-status` instead of `magit-file-popup`.

Output of `magit-version`:
`Magit 2.6.1-10-gf6601b3, Git 2.8.1, Emacs 25.0.92.1, gnu/linux`

**Comment by tarsius** [comment]
Does `dd`, after preceding steps, really just show the unstaged changes, or does it ask for a range? When I follow those steps, then I am asks for a range (and that's also what I expected to happen). Also you could just use `du` instead, and then you can discard.

`dd` guesses the range and/or whether `--cached` should be used. It does so by inspecting information at point. It can only do that in a Magit buffer (and even there not in all places). In a file buffer, which may visit a file with both staged and unstaged changes, there is no information at point which could be used to guess what diff you want to say. (Well we could  check whether point is inside a staged or unstaged change, but that would be quite some work, esp. since Magit currently leaves visualizing changes in file-visiting buffers to other packages such as `diff-hl`.

But we should make sure we fall back to `undefined` not `committed` as the "diff type" in all cases, that would be less confusing.

**Comment by johnmastro** [comment]
> Does dd, after the preceding steps, really just show the unstaged changes, or does it ask for a range? When I follow those steps, then I am asks for a range (and that's also what I expected to happen).

You're right, it does ask for a range. In my scenario above I hit `RET` to accept the default (`master`) - sorry I forgot to include that.

> dd guesses the range and/or whether --cached should be used. It does so by inspecting information at point. It can (currently) only do that in a Magit buffer (and even there not in all places). In a file buffer, which may visit a file with both staged and unstaged changes, there is no information at point which could be used to guess what diff you want to say.

> (Well we could check whether point is inside a staged or unstaged change, but that would be quite some work, esp. since Magit currently leaves visualizing changes in file-visiting buffers to other packages such as diff-hl.)

Ah, that makes sense. It doesn't sound like the added complexity to support that would be warranted.

> But we should make sure we fall back to undefined not committed as the "diff type" in all cases, that would be less confusing. But except for that I do not intend to change anything in the short run, just use the more explicit du instead of dd which isn't capable enough to guess correctly in this case.

Thanks for looking into this and for the explanation! I'll stick to `du` when doing this.

**Comment by tarsius** [comment]
> You're right, it does ask for a range. In my scenario above I hit `RET` to accept the default (`master`) - sorry I forgot to include that.

In that case you are not actually showing the unstaged changes! (The header of the diff buffer begins with "Unstaged changes" when actually showing unstaged changes.) Instead you were showing the changes between the `master` branch and HEAD, and since those changes actually are committed, Magit was right in telling you that those cannot be unstaged because they are committed.

**Comment by johnmastro** [comment]
> In that case you are not actually showing the unstaged changes! (The header of the diff buffer begins with "Unstaged changes" when actually showing unstaged changes.) Instead you were showing the changes between the master branch and HEAD, and since those changes actually are committed, Magit was right in telling you that those cannot be unstaged because they are committed.

I may be misunderstanding but I don't think that's right. The header says e.g. `Changes from master to working tree in file init.el` and that seems correct - it includes all uncommitted changes (staged and unstaged).

Granted, I don't think that affects the conclusion.

**Comment by kyleam** [comment]
> Instead you were showing the changes between the master branch and
> HEAD

It's with the working tree rather than HEAD, so there may be some
unstaged, as well as staged, changes lumped in with the diff.

**Comment by grothesque** [comment]
I noticed that the same problem appears (with Magit 2.12.0, Git 2.18.0, Emacs 25.2.2, gnu/linux) in the diff buffer opened by M-x magit-diff-buffer-file (or by pressing "d" in the magit-file-popup): it is not possible to discard changes by pressing "k".  Should I open a new issue for this?

**Comment by tarsius** [comment]
https://github.com/magit/magit/commits/uncommitted should fix this.

**Comment by grothesque** [comment]
Thanks for the quick fix!
