### ISSUE TITLE
Speeding up grooming

### ISSUE THREAD

**Issue by jsyjr** [magit/magit#2630]
I have recently discovered the difference between "rebasing interactively" (r i) and "rebasing to edit a commit" (r m).  I appreciate the increased efficiency during commit grooming.  Some suggestions:

* The 'm' sub-command might be more mnemonically described as "to modify a commit".
* Having staged my modifications often it would speed things up if the rebase popup offered a choice to reuse the current commit message.  My first thought is 'f' meaning something like 'finish' or 'fast'.

**Comment by tarsius** [comment]
1. True. Though in other places we also use "edit", which is one reason why we use that here too. Some time back it was actually <kbd>e</kbd> which was bound to this command, which *was* another reason to use "edit". Don't feel strongly about this - what do others think?

2. Like in <kbd>r f</kbd> instead of <kbd>r r</kbd>, commit message buffer popups up, and then <kbd>C-c C-c</kbd>. Yeah, that would be a bit faster and while this extra step never really bothered me, now that you mention it...

   It would be a bit of work to implement that though, because `git rebase --continue` does not offer an option to not have the user review the message. But that edit request could be intercepted and ignored.

**Comment by tarsius** [comment]
You could also use <kbd>c a</kbd> followed by <kbd>r r</kbd>. That's two commands, but at least the commit message buffer won't pop up. On the other hand, getting to see the message allowed me a few times to notice that I accidentally squashed or dropped commits.

**Comment by jsyjr** [comment]
(What markup do you use for those pretty character sequences?)

Does not (c a) restrict me to amending the most recent commit?

My focus in this discussion is grooming a series of commits to get them into a state for review and pushing up-stream.  That is why (r m) is so pleasant.  It lets me jump into the middle of my series of commits more efficiently than (r i).  (rm) saves me having to navigate to a commit line in the popped up buffer and hit (e c-c c-c).  I often do this repeatedly as part of polishing comments, fixing typo, etc.

**Comment by npostavs** [comment]
> (What markup do you use for those pretty character sequences?)

It's `<kbd>c a</kbd>` (github should really let people see markup without having to have edit privileges...)

> Does not (c a) restrict me to amending the most recent commit?

After you have done <kbd>r m</kbd>, the most recent commit is the one you want to modify. I think <kbd>c e</kbd> was meant, since amending also pops up the message buffer for editing. So comparing the entire sequence with and without the hypothetical <kbd>r f</kbd>:

- <kbd>r m</kbd> (do some modifications, stage) <kbd>r f</kbd>
- <kbd>r m</kbd> (do some modifications, stage) <kbd>c e</kbd> <kbd>r r</kbd>

**Comment by tarsius** [comment]
Please try the above commit.

I am not sure whether that really is a good idea though.

**Comment by jsyjr** [comment]
@tarsius : Thanks.  I will try it but you will have to wait for a week.  I am leaving in a few hours for a week's vacation with my wife.  No coding allowed.

**Comment by tarsius** [comment]
Have fun!

**Comment by tarsius** [comment]
Closing in favor of #2641.
