### ISSUE TITLE
COMMIT_EDITMSG does not always appear when expected

### ISSUE THREAD

**Issue by abingham** [magit/magit#2632]
From time to time when I run `magit-commit` the `COMMIT_EDITMSG` buffer does not become visible. It exists and I can switch to it manually, but it doesn't become visible automatically as I (perhaps incorrectly) expect. I don't have a good sense right now of what conditions cause this, e.g. if it happens when the commit is large, I have lots of buffers open, or something like that. There may not even be a pattern. The large majority of the time (say, 90% or so) the buffer becomes visible properly.

This is on windows using spacemacs, and I've definitely seen it over the past few versions of spacemacs. I *think* I've seen it on OSX, but I'm not 100% certain.

This problem could well be the result of spacemacs, but I figured I'd check here first since it's at least proximally a magit issue.

**Comment by npostavs** [comment]
I've hit this too, and I'm equally unsure about the pattern.

**Comment by abingham** [comment]
@npostavs Are you using spacemacs?

**Comment by npostavs** [comment]
No, not using spacemacs. It could be something in my config that's also in spacemacs though?

**Comment by phil-s** [comment]
Likewise for me -- this happens from time to time, but I've not investigated why. (Also not using Spacemacs.)

**Comment by tarsius** [comment]
Used to happen to me too but hasn't in a long time.

I suspect it's a bad interaction with "something else". Unfortunately the code responsible for showing that buffer and the diff buffer is... a bit complicated. It can be found all over the place and I should probably write a short overview explaining how the various pieces work together.

**Comment by abingham** [comment]
I've been trying to pay attention to what causes this to happen, and there seems to be a correlation with deleting the COMMIT_EDITMSG buffer explicitly. That is, sometimes I cancel a commit by running `kill-this-buffer` rather than the (what I assume is) more appropriate `with-editor-cancel`. When I do this, the diff buffer stays around.

Subsequently, when I do a commit the diff buffer is displayed instead of the expected commit message buffer.

I haven't nailed down a 100% reproducible set of steps, but perhaps this gives some clues as to what's going on. I'll see if I can find a way to reproduce this consistently.

**Comment by npostavs** [comment]
> That is, sometimes I cancel a commit by running kill-this-buffer rather than the (what I assume is) more appropriate with-editor-cancel.

Aha, my config has a key binding to `kill-buffer` so this could be it.

**Comment by marinintim** [comment]
Happens to me when I open diff buffer separately and there are at least two buffers visible.

**Comment by tarsius** [comment]
> Happens to me when I open diff buffer separately and there are at least two buffers visible.

I can reproduce that when I type `c c` within the diff buffer. I can understand why that fails and it shouldn't be to hard to fix that.

Does that also happen when you bring up the diff buffer, go back to the status buffer, and then type `c c`?

----

When this happens again (in other cases than the above), then also try whether:

1. The commit file is actually being in a visible buffer in *another* frame (which potentially is "invisible" because other X11 windows cover it or is located on another virtual desktop).

  If I remember correctly, that used to happen to me if I previously initiated a commit from the command line. But I cannot reproduce this.

2. If the buffer is created but not made current in any window on any frame.

**Comment by tarsius** [comment]
I have narrowed the issue down somewhat, and have also found a fix, but I do not know the cause of the issue.

I have created two situations that as far as I can tell are identical.

* Common part. `(display-buffer DIFF-BUFFER nil)` is called. The current buffer is the commit message buffer. It previously displayed the diff buffer. There is another buffer in the frame, the status buffer.  The exact same code is called to display the diff buffer `(magit-diff-staged)` (I edited both `magit-commit-diff` and `magit-diff-while-committing` to do that and nothing else.

1. Removed `magit-commit-diff` from `server-switch-hook` to prevent the diff from automatically being displayed. Invoke a commit with the diff buffer/window current. The diff buffer is replaced with the message buffer. Then I interactively invoke `magit-diff-while-committing`. The diff buffer is displayed in the window which previously displayed the status window. In the process `display-buffer-in-previous-window` is called, but it decides it cannot display the buffer.

2. Add `magit-commit-diff` back to `server-switch-hook`. Everything else is the same and the commit buffer is displayed in the same window as before, but then `magit-commit-diff` buffer is called without user intervention. This time around `display-buffer-in-previous-window` decides it can display the buffer and it does so in the "previous window", which previously displayed the commit buffer, and before that the diff buffer. I.e. it does use the "previous window".

In one case `display-buffer-in-previous-window` displays the buffer in the other it does not. I made the two cases as similar as possible and inspected the values of the various `display-buffer-*` variables. As far as I can tell everything is the same.

---

Well, I have fixed this by using `(display-buffer BUFFER '(display-buffer-use-some-window . (inhibit-same-window t))` instead of `(display-buffer BUFFER nil)` when we don't want the current window to be used to display BUFFER. But what the relevant difference between the above two cases is, will probably remain a mystery.

**Comment by tarsius** [comment]
Okay, so I have thought about this again with a clear mind and the difference is simple: in one case the diff buffer *was* previously displayed in the buffer which now displays the commit message buffer, and in the other it was *not*. Simple as that.

I have now removed the previous kludge and added a new one based on actually knowing what's going on: remove the diff buffer from the list of buffers that were previously displayed in the buffer currently displaying the commit message buffer before displaying the diff buffer again.

**Comment by marinintim** [comment]
@tarsius what should I do to check out fix, just update from melpa?
