### ISSUE TITLE
[magit.el] Use `locate-library` to locate 'magit-version.el' in 'static' case

### ISSUE THREAD

**Issue by vp1981** [magit/magit#2636]
Hello,
consider to apply following patch to `magit.el`:
```
diff --git a/lisp/magit.el b/lisp/magit.el
index 6afb049..c99048d 100644
--- a/lisp/magit.el
+++ b/lisp/magit.el
@@ -2826,7 +2826,7 @@ Git, and Emacs in the echo area."
              (gitdir (expand-file-name
                       ".git" (file-name-directory
                               (directory-file-name topdir))))
-             (static (expand-file-name "magit-version.el" topdir)))
+             (static (locate-library "magit-version.el")))
         (or (progn
               (push 'repo debug)
               (when (and (file-exists-p gitdir)
```

If I understand code correctly, the `static` variable is used for "static" case, i.e. when magit installed by a distribution package manager. In such case el files can be compressed and `expand-file-name` gives full path to non-existing file while `locate-library` returns path to existing file (for example, the current call returns `/usr/share/emacs/site-lisp/magit/magit-version.el`, while correct path is `/usr/share/emacs/site-lisp/magit/magit-version.el.gz` and it is returned by `locate-library`).

I tested this patch in my Linux distribution (Archlinux x86_64), for which I build distro-package from git repository and `M-x magit-version` works fine. Without this patch I see message in `*Messages*` buffer beginning with "Cannot determine Magit version...".

**Comment by tarsius** [comment]
Well that's a bug in the Arch package -Magit expects this file not to be compressed and it is being compressed anyway - but I suspect other distributions have to same issue, so let's avoid this here.

Your change doesn't quite do it. One case this function has to cover is when a user has installed multiple Magit versions and thinks s/he is using a version different from that s/he is actually using. This change would make it less likely that we would notice that because now a `magit-version.el*` file might be found that is located outside the installation which is being used. By using the PATH argument we can avoid that.
