### ISSUE TITLE
Make no such file or directory /path/to/magit/magit-version.el

### ISSUE THREAD

**Issue by kas2207** [magit/magit#2643]
I am trying to build magit from the git repository but I am having issues with make.
I first pulled with-editor and dash from github and brought them into my site-lisp directory using gitsubtree (my .emacs.d directory is within a github repository).
I then created the config.mk file with the three variables specified in the manual, providing the paths to my magit, with-editor, and dash directories.
I then ran make within the magit directory and received the following output:

```bash
$ make
Cannot open load file: no such file or directory, /home/kyleschmidt/dotfiles/emacs.d/site-lisp/magit/magit-version.el
make[1]: Entering directory '/home/kyleschmidt/dotfiles/emacs.d/site-lisp/magit/lisp'
Cannot open load file: no such file or directory, /home/kyleschmidt/dotfiles/emacs.d/site-lisp/magit/lisp/magit-version.el
Compiling git-commit.el
Compiling magit-popup.el
Compiling magit-utils.el
Compiling magit-section.el
Compiling magit-git.el
Compiling magit-mode.el
Compiling magit-process.el
Compiling magit-autorevert.el
Compiling magit-core.el
Compiling magit-diff.el
Compiling magit-log.el
Compiling magit-wip.el
Compiling magit-apply.el
Compiling magit.el
Compiling magit-sequence.el
Cannot determine Magit's version (error "/home/kyleschmidt/dotfiles/emacs.d/site-lisp/magit/lisp/magit.el" repo static elpa)
Compiling magit-commit.el
Cannot determine Magit's version (error "/home/kyleschmidt/dotfiles/emacs.d/site-lisp/magit/lisp/magit.el" repo static elpa)
Compiling magit-remote.el
Cannot determine Magit's version (error "/home/kyleschmidt/dotfiles/emacs.d/site-lisp/magit/lisp/magit.el" repo static elpa)
Compiling magit-bisect.el
Cannot determine Magit's version (error "/home/kyleschmidt/dotfiles/emacs.d/site-lisp/magit/lisp/magit.el" repo static elpa)
Compiling magit-stash.el
Cannot determine Magit's version (error "/home/kyleschmidt/dotfiles/emacs.d/site-lisp/magit/lisp/magit.el" repo static elpa)
Compiling magit-blame.el
Cannot determine Magit's version (error "/home/kyleschmidt/dotfiles/emacs.d/site-lisp/magit/lisp/magit.el" repo static elpa)
Compiling magit-submodule.el
Cannot determine Magit's version (error "/home/kyleschmidt/dotfiles/emacs.d/site-lisp/magit/lisp/magit.el" repo static elpa)
Compiling magit-subtree.el
Cannot determine Magit's version (error "/home/kyleschmidt/dotfiles/emacs.d/site-lisp/magit/lisp/magit.el" repo static elpa)
Compiling magit-ediff.el
Cannot determine Magit's version (error "/home/kyleschmidt/dotfiles/emacs.d/site-lisp/magit/lisp/magit.el" repo static elpa)
Compiling magit-extras.el
Cannot determine Magit's version (error "/home/kyleschmidt/dotfiles/emacs.d/site-lisp/magit/lisp/magit.el" repo static elpa)
Compiling git-rebase.el
Cannot determine Magit's version (error "/home/kyleschmidt/dotfiles/emacs.d/site-lisp/magit/lisp/magit.el" repo static elpa)
Generating magit-version.el
Generating magit-autoloads.el
Wrote /home/kyleschmidt/dotfiles/emacs.d/site-lisp/magit/lisp/magit-autoloads.el
make[1]: Leaving directory '/home/kyleschmidt/dotfiles/emacs.d/site-lisp/magit/lisp'
make[1]: Entering directory '/home/kyleschmidt/dotfiles/emacs.d/site-lisp/magit/Documentation'
Cannot open load file: no such file or directory, /home/kyleschmidt/dotfiles/emacs.d/site-lisp/magit/Documentation/magit-version.el
Generating magit-popup.info
Generating magit.info
Generating dir
make[1]: Leaving directory '/home/kyleschmidt/dotfiles/emacs.d/site-lisp/magit/Documentation'
```

OS: Debian Jessie
Emacs: 24.4.1
Git: 2.1.4

I am not able to run ```M-x magit-version```.
When I run ```M-x magit-status```, I receive the following: Cannot open load file: no such file or directory, dash

Thank you for your help.

**Comment by tarsius** [comment]
I did make  some changes to `magit-version` a little while ago, but I don't think that's the issue.

Magit depends on `dash` and it appears you haven't installed that.

Also see https://magit.vc/manual/magit/Installing-from-the-Git-repository.html.

**Comment by kas2207** [comment]
I have placed dash in my site-lisp directory. I have also used the manual to install magit which is why I'm a little confused why magit didn't build correctly. I made the config.mk file and added the following:

LOAD_PATH  = -L /home/kyleschmidt/dotfiles/emacs.d/site-lisp/magit/lisp
LOAD_PATH += -L /home/kyleschmidt/dotfiles/emacs.d/site-lisp/dash
LOAD_PATH += -L /home/kyleschmidt/dotfiles/emacs.d/site-lisp/with-editor

**Comment by tarsius** [comment]
And now it works?

**Comment by kas2207** [comment]
That's what I originally did to produce the error.

**Comment by tarsius** [comment]
Ah. Well then it probably is that recent change I made that is causing this issue. Try reverting 3be90fb87e18f705b30d9ec81ac128bf23eb63a3.

**Comment by kas2207** [comment]
That worked! Thank you!!

**Comment by tarsius** [comment]
I would like to investigate this issue further.

There actually appear to be two issues:

1. At least at compile time `magit-version` cannot be loaded leading to some *warnings*. Compilation succeeds anyway, otherwise `make` would fail. But `magit-version.el` is probably still missing afterwards, which shouldn't be fatal.

2. At runtime `dash` appears to be unavailable: `Cannot open load file: no such file or directory, dash`. That's fatal. Setting `LOAD_PATH` in `config.mk` doesn't help with that as this is only used during compilation.

I don't know why reverting the commit actually helped. I suspect that you changed something else too.

Could you please revert the revert, make sure you are up-to-date with `origin/master` and try again.

First remove all generated files using `make clean`. Then make sure both magit's `lisp` directory and dash's top-directory are in the `load-path`. The explicitly require `magit`. There is no autoloads file, so you have to do it explicitly. Then also test whether `M-x magit-status` works.

Once we know that this works we can get to the second issue.

```
$ make
Cannot open load file: no such file or directory, /home/kyleschmidt/dotfiles/emacs.d/site-lisp/magit/magit-version.el
make[1]: Entering directory '/home/kyleschmidt/dotfiles/emacs.d/site-lisp/magit/lisp'
```

This warning is shown before entering the `lisp` directory, which indicates that it it occurs while setting the variable `VERSION` at the end of `default.mk`, which in turn is included by `Makefile`.

```
VERSION := $(shell \
  test -e $(TOP).git\
  && git describe --tags --dirty 2> /dev/null\
  || $(BATCH) --eval "(progn\
  (fset 'message (lambda (&rest _)))\
  (load-file \"magit-version.el\")\
  (princ magit-version))")
```

I confirmed that this is likely by removing `test ... ||` in this piece of code. If I do that I get the same warning.

Since `$(TOP).git` exists (right?) only `git describe...` should be evaluated, unless of course that returns with a non-zero exit status. Replace the `2> /dev/null` with `2>&1`. Then we might get some error message in place of the version which is supposed to be shown when running `make help`.

```
$ make help

Current version: magit-2.6.2-25-ge3c7a2c-dirty
....
```

Also try running `git describe --tags --dirty` on the command line.

**Comment by tarsius** [comment]
> brought them into my site-lisp directory using gitsubtree

Ah, that explains it. Magit's build system expects to be run from within a real git repository with tags and everything, or from an extracted tarball which contains `magit-version.el`. This doesn't work when using a shallow clone or a subtree merge.

But this isn't fatal, you will just get these warnings and the `magit-version` function will fail in interactive use also. I think I'll leave at this.

Some off-topic remarks:

1. I just added support for subtrees, see #2640.

2. I recommend using submodules instead of subtrees to install Emacs packages.

3. I am going to release a package which is based on that idea as soon as: tomorrow!
