### ISSUE TITLE
Add action for renaming stashes

### ISSUE THREAD

**Issue by dustinpaluch** [magit/magit#2650]
It would be nice to have an action via the magit-stash-popup for renaming a stash.

 I don't always have the time/patience to come up with a good stash message at the time of creation. It would be nice to be able to redo a stash message without popping/saving. (Also for fixing typos)

**Comment by tarsius** [comment]
Due to how Git implements stashes (it uses a single ref and individual stashes are only stored in the reflog of that ref) this is not actually possible. The closest we could get is creating a new stash (`stash{0}`) which is identical to the other stash except for the commit message.

**Comment by tarsius** [comment]
And doing so would be fairly complicated. I don't think it is worth the effort.

**Comment by dustinpaluch** [comment]
Oh well. Thanks for investigating.

**Comment by fice-t** [comment]
@tarsius What about doing something like http://stackoverflow.com/a/35549615?

**Comment by kyleam** [comment]
> @tarsius What about doing something like http://stackoverflow.com/a/35549615?

A frew weeks ago I added [a command] to my configuration that uses
that approach.  (I'd guess that I got the information from that
question.)

```elisp
(defun magit-stash-edit-message (stash message)
  "Change STASH's message to MESSAGE."
  (interactive
   (let* ((stash (magit-read-stash "Rename" t))
          (old-msg (magit-git-string "show" "-s" "--format=%s" stash)))
     (list stash (magit-read-string "Stash message" old-msg))))
  (let ((commit (magit-rev-parse stash))
        (inhibit-magit-refresh t))
    (magit-stash-drop stash)
    (magit-stash-store message "refs/stash" commit))
  (magit-refresh))
```

It seems to work OK, but I haven't used it much.  I tend to work with
stashes in a very transient manner, so I very rarely care about the
messages.

@fice-t, if you have a workflow that would use this command more
often, perhaps you could test the command out a bit and raise the
issue again if you think we should consider adding it.

[a command]: https://github.com/kyleam/emacs.d/commit/552e3a5951840c082529ae1dd90304e2d37435d9

**Comment by fice-t** [comment]
@kyleam Thanks. I wouldn't say I use it often, but I seem to have the occasional habit of lazily creating a poor stash message and wanting to refine it a few days/weeks later.

One problem I noticed is that while it updates the name in `magit-status`, when viewing the stash with `RET`, and also when trying to rename it again, only the old message appears in the stash buffer/minibuffer. Otherwise it seems to work as expected.

**Comment by kyleam** [comment]
Yes, that problem is inherent to the approach you linked to (i.e, if
you did the those commands at the terminal, you'd see the same thing).
The same commit is being used, so you can't change the actual commit
message.  Instead, the reflog message is changed.  (Given how hacky
this is, it probably shouldn't be added to Magit.)

To get the actual commit message changed, you're back in the situation
that @tarsius decribed above.  In which case, I agree that it doesn't
seem worth the effort.

**Comment by tarsius** [comment]
> Given how hacky this is, it probably shouldn't be added to Magit.

I wouldn't mind adding it to the `magit-rockstar` package. (But with a more precise doc-string.)

**Comment by fice-t** [comment]
@kyleam Right, sorry about missing that.

Though for my needs just a better name in `magit-status` is all I really need.

I suppose stashing the index, popping the desired stash, re-stashing with a new name, and popping the index stash is too risky to do?

**Comment by tarsius** [comment]
> I suppose stashing the index, popping the desired stash, re-stashing with a new name, and popping the index stash is too risky to do?

Well no, that's how I deal with such a situation, but describing that as "edit message" is... not quite accurate ;-)

To avoid potential conflicts a separate working tree should be used. Magit already has some support for creating separate working trees. If someone wants to implement a non-hacky edit-stash-message, then I would suggest looking into that.

**Comment by kyleam** [comment]
Well, if someone implements it, it's of course worth considering, but
as you initially said, it's probably not worth the effort.

Popping and renaming manually with a clean worktree is already simple
(<kbd>zpzz</kbd>).  And if the worktree is dirty, you can just create
another stash before popping.  Also, I think that if the stash no
longer applies cleanly or if the stash is expected to be long-lived,
it makes more sense to turn the stash into a branch rather than giving
it an additional message.

**Comment by ericprud** [comment]
I frequently need stashes when I don't want to distract myself coming up with the best name (tldr1). I use `git rev-parse stash@{n}` (n an integer) to get a hash and `git stash store -m <msg> <hash>` to give it the name I wish I had given it before ([kudos](https://stackoverflow.com/questions/25931026/how-can-i-rename-a-git-stash#comment97031938_25935360)). This works well but re-orders stashes ('cause I'm not doing this in a GUI so I don't bother touching all the ones with lower indexes after renaming the nth).

Because magit is truly fabulous, it may be worth adding an edit mode à la [dired's edit mode](https://www.gnu.org/software/emacs/manual/html_node/emacs/Wdired.html#:~:text=30.17%20Editing%20the%20Dired%20Buffer,while%20in%20a%20Dired%20buffer.). I can imagine there are other priorities but I'm hoping that some skillful geek with be be motivated to contribute such an interface. 

tldr1: My testing dogma pushes me to frequently use stashes (typically when I'm working on something big and notice little issues that I want test or fix without my big changes). As a result, I either spend more cycles than I'd like naming stashes or I end up with stashes with less-than-helpful names.

**Comment by dabrahams** [comment]
FWIW, this feature would be *hugely* valuable to me even if the stashes get reordered.  The ordering is never significant to my workflow.
