### ISSUE TITLE
submodule updating

### ISSUE THREAD

**Issue by npostavs** [magit/magit#2657]
I don't use submodules a lot, basically my only use is when working on yasnippet to update the yasnippet-snippets submodule. The current interface seems suboptimal for my minimal use cases:

#### I need get the changes made in the upstream yasnippet-snippets recorded into the submodule.

The git command for this is `git submodule update --remote` (which I have to lookup pretty much every time). Perhaps `--remote` should be added to the submodule popup? Although my feeling is that the actions should be renamed/reorganized because I can never remember the difference between `update`, `sync`, and `fetch` (and in this particular use case they are all nops).

#### I've switched branches and so the submodule has been left in a modified state.

It's a bit annoying that `k` (`magit-discard`) does nothing on submodule sections. Actually, it looks like magit doesn't even distinguish submodule section as a separate type (even in case of `diff.submodule = log` (this is way too obscure by the way)). We could do that by checking for the special file mode `160000`, according to https://git-scm.com/book/en/v2/Git-Tools-Submodules. 

But maybe it's better to pass `--ignore-submodules` to `git diff` and just rely on `magit-insert-submodules` instead? Speaking of...

#### Looking at submodule status

The submodules that I work with don't have tags, so `magit-insert-submodules` doesn't give very useful info (just a list of directory names). What about using `git submodule status` output for this?

---

Thoughts?

**Comment by tarsius** [comment]
@npostavs @kyleam Now that v2.7 is out I intend to give the "take a break" thing another try. Which means I will try very hard not to implement new features *myself*. But you are more than welcome to implement new features or improve features you feel are lacking. I'll try to comment in a useful time frame, but in some cases my response will essentially be "looks good in principal, I haven't looked at the details, go ahead".

#2656 is an instance of that. We had a discussion about that earlier and I think we pretty much agreed on what to do, just didn't get around to doing it. Now that you have done it, you can probably just go ahead and merge it. Or you could first invite the users who previously showed interest in such variants and ask them to give your implementations a try before you merge.

But it is a somewhat big change, so I appreciate that you opened a pull request and gave my the opportunity to raise any objects. I don't have any in this case - now it is up to you to decide how to proceed.

----

This issue (#2657) is different. It's much more open ended. Please develop these ideas further and then open pull requests. In this case me trying to take a break will probably lead to some delays.

**Comment by tarsius** [comment]
Okay so back from the meta-level...

If you have seen my recent blog post [Assimilate Emacs packages using Git submodules](https://emacsair.me/2016/05/17/assimilate-emacs-packages-as-git-submodules/), then you know that I think that submodules are awesome but that the tooling still needs some work. You might also have noticed that over the last few months I have made little improvements in this area.

It would be nice if the tooling improved on the Git side, but unfortunately they are moving rather slow. A lot of work went into improving support for submodules in basic commands such as `git add`, and that is certainly very important but not very visible unless you read the release notes. But the improvements to `git submodule` itself have been to conservative for my taste.

I recently made a (rather poor) attempt to encourage the Git folks to improve some aspects of that command. And I will try to follow up on that soon, but I do not have high hopes. I suspect that I might end up forking `git submodule`, and if I do, then shipping that with Magit might be an option.

Or I might do the same as I have done for `git stash`: write a completely new implementation in Elisp. But since I do hope that if I write an improved `git-submodule.sh`, that it might make it into Git, I will probably go with the fork approach in this case.

----

In practice I hardly ever use `git submodule` or a Magit wrapper. I do add new modules using `git submodule add`, but that pretty much is it.  My main complain about `git submodule` is that it does a poor job when first setting up the submodules. After that I don't care much, because I think that the general-purpose Git/Magit commands get the job done just fine. So for day to day work with submodules I mostly use just those. While I find `git submodule` lacking I think the Git developers have done a good job making everything else submodule aware.

I recommend you start by activating all the optional submodule-related features available in Magit:

```lisp
  (magit-add-section-hook 'magit-status-sections-hook
                          'magit-insert-modules-unpulled-from-upstream
                          'magit-insert-unpulled-from-upstream)
  (magit-add-section-hook 'magit-status-sections-hook
                          'magit-insert-modules-unpulled-from-pushremote
                          'magit-insert-unpulled-from-upstream)
  (magit-add-section-hook 'magit-status-sections-hook
                          'magit-insert-modules-unpushed-to-upstream
                          'magit-insert-unpulled-from-upstream)
  (magit-add-section-hook 'magit-status-sections-hook
                          'magit-insert-modules-unpushed-to-pushremote
                          'magit-insert-unpulled-from-upstream)
  (magit-add-section-hook 'magit-status-sections-hook
                          'magit-insert-submodules
                          'magit-insert-unpulled-from-upstream)
```

My submodule-related workflow in `~/.emacs.d` is as follows:

First I use <kbd>f m</kbd> to fetch all modules. That's very similar to `git submodule fetch`, but after failing to fetch one module it continues with the next. This gives me a list of modules with modules with new commits in "Modules unpulled from @{upstream}". Each module subsection can be expanded to show the added commits. But usually I visit the submodule status buffer directly using <kbd>RET</kbd>. Then I pull in the submodule and go back to the super-repository status using <kbd>q</kbd>. For performance reasons that buffer was not refreshed, so I do that explicitly now. The module now appears under "Unstaged changes" and I stage it.

That might sound a bit cumbersome, but once you've got the hang of it, it works really well.  Of course this could be further improved and I welcome suggestions.

**Comment by tarsius** [comment]
> The git command for this is `git submodule update --remote` (which I have to lookup pretty much every time).

Magit should probably provide a wrapper for that and it should have a binding when point is on "Modules unpulled from @{upstream}". There should also be a variant for updating a single module. If this causes `HEAD` to be detached, then we should implement our own command instead of wrapping `update --remote`.

> Although my feeling is that the actions [in the popup] should be renamed/reorganized

Well I never use that popup, so I wouldn't know ;) We probably should.

But maybe more importantly we should also teach various do-something-to-the-thing-at-point about submodules.

> It's a bit annoying that `k` (`magit-discard`) does nothing on submodule sections.

What should it do? This is actually one command I currently think should not be taught about submodules. Resetting to the recorded commit seems reasonable but it's also dangerous because you could end up losing commits. In any case I would not want this command to result in a detached `HEAD`.


> Actually, it looks like magit doesn't even distinguish submodule section as a separate type

I am not sure this is needed beyond what we already have. If we start using a separate type, then many existing commands might have to be adjusted, so we should make sure we really need this before we do.

> (even in case of `diff.submodule = log` (this is way too obscure by the way)). 

I am okay with adding an Elisp option, but the default should be "according to `diff.submodule`.

> We could do that by checking for the special file mode `160000`, according to https://git-scm.com/book/en/v2/Git-Tools-Submodules. 

"That" being "determine whether we should use the `submodule` type"? Yes, but as I said, let's first make sure we have to do that.

> But maybe it's better to pass `--ignore-submodules` to `git diff` and just rely on `magit-insert-submodules` instead?

In the workflow I described above that would make it harder to stage a submodule. That workflow separates the steps "checkout the desired commit" and "record the checked out commit in the super-repository". I like that approach and suggest you try it for a while.

> The submodules that I work with don't have tags, so `magit-insert-submodules` doesn't give very useful info (just a list of directory names). What about using `git submodule status` output for this?

Seems you were not aware of those other submodule sections I mentioned above :-)

**Comment by npostavs** [comment]
I've been working with detached HEAD in my submodules, I hardly ever contribute to the upstream so losing commits isn't a concern. I have a separate clone of the upstream for when I do want to contribute. (The submodule wasn't part of the superproject from the beginning; several times I went back and forth over the commit where it was introduced, deleteting and recreating the submodule. So keeping permanent work in there makes me feel uncomfortable.)

> Seems you were not aware of those other submodule sections I mentioned above :-)

I wasn't, but when using detached HEAD submodules the `magit-insert-modules-un{push,pull}ed-*` functions do nothing.

>> It's a bit annoying that `k` (`magit-discard`) does nothing on submodule sections.
>
> What should it do? This is actually one command I currently think should not be taught about submodules. Resetting to the recorded commit seems reasonable but it's also dangerous because you could end up losing commits. In any case I would not want this command to result in a detached HEAD.

Yeah, I was thinking `git submodule update`, which does result in detached HEAD (unless you've configured `submodule.$name.update`). It's also accessible from the popup...

>> But maybe it's better to pass --ignore-submodules to git diff and just rely on magit-insert-submodules instead?
> 
> In the workflow I described above that would make it harder to stage a submodule.

Actually, I realize now it would make it harder to stage a submodule in my workflow too.

**Comment by npostavs** [comment]
Noting some additional problems:
- interactive form of `magit-submodule-add` is broken (requires `path` is an existing directory, but git requires the directory not exist). Also, should probably ask for the URL first, and use it for default value of path.
- `k` on a *staged* submodule attempts `delete-file` on the directory resulting in a `file-error` ("is a directory").

**Comment by tarsius** [comment]
> interactive form of `magit-submodule-add` is broken (requires `path` is an existing directory, but git requires the directory not exist). Also, should probably ask for the URL first, and use it for default value of path.

That should be fixed now.

**Comment by tarsius** [comment]
@npostavs Does #2674 address all you have brought up here?

**Comment by npostavs** [comment]
Everything except 

> `k` on a *staged* submodule attempts `delete-file` on the directory resulting in a `file-error` ("is a directory").

But it something else seems to have changed (git?), because trying it now it unstages the submodule changes, with a warning in the `*magit-process` buffer:`warning: unable to rmdir snippets: Directory not empty`.

**Comment by tarsius** [comment]
I've added a note to #2674.
