### ISSUE TITLE
Support manually editing Git commands generated by popups

### ISSUE THREAD

**Issue by ntc2** [magit/magit#2700]
Feature request: I would like to manually edit the Git command run by a Magit popup.

For example, in `magit-log-popup`, I want to add `--date default` to the git log command that Magit is going to run. The `--date` option is not one of the options supported by the log popup. Similarly, I would sometimes like to add `--pickaxe-regex`. Using `magit-define-popup-option` is too heavyweight here, for cases like `--date` that I would rarely want to add.

Related SO question: http://emacs.stackexchange.com/questions/23966/magit-edit-git-command-before-running-it?noredirect=1#comment36710_23966

**Comment by tarsius** [comment]
I likely won't be adding this feature to the current implementation in `magit-popup.el` but I will consider adding it to the planned successor `transient`.

**Comment by ntc2** [comment]
Great, thanks!

**Comment by tarsius** [comment]
`transient` is coming along well. It hasn't progressed beyond the "pre-alpha" state yet, but that's mostly because I still amend to the initial commit and because some features from `magit-popup` are still missing. But I have already redefined all of Magit popups as "transient" commands and am using that feature branch daily.

I am currently looking at the various issues again where I responded "I won't add that to `magit-popup` but maybe to its successor `transient`" to determine whether I actually should do that.

In this case I have decided that I won't do it for the following reasons:

1. It is not necessary to accomplish what you want to accomplish. It is already possible to add new arguments to existing popups using a different mechanism.

   See https://github.com/magit/magit/wiki/Additional-proposed-infix-arguments-and-suffix-commands for how this is currently done. As a side-note, that's one of the features that is still missing from `transient`, but by the time Magit starts using it it will be implemented there too.

2. This would best be implemented in the commands invoked *from* popups not "in the popup". For example:

   ```lisp
   (interactive
    (let ((args (magit-SOMETHING-arguments)))
      (if current-prefix-arg
          (list (somehow-split-again
                 (read-string "Edit command: "
                              (mapconcat #'shell-quote-argument args " "))))
        (list args))))
   ```

3. I do not intend to do that for any of Magit's own commands. `magit-foo` does not necessarily support all of `git foo`'s arguments. Often the output is parsed and when a new argument is added, then that might require changes to the parser.
