### ISSUE TITLE
Actions on multiple refs

### ISSUE THREAD

**Issue by baby-gnu** [magit/magit#2726]
Hello,

I would like to be able to act on several refs at the same time, for example deleting branches locally and remotely.

Today I need to move to each reference and hit `k` and confirm the branch name.

It's quite fast locally but when I want to delete several remote branches it can take time.

Is it possible to have a mechanism to mark several refs and then apply an action on them, with a single confirmation with all the refs names?

Regards.

Magit 20160724.858, Git 2.8.1, Emacs 24.5.1, gnu/linux

**Comment by npostavs** [comment]
You can mark several refs with the region, but they must be consecutive. So hit `y` to switch to `*magit-refs` buffer.

I think there was a similar request some time ago, though I can't find it right now. At the time, @tarsius didn't want to implement fully general (i.e., non-consecutive) marking because it might interfere with planned refactoring (I think?)

**Comment by kyleam** [comment]
> I think there was a similar request some time ago, though I can't find it right now. 

#2384?

**Comment by npostavs** [comment]
>> I think there was a similar request some time ago, though I can't find it right now.
> 
> #2384?

Yup, that's the one, thanks.

**Comment by tarsius** [comment]
It's highly unlikely that I will implement this feature anytime soon, but I will consider it for `v3.1`. I am closing this issue like #2384.

> So I have added "Maybe implement 'section marking'" to the Roadmap for v3.1, and am closing this issue (which doesn't mean you cannot keep discussing this here.
