### ISSUE TITLE
Documentation for `magit-inhibit-save-previous-wconf`

### ISSUE THREAD

**Issue by FrancisMurillo** [magit/magit#2737]
So I came across the variable `magit-inhibit-save-previous-wconf` which let's the window configuration alone when using `magit-status`. I was wondering why this isn't a `defcustom` instead of `defvar`? If this is a configurable variable, is it possible to ask some documentation?

**Comment by tarsius** [comment]
The variable is named `...-winconf`.

> I was wondering why this isn't a `defcustom` instead of `defvar`

Because it is for internal use. Functions containing `-inhibit-` tend to be.

> some documentation?

Remove `magit-save-window-configuration` from `magit-pre-display-buffer-hook` to not save the value and change the value of `magit-bury-buffer-function` to prevent the saved value, if any` from being used. Doing the former is not really necessary, the latter is documented [here](https://magit.vc/manual/magit/Quitting-Windows.html).

**Comment by FrancisMurillo** [comment]
My understanding of private variables are ones with a `--` after the module prefix as in `magit--`. Thanks for the prompt reply.

**Comment by tarsius** [comment]
Yeah, that's usually the case, but in Magit many symbols would have to renamed, so that should be done at a safe time (before a major release).

Also this particular variable might actually not be internal, but "not for end-users", i.e. it might make sense for an extension to use it.
