### ISSUE TITLE
Reduce minibuffer-based prompting

### ISSUE THREAD

**Issue by yurikhan** [magit/magit#2741]
In many places, Magit asks for several arguments in sequence via the minibuffer. Example: <kbd>b c</kbd> `magit-branch`, <kbd>b B</kbd> `magit-branch-and-checkout`, <kbd>b b</kbd> `magit-checkout`, <kbd>t t</kbd> `magit-tag` all ask for a commit to base the new branch on or to put the new tag on.

I find that I only ever invoke these commands from the log buffer, with cursor placed on the commit I want to branch from or tag. Magit suggests that commit by default but still requires me to press <kbd>RET</kbd>. I routinely forget and start typing the name for the new branch, only to be greeted by the “and now here’s the prompt that the thing you last typed should go in”.

I would like a more “point-and-shoot” experience. My mind perceives <kbd>b b</kbd> as “check out *this*”, <kbd>b c</kbd> as “create a new branch *here*”, <kbd>b B</kbd> as “start a new branch from *here*”, and <kbd>t t</kbd> as “tag *this commit*”, no questions asked. (Obviously, a prompt for the name of the new branch or tag is OK and expected.) I still want my muscle memory to know them as <kbd>b b</kbd>, <kbd>b c</kbd> and <kbd>b B</kbd>, though, not as <kbd>b b RET</kbd>, <kbd>b c RET</kbd> and <kbd>b B RET</kbd>.

Similarly, I’d like <kbd>b r</kbd> to rename the branch the point is currently on, or if there is no such branch, the branch that is currently checked out, only prompting for the new name.

**Comment by Fuco1** [comment]
This used to be a huge issue for me as well, I kind of got used to it by now but still curse ocassionaly :)  Even worse, 99.9% of the time I want to branch from master, not even the commit under point (I too basically live in the log buffer).  Some quicker options would sure come handy

**Comment by yurikhan** [comment]
For me, getting used to it would equate to learning a bad habit, comparable to following each file deletion command with a confirming <kbd>Enter</kbd>. I’d like to avoid that if possible.

In case of dangerous commands, an argument could be made that multiple prompts are a speedbump that forces you to slow down and think carefully. For branching, no such speedbump is necessary.

**Comment by tarsius** [comment]
> only to be greeted by the “and now here’s the prompt that the thing you last typed should go in”.

The order in which these branches are read can be changed using `magit-branch-read-upstream-first`. At least `b c RET feature RET` then becomes `b c feature RET RET`.

Personally I prefer to read the starting-point first, because then the name of the new branch can be based on that (e.g. when branching "origin/some-feature", then the second prompt would default to "some-feature").

But not everyone agreed, and so I created an option to change the order.

> I would like a more “point-and-shoot” experience.

I am considering doing something similar here, but this is going to take a while because giving users this choice is more complex than it might seem.

The current implementation is flexible, safe, consistent, but slightly inefficient in some cases. What you are proposing is much less flexible (if there is something relevant at point, then you do have to move away first), less safe for inexperienced users (to whom e.g. something as harmless as renaming the wrong branch could be very confusing), not consistent at all ("unsafe" commands would still require confirmation, which commands are "unsafe" and which are "safe"?), but more efficient in what - for you - is the most common work flow.

These are the trade-offs, and why I am certain I will at least keep the current behavior as the default. Implementing what you are asking for *as an option* will require changes all over the place, and I am taking it easy the next month at least, so this will take a while.

**Comment by npostavs** [comment]
> Even worse, 99.9% of the time I want to branch from master, not even the commit under point (I too basically live in the log buffer)

`b s` (`magit-branch-spinoff`) might make more sense for this use case (it works also if there are 0 unpushed commits).

**Comment by kyleam** [comment]
> I would like a more “point-and-shoot” experience.

For context, I thought I could point to several previous issues
because I'm pretty sure I've seen this discussed a few times, but my
searches didn't turn up much.  I did find a [comment] that describes
the motivation behind the current behavior.

[comment]: https://github.com/magit/magit/issues/1858#issuecomment-104791472

**Comment by yurikhan** [comment]
> Personally I prefer to read the starting-point first, because then the name of the new branch can be based on that (e.g. when branching `origin/some-feature`, then the second prompt would default to `some-feature`).

This is a valid explanation for reading the starting point before the new branch name vs. after, but not for *reading* the starting point at all.

The remote branch or local branch or commit under point is already the top default value for the starting point, I just want to use it silently without confirmation.

In fact, I can do just that:

```elisp
(defun yk-magit-read-starting-point (prompt)
  (or (let ((r (magit-remote-branch-at-point))
            (l (magit-local-branch-at-point)))
        (if magit-prefer-remote-upstream (or r l) (or l r)))
      (magit-commit-at-point)
      (magit-stash-at-point)
      (magit-get-current-branch)
      (user-error "Nothing selected")))
(advice-add 'magit-read-starting-point :override 'yk-magit-read-starting-point)
```

Thanks everyone.

**Comment by tarsius** [comment]
> This is a valid explanation for reading the starting point before the new branch name vs. after, but not for *reading* the starting point at all.

I did not try to imply otherwise. Preceding that I said "to make the current behavior less painful, you might consider [ab]using this option", and fallowing up on it "[this is an example of] my adding an option due to popular demand even though I think the default is better".

> In fact, I can do just that:

Yes, implementing support for a particular preference/work-flow isn't hard. So please use that for the time being.

As I said before, I will probably add some option/mechanism to make this customizable, but doing it right is more complex than it might seem, and I don't have the time to work on that right now.

**Comment by phil-s** [comment]
I sometimes still make this mistake with `b c` and something occurs to me:

If the value I enter at the first prompt *isn't a valid ref*, then Magit could DWIM and (with a prompt to confirm) create a new branch of that name, starting at whatever the default value had been.

**Comment by tarsius** [comment]
> If the value I enter at the first prompt isn't a valid ref, then Magit could DWIM

A revision hash is also valid. Or a fully qualified ref, or some other ways of referring to some revision or reference. But we could check if it is any of those by asking `git rev-parse` and if that fails, *then* we could do what you are suggesting.

**Comment by phil-s** [comment]
Precisely what I was trying to suggest :)

**Comment by tarsius** [comment]
If implemented all the requested features. You'll have to customize `magit-branch-read-upstream-first` and the new `magit-no-confirm-default`.

**Comment by phil-s** [comment]
The new `fallback` option for `magit-branch-read-upstream-first` is perfect. Cheers!
