### ISSUE TITLE
undo-tree like interface to navigate in git history

### ISSUE THREAD

**Issue by bricewge** [magit/magit#2750]
This feature request is a following up of [this](http://emacs.stackexchange.com/questions/17270/combining-magit-with-undo-tree-for-easy-history-navigation) question on StackExchange.

It would be great to have a view similar to `undo-tree` in magit to navigate quickly in git history. The options discussed on StackOverflow are nice but the usability is still lacking.
Is it possible to "polish the edges" of this feature?

**Comment by tarsius** [comment]
> Is it possible to "polish the edges" of this feature?

Yes, but it requires more than just polishing edges.

I don't know which "part of the feature" in particular you would like to see improved, but there are quite a few things that are more or less related to this that I want to improve. I'll try to write down an overview at a later time because I intend "this" to be one of the new killer features in version tree.

But I'm afraid, until I actually start on v3, I don't intend to make any incremental changes in this area.

**Comment by tarsius** [comment]
Closing in favor of #2989.
