### ISSUE TITLE
Prompts should allow the use of yes-or-no-p

### ISSUE THREAD

**Issue by dnedde** [magit/magit#2752]
Many of the operations magit performs are destructive and not un-doable, such as discard stash or "discard unstaged changes".  These are often prompted with y-or-n-p.

This does not match with built-in emacs functions, that will prompt you with yes-or-no-p for destructive actions.

Can destructive, non-recoverable changes be changed to yes-or-no-p or at least make it an option to select this level or confirmation?

**Comment by tarsius** [comment]
I have add a new option `magit-slow-confirm` on branch [`jb/slow-confirm`](https://github.com/magit/magit/compare/jb/slow-confirm?expand=1).

I am currently not adding any new features, so you will have to use that branch or [`pu`](https://github.com/magit/magit/compare/pu?expand=1).

**Comment by tarsius** [comment]
I've decided to drop this because (1) I don't want to default to "yes or no", and (2) the option then becomes kind of pointless because I don't expect anyone to think "this is kinda dangerous, lets check if Magit has an option to use `yes-or-no-p` instead. So essentially this would be an option just for you.

These actions also aren't as destructive as you think. It is for example possible to recover a stash using `git update-ref refs/stash HASH` (the hash is printed to both *Messages* and the process buffer). I also recommend you read https://magit.vc/manual/magit/Safety.html.

**Comment by tarsius** [comment]
I changed my mind and added the option.

**Comment by CyberShadow** [comment]
Hi @tarsius,

I think it doesn't make sense to use one of either `y-or-no-p` or `yes-or-no-p` for all questions.

A lot of the things you can do with magit are easily recoverable, but some are not. For example, dropping ALL stashes should **definitely** be an action confirmed by `yes-or-no-p`. This action is not easily recoverable, and e.g. I use the stash as a recycle bin for incomplete ideas and debugging code that I will likely need again in the future (for some projects I have over a hundred items in there). It's also easy to "miss" by positioning the cursor on the wrong line when the intention was to unstage everything.

IMHO, magit should just continue using `y-or-no-p` for actions that are trivially undoable or easy to redo by hand, and `yes-or-no-p` for actions that are not undoable with git commands.

And thank you for your work on magit!

**Comment by tarsius** [comment]
`magit-slow-confirm` can now also be a list and by default `drop-stashes` is its only member.

**Comment by CyberShadow** [comment]
Awesome, thank you!!
