### ISSUE TITLE
Cannot clone large repos

### ISSUE THREAD

**Issue by mrkkrp** [magit/magit#2753]
I can't clone `https://github.com/twbs/bootstrap` anymore. Previously it worked, now it sort-of hangs and then says:

```
Running git clone https://github.com/twbs/bootstrap.git /home/mark/projects/programs/svod/bootstrap/
error in process sentinel: magit-process-finish: Git error: "index-pack failed (in ~/projects/programs/svod/)"
error in process sentinel: Git error: "index-pack failed (in ~/projects/programs/svod/)"
```

**Comment by Silex** [comment]
Does `git clone https://github.com/twbs/bootstrap.git` work on the command line?

**Comment by mrkkrp** [comment]
Yes, that's how I cloned it after all.

**Comment by npostavs** [comment]
Does it always fail from Emacs? What are OS and git versions?

**Comment by mrkkrp** [comment]
Git 2.9.3, Arch Linux (recently upgraded).

**Comment by npostavs** [comment]
Does it always fail from Emacs?

**Comment by mrkkrp** [comment]
With this repo? It works with smaller ones.

**Comment by mrkkrp** [comment]
@npostavs Can't you reproduce it yourself?

**Comment by npostavs** [comment]
> With this repo? It works with smaller ones.

Then does it always fail with bigger ones?

> Can't you reproduce it yourself?

I'm waiting to see if you can reproduce it before spending time on it myself.

**Comment by johnmastro** [comment]
I'm unable to reproduce it on Windows 10 with `git` 2.8.3 from Cygwin.

My `magit-version` is:

    Magit 20160820.627, Git 2.8.3, Emacs 25.0.94.2, windows-nt

**Comment by mrkkrp** [comment]
Of course I checked several times before reporting this!

**Comment by npostavs** [comment]
> Of course I checked several times before reporting this!

That's great, but it was not at all obvious from what you *wrote*. For next time, please include info on troubleshooting you already performed in your initial report so we don't have to play [20 questions](https://en.wikipedia.org/wiki/Twenty_Questions), thanks.

**Comment by mrkkrp** [comment]
If you don't believe I do my checking before reporting, I'll just use `git clone` from command line, for the next time.

**Comment by npostavs** [comment]
> If you don't believe I do my checking before reporting, I'll just use git clone from command line, for the next time.

I believe you, now that you've told me. Just please be more generous with your information in bug reports.

**Comment by tarsius** [comment]
> index-pack failed

This part of the error message comes from git.

The full error which you can see in the process buffer (which you can show by pressing <kbd>$</kbd>) probably reads something like this:

```
remote: Counting objects: 6503, done.
remote: Compressing objects: 100% (4519/4519), done.
Connection to github.com closed by remote host.| 350 KiB/s
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
```

`git index-pack` is a git plumbing command which is used, among other places, when cloning a repository. It is highly unlikely that something in the way Magit calls `git clone` or in how Emacs implements handling of child processes is the cause of an error occurring here.

It is much more likely that a network issue or an overloaded server is causing this error. Another possible cause is data corruption, but since you were later able to clone, I think it is more likely a capacity issue.

The fact that you couldn't clone with Magit, even though you tried multiple times, and then later were able to clone on the command line, is most likely a coincidence. It probably is no coincidence that it happened with a large and popular repository - the size and popularity makes it more likely that the capacities of server or the network are exceeded.

**Comment by npostavs** [comment]
@mrkkrp

> Git 2.9.3, Arch Linux (recently upgraded).

For the record, `magit-clone` succeeded here, also Git 2.9.3, also Arch Linux.

---

Also for the record, I'm sorry I reacted passive-aggressively to your bug report, that was unconstructive. I shall try to be less of an ass in the future.

---
---

> The full error which you can see in the process buffer (which you can show by pressing <kbd>$</kbd>)

<kbd>$</kbd> only works if you ran `magit-clone` from an existing magit buffer, otherwise it ends in up in a buffer named `*magit-process:` that you have to switch to manually.
