### ISSUE TITLE
Possible typo

### ISSUE THREAD

**Issue by elibarzilay** [magit/magit#2759]
This line:

  https://github.com/magit/magit/blob/1b7e0605e401df1be0215b8a5a16ac94e2aca9a7/lisp/magit-mode.el#L291

seems to be likely typo that should have been "S-tab".

**Comment by tarsius** [comment]
Possibly, but I am not sure. Maybe someone else remembers something.

<kbd>s-tab</kbd> is `Super+Tab`, so it is possible that this is intentional we use that to avoid overwriting some default binding for <kbd>S-tab</kbd> and <kbd>backtab</kbd> (which is translated to the former). But I just checked `emacs -Q` and there does not appear such a binding.

Most likely I will additionally bind <kbd>S-tab</kbd> and keep the <kbd>s-tab</kbd> binding just in case someone uses that. But lets wait a bit and see if someone else knows more.

**Comment by npostavs** [comment]
It's quite uncommon for packages to bind Super+ keys by default. Checking blame output shows <kbd>s-tab</kbd> was added by 7fbfa691046a00aacd03091e6ed4ebb435c43041, and then #2411 adds <kbd>backtab</kbd>, where it seems like @mosic thought perhaps <kbd>s-tab</kbd> corresponded to <kbd>Shift+tab</kbd> on *some* other platforms (hence why he didn't suggest completely replacing the existing <kbd>s-tab</kbd> binding).

I  think <kbd>s-tab</kbd> is just a typo for <kbd>S-tab</kbd>.

**Comment by elibarzilay** [comment]
Yes, I thought it was a typo because of how rare it is to grab s- keys too, especially `s-tab` which is most likely bound to some WM thing.

**Comment by tarsius** [comment]
I've now bound <kbd>S-tab</kbd> to this command too. I'am keeping the old bindings in case someone uses those and because I have promised to not "needlessly mess with key bindings" again.

@elibarzilay Thanks for bringing this to our attention.

**Comment by elibarzilay** [comment]
Thanks!
