### ISSUE TITLE
Support multiple indexes

### ISSUE THREAD

**Issue by spacefrogg** [magit/magit#2760]
Git tools since long support the use of alternate staging areas via the `GIT_INDEX_FILE` environment variable. This is rather inconvenient to use from the shell, but I frequently come across the need for an interface to an alternate index. The mechanics are simple, use multiple indexes to form different commits from different parts of your worktree. So this can be regarded as a feature request.

The benefits I see here:
- Easily insert a commit (like a fix) before your main commit while already in the process of staging the main commit by using an alternate index.
- Shift hunks from one index to another/add hunks to different indexes depending on their meaning

Drawbacks I see here:
- `git status` et al. does only a have a view on a single index not the combination of all indexes. You cannot easily see what is staged in the other indexes from command line. This should not be a problem to magit as it would be aware of all active indexes and could generate a complete picture. Although, this looks like generating the most work.

**Comment by tarsius** [comment]
This is something I might consider for v3. It's an interesting idea but I also expect that this would be a lot of work and would only benefit very few users. I am afraid this request will be on hold for a long time.

Note that Magit already supports "alternative indices" by supporting the new worktree feature. But that's not what you are asking for, as I understand it you want multiple indices in *one* worktree.

Regarding the benefits you mentioned:

> Easily insert a commit (like a fix) before your main commit while already in the process of staging the main commit by using an alternate index.

You could stash just the index using <kbd>z i</kbd>, stage and commit the fix, and then pop the stash to resume work on the main thing you were working on.

> Shift hunks from one index to another/add hunks to different indexes depending on their meaning

That's more a feature request than a benefit. Why do you want to shift hunks from one index to another.

**Comment by spacefrogg** [comment]
> I am afraid this request will be on hold for a long time.

I believed so, but I didn't want to let the idea go unheard.

> Note that Magit already supports "alternative indices" by supporting the new worktree feature. But that's not what you are asking for, as I understand it, you want multiple indices in _one_ worktree.

You understand correctly.

> You could stash just the index using <kbd>z i</kbd>, stage and commit the fix, and then pop the stash to resume work on the main thing you were working on.

This is my current way out of this situation and almost as good for fixup commits that have to slip in before the main commit.

> Why do you want to shift hunks from one index to another.

Because this is the very idea of splitting a commit in two. Consider I started staging the first commit and then find out there are hunks that belong to a second commit. There is no easy way right now to remember that code and continue staging the first commit. I could:
 1. Unstage the hunks for the second commit, 
 - Stash the first index
 - Stage the hunks for the second commit again, 
 - Stash the second index,
 - Pop the first index and continue.

I have to repeat this sequence whenever I find code for either staging area. Or I could just stage hunks and move them between staging areas individually. (If, I could do that)

**Comment by tarsius** [comment]
> There is no easy way right now to remember that code and continue staging the first commit.

One could argue that the thing you have to remember is more complex than "create a separate commit for that typo fix" that you have made to many changes without creating commits :-) But I see what you are getting at and agree that it could sometimes useful to prepare multiple commits at once. Just don't tell anybody who still things the index is a useless concept anyway, or they will think you have gone completely insane ;-)

Anyway, hacking together a proof-of-concept shouldn't be to hard (but still quite a bit of work). But I don't have the time for that now, especially because the logical next step would be a solid and documented version, which also deals with edge cases such as conflicts between the indices.

This might be a good opportunity for you to get your hands dirty though. You basically have to do four things.

1. Somehow record the additional indices in existence.
2. Teach `magit-stage` and `magit-unstage`, and/or the functions used to implement them to respect a numeric prefix argument to mean operate on index N.
3. Create a variant of `magit-insert-staged-changes` which show the additional indices.
4. Create a variant of `magit-commit` which commits from an additional index.

**Comment by tarsius** [comment]
See `magit-wip-commit-index` and `magit-wip-update-wipref` as a source of inspiration; they use a temporary index.

**Comment by tarsius** [comment]
I don't think I will ever implement this. I have marked this as something to look at again at a later time, but I am closing this to avoid getting anyone's hope up.

**Comment by stianhoiland** [comment]
Too bad this is no longer being considered. It's beyond me why this is not baked into git; for me it's such a natural way to work. [Relevant SO question.](http://stackoverflow.com/questions/28947201/multiple-staging-areas)

**Comment by tarsius** [comment]
*So this isn't as well structured as it should be, but I spend some time writing it. I am posting it in the hope that it will help others see why this isn't as trivial as it might seem.*

> It's beyond me why this is not baked into git; for me it's such a natural way to work.

If you go beyond a proof-of-concept it gets really complex really fast and that's not just on the implementation side, the user has to be exposed to it.

(Also this is not actually true. Git does provide this feature. This is how you use it: `GIT_INDEX=/path/to/index git add ...`, but that is beside the point. *Magit* does not support this though, and yes, git's support is pretty low-level.)

For starters, if you have multiple indices then those can conflict. Once you want to commit the indices, those conflicts have to be resolved. So you will have to think of the two indices as "light-weight branches". The problem with that is that all the additional information that is associated with a branch is missing from the index. That can be worked around by creating commits and then merging those and then converting the merge commit into a non-merge commit. And the problem with that is that users will have difficulties understanding why a merge is being performed and ...

Hm, cherry-picking instead of merging might work better, but in any case this is quite difficult to get right, so it is not beyond *me* why this isn't backed into git.

But what makes this really hard is that you cannot only get conflicts when applying indices. You can actually get conflicts when *staging*. I have no idea how I would deal with that.

Consider this case: In some special-case you have just discovered you want to show a more suitable message. You then discover that the current message, which, until now, is always shown contains a typo. You fix the typo and stage it to the `typo fixes`-index. Then you add the specialized message. As a result the line with the common message now gets re-intended (it's now the ELSE of an `if`). Now you stage that change to the `changes I actually intended to make`-index.

And after that you can do whatever you want. You can commit one of the indices first and then the other, or the other way around. Or you commit one of them on one branch and the other on another branch. And git/magit somehow has to figure out how to deal with the conflicts and because they can't they have to ask you. But that will involve commits you did not actually create, so that might confuse you in turn.

I think the "change set" feature gives the illusion that it is possible to work on unrelated things at the same time on the same branch without those unrelated things conflicting. But often they do, especially when you want to have two change sets such as `various fixes to the old implementation` and `replace the old implementation with a better one`. Such change sets not only tend to involve the same files they usually even concern the exact same lines in those files.

> for me it's such a natural way to work.

I also tend to do things at the same time that will have to go into different commits. The way I deal with that is that I create temporary commits which will later get rearranged. So at one point I might have this history:

```
* [feature] fix another old typo
* finish the feature
* cosmetic changes to existing implementation
* the new feature now kinda works
* [master] unrelated change
```

Assume that `fix another old typo` touches lines also modified by `the new feature now kinda works`, but I did not necessarily notice (or rather just ignored) that when I committed the fix.)

What I finally want is

```
* [feature] a new feature
* cosmetic changes
* [master] fix typo
* unrelated change
```

Magit provides lots of features to make this kind of transformation fairly painless. (And I keep adding new ones. E.g. the recently added `magit-cherry-{harvest,absort,spinout,spinoff}` commands. But just interactive rebase, cherry-picking, and "rebase onto upstream" works pretty well too.) Git provides the necessary functionality too, but on the command line its quite cumbersome to do this sort of thing.

The benefit of the `commit, then rearrange` approach is that it is quite easy to understand why you get conflicts when rearranging changes and that makes it easier to determine how to resolve such a conflict.

If you use multiple indices then this is the situation before staging `fix another old typo`.

```
* [worktree] fix another old typo
|\
* | [fixes index] cosmetic changes to existing implementation
| * [feature index] the new feature now kinda works && finish the feature
|/
* [master] unrelated change
```

The problem is that this "commit graph" are a lie. The implied relationships at best exists in the user's head, but in cases like the one I am discussing here where I did not notice that "fix another old typo" touches I line also modified by "the new feature now kinda works" not even that is the case.

So what happens when you try to stage `fix another old typo` to `[fixes index]` is that you get a conflict -- while staging !!! --- because the changes from `the new feature now kinda works` are not actually in that index. That's gonna confuse the hell out of users.

**Comment by tarsius** [comment]
That being said, it certainly would be something overcoming these issues. I might try one day, I just don't know if that would lead anywhere. But I know it would be a lot of work and because there are other things that I *know* will lead somewhere, I will tackle those first.

**Comment by stianhoiland** [comment]
Hey Jonas. Wonderful reply. I didn't see your response until just now, when once again I went scouring the Internet for a solution for this. I tried to understand your reply as best I could, and while I don't understand how git does its work as well as you do, I know that this needs a solution and that I'm willing to accept an imperfect solution.

The basic functionality seems easy enough and just like you said: Provide some interface to easily add changes in the work tree to an arbitrary index, i.e. create the index file if it doesn't exit, and prefix the adding of those changes with that index file: `GIT_INDEX=/path/to/index git add ...`.
There should also be facility for swapping any arbitrary index file with the default index file `$GIT_DIR/.index`, to let git see whichever of the indexes (word!) one wants.

The main issue seems to be inter-index conflicts. And this is what I meant when I said that I would accept an imperfect solution. Just forget about conflict resolution. Leave it up to me to carefully craft the index files, perilous as it is.

With that basic functionality in place, maybe clever or even just sufficient solutions for handling those conflicts could emerge. Or even if it didn't, at least that basic functionality would be there to be used with the disclaimer that it does not handle inter-index conflicts, and I would be one happy git'er.

As for more advanced features:

Going through the work tree and shuttling changes to the index file of your choice should be available both as an interactive workflow that takes hunk-by-hunk and asks where you want to put, i.e. which index file it should be added to (and this appears to me like a wet dream right now...), as well as just an overview of the work tree and facility for assigning any change to any index file. This could maybe be considered part of the basic functionality.

Going one step further, the possibility of shifting hunks from one index file to another, which may be implemented as unstaging the change, thereby "returning it" to the work tree, and then immediately staging the change to the index file it was moved to.
While there is indeed even in the basis functionality always the chance of creating conflicts, it may be that this feature is more likely to create conflicts. Or maybe that's just my imagination.

The more I think of it, the less I think this functionality should handle conflicts. The only caveat to all of this that I can think of is that it may turn out as you have speculated that these conflicts are actually so frequent that there is no practical way to support this kind of workflow. And you know I can't accept that on faith :)

**Comment by stianhoiland** [comment]
Okay, hang on. I thought of something. Let me know what you think:

I was thinking about how it would be true, as you say, that conflicts would easily arise. I think *maybe* there's been something gone missing in translation here, possibly because you don't have this same kind of workflow yourself.

All right. So you have a work tree with a whole bunch of changes belonging to separate logical chunks you want to create commits for. Now, if you just keep these changes and shuttle them back and forth between index files, how can that create conflicts? As it is, the work tree is already in a non-conflicted state, and you would only be shuttling those non-conflicting changes between index files.

Okay, so what is this whole conflict thing then?

I think what you have imagined is that, as changes are assigned to index files, one also continues to make *new changes* to the work tree, and that this quickly becomes a hairy mess.

So, on one hand I want to just say, "this isn't how it is", since this workflow goes like this: One does a whole lotta changes, and then switches to "commit mode", where no new changes are made to the files and instead one now focuses on committing the changes. How can conflicts be created? They can't.

But on the other hand, if someone does have this workflow of also creating little or big changes while having various index files floating around... then well, there are two options for a usability perspective: 1) Either require that access to the multi-index features completely disallow any new changes by locking the work tree, or 2) simply leave it up to the user to either a) don't make any changes while slicing the work into index files to commit, or b) make sure that any change they make to the files don't cause any conflicts.

**Comment by stianhoiland** [comment]
As for names for this thing... whereas "git multi index" describes the implementation, another term for it that describes the use case could be "git triage".

**Comment by stianhoiland** [comment]
I'm not sure this is really the place for the following, and I apologize if the following is too long, too obvious, or too presumptuous, but here are some thoughts about the general suitability of this triaging of changes for git.

See, I really struggle to integrate git into my coding workflow. How it suits anyone to break their flow every few minutes to commit changes is beyond me. Creating good commits seems almost perfectly antithetical to the process of immersed coding; there's a lot of details here I'll skip for brevity.

Every time I reach my git breaking point in a project I go through the same cycle. First I desperately wish for a solution that would allow me to triage changes with multiple index files. Then I realize I'm too lazy to make that myself (though I did get some of the way once...) and instead start to think of other quick hacks I could implement to get myself out of this git hell I find myself in yet again.

And every time I come up with the same hack: Scheduled commits and autocommits. I start to think of various ways to integrate a fixed commit schedule into the tools I'm using, the most basic just being a dumb "git add -A && git commit -m Autocommit" every 10 minutes or whatever.

Now, I'm the type that likes a clean commit history, and I try to hide the sausage-making as much as I can. So autocommits just rub me the wrong way, since it's basically the opposite of logically defined commits, no matter how much additional functionality I graft onto scheduled commits.

And to overcome this grating feeling, every time I try to change the way I think about git to something like the following: At least this way I'll get a chronological representation of the work I'm doing. And ain't that great. Right? Right?...

But eventually I came to a realize a few things:

First, git is not supposed to be a chronological story of the logical features of the project. A clue is the word "commit". A commit is not an encapsulation of a feature or some such, but is instead *a commitment to a piece of code*. It means, "yeah, I want this piece of code in my project", and since we commit to it, we want to track it, hence we add it to a collection of data that we want to observe diachronically. This definition of a *commit* has no regard for the chronology of the work. You could have been making this piece of code for several weeks, piece by piece, and only now do you consider it to be in a state in which you are willing commit to it.

If a commit is "just" a commitment to a piece of code, so that commits don't really have any regard for the chronology of the work, then why are we committing so often and so close to when the change was made? And, since code that we want to commit to often evolve in a staccato manner, why is it so difficult to manage lingering, logically-grouped changes, possibly spanning several files? Of course there's branches, but this suffers the same following analysis:

It seems like the commit-often philosophy is a *workaround for a problem* and rather than *a solution to it*, and isn't really "how it should be done" but instead "how we have to do it". What is the problem and why do we have to do it this way? Git itself doesn't support a workflow on the committing side of its functionality that aligns with its own intended use.

This is why I said that it's beyond me why this is not baked into git. Few things sound as git-like as being able let code evolve *organically*, and then being able to easily define units of that code *that we want to commit to*. Why does git have to insert itself into the coding phase, requiring us to commit often to be practically useful? Why can't git be a separate work task? I mean, that's the problem: committing is a fundamentally different task than coding, so committing always *interrupts* coding, even if it's just for two or three seconds--which, if you only spend that long committing, you're unlikely to make very good commits, or at the very least you are creating more work to be done later in yet another task, i.e. cleaning up your branch.

Anyway, that was both a bit too long and not very complete, but there it is. And I think you can see the merit in being able to thoroughly separate committing as a task from coding as a task, even with my all my idiosyncrasies.

**Comment by chris3torek** [comment]
@stianhoiland I think the fundamental issue here is "changeset vs commit".

There is a way around this issue, and that is to create branches.  (The rest of this is a description and a bit of a thought experiment.)

In Git, a commit contains a complete snapshot (plus additional data), and an index is a proposed commit (without the additional data).  Therefore, each index is quite naturally a complete snapshot.

But when we _look at_ a commit, we see a changeset.  Git _computes_ the changeset on demand, when we ask _what happened in this commit_, by comparing the snapshot for the commit to the snapshot for the commit's parent.  (This breaks down a bit, or a lot, at merge commits, which have more than one parent.  But mostly we look at non-merge commits.)

In order to turn a commit into a changeset, Git _needs_ the parent.  Indexes store proposed commits minus the auxiliary data, and what's missing _includes the parent_.  You must turn the proposed commits into actual commits, which do have parents.  But the normal process of making a new commit—running `git commit`—does _too much_ because it not only creates that commit (with the current commit as its parent), it also _moves the current branch_ so that the new commit _is_ the current commit.

I believe you wish to think about multiple indexes that are taking new shapes as _changesets with respect to the current commit_.  What this means is that in Git's terms, you will have to "assign" such an index to a new, temporary branch.  You **must** do this before you make a normal commit, because a normal updates the current _branch_.  The temporary index snapshots would then have the wrong parent!  Converted to changesets, they will _undo_ something you did in the real commit.  An actual commit can be made with the right parent: commits record their parents, so the parent for each of these multiple temporary indices must be _the commit that **was** current when the index was active_.

Hence, to save the indices as commits, the underlying mechanism is something like this:

    for i in $temporary_index_set:
        new_commit = $(git commit-tree -p HEAD -m $message $(GIT_INDEX_FILE=$i git write-tree))
        new_branch_name = (something, as yet to be determined)
        git branch $new_branch_name $new_commit
 
This turns each snapshot-as-index into a permanent (well, semi-permanent) commit object that Git can turn back into a changeset.  (Note: it would be possible, and maybe even wise, to use something other than _branch names_ here, but I will use them for now for illustration at least.)

Now that the parents are properly recorded, it's possible to make a real commit using the real index:

    git commit ...

At this point, if you want to turn each of those branches made in the loop back into not-yet-committed temporary indexes, that's possible:

    for i in $branches_made_above:
        make temporary work-tree / index pair
        use temporary pair to (git cherry-pick -n $i) (and note any failures)
        - on success, move this work-tree's index to a new temporary index,
            deleting the work-tree itself and the branch name $i
        - on failure, do something else sensible

Note that this is a lot of work, and does require some sort of manual intervention if there are conflicts.

**Comment by stianhoiland** [comment]
Thanks for taking the time to explain Chris. Highly appreciated.

Lemme see if I understood:

Example: We have the current state of the repo/branch, including uncommitted changes. We create a couple index files and assign the uncommitted changes as we like to their desired index file.

So far, so good. We've separated the work and have our index files lined up ready to be committed.

Then we commit the first index file.

But now the other index files are dangling off *the previous head*, i.e, the parent of the newly created commit at head, and all the remaining index files will have to be updated with the newly created commit as their new parent (or some such)?

Is that right?

**Comment by stianhoiland** [comment]
Chris, I read your reply for the nth time and I see that you are saying much more than what I asked.

**Comment by chris3torek** [comment]
Yes, the problem is that if / when HEAD moves, if you use the index you have now to make a new commit relating to the _new_ HEAD, your new commit _removes your previous work_.

**Comment by stianhoiland** [comment]
This also doesn't need to be conceptualized as "tagging changes". It might as well be presented as multiple virtual index files. Whatever really! Though Imma put a good word in for calling it *triaging*!

**Comment by stianhoiland** [comment]
I found that JetBrains' IDEs (like IntelliJ IDEA) have a feature called [changelists](https://www.jetbrains.com/help/idea/managing-changelists.html), which is reminiscent of what we're discussing here. There is also Stacked Git ([StGit](http://www.procode.org/stgit/)).

From reading about it, I get the impression that the implementation of Stacked Git coupled with a GUI like JetBrains is the kind of thing I'd want. But! Both of these tools conceive of this workflow not as a something you do at the end of a coding session with a messy working directory containing changes for several commits, but for setting up "buckets" for code _prior_ to coding or while coding. No likey. So I can't really make these tools work for me.

I'll have a look at how Stacked Git makes its patches, and then I'll have to look into what would be a good GUI for selecting hunks and lines and assigning them to separate patches to be committed.
