### ISSUE TITLE
GPG signing functionality breaks on OS X

### ISSUE THREAD

**Issue by LukeXuan** [magit/magit#2776]
After a recent software update (both gpg and emacs), the gpg signing functionality of magit breaks, show the following error codes
```
gpg-agent[1736]: command get_passphrase failed: Inappropriate ioctl for device
gpg: problem with the agent: Inappropriate ioctl for device
gpg: skipped "xxx": Operation cancelled
gpg: signing failed: Operation cancelled
error: gpg failed to sign the data
fatal: failed to write commit object
```

with the gpg-agent version and gpg2 version,

```
$ gpg-agent --version
gpg-agent (GnuPG) 2.0.30
libgcrypt 1.7.3
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
$ gpg2 --version
gpg (GnuPG) 2.0.30
libgcrypt 1.7.3
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: ~/.gnupg
Supported algorithms:
Pubkey: RSA, RSA, RSA, ELG, DSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: MD5, SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
```

While the magit version
```
Magit 20160609.1825, Git 2.7.4 (Apple Git-66), Emacs 24.5.1, darwin
```

and emacs version (actually `emacs-plus`)
```
GNU Emacs 24.5.1 (x86_64-apple-darwin15.6.0, NS apple-appkit-1404.47) of 2016-08-01
```

Reproducing
---

Any commit trying to enable signing using GPG fails with the above message.

**Comment by tarsius** [comment]
Please try signing a commit on the command line. Do you get the same error?

**Comment by LukeXuan** [comment]
No signing a commit normally prompt `pinetry-curses` for passphrase with gpg2.
BTW, I find that magit still works with gpg1, which simply uses the command line to input the passphrase.

**Comment by tarsius** [comment]
Magit doesn't use a pty but just consumes stdout. `pinentry-curses` expects a pty. Can you tell gpg2 to use a graphical dialog to get the passphrase?

**Comment by huyuehui** [comment]
If I set the env var "INSIDE_EMACS" to be NOT nil, the passphrase can be read from Emac's minibuffer with M-x pinentry-start. Does Magit have an option to set this env var?
Sorry to be off the topic a little bit. I have a similar issue when signing git commits. The error messages look alike.
magit 2.8.0, gpg 2.1.15, emacs 25.1

**Comment by tarsius** [comment]
> If I set the env var "INSIDE_EMACS" to be NOT nil, the passphrase can be read from Emac's minibuffer 

Sounds like an old feature has turned into a bug. At some point gpg learned that it should read the password from stdin when INSIDE_EMACS, which ensured that the password could be read in console Emacs too.

Now it does not read the password from stdin anymore, probably for safety reasons. And so the password cannot be read at all anymore, even in gui Emacs where usually a dialog window would be used.

> Does Magit have an option to set this env var?

No. I was going to suggest an advice which removes it from `process-environment`. But it is not a member of that, so it is probably not possible to unset this for child processes.

**Comment by npostavs** [comment]
> No. I was going to suggest an advice which removes it from `process-environment`. But it is not a member of that, so it is probably not possible to unset this for child processes.

I understood from 'set the env var "INSIDE_EMACS" to be NOT nil, the passphrase can be read' that it should be *set* to make it work, not unset.

**Comment by huyuehui** [comment]
What I said "read from..." might be confused. With INSIDE_EMACS not nil, this env will be passed on to gpg-agent. If gpg-agent sets "allow-emacs-pinentry", Emacs can communicate with gpg-agent via a local unix socket (M-x pinentry-start). The passphrase prompt shows up in Emacs's minibuffer without a GUI dialog.

If INSIDE_EMACS is nil AND pinentry-curse is used, the passphrase prompt shows up in the TTY I start window manager. I don't know how to type my passphrase in. After a timeout count, I get these error messages: 
```
128 git … commit --all --gpg-sign=xxxx
Waiting for Emacs...
error: gpg failed to sign the data
fatal: failed to write commit object
```
The reason of this, as pointed out by tarsius, might be:
> Magit doesn't use a pty but just consumes stdout. pinentry-curses expects a pty.

**Comment by tarsius** [comment]
Should be fixed by #2789.

**Comment by xkpb** [comment]
Hey Tarsius! Thanks for all your hard work. Unfortunately, this problem is persisting for me.  Signing commits via the command line works perfectly fine.

## Error

```
128 git … commit --gpg-sign\=F6B4<REDACTED>FE79
Waiting for Emacs...
error: gpg failed to sign the data
fatal: failed to write commit object
```

## GPG Agent Version

```
$ gpg-agent --version
gpg-agent (GnuPG) 2.2.4
libgcrypt 1.8.2
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Patricks-MacBook-Pro-2:~ patrick.brown$ 
```

## Magit Version

```
magit              20180224.1651 installed             A Git porcelain inside Emacs.
```
 
## Emacs Version

```
GNU Emacs 25.3.1 (x86_64-apple-darwin13.4.0, NS appkit-1265.21 Version 10.9.5 (Build 13F1911)) of 2017-09-12
```

## OS Version

![image](https://user-images.githubusercontent.com/4147775/36687392-5040cbde-1ade-11e8-95bb-0206a7274590.png)

**Comment by tarsius** [comment]
> After a recent software update (both gpg and emacs), the gpg signing functionality of magit breaks, show the following error codes

@xkpb Is this what happened to you too? If not then this issue is not the appropriate place to ask for help.

The problem you are having probably boils down to your shell's environment being properly setup for gpg to work and your Emacs' environment not being properly setup because you clicked on an icon to start Emacs and so your shells configuration does not apply to Emacs.

**Comment by xkpb** [comment]
@tarsius Indeed I am asking in the wrong place, apologies.

**Comment by jasonzhouu** [comment]
@kineticdial I have come cross the same problem, too. 

I think it's because `gpg` need user to input passphrase when committing, but `magit` don't show the interface to input passphrase.

But first you need to ensure that your `gpg` is working fine by commend: 
```
echo "test" | gpg --clearsign
```

I don't know deep about `gpg`. And I don't know why sometimes `gpg` don't need passphrase.

**Comment by ezchi** [comment]
I solve same issue by follow [this discussion](https://superuser.com/questions/1108170/gnupg-pinentry-depending-on-gui-presence/1354971#1354971).

**Comment by thor314** [comment]
Thanks @ezchi. It would be nice if that featured somewhere more prominently in documentation. It took me annoyingly long to find this.

**Comment by tarsius** [comment]
This can be misconfigured in many ways and I don't think it makes much sense to document this particular variant of what could go wrong in the Magit FAQ. This really goes beyond the scope of what the Magit documentation is supposed to be about.

It just so happens that I had similar issues today. In my case the fix was to add the following to `~/.gnupg/gpg-agent.conf`:

```
pinentry-program /usr/bin/pinentry-gnome3
```

I am mentioning this because some other Magit user might google their way to here and I suspect that this particular setting will help with many variants of "this" issue.

**Comment by larrasket** [comment]
Thanks @tarsius. Fixed for me with 
```conf
pinentry-program /opt/homebrew/bin/pinentry-mac
```
