### ISSUE TITLE
Consider to add separate Configure section for magit-branch-popup

### ISSUE THREAD

**Issue by fice-t** [magit/magit#2801]
When `magit-branch-popup-show-variables` is nil, then the `Configure` option is under the `Action` section in `magit-branch-popup`.

However, in `magit-{fetch,pull,push}-popup` it is under its own `Configure` section.

Could it be made the same in `magit-branch-popup` for consistency's sake?

`Magit 20160902.1451, Git 2.9.3, Emacs 25.1.3, gnu/linux`

**Comment by tarsius** [comment]
It's only a minor inconsistency though and I will leave it as-is for now because changing it would raise a few other minor issues. "Rename" should probably also be moved to "Configure" but what about "Reset" and "Delete", is that "configuring"? But lets ignore those two for a moment. The other popups you mention have dedicated section headings like "Push feature to", the branch popup does not. We could create a "Branch and/or Checkout section", but that's to noisy. Using two sections "Checkout" and "Create and Checkout" instead wouldn't quite work because several of the "checkout" variants actually also "Create" but that's not in their description because it is implied by the other words in their description, never the less having a "checkout" command under "Create and checkout" would be confusing. Also due to limitations in the implementations using more sections would waste to much space when the configure sections are also shown.

So yes, this should probably be addressed at some point, but I'll delay it until I work on the popups again anyway.

**Comment by tarsius** [comment]
Closing in favor of #2957.
