### ISSUE TITLE
Consider to allow hunk-internal region to span multiple hunks

### ISSUE THREAD

**Issue by IvanMalison** [magit/magit#2809]
Currently, when magit stage is invoked and point/mark span several hunks, only the mark at point is staged. It seems like the best behavior in this scenario would be to stage all of the hunks in between point and mark.

EDIT: issue title updated after discussion

**Comment by tarsius** [comment]
Unlike what you have been told on on gitter this is for the most part already possible.

1. It is possible the stage parts of a hunk.
2. It **is** possible to stage multiple hunks.
3. It is **not** possible to stage multiple **parts** of multiple hunks at once.

I.e. it is not possible to stage the bottom part of one hunk and the top part of another hunk. Is that really the feature you are after?

For (1) to work point and mark have to be within the same hunk *body*. For (2) to work mark has to be within the *header* of one hunk and point has to be within the *header* of another hunk.

This is also described in the documentation; [here](https://magit.vc/manual/magit/Staging-and-unstaging.html) and probably a few other places.

**Comment by IvanMalison** [comment]
> Unlike what you have been told on gitter this is for the most part already possible.
> 
> It is possible the stage parts of a hunk.
> It is possible to stage multiple hunks.
> It is not possible to stage multiple parts of multiple hunks at once.
> I.e. it is not possible to stage the bottom part of one hunk and the top part of another hunk in one go (plus optionally any number of complete hunks in between). Is that really the feature you are after?

Yes, sort of, although it is definitely useful to know that it IS possible to stage multiple hunks. It is sort of surprising (to me), that only the hunk at point is staged if mark does not start on a hunk heading. It seems to me that if someone has bothered to set the mark, they likely want anything that has been "selected" to be staged. OTOH, I can understand how this behavior makes more sense given the concept of sibling section types. I noticed that the location of mark (and whether it starts at a hunk heading or not) affects the way point/mark selection affects the faces of intermediate hunks, which should be a clue that putting mark somewhere other than the heading has different behavior, but I had simply never noticed this up until now.

> 
> For (1) to work point and mark have to be within the same hunk body. For (2) to work mark has to be within the header of one hunk and point has to be within the header of another hunk (this is where the "go to next/previous section" commands move).

> This is also described in the documentation; here and probably a few other places.

Sorry for missing that. I did open the manual and flip to the staging section, but I searched for point/mark instead of region and didn't read the entire section closely enough. 

Feel free to close this if you feel that there is good reason to keep the current behavior when the region does not start on a hunk heading.

**Comment by tarsius** [comment]
(I should add a node "Interface concepts > Sections > Section selection" to the manual. There is "Plumbing > Section plumbing > Section selection", but that describes the api, isn't intended for end-users, and only touches on the concepts in passing.)

I have considered implementing something similar to what you have in mind before, and still do, but since, as far as I remember, nobody ever asked for it before, I never seriously considered starting to implement it. I don't intend to do so any time soon, but this is still on the table. But I might as well outline some of the issues now.

To some extend the current restriction might, at least historically speaking, fall out of the implementation, but there are also factors concern consistency that speak against lifting this restriction.However I think that you might perceive the current limitation as an artificial restriction because you weren't aware that it is possible to stage multiple hunks at once at all until now.

The body of all other sections that can be selected as siblings consist of child sections. Only in the case of hunks does the body belong to the hunk but not also to a child. In other cases it would make no sense for a region that begins in the body of one section and ends in that of the next sibling to mean that commands should act on the two siblings. For example in the references buffer (the one you get with `y`) `k` with a region that begins on the nth commit of a branch and ends at the nth commit of the next sibling should absolutely not delete both of these branches. I don't think anyone would expect that and the non-special appearance of the region indicates that this won't happen.

The reason that Magit insists on the beginning and end of the region to begin inside the body is one of consistency. Lets for a moment assume you want to stage the beginning of a single hunk. You might not be aware that you first have to move inside the region before activating the mark, but you think that should be possible, and so you never find this feature. But you might not do so even if this restriction was lifted because I don't think it would be advisable visually indicate that the region is active for four reasons:

1. Most Emacs commands cannot act on an empty region, and so Emacs by default also does not visualize an empty region.

2. The hunk-internal region used for staging just parts of a hunk *can* act on an empty region and therefore does visualize it (i.e. the single line that will be staged). But the header of a hunk is not a removed or added line, it is metadata that cannot be staged.

3. Sibling selection requires at least two siblings to be selected. When the region only selects one section, then that is not considered a selection. Many commands behave quite differently depending on  whether they act on a selection or the current section (e.g. with regards to whether confirmation is required) and so again this should not be visualized.

4. Even if we ignored the above we couldn't visualize the region because we don't know if the user is going to press `C-n` in which case the hunk-internal region style would have been appropriate, or `n` in which case the selection style would have been appropriate.

I haven't gotten to the most serious issues yet, but I am done for now ;-)

**Comment by tarsius** [comment]
> Consider to allow hunk-internal region to span multiple hunks

I have decided against it.

**Comment by IvanMalison** [comment]
> I have decided against it.

:( I still find that this issue affects me from time to time. Is your reason for not including it that you don't want to do the work or that you don't think its a good idea. What if the behavior was disabled by default and configurable with a variable?

**Comment by tarsius** [comment]
Both really. I would have to support all kinds of special cases in already complicated code to support a feature that isn't really necessary (though possibly nice to have). And nobody else ever asked for this feature.

I have marked this as `wontadd`. Sometimes I revisit such issues and change my mind, but this at least fell considerably on my priority list.

**Comment by IvanMalison** [comment]
@tarsius Any chance you would reconsider this if I do all of the work to add the feature?

**Comment by vermiculus** [comment]
> What if the behavior was disabled by default and configurable with a variable?

As with all things, be wary of adding unnecessary complexity.
