### ISSUE TITLE
whitespace-mode kills colors

### ISSUE THREAD

**Issue by lazywithclass** [magit/magit#2821]
Thanks for the efforts coding this!

I reproduced this bug with plain Emacs with magit, then `M-x magit-status`, then open latest commit and notice the presence of colors.
`whitespace-mode` and all the colors are gone from the buffer.

Tested with Magit 20161011.744, Git 2.8.4 (Apple Git-73), Emacs 25.1.1, darwin

This was originally reported in Spacemacs https://github.com/syl20bnr/spacemacs/issues/4940

**Comment by tarsius** [comment]
`whitespace-mode` uses font-lock to do its thing. Magit does not use font-lock to to add faces/colors to its buffers. That makes them incompatible because turning on font-lock removes all faces keeping only those that it adds itself.

The only thing we could do is to somehow prevent `whitespace-mode` from being turned on in magit buffers. And because this issue comes up ever so often, I have done that now. For an alternative see `magit-diff-paint-whitespace`.

**Comment by lazywithclass** [comment]
Thanks a lot for the prompt answer.
