### ISSUE TITLE
Make SPC scroll blob/file buffer while point is on diff

### ISSUE THREAD

**Issue by phil-s** [magit/magit#2833]
I've become very used to typing SPC in diff buffers to view/scroll the relevant file in the other buffer. So much so, that I find myself trying to do this on the un/staged changes in the status buffer too, in an attempt to see more context around the current change.

At present that command will prompt for a commit, which doesn't seem like a useful thing to do contextually, so this seems like a sane feature request.

If it helps anyone else, my current hack is to add the following remapping to `magit-hunk-section-map`:

```
(define-key map [remap magit-diff-show-or-scroll-up] 'magit-diff-visit-file-other-window)
```

and the function:

```
(defun magit-diff-visit-file-other-window (file &optional force-worktree)
  "`magit-diff-visit-file' in other window, but not selecting the window."
  (interactive (list (--if-let (magit-file-at-point)
                         (expand-file-name it)
                       (user-error "No file at point"))))
  (save-selected-window
    (magit-diff-visit-file file :other-window force-worktree)))
```

I'm pretty sure that's not the _right_ solution, but it's useful in the meantime.

**Comment by tarsius** [comment]
> I've become very used to typing SPC in diff buffers to view/scroll the relevant file in the other buffer. 

I assume you mean "SPC in *log* buffers to scroll the *diff* buffer" and/or "SPC in diff buffer to scroll that buffer *itself*"?

> So much so, that I find myself trying to do this on the un/staged changes in the status buffer too, in an attempt to see more context around the current change.

Taken together with the above vagueness, this confused me for a while. I think what you are trying to achieve is that "pressing `SPC` on a diff in the status buffer, shows the file/blob buffer and if it is already visible, scroll that buffer instead (both without selecting the window which shows the file/blob buffer)".

That seems useful, but there are at least two issues:

1. Doing that would also make sense in *diff* buffers, but here `SPC` already does something different from scrolling "the other buffer", it scrolls the current buffer instead.
2. The "visit blob/file at the appropriate place for the diff at point" is limited to a few possible behaviors out of a set of many more actions, that are all reasonable and which we should find a way to make available. I don't want to go into details here, but this concerns questions such as whether the blob/file should be displayed in the selected or current window and whether the working tree file should be shown or the blob as found in a commit (or the index). There are many "dimensions" and I have to figure out which "coordinates" make sense and how to map commands and/or prefix arguments to those, as well as whether options to tune the behavior are required.

And now you just added an additional dimension, to scroll or not to scroll... ;-) It's quite complex, and I don't want to make any incremental changes, because that would most likely mean that I would have to make *breaking* changes several times. So... for now please use your command and binding, but I'll keep this in mind.

**Comment by phil-s** [comment]
Ack. I'm sorry for the confusion -- in retrospect I'm not sure how I managed to get that quite as wrong as I did :/

You have indeed managed to extract the correct interpretation from it all, and obviously I failed to take a lot of things into consideration. I'll follow up if I think I have something more useful to add, or if I improve on my interim solution.

**Comment by tarsius** [comment]
> pressing `SPC` on a diff in the status buffer, shows the file/blob buffer [...] without selecting the window which shows the file/blob buffer.

I have implemented that for any diff, not just those in the status buffer.

To avoid tears, I have not added any key bindings. See the release notes for instructions.

> and if it is already visible, scroll that buffer instead

Instead it simply jumps to the correct position. So pressing `SPC` again on the same line in the diff won't do anything. However if you move to another line, and then press `SPC` again, then point will be moved to the respective line in the file-visiting buffer also. Seems much more useful.
