### ISSUE TITLE
Support git-filter-branch

### ISSUE THREAD

**Issue by tarsius** [magit/magit#2851]

**Comment by andreareina** [comment]
Guessing the duplicate is #2849 and the resolution is `wont add`? Would be nice to have that explicitly confirmed here, this issue is the only thing that shows up when I google `magit filter-branch`. Need to `magit filter-branch site:github.com/magit/magit/issues` to surface the #2849 (or wade through the ocean that is github issue search). Love magit by the way, I love that lets me do stuff I'd never have tried with the cli, shows me *how* to do that on the cli, and still provides an escape hatch with `magit-git-command`.

**Comment by kyleam** [comment]
> Guessing the duplicate is #2849 and the resolution is `wont add`?

Correct.

I don't see explicit discussion of `filter-branch` in gh-2849, but two notes:

 1) `filter-branch` is note likely to be used routinely

 2) its use is now discouraged by Git, which gives the following warning:

    ```
    git-filter-branch has a glut of gotchas generating mangled history
    rewrites.  Hit Ctrl-C before proceeding to abort, then use an
    alternative filtering tool such as 'git filter-repo'
    (https://github.com/newren/git-filter-repo/) instead.  See the
    filter-branch manual page for more details; to squelch this warning,
    set FILTER_BRANCH_SQUELCH_WARNING=1.
    ```
