### ISSUE TITLE
magit-log should use magit-list-refnames

### ISSUE THREAD

**Issue by jferguson-gnubio** [magit/magit#2878]
When doing `Log other` (`magit-log`, `l o`), I would expect to use my normal `completing-read`, as defined in `magit-completing-read-function`.

Instead, I don't get my expected completion system (`ivy`, for what it's worth).  The code seems to use `read-from-minibuffer`, which at least `ivy` doesn't seem to automagically hook into.  Perhaps there's some reason why `magit-completing-read` is inappropriate here?

To reproduce, install `ivy` and `(setq magit-completing-read-function 'ivy-completing-read)`, then `Log other` doesn't have the expected ivy completion.  Is that enough detail?

magit-version: `Magit 20161126.1038, Git 2.7.4, Emacs 24.5.1, gnu/linux`

Thank you!

**Comment by npostavs** [comment]
> Instead, I don't get my expected completion system (`ivy`, for what it's worth).  The code seems to use `read-from-minibuffer`, which at least `ivy` doesn't seem to automagically hook into.  Perhaps there's some reason why `magit-completing-read` is inappropriate here?

Yes, you can enter multiple revisions (separated by `,`) at this prompt. And fancier completion methods don't support this kind of multi prompt.

**Comment by kyleam** [comment]
> you can enter multiple revisions (separated by ,)

Range indicators (`..` and `...`) are also useful separators.

**Comment by jferguson-gnubio** [comment]
Ok, thanks you, I thought there would probably be a reason.

So if I want to log another ref (e.g. frequently a github PR ref), is there some existing functionality to do that I haven't noticed? 

(In my git config for my upstream github remote I have `fetch = +refs/pull/*/head:refs/pull/gb/*`, so PR refs are available as `pull/origin/<pr_number>`.  `magit-log` won't complete those, and I'm so reliant on fuzzy completion elsewhere I never remember the format)

**Comment by kyleam** [comment]
> In my git config for my upstream github remote I have fetch =
> +refs/pull/*/head:refs/pull/gb/*, so PR refs are available as
> pull/origin/<pr_number>. magit-log won't complete those

Right, `magit-log-read-revs` uses `magit-list-branch-names`, which
doesn't include the refs/pull namespace.  If `magit-list-refnames`
were used instead (like in `magit-read-range`), these refs would be
included.  Since `magit-list-refnames` is used in the diffing command
prompts, I think it would be consistent to use it in the log prompt as
well.  If there is worry about flooding the completion list with too
many options due to the number of tags and pull requests, we could add
an option to choose between `magit-list-branch-names` or
`magit-list-refnames` that both `magit-read-range` and
`magit-log-read-revs` honor.

**Comment by tarsius** [comment]
> If `magit-list-refnames` were used instead (like in `magit-read-range`), these refs would be included.

Let's do that.

**Comment by kyleam** [comment]
> Let's do that.

OK, will do (my) tonight.
