### ISSUE TITLE
Dropping :use-prefix for magit-show-refs-popup

### ISSUE THREAD

**Issue by fice-t** [magit/magit#2894]
This is continued from the discussion [here](https://github.com/magit/magit/pull/2868#issuecomment-262437060).

As this is the only occurrence of `:use-prefix`, I think it should be removed by default. Restoring the functionality would just be `(plist-put magit-show-refs-popup :use-prefix 'popup)`, right?

Changing it would make all popup commands consistent, as well as at least showing users that there are other options that can be used with `y`, even if they are rarely used.

Then again, @tarsius raises a good point for the current behaviour:

> The refs buffer is like the status buffer in that it provides a grand overview. So it's consistent that both buffers are brought up without a popup (actually poping up).

I'm not sure whether I'd personally stick with the new default or put the `plist-put` line in my config, but I still think removing `:use-prefix` would be a good default.

**Comment by kyleam** [comment]
I don't weigh the consistency argument very strongly.  For me, the
important question is whether the goal is for the popup to behave
operationally as a command.

My understanding is that magit-show-refs (a *command*, not a popup)
originally replaced both the magit-branch-manager and magit-wazzup
*commands* (2e8c1d5e).  This was later extended as a popup (f08cb223).
So, by default, the popup's behavior was indistinguishable from the
command it replaced.  So are any of the current options or alternative
actions useful enough to make magit-show-refs-popup stop behaving as a
command?

**Comment by tarsius** [comment]
For me too, the history outlined by Kyle trumps the consistency @fice-t is after.

However in the release notes for `2.9.0` I wrote:

> [Type] "y o RET" to make commit counts and lists of cherries commits relative to the reference at point.

Which @kyleam pointed out was wrong, it should have been <kbd>C-u y o RET</kbd>. That wasn't a typo though, I though it did behave that way and certainly think it should. I implemented that in #2898 but then realized there was an additional, more important, and harder to address issue. I am closing this issue in favor of #2898.

I will not change the behavior of <kbd>y</kbd> in non-refs-buffers and because I also don't want to change the behavior of <kbd>C-u y</kbd> that means that there will still be a popup that by default just invokes its default action. There is a possibility that I will remain that command from `magit-show-refs-popup` to `magit-list-references`, but then that just trades one inconsistency for another.

**Comment by fice-t** [comment]
The current behaviour does make more sense given the history. I still dislike that it's being grouped in with the other popups though. I don't suppose commands like `y` and `e` could be moved out to another (misc.) section in `h`? That would also alleviate my concerns about consistency, and would also give commands like `i` a place in `h`.

> So are any of the current options or alternative
actions useful enough to make magit-show-refs-popup stop behaving as a
command?

Not really. It just pokes me the wrong way, so it doesn't matter much.

**Comment by tarsius** [comment]
> I don't suppose commands like `y` and `e` could be moved out to another (misc.) section in `h`?

We should consider that. Please open a new issue.

**Comment by kyleam** [comment]
@fice-t 
> Not really. It just pokes me the wrong way, so it doesn't matter
> much.

I think the consistency of magit-show-refs-popup is a good point to
discuss.  I hope my comment above didn't read as dismissive.

**Comment by tarsius** [comment]
... or let's talk here for context.
