### ISSUE TITLE
Linkify issues and hashes in commit messages

### ISSUE THREAD

**Issue by tarsius** [magit/magit#2949]
Issue numbers and hashes should be linkified in commit messages. This applies both to `magit-revision-mode` buffers and to "COMMIT_EDITMSG` and friends.

For issue numbers we can use the built-in `bug-reference` package. For Magit for example one has to add the following to `./.dir-locals.el` (I'm gonna do that by the way):

```
((nil
  (bug-reference-bug-regexp . "#\\(?2:[0-9]+\\)")
  (bug-reference-url-format . "https://github.com/magit/magit/issues/%s")))
```

We might want to narrow this down instead of using the match-all `nil`. Additionally `bug-reference-mode` has to be added to `magit-revision-mode-hook` and `git-commit-setup-hook`. We might wanna do that by default or at least present it as an option.

This should also be documented in the Magit manual (and or the doc-strings of the mentioned hook variables) or maybe we could even provide tooling to set this up automatically.

---

For hashes I am not aware of an existing package. Also here we don't want to send the user to some web page, instead the revision should be shown using `magit-show-commit`.

Regarding finding hashes will avoiding to many false-positives and false-negatives: this should be good enough, at first at least:

```
(and (re-search-forward "\\<[0-9a-z]\\{7,40\\}\\>" nil t)
     (string-match-p "[0-9]" (match-string 0)))
```

---

We should also attempt to set this up automatically.

---

Some things to check out:

- http://oremacs.com/2016/02/15/counsel-ffap/
- https://melpa.org/#/bug-reference-github

**Comment by phil-s** [comment]
I think it would be useful if, in the absence of a linked ref, `RET` would check the text at point to see if it was a valid ref, and if so then visit it.

That approach avoids the problem of deciding in advance whether or not something is a ref, and also allows for accessing all types of ref, rather than just hashes.

`SPC` seems problematic in that you don't want to be using that to scroll through the buffer and suddenly find you're instead visiting a ref in the other window because point happened to fall on one after the previous scroll. The other-window visiting behaviour is desirable to retain, though, so perhaps `C-u SPC` could be used for this?

I think this would mean `magit-visit-ref` should work everywhere, in general? Which would be very nice.

**Comment by tarsius** [comment]
> I think it would be useful if, in the absence of a linked ref, RET would check the text at point to see if it was a valid ref, and if so then visit it.

Yes, that would be useful too.

> That approach avoids the problem of deciding in advance whether or not something is a ref,

but make it less obvious that that feature even exists.

> and also allows for accessing all types of ref, rather than just hashes.

which is why we should use both approaches ;-)

(But I haven't given the implementation too much though yet. Well almost none.)
