### ISSUE TITLE
magit-diff-while-commiting shows empty when the repo was made with --separate-git-dir

### ISSUE THREAD

**Issue by yamada-github-account** [magit/magit#2955]
When editing a commit message at "COMMIT_EDITMSG" buffer, it is expected the staged changes are shown in "*magit-diff: foo" buffer, however, the "*magit-diff: foo" buffer says "(empty)" and the "foo" (directory name) is outside the git repository.

This happens the all the time as long as the repository has been made with --separate-git-dir option.
When I manually executed the function "magit-toplevel" at "COMMIT_EDITMSG" buffer, it returned wrong directory (one level higher directory than the correct git top level directory).

This is also reproduced at the pure emacs instance of "magit-emacs-Q-command".

Magit 20170106.1903, Git 2.11.0, Emacs 25.1.1, darwin
GNU Emacs 25.1.1 (x86_64-apple-darwin16.1.0, Carbon Version 157 AppKit 1504.6) of 2016-11-03
macOS Sierra version 10.12.2

**Comment by tarsius** [comment]
Could you please provide exact steps to reproduce this? I almost exclusively use repositories "created with `--separate-git-dir`, and never see this. Also please explicitly state the `default-directory` in the various buffers. It seems some information has been lost in the foo-ificaion.

**Comment by yamada-github-account** [comment]
The Following is the exact steps;

cd ~
git init dirA --separate-git-dir=dirB
cd dirA
/Applications/MacPorts/EmacsMac.app/Contents/MacOS/Emacs -Q --eval \(setq\ debug-on-error\ t\) -L /Users/yamada/.emacs.d/elpa/magit-20170106.1903/ -L /Users/yamada/.emacs.d/elpa/magit-popup-20170104.924/ -L /Users/yamada/.emacs.d/elpa/with-editor-20161231.826/ -L /Users/yamada/.emacs.d/elpa/git-commit-20170109.1253/ -L /Users/yamada/.emacs.d/elpa/dash-20161121.55/ -l /Users/yamada/.emacs.d/elpa/magit-20170106.1903/magit fileA

Type some letters.
C-x C-s
M-x magit-status
Stage fileA by pressing "s"
c c

The popup buffer name is "*magit-diff: yamada" instead of "*magit-diff: dirA"
The "*magit-diff: yamada" buffer shows

Staged changes
(empty)
[back]

The values of default-directory
"~/dirA/" at "fileA"
"/Users/yamada/dirA/" at "*magit: dirA"
"/Users/yamada/dirA/" at "*magit-commit-popup*"
"/Users/yamada/dirB/" at "COMMIT_EDITMSG"
"/Users/yamada/" at "*magit-dir: yamada"
"/Users/yamada/dirA/" at "*magit-process: dirA"
global value is nil

**Comment by tarsius** [comment]
Okay I can reproduce.

Also it's not really true that I use `--separate-git-dir` a lot. I use submodules and by default their git directories are places at `<super-repo>/.git/modules/<name>`. But when creating a submodule that also sets `core.worktree` in `<super-repo>/.git/modules/<name>/config`. `git init --separate-git-dir` doesn't do that, and that should probably be considered a bug.

The diff buffer is created while the `COMMIT_EDITMSG` is current and the `default-directory` of that is `<super-repo>/.git/modules/<name>/`. Since `core.worktree` is not set git and magit have no way of knowing where the worktree is at that point.

Git then steps out of the git directory (goes to `../`), which in other situations is the correct thing to do. We could probably avoid doing this in this particular case (or always?). But that will require some thought and testing.

Meanwhile you can just set `core.worktree`. Also maybe you could ask on the Git mailing list why `core.worktree` isn't set?

**Comment by kyleam** [comment]
Reopening.  The fix from #2963 was reverted in 8fcda90c due to the
issue raised in #2981.
