### ISSUE TITLE
vdiff integration

### ISSUE THREAD

**Issue by tarsius** [magit/magit#2962]
Just doing the same as for `ediff` should be easy.

Unless `vdiff`'s interface differs significantly.

https://github.com/justbur/emacs-vdiff/issues/8

**Comment by justbur** [comment]
[FYI](https://github.com/justbur/emacs-vdiff/issues/8#issuecomment-275975015)

**Comment by justbur** [comment]
@tarsius I merged something that works for most functions. I don't have something like `ediff-merge-buffers-with-ancestor` yet, so `vdiff-magit-resolve` is limited to 2-way merges. 

There's a lot of code duplication though and it would be nice to reduce that. The vdiff API is very similar to ediff but not the same. The main differences are 
  1. I simplified the way callbacks work at the end of the diff session. `vdiff-buffers` and friends take a `lambda` that accept the buffers as arguments. ediff wants a hook to run in the control buffer (there's no control buffer in vdiff).  
  2. There are built-in options to restore the window configuration and kill buffers. Sometimes this has to be done manually, but these options reduce the amount that has to be done in the callback. 
  3. There's no real distinction with merge buffers yet, so in `vdiff-magit-resolve` for example I just use `vdiff-buffers3` instead of a specialized function like `ediff-merge-buffers`. 

Anyway, my reason for explaining this is that I was wondering what the best way forward is. Some questions:
  - Should the integration functions be put into magit proper or should it be maintained separately? 
  - Should magit-ediff.el be made more generic with say a `buffer-diff-function` option that users can set? 
  - Should the API for vdiff match ediff's to the extent possible?

**Comment by tarsius** [comment]
Just wanted you to know that while I have forgotten about this, I just remembered again. I'll try to look into this soonish.

**Comment by tarsius** [comment]
I have just looked at `magit-ediff.el` and `magit-vdiff.el` again. Since I don't use `ediff` or `vdiff` I am not particularly motivated to (re-)learn enough about their APIs in order to write some kind of Magit API that would work for both `magit-ediff` and `magit-vdiff`.

Also you have already written `magit-vdiff.el` so you have already spend the time necessary to do this because Magit does not provide an API, and I assume it works well, so investing lots of time to write some abstraction just so some duplicated code can be removed does not sound appealing.

> Should the integration functions be put into magit proper or should it be maintained separately?

You have already done the latter, right - that's what `magit-vdiff.el` does?

> Should magit-ediff.el be made more generic with say a `buffer-diff-function` option that users can set?

I don't think a single option will do.

 > Should the API for vdiff match ediff's to the extent possible? 

No, I think you should make it as good as possible instead :wink: The downside is that you have to maintain a `magit-vdiff.el` that isn't trivial, but from the looks of it is simpler than `magit-ediff.el`, so that's a win. Well, except for the fact that you have to maintain it of course.

---

I am closing this because I don't see myself implementing `vdiff` support. You are welcome to try to abstract `magit-ediff.el` so that it can support `vdiff` as well, but if the end result is that we trade some duplication for increased complexity, then I prefer the duplication.

**Comment by justbur** [comment]
Fair enough. Thanks for looking into it at least.
