### ISSUE TITLE
Batch operation in magit-list-repositories

### ISSUE THREAD

**Issue by HIRANO-Satoshi** [magit/magit#2971]
Hi,

magit-list-repositories has become very much better with DIRTY flag. Thank you.

Now we need to open repos and do pull/push remote one by one.

We would be happy if we can do 'F' for pull all, 'P' for push all, 'C' for commit all in all repos.
Such batch operations will be very convenient.

**Comment by tarsius** [comment]
Of the commands you mention I could only see myself using `fetch` for all repositories at once.

I often create commits that I don't want to push, sometimes I even create them directly on `master`. And often I don't remember that I have done that in some repository and have to go and look. So at least in my case it would be dangerous to push in all repositories.

I also care about the quality of commit messages, so committing everything in every repository using commit messages like "Updates" is out of question. As is unintentionally committing incomplete changes because I walked away from the computer and then did not remember when I came back.

In some of my repositories doing these things would be okay, but not in every repository returned by `magit-list-repos`. That list is intended to be complete or at least a diverse subset of all the repositories.

So I think that it would be better to implement specific tasks (such as "commit and push everything in A, B and C, but not any other repositories") in simple shell scripts. Or as personal elisp commands.

Another issue with a generic "run stuff everywhere" command is that we would have to choose between doing "stuff" synchronously (in which case the user might have to wait a long time), or asynchronously (in which case the user *also* would have to wait a long time, and then s/he wouldn't even be certain that everything was done yet).

Implementing a minimal viable version isn't hard, here you go:

```lisp

(with-eval-after-load 'magit-repos
  (define-key magit-repolist-mode-map "x" 'magit-repolist-popup))

(magit-define-popup magit-repolist-popup
  "Popup console for repolist commands.
Commands bound in this popup should use the
macro `magit-with-repositories' (which see)."
  :actions '((?f "Fetch in all repositories" magit-repolist-fetch)
             (?F "Fetch in all repositories asynchronously"
                 magit-repolist-fetch-async)
             (?x "Run a command in all repositores"
                 magit-repolist-run))
  :max-action-columns 1)

(defun magit-repolist-fetch ()
  "Fetch all remotes in repositories returned by `magit-list-repos'.
Fetching is done synchronously."
  (interactive)
  (run-hooks 'magit-credential-hook)
  (let* ((repos (magit-list-repos))
         (l (length repos))
         (i 0))
    (dolist (repo repos)
      (let* ((default-directory (file-name-as-directory repo))
             (msg (format "(%s/%s) Fetching in %s..."
                          (cl-incf i) l default-directory)))
        (message msg)
        (magit-run-git "remote" "update" (magit-fetch-arguments))
        (message (concat msg "done")))))
  (magit-refresh))

(defun magit-repolist-fetch-async ()
  "Fetch all remotes in repositories returned by `magit-list-repos'.
Fetching is done asynchronously."
  (interactive)
  (run-hooks 'magit-credential-hook)
  (dolist (repo (magit-list-repos))
    (let ((default-directory (file-name-as-directory repo)))
      (magit-run-git-async "remote" "update" (magit-fetch-arguments)))))

(defun magit-repolist-call-command (command)
  "Read a command and run it in repositories returned by `magit-list-repos'.

If the COMMAND does its job asynchronously, then that likely
won't be done for all repositories by the time this function
returns.  If it does its job synchronously, then doing it
many times might take a long time."
  (interactive (list (read-command "Call in all repositories: ")))
  (magit-with-repositories
    (call-interactively command))
  (magit-refresh))
```

But that isn't useful or good enough for me to add it to Magit. That being said, your mileage may vary, so feel free to add this to your init file. But I think going with personal scripts, that do exactly what you want and that you can edit when your needs change, are a better option.

**Comment by HIRANO-Satoshi** [comment]
@tarsius  Thank you very much!!

**Comment by alphapapa** [comment]
This is the kind of that that http://myrepos.branchable.com/ was designed for.

**Comment by haji-ali** [comment]
@tarsius, I realize this is an old issue. But one macro I am interested in using is `magit-with-repositories` which does not seem to be part of magit anymore. 

I tried searching in the history of the repository with no luck. Am I missing something?

**Comment by tarsius** [comment]
Seems that never actually existed but this should do: `(dolist (repo (magit-list-repos)) ...)`.

**Comment by haji-ali** [comment]
Wouldn't I also need some `with-repo` command to be able to call `command` interactively in `magit-repolist-call-command` like you wrote above?

**Comment by tarsius** [comment]
Let-binding `default-directory` on each iteration makes sure you run inside each repository in turn. If possible you should probably avoid using `call-interactively` and just call the function directly with the appropriate arguments.

**Comment by chasecaleb** [comment]
I had problems with this breaking due to magit's caching, but I was able to work around it.

Most of my repos have `origin/master` as upstream, but not all, and one in particular does not even have a `master` branch. Using [tarsius' version of `magit-repolist-fetch` above](https://github.com/magit/magit/issues/2971#issuecomment-336644529) causes the following:

```elisp
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  split-string(nil "\11")
  magit-rev-diff-count("HEAD" #("origin/master" 0 13 (face magit-branch-remote font-lock-face magit-branch-remote)))
  (cdr (magit-rev-diff-count "HEAD" it))
  (car (cdr (magit-rev-diff-count "HEAD" it)))
  (magit-repolist-insert-count (car (cdr (magit-rev-diff-count "HEAD" it))) spec)
  (progn (magit-repolist-insert-count (car (cdr (magit-rev-diff-count "HEAD" it))) spec))
  (if it (progn (magit-repolist-insert-count (car (cdr (magit-rev-diff-count "HEAD" it))) spec)))
  (let ((it (magit-get-upstream-branch))) (if it (progn (magit-repolist-insert-count (car (cdr (magit-rev-diff-count "HEAD" it))) spec))))
  magit-repolist-column-unpulled-from-upstream(((:id "gitlab-pipeline") (:title "B<U") (:width 3) (:right-align t) (:help-echo "Upstream change not in branch")))
  #f(compiled-function (arg0) #<bytecode 0x14173089936a6a47>)(("B<U" 3 magit-repolist-column-unpulled-from-upstream ((:right-align t) (:help-eco "Upstream changes not in branch"))))
  #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_13>(("gitlab-pipeline" . "/home/caleb/gitlab-pipeline/"))
  magit-repolist-refresh()
  tabulated-list-revert(nil nil)
  revert-buffer()
  magit-refresh()
  magit-run-git("remote" "update" nil)
  cc/magit-repolist-git-fetch()
  funcall-interactively(cc/magit-repolist-git-fetch)
  command-execute(cc/magit-repolist-git-fetch)
```

Caching makes magit use `origin/master` as upstream for `gitlab-pipeline` repo, when it's actually `origin/v4`. I didn't experiment far enough to be sure, but I assume the issue is that the cache key doesn't take into consideration the `default-directory` change. I was able to work around it like this (note the temporary advice that resets the cache):
```elisp
;; From https://emacs.stackexchange.com/a/54502
(defmacro cc/with-advice (original-fn where advice-fn &rest body)
  "Execute BODY with advice temporarily enabled."
  (declare (indent 3))
  `(let ((fn-advice-var ,advice-fn))
    (unwind-protect
      (progn
        (advice-add ,original-fn ,where fn-advice-var)
        ,@body)
      (advice-remove ,original-fn fn-advice-var))))

(defun cc/magit-repolist-git-fetch ()
    "Fetch all remotes in repositories returned by `magit-list-repos'.
Fetching is done synchronously."
    (interactive)
    (run-hooks 'magit-credential-hook)
    (let* ((repos (magit-list-repos))
           (l (length repos))
           (i 0))
      (dolist (repo repos)
        (let* ((default-directory (file-name-as-directory repo))
               (msg (format "(%s/%s) Fetching in %s..."
                            (cl-incf i) l default-directory)))
          (message msg)
          ;; Hack to deal with caching bug. Caches are fun and easy, right? (n.b. no, they aren't)
          (cc/with-advice #'magit-get-upstream-branch :around
                          (lambda (fn &rest args)
                            (let ((magit--refresh-cache nil))
                              (apply fn args)))
            (magit-run-git "remote" "update" (magit-fetch-arguments)))

          (message (concat msg "done")))))
    (magit-refresh))
```

@tarsius FYI you might want to be aware of this. Obviously it's no big deal that a four year old snippet no longer works, but I wanted to point this out in case it indicates a real issue in your `magit--with-refresh-cache` macro. Maybe the macro could add `default-directory` (or a hash of it) to the key.

**Comment by kyleam** [comment]
> Maybe the macro could add `default-directory` (or a hash of it) to the key.

Looking through the 13 `(magit--with-refresh-cache` grep hits, it looks like only 3 call sites don't use `default-directory` in the key.  I think this should cover it (untested):

<details>
<summary>patch</summary>

```diff
diff --git a/lisp/magit-git.el b/lisp/magit-git.el
index 84a6c517..120734bb 100644
--- a/lisp/magit-git.el
+++ b/lisp/magit-git.el
@@ -1455,7 +1455,8 @@ (defun magit-get-upstream-branch (&optional branch)
 then return nil.  I.e.  return the name of an existing local or
 remote-tracking branch.  The returned string is colorized
 according to the branch type."
-  (magit--with-refresh-cache (list 'magit-get-upstream-branch branch)
+  (magit--with-refresh-cache
+      (list default-directory 'magit-get-upstream-branch branch)
     (when-let ((branch (or branch (magit-get-current-branch)))
                (upstream (magit-ref-abbrev (concat branch "@{upstream}"))))
       (magit--propertize-face
@@ -1525,7 +1526,8 @@ (defun magit-get-push-remote (&optional branch)
     (magit--propertize-face remote 'magit-branch-remote)))
 
 (defun magit-get-push-branch (&optional branch verify)
-  (magit--with-refresh-cache (list 'magit-get-push-branch branch verify)
+  (magit--with-refresh-cache
+      (list default-directory 'magit-get-push-branch branch verify)
     (when-let ((branch (or branch (setq branch (magit-get-current-branch))))
                (remote (magit-get-push-remote branch))
                (target (concat remote "/" branch)))
diff --git a/lisp/magit-log.el b/lisp/magit-log.el
index 3eeb8771..a4b0858d 100644
--- a/lisp/magit-log.el
+++ b/lisp/magit-log.el
@@ -1820,7 +1820,8 @@ (defun magit-insert-unpushed-to-pushremote ()
         (magit-log-insert-child-count)))))
 
 (defun magit--insert-pushremote-log-p ()
-  (magit--with-refresh-cache 'magit--insert-pushremote-log-p
+  (magit--with-refresh-cache
+      (list default-directory 'magit--insert-pushremote-log-p)
     (not (and (equal (magit-get-push-branch)
                      (magit-get-upstream-branch))
               (or (memq 'magit-insert-unpulled-from-upstream
```

</details>
