### ISSUE TITLE
Given a commit, show log of "surrounding" commits

### ISSUE THREAD

**Issue by tarsius** [magit/magit#2990]
Say you are investigating why something is implemented the way it is and start with blaming.  Then you visit some commit by pressing `RET` on a line you expect to lead you to a commit whose commit message might shed some light on the issue.

Reading the message, you realize that it is part of a series of commits, and you want to read the messages of those other commits also.  You can show a log up to the commit you are looking at using `l o RET`, but you cannot easily show a log that also lists the commits that follow the current commit.

Implement that.

Complications:

1. Detect whether the commit is part of a feature branch.  Use that to decided how many commits to display.

2. The history might diverge following the commit.  If so, then show the log for multiple commits.  Though given (1), maybe not.

**Comment by Silex** [comment]
Yes! Finding parents is easy (REF^N or REF~N), but finding children in git is a pain. You basically have to know in advance, or use something like `git log --oneline --reverse master..REF | head -n 10`.

**Comment by mbertheau** [comment]
I think there's no need to think about how many commits to display that follow the commit in question - whatever you pick could be too little for somebody. Instead you could interpret that as just "scroll to this commit in my current log".

Since it seems to be a performance problem to show many commits in the log, maybe have a way to scroll up the same way there's a feature to scroll down already.

**Comment by yashi** [comment]
I like the @mbertheau 's idea (scroll up and down anyway), but I just tried whether I can detect the given commit is on a feature branch or not.

Given that a feature branch is merged with `--no-ff` all the time, then we have a merge base and a merge point unless the feature branch is still WIP state and not merged yet.

To illustrate my idea, I'm using Linux kernel git repository, for speed and complexity.

First, let's find the merge point.  This is the first merge commit of the target commit.  It might not be a merge to master but it should be good to indicate the end of the series.

```
git rev-list --merges --ancestry-path 55461ddbcb0b36d1575e01fb4f130c609ca1cfee..master | tail -n 1
1c212c65b2468e9a302f06849e244d461cc89d86
```

And this takes time if the commit is deep in the history.  In the case of the above commit, it took 5 second on my Intel Core i5-3360M CPU @ 2.80GHz with all warm cache.

```
4.49user 0.10system 0:04.59elapsed 99%CPU (0avgtext+0avgdata 515712maxresident)k
0inputs+0outputs (0major+43326minor)pagefaults 0swaps
```

Then, we need the merge base.  That's where the series started in a simple feature branch case.  It might not be that simple if merge history is complex.

In order to get the merge base you must take the other path the commit is not on.  To do that, get parents of the merge point.

```
git show --pretty=%P 1c212c65b2468e9a302f06849e244d461cc89d86
f82202bae3f7f076402b16ca7bced9928aad16d0 f57b07c0c7ca9e4dde36acfabdf474ee3c478e6d
```

Then, check whether the commit is an ancestor or not.

```
git merge-base --is-ancestor 55461ddbcb0b36d1575e01fb4f130c609ca1cfee f82202bae3f7f076402b16ca7bced9928aad16d0
echo $?
1
git merge-base --is-ancestor 55461ddbcb0b36d1575e01fb4f130c609ca1cfee f57b07c0c7ca9e4dde36acfabdf474ee3c478e6d
echo $?
0
```
So, use `f82202bae3f7f076402b16ca7bced9928aad16d0` to find the merge base.

```
git merge-base 55461ddbcb0b36d1575e01fb4f130c609ca1cfee f82202bae3f7f076402b16ca7bced9928aad16d0
f4ba394c1b02e7fc2179fda8d3941a5b3b65efb6
```
So, `f4ba394c1b02e7fc2179fda8d3941a5b3b65efb6` is the merge base.  Now plot the results, from the merge base to merge point.

```
gitk f4ba394c1b02e7fc2179fda8d3941a5b3b65efb6..1c212c65b2468e9a302f06849e244d461cc89d86
```
OK, the result isn't limited to the topic branch, but it's quite good view of what's going on.

my 2 cents,

**Comment by mbertheau** [comment]
However long it takes, it should be faster than finding the commit by hand.

**Comment by tarsius** [comment]
@kyleam Implemented a basic `magit-log-merged` a few months ago. It is not available from the log transient by default but can be easily enabled as described under "Interactively Enabling and Disabling Suffixes" at https://emacsair.me/2019/02/14/transient-0.1.

I have implemented some improvements now:

* Put point on the commit the user specified.
* Commit that were made directly on the branch are supported too now. In that case just show the 20 surrounding commits.

**Comment by mbertheau** [comment]
Works well enough for me, thanks!

**Comment by Jean-Baptiste-Lasselle** [comment]
Ah, mais, ne serait-ce pas là la notion de "Voisinage", qui apparaît, là où ne l'attend pas...? :)
