### ISSUE TITLE
Expose git-merge's "-S" option for GPG signing merge commits

### ISSUE THREAD

**Issue by dakrone** [magit/magit#2996]
I appreciate that magit lets me sign individual commits by adding the `=S` option (for adding `--gpg-sign`).

I think it would also be useful to expose the `-S` option for `git merge` that allows signing the merge commits generated when non-fastforward merging a branch.

**Comment by kyleam** [comment]
How about setting it in your configuration?  Something like

```elisp
(magit-define-popup-option 'magit-merge-popup
  ?S "Sign using gpg" "--gpg-sign=" #'magit-read-gpg-secret-key)
```

Also, see #2941.

**Comment by dakrone** [comment]
@kyleam that works in the meantime, thanks!

**Comment by baltakatei** [comment]
Regarding automatically signing merge commits, sometimes a pull operation under Magit will trigger a merge commit which isnʼt necessarily signed as one could do manually via `git pull --gpg-sign`. I looked up a way to do this automatically in Maigt as of `20231014.1408 [>= 3.3.0.50-git], Transient 0.4.3, Git 2.34.1, Emacs 27.1, gnu/linux`. Since `magit-define-popup-option` seems deprecated, a solution requires using `transient`.

After examining the [relevant manual page](https://magit.vc/manual/transient/Modifying-Existing-Transients.html) of Transient and resolving an issue where Emacs complained that `magit-pull` was not a command upon startup (fixed via using [`with-eval-after-load`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Hooks-for-Loading.html)), evaluating the following at startup (e.g. by adding it to your `~/.emacs.d/init.el`) seems to work.

```
(with-eval-after-load 'magit
  (transient-append-suffix 'magit-pull "-r"
  '("-S" "Sign using gpg" "--gpg-sign")))
```

This results is the placing of  the popup text `-S Sign using gpg (--gpg-sign)` after the `-r Rebase local commits (--rebase)` line in the `F` (pull) transient (?). Example in the image below:

 ![magit pull transient with -S](https://reboil.com/res/2023/img/20231019T0330+00..magit_pull_gpgsign_transient_400x200.png)

Also, immediately after manually evaluating the statement, I get the following return message instead of an error message, so I must be doing something right: `((1 transient-switch (:key "-S" :description "Sign using gpg" :argument "--gpg-sign" :command transient:magit-pull:--gpg-sign)) (7 transient-switch (:key "-A" :description "Autostash" :argument "--autostash" :command transient:magit-pull:--autostash)))`.

See also: https://github.com/magit/magit/discussions/4889

**Comment by tarsius** [comment]
This argument is available from that prefix already, but it is hidden by default.

To learn how to show it, see https://magit.vc/manual/transient.html#Enabling-and-Disabling-Suffixes.
