### ISSUE TITLE
`b b RET` in a magit refs buffer

### ISSUE THREAD

**Issue by elibarzilay** [magit/magit#3009]
I have recently updated my magit from 2.8 (or older, not sure) to
2.10.1.  One change that I ran into is the different behavior of `RET`
in a magit refs buffer.  I saw a mention of that in
`RelNotes/2.9.0.txt`, and I tried to follow the recommendation there and
use `b b RET` instead of `RET`.  That breaks, however, on a remote ref,
resulting in a detached head.  As I re-read that text, I see that I
missed the additional recommendation to use `b c RET RET` in those
cases, but that becomes more cumersome.

So, I resorted to

    (setq magit-visit-ref-behavior '(create-branch checkout-any focus-on-ref))

but I dislike diverging from the recommended thing, however, it looks
like there is nothing that works as `RET` does with that settings--?
I.e., some key (other than `RET`) that I can always hit to checkout the
branch, making a local one if it's a remote one.

(Apologies if this is the wrong place, I started this as a bug report,
but since the functionality is there, it's probably more like a feature
request.)  (And double apologies if it does exist somewhere.)

My version:
> Magit 2.10.1-19-gc5922d9f, Git 2.11.0.windows.3, Emacs 25.1.1, windows-nt

**Comment by tarsius** [comment]
> I dislike diverging from the recommended thing

It looks like there's no way around that, or living with it "becoming cumbersome". You either have to:

1. Set `magit-visit-ref-behavior` as recommended. Then `RET` behaves exactly the same as before. And the code that is actually executed is also the same, except that there are a few `(if (memq X magit-visit-ref-behavior) ...)` sprinkled in. I don't intend to make any more changes to that code-path or the configuration mechanism, so this should be safe.
2. You use `b c`, the "create and checkout a new branch" command. Which would be the "recommended thing". Using `b b` would not work, as you have noticed, because that does "checkout something, without creating anything new". `HEAD` can only point at a local branch or directly at a commit, for tags, remote branches, and any other non-local-branch ref for that matter, that means checking out the pointed at commit directly.
3. I add yet another option so that `b b` can be configured to behave like `b c` when the user chooses a remote branch. But changing the value of that option would again mean to diverge from the "recommended thing".

**Comment by elibarzilay** [comment]
Obviously if the functionality I want is not there and will not be there on some key then I'll need to diverge from recommended thing.  I was hoping that there is some convenient command that does that, or some place to add it to.

I ended up tweaking `magit-visit-ref` as below.  The second change is because I usually scan a long list of remote branches and it's far more useful to me to check one out when I'm at that part instead of jumping to the top after I find that I already have a local branch for that remote one, instead of the resetting behavior.

Both/either of these can be made properly, conditioning on additional `magit-visit-ref-behavior` flags; I can do that in a PR if there's interest.

       (if (and (derived-mode-p 'magit-refs-mode)
                (magit-section-match '(branch tag)))
           (let ((ref (magit-section-value (magit-current-section))))
    -        (cond ((and (memq 'focus-on-ref magit-visit-ref-behavior)
    +        (cond (current-prefix-arg
    +               (let ((current-prefix-arg nil))
    +                 (call-interactively #'magit-show-commit)))
    +              ((and (memq 'focus-on-ref magit-visit-ref-behavior)
                         current-prefix-arg)
                    (magit-show-refs ref))
                   ((and (memq 'create-branch magit-visit-ref-behavior)
                         (magit-section-match [branch remote]))
                    (let ((branch (cdr (magit-split-branch-name ref))))
                      (if (magit-branch-p branch)
    -                     (if (yes-or-no-p
    -                          (format "Branch %s already exists.  Reset it to %s?"
    -                                  branch ref))
    -                         (magit-call-git "checkout" "-B" branch ref)
    -                       (user-error "Abort"))
    +                     (progn (message "Branch %s already exists, switching to it."
    +                                     branch)
    +                            (magit-call-git "checkout" branch))
                        (magit-call-git "checkout" "-b" branch ref))
                      (setcar magit-refresh-args branch)
                      (magit-refresh)))

**Comment by tarsius** [comment]
> Both/either of these can be made properly, conditioning on additional `magit-visit-ref-behavior` flags; I can do that in a PR if there's interest.

Seems reasonable. But I would like to get a second opinion. @kyleam?

**Comment by kyleam** [comment]
I think both these behaviors would be worth supporting.

For the C-u show-commit part, it may be useful to enable that without
adding an additional flag, instead just checking if `focus-on-ref` is
not there.

For the reseting vs switching to local branch behavior, I wonder if
it's a rare enough event that it'd be ok to prompt about whether to
reset or switch, rather than adding another flag to
`magit-visit-ref-behavior`.

**Comment by tarsius** [comment]
Maybe yes. The second thing occurred to me too, in much the same way as to you: probably but not sure ;-)

**Comment by tarsius** [comment]
I have implemented both changes as suggested by @kyleam.

@elibarzilay You will need `(setq magit-visit-ref-behavior '(create-branch checkout-branch)` and you will have to confirm that you want to simply checkout the existing local branch instead of resetting it to the remote branch at point. You might also want to keep an eye on #2906.

**Comment by elibarzilay** [comment]
@tarsius, thanks!  I'll try to update my environment soon and see how it works.

(I will surely run into it since the refs buffer is an extremely useful feature.)
