### ISSUE TITLE
How to set the default section show level in magit-status?

### ISSUE THREAD

**Issue by lukertty** [magit/magit#3023]
```elisp
(define-derived-mode magit-staging-mode magit-status-mode "Magit staging"
  "Mode for showing staged and unstaged changes."
  :group 'magit-status)

(defun magit-staging-refresh-buffer ()
  (magit-insert-section (status)
    (magit-insert-status-headers)
    (magit-insert-merge-log)
    (magit-insert-rebase-sequence)
    (magit-insert-am-sequence)
    (magit-insert-sequencer-sequence)
    (magit-insert-bisect-output)
    (magit-insert-bisect-rest)
    (magit-insert-bisect-log)
    (magit-insert-untracked-files)
    (magit-insert-unstaged-changes)
    (magit-insert-staged-changes)
    (magit-insert-stashes)
    (magit-insert-unpulled-from-upstream)
    (magit-insert-unpulled-from-pushremote)
    (magit-insert-unpushed-to-upstream)
    (magit-insert-unpushed-to-pushremote)
    ))

(defun magit-staging ()
  (interactive)
  (magit-mode-setup #'magit-staging-mode))
```

This code is copy from wiki, and I just want to run `magit-section-show-children` in `magit-staging` or `magit-status`, is there a way? 

Thx!

**Comment by kyleam** [comment]
Hmm, I'm confused about what you're trying to do here.  The code on
the wiki is much shorter and stems from #2219.  The main idea is to
_remove_ most of the sections that are included in the status buffer,
keeping only the sections for unstaged and staged changes.  But you
seem to be adding that back, so why not just use the status buffer?

> I just want to run magit-section-show-children in magit-staging or
> magit-status, is there a way?

The default visibility is controlled by the `HIDE` argument to
`magit-insert-section`.  Because you're calling
`magit-insert-unstaged-changes` and `magit-insert-staged-changes`
rather than using `magit-insert-section` directly, you can't change
the value of `HIDE`, but you can change
`magit-section-set-visibility-hook`.  For example

    (add-hook 'magit-section-set-visibility-hook
              (lambda (section)
                (and (memq (magit-section-type section) '(file))
                     'show)))



[By the way, we prefer GitHub issues to be limited to bug reports and
feature requests.  Please ask questions like these on one of the
channels suggested in the README.]

**Comment by kyleam** [comment]
> (memq (magit-section-type section) '(file))

I modified the hook directly from `magit-diff-expansion-threshold`,
which uses the above line, but it could also be written as
`(eq (magit-section-type section) 'file)`.
