### ISSUE TITLE
Magit commit may lose focus when jit-lock-defer-time is not null

### ISSUE THREAD

**Issue by lukertty** [magit/magit#3038]
This is the way to reproduce.

1. emacs -Q
2. paste these line to *scratch*

```elisp
(add-to-list 'load-path "/Users/lukertty/.emacs.d/elpa-25.2.1/git-commit-20170314.1414")
(add-to-list 'load-path "/Users/lukertty/.emacs.d/elpa-25.2.1/magit-20170329.221")
(add-to-list 'load-path "/Users/lukertty/.emacs.d/elpa-25.2.1/magit-popup-20170308.146")
(add-to-list 'load-path "/Users/lukertty/.emacs.d/elpa-25.2.1/dash-20170207.2056")
(add-to-list 'load-path "/Users/lukertty/.emacs.d/elpa-25.2.1/with-editor-20170111.609")

(require 'magit)

(setq jit-lock-defer-time 0.03)
```
3. M-x eval-buffer

4. M-x magit-status, type c c(If there is something staged), and it works right. And we go back to the *scratch*.
5. M-x eval-last-sexp this line again
```elisp
(setq jit-lock-defer-time 0.03)
```
6. M-x magit-status, type c c(If there is something staged), and the buffer we edit message have no highlight.
7. when we click the window or type anything, it highlight again.

This is a small gif.

![1](https://cloud.githubusercontent.com/assets/11374295/24491643/cc3c1a8e-155a-11e7-9c7e-148544f31ffc.gif)

I dont know why it need to eval twice, but if i put `(setq jit-lock-defer-time 0.03)
` to my init file, it happens every time.

* Emacs version 25.2.1
* System version OSX 10.11.6

Thx.

**Comment by tarsius** [comment]
I believe `jit-lock-mode` is an alternative `font-lock` implementation. After a quick look at the function (not command) `jit-lock-mode`, I am unsure how one is supposed to turn that mode on. The doc-string says one should "Enable it automatically by customizing group `font-lock`." I didn't find anything in that group or the `jit-lock` group that suggests that it is the nob one has to turn to enable it.

The code you present suggests that you think that setting `jit-lock-defer-time` is the way to do it. That might be correct or it is not correct and trying to do it like this is actually the cause of the issue you are seeing. Please locate some documentation that explains how one is supposed to enable `jit-lock` and post that here.

**Comment by lukertty** [comment]
I am unsure too..
I just removed the `jit-lock-defer-time` and everything works well..

I think this issue could be closed.

**Comment by johnmastro** [comment]
I was curious about this so I did a little reading. I also thought `jit-lock` was somehow an alternative to the normal `font-lock`, but it turns out it's actually [been the default since Emacs 21](https://www.gnu.org/software/emacs/manual/html_node/efaq/Turning-on-syntax-highlighting.html). I confirmed that it's still on by default in Emacs 25 and Emacs 26. It can be toggled by calling the `jit-lock-mode` function. Unlike most mode functions, `nil` disables it and any non-`nil` value enables it.

What's *not* on by default is `jit-lock`'s "deferred fontification" feature, where chunks of fontification may be "deferred" by running them on an idle timer. The value of `jit-lock-defer-time` is ultimately used as an argument to `run-with-idle-timer`. (Zero has a special meaning - "fontification is only deferred while there is input pending" - but it's presumably not relevant for this issue since the reporter used a non-zero value).

The "deferred fontification" feature is enabled by setting `jit-lock-defer-time` (there's no separate toggle variable/function).
