### ISSUE TITLE
Diff with magit-merge

### ISSUE THREAD

**Issue by rgtk** [magit/magit#3039]
`magit-commit` open two windows: one with diff another one for message. Same behavior for `magit-merge` would be insanely useful. I use magit to verify code from different branches which can be troublesome at times since I have to select popup item two times per each branch. This can be a pain if there are a lot of branches.

If `magit-merge` deliberately works different than `magit-commit`: would it be possible to preselect branch name for `magit-merge` if user is in diff buffer generated by `magit-merge`?

**Comment by tarsius** [comment]
At what time during the merge do you want to see the diff? You can already do so *before* initiating it using `m p`. If you want to do so while writing the commit message, then you have to use the merge variant that allows that, i.e `m e` instead of `m m`, *and* you then have to type `C-c C-d` to show the diff. I guess what you are asking for is that this last step would be made unnecessary.

**Comment by rgtk** [comment]
I would like to see diff when `m e` just like with `c c`. Doing `m p` and then `m m` requires to select desired branch from popup two times.

I think that showing diff by default would be the best since UI is very similar for commiting.

**Comment by tarsius** [comment]
> Doing `m p` and then `m m` requires to select desired branch from popup two times.

Yes, but I suggested a second alternative `m e` followed by `C-c C-d`, which does *not* require that.

> I think that showing diff by default would be the best since UI is very similar for commiting.

I tend to agree, but above I was just trying to make sure I understand what you are asking for and suggested a way of doing it in a slightly cumbersome way.

I believe to remember that there are other cases where the diff should/could be shown automatically while writing the commit message, but is not. I want to look into that too and ideally "fix" all those cases in one go. I'll look into this eventually but probably not very soon.

**Comment by tarsius** [comment]
> what I assumed you were asking for

Reading your apply again, I think I might have guessed wrong.

> Doing `m p` and then `m m` 

Since you didn't say "Doing `m p` and then `m e`" instead, I am not so sure anymore if you are asking for the diff to be shown while writing the commit message (because `m m` does not necessarily give you an opportunity to even edit the automatically generated message).

**Comment by tarsius** [comment]
Or put another way, do you want to see the diff so that you can (a) decide whether to merge (b) see whether there will be merge conflicts, or (c) so that you can summarize all changes without forgetting anything.

**Comment by rgtk** [comment]
I want to see diff to decide if I want to merge it. To do so, first I `m p` then `m m` which requires me to select target branch two times. Doing everything in one go would be fantastic. I see two alternative solutions for this: 
1. If `m m` was invoked in `*magit-merge-preview*` buffer, default prompt to currently previewed branch so user has to only confirm it with enter.
2. Show diff with `m m`.

**Comment by tarsius** [comment]
> If `m m` is invoked in `*magit-merge-preview*` buffer, default prompt to currently previewed branch so user has to only confirm it with enter.

I've implemented that.
