### ISSUE TITLE
FR: magit-file-checkout-previous

### ISSUE THREAD

**Issue by xged** [magit/magit#3052]
If I want to *checkout* previous commit of a current file, I have to (Spacemacs) `SPC SPC` `magit-file-checkout` & write `master~` & remember current number (range from master) & +1 & write it & <kbd>RET</kbd> & <kbd>RET</kbd>. 

Bonus if requested function would skip commits, which does not effect a file.

**Comment by tarsius** [comment]
If you invoke `magit-file-checkout` from a revision buffer, it is a bit more convenient:

1. View revision you want to reset to.
2. Move to file you want to reset.
3. `M-x magit-file-checkout RET RET RET`

An alternative approach could be:

1. You already know what revision you want to reset too, are in the file visiting buffer, and invoke `magit-file-checkout`.
2. Instead of prompting for a revision to be read in the minibuffer, that command uses a dialog similar to that used by `r F` (instant fixup). However the problem with that is, that you now can only select a revision that is reachable from `HEAD`.

**Comment by xged** [comment]
A better way: `SPC g f h` (`magit-log-buffer-file`) `j` (down) `SPC SPC` (`M-x`) `magit-file-checkout RET RET`.

**Comment by xged** [comment]
Maybe we could just assign key (`b f`) to `magit-file-checkout`?

**Comment by tarsius** [comment]
I think `X f` would be better suited. Even though `git checkout` is used both for branch switching as well as resetting files, what "checking out a single file" actually does is to reset a file to an earlier state (just like `git reset` does for the index, working tree, and/or all files).

**Comment by xged** [comment]
@tarsius Fine with me.

**Comment by tarsius** [comment]
Done. Thanks for the suggestion!
