### ISSUE TITLE
Guide fixup commits based on changed lines

### ISSUE THREAD

**Issue by DamienCassou** [magit/magit#3053]
After having changed a few lines in a file, I would like magit to guide me in fixing up to the right commit.

1. I create a commit A adding some code
1. I optionally do more commits after this one
1. I realize I did a mistake in commit A and fix it. Now I want to fixup this change into A.

I would like magit to help me fixup to commit A. This can for example be achieved by proposing a default commit when the log appears after `M-x magit-commit-fixup`.

**Comment by npostavs** [comment]
> This can for example be achieved by proposing a default commit when the log appears after `M-x magit-commit-fixup`.

But how would magit know which commit to propose?

**Comment by tarsius** [comment]
> after `M-x magit-commit-fixup`.

You can use `c f` for that. In most cases I would recommend the instant variant though, which is on `c F`.

> I would like magit to help me fixup to commit A. This can for example be achieved by proposing a default commit when the log appears after `M-x magit-commit-fixup`.

How is Magit supposed to know which commit you want to fix up? What it currently does is to place point on the same commit in the "log select" buffer as it was on in the status buffer (if any).

I suppose Magit could guess the default by checking what commits last touched the lines that now have additional staged changes. Is that what you had in mind?

> I realize I did a mistake in commit A and fix it. Now I want to fixup this change into A.

Just to be sure: by "fit it" you mean "make changes but don't yet commit them". Otherwise you are probably looking for the autosquash rebase variant (`r f`).

**Comment by tarsius** [comment]
So yeah, that's something I though about before too. But I am not sure how well that would work except in the most simple cases where every changed line was previously changed by the same previous and very recent commit.

Another likely case is something along the line of you changing the name of a function and forgetting to adjust a caller accordingly. When you then fix that caller, the "commit that last touched the lines with staged changes" is actually a very old commit. In that case it is preferable to start the "log select" buffer with point on `HEAD`.

We have to think of things like this, otherwise the default might very well end up being more annoying than helpful in many cases. Also what about the current behavior of placing point on the same commit as in the status buffer, that I mentioned earlier? Which of those defaults should take precedence?

**Comment by DamienCassou** [comment]
> But how would magit know which commit to propose?

By looking at which commit last changed the changed lines

> You can use c f for that. In most cases I would recommend the instant variant though, which is on c F

sure. I just thought the function name was clearer for a feature request / issue description

> I suppose Magit could guess the default by checking what commits last touched the lines that now have additional staged changes now.

exactly

> Just to be sure: by "fix it" you mean "make changes but don't yet commit them"

exactly (lines changed and staged).

> In that case it is preferable to start the "log select" buffer with point on HEAD

I guess there are plenty of cases where point on HEAD would be the best solution. E.g., if  you staged a lot of different lines in a lot of different files, it might be unreasonable to search for a commit to fixup to.

> Also what about the current behavior of placing point on the same commit as in the status buffer, that I mentioned earlier?

I have to admit Magit manages to read my mind just fine most of the times so I can't complain :-). For this particular case, I really don't know and trust you to do the right thing!

Thanks for Magit. It rocks.

**Comment by mgeisler** [comment]
This feature sounds very much like `hg absorb`: http://files.lihdd.net/hgabsorb-note.pdf. The command seems to be implemented [here][1].

[1]: https://bitbucket.org/facebook/hg-experimental/src/71664dec492f9f72a47dc0858e614fa275f2f6ad/hgext3rd/absorb/__init__.py?at=default&fileviewer=file-view-default#__init__.py-917

**Comment by tarsius** [comment]
I found two implementations for git:

* https://github.com/tummychow/git-absorb
* https://github.com/torbiak/git-autofixup, http://torbiak.com/post/autofixup/

and have implemented a command that uses the latter. In my limited testing so far it worked really well, so I have pushed it to `master`. It's still experimental though and I haven't added a key binding yet. Add it like this:

```lisp
  (magit-define-popup-action 'magit-commit-popup
    ?x "Absorb" 'magit-commit-absorb-popup)
```

`magit-commit-absorb-popup` is just a thin wrapper around `magit-commit-absorb`. If you invoke it without a prefix argument, then it just calls the latter.

Please give this a try. I might still give the other script a try or re-implement this in elisp, but as I said it seems to work really well, so I hope I won't have to do that.

One thing that is a bit odd (but understandable when you think about what it would entail to change it) is that `git-autofixup` operates on all unstaged changes and will abort if there are any staged changes.

**Comment by DamienCassou** [comment]
Thank you so much for implementing that. I just had a use-case and things worked perfectly. Thanks again.

I have some problems with it though:

1. when autofixup can't find any target commit, it doesn't do anything and magit won't tell us that something failed. Magit-process buffer shows success status (0):

    ```
      0 git … autofixup -vv b368b434f9
    some file @@ -202,6 +202,7 @@ has no targets
    ```

2. it's not obvious why pressing `c x` would ask me to select a commit in the log buffer. I thought the point of this command was to pick a commit for me automatically. Now I think I understand that autofixup wants a limit commit beyond which it won't try to fixup things to. I suggest that the limit commit is picked automatically by default by Magit and to add another action to the popup to let the user choose the limit commit herself. If that's not reasonable, I suggest to at least show a message explaining what the user must choose in the log buffer and why.

3. when the log buffer opened the first time, the point was on `origin/master` which made a lot of sense. When I tried again and the log buffer opened, the point was on the first line and I had to move the point manually to `origin/master` to make things work.

**Comment by torbiak** [comment]
After reading this thread again I realize I didn't really think about the git-autofixup use case of committing only the hunk being currently worked on instead of a whole batch of hunks at a time. I don't think this changes my thoughts on unassigned hunks being an error (see [git-autofixup#4](https://github.com/torbiak/git-autofixup/issues/4)), but it did make me think about how useful it'd be to limit git-autofixup to certain files or regions of files, although I didn't come to any conclusions.

**Comment by aspiers** [comment]
[**@tarsius**](https://github.com/tarsius) commented on [August 4, 2018 9:27 PM](https://github.com/magit/magit/issues/3053#issuecomment-410475533 "2018-08-04T20:27:18Z - Replied by Github Reply Comments"):
> I found two implementations for git:
> 
> *   [tummychow/git-absorb](https://github.com/tummychow/git-absorb)
> *   [torbiak/git-autofixup](https://github.com/torbiak/git-autofixup), [http://torbiak.com/post/autofixup](http://torbiak.com/post/autofixup/)

Late to the party here :-)  I only just found this issue, but I've also implemented a tool to do this ... or to be more accurate, I implemented a more general purpose tool and then implemented this use case as an after-thought:

This [use case of automatically creating fixup commits pointing to the correct ancestor](https://github.com/aspiers/git-deps/blob/master/USE-CASES.md#use-case-4-automatic-squashing-of-fixup-commits) is one of [several use cases](https://github.com/aspiers/git-deps/blob/master/USE-CASES.md) catered for by my commit dependency analysis tool [`git-deps`](https://github.com/aspiers/git-deps/).  The `git-deps` distribution ships with [`git-fixup`](https://github.com/aspiers/git-deps/blob/master/bin/git-fixup), a trivial wrapper around `git-deps` which implements the auto-fixup use case.  It would be very easy to rewrite this wrapper in elisp as a magit function.

Like the above-mentioned `git-autofixup` (and unlike `git-absorb`), the algorithm uses `blame` at its core.

Since the CLI interface to `git-deps` was designed to support non-interactive usage, I can see potential benefit for magit (or extensions thereof) implementing not just this but several other workflows based on `git-deps`.  Very happy to discuss more if this is of interest.

**Comment by tarsius** [comment]
@aspiers Sorry for never following up--just came across this by means of an old school bookmark. Unfortunately I don't have time to look into things like this now and for quite some time going forward. That doesn't mean I wouldn't be interested, but you would have to implement the elisp side too. Now trying to put the bookmark somewhere I will run into it again in a few months...

**Comment by aspiers** [comment]
No problem at all @tarsius, thanks a lot for the reply anyway. Maybe I will get around to scratching this itch at some point and hack up the elisp wrapper!

**Comment by tarsius** [comment]
> Now trying to put the bookmark somewhere I will run into it again in a few months...

Ah look, interesting bookmark! Adding it to `todo.org` instead...

**Comment by aspiers** [comment]
Happy to answer any questions you may have about git-deps, whenever you get around to looking at this!
