### ISSUE TITLE
Magit force-deletes branch after checking out master

### ISSUE THREAD

**Issue by phst** [magit/magit#3058]
To reproduce:
Check out a branch `a` that is not fully merged into master. From the status buffer, run `b k` (`magit-branch-delete`), and select the branch `a`. Magit will offer to check out master and delete (`c`); pick that option. Magit will then force-delete `a` (`git branch -D a`), even though it's unmerged, without further prompts. I think that's undesired; Magit should always prompt about deleting unmerged branches. I guess this behavior is caused by https://github.com/magit/magit/blame/master/lisp/magit-branch.el#L446.

**Comment by tarsius** [comment]
You are being asked two questions: `Delete unmerged branch foo? (y or n)` and then `Branch foo is checked out.  [d]etach HEAD & delete, [c]heckout master & delete, [a]bort`. I think that gives you enough opportunity to abort.

This assumes that `delete-unmerged-branch` isn't a member of `magit-no-confirm`, which by default it is. If you prefer having to answer with either `yes RET` or `no RET` (instead of just `y` or `n`), then you can get that behavior using `(add-to-list 'magit-slow-confirm 'delete-unmerged-branch)`.

**Comment by phst** [comment]
It doesn't ask the first question. To fully reproduce (version is Magit 2.10.3, Git 2.12.2, Emacs 25.1.1, darwin):

- `mkdir /tmp/magit`
- `cd /tmp/magit`
- `git init`
- `echo foo > a`
- `git add a`
- `git commit -m 'commit on master'`
- `git checkout -b b`
- `echo bar > b`
- `git add b`
- `git commit -m 'commit on branch'`

Then open Emacs with `-q`, load Magit, and run `magit-status` for `/tmp/magit`. Make sure branch `b` is still checked out.
From the status buffer, hit `b k` and select branch `b` to delete. Magit will *not* ask whether that unmerged branch should be deleted; after asking to check out master and delete it will do so, using `git branch -D b`.
This is because https://github.com/magit/magit/blob/master/lisp/magit-branch.el#L392 doesn't run `git branch --no-merged master`, but `git branch --no-merged`, i.e. it checks whether `b` has been fully merged into `b`, which is of course the case. Instead the `git branch --no-merged` check needs to be repeated after the user requested to check out master.

**Comment by tarsius** [comment]
Thanks for the analysis! For me it did ask because of `(magit-list-unmerged-to-upstream-branches)` and the testing branch's upstream was `master`. This isn't directly related to this issue, but I recommend that you set `branch.autoSetupMerge` to `always`, so that the upstream is automatically set when branching off a local branch.

But yes, I have to do something about this. Unfortunately I am quite busy and fear I won't get to it very soon. Also because this command does waaaay to much (see rant at beginning of the definition, this is by far the worst command in all of Magit), it will be quite difficult to fix this without making it even longer and more unreadable.

**Comment by tarsius** [comment]
Well, actually this would go a long way:

```lisp
(defun magit-merged-p (branch)
  "Return t if BRANCH is merged.
If BRANCH has an upstream check whether is merged into that.
Otherwise check whether it is merged into `HEAD`."
  ...)
```

**Comment by tarsius** [comment]
I haven't tested it yet, but https://github.com/magit/magit/compare/master...fix-3058 should do the trick.

**Comment by phst** [comment]
`magit-branch-merged-p` should check whether BRANCH is merged into master, not HEAD, shouldn't it?

**Comment by tarsius** [comment]
> `magit-branch-merged-p` should check whether BRANCH is merged into master, not HEAD, shouldn't it?

Doing the latter is consistent with what we did before and what `git branch -d` considers to be "merged":

```
-d, --delete
           Delete a branch. The branch must be fully merged in its upstream
           branch, or in HEAD if no upstream was set with --track or
           --set-upstream.
```

Also it doesn't really matter in this case.  After checking out `master`, `HEAD` and `master` point at the same commit.

That being said, that doesn't seem very safe if we start using `magit-branch-merged-p` elsewhere.  I have added a new commit that changes `magit-branch-merged-p` to check whether the branch is merged into the current branch, instead of `HEAD`.  I am undecided what we should do here.

> @kyleam asked whether we should do the same for the "detach HEAD" case as for the "checkout master" case.

In the same vain as above, this won't make a difference since `HEAD`, after detaching, points at the same commit that it previously pointed at indirectly (by pointing at a branch, which pointed at that commit).

I guess we won't know until someone who uses the "detach" case tells us.  But I think that if someone decides to use that case, then s/he is prepared to deal with dangling commits.

**Comment by kyleam** [comment]
0b36d6ff1dfb53155167adf64a2e7921e92f17fa:

> Git has no "is it merged into something appropriate command".
> The closest it gets to that is `git branch -d BRANCH', which checks
> whether BRANCH is merged either into its upstream or `HEAD'.  We
> depart from that and instead check whether BRANCH is merged into
> the current branch, because it does not seem safe to assume that
> commits that are reachable from the detached `HEAD' won't soon
> be dangling if not referenced elsewhere.

I'm not opposed to doing that, but I'd also be OK with saying if the
user is in a detached state, "then s/he should be prepared to deal
with dangling commits".

**Comment by tarsius** [comment]
I've made `magit-branch-merged-p` more flexible and am using it for the `detached` case too now. Please see #3069. That results in a bit of code duplication, which I don't really want to abstract away.

**Comment by phst** [comment]
Thanks!
