### ISSUE TITLE
Signature Removes magit-log Commit Messages

### ISSUE THREAD

**Issue by base698** [magit/magit#3060]
(1) If show signature is enabled in .gitconfig you can't see commit messages in magit-status for signed commits.  
  (2) the commit log message missing and instead shows 
```
gpg: Signature made Wed 03 May 2017 08:05:16 AM PDT
```
  (3) set .gitconfig showSignature = true and open magit status with a signed commit.

  M-x magit-version RET

```
Magit 20170425.638, Git 2.11.0, Emacs 25.1.1, gnu/linux
```

**Comment by kyleam** [comment]
Thanks for a report.

It looks like `log.showSignature=true` can lead to issues anywhere
`git log` or `git show` is called because it will prepend the
`--show-signature` output to any `--format` specification.  There
isn't a "don't show signature" flag to override this, although we
could add "-c" "log.showSignature=false" to each of these calls.  But
I think the best approach would be to just add "-c"
"log.showSignature=false" to `magit-git-global-arguments`.
