### ISSUE TITLE
ask to create new branch when typing non-existing branch in `b b` (checkout)

### ISSUE THREAD

**Issue by wbolster** [magit/magit#3104]
somehow i manage to use `b b` (checkout existing branch) quite often while i actually am trying to create a new branch. after typing the new branch name the command fails since there is no branch with that name (yet). i then have to do `b c` (create branch), and because the history for the prompt is not shared, i have to type the branch name again.

this happens to me more often than i would like. instead of aborting with an error, i think it would make sense to ask me "branch xyz does not exist, create it?" instead.

good idea?

**Comment by tarsius** [comment]
> good idea?

Let's say I have some reservations. But I will leave this open and decided at a later time.

**Comment by wbolster** [comment]
alternatively, why don't these "checkout branch" style inputs not share history? that would alleviate the problem as well.

**Comment by jsab** [comment]
This would be the same logic as elsewhere in emacs, switching buffer or opening a file for example.

**Comment by tarsius** [comment]
> alternatively, why don't these "checkout branch" style inputs share history? that would alleviate the problem as well.

Can you give an example of two prompts that should share history but don't. Many of these commands read two branches from the user; the name of an existing branch and a string to be used as the name of a yet to be created branch.

The "existing branch" prompts are supposed to share history across commands.

The "new branch" prompts read a string without any completion candidates or history. I have in the past considered doing providing this information, because that would save users from typing out common prefixes such as `feature/`. On the other hand if a prompt that's supposed to be used a name a new thing offered existing things as completion candidates, then that would make it more likely that the user would think that s/he is supposed to select an existing thing. I.e. I don't think it would be a good idea if the completion candidates consisted of a list of invalid inputs.

**Comment by tarsius** [comment]
Please give this a try:

```lisp
(defun magit-branch-or-checkout (arg &optional start-point)
  "Like `magit-checkout' or `magit-branch-and-checkout'.

Ask the user for an existing branch or revision.  If the user
input actually can be resolved as a branch or revision, then
check that out, just like `magit-checkout' would.

Otherwise create and checkout a new branch using the input as its
name.  Before doing so read the starting-point for the new branch.
This is similar to what `magit-branch-and-checkout' does."
  (interactive
   (let ((arg (magit-read-other-branch-or-commit "Checkout")))
     (list arg
           (and (not (magit-rev-verify-commit arg))
                (magit-read-starting-point
                 (format "Create and checkout branch %s starting at" arg))))))
  (when (string-match "\\`heads/\\(.+\\)" arg)
    (setq arg (match-string 1 arg)))
  (if start-point
      (magit-branch-and-checkout arg start-point (magit-branch-arguments))
    (magit-run-git "checkout" arg)))

(magit-remove-popup-key 'magit-branch-popup :action ?b)
(magit-define-popup-action 'magit-branch-popup
  ?b "CheckoutX" 'magit-branch-or-checkout
  'magit-branch t)
```

**Comment by jsab** [comment]
> Please give this a try:

Works exactly as expected. Very natural especially since I normally use `magit-branch-read-upstream-first nil`

**Comment by tarsius** [comment]
I've added the command to Magit, so you can remove the definition from your init file now. You still have to add to the popup yourself though.

**Comment by wbolster** [comment]
thanks!
