### ISSUE TITLE
magit-process buffer should visit <file path>:<line>:<column>

### ISSUE THREAD

**Issue by bryan-ash** [magit/magit#3105]
We use git hooks to run static code analysis prior to committing. If this fails, magit captures the output in the magit-process buffer, e.g.

```
[1mRunning pre-commit hooks[0m
Check YAML syntax........................................[YamlSyntax] [32mOK[0m
Analyzing with RuboCop......................................[RuboCop] [31mFAILED[0m
[1;31mErrors on modified lines:
/Users/bryan/code/spec/support/reports.rb:26:5: C: AlphabetizedMethods: Methods should be in alphabetical order.
Errors on lines you didn't modify:
/Users/bryan/code/spec/support/reports.rb:48:5: C: AlphabetizedMethods: Methods should be in alphabetical order.
```

It would be really nice if I could switch to that buffer, move to a failure line, and hit [Enter] to visit the failure point.

**Comment by tarsius** [comment]
I think you should implement that in your init file or as an independent package. I don't have the time to add support for custom git hook scripts. Also because the text you want to attach some functionality too isn't and cannot be a "magit section" such a command would have to simply act on the *text* at point. Therefore you don't need to know anything about how magit is implemented to create such a command. Creating a command that does this is easy. What is harder is to bind `RET` to it and then still have `RET` do "something else" when point is not on such text. If you want to avoid that, bind some other key to your command.

**Comment by johnmastro** [comment]
> Creating a command that does this is easy. What is harder is to bind RET to it and then still have RET do "something else" when point is not on such text. If you want to avoid that, bind some other key to your command.

Emac's [FFAP](https://www.gnu.org/software/emacs/manual/html_node/emacs/FFAP.html) package might be useful for this (either `find-file-at-point` directly or some of its helper functions like `ffap-file-at-point`).

**Comment by ahonnecke** [comment]
For future visitors, this doesn't integrate the failures into magit (which would be better), but functionally it performs pretty well:
https://github.com/ahonnecke/prelude/blob/ubuntu/personal/magit-bindings.el#L11-L67

When a hook fails, the failure shows up in magit-process, and this makes it open the magit-process buffer: https://github.com/ahonnecke/prelude/blob/ubuntu/personal/magit-bindings.el#L58-L63

Then this alters find file at point to parse line numbers:
https://github.com/ahonnecke/prelude/blob/ubuntu/personal/magit-bindings.el#L11-L56

This just binds return to the file opener to enter when in the magit-process buffer:
https://github.com/ahonnecke/prelude/blob/ubuntu/personal/magit-bindings.el#L65-L67
