### ISSUE TITLE
git rev-parse --symbolic-full-name doesn't behave as we expect

### ISSUE THREAD

**Issue by tarsius** [magit/magit#3106]
`git rev-parse --symbolic-full-name` only works on names of actual refs. It does not work on something like `NAME~1`. But the changes introduced in #3101 assume that the latter works too.

If you do this:

```shell
git init testibus
cd testibus
git commit --allow-empty -m "A"; A=$(git show --format=%H)
git commit --allow-empty -m "B"; B=$(git show --format=%H)
git commit --allow-empty -m "C"; C=$(git show --format=%H)
git update-ref refs/foo/refs/heads/master C
git reset --hard A
git commit --allow-empty -m "D"; D=$(git show --format=%H)
git log --oneline --graph --all
git name-rev --refs='refs/heads/*' $A
git name-rev --refs='refs/heads/*' $B
git name-rev --refs='refs/heads/*' $C
git name-rev --refs='refs/heads/*' $D
echo "A $(git rev-parse --symbolic-full-name $(git name-rev --name-only --refs='refs/heads/*' $A))"
echo "B $(git rev-parse --symbolic-full-name $(git name-rev --name-only --refs='refs/heads/*' $B))"
echo "C $(git rev-parse --symbolic-full-name $(git name-rev --name-only --refs='refs/heads/*' $C))"
echo "D $(git rev-parse --symbolic-full-name $(git name-rev --name-only --refs='refs/heads/*' $D))"
```

we get:

```
Initialized empty Git repository in /tmp/testibus/.git/
[master (root-commit) bbad412] A
[master aebdbd7] B
[master f6c44d9] C
HEAD is now at bbad412 A
[master 224554d] D
* f6c44d9 (tag: C, refs/foo/refs/heads/master) C
* aebdbd7 (tag: B) B
| * 224554d (HEAD -> master, tag: D) D
|/  
* bbad412 (tag: A) A
A master~1
B foo/refs/heads/master~1
C foo/refs/heads/master
D master
A 
B 
C refs/foo/refs/heads/master
D refs/heads/master
```

`magit-get-shortname` now returns:

* for `A` line: `heads/master-1` when `master-1` would have been unambiguous.
* for `B` line: `heads/refs/heads/master~1`, which is wrong and causes `magit-show-diff` to fail.

**Comment by tarsius** [comment]
This might be an appropriate fix, at least in the short run. But I haven't tested it yet:

```diff
diff --git a/lisp/magit-git.el b/lisp/magit-git.el
index 1b0cd0ac..fff2d265 100644
--- a/lisp/magit-git.el
+++ b/lisp/magit-git.el
@@ -849,16 +849,20 @@ (defun magit-name-tag (rev &optional lax)
          (substring it 5))))
 
 (defun magit-ref-fullname (name)
-  (magit-rev-parse "--symbolic-full-name" name))
+  (save-excursion
+    (string-match "\\`\\(.[^^~]\\)" name)
+    (magit-rev-parse "--symbolic-full-name" (match-string 1 name))))
 
 (defun magit-ref-ambiguous-p (name)
   (not (magit-ref-fullname name)))
 
 (cl-defun magit-ref-maybe-qualify (name &optional (prefix "heads/"))
   "If NAME is ambiguous, prepend PREFIX to it."
-  (concat (and (magit-ref-ambiguous-p name)
-               prefix)
-          name))
+  (save-excursion
+    (string-match "\\`\\(.[^^~]\\)" name)
+    (concat (and (magit-ref-ambiguous-p (match-string 1 name))
+                 prefix)
+            name)))
 
 (defun magit-ref-exists-p (ref)
   (magit-git-success "show-ref" "--verify" ref))
```

**Comment by kyleam** [comment]
Doh.  I'll find time tonight to look into it.

**Comment by kyleam** [comment]
> But the changes introduced in #3101 assume that the latter works too.

Yep.  Before #3101, the `magit-ref-fullname` call in
`magit-get-shortname` seems to be the only place that incorrectly
assumed this.  (This resulted in an unnecessary "tags/" prefix that
I've wondered about a few times in the past but never looked into.)

> magit-get-shortname now returns:

I'm assuming that, in both cases below, you've deleted the tags on
those commits.  Otherwise, aren't tags always given precedence by
`magit-get-shortname`?  (I see this before and after the #3101 merge).

> for A line: heads/master-1 when master-1 would have been unambiguous.

I think we should fix this by extending `magit-ref-ambiguous-p` to
strip revision suffixes, like in [km/fix-ambig-check].  I'm not sure
we should do anything with `magit-ref-fullname` because the remaining
callers use it to actually get the full refname and don't seem to pass
refs with suffixes.

[km/fix-ambig-check]: https://github.com/magit/magit/compare/km/fix-ambig-check

> for B line: heads/refs/heads/master~1, which is wrong and causes magit-show-diff to fail.

This particular case should be fixed with the km/fix-ambig-check
branch as well, but it points to another complication that was there
before #3101.  AFAICT the intention is for `magit-get-shortname` to
return refs in "refs/{tags/heads/remotes}/", so
"refs/foo/refs/heads/master" shouldn't be considered as a short name
for `REV`.  The reason it is is that the `--refs=refs/heads/*` matches
the middle part.  I don't see an easy what to anchor the pattern
("^refs/heads/*" doesn't work).  It's probably not worth doing
anything about because very few users will create non-standard
namespaces, and even fewer create one matching `*/refs/heads/*`.

**Comment by tarsius** [comment]
>> magit-get-shortname now returns:

> I'm assuming that, in both cases below, you've deleted the tags on those commits. 

Actually I did previously use shell variables instead of tags to store the commit hashes and after changing that I did not bother to rerun `magit-get-shortname` to see what would be returned. But yes. I have changed the script above.

**Comment by tarsius** [comment]
We probably should adjust `magit-ref-fullname` too. Future callers might pass refs with suffixes.

> The reason it is is that the --refs=refs/heads/* matches the middle part.  I don't see a way to anchor the pattern ("^refs/heads/*" doesn't work).

That's how the trouble began yes. I find this unfortunate but we have to live with it.

> AFAICT the intention is for magit-get-shortname to return refs in "refs/{tags/heads/remotes}/", so "refs/foo/refs/heads/master" shouldn't be considered as a short name for REV.

Yes.

> It's probably not worth doing anything about because very few users will create non-standard namespaces, and even fewer will create one matching */refs/heads/*.

Magit's very own "wip modes" do that. So I think we should explicitly filter out `refs/wip/*`.

**Comment by kyleam** [comment]
> We probably should adjust magit-ref-fullname too. Future callers might pass refs with suffixes.

OK.  I'll go that route instead.

> Magit's very own "wip modes" do that. So I think we should explicitly filter out refs/wip/*.

Good point.  I'll update the branch to do that.

**Comment by kyleam** [comment]
> I don't see a way to anchor the pattern ("^refs/heads/*" doesn't work).

Ah, but we can exclude `*/refs/heads/*` (6c8b7d5fd).

**Comment by tarsius** [comment]
Nice!
