### ISSUE TITLE
Support for unnamed remote URLs

### ISSUE THREAD

**Issue by njsmith** [magit/magit#3116]
The github `hub` command has a neat feature to make it easy to review and modify pull requests. You can run, say, `hub pr checkout 3115`, and it will create a local branch containing the contents of PR #3115. (You need the [latest prerelease](https://github.com/github/hub/releases) for this syntax to work, but something similar can be done with `hub checkout` in older releases.) And if that PR is coming from a branch named BRANCHNAME in SUBMITTER's fork, then it sets up `.git/config` like:
```
[branch "SUBMITTER-BRANCHNAME"]
        remote = git@github.com:SUBMITTER/magit.git
        merge = refs/heads/BRANCHNAME
```

If I then hit F in magit, it offers:
```
Pull into SUBMITTER-BRANCHNAME from
 p origin/SUBMITTER-BRANCHNAME
 u git@github.com:SUBMITTER/PROJECT.git/BRANCHNAME
 e elsewhere
```
so it seems like hitting `u` is just what you'd want to pull down any updates that have been made to the original PR branch.

And if I hit P in magit, it offers:
```
Push SUBMITTER-BRANCHNAME to
 p origin/SUBMITTER-BRANCHNAME
 u git@github.com:SUBMITTER/PROJECT.git/BRANCHNAME
 e elsewhere
```
so it seems like hitting `u` is just what you'd want to push up any changes you've made back to this PR. (Github now allows this by default! So if you see a trivial typo or something you can just fix it instead of having to post a comment asking the original submitter to fix it! It's really slick, except...)

If I actually hit `u` on either of these screens, though, then magit says:
```
magit-split-branch-name: Invalid branch name git@github.com:SUBMITTER/PROJECT.git/BRANCHNAME
```

It would be really really nice if pushing and pulling to this kind of remote – that's specified as a bare URL rather than a remote name – could Just Work from magit. (AFAICT git itself handles them fine.)

PS: thanks for magit, it's amazing.

**Comment by tarsius** [comment]
An early draft is in https://github.com/magit/magit/tree/fix-3116, but this still needs some work.

**Comment by tarsius** [comment]
I have just pushed a fix for the issues you mentioned. There might be other similar issues that have not been discovered yet, because I was not aware that the use of an url as `branch.<name>.remote` was possible.

I have only fixed this for compatibility with a work-flow that `git` allows, but I would recommend against actually using this feature. If you do this, then some information that would be available if a named remote was used is missing. For example Magit can then not show "Unpushed to {upstream}" and "Unpulled from {upstream}" if you use an url.

I have taken this as an opportunity to finally improve `magit-branch-pull-request` in the `magit-rockstar` package (in the `setup-pr-branch` branch for now). I plan to eventually move that info Magit itself, but it still needs a lot of testing and some work. The current implementation is quite nice I think, and already handles many different cases. But most of them have not been tested yet.

**Comment by nex3** [comment]
> I have only fixed this for compatibility with a work-flow that git allows, but I would recommend against actually using this feature. If you do this, then some information that would be available if a named remote was used is missing. For example Magit can then not show "Unpushed to {upstream}" and "Unpulled from {upstream}" if you use an url.

In the `hub` case, I think it makes sense. The choice is between either creating a new named remote for each pull request from a new contributor and using a URL,. The former is likely to pollute the repo with a bunch of outdated remotes which were only used for one PR, which makes tab-completion and various other features less usable.

**Comment by tarsius** [comment]
> The choice is between either creating a new named remote for each pull request from a new contributor and using a URL

I've implemented both approaches yesterday :wink:

> The former is likely to pollute the repo with a bunch of outdated remotes which were only used for one PR, which makes tab-completion and various other features less usable.

I think the benefits of the former far outweigh its drawbacks. Especially because to drawbacks can be mitigated to a large extend.

1. Clone just the needed branch (`git remote add -f --no-tags -t BRANCH NAME URL`) and when another pr by the same person already exists, then just add a new refspec (`remote set-branches --add REMOTE BRANCH`). `magit-branch-pull-request` already does that and more, so see the definition (it probably still contains bugs such as unhandled cases, I just drafted it yesterday).

2. Special care has to be taken when deleting a "pull-request branch". In the case of Magit that would happen in `magit-branch-delete` (which I haven't done yet, because `magit-branch-pull-request` itself isn't part of Magit yet).

Not sure how hard it would be to do (2) in `hub`. One basically has to wrap `git branch -d`, in order to also `git remote remove` when appropriate. When there are more branched pull-requests from the same person, then only remove the appropriate refspecs. 

So all in all, I think this is quite doable, at least in Magit.

Ps: I also plan to implement something like `magit-merge-absorb`, which merges a feature branch (pr branch or not), and then also deletes the merged branch locally and on the remote - and in case of).
