### ISSUE TITLE
Pressing return in wip-log doesn't always work

### ISSUE THREAD

**Issue by alex-rozenshteyn** [magit/magit#3120]
To reproduce:
1. Turn on a wip mode
2. Make changes so there is a wip branch with at least two commits
3. `magit-wip-log-current`
4. Navigate to a wip commit that is not the tip of the wip branch
5. `RET`

Expected: magit shows the commit
Got: minibuffer displays `heads/wip/index/refs/heads/my-branch~1 is not a commit`

If I explicitly put the hash in, everything works as I expect, so I'm guessing the issue is that the way magit constructs the revision name doesn't work for wip commits.

Magit version:
```
Magit 20170609.2322, Git 2.12.2, Emacs 25.1.1, darwin
```
Note, I'm running spacemacs and evil-magit.

**Comment by kyleam** [comment]
Thanks.  There has been some recent work in this area: #3101, #3109,
and (the still open) #3119.  Based on your reported version and the
error, I think you're using a Magit version that is after #3101 but
before the others.

Anyway, I believe (without confirming by testing) that 9ab6d5548 (from
#3109) would have fixed this, but that commit was reverted because it
relied on a Git flag that was only recently introduced.  A new
approached has been proposed in #3119 and should fix this.

**Comment by kyleam** [comment]
> I believe (without confirming by testing) that [...]

Just tested.  Actually, #3119 isn't need in this case.  Your issue
should already be fixed as of 8548d2017 (#3108), so please update to
the latest version on MELPA.
