### ISSUE TITLE
Find all string (pattern) occurrences in all the diffs of a git repository?

### ISSUE THREAD

**Issue by xged** [magit/magit#3129]
I believe `=S` or `=G` option in magit-log used to do it somewhat, but now they only filter the commits.

**Comment by kyleam** [comment]
Can you provide more details about what you expect to see when you use
`=S` and `=G` in the log popup?

> but now they only filter the commits.

These match the commits shown by `git log --online -G/-S`.  Are you
looking for the diffs inline (`-u` in the log popup)?

**Comment by xged** [comment]
I want to get a list of lines of diffs matching the pattern (think helm or ivy-counsel). I am likely having wrong memories of what those options used to do seeing that they match original git behaviour.

**Comment by kyleam** [comment]
I still don't have a clear picture of what you're after (e.g., where
do you want to end up once you've selected a line?), but I don't think
anything that accomplishes what you want has existed in Magit.

As to whether Magit should have such a feature, I don't have a strong
opinion because I don't really understand the use case.  Instead, you
could implement a custom helm or ivy-counsel command that either a)
works on the magit log buffer or b) is fed the lines of interest, if
you can produce the lines you want with a git command.

An example of the first option: If you wanted to use `helm-swoop` in a
log buffer created with "l -u =Gpattern a", you could avoid needing to
retype the pattern in `helm-swoop`'s prompt by creating a variant
that extracts the pattern from `magit-refresh-args` in the log buffer
and passes it to a `helm-swoop` call.

**Comment by xged** [comment]
> where do you want to end up once you've selected a line

In *magit-revision* at the corresponding line in diff.

**Comment by tarsius** [comment]
Closing in favor of #3130.
