### ISSUE TITLE
"core.commentChar auto" setting not respected

### ISSUE THREAD

**Issue by Deewiant** [magit/magit#3138]
Just something I noticed. As per `git-config(1)`, `core.commentChar` has a magical "auto" setting:

> If set to "auto", git-commit would select a character that is not the beginning character of any line in existing commit messages.

(Note that by "existing commit messages", it means "the commit message to be edited", i.e. when there is already a non-empty commit message to begin with.)

Magit instead treats the comment starter as the string `auto`.

To be fair, with the ability to set `commit.status` to false I have no idea how Magit even could guess what the actual comment character is, unless peeking into `git`'s source code and copying the algorithm from there is acceptable.

```
Magit 20170729.2104, Git 2.13.3, Emacs 25.2.1, gnu/linux
```

**Comment by tarsius** [comment]
> (Note that by "existing commit messages", it means "the commit message to be edited", i.e. when there is already a non-empty commit message to begin with.)

So it is only really useful when editing messages of existing commits *and* makes it impossible to at the same time specify the character to be used when writing *new* messages. I assume git just falls back to the default of `#`.

> Magit instead treats the comment starter as the string `auto`.

That's a bug but I am not sure it can be fixed. My initial impulse was to just fall back to `#`, but while that would make the buffer look better, that would actually be misleading.

---

I suspect you started looking into this because you want to write messages like:

```
Do stuff

Do stuff for good reasons. Do stuff for good reasons. Do stuff for good reasons. Also see
#1234 for more information.
```

I sometimes end up with messages like this too due to Emacs automatically wrapping lines and deal with it by manually adding a line break:

```
Do stuff

Do stuff for good reasons. Do stuff for good reasons. Do stuff for good reasons.
Also see #1234 for more information.
```

> To be fair, with the ability to set `commit.status` to false I have no idea how Magit even could guess what the actual comment character is, unless peeking into `git`'s source code and copying the algorithm from there is acceptable.

Looking at the git code would not help much because it must be doing something like:

1. Look at the commit message to determine an unused character.
2. Add instructions to the commit message, using that character to comment it out.

Magit does not have a change to look at them message from (1), it always gets the result of (2). We could use a list of strings that appear in comments git adds when asking for a message. That list would never be complete and would have to be adjusted for each "as user for message" task, for each language git has been translated too, and each git version magit still supports.

We could also use the "opposite" of the algorithm used by git: the character that is at the beginning of the *most* lines is (probably) the comment character. But that would fail too sometimes, maybe even regularly.

So I think the best option is to not do anything. This causes the font-locking to be wrong, but that is a *good* think as it tells users that something is off, so they might check the message after confirming the commit and notice if git did swallow any lines and/or did not remove comments.

**Comment by Deewiant** [comment]
> So it is only really useful when editing messages of existing commits and makes it impossible to at the same time specify the character to be used when writing new messages. I assume git just falls back to the default of #.

This might also come up with commit message templates (`git config commit.template` a.k.a. `git commit -t`) but in any case it must be an extremely fringe use-case. I'd never heard of this before today. And yes, `git` seems to use `#` by default.

> Magit does not get a change to look at the message from (1), it always gets the result of (2). We could use a list of strings that appear in comments git adds when asking for a message. That list would never be complete and would have to contain entries for each "ask user for message" task, for each language git has been translated too, and each git version magit still supports.
>
> We could also use the "opposite" of the algorithm used by git: the character that is at the beginning of the most lines is (probably) the comment character. But that would fail too sometimes, maybe even regularly.

Yeah, I was thinking of the "list of strings" approach as well as that "opposite" algorithm, but having `commit.status false` is a guaranteed failure for both. (But then, that is probably also an extremely esoteric setting...) You're right that localization and version-related changes makes this even worse, though.

I thought Magit could in most cases see the (1), though it might be a lot of work. I mean, in all of the following cases you can see the original message:

case | location of original message
---- | ---------------------------------
`commit --amend` | `HEAD`
merge conflict during rebase | the original commit (next one in todo? I forget how to get at it programmatically)
fixup or squash during rebase |  the original commit (available in the todo list at the start)
cherry-pick | the named commit
templated commit | the template

There may be other cases but it doesn't strike me as impossible. Most likely impractical though.

> So I think the best option is to not do anything. This causes the font-locking to be wrong, but that is a good think as it tells users that something is off, so they might check the message after confirming the commit and notice if git did swallow any lines and/or did not remove comments.

Perhaps it's worth documenting or somehow warning that the "auto" setting is not supported? I agree that having the font-locking be off might be a good enough indicator.

---

Regarding use cases for this and #3137, yes, that's one. Of course it can be worked around, but it's annoying e.g. when `M-q` changes the semantics of what you wrote. It also sometimes comes up in commit summaries, e.g. the common "reference to issue tracker" practice as in `#ID: do stuff`. I suppose most people work around this by writing `(#ID) do stuff` or similar instead, but to me it wastes a column and doesn't read any better.

**Comment by tarsius** [comment]
For me that is pretty low priority, but I will keep these issues open. Maybe one day I will get to it :wink:

You have already though about this quite a bit, so maybe you want to implement something?

**Comment by Deewiant** [comment]
Sorry, it's not important enough for me either to sacrifice my time to that extent... I can live with the incorrect highlighting in #3137 and this one is not even a use case of mine, just a curio.

**Comment by tarsius** [comment]
Closing now. I have added the `wontfix` label, so there still is a slight change I will do something about this when I do another "let's reconsider some old decisions round".
