### ISSUE TITLE
do not collapse recent commits in magit-insert-unpulled-from-upstream-or-recent

### ISSUE THREAD

**Issue by wbolster** [magit/magit#3147]
magit enables me to see recent commits in case my code is in sync with upstream using `magit-insert-unpulled-from-upstream-or-recent` (why is this not the default? it's great):

``` elisp
  (magit-add-section-hook
   'magit-status-sections-hook
   'magit-insert-unpulled-from-upstream-or-recent
   'magit-insert-unpulled-from-upstream)
  (remove-hook
   'magit-status-sections-hook
   'magit-insert-unpulled-from-upstream)
```

but `magit-insert-unpulled-from-upstream-or-recent` will unconditionally collapse (the `t` below) the section:

``` elisp
        (magit-insert-recent-commits t)
```

i would like the section to _not_ be collapsed, so that `magit-status` becomes more useful to get a quick overview. especially in combination with `magithub` (list of prs) this makes magit a very useful "project dashboard" for everyday use.

would it be possible to make the collapsing optional? (or changing the defaults.)

**Comment by tarsius** [comment]
> magit enables me to see recent commits in case my code is in sync with upstream using `magit-insert-unpulled-from-upstream-or-recent` (why is this not the default? it's great):

I am using that too and we could show it by default. What do others think?

Meanwhile should use this to add it to the hook:

```lisp
  (magit-add-section-hook 'magit-status-sections-hook
                          'magit-insert-unpulled-from-upstream-or-recent
                          'magit-insert-unpulled-from-upstream
                          'replace)
```

> i would like the section to _not_ be collapsed

There should be a generalized mechanism for that sort of setting, see #2780.

**Comment by kyleam** [comment]
> I am using that too and we could show it by default. What do others think?

fine by me

**Comment by tarsius** [comment]
That should work now. Note that you no longer have to add `magit-insert-unpulled-from-upstream-or-recent` to the hook. The new `magit-insert-unpushed-to-upstream-or-recent` is now on there by default.

**Comment by wbolster** [comment]
thanks @tarsius!

**Comment by cavd** [comment]
How do we get the old behavior back. This is way too noisy to be useful.

**Comment by tarsius** [comment]
> How do we get the old behavior back.

See #3230.

**Comment by wbolster** [comment]
hey @cavd, do you always just stumble in and start complaining about something without a hint of friendliness? remember that you are _not_ entitled to anything yet you behave like you do. your negative wording is not doing any good. such behaviour drains volunteers' energy, for no reason.

**Comment by tarsius** [comment]
@wbolster While I do appreciate it when other users tell an actor that s/he is being persistently unreasonable, entitled or offensive--it helps to you know when that you as the maintainer are not the only one who feels that way and to always have to be the one who says "stop it"--I also feel like @cavd behavior was still okay.

Sure, wouldn't have hurt to be a little bit friendlier, as in "This feels way too noisy to be useful to me. Please let me know how to get the old behavior back. I searched but couldn't find anything", but one could also say that the used wording falls into the category "brief and to the point".

I can deal with that. What I really have difficulties grasping, and therefore need some help with, is when someone outright refuses to see the other side of the argument. The most troubling part of that is that such people usually accuse the other side of doing exactly what they themselves are doing, and that they apparently are not capable of seeing that.

**Comment by jacksonrayhamilton** [comment]
I agree that it's noisy and would prefer the old behavior.

I've been trained to think "I need to push stuff now" when I see a long list of commits in the status buffer.  Now, I always see an arbitrarily long list of commits.  If I wanted to see any amount of past commits, I would look at the log.

**Comment by tarsius** [comment]
@jacksonrayhamilton So what's your point? That the default should be changed again? Or are you just explaining why someone might prefer the old default of not showing "Recent commits"?

**Comment by jacksonrayhamilton** [comment]
I'd like the default to be changed back.

**Comment by jacksonrayhamilton** [comment]
Behind that "training" is an expectation for lists of commits in the status buffer to continue to have a single meaning rather than multiple meanings; i.e., for Magit to be simpler.

> I have made it the default now because I have made the change this issue originally was about, changed from "unpulled or recent" to the much more reasonable "unpushed or recent", and also made sure that changing the visibility state of "unpushed" affects that of "recent" and vice-versa.

This doesn't make sense.  What does "recent" even mean?  (I'd like to know, but this is also a rhetorical question because "recent" is a nebulous term.)  And, I've always seen "unpulled" _and_ "unpushed" commits in the status buffer, so I don't understand what you mean by "changed from."

**Comment by tarsius** [comment]
> What does "recent" even mean?

It means "leading up to HEAD", i.e. `HEAD` itself, `HEAD~`, `HEAD~2`, `HEAD~3`... but not `HEAD~100`. If you know a better, short word for that then let me know.

> I've always seen "unpulled" and "unpushed" commits in the status buffer

When there actually are unpulled and unpushed changes, that is. The only thing that changed is that when there are no unpushed changes (which is a subset of recent changes), then the status buffer now features a another section containing N (where N is a customizable number) recent changes instead of only those of the recent changes that have not been pushed yet.

The first implementation that allowed users to display N recent commits was `magit-insert-recent-commits`. That function always inserted that list and some users noticed that this was, for the most part redundant because when there actually are unpushed changes, then the "unpushed" section also listed recent changes.

For some odd reason I created `magit-insert-unpulled-from-upstream-or-recent`. I think that was a bug so I have now replaced that with `magit-insert-unpushed-to-upstream-or-recent`. That's what I meant by:

> changed from "unpulled or recent" to the much more reasonable "unpushed or recent"

I removed the function `magit-insert-unpulled-from-upstream-or-recent` and instead added the function `magit-insert-unpushed-to-upstream-or-recent`.

> Behind that "training" is an expectation for lists of commits in the status buffer to continue to have a single meaning rather than multiple meanings

Nothing has changed with regards to that. The "unpushed" section still always only lists unpushed commits. But when there are no unpushed changes, then N recent changes are now shown. Some people find that useful, you obviously don't. The fact that this is implemented using a single function `magit-insert-unpushed-to-upstream-or-recent` is an implementation detail.

Full discloser: As mentioned before the "unpushed"  and "recent" sections share the visibility state. You could argue that this make my earlier statement that these are two independent sections untrue. But really this is just an optimization that is useful to people who want to see N recent changes when there are no unpushed changes. Since you are not one of them it should not matter to you.

**Comment by jacksonrayhamilton** [comment]
> In this context it means "leading up to HEAD" . . .

What is the subject of the sentence "leading up to HEAD?"  Is the subject "N commits" leading up to HEAD?  I have checked out different branches in different repos and the number of commits in the "recent" list is always different, and the set of commits shown doesn't follow any pattern I can discern.

**Comment by tarsius** [comment]
> What does "recent" even mean?

>> In this context it means "leading up to HEAD"

It's an answer to your question. "It" reverse to "recent". I.e. I explain what the word "recent" means in this context. An other way of saying it would be "'recent commits' refers to the last few commits on the current branch".

Are you trolling me?

> I have checked out different branches in different repos and the number of commits in the "recent" list is always different,

The variable `magit-log-section-commit-count` controls how many commits we **try** to display. Obviously if there are fewer commits than that, then we cannot display that many commits. We use the value of that variable as the N in `git log -n N ...`. If there are merge commit in the range `HEAD~N..HEAD`, then that git command may display *more* commits in order to produce a meaningful history.

**Comment by jacksonrayhamilton** [comment]
> Are you trolling me?

No, I was confused by your definition of "recent."

I should have been more specific:  What I precisely meant to ask was "what does 'recent [commits]'" even mean, i.e. the phrase "recent commits," not the adjective "recent."  Hence why I was looking for a subject in the sentence "leading up to HEAD," e.g. "the last 10 commits leading up to HEAD."

I needed to know which commits were being displayed before I could attempt to appreciate this new default.  Now I know that the commits being displayed are "up to the last 10 commits, or more according to some magic Git algorithm," which confirms to me that this is indeed totally random and therefore useless noise.

**Comment by manuel-uberti** [comment]
Sorry to chime in in a closed issue.

I like the new behaviour, just wish `Unpulled from origin/master` could be collapsed like `Unmerged into origin/master` the first time I open `magit-status`.

**Comment by tarsius** [comment]
> Now I know that the commits being displayed are "up to the last 10 commits, or more according to some magic Git algorithm," which confirms to me that this is indeed totally random and therefore useless noise.

Actually that was just some unfounded speculation on my part. The reason why more commits were being displayed in some cases was a bug in Magit. That's fixed now.

**Comment by tarsius** [comment]
@manuel-uberti I am also not quite happy with which the default visibility states of the various log sections. There likely will be improvements in the future. For now I leave it as is in order to learn what annoys me the most ;-)

**Comment by manuel-uberti** [comment]
@tarsius take your time, of course. It's already helpful as it is. :-)

**Comment by jacksonrayhamilton** [comment]
> Actually that was just some unfounded speculation on my part. The reason why more commits were being displayed in some cases was a bug in Magit. That's fixed now.

I just updated to Magit 20171116.649 and in the `magit-status` buffer for my [context-coloring repo](https://github.com/jacksonrayhamilton/context-coloring/), I see 20 commits under "Recent commits" even though `magit-log-section-commit-count` is 10.

**Comment by tarsius** [comment]
That's probably because Melpa usually takes a few hours to build a new package.

**Comment by npostavs** [comment]
I think you need to wait for  20171116.1736 or higher (assuming melpa timestamps are UTC?).
https://github.com/magit/magit/commit/2434db54fd23dc07c466cc312cecdc15c5df8865.patch

**Comment by jacksonrayhamilton** [comment]
Yep, it just shows up to 10 commits now.

Allow me to explain in a little more detail why I think this "recent commits" feature is bad and should be turned off by default.

Even with this fix to ensure that the cap is actually N, this still feels like an arbitrary sample from a very large pool of information.  With "Head:", "Push:" and "Tag:", these are all single data points.  With "Unpulled:" and "Unpushed:", these include _all_ commits needing to be pulled or pushed.  But with "recent commits," only _some_ commits are shown.

Some of the commits in this set might be interesting.  There may be more commits which are also interesting, yet are obscured.  The usefulness is based on a guess for the range of commits that might include useful information but won't be so long as to obscure other information at-a-glance.  Eventually, that guess will be wrong.  The usefulness is _luck-based_.  When the user is unlucky, he will need to resort to a "fallback" function, which is `magit-log`.  It's weird to refer to `magit-log` as a "fallback," since it is only an `l-l` away.  But because of the dichotomy produced by this feature, typing `l-l` has become a "regrettable disruption" since just staring at the status buffer wasn't sufficient for obtaining commit information.

Magit would be simpler from a use perspective without this special shortcut, because the user would not have two ways of seeing commits.  Instead, he would only have one, and that one way would be the most generalized way.  It would most optimal for his muscles to automatically refer him to this guaranteed-useful screen when he required commit information.

**Comment by kyleam** [comment]
> Allow me to explain in a little more detail why I think this "recent commits" feature is bad and should be turned off by default.

Other users find something useful that you (and I) don't.  I have no
idea what that split looks like across all Magit users.  I doubt many
users will say "I'm really confused about what recent commits are and
now the whole Magit interface seems too complicated", but perhaps many
will say "I don't want to see these".  Not knowing what the split is,
I'm for enabling it by default because I think there's a good chance
that many users will find it useful but wouldn't have discovered it
otherwise.

**Comment by jacksonrayhamilton** [comment]
> I doubt many users will say "I'm really confused about what recent commits are and now the whole Magit interface seems too complicated", but perhaps many will say "I don't want to see these". .

Since the problem I've described is a subliminal UX problem, I think fewer people will identify precisely why it becomes annoying.  Hence why a better default should be chosen.

> Not knowing what the split is, I'm for enabling it by default because I think there's a good chance
that many users will find it useful but wouldn't have discovered it otherwise.

I disagree.  A bad feature won't be made good by enabling it by default.  That sounds more like a tactic to try to justify a feature's existence.

**Comment by kyleam** [comment]
> Since the problem I've described is a subliminal UX problem

I don't agree that it is a problem.  It's a preference that varies
among users.

> I disagree. A bad feature won't be made good by enabling it by default.

That assumes that I think it's a bad feature, which I don't.  Many
users seem to find it useful, and I don't think there is anything
inherently bad or problematic about showing recent commits.

> That sounds more like a tactic to try to justify a feature's existence.

Its existence is justified by a subset of users finding it useful.

**Comment by jacksonrayhamilton** [comment]
> I don't agree that it is a problem. It's a preference that varies among users.

To convince me that this is not a problem, you would have to argue that the "dichotomy" I described [here](https://github.com/magit/magit/issues/3147#issuecomment-345181378) is mostly irrelevant.  Since the usefulness of the feature is random, I don't think that argument can be made.  This leads me to assume that there will always be some disruption coupled with what usefulness this brings.  If there is any disadvantage to a feature, then I am suspicious of having it on by default.

**Comment by MatthewFluet** [comment]
Not sure if this closed issue is the right place to continue this discussion, but I'm a user who finds the Recent Commits a helpful default.  I often keep a local branch synchronized with its merge and push remotes (so Unpushed and Unpulled logs are empty), so Recent Commits is a convenient way to remember where I left off in a development when I start the next day (or, more often, days later).  I also find it useful when staging/committing individual hunks (i.e., breaking up a large edit into individual commits), where Recent Commits is a convenient way to see what has already been done.  I also have build artifacts archived by commit hashes, so Recent Commits (which shows hashes) is convenient for cross-referencing.

@jacksonrayhamilton does have a point that Unpushed and Unpulled logs are (almost always) complete logs while Recent Commits is (almost always) truncated, and that distinction is not visualized.  Note that, with magit's defaults, the Unpushed and Unpulled logs are truncated at 256 items, which probably rarely results in truncation, but could happen.

It might be nice if a `magit-log-section` indicated if the log had been truncated and if `magit-log-section-commit-count` (or a new customizable variable) would limit Unpushed and Unpulled log sections.
