### ISSUE TITLE
Enable ediff to view the changed files one after the other without having to return to the status window first

### ISSUE THREAD

**Issue by vonHabsi** [magit/magit#3164]
Currently with ediff when you use the `n` key to move through the changes and get to the last diff, you have to `q`uit the diff  to return to the status window, before selecting the next changed file to diff it.

It will be better to have the option of moving to the next changed file in the list automatically, either by pressing the `n` key on the last diff, or by having a separate command to skip on to the next file even if you haven't reached the end of the current file.

**Comment by mickvangelderen** [comment]
I was looking into if it is possible for magit to show side by side diffs in things like git status or when viewing a particular commit. From my quick search it seemed viewing the file changes with ediff was the solution. After trying out ediff I quickly found myself wishing for this exact functionality.

**Comment by tarsius** [comment]
If someone else would like to implement this: `ediff-mult.el`'s commentary explains what you have to do.

**Comment by tarsius** [comment]
> If someone else would like to implement this: `ediff-mult.el`'s commentary explains what you have to do.

I looked into this a few months ago. Implementing something using this abstraction wouldn't be useful. It would allow avoiding having to go back to Magit's status buffer, but instead one would now have to go back to another ediff "control buffer" which is much less useful than Magit's status buffer. So a lot of work to make things worse.

I don't have any plans to implement this myself anytime soon, if ever, because I almost never use Ediff (basically only when someone asks me to implement a feature). So I am closing this.

Quite a few users have given this their thumbs up but unfortunately nobody volunteered to help implementing this. I would still be interested in adding such a feature to Magit, but somebody else has to do it.

**Comment by hgranthorner** [comment]
Sorry to necro this, happy to open a new discussion/issue if you prefer - I've hacked together something that mostly fits the bill here that I've been using at work for a bit for PR reviews. Would you still be interested in a contribution?

**Comment by tarsius** [comment]
Open a pull-request. I probably won't find the time to review it any time soon, but should get around to it eventually. Even if it sits on a feature branch for a while, others who are interested in such functionality could give it spin and provide feedback.

**Comment by hgranthorner** [comment]
Great, I'll try to find some time this weekend to polish it up and make a PR.
