### ISSUE TITLE
Allow setting relevant variables from remote popup

### ISSUE THREAD

**Issue by drrlvn** [magit/magit#3165]
Using `magit-remote-set-url` (`M`, `u`) changes only the `url` field in the git config but does not change the `pushurl` when it is specified.

**Comment by kyleam** [comment]
Why do you expect it to?  I think `pushurl` exists for cases when the
user wants to set it to something other than `url`, so we wouldn't
want to set both of them for a command supposed to set `url`.

`magit-remote-set-url` corresponds directly to `git remote set-url <r> <u>`.
We could add a `magit-remote-set-pushurl` command for
`git remote set-url --push <r> <u>` (or add `--push` as a switch if we
don't mind another "Switches for ..." section), though I'm not sure
how many users set `pushurl`s.

**Comment by drrlvn** [comment]
A `--push` flag like you suggested sounds like the best option.

**Comment by tarsius** [comment]
I was thinking something along the line of showing (and allowing to edit) relevant variables in the remote popup like we do in the branch popup.

**Comment by kyleam** [comment]
@tarsius That'd be a better direction.

The command and switch route have the issue that once you allow
setting the pushurl, you should also allow deleting it, so you'd need
more commands/switches.

In addition, the switch route has the issue that, since `-f` is
activated by default, splitting the switches into "Switches for ..."
doesn't work well here because <kbd>Mu</kbd> would give an error
unless the user remembered to switch it off for that call.  (Of course
the few other popups that use the "Switches for ..." approach probably
have a similar problem if a user sets any default arguments.)
