### ISSUE TITLE
magit-refs-mode buffer fontify incorrectly

### ISSUE THREAD

**Issue by wrn** [magit/magit#3179]
Magit 2.11.0, Git 2.8.3, Emacs 24.5.1, gnu/linux

What I observed:
In an example entry below in magit-refs buffer:

Branches (5)
  my-branch          [fix] My latest fix

The "fix" in the commit message is fontified with "magit-branch-remote", while the correct face to use is "magit-keyword"

**Comment by kyleam** [comment]
Thanks for the report.

The issue is that `magit-insert-local-branches` parses the output of
`git branch -vv` with a regexp, so it can't distinguish between the
upstream information and the message.

I think the best fix would be to rewrite `magit-insert-local-branches`
to use `git branch`'s `--format` flag.  For example,

```
git branch -vv --format="%(symref)%00%(refname:short)%00%(objectname:short)%00%(upstream:short)%00%(upstream:track,nobracket)%00%(subject)"
```

contains all the same information, but now we can unambiguously identify
the fields by splitting on NUL.

Similar changes could be made for `magit-insert-remote-branches`.

**Comment by tarsius** [comment]
Err, I noticed this a fairly long time ago and thought I already fixed it. Sorry about that.

I agree NUL is the way to go.

**Comment by tarsius** [comment]
Working on it...
