### ISSUE TITLE
':' should not be escaped in refspecs

### ISSUE THREAD

**Issue by jgarvin** [magit/magit#3187]
I am trying to run:

git push origin HEAD:ref/for/master

By choosing the option to push an explicit refspec. But magit will then try to run:

git … push -v origin HEAD\:ref/for/master

Which gets rejected.

I am using emacs head (although the same issue happens in the latest release 25.3) and:

magit-version is a variable defined in ‘magit.el’.
Its value is "2.11.0"

**Comment by tarsius** [comment]
> Which gets rejected.

(What is the rejection message?)

It probably gets rejected because your push doesn't result in a fast-forward, i.e. your local changes have diverged from what is currently in `ref/for/master` on the remote. Try using `--force-with-lease` or if that fails using `--force`. I saw your recent question on Stackexchange, so I know that Gerrit is involved. I don't know how that Gerrit feature works, but I assume that you don't pull `ref/for/master`, so you will probably have to use the `--force` (which you can do using <kbd>- F</kbd> in the pushing popup).

Also, are you sure it is `ref/for/master`, not `refs/for/master`?

**Comment by npostavs** [comment]
I think this came up in the gitter chat, and <kbd>P r</kbd> (`magit-push-refspecs`) worked for this.

**Comment by jgarvin** [comment]
Gah, my mistake, I assumed it was the escaping, didn't catch my typo of ref vs refs.
