### ISSUE TITLE
Stash selected files

### ISSUE THREAD

**Issue by bricewge** [magit/magit#3200]
With git `2.1.13` it is possible to stash only specified files with [`git stash push`](https://www.git-scm.com/docs/git-stash#git-stash-push-p--patch-k--no-keep-index-u--include-untracked-a--all-q--quiet-m--messageltmessagegt--ltpathspecgt82308203). It would be nice to have this functionality in Magit too.

**Comment by tarsius** [comment]
Magit allows stashing just the staged changes. Does that help?

**Comment by bricewge** [comment]
Yeah, definitely! Having the ability to stash selected files would enhance
the UI though.

Le 12 oct. 2017 15:46, "Jonas Bernoulli" <notifications@github.com> a
écrit :

**Comment by tarsius** [comment]
You can already stash just selected lines by using Magit's usual staging mechanism. Just selectively stage as if you were going to create a regular commit, then, instead of creating that, create a stash.

It appears that Git and Magit have diverged with regards to stash creation. This is one of the few areas where Magit uses its own implementation instead of Git's implementation, because Git's just isn't flexible enough to implement Magit's features on top of.

**Comment by tarsius** [comment]
If there is something that can be done with `git stash push` that cannot be done with Magit, then please walk me through the steps you would use on the command-line.

**Comment by fice-t** [comment]
It would be nice, though, if one could selectively stash files (with `git stash push`) and hunks (with `git stash -p`) without altering the index.

**Comment by bricewge** [comment]
This issue is not really about how magit manage stashes but about the UI. Having to stage the changes you want to stash isn't intuitive. And it seems I'm not the only one who didn't figured it out by myself : https://emacs.stackexchange.com/questions/18077/how-to-stash-individual-files-with-magit.

Here is an example: you select the files you want to stash with `C-SPC` and stash them with `Z`. Instead of the current `C-SPC`, `s`, `zi`.

If you think this feature request is useless feel free to close it since the functionality is already there.

**Comment by tarsius** [comment]
It doesn't sound necessary or very useful to me, so it is a low priority. But I will keep this open, maybe I'll change my mind.

**Comment by tarsius** [comment]
> you select the files you want to stash with `C-SPC` and stash them with `Z`.

If you are okay with that stashing those files **and** what is already staged, then that should be fairly easy to do.

**Comment by tarsius** [comment]
> It would be nice, though, if one could selectively stash files (with `git stash push`) and hunks (with `git stash -p`) without altering the index.

Not quite sure what you are saying here. This commands do alter the index, so if Magit used them then Magit would do so too.

**Comment by tarsius** [comment]
> This issue is not really about how magit manage stashes but about the UI. Having to stage the changes you want to stash isn't intuitive. And it seems I'm not the only one who didn't figured it out by myself : 

It's different from how `git` does it and therefore potentially unexpected. However "selecting changes to do something with them" always works like this in Magit, so it is consistent. I don't want to add an alternative, more git-like interface, just because some users would be more likely to discover that interface. I don't think this would do those users much good because it would make it less likely that they would discover the, IMO better, interface provided by Magit eventually.

Therefore I won't provide a `--patch` like interface. If you want to stash parts of a file, then use Magit's standard interface for staging changes, and then stash the result.

I believe Magit already implements the equivalent of `git stash push -p`, using its own UI conventions.

`git stash push -- files` provides a feature that Magit currently does not provide: *after already staging changes, only stash some of them*. This might be useful in cases when one has already carefully staged some changes in order to commit them and then decides that it would be a good time to stash *parts* of that instead.

I have difficulties imagining a situation in which I would want to do that. It seems to me that if one has already staged some changes that the next logical step is to somehow commit them -- either by creating a regular commit or a stash. Since we are operating under the assumption that the index wasn't build in order to stash it, the only logical step is to create a regular commit. So do that, and now you can selectively stash again -- without messing up a carefully crafted index.

If you have a use-case that makes it desirable to stash only some files, while maintaining the index, then please explain it in detail and also show the commands that could be used on the command line to accomplish that.

**Comment by bricewge** [comment]
I don't remember the use-case I was doing when I opened this issue, if it come back again I will explain it here.

You made your point clear here, and I agree with it. Sorry for losing your time, keep up your good work on Magit, it is an amazing piece of software!

**Comment by tarsius** [comment]
No problem. Cheers!

One note on

> also show the commands that could be used on the command line to accomplish that.

I did some experimentation and one thing I noticed is that while `push -- FILES` allows leaving the other files untouched, it does completely stage `FILES`. I.e. you loose all partial staging that has been done to those files.

The alternative would be to use a secondary index and preserve the old index, but as I said that could lead to conflicts between the two indices. I do not expect `git` to go the second road anytime soon, because it actually relies on storing information in the index while the user is resolving conflicts in the working tree - so having an index with its own conflicts would be a big problem.

**Comment by fice-t** [comment]
> Not quite sure what you are saying here. These commands do alter the index, so if Magit used them then Magit would do so too.

I guess I thought they did something else. I figured it would have been straighforward to use those commands and then apply the stash created to get the index back, but that apparently doesn't work. Oh well.

**Comment by blamario** [comment]
> It's different from how git does it and therefore potentially unexpected. However "selecting changes to do something with them" always works like this in Magit, so it is consistent.

Not entirely. Magit allows me to hit k on any file, thunk, or selected region and discard all changes within, whether they've been staged or not. The stash operation is conceptually not all that different from kill; when I use `git stash` on the command line, I often use it as an "undoable kill". Just compare `git checkout -p` and `git stash -p`. Why should magit support the former but not the latter?
