### ISSUE TITLE
Support notes for stashes

### ISSUE THREAD

**Issue by fice-t** [magit/magit#3212]
Apparently you can have notes on stashes. It would be nice to view/edit/manipulate them with stashes as you would with commits.

`Magit 20171014.220, Git 2.14.2, Emacs 26.0.60, gnu/linux`

**Comment by tarsius** [comment]
> Apparently you can have notes on stashes.

Any use-case?

> It would be nice to view/edit/manipulate them with stashes as you would with commits.

Since stashes consists of 2-4 commits you can already add notes "as you would with commits". Granted it that might involve showing the log for the stash (to get access to those commits) and viewing the notes would probably also be a little more involved.

Before adding some specialized support for stashes I will focus on improving basic generic notes functionality.

**Comment by fice-t** [comment]
> Any use-case?

Yeah, I have a tendency to leave a lot of things unfinished, so having notes on stashes would help me remember what I was doing with them after a long time has passed.

> Since stashes consists of 2-4 commits you can already add notes "as you would with commits".

Perhaps. I meant that commands such as `T T` would offer the stashes as possible candidates.

It turns out that using `d c` on the stash will show the notes, but it would be nicer if `z v` also showed them.

Also, I think having point on a stash in the status buffer should make it the default candidate in completions such as `d c`.

**Comment by tarsius** [comment]
`T T` on a stash now defaults to that (but it is not offered as a candidate elsewhere) and when showing a stash the notes for `stash@{N}` are shown.

**Comment by fice-t** [comment]
Thanks, that works well for me.
