### ISSUE TITLE
Remove `A` keybinding for magit-stash-pop?

### ISSUE THREAD

**Issue by fice-t** [magit/magit#3220]
Since `A` is the keybinding for `magit-cherry-pick-popup`, one can accidentally pop a stash if the point happens to be on a stash when they want to cherry pick something.

`z p` should be good enough, and one is free to rebind `A` if they'd like. I think it's best to avoid conflicts like these if possible, especially if they modify the repository.

**Comment by tarsius** [comment]
Since, as far as I remember, nobody else brought this up, while changes to key bindings usually result in protests, I would rather not.

**Comment by fice-t** [comment]
I understand that there were some issues in the past, but I don't think that should mean that no key bindings should change in the future. I think this is one of those cases where removing it makes sense:

- Unlike some past changes, adding in the removed keybinding is trivial (one `define-key` and optionally a `with-eval-after-load`)

  - One could argue that it's just as easy to remove the keybinding, but I would say that it's better to avoid making the user accidentally modify the repository state. Removing the keybinding is the proactive approach, which I believe is preferable to forcing users to remove the keybinding after it messes up their repo.

- The binding is unintuitive since you would expect, from `magit-dispatch-popup`, to open the cherry popup rather than popping a stash. There doesn't appear to be any other cases where a popup binding is overridden in a section in the status buffer.

If you're still worried about removing it now, then perhaps consider doing it for the next major release? People shouldn't be surprised to see minor keybinding changes in a major release.

**Comment by tarsius** [comment]
Asking for confirmation would probably be a good compromise.

**Comment by fice-t** [comment]
It would be nice, since at least `z k` brings up a completion table before dropping the stash at point.

However, I still don't think the keybinding belongs. On one hand it makes sense that Shift+`magit-apply` on a stash would do some modified apply (pop) on the stash, but it doesn't fit in with the rest of the bindings in that section (visit, apply, drop -- which all are applicable to other sections as well), or with other bindings in magit.

I hope there is a point in the future where magit gets to clean up out-of-place artifacts like these.

**Comment by tarsius** [comment]
In #3232 I am implementing a mechanism for decoupling confirmation and completion for individual commands.

On the same branch I am changing `magit-stash-pop` to ask for confirmation. I will immediately undo in my own configuration, because if you know what is going on, then this is safe. Otherwise its unsafe because it is hard to figure out what just happened if you are not aware that <kbd>A</kbd> behaves differently when on a stash.

But that is as far as I am willing to go here.

> it doesn't fit in with the rest of the bindings in that section (visit, apply, delete

I think `apply+delete` fits in very well with `visit, apply, delete`. It literally combines two of those into a single action.

> I hope there is a point in the future where magit gets to clean up out-of-place artifacts like these.

While I generally agree, I don't think this is one of those artifacts.

* <kbd>a</kbd> does apply the changes at point, disregarding additional metadata.
* <kbd>A</kbd> does apply the changes at point (or some other changes), doing something with the additional metadata. What the metadata is and what exactly is being done with it differs depending on what the point is on.

The interactive behavior of <kbd>A</kbd> also differs depending on what is at point. In most places the cherry-pick popup is shown, on a stash asks for confirmation (or rather it will do that by default soon).

Beside the slightly misleading entry in the dispatching popup, the only inconsistency is that when on a stash, then you cannot apply something else. (Actually you can configure it to be able to apply another stash instead, but not to cherry-pick an arbitrary commit instead.) However, that is not a big deal, because using completion to select a commit to cherry-pick is not nearly the most efficient method in most cases. (Moving to the commit first is.)

> The binding is unintuitive since you would expect, from `magit-dispatch-popup`, to open the cherry popup rather than popping a stash.

The dispatch popup was an after-thought. <kbd>A</kbd> was able to pop a stash long before it was created. It might even be that it was possible to pop a stash using this key before the cherry-picking popup was created. Of course sometimes some old things have to be changed for new things to be consistent, but I don't think this is one of those cases. And the reason for that is that, as mentioned above, <kbd>A</kbd> already consistently "applies some thing and does something with the  associated metadata".

I could change the description of <kbd>A</kbd> in the dispatching popup from "Cherry-picking" to "Applying" that would make it correct in all cases. But that seems unnecessary.

I could also add `magit-stash-pop` to `magit-cherry-popup` (which would then have to be renamed to `magit-apply-popup`) and remove the specialized <kbd>A</kbd> binding on a stash. But I don't want to. Git and Magit offer a lot of functionality and as a consequence not everything can be perfectly consistent without sacrificing convenience. I think Magit is pretty consistent, and that's actually something that is important to me, but in this case I want to do the convenient thing, instead of maximizing consistency.
