### ISSUE TITLE
Renaming branch fails if branch has same name as tag

### ISSUE THREAD

**Issue by alphapapa** [magit/magit#3222]
Magit 20161024.1349, Git 2.7.4, Emacs 25.2.2, gnu/linux

I realize I haven't updated Magit in a while, but I don't see any closed issues relating to this, and it seems somewhat obscure, so I think it's unfixed.  Apologies if it is already fixed.

1.  Make branch named `0.1`.
2.  Make tag named `0.1`.
3.  Notice that branch is now referred to in Magit as `heads/0.1` to disambiguate it from the tag.
4.  Decide to rename branch to `stable/0.1`.
5.  Try to rename the branch in Magit.  Magit fails because it includes an extra `heads/` in the git command:
```
128 git … branch -m heads/0.1 stable/0.1
error: refname refs/heads/heads/0.1 not found
fatal: Branch rename failed
```
6.  Try to rename the branch in Magit, but type the branch name manually, `0.1`.  This works:
```
0 git … branch -m 0.1 stable/0.1
```

Thanks for your work on Magit!

**Comment by kyleam** [comment]
I think #3101 is the most recent work on ambiguous refs, but based on
quick testing the issue you report doesn't seem affected by those
changes.

This issue is similar to the checkout one fixed by 7bb09ca2
(magit-checkout: strip "heads/" from revision, 2017-06-08).  We have
to use qualified branches in many cases, but some downstream Git
commands assume a branch and don't ever want a qualified ref.

**Comment by kyleam** [comment]
And just a note: I'd recommend that you don't use a naming scheme that
involves ambiguous refs.  While ideally we would handle ambiguous refs
appropriately in all places, that's not currently the case.  A little
while ago, I started digging deeper to fix some remaining issues, but
it gets messy quickly.  I don't give these issues much priority
because most people don't use ambiguous refs, but I should at least
open an issue to document the remaining issues that I'm aware of.

**Comment by alphapapa** [comment]
Thanks.

**Comment by alphapapa** [comment]
Thanks!
