### ISSUE TITLE
Holding mouse-1 on some sections highlights them

### ISSUE THREAD

**Issue by fice-t** [magit/magit#3248]
Some sections count holding `mouse-1` (without moving the cursor) on them as selecting the section, which shouldn't happen.

Some examples:

- (Un)staged changes header
- file headings
- hunk headings

`Magit 20171105.1234, Git 2.14.2, Emacs 26.0.90, gnu/linux`

**Comment by fice-t** [comment]
Also, I noticed that for other sections (e.g., commits) holding `mouse-1` on them and moving only starts to highlight once `mouse-1` is released (or it moves into a new section). Ideally, it would highlight the selection when the mouse has moved, even within the section.

**Comment by tarsius** [comment]
Yeah, I am aware. I was hoping I would get away with it until I refactor the section abstraction :stuck_out_tongue_winking_eye:

**Comment by tarsius** [comment]
> Some sections count holding `mouse-1` (without moving the cursor) on them as selecting the section, which shouldn't happen.

115041d4b471228091c14b59bba6c91eb4d4c0f0 introduced support for single-section selections. Without an additional condition that results in the observed behavior. I did address that for non-diff-related sections in that commit. The first commit in #3249 does so for diff-related sections. That is not as straight forward and might have unintended consequences.

> Also, I noticed that for other sections (e.g., commits) holding `mouse-1` on them and moving only starts to highlight once `mouse-1` is released (or it moves into a new section). Ideally, it would highlight the selection when the mouse has moved, even within the section.

That doesn't bother me much since you cannot actually act on the selection before releasing the mouse button.

This did however remind me that I have thought about not hiding the region while dragging and/or when the region begins and ends in the same line. I have implemented that in the second commit.

**Comment by tarsius** [comment]
> Also, I noticed that for other sections (e.g., commits) holding `mouse-1` on them and moving only starts to highlight once `mouse-1` is released (or it moves into a new section). Ideally, it would highlight the selection when the mouse has moved, even within the section.

I have looked into this again. This only happens for non-diff-related sections, because those are highlighted on `post-command-hook` and dragging the mouse does not cause that hook to be called repeatedly. Diff-related sections are highlighted on `pre-redisplay-functions`, which is called much more frequently.

The former is much cheaper than the latter, which is why we only use the latter when necessary. Or at least I think that's the reason - it's a longstanding plan of mine to look into this again and possibly refactor. But this minor issue is not enough to motivate me to do it now.
