### ISSUE TITLE
Magit shows empty log instead of error in corrupted repo

### ISSUE THREAD

**Issue by 501st-alpha1** [magit/magit#3254]
One of my Git repositories somehow got corrupted, but I didn't realize it right away because Magit didn't report the error.

When I ran `git log --graph` from the command line, I got this error:

```
error: Could not read aabbccdd...
fatal: revision walk setup failed
```

However, when I did `l l` from the status buffer, I got no error, but saw:
```
Commits in my-branch
(empty)
```

Only when I set `magit-git-debug` to `t` did I see the `revision walk setup failed` error in Emacs, and was I able to see the log command in the process buffer.

Can such errors please be reported to the user even when debug mode is off?

Magit version:

```
Magit 20170403.1234, Git 2.1.4, Emacs 24.4.1, gnu/linux
```

**Comment by tarsius** [comment]
> Can such errors please be reported to the user even when debug mode is off?

Not without simply always turning debug mode on, but that isn't already being done because that would be costly. An alternative would be to only turn debug mode for log commands, but as far as this request goes those commands only differ from other commands in that someone has *reported* that corruption of the repository can lead to a silent error. But that's also possible for many other commands, so we have cycled back to always turning debug mode on - or not.

I think it is fair for Magit to assume that git data isn't corrupted and expect users to drop to the command line to investigate strange issues - or its own debug mode, though that only takes you that far.
