### ISSUE TITLE
Let cursor be at the default action key in magit popup buffer like in magit 1.x

### ISSUE THREAD

**Issue by netjune** [magit/magit#3262]
Is there a custom option to achieve this? For me, the default action covers 90% of my use case.

**Comment by tarsius** [comment]
No there is no option for that, but did you notice that unlike in v1 you can in most cases press the same key that was used to show a popup to invoke its default action? So to create a plain old commit you could use <kbd>c c</kbd> instead of <kbd>c RET</kbd> - that seems to be even more efficient.

**Comment by netjune** [comment]
Yes, it is. But for chinese users, because of the input method(such as the pinyin input method), 'c c' will be 'c RET c RET'.

**Comment by tarsius** [comment]
> 'c c' will be 'c RET c RET'.

That sounds horribly - is that really the best available input method for read-only buffers?

**Comment by tarsius** [comment]
I guess you have to ask some other Chinese users how to be able to use `c c` instead of `c RET c RET`. Once you have done that, please summarize that here.

I won't bring back placing point on the default action. `magit-popup` is about to be replaced with a new implementation and in the successor it most likely won't even be possible to invoke the action at point using `RET`.
