### ISSUE TITLE
Forward blame shows unexpected commit details

### ISSUE THREAD

**Issue by kvaneesh** [magit/magit#3263]
Using forward blame I am finding wrong commit details mapped to lines.

-aneesh

**Comment by tarsius** [comment]
Please elaborate.

**Comment by kvaneesh** [comment]
with latest magit from melpa, i do a git blame and after some time want to froward blame 'key binding f'. I see commit details show which doesn't touch the line at all. For example see the attached file. The commits shown around do_fork are not related to that file at all
![screenshot from 2017-11-15 21-47-38](https://user-images.githubusercontent.com/19270/32846971-b05ca244-ca4e-11e7-9f03-c10d1cd2bd2f.png)

**Comment by tarsius** [comment]
Please run the equivalent git command in a shell and verify that it doesn't display the same information. Have you been using reverse blaming before support was added to Magit? Are you sure you understand what information it is supposed to display and that what is being displayed is not exactly that?

```
       --reverse <rev>..<rev>
           Walk history forward instead of backward. Instead of showing the
           revision in which a line appeared, this shows the last revision in
           which a line has existed. This requires a range of revision like
           START..END where the path to blame exists in START.  git blame
           --reverse START is taken as git blame --reverse START..HEAD for
           convenience.
```

**Comment by tarsius** [comment]
If Magit really displays something that is different from what Git displays, then find a public replsitory in which you can reproduce the issue and the provided detailed steps on how to produce it. Also include the steps you performed on the command line to see whether Git shows the same information.

**Comment by fice-t** [comment]
Could Magit provide a distinction between "forward" blaming and "reverse" blaming?

By "forward blaming" I am referring to the description used in `magit-blame-reverse`:

> For each line show the subsequent revision that removes it.

"reverse" blaming instead shows the revision that last contains the lines (a parent of the above).

I think it would be useful to find the commit that actually removes the given lines.

**Comment by kyleam** [comment]
@fice-t I've read your comment a couple times and don't understand
what distinction you're asking for, but FWIW I think the description
in `magit-blame-reverse`'s doc-string is inaccurate (and maybe that's
what is leading to @kvaneesh's confusion).  `--reverse` doesn't show
"the subsequent revision that removes it" but instead "the last
revision in which a line has existed".

**Comment by kyleam** [comment]
@kvaneesh try running `git blame --reverse HEAD^.. -- <file` on a file
that you know wasn't touched in the last commit.  You'll see that
every line is assigned HEAD's commit.

**Comment by fice-t** [comment]
> I've read your comment a couple times and don't understand
what distinction you're asking for

The distinction would be to have a function that provides the behaviour the current doc-string describes ("show revision that removes the line").

So, "forward blaming" a buffer shows hunks that, if you press `RET` on them, show the commit that removes the lines they contain.

**Comment by kyleam** [comment]
> The distinction would be to have a function that provides the behaviour the current doc-string describes ("show revision that removes the line").

But that doesn't seem like a git blame thing (and thus
`magit-blame-*`) to me then, since there's no native way to accomplish
it with `git blame [...]`.  Do you have a git command that could
accomplish this in mind?  If I wanted to know what removed/added some
content, I'd typicall use git log's `-S` (which wouldn't be restricted to
deletions, of course).

> So, "forward blaming" a buffer shows hunks that, if you press RET on them, show the commit that removes the lines they contain.

I would avoid calling this "forward", since git-blame's manpage
describes `--reverse` as "Walk history forward instead of backward".

**Comment by fice-t** [comment]
> Do you have a git command that could
accomplish this in mind?

I don't know of anything offhand. If there isn't a way to do this with `git blame`, then I think there should be.

Pressing `f` on a chunk seems to already know the proper commit, though. `magit-blame-reverse` uses `(magit-blame-arguments* t)`, which uses:

`(magit-blame-chunk-get :previous-hash)`

to get the commit in question. So there could be an option to just use this value, right?

> I typically use git log's -S (which wouldn't be restricted
to deletions, of course).

I don't believe it's as convenient, though (when you're already in a blob).

> I would avoid calling this "forward", since git-blame's manpage
describes --reverse as "Walk history forward instead of backward".

Right, I just used the term since that's what @kvaneesh used. Plus, it also fits the current bindings (`f`).

**Comment by tarsius** [comment]
>  For each line show the subsequent revision that removes it.

Eeep. Seems I as a bit confused about this too. Fixed.

**Comment by kyleam** [comment]
> (magit-blame-chunk-get :previous-hash)
>
> to get the commit in question. So there could be an option to just use this value, right?

Depending on what you want, I think it's a lot more complicated than
just using that value.  Above you say

> "forward blaming" a buffer shows hunks that, if you press RET on them, show the commit that removes the lines they contain

To show the `:previous-hash` hunks in-buffer we'd need to manipulate
`git blame --incremental`s output, which I don't think is a good idea.
That adds a lot of complicated logic to what is currently just a
parsing task, and I think it'd be difficult to get right and prone to
breaking.  I haven't convinced myself that showing hunks like you
describe would lead to sensible output, but, if you think it would,
I'd suggest proposing an alternative `git blame` mode on the git
mailing list.

As for having some show-commit variant that shows the revision buffer
for a non-nil `:previous-hash`, that might be worth doing.

**Comment by kyleam** [comment]
> The simplest/crude method would be to just overwrite [...]

If the results of doing that look promising, please ignore my
comments, which are probably overestimating the complications.

> What aren't you convinced about specifically?

I say that "I haven't convinced myself" because I'm having trouble
thinking through and reasoning about it.  I'm not saying you're wrong,
just that I'm too slow to know if you're right.

Can we reliably identify the deletion commit using blame's output
given that git doesn't explicitly handle it?  Here's what Junio says
in 85af7929e (git-blame --reverse, 2008-04-02):

    [...]
    This mode probably needs more tweaking so that the commit that removed the
    line (i.e. the children of the commits listed in the above sample output)
    is shown instead to be useful, but then there is a little matter of which
    child of a fork point to show.

    For now, you can find the diff that rewrote the fifth line above by doing:

        $ git log --children 213523f4^..

    to find its child, which is 1025fe5 (Merge branch 'lt/rev-list' into next,
    2006-03-01), and then look at that child with:

        $ git show 1025fe5

And [here's] a relevant git mailing list thread about this topic.

[here's]: https://public-inbox.org/git/BANLkTikuFEg686VH_RojEe-zmBZRBOx6eA@mail.gmail.com/T/#u

**Comment by tarsius** [comment]
I've been improving blame support over the last week. Lots of refactoring, but I also got to implement some new features.

#3420 implements the blame "type" requested here ("removal" commits that remove lines). It does *not* replace the "final" (last commits that still have lines) type, which here was described as "finding wrong commit details". I think the "removal" type is more useful than the "final" type, but the latter might also have its uses, and users who used `--reverse` will expect it to exist in Magit too.

So I have added a new command instead of replacing the old command. That leads to some complications with regards to key bindings, which I haven't addressed yet. I also haven't updated the documentation yet.

I have also added a new command `magit-blame-visit-orig-file`, which for the "removal" type actually visits the previous blob not the "original" blob. No key is bound to this command yet and it may jump to a weird place within the blob for the "removal" type. I probably won't address that before merging.

But please check it out.
