### ISSUE TITLE
Checkout should autocomplete branches at origin

### ISSUE THREAD

**Issue by fommil** [magit/magit#3264]
I often find myself wanting to check out a branch that I started on another computer and pushed to `origin`, let's call it `feature/foo`.

I expect to be able to do `b` (Checkout) then `feat[TAB]`, but it is not visible. Currently the only way to get autocompletion is to do `origin/feat[TAB]` and then `C-a` and delete the `origin/` part. It would be nice if the remote branches were included by default in the autocomplete.

---- now delete this line and everything above ----

But I like this line! :stuck_out_tongue:

**Comment by tarsius** [comment]
* `b b` (`magit-checkout`) is supposed to offer that branch, but checking it out will result in a detached `HEAD` because remote branches cannot actually be checked out. Is that what you are trying to do?

* I guess not. You probably want to rely on `git checkout foo` being equivalent to `git checkout -b foo --track origin/foo` in some cases.

   ```
           If <branch> is not found but there does exist a tracking branch in
           exactly one remote (call it <remote>) with a matching name, treat
           as equivalent to

               $ git checkout -b <branch> --track <remote>/<branch>
   ```

   Magit does not support that, not least because of the "there does exist a tracking branch in exactly one remote" part.

* You can use `b c "fo" TAB RET RET` (assuming you use a decent completion framework and haven't changed the value of `magit-branch-read-upstream-first`.

* Check out the new "checkout local branch" variant on `b l`:

  > Checkout an existing or new local branch.

  See the doc-string for a detailed description.

**Comment by fommil** [comment]
oh I don't have that new feature yet, sounds like it's what I'm after! I'll look out for the next release in that case :smile:
