### ISSUE TITLE
Shortcut for moving changes between branches

### ISSUE THREAD

**Issue by Wasabichicken** [magit/magit#3325]
Hi.

Due to poor git discipline, every now and then I find myself working on a branch only to realize that my changes should actually go into a different, possibly not yet created, branch instead. What I typically do to resolve it is the following:

1. (Optional if nothing has been committed yet) Soft reset to the last commit without my accidental changes,
2. Stash everything using some temporary stash message,
3. (Optional) Create the correct branch if it doesn't exist yet,
4. Check out the correct branch,
5. Pop the stash.

I do this screwup often enough that I find myself wanting a shortcut to perform the steps above. If you too see a frequent use case for this "move stuff to other branch" type of high-level command, please consider adding one.

Thank you in advance, and especially, thanks for an outstanding git client.

**Comment by tarsius** [comment]
This happens to me too and I was already planning to implement a few commands very soon, likely next week. I probably won't implement it exactly as described in #2921, but it should come fairly close in functionality.

Ps: Do not prefix feature request summaries with "Feature request". That's easy enough for me to figure out and then I use a label to classify the issue as such. Github should allow maintainers to whitelist some labels for users to apply for themselves.

**Comment by vermiculus** [comment]
> Github should allow maintainers to whitelist some labels for users to apply for themselves.

Sounds like isaacs/github#148. GitHub doesn't necessarily look at this repo, but it's a good collection of knowledge. Best followup is to badger GitHub 😄

**Comment by tarsius** [comment]
Thanks for that link. I'll have to go check whether "Github by default creates corrupted commit messages" * is listed there. That one truly pisses me off because it likely is a one-line fix and I have first reported it years ago.

(*) Unless you manually put it there, commit messages created on Github do not end with a newline character, while it is not possible to create such a message using the `git` porcelain. Using `git` plumbing commands it is possible, which is probably what Github is doing.
