### ISSUE TITLE
can't do a merge --squash --no-commit

### ISSUE THREAD

**Issue by glyph** [magit/magit#3348]
M-x magit-version RET

```
Magit 20180107.832, Git 2.16.0, Emacs 25.3.1, darwin
```

If, in a `magit-status` buffer, I hit <kbd>m</kbd> <kbd>-s</kbd> <kbd>n</kbd> and then select a branch, I get an error `fatal: You cannot combine --squash with --no-ff.`.  But I didn't select `--no-ff`.  `magit-merge-arguments` is `nil`.

How do I do a `--squash` `--no-commit` merge?

**Comment by tarsius** [comment]
> How do I do a `--squash` `--no-commit` merge?

Use <kbd>m</kbd> <kbd>-s</kbd> <kbd>m</kbd>, which will do a `--squash`. `--no-commit` is not necessary in this case - as the description of `--squash` says this will never create a commit.

> But I didn't select `--no-ff`.  `magit-merge-arguments` is `nil`.

The `--no-ff` is hard-coded for <kbd>e</kbd> and <kbd>n</kbd>.

Like <kbd>e</kbd> ("Merge and edit message") <kbd>n</kbd> is about creating an actual merge commit with a commit message. Unlike the former it also allows editing the changes, not just the message.

Its description `Merge but don't commit` is probably not so good `Begin merging but stop before committing` might be better, but the length of that causes issues due to some limitation of the popup implementation.

**Comment by npostavs** [comment]
> Its description `Merge but don't commit` is probably not so good `Begin merging but stop before committing [so that the changes can be edited]` might be better, but the length of that causes issues due to some limitation of the popup implementation.

`Merge, stage only`?

**Comment by tarsius** [comment]
> `Merge, stage only`?

`Merge and edit changes`?

**Comment by tarsius** [comment]
```
e Initiate merge, edit message
n Initiate merge, edit changes
```

Or use a single column and use

```
e Initiate merge, allow editing message
n Initiate merge, allow editing changes
```

**Comment by tarsius** [comment]
How the actions are arranged now is pretty weird anyway.

**Comment by npostavs** [comment]
I don't think the "allow" really adds much to the description (I don't have an opinion about the column arrangement).

**Comment by tarsius** [comment]
And maybe add one of

```
q Initiate squash
q Initiate squash commits from branch
```

(I want to avoid the term "merge" here.)

**Comment by tarsius** [comment]
> I don't think the "allow" really adds much to the description

Well it emphasizes that the "initiating" is done by Git, while the "editing" is up to the user. But maybe not enough to make a difference and "..., allowing the user to edit..." now that is too long.

**Comment by tarsius** [comment]
Well it comes down to this: If you know what `--squash` does, then it makes sense to assume that `Merge but don't commit` is the right action. So maybe we should just change that command to silently forgo adding `--no-ff` when `--squash` is present and be done with it.

**Comment by tarsius** [comment]
I would prefer that in the short run at least because I think that aside from this complication `Merge but don't commit` is actually a fine description.

**Comment by tarsius** [comment]
Or remove `--squash` and instead add `Apply branch` to the apply popup.

Anyway, I will finish #2922 and #2921 first because I think those will provide better alternatives.
