### ISSUE TITLE
Build dependencies

### ISSUE THREAD

**Issue by elibarzilay** [magit/magit#3350]
For those of us that like to build from source, the dependencies on
other packages can be confusing...  My recent cycle was: update, run
make, get error about a missing file, scratch head, try random things,
finally get to the RTFM.

It would be nice if there was some clear error thrown when a package is
missing, instead of complaining about missing files.

**Comment by tarsius** [comment]
I don't think that

    magit-status.el:30:1:Error: Cannot open load file: No such file or directory, ghub

for example, is particularly cryptic. What "random things" did you try to fix the issue? It seems that the next logical step is to install the missing dependency.

Of course it would be possible to instead display:

    Magit depends on the ghub package, which appears to not be available.
    You need to install that dependencies and also all the other dependencies.
    Please read https://magit.vc/manual/magit/Installing-from-the-Git-Repository.html
    for instructions.

But that ... is a bit much. I don't know of any other software that goes to such lengths and I won't to it for Magit.

It is perfectly reasonable for an experienced user like you to just type `make` and hope for the best. After all that might just work. But once that doesn't work you should just consult the documentation. Simply banging on it some more like you apparently did is okay too, but if that turns out to not be a very pleasant experience, then that doesn't mean that the maintainer has to add some sort of setup wizard to the build steps.

Magit already goes to great length to make `make` "just work" in various common and not so common scenarios (with the result of at least on distribution maintainer expressing their disgust). It cannot also handle the "the dependencies are simply not available" case.

**Comment by elibarzilay** [comment]
1. The thing that confused me was a missing magit-popup, IIRC.  Since it
   looked like it belongs in magit, and I've that file there before, I
   didn't even think that it would become a package.

2. I don't remember what I did, it was very roughly going along the
   lines of:
   - run a `make`, get a complaint about a missing file (don't remember
     which one)
   - run a `make clean`, get a different error (I think that this is
     where the magit-popup error started)
   - re-do the whole thing outside of an emacs shell (since I vaguely
     remember having some weirdness when running the magit build inside
     emacs)
   - suspecting that maybe I messed up the repository, nuking it, and
     repeating
   - then I grepped for the file in the tree, and saw it mentioned in
     the docs, and read that.

3. I half expected there to be some variant of load/require/etc that
   looks for a file from a package and gracefully complain about a
   missing package.  (Eg, I imagined some `(require-package 'foo)` that
   complains about a missing package.)  Probably nothing like that
   exists.

   Then I thought that it would be some simple

       (dolist (p '(dash with-editor magit-popup ...etc...))
         (unless (package-installed-p 'dash) (error ...)))

   but I see now that the code looks for the directories of these things
   when the package is missing, which means that you want things to work
   even when these package are not installed since they might exist
   outside of the package system.

4. Finally, that last bit (which might be what people complained about:
   the bits that look for directories in `$(ELPA_DIR)`) looks like its
   the source of the problem --- making things work even without a
   properly installed package.  This is also related to why you don't
   see software that goes to such lengths: most packages that I see in
   various languages and environments use the package system to specify
   the dependencies, so there's no need to write extra code; going
   outside of the package system voids that.

5. As a sidenote, there a whole bunch of code in the makefile and
   related that would be easier to do with a real language --- in
   elisp...  (Something that could have been helpful is to just have a
   catchall error message that points to that page, but with a makefile
   I can see how this could be hard to do.)
