### ISSUE TITLE
checkout pull-request will always create `pr-$number` local branch

### ISSUE THREAD

**Issue by noc0lour** [magit/magit#3371]
Running: Magit 20180208.1958, Git 2.13.6, Emacs 25.3.1, gnu/linux

(1) Running `magit-checkout-pull-request` creates a new local branch named accordingly to the forks branch.
(2) A new branch named `pr-$number` is created and push remote is not set correctly
(3) Use a version which includes this https://github.com/magit/magit/commit/4f7f55c93635cc4b7bd536ec124000e98d2bc392 commit. 

This commit assumes the `maintainer_can_modify` property is exposed in the `/repos/$id/pulls` API response. Unfortunately it is only available in `/repos/$id/pulls/$pr_number` API response which is not used.

**Comment by tarsius** [comment]
Thanks! I noticed and fixed a second bug, but I am not sure what you mean by that.

> A new branch named `pr-$number` is created and push remote is not set correctly

It is being set to the upstream repository, right? If we are not allowed to push to the fork then that is the appropriate thing to do. It allows the maintainer to quickly push their changes somewhere in order to show it to the contributor. Of course if we are actually allowed to push to the pr's branch on the fork, then we should there, but if we are not, then this is a good fallback.

**Comment by noc0lour** [comment]
Ah, right, just saw it it set to the upstream repository and the contributors branch is just not yet available there. Alright, thanks for fixing this !

**Comment by tarsius** [comment]
No problem, thanks for a very actionable bug report.
