### ISSUE TITLE
Subset rebase passes wrong commit hash to git

### ISSUE THREAD

**Issue by greenrd** [magit/magit#3380]
Expected behaviour:
'r' then 's' should rebase only the selected commit and its descendants.

Actual behaviour:
'r' then 's' rebases the selected commit, its descendants and some other stuff as well - its parent, I think.

To reproduce:
'r' then 's', enter origin/master, then select a non-HEAD commit

M-x magit-version RET:
Magit 2.11.0, Git 2.14.1.windows.1, Emacs 25.1.1, windows-nt

**Comment by tarsius** [comment]
This difference to Git is intentional and extends to other rebase variants as well as other commands.

A range `A..B` means "do something with the commits *after* A, up to and including B". This does make sense from a technical perspective and for some commands (most importantly diff), also from a user-interface perspective.

But it is weird when the user only has to select the beginning of the range and the end is implied. Git expects to be told "do something with the commits *after* this commit. Magit on the other hand expects to be told "do something with *this* commit and the subsequent commits".

It think the latter make much more sense but it is an occasional source of confusion. (This has come up before but unfortunately I wasn't able to find my old (more detailed?) explanation.)

The "implementation" of this difference boils down to this: the user selects "A" the first commit to act on, and Magit forwards that to Git passing "A^", as in "start after the commit `A^`, i.e. start with `A`".

**Comment by greenrd** [comment]
Sorry, this wasn't a magit issue but a git issue with the particular rebase I was trying to do. It was trying to rebase a commit that had already been merged.
