### ISSUE TITLE
Add hooks to decorate log entries

### ISSUE THREAD

**Issue by snogge** [magit/magit#3384]
I'd like to be able to add various indicators to loglines. 
I'm thinking of test report icons from travis and review-votes and things like that.
The decoration could be characters or images added to the line, or style overlays that set a background color or add a margin or fringe.

**Comment by tarsius** [comment]
I have added a new variable `magit-log-format-message-function` that you can use for this purpose. It is called with two arguments, the hash and the message. You probably want to call the default value `magit-log-propertize-keywords` in function.

I haven't documented this variable and added no entry to the release notes because this will likely change within a few months. I might, for example, replace this with a hook as you suggested, but I just don't know yet until I start refactoring this area of Magit.

**Comment by snogge** [comment]
Thank you!
I will try it out and report back.

**Comment by snogge** [comment]
So I made a test to display Gerrit votes for each commit in the log, and that worked.
Unfortunately it is so slow that I actually see the washing happening in the buffer. 
For this operation I first had to find the Gerrit Change-Id from the commit message.  That required a call to git through `magit-rev-insert-format`. Then I had to make a REST API call to the Gerrit server. 

I think some kind of outer scope and state object is needed to make this efficient, even if there must be something wrong with my setup to make it this slow.

It would also be useful to only trigger the format function for certain fixes.  For pull request and CI info commits that are already merged are not that interesting.

**Comment by tarsius** [comment]
I think you should be able to implement those things without any further changes to Magit. Using some log related hook and a buffer-local variable should do the trick.

If you disagree, then make the necessary changes, get performance right, and then let me have a look.
