### ISSUE TITLE
Add support for different hostname for GitHub.com in magit-collab.el

### ISSUE THREAD

**Issue by introom** [magit/magit#3392]
Sometimes I want to use different hostnames to differentiate accounts on GitHub.com.

For example, 
One git repo url is set as: git@github.com-foobar:xxxx/yyy.git

Note the github.com-foobar, which is used to differentiate GitHub accounts. Cf. [link](https://stackoverflow.com/questions/7927750/specify-an-ssh-key-for-git-push-for-a-given-domain)

magit-collab.el hardcodes "github.com", is it possible to extract that part out as defcustom?

Or, on the other hand, how to set and let magit know the correct repo url?

**Comment by tarsius** [comment]
I have just pushed support for Github Enterprise instances. The url no longer has to mach "github.com", it may also match `ghub.host`. But that doesn't address this issue yet.

Instead of adding yet another option, I would prefer to use existing information. Does `gpg` provide some sort of lookup command that could be used here?

**Comment by introom** [comment]
hi, thanks for the work.

after upgrading to the latest ghub, i now see the message when pulling requests (b-y):
Currently only Github is supported

**Comment by tarsius** [comment]
The change was implemented in Magit not Ghub, so updating the latter won't change anything. At the time you wrote you above reply the change was less than an hour old, so probably Melpa had not build a new version yet. I just tried this again and it works for me. Update Magit again.
