### ISSUE TITLE
No Syntax Highlight of Commit Message Buffer when Using Magit in Terminal on `% git commit` 

### ISSUE THREAD

**Issue by volodymyrprokopyuk** [magit/magit#3415]
There is no syntax highlight of the commit message buffer when using Emacs with Magit in terminal on `% git commit`. The commit message buffer is opened in Fundamental mode without any syntax highlight. Several month ago when doing `% git commit` from terminal the commit message buffer was nicely highlighted by Magit in Emacs in terminal. Committing from Magit buffer in Emacs in terminal works fine and the commit message buffer is nicely highlighted.

I'm using Emacs server mode and `emacsclient` in terminal
```bash
export EDITOR="emacsclient -t"
```

My Magit configuration
```emacs
; Magit mode
(add-to-list 'load-path "~/.emacs.d/with-editor")
(add-to-list 'load-path "~/.emacs.d/magit-popup")
(add-to-list 'load-path "~/.emacs.d/ghub")
(add-to-list 'load-path "~/.emacs.d/magit/lisp")
(load "~/.emacs.d/magit/lisp/magit-autoloads.el")
(with-eval-after-load 'info
    (info-initialize)
    (add-to-list 'Info-directory-list "~/.emacs.d/magit/Documentation/"))
(global-set-key (kbd "C-x g") 'magit-status)
(global-git-commit-mode)

; Git modes (gitattributes, gitconfig, gitignore)
(add-to-list 'load-path "~/.emacs.d/git-modes")
(load "~/.emacs.d/git-modes/git-modes-autoloads.el")
``` 
Magit version
`Magit 2.11.0-608-g4b9386c, Git 2.7.4, Emacs 27.0.50, gnu/linux`

I've tried setting `(global-git-commit-mode)` in my Magit configuration file but in this case on `% git commit` Emacs exits unexpectedly with return code `1`

**Comment by bwolf** [comment]
Without digging into your configuration, I can state that simply setting `EDITOR="emacsclient -t"` works for me. Seems to me an issue with your configuration.

**Comment by tarsius** [comment]
After adding `(require 'git-commit)` to your init file this should work again.

**Comment by tarsius** [comment]
To make that more explicit: Emacs has to be instructed to handle files named `COMMIT_EDITMSG` differently. Those instructions can be found in `git-commit.el`, so if you have not loaded that library at the time such a file is opened, Emacs doesn't know it has to do something special.

When committing from inside Emacs using Magit, that is not a problem because loading Magit will also load `git-commit`. 

When committing from outside of Emacs you have to make sure `git-commit` has somehow been loaded yourself. The easiest way is to just always require `git-commit`, but if you want to avoid that, then there other ways, like always remembering to load it explicitly before executing `git commit` in a shell after starting a new Emacs instance.

I don't think it is possible to instruct Emacs how to handle `COMMIT_EDITMSG` using autoloads. The instructions are implemented as mode defined in `git-commit.el`.

**Comment by tarsius** [comment]
> I thought that `(load "~/.emacs.d/magit/lisp/magit-autoloads.el")` should do the necessary setup

Well, it doesn't.

> The only thing that changes is the way of starting the commit process: (a) rather than commit from within Magit,

The significant difference is that in order to commit "from Magit" Magit has to be loaded, and loading that causes `git-commit` to be loaded too.

> When I include `(require 'git-commit)` in my configuration and do `% git commit`, Emacs starts in server mode and immediately crashes with exit code `1`.

Moving on to a different issue then ;-)
I'll need more detailed information. 

> do `% git commit`, Emacs starts in server mode

I.e. you call `emacsclient -t some-file`. That's not enough to start Emacs. There needs to be an existing `emacs` instance that already has a running server.

> Emacs ... immediately crashes with exit code `1`

Are you sure it is `emacs` that "crashes" and exits? Or isn't it rather `emacsclient` that fails to connect to `emacs` and returns with 1, which then causes `git commit` to also return with 1?

**Comment by volodymyrprokopyuk** [comment]
First of all thank you very much for your support @tarsius !

I've pulled your latest changes from the Magit repository and I've added `(add-hook  'find-file-hook 'git-commit-setup-check-buffer)` after `(load "~/.emacs.d/magit/lisp/magit-autoloads.el")` in my configuration file (I'm not very sure that this is the right way to apply your recent change as the suggested solution in the commit message is not so comfortable to use). Now the results of syntax highlight on `% git commit` depend on whether the `emacsclient` starts for the first time and causes Emacs server to start or the Emacs server has already started and the `emacsclient` just connects to the already running Emacs server as below:
- **Before** adding `(add-hook  'find-file-hook 'git-commit-setup-check-buffer)` to the configuration file
    - `emacsclient` **first run** (Emacs server starts). Emacs shows the commit message buffer without syntax highlighting
    - `emacsclient` **second run** (Emacs server is already running). Emacs shows the commit message buffer without syntax highlighting
- **After** adding `(add-hook  'find-file-hook 'git-commit-setup-check-buffer)` to the configuration file
    - `emacsclient` **first run** (Emacs server starts). Emacs (or `emacsclient`) crashes with `1` exit code as before
    - `emacsclient` **second run** (Emacs server is already running). **Congratulations!** Emacs shows the commit message buffer with very nice syntax highlighting

The only issue that still persists is to make working commit message buffer syntax highlighting on `% git commit` when the server is starting and `emacsclient` has been launched for the first time.

Probably this can help: `% git rebase -i` launches Emacs with correct syntax highlighting when the `emacsclient` starts for the first and subsequent times. Couldn't the `% git rebase -i` initialization mechanism be also used for the `% git commit` use case?

Thank you very much @tarsius for the fantastic job you are doing with Magit! These issues are minor things.

**Comment by tarsius** [comment]
> emacsclient first run (Emacs server starts). Emacs (or emacsclient) crashes with 1 exit code as before

As in:

```
hint: Waiting for your editor to close the file... /usr/local/bin/emacsclient: can't find socket; have you started the server?
To start the server in Emacs, type "M-x server-start".
/usr/local/bin/emacsclient: No socket or alternate editor.  Please use:

        --socket-name
        --server-file      (or environment variable EMACS_SERVER_FILE)
        --alternate-editor (or environment variable ALTERNATE_EDITOR)
error: There was a problem with the editor 'emacsclient'.
Please supply the message using either -m or -F option.
```

?

**Comment by tarsius** [comment]
See https://github.com/magit/magit/wiki/FAQ#when-committing-from-the-command-line-then-git-commit-mode-isnt-used. Does that leave anything unanswered?
