### ISSUE TITLE
git pre-commit hook doesn't find files when run under magit

### ISSUE THREAD

**Issue by martin-schwenke** [magit/magit#3419]
(1) what behavior you expected

Added a git pre-commit hook that attempts to match only *.[ch] files:

git diff-index --check HEAD -- :/*.[ch]

When I run "git commit" manually the commit fails because a have a whitespace error in one of the files being commited.  So, I expect magit to have the same behaviour when I commit.

  (2) what behavior you observed

When I commit using magit then the pre-commit hook does not fail.

The problem appears to be that <path> arguments to git commands do not seem to match when run under magit.  I have tried adding additional git commands to the hook for debugging.  Without <path> arguments, I see the full contents of the commit.  With <path> arguments, I get no output.  Experiments show that running git from the command line with similar <path> arguments works fine.

  (3) and how we can reproduce the issue.

Use the above in a pre-commit hook and attempt it commit a file foo.c that has trailing whitespace on a changed line.

Also post the output of

  M-x magit-version RET

Magit 2.11.0, Git 2.16.3, Emacs 25.2.2, gnu/linux

Any ideas?    Is this a bug?

Thanks...

**Comment by npostavs** [comment]
Try `git --glob-pathspecs diff-index ...`.

**Comment by martin-schwenke** [comment]
Hmmm... then I get:

```fatal: global 'literal' pathspec setting is incompatible with all other global pathspec settings```

**Comment by npostavs** [comment]
Oh, maybe you need `--no-literal-pathspecs` too.

**Comment by tarsius** [comment]
For clarification, I think what @npostavs is getting at is that Magit always calls `git` with `--literal-pathspecs` (because that makes things easier) and that `git` then passes on that configuration to other `git` subprocess it starts recursively. Because your hook depends on other settings, you have to explicitly override the settings that were imposed by Magit.

**Comment by npostavs** [comment]
Right, maybe we should add a FAQ for this? It's come up a couple of times on gitter:

https://gitter.im/magit/magit?at=57c6f287d42df13066100180
https://gitter.im/magit/magit?at=5873ea96074f7be763adb0cf

**Comment by martin-schwenke** [comment]
Cool.  Thanks, got it!

The cleanest recommendation for hook scripts might be to simply unset the environment variable near the top of the script:

unset GIT_LITERAL_PATHSPECS

That means that all subsequent git commands get it, rather than having to add an option to each one.

Thanks, again!

**Comment by tarsius** [comment]
I have added an entry to the faq.

**Comment by asottile** [comment]
hitting this as well here: https://github.com/asottile/seed-isort-config/issues/5

instead of `magit` setting this environment variable, could it instead invoke `git` instead as `git --literal-pathspecs ...`?  this would probably jive better with other tools (and imo be much less surprising!)

**Comment by npostavs** [comment]
> instead of `magit` setting this environment variable, could it instead invoke `git` instead as `git --literal-pathspecs ...`?  this would probably jive better with other tools (and imo be much less surprising!)

That *is* what magit currently does. It's `git --literal-pathspecs ...` that invokes itself with the environment variable set when running other subcommands. Surprise! ;)

**Comment by asottile** [comment]
augh, git whyyyyy :'( -- I guess the other way to "fix" this would be to change any place where a path is passed to prefix `:(literal)`, but I imagine that'd be a pain for you guys :(

**Comment by rpatterson** [comment]
Not strictly related, but I wanted to capture my distantly related findings somewhere Google'able.  One may encounter a somewhat related issue because under magit `stdout` is a pipe.  In Python, and I imagine possibly something similar in other languages/situations, this means that `sys.stdout.encoding` is `None` where otherwise it is a string representing the encoding, such as `utf-8`.  For Python code run as a part of a VCS hook that depends on `sys.stdout.encoding` not being `None`, such as towncrier, this can result in an error:
```
...
  File ".tox/py27/lib/python2.7/site-packages/towncrier/check.py", line 44, in __main
    .decode(getattr(sys.stdout, "encoding", "utf8"))
`TypeError: decode() argument 1 must be string, not None`
```

See [this SO answer for a workaround](https://stackoverflow.com/a/4027726/624787).
