### ISSUE TITLE
Different project names in different magit buffers

### ISSUE THREAD

**Issue by Compro-Prasad** [magit/magit#3506]
1. What I want: Buffer names always match a directory/project name

2. See buffer names in the following two screenshots:
![`magit-status` screenshot](https://user-images.githubusercontent.com/11143962/42266910-48beeabe-7f95-11e8-9767-23ca387ac106.png)
Buffer name is: `magit: .emacs.d`
![Commiting screenshot](https://user-images.githubusercontent.com/11143962/42266954-607293cc-7f95-11e8-9cad-a9dc06c38c17.png)
Buffer name is: `magit-diff: emacs-config`
Why are the project names different? One is `emacs-config` while the other one is `.emacs.d`?

3. How to reproduce the issue
    - Make a repository under `/tmp/abc`
    - Create a symlink to this repository say: `/tmp/link2abc`
    - Run `magit-status` under `/tmp/link2abc`. Note the buffer name. It will be `magit: link2abc`
    - Make some changes to the repository and commit from the buffer `magit: link2abc`. When writing the commit message, note the buffer name of the diff buffer. It will be `magit-diff: abc`.
```
    M-x magit-version RET

    Magit 2.13.0-70-g1e2f1686, Git 2.18.0, Emacs 27.0.50, gnu/linux
```
It sure isn't a huge issue. But it might be very confusing for users who can't understand why are the project names different. It took me almost a week to figure this out.

**Comment by tarsius** [comment]
When `magit-diff` or some other command is invoked from the status buffer or a file inside the working tree, then the name of the buffer derives from the value of `default-directory`. The same is the case when showing the diff from the `COMMIT_EDITMSG` buffer, but the `default-directory` of that file is different because it is not located inside the working tree - it is located inside the git directory. The `default-directory` of that file is beyond Magit's control because it is `git commit` that decides what it should be by using `$EDITOR /path/to/.git/COMMIT_EDITMSG`. Git resolves symlinks when doing so, while Magit does not when setting the `default-directory` of the status and other Magit buffers. So there's not really anything that can be done about this.

**Comment by Compro-Prasad** [comment]
symlinks can also be followed using `file-truename` in Emacs Lisp

**Comment by tarsius** [comment]
Emacs, and by extension Magit, can be told to follow symlinks when opening files. But you probably wouldn't want that because then e.g. visiting `~/.emacs.d/init.el` would result in `~/where/the/wild/repos/are/emacs-config/init.el` being visited.

**Comment by tarsius** [comment]
If you do want that, then `(setq find-file-visit-truename t)` should do the trick.

**Comment by Compro-Prasad** [comment]
@tarsius Thanks a lot. How can I stop processing of recursive symlink problems if any in Emacs?

**Comment by tarsius** [comment]
You can tell Emacs to not follow symlinks (that's the default), but as far as I can tell the issue you are having is that *Git* is following symlinks and I don't think you can tell it not to do that.

**Comment by Compro-Prasad** [comment]
No, thats resolved! I was just asking about recursive symlinks. Does it cause any freezes? C-g is enough to stop the freeze? Thats all.

**Comment by tarsius** [comment]
Well you can of course create symlink bombs or circular symlinks, and I don't know how Emacs copes with things like that, but a fairly short symlink chain should not cause any issues I think.
