### ISSUE TITLE
Act on the specific branch or tag at point

### ISSUE THREAD

**Issue by yurikhan** [magit/magit#3530]
Consider a log buffer with multiple branches and/or tags pointing at the same commit.

Currently (2.13.0), `(magit-branch-or-commit-at-point)` returns the same name for all positions within the log line.

It would be nice if placing the point on a specific branch or tag label caused `(magit-branch-or-commit-at-point)` to return that specific branch or tag. This would allow, for example, switching to “the other” branch pointing at the same commit, or deleting “the other” branch, without having to type out its name.

I can achieve that effect by moving the invocation of `thing-at-point` higher:

```diff
 (defun magit-branch-or-commit-at-point ()
   (or magit-buffer-refname
+      (thing-at-point 'git-revision t)
       (magit-section-case
         (branch (magit-ref-maybe-qualify (oref it value)))
         (commit (let ((rev (oref it value)))
                   (or (magit-name-branch rev)
                       (magit-get-shortname rev)
                       rev)))
         (tag (magit-ref-maybe-qualify (oref it value) "tags/")))
-      (thing-at-point 'git-revision t)
       (and (derived-mode-p 'magit-revision-mode
                            'magit-merge-preview-mode)
            (car magit-refresh-args))))
```

but this has the (probably undesirable) effect that parts of the commit message summaries that correspond to existing branches, tags, or commit hashes, are also picked up. The proper solution would probably involve marking up branch and tag labels with text properties.

**Comment by tarsius** [comment]
I've pushed a draft.

**Comment by yurikhan** [comment]
Nice. Some feedback: 

* `b b`, being the generic “checkout this” command, should probably pick up tag names, too. Currently, it prefers a branch at the same commit, if any exists.

* Corner case: Suppose I have a local branch `foo` and its push target is `origin/foo` and they are at the same commit. In this case, the log collapses them into one label `origin/foo`, where `origin/` is in magit-branch-remote face and `foo` in `magit-branch-local` face.

    Currently, `b b` on such a label always picks up the remote branch `origin/foo`.

    I think, in contexts where either a local or a remote branch is expected, it would make sense to pick up the local branch if point is within `foo` and the remote branch if within `origin/`.

* Also it looks like `magit-branch-delete` is using some other mechanism to determine the default, so is not affected by this improvement.

**Comment by tarsius** [comment]
1. Checking out anything but a local branch results in a detached HEAD. If we checkout something else that is referring to the commit at point, then it doesn't matter if its a remote branch, tag, or the revision hash itself, the result will always be exactly the same.

   So what doesn't work is placing point on the tag name in order to force a detached HEAD. I guess that could be a bit surprising. But doing it that way is actually more work than using `M-p` in the minibuffer to get to the "next completion history element", which in this case always is the commit message. (I don't know if that is the actual key binding and what the command is called, since I use `ivy-mode` with my own key bindings).

   It also would be a lot of work to implement this for very little gain, so I won't do it.

**Comment by tarsius** [comment]
I've pushed the second iteration.

**Comment by yurikhan** [comment]
Okay, thanks.
