### ISSUE TITLE
Make behavior of magit-commit-diff configurable

### ISSUE THREAD

**Issue by NimoTh** [magit/magit#3577]
I usually enter git-commit mode by doing `git commit -a` from command line. That means, nothing is staged and `last-command` is none of the magit commands. 
Current behavior of `magit-commit-diff` in this case is to show either diff from HEAD^ to working tree (`magit-diff-while-amending` I suppose) or show staged changes (`magit-diff-staged` I suppose). What I really need, though, is `magit-diff-working-tree`, which is selected when invoking `git commit --all` via magit, i.e. when `last-command` is `magit-commit-all`. I cannot even switch to HEAD vs. working tree via <kbd>C-c C-d</kbd>.

Please add a configuration option, which allows me to set the default behavior of `magit-commit-diff` in case `last-command` is none of magit's commands and nothing is staged.

Also see my Stack Exchange question on the topic: https://emacs.stackexchange.com/questions/41408/magit-shows-magit-diff-with-head-instead-of-head-when-invoked-from-console

**Comment by tarsius** [comment]
Customizing such an option would not only result in the correct diff to be displayed in cases where previously the wrong diff was displayed, it would also result in the wrong diff to be displayed in cases where previously the correct diff was displayed.

There are other instances of the wrong diff being displayed, which I find more pressing because they occur even when invoking the commit from within Magit, which is the primary use-case. I have added a note about this issue to #3246. I will look at this issue when I deal with that and am closing this issue.
