### ISSUE TITLE
Offer documentation in ePub format

### ISSUE THREAD

**Issue by dilyanpalauzov** [magit/magit#3579]
Please consider offering the documentation for download in ePub format.

With https://github.com/jlhg/texinfo2epub it is easy to convert .texi to .epub .

**Comment by tarsius** [comment]
If you implement this, then don't *use* that script. Use it for inspiration only.

**Comment by tarsius** [comment]
What about it?

I think it would be nice to make the manual available in ePub format, but I don't think it is urgent, so I won't get to it anytime soon. But if someone else has experience with this or is willing learn, then I would welcome that very much.

Doing so would of course involve investigating the available options. Pandoc may be one of them, but it may or may not be the best choice. A good place to start would be to learn about the available options and to compare the outputs. If you do, then please post those so that others can easily compare them too.

Once the best candidate has been selected a `epub` make target has to be added. Other targets such as `clean` and `publish` and some variables also have to be adjusted. And `.gitignore`.

**Comment by dilyanpalauzov** [comment]
I propose starting short term with texinfo2ebup or anything else and. ater check if there are better options.  This is better than not offering documentation in ePub format anytime soon.

**Comment by mrwacky42** [comment]
> What about it?
To clarify: what about `pandoc` as a nice way to target `epub`, since you said not to use the linked shell script.

**Comment by tarsius** [comment]
An epub is now available at https://magit.vc/manual/magit.epub. A link should appear on https://magit.vc/manual/ after CDN cache invalidation.

`pandoc`'s output was unusable. `makeinfo`+`xsltproc` is reasable, but you might still prefer the pdf.

This is how much time I am going to invest in this. If you want something better, then consider contributing that yourself.

**Comment by dilyanpalauzov** [comment]
How long will the CDN cache invalidation take?

**Comment by dilyanpalauzov** [comment]
I go to https://magit.vc/ → Documentation, and there I see: “Magit User Manual (single-page, pdf, org)”.  Epub is not mentioned.  The returned headers include:
  Date: Tue, 09 Oct 2018 11:11:58 GMT
  Last-Modified: Tue, 09 Oct 2018 11:09:08 GMT

I do not see anything cache related. The same happens when I use curl.

**Comment by vermiculus** [comment]
It's definitely there: https://magit.vc/manual/

Search "epub".

**Comment by vermiculus** [comment]
Ohh, I see. It's not listed under the 'Documentation' header, but it is under 'all manuals'.

**Comment by dilyanpalauzov** [comment]
Indeed, I meant the text behind https://magit.vc/#documentation.

**Comment by dilyanpalauzov** [comment]
Dears, it is very good that the documentation is now offered in ePub format.  To make most use of it, please consider amending  https://magit.vc/#documentation to state near “Magit User Manual (single-page, pdf, org)” also epub.

Referencing epub only from https://magit.vc/manual/ is imperfect: the one who searches for epub will conclude, that it is not offered, after seeing at https://magit.vc/#documentation many formats.  Alternatively, you can remove the formats from https://magit.vc/#documentation and guide/force the user instead to visit https://magit.vc/manual/.

Thanks in advance for taking time to polish this.
