### ISSUE TITLE
magit-format-patch support a limiting to files

### ISSUE THREAD

**Issue by CeleritasCelery** [magit/magit#3601]
Asked on [Stack Overflow](https://emacs.stackexchange.com/questions/44960/create-patch-for-one-file-with-magit) and it seems this feature is not supported. With command line git, you can use `git format-patch [commit_hash] [file]` to generate a patch for a single file. However `magit-format-patch` does not support that and generates a patch for all files. It would be ideal if one could mark files in a diff buffer (similar to staging changes) and then use `W p` to generate a patch for the marked files (or hunks).

**Comment by tarsius** [comment]
The selection or location of point is already used to select the commit(s) for which to create a patch, so we have to use a separate mechanism to select the files. That's necessary anyway because otherwise, given files `foo`, `bar` and `baz`, it would not be possible to select only `foo` and `baz`.

Adding an optional `files` argument and reading files using `magit-completing-read-multiple*` is probably a good approach. This should probably be hidden behind the prefix argument and/or an option.

**Comment by tarsius** [comment]
> This should probably be hidden behind the prefix argument and/or an option.

Or use a file argument similar to the one of the log popup.

**Comment by kyleam** [comment]
> Or use a file argument similar to the one of the log popup.

That was my thinking.  The main issue I see with that is deciding on a key since `=f` is already taken for `--from`.  Perhaps `=F`?

**Comment by tarsius** [comment]
> Perhaps `=F`?

I went with that.
