### ISSUE TITLE
Bisect fails silently with uncommitted changes

### ISSUE THREAD

**Issue by contrapunctus-1** [magit/magit#3604]
For sake of context, I almost always use Magit and almost never the git command line. I'm also pretty new to git, which explains how I ran into this.

I tried bisecting (`B B`), but after selecting the good and bad revisions, nothing happened. The process buffer had nothing to show, either. It was after a lot of trial and error that I realized that this was because I had uncommitted changes. In hindsight, this was pretty obvious, but perhaps Magit can warn when this happens?

Magit 2.13.0-205-g0e818e9d, Git 2.11.0, Emacs 25.1.1, gnu/linux

GNU Emacs 25.1.1 (i686-pc-linux-gnu, GTK+ Version 3.22.11) of 2017-09-15, modified by Debian

**Comment by tarsius** [comment]
Are you sure that the uncommitted changes are what is causing the problem?

On the first attempt I created some random uncommitted changes that did not touch any of the files that are modified by the commits that are being bisected and it worked.

On the second attempt I made sure the uncommitted changes touched files that are modified by one of the relevant commits, expecting a failure when bisect attempts to checkout but cannot because that would result in the lose of the uncommitted changes.

Instead I got silent failure and it turned out that it was because I was so preoccupied with making sure that there would be a conflict, that I accidentally flipped the good and bad revision. When I re-ran the command on the command line I got:

```
Some good revs are not ancestors of the bad rev.
git bisect cannot work properly in this case.
Maybe you mistook good and bad revs?
```

On the third attempt I payed closer attention to what I was doing and got the expected error, *displayed in the status buffer:

```
Bisecting: 0 revisions left to test after this (roughly 0 steps)
error: Your local changes to the following files would be overwritten by checkout:
	lisp/magit-submodule.el
Please commit your changes or stash them before you switch branches.
Aborting
```

I suspect that you did the same as I did in my second attempt and will add an assert to prevent that from happening.

**Comment by tarsius** [comment]
> I suspect that you did the same as I did in my second attempt and will add an assert to prevent that from happening.

Actually I can reproduce the issue now as you reported it. When the initial checkout fails due to conflicts, then that failure is silent as you described.

**Comment by tarsius** [comment]
Added an assert for that too.
