### ISSUE TITLE
Yubikey support is broken

### ISSUE THREAD

**Issue by ezeenova** [magit/magit#3605]
It appears as though Yubikeys should be supported, judging by this piece of code: https://github.com/magit/magit/blob/8adbe43554d5a36acf1de6a23f4395bfa82a85e2/lisp/magit-process.el#L161

However, as of 20180928.1153 magit does not detect my Yubikey Neo.

**Comment by tarsius** [comment]
Please look at the output using `$` -- what is the prompt used by this device?

**Comment by ezeenova** [comment]
This is the output of $:
```
128 git … fetch origin

fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
I am not sure what you mean by prompt. I normally use pinentry to input the PIN.

**Comment by tarsius** [comment]
I am afraid I don't remember how this is supposed to work. I guess that it still works the way it is supposed to work, but that you try to do something different.

The feature that magit supports is this: Something produces output like "Yubikey for HOST:", magit detects that and forwards the prompt to the user, the user touches the device, which acts as a hid device and "types" some secret, magit sends the secret to the process that asked for it.

> I normally use pinentry to input the PIN.

Sounds like you do something different then. Or do you touch the device at that point instead of typing the secret?

Maybe you could link to the tutorials that you used to learn how to do this on the command line. (It actually works on the command line, right?)

**Comment by ezeenova** [comment]
It does work on the command line, yes. I use git over ssh, and when I want to talk to the remote I insert the Yubikey into a USB port and enter whatever command I want to run. At that point pinentry prompts me for the Yubikey's PIN, and then the command runs. I do not use the Yubikey's touch functionality. I followed this guide to set it up: https://github.com/drduh/YubiKey-Guide

The Yubikey can be used in one of two ways:
1. It can be used as a smart card to store GPG keys. This is what I am doing. In this specific case, I have configured the remote ssh server to accept the authentication subkey on the Yubikey in place of a typical ssh key.
2. It can generate one-time passwords for multi-factor authentication. I am not using this functionality in this case.

**Comment by ezeenova** [comment]
You are right, if I start emacs from the command line it works as expected. I haven't been able to figure out which environment variables are needed, exactly; I tried loading GPG_AUTH_SOCK and GPG_AGENT_INFO into emacs, but that didn't help.

Running emacs from the command line is an acceptable workaround for now. I'll keep trying to get it to work when starting emacs normally, and will update this if I find a solution.

Thanks for the help!

**Comment by Wheest** [comment]
An issue that I was also having up until 5 mins ago.

The following variables are different in my emacs env, relative to bash.

- `KEYID`:  id of SSH key I think, missing in eshell
- `SSH_AUTH_SOCK`: different in eshell.  In bash is: `/run/user/1000/gnupg/S.gpg-agent.ssh`

By setting both of these variables to what they were in bash, `git push` now works with magit!

Hopefully this helps anyone in the past or future.
