### ISSUE TITLE
magit stash masking errors

### ISSUE THREAD

**Issue by CeleritasCelery** [magit/magit#3613]
When auto-detection is disabled (and I assume other scenarios as well) and you use `magit-stash`, magit will report `Cannot save the current index state`. This is masking the true error, which is  `fatal: no name was given and auto-detection is disabled`. It would be very helpful if `magit-stash` could pass up the actual error, providing more information to the user. 

Magit 2.13.0-196-g87de83da, Git 2.12.0, Emacs 26.1, gnu/linux

**Comment by tarsius** [comment]
In this case passing up the actual error would be too much work considering that if this error occurred for this command, then it would also occur for other commands (i.e. you would be informed about the issue shortly anyway).

`magit-stash` is not implemented using `git stash push` or `... save`, it is implemented in elisp. Ultimately `magit-git-string` fails to return a string due to this issue and I had the foresight to error out if that unexpected error occurs. However `magit-git-string` just returns a string or nil, it does not concern itself with the exit code and it discards standard-output.

Maybe at some point in the future I will write a replacement for that command and then this particular problem would be addressed too. The reason I have not done that yet, is that Emacs does not allow separating stdout and stderr into two different buffers, only one buffer and one *file*. Doing that for every call to `magit-git-string`--just because in some rare cases some misconfiguration could trigger an unexpected error--would be too costly given the limited benefit.
