### ISSUE TITLE
skipped "<key id>": secret key not available

### ISSUE THREAD

**Issue by f-florian** [magit/magit#3665]
Magit fails to sign commits with the following message:

"Waiting for Emacs...
gpg: skipped `"<key-id>":` secret key not available
gpg: signing failed: secret key not available
error: gpg failed to sign the data
fatal: failed to write commit object"

Although this message seems to be generated by gpg, the issue is specific to magit, since using 'git commit' on the command line the commit gets signed, and 'M-x epa-sign-file' also succeeds.

**Comment by tarsius** [comment]
The issue is not specific to magit. Most likely the issue is that you have configured gpg in your shells init file but do not start emacs from a shell. The solution is to also configure the environment exported by emacs. I use `keychain-environment` for that, others use `exec-path-from-shell`. Many others had this issue before you, so a search engine should be point you to useful information.

**Comment by f-florian** [comment]
> Most likely the issue is that you have configured gpg in your shells init file but do not start emacs from a shell.

I do not think this the issue, because 'M-x epa-sign-file' also succeeds, as I already said.

**Comment by tarsius** [comment]
Please provide information about the software that you use.

**Comment by f-florian** [comment]
Appearently some of the last updates fixed the problem, so I am not able to reproduce it anymore.

I will still provide software versions just in case they will be needed in the future:
Emacs 26.1
magit 20181113.1837 (melpa)
gpg (GnuPG) 2.1.11 (gpg (GnuPG) 1.4.20 is also present, but it comes later in $PATH)
libgcrypt 1.6.5
Linux 4.4.0-139-generic
Ubuntu 14.04

I also verified that my key is only supported by gpg2, so if magit was using gpg1 for some reason, not finding the key would be the expected behaviour
