### ISSUE TITLE
Why are added whitespaces highlighted, but removed ones aren't?

### ISSUE THREAD

**Issue by reputet** [magit/magit#3671]
### Description
> Please explain what behavior you expected what behavior you observed

In the **diff popup** I can see the whitespaces that were added, but not the whitespaces that were removed.
I expect to see all the removed whitespaces as well, not only added ones.
![image](https://user-images.githubusercontent.com/12900980/48850363-8cb1df00-edb9-11e8-9331-8af6402f54d2.png)

### How to reproduce the issue ###

Run emacs without a configuration file:
`$ emacs -q`

Run commands within emacs:
```
M-x eval-expression RET
(require 'package)
M-x package-initialize RET
M-x magit-status RET
```
Define a path to a repository that contains diffs with whitespaces.

### Notes
This issue may be related to another one:
[magit-diff-refine-hunk doesn't highlight whitespace #1689](https://github.com/magit/magit/issues/1689).
Keep in mind that the variable `smerge-refine-ignore-whitespace` is **t** by default.
However, even if I set its value to **nil**, and execute `diff-refine-hunk`, it doesn't work properly with some themes such as [zenburn](https://github.com/bbatsov/zenburn-emacs).
In this case it highlights the removed whitespace (in diffs popup) only when the block is **NOT** selected.
Look at the end of the line 3:
![image](https://user-images.githubusercontent.com/12900980/48853197-0947bc00-edc0-11e8-9d0b-93713162490f.png)

Otherwise, if the block **is** selected, removed whitespaces aren't visible:
![image](https://user-images.githubusercontent.com/12900980/48853244-1ebce600-edc0-11e8-991b-33dee1d43bfc.png)
Maybe it's a question about the **theme** and it is related directly to the issue in **zenbug-emacs** repository (I'm not sure)
[Incorrect magit diff inheritage #305](https://github.com/bbatsov/zenburn-emacs/issues/305)

If so, I don't expect you to resolve the "theme" problem, but **the main question is whether it is expected behaviour that "removed whitespaces" and "added whitespaces" are highlighted in a different way or not?**

### Magit version
Magit 20181115.1006, Git 2.19.1, Emacs 26.1, gnu/linux

**Comment by tarsius** [comment]
> Why are added whitespaces highlighted, but removed ones aren't?

Because I considered the former to be useful; not so much the latter. But now I can see how that can be useful too.

> `smerge-refine-ignore-whitespace`

Magit does not abuse the feature controlled by `smerge-refine-ignore-whitespace` for highlighting whitespace errors; it uses it to optionally highlight whitespace *changes*, including but not limited the removal or addition of whitespace errors.

I found (and will fix) a overlay priority bug in how that and our whitespace-error handling interact, but I don't think it that is related to:

> However, even if I set its value to nil, and execute diff-refine-hunk, it doesn't work properly with some themes such as zenburn.

I wasn't able to reproduce with `solarized-light`. Haven't tried `zenburn` yet.

**Comment by tarsius** [comment]
I have added two new options `magit-diff-paint-whitespace-lines` and `magit-diff-refine-ignore-whitespace`, which you can use to control the things we talked about here.

>> However, even if I set its value to nil, and execute diff-refine-hunk, it doesn't work properly with some themes such as zenburn.
>
> I wasn't able to reproduce with `solarized-light`. Haven't tried `zenburn` yet.

Are you still able to reproduce that?

**Comment by tarsius** [comment]
`uncommitted` is a new value for `magit-diff-paint-whitespace` now. (Only related to the above in that I noticed this had to be done while working on the above.)

**Comment by reputet** [comment]
Thank you for the quick reply!

> Are you still able to reproduce that?

Yes, nothing has changed in the **diff popup**.
I've downloaded the new version of magit from the melpa today.
`Magit 20181121.2055, Git 2.19.1, Emacs 26.1, gnu/linux`

I had set the variables and ran `diff-refine-hunk`

| variable                            | value |
|-------------------------------------|-------|
| magit-diff-paint-whitespace-lines   | 'all' |
| magit-diff-paint-whitespace         | t     |
| magit-diff-refine-ignore-whitespace | nil   |

But the removed whitespaces still aren't shown.
Am I doing something wrong here?

**Comment by tarsius** [comment]
> zenburn.
> In this case it highlights the removed whitespace (in diffs popup) only when the block is NOT selected.

That is a regression in that theme introduced by https://github.com/bbatsov/zenburn-emacs/pull/300. It uses the same color for highlighting the changes within a diff line and for highlighting of diffs, which is wrong because a highlighted diff can contain changes within individual lines.

However, as I mentioned, highlighting of whitespace errors and whitespace changes (including but not limited to errors) are unrelated (and are implemented differently). With the changes I have made highlighting of errors should always win against highlighting of changes, so it should not matter that highlighting of changes is broken - you should always see the errors. To make testing easier change the color used by `magit-diff-whitespace-warning` to something like blue.

You may also want to turn of `magit-diff-refine-hunk` completely. If that works as expected you can then turn it on again and if it doesn't work anymore after that, then that indicates that highlighting errors does *not* always win against highlighting of changes. But I don't think it will come to this.

> Am I doing something wrong here?

You probably got yourself in an inconsistent state; nothing that restarting Emacs wouldn't fix. By the way, going forward while debugging this please always restart after making changes, just in case.

**Comment by reputet** [comment]
> highlighting of whitespace errors and whitespace changes are unrelated
> To make testing easier change the color used by magit-diff-whitespace-warning

I realize that the ways how _whitespace **errors**_ and _whitespace **changes**_ work are different.
So I no longer expect the one to behave just like the another.
I also get that **whitespace errors** colour is altered when I change the value of **magit-diff-whitespace-warning**.

> please always restart after making changes, just in case.

No problem, but I still don't have any progress with **whitespace changes** highlightning.
I start emacs with the following command:

``` shell
emacs -q -l /tmp/debug_init.el
  # -q, --no-init-file. Do not load an init file.
  # -l file, --load=file. Load the lisp code in the file file
```
The config contains these lines:

``` emacs-lisp
(require 'package)
(package-initialize)
(setq magit-diff-paint-whitespace-lines "all")
(setq magit-diff-paint-whitespace t)
(setq magit-diff-refine-ignore-whitespace nil)
(setq magit-diff-refine-hunk nil)
```

And that's what I have:
![image](https://user-images.githubusercontent.com/12900980/48913960-12ea2600-ee8b-11e8-9e18-dc65b873c271.png)

Have I forgotten something or misunderstood?

**Comment by kyleam** [comment]
> (setq magit-diff-paint-whitespace-lines "all")

I haven't been following the discussion closely, so this may not be relevant, but: This should be a symobl (`'all` ), not a string.

**Comment by reputet** [comment]
> This should be a symbol `'all`, not a string `"all"`.

Indeed!
I was caught in my own unawareness of elisp.
The `'all` value did the trick!

Thank you, @kyleam!

@tarsius, thanks for your detailed answers and good job with the magic package!
