### ISSUE TITLE
add subdirectory .gitignore support

### ISSUE THREAD

**Issue by ensc** [magit/magit#3705]
It would be nice to have an option to add files to `.gitignore` within subdirectories.  E.g. when selecting `bar` in a dirtree like

```
.
|-- .gitignore
|-- foo
`-- subdir/
    |-- .gitignore
    `--  bar
```

and pressing e.g. `i + s`, `bar` would be added to `subdir/.gitignore` instead of adding an entry `/subdir/bar` in toplevel `.gitignore`.

This resembles the "ignore" operation of the deprecated `git-status`.

**Comment by tarsius** [comment]
Well to be honest I think the whole feature is unnecessary.

Personally I edit `.gitignore` manually, which isn't a problem because I have to do that very seldom.

I also think that users that have to add new ignore rules often should take a moment to reflect on what they are doing and if there is a better way.  My guess is that these users ignore new individual files as they are created and I think that it would be better to setup future proof rules that also cover future ignore-worthy files.  For example one should use the pattern `*.o` instead of adding `foo.o` and then later `bar.o`.

While the `magit-gitignore` commands allow specifying patterns I still think these commands are a mistake because the encourage sloppy rules.  To add good rules one has to look add the existing rules and that one can only do by looking at the relevant files.

These commands are here to stay, but I don't intend to improve them because I think users are better of not using them.

**Comment by tarsius** [comment]
Well that ship has sailed. I might add this after all.

**Comment by tarsius** [comment]
Done on the `transient` branch, which will be merged later this month.

**Comment by ensc** [comment]
thanks for adding this feature... I use it especially in cases like test suites where I have a subdirectory with lot of small programs (e.g. `test-foo.c`) which create binaries (e.g. `test-foo`) which can not be classified by patterns.

**Comment by tarsius** [comment]
How about

```
test-*
!test-*.c
```

**Comment by ensc** [comment]
Will work in a lot of cases.  But sometimes, there are hand-written `test-script` scripts or generated `.c` files.  Ignoring the binaries with `i` in old `git-status` was a fast way to filter out the generated files.
