### ISSUE TITLE
Horizontally scrolling `magit-log` buffer could free space taken by committers column

### ISSUE THREAD

**Issue by Alexander-Shukaev** [magit/magit#3715]
When I horizontally scroll the `magit-log` buffer, I see that committers column is blanked out but does not disappear completely.  That is somewhere in the middle of horizontal scroll I'm left with a lot of wasted empty space on the right of the buffer.  Either committers column should not be blanked out on horizontal scroll and keep the information displayed or the whole column should disappear altogether to leave more space for the actual commit messages to be displayed.

**Comment by tarsius** [comment]
The reason that this happens is that the text that appears in the margin of a line is a property of a single character.  If that character is not visible in its window, because of sidewise scrolling, then the margin does not display the specified text anymore.

Like any other text property, the `margin` property can be assigned to a range of characters, but to determine whether the margin text should be displayed only the "visibility" of the first character in the range is considered.

This is similar to the `before-string` property, which also can be set for a range of characters but is only displayed before the first character of that range.  So this behavior makes sense at least.  I still it is unfortunate in the case of `margin` because it leads to issues such as this.

> the whole column should disappear altogether to leave more space for the actual commit messages to be displayed.

IMO that is not worth the effort.
