### ISSUE TITLE
Accommodate `+` and `-` sings in diffs onto a gutter

### ISSUE THREAD

**Issue by Alexander-Shukaev** [magit/magit#3716]
How feasible/difficult it would be to move `+` and `-` signs out of the buffer onto a associated gutter in all diff-related modes?  I frequently find myself surfing through a project history and selectively copy/pasting snippets between different projects and of course I hate to delete a column of `+` or `-` signs afterwards (thanks to `evil` mode, it's easy but still very annoying).  Thanks!

**Comment by tarsius** [comment]
Doing this would make it easier to copy these lines without the +/-/\s prefix characters.  At the same time it would make it *impossible* to copy *with* those characters and that is sometimes useful too.  And that's one downside from the top of my head.

I think such a feature would be a net *loss*.  Additionally it would be a lot of work to implement it and the potential for bugs is great, so I wouldn't even implement this if I though it would be a small *gain*.

**Comment by basil-conto** [comment]
> How feasible/difficult it would be to move `+` and `-` signs out of the buffer onto a associated gutter in all diff-related modes?

FWIW, if you have a recent checkout of the Emacs sources, you can have the built-in `diff-mode` place these characters in the fringe by setting `diff-font-lock-prettify` to a non-`nil` value. AFAIK this is not supported by Magit, though.

> I frequently find myself surfing through a project history and selectively copy/pasting snippets between different projects and of course I hate to delete a column of `+` or `-` signs afterwards

Unfortunately enabling `diff-font-lock-prettify` still includes these characters as part of any killed text. One way to work around this is to advise the buffer-local definition of `filter-buffer-substring-function` to strip such leading characters, similarly to what `diff-mode` does in order to strip `display` properties.

Another option which can work for both `diff-mode` and Magit modes is to use a custom killing command. See, for example, the following Emacs SE post by @kyleam: https://emacs.stackexchange.com/a/36090/15748

**Comment by tarsius** [comment]
@basil-conto Thanks for digging this up. I vaguely remembered that command but couldn't find it.
@kyleam What about adding that command to Magit?

**Comment by kyleam** [comment]
> What about adding that command to Magit?

Sure, happy to do that.  Perhaps it'd even make sense to add the marker stripping behavior directly to `magit-copy-section-value` under the condition

    (and current-prefix-arg
         (magit-section-internal-region-p)
         (magit-section-match 'hunk))

**Comment by tarsius** [comment]
Sounds good.
