### ISSUE TITLE
Error (use-package): magit/:catch: Cannot open load file: No such file or directory, magit-popup

### ISSUE THREAD

**Issue by DrWaleedAYousef** [magit/magit#3749]
All of of a sudden, emacs gives me at startup this message:
```
Error (use-package): magit/:catch: Cannot open load file: No such file or directory, magit-popup
```
I did not change anything in my `.emacs` file. My configuration part of `magit` is:
```
(use-package magit)
(setq auth-sources '("~/.authinfo.gpg"))
(setq magit-process-find-password-functions '(magit-process-password-auth-source))
(use-package magithub
  :after magit
  :ensure t
  :config (magithub-feature-autoinject t))
```

**Comment by tarsius** [comment]
Magit now uses the new `transient` package instead of `magit-popup`. You can find the announcement here: https://emacsair.me/2019/02/14/transient-0.1.

Third-party packages that add their own popups but only depend on `magit` instead of depending explicitly on `magit-popup` now have to add that dependency because installing `magit` no longer pulls in `magit-popup`.

Users who define their own popups have to do the same.

Third-party packages that modify `magit`'s popups have to be modified to instead modify `magit`'s "transients", which the former have been replaced with.

(Lets keep this issue open for a while.)

**Comment by DrWaleedAYousef** [comment]
Thanks so much; 
so do you suggest I change something in my `.emacs` to avoid this error message at startup?

**Comment by tarsius** [comment]
```emacs-lisp
(use-package magit-popup
  :ensure t ; make sure it is installed
  :demand t ; make sure it is loaded
  )
```

The `:demand` should be unnecessary provided the libraries that need `magit-popup` at least `require` it explicitly.

And since magithub hasn't been updated yet (see https://github.com/vermiculus/magithub/issues/402), you will likely have to comment out the respective `use-package` form for the time being.

**Comment by PiyushDatta** [comment]
I am still getting the error, this is what I've done.

`
(use-package transient
  :ensure t ; make sure it is installed
  :demand t ; make sure it is loaded
  )
(use-package magit-popup
  :ensure t ; make sure it is installed
  :demand t ; make sure it is loaded
  )

(use-package magit
  :ensure t)`

**Comment by tarsius** [comment]
That's a different error but thanks for the report, it's something that needs to be fixed quickly.

I have just released `magit-section` as a separate package. Unfortunately I did not update `magit` to depend on it. I am fixing that now but it could take a few hours until it makes it onto Melpa, so you will have to explicitly install `magit-section`.

**Comment by usatosi** [comment]
> That's a different error but thanks for the report, it's something that needs to be fixed quickly.
> 
> I have just released `magit-section` as a separate package. Unfortunately I did not update `magit` to depend on it. I am fixing that now but it could take a few hours until it makes it onto Melpa, so you will have to explicitly install `magit-section`.

I installed magit-section version 2.90.1 and got the following new error.

`defvar: Symbol’s value as variable is void: magit-section-mode-map`

Do I need add configs to my init.el?

**Comment by tarsius** [comment]
Do you use the released version of Magit or a development snapshot?
If it is the later, then just install the development snapshot of Magit-Section as well.

Do you install Melpa-Section explicitly or is the package manager bringing it in as a dependency?

This could be a big issue. I'll investigate right away.

There isn't actually a `magit-section-2.90.1` but I cannot prevent Melpa from making something available under that name. But if Melpa retroactively changed `magit-2.90.1` to depend on the fake `magit-section-2.90.1`, then I need to fix.

**Comment by tarsius** [comment]
Yep, `magit-section.el` was missing from `magit-2.90.1`, so I was forced to add it back to the `magit` snapshot as well.

**Comment by usatosi** [comment]
> Do you use the released version of Magit or a development snapshot?
> If it is the later, then just install the development snapshot of Magit-Section as well.
> 

My fault. I mixed development snapshot of Magit and released version of magit-section. Fixing Magit version to 2.90.1 solved the issue.

Thank you for your great work and quick answer.
