### ISSUE TITLE
Keeping up with git changes

### ISSUE THREAD

**Issue by davep-github** [magit/magit#3755]
Add the ability to specify arbitrary parameters to git commands on their popups.

Since there is some latency between a git change and magit's support for it, it would be nice if there was a way to specify arbitrary parameters to a command on its popup.
E.g. an Option, say =X
```
=X Extra Options ()
And I can edit thus:
X: --src-prefix='<index>/' --dst-prefix='<working>/'
-->
=X Extra Options (--src-prefix='<index>/' --dst-prefix='<working>/')

```
There could be a switch to make it permanent per command, or for the current execution only.
It might be nice to make it something like a printf format string where you can substitute known parameters.  E.g. --src-prefix='<%c>/', where %c is replaced by the current working directory.
Or allow environment variables to be interpolated.

**Comment by vermiculus** [comment]
Wouldn't actually adding the command to the popup be preferred? You can do this on-the-fly in your config. (I would link to how this is done, but I cannot find up-to-date documentation on this -- I'm sure it exists though.)

**Comment by tarsius** [comment]
I assume you are talking about the `--src-prefix` and `--dst-prefix` arguments **of `git diff`**.

While both Magit-Popup and Transient support adding additional arguments to existing commands (previously known as "popups" and now as "transient prefix commands"), these particular arguments cannot be added.

In order to be able to reliably parse file-names in diffs, Magit explicitly uses the `--no-prefix` argument when calling `git diff`. This protects against users changing the prefixes using the respective Git variables.

We are not doing this because I think it is better/prettier/... to use no prefix but because we have to be absolutely sure that the path we get is what we expect. We could probably make this more flexible, but this would be a lot of work for not very much benefit, so I don't intend to do it.

**Comment by davep-github** [comment]
I don't know if that will help.  I'll look into it.  BTW: do you mean my magit config or git config?However, at this time I'm interested in new, unknown parameters.I also thought of an alias, but didn't want to duplicate the code for the other popup params, because that would begin to drift from any new releases.
thanks again,davep

-----Original Message-----

**Comment by tarsius** [comment]
As I said, `transient` the library that is now used to implement all this support adding new arguments to existing prefix commands.

I am open to adding new arguments. At the same time I don't want make every argument available by default, that would be to overwhelming. Luckily `transient` provides a mechanism for adding arguments *without* making them available by default.

You should read the [release announcement](https://emacsair.me/2019/02/14/transient-0.1/) and the manual, in particular the parts that the announcement links to.

----

The arguments that you have mentioned here cannot be added because doing so would break Magit, but if you want other arguments to be added, then please open a pull-request or feature-request.

> However, at this time I'm interested in new, unknown parameters.

We can add arguments that existed for a long time but which were not available from the respective popups until now. And we can add arguments that were added in the very latest Git release too.

**Comment by davep-github** [comment]
tarsius:  was replying to vermiculus and I missed his reference to transient.  When I made my reply I hadn't seen your message.
thanks for the quick reply, though.  And magit.

regards,
davep
