### ISSUE TITLE
Is `magit-diff--initial-value` can be changeable?

### ISSUE THREAD

**Issue by ccqpein** [magit/magit#3793]
I noticed several versions ago, `Limit to files` in `magit-diff` has the default value is current file. Also `=f` change to `--` to limit file.

Is it possible I can custom `Limit to files`'s default value? I prefer this config to empty files.

Thanks

**Comment by tarsius** [comment]
Logs are only limited to files if the log command was invoked from a file-visiting buffer. That hasn't actually changed. It is not possible to change the default file limit, it is always the visited file when invoked from a file-visiting and empty when not.

**Comment by ccqpein** [comment]
I understand. My personal hobbit is check diff of unstaged of whole repo. Then `S` staged them all. So if `Limit to files` can empty default. It might be neat. However, it just my personal idea, it is not a big deal.

**Comment by tarsius** [comment]
Also note that saving *any* value for the log and diff popups/transients does not work right now. That's a bug and I am working on it. I *might* add an option to disable limiting the diff to the current file, while working on fixing the bug.

**Comment by tarsius** [comment]
You didn't say how you invoke log, but I am guessing you do so by typing `C-c M-g l` from a file-visiting buffer. If so, then you can get the behavior you want by adding this to your init file.

```lisp
(transient-replace-suffix 'magit-file-dispatch 'magit-log-buffer-file
  '("l" "Log" magit-log-current))
```

Alternatively you could also just type `C-c M-g L l` instead. But that is quite cumbersome due to all the modifier switching that this involves.

By the way, I recommend that you bind `C-c g` instead of `C-c M-g` to `magit-file-dispatch` like so:

```lisp
(define-key magit-file-mode-map (kbd "C-c g") 'magit-file-dispatch)
```
