### ISSUE TITLE
commit: support --no-gpg-sign

### ISSUE THREAD

**Issue by benma** [magit/magit#3832]
No way to specify `--no-gpg-sign` when signing at the moment as far as I can tell.

**Comment by tarsius** [comment]
With the switch from `magit-popup` to `transient` that argument was hidden by default. You can unhide it as described in the release announcement: https://emacsair.me/2019/02/14/transient-0.1.

**Comment by kyleam** [comment]
@tarsius But that's --gpg-sign, not --**no**-gpg-sign, right?  The latter could be useful for temporarily disabling `commit.gpgSign`.

**Comment by benma** [comment]
Kyle that's correct.

**Comment by tarsius** [comment]
Ah, overlooked that.

Yes that argument would have to be added explicitly. As documented at https://magit.vc/manual/transient/Modifying-Existing-Transients.html.

I am not done with `transient` yet. This touches on the planed features mentioned in #2610 and #2993.

**Comment by tarsius** [comment]
#2610 even being about the same argument. I guess I will use that argument when implementing the prototype.

I looked into this when I was implementing `transient` but when I looked for arguments that could benefit from this it turned out there were way fewer of them than I had expected, so I did not prioritize this feature.
