### ISSUE TITLE
Prevent magit-log from auto filling the current file

### ISSUE THREAD

**Issue by CeleritasCelery** [magit/magit#3844]
Currently running `magit-log` from `magit-dispatch` (`C-x M-g l`) will auto-fill "limit to files" to the current file.  This is in contrast to running it through the status buffer (`C-x g l`) which will launch the log for the whole project. There is currently no good way to run the log for the current project without either opening the status buffer first (which can be slow) or clear the file limit every single time (`C-x M-g l - - C-S-DEL RET l`). 

If a user wants to open the log for the current file, that can be done with `magit-file-dispatch` (`C-c M-g l l`). `magit-log` from `magit-dispatch` should open the log for the whole project (by default) and behave similar to calling it in the status buffer.

**Comment by tarsius** [comment]
Agreed.

**Comment by ktfleming** [comment]
@tarsius This bug seems to have returned with commit https://github.com/magit/magit/commit/06f3ffa868f9aaa4ddeaf65811f315fdb6a4a626. Looking at the code now,

https://github.com/magit/magit/blob/d7f1b6c7f334553db628602cf4b0fbb66bb52c53/lisp/magit-log.el#L356-L358

it looks like it's binding the value of `(eq transient-current-command 'magit-dispatch)` to the variable `not`, rather than calling function `not`, which I assume was the intention.

**Comment by tarsius** [comment]
Thanks! Fixed in 5b4c4aea1bd90b296373777f0588acbe2ea6eec5.
