### ISSUE TITLE
magit-log-arguments is missing

### ISSUE THREAD

**Issue by Deanseo** [magit/magit#3850]
The recently updated version seems to have discarded `magit-log-arguments` as follows:

> Error (use-package): magit/:config: Symbol’s value as variable is void: **magit-log-arguments**

I usually give `--color` to the list as such:

      (add-to-list 'magit-log-arguments "--color")

`(magit-version)` returns the following:

> Magit 20190428.2220, Git 2.17.2 (Apple Git-113), Emacs 26.2, darwin

So far I've tried removing literally all packages installed through MELPA and turning Emacs off and on again (so that all needed packages will be automatically re-installed again by `use-packages`), ended up having no luck.

Please let me know if I've misunderstood anything in that regard.

**Comment by tarsius** [comment]
[Magit switched from `magit-popup` to `transient` a few weeks ago](https://emacsair.me/2019/02/14/transient-0.1/). As a result setting and saving log and diff arguments *using the respective popups* was broken until two weeks ago.

The problem was variable like `magit-log-arguments`. Transient doesn't use such variables anymore, but the log and diff popups did complicated things with those variables that went beyond what other popups did, so I couldn't just drop these variables.

This is why your usage of these variables did not break when Magit switched to `transient` but only now.

>      (add-to-list 'magit-log-arguments "--color")

These variables were never intended to be used like that. The intention always was that the user changes the arguments to their liking in the popup and then invoke the "save current settings for future use" command.

`magit-popup` used a separate variable for each popup, while `transient` uses a single variable for all popups (now called transients) and then stores that in a dedicated file.

The problem with modifying arguments like you did was that this broke the intended way of editing and saving arguments. Say you used it to remove `--color` argument again and saved that. Then you restart Emacs and it is put back by the above form.

The proper way to set and save arguments is documented [here](https://magit.vc/manual/transient/Saving-Values.html).

**Comment by Deanseo** [comment]
Big thanks for the kind support!
