### ISSUE TITLE
No completion on magit-diff-range

### ISSUE THREAD

**Issue by qleguennec** [magit/magit#3857]
The [manual](https://magit.vc/screenshots/#invoking-git-commands-using-popups) says for diff range:

> Or you might want to show the diff for an arbitrary range, in which case you would press r. After doing so you can type the range with completion

With emacs-Q on b4d6320d0c5ac6777802b2ede84701958dc43f98, I don't get any completion.

**Comment by tarsius** [comment]
That command uses `completing-read-multiple` instead of just `completing-read`. Those functions behave a bit differently its possible that you have to type `TAB` with the former where you wouldn't have to with the latter.

I use `ivy-mode` so this behaves a bit differently for me than with builtin completion but I just tried with that off and it works too.

**Comment by qleguennec** [comment]
Indeed I was missing the `TAB` part. Should I update the doc I linked to make it more explicit?

**Comment by tarsius** [comment]
> Should I update the doc I linked to make it more explicit?

I don't think that is necessary. We cannot add "in order to see the available completions type `TAB`" everywhere where we mention that completion is available. That's just how completion works by default across pretty much all of Emacs.
