### ISSUE TITLE
Stage all with out confirmation when only one file is unstages

### ISSUE THREAD

**Issue by BenBals** [magit/magit#3871]
This is just a really small thing, but it might make Magit just a little bit smoother than it already is.

When I stage all files, Magit asks for a confirmation (which is good), but that seems unnecessary when staging just a single file. What do you think?

**Comment by tarsius** [comment]
Users are asked for confirmation if and only if there already are staged changes. These staged changes might have been laboriously picked from all the original unstaged changes and also staging everything else would lose that work. If the same lines were modified after staging then staging can even lose intermediate versions.

Of course that can happen regardless of what is being staged. It can happen if a single file is being staged or even a single hunk. But Magit cannot just ask for confirmation for any staging action, users would quickly disable it. So a compromise had to be found and I settled on:

* If and only if there are already any staged changes, then ask for confirmation before staging everything.

You would prefer:

* If and only if there are already any staged changes, then ask for confirmation before staging everything. Except if that would only stage one file, in that case don't ask for confirmation.

And these aren't the only two options. E.g.:

* If and only if there are already any staged changes, then ask for confirmation before staging everything, provided the changes that would be staged touch at least one of the files that already have staged changes.

A line could be drawn somewhere. My variant is easy to understand and protects from fat-fingering `S` instead of `s` in all cases. Other users would prefer the line to be drawn elsewhere but not everyone would agree on where that should be.

**Comment by BenBals** [comment]
Thanks for your reply. I see your motivation now. It is much more thoughtful than what I suggested. I am happy with this arrangement.
