### ISSUE TITLE
git password security issue

### ISSUE THREAD

**Issue by kosantosbik** [magit/magit#3893]
Expected: Yanking the kill before the password.
Observed: Yanking the password.
How to reproduce: 
1) Open `magit-status` buffer
2) Choose any pull or push command which requires a password
3) Type in password which looks like number of dots (........)
4) Use backward-kill-word command (C-backspace by default)
5) Finish the command and close `magit-status` buffer
6) Yank (C-y by default)

Backtrace:

`Debugger entered--Lisp error: (quit)`
`  read-string("Enter passphrase for key '/home/kosantosbik/.ssh/id_rsa': " nil t nil)`
`  read-passwd("Enter passphrase for key '/home/kosantosbik/.ssh/id_rsa': ")`
`  magit-process-password-prompt(#<process git<3>> "Enter passphrase for key '/home/kosantosbik/.ssh/id_rsa': ")`
`  magit-process-filter(#<process git<3>> "\015Enter passphrase for key '/home/kosantosbik/.ssh/id_rsa': ")`
`  (lambda (proc str) (magit-process-filter proc str) (with-editor-process-filter proc str t))(#<process git<3>> "\015Enter passphrase for key '/home/kosantosbik/.ssh/id_rsa': ")`

Magit-version: 20190505.1100

When you kill the password with backward-kill-word it saves the original text into kill ring. You can yank it after. It shouldn't save it into kill ring

**Comment by kyleam** [comment]
I'm not spotting any place where magit alters the behavior of `read-passwd`.  Do you see the same behavior when calling `read-passwd` directly?

I've tried triggering this by either calling `read-passwd` directly or following your steps but replacing 5 with <kbd>C-g</kbd>.  In both cases I get dots when I yank.

**Comment by kosantosbik** [comment]
There is no `read-passwd` in my command list. Where is it located exactly?

**Comment by kyleam** [comment]
It's a non-interactive function in subr.el.

**Comment by kosantosbik** [comment]
I'm unable to reproduce the outcome you describe. Have you tried using it from magit as I described?

**Comment by kyleam** [comment]
> I'm unable to reproduce the outcome you describe.

So when you call `read-passwd` directly and then `backward-kill-word`, the original text is saved to the kill ring?  If so, the issue lies outside of magit.

> Have you tried using it from magit as I described?

Not quite.  As I said above, I "followed your steps but [replaced] 5 with <kbd>C-g</kbd>".  When I do that, text killed with `backward-kill-word` is yanked as dots, the same behavior I see if I call `read-passwd` directly.  The reason I'm replacing 5 is that, at first glance, it doesn't appear essential and I don't have at hand a repo/setup where I can successfully do an operation that requires a password prompt.  If you could confirm that you don't see the issue (i.e. dots are yanked) when (1) you use `read-passwd` directly and (2) iperform you steps but replace 5 with <kbd>C-g</kbd>, I can take the time to set things up so that I can follow 5.

**Comment by tarsius** [comment]
I have looked at the definition of `read-passwd` and concluded that it would always do this. You can test by putting the cursor after `(read-passwd "test: ") and typing `C-x C-e`. The user input is made to look like a string of dots using the display text property. The string is the actual user input. I am not sure whether this is considered a feature or whether it would be so complicated to not do it like this. The author of this probably concluded that if the user copies the input, then they want the actual input not a bunch of dots.

In any case this is not implemented in Magit and would have to be changed in Emacs.

**Comment by npostavs** [comment]
> I've tried triggering this by either calling `read-passwd` directly or following your steps but replacing 5 with C-g. In both cases I get dots when I yank.

I was confused about this too; you *think* that you get dots, but that's just because you're yanking into an Emacs buffer, which applies the display properties (which are also yanked). If you `C-u C-x =` on one of the dots (or copy into a different program), you'll see it's actually a letter.

**Comment by kyleam** [comment]
@npostavs Thanks.  I should have realized that :$  It's also easy to see by looking at the kill-ring value.  For example:

```
("kill"
 #("fine" 0 1
   (display ".")
   1 2
   (display ".")
   2 3
   (display ".")
   3 4
   (display ".")))
```

**Comment by npostavs** [comment]
>  I should have realized that :$

I have to admit, I only realized it after reading @tarsius' comment.

**Comment by kosantosbik** [comment]
Thanks for the explanation @tarsius :)

**Comment by kyleam** [comment]
> Thanks for the explanation @tarsius and @npostavs :)

@kosantosbik So that means you understand why you were seeing what you did?  Your recipe suggests you were yanking into an Emacs buffer, so why weren't the display properties being applied for you?

On top of that, I'm confused that after my initial response that "I'm not spotting any place where magit alters the behavior of read-passwd. Do you see the same behavior when calling read-passwd directly?", you seemed continue to conclude it was Magit-specific, but the knowledge that read-passwd uses the display text property somehow cleared that up for you.

As already established, this is outside of Magit, so it's not worth a long response, but if there's a short explanation, I'm curious.
