### ISSUE TITLE
FUNDING.yml incorrectly formatted?

### ISSUE THREAD

**Issue by fosskers** [magit/magit#3903]
At least, when I press the new `Sponsor` button beside `Watch`, that's what it claims.

![2019-06-18-072545_1918x1078_scrot](https://user-images.githubusercontent.com/229679/59692687-58a96b80-919a-11e9-8d67-981f4c1e5fe2.png)

**Comment by tarsius** [comment]
I though that error was only shown to me. It is annoying that it is not.

I have not yet been accepted to "GitHub Sponsors". Never-the-less I added the corresponding entry to the `FUNDING.yml` of a few dozen repositories because (1) that meant I would not have to add another few dozen commits once I am accepted and (2) at the time I did that the "invalid" entry did not result in an error, instead it was silently ignored.

Well, I will have to live with this and hope that it doesn't discourage anyone from making a contribution.

**Comment by tarsius** [comment]
Also, how did you theme Github?

**Comment by Silex** [comment]
If you look at https://github.com/saberland/create-portfolio/blob/master/.github/FUNDING.yml, I think what is incorrect in your FUNDING.yml is that you added `github: tarsius`.

If you remove it the error should disappear, and then you can add it back once you were accepted by github.

**Comment by Silex** [comment]
I realised it's exactly what you said, so ignore my comment :wink:

**Comment by tarsius** [comment]
On the other hand, I should probably do it here anyway (but leave the respective files in all the other repositories alone).

**Comment by fosskers** [comment]
@tarsius Github Dark, my man :sunglasses:  https://github.com/StylishThemes/Github-Dark
