### ISSUE TITLE
magit-file-rename should rename untracked file's buffer as well

### ISSUE THREAD

**Issue by happy-barney** [magit/magit#3916]
Renaming tracked files (staged is enough) works as expected, buffer name is renamed as well.

Renaming untracked files, though it renames files, does not rename respective buffer name.

**Comment by tarsius** [comment]
Untracked files are being renamed using the built-in `rename-file`, which does not rename the buffer. I sometimes use this command directly and then wonder why it doesn't at least offer to do so. I never use `magit-file-rename` to rename untracked files because those don't really have anything to do with git/magit in my eyes.

`magit-file-rename` could be changed to also rename the buffers visiting untracked files I suppose. What do others think?

**Comment by kyleam** [comment]
> `magit-file-rename` could be changed to also rename the buffers visiting untracked files I suppose. What do others think?

The logic is already present in the "tracked?" clause, so I think it'd make sense to get rid of the outer `if` and use "tracked?" to decide whether to `(magit-call-git "mv" ...` or `(rename-file ...` (following up either call with a refresh).  This would mean the prefix argument isn't considered for `rename-file` and that renaming an untracked file would be subject to the same user-error's, but IMO that consistency is a good thing.

As a side note, I think we should call `set-visited-file-name` with a non-nil ALONG-WITH-FILE.  Otherwise I get queried about saving the file when I call `magit-refresh` after calling `magit-file-rename` to rename a tracked file.
