### ISSUE TITLE
Release version 2.90.2

### ISSUE THREAD

**Issue by skangas** [magit/magit#3918]
Version 2.90.1 was released on Nov 16, 2018.  Could you please consider tagging a new version 2.90.2 for those of us using melpa-stable?

Thanks,
Stefan Kangas

**Comment by tarsius** [comment]
I plan to create a release in August.

It will be named 2.91.0 not 2.90.1 because there are changes than would justify just a bug fix release. Hell I am even considering making it 3.0.0, which is why I don't want to rush it.

And yes, I should release more often and plan to do that after 3.0.0.

I did see https://github.com/magit/transient/issues/50#issuecomment-511109196 by the way.

**Comment by skangas** [comment]
Thank you!  We're all just eager to start using the new features.

**Comment by sdhoward** [comment]
We are still hoping for a new stable release. What is the new ETA?

**Comment by tarsius** [comment]
Yes. This month.
