### ISSUE TITLE
global-git-commit-mode takes considerable init time

### ISSUE THREAD

**Issue by cyrus-and** [magit/magit#3931]
I use `(global-git-commit-mode)` in my init file and it takes ~0.3 seconds which seems quite a lot. Especially if we consider that the following achieves the same effect and it's basically immediate:

```lisp
(add-to-list 'auto-mode-alist `(,git-commit-filename-regexp . git-commit-setup))
```

So the the purpose of this issue is twofold:
1. the above is really equivalent to calling `(global-git-commit-mode)` or there are some dark cases?
2. in case, would it be possible to implement it directly in Magit?

I used the following `.emacs` to test this:

```lisp
(package-initialize)

(global-git-commit-mode)
;; (add-to-list 'auto-mode-alist `(,git-commit-filename-regexp . git-commit-setup))

(message (emacs-init-time))
```

---

Magit 20190727.1910, Git 2.20.1, Emacs 26.1, gnu/linux

**Comment by basil-conto** [comment]
See also some precedent in #3070.

**Comment by tarsius** [comment]
So to answer your questions; yes that works too and please continue to add it to your init file literally.

**Comment by cyrus-and** [comment]
@basil-conto thank you for #3070 that made this possible

@tarsius thanks for your reply, I wonder then why one should prefer the `(global-git-commit-mode)` approach or why it's still in Magit if slower.

**Comment by tarsius** [comment]
1. The entries in `auto-mode-alist` are supposed to reference modes. Adding a function that is not a mode instead is a hack. That's fine if the user does it knowingly but I would rather have the package do the correct thing instead of the performance hack.

2. Most people don't use the global mode because they commit using Magit in which case it is needed. I sometimes commit from the command line but when I do, then Magit and thus git-commit have already been loaded in 99% of all cases. So I don't enable the global mode either.

**Comment by cyrus-and** [comment]
Got it, thanks for the explanation.
