### ISSUE TITLE
magit-clone with submodules

### ISSUE THREAD

**Issue by pereiragc** [magit/magit#3939]
It would be nice to have the options `--recurse-submodules` or `--recursive` when cloning repos.

**Comment by tarsius** [comment]
Are you aware that `magit-clone` behaves as a prefix command when it is invoked with a prefix argument or when `magit-clone-always-transient`? I am guessing you are.

While `--recurse-submodule` is not offered as an infix argument be default, that is only because that argument is not enabled by default. See [Enabling and Disabling Suffixes](https://magit.vc/manual/transient/Enabling-and-Disabling-Suffixes.html) to learn how to change that.
