### ISSUE TITLE
config format.outputDirectory ignored on stash / Transform / format patch ?

### ISSUE THREAD

**Issue by muihlinn** [magit/magit#3954]
I have git config `format.outputDirectory` pointing to an specific place to have the generated patches there. It seems to work fine from `W` `c` (saving patches where I do expect them) or `W` `s` (asking for file name).  If I try to format patch from stash ( `z` `f` ) the patch is generated silent and succesfully but it doesn't respect `format.outputDirectory` neither asks for file name, dropping the file in root level. 

is this a bug, the expected (git) behavior or am I missing something from the manuals?

**Comment by kyleam** [comment]
> I have git config `format.outputDirectory` pointing to an specific place to have the generated patches there. It seems to work fine from `W` `c` (saving patches where I do expect them)

<kbd>Wcc</kbd> (`magit-patch-create`) calls `git format-patch ...`, so honoring `format.outputDirectory` is expected without any intervention from Magit's end.

> or `W` `s` (asking for file name).

<kbd>Ws</kbd> maps to `magit-patch-save`, and that boils down to `git diff ... REV >OUTFILE`, where OUTFILE is read from the user without considering `format.outputDirectory`.  It does not use `git-format-patch` and is not intended to produce format-patch-like output (i.e., there is no message and it can't be fed to `git am`).  Because of this, I think it makes sense that it doesn't consider `format.outputDirectory`.  (You say this behavior is fine, but I'm going through it because I think `magit-stash-format-patch` is a similar case.)

> If I try to format patch from stash ( `z` `f` ) the patch is generated silent and succesfully but it doesn't respect `format.outputDirectory` neither asks for file name, dropping the file in root level.

This maps to `git stash show -p STASH >0001-SUBJECT.patch`.  Despite the function's name and naming scheme of the output file, `git-format-patch` isn't used and the content doesn't match the output of format-patch.  It is a plain diff like with `magit-patch-save`.  As with `magit-patch-save`, I think it's reasonable that it doesn't respect a configuration value for `git-format-patch`.

Looking at the definition of `magit-stash-format-patch`, I think two changes are worth considering:

  * Allow the user to specify the output file (perhaps based on a prefix argument)
  * Ask before overwriting an existing file.

Given that you think `magit-patch-save` works fine and it reads the file from the user but doesn't consider `format.outputDirectory`, I guess you'd think `magit-stash-format-patch` is ok too if it allows reading the file.

**Comment by muihlinn** [comment]
> Given that you think magit-patch-save works fine and it reads the file from the user but doesn't consider format.outputDirectory, I guess you'd think magit-stash-format-patch is ok too if it allows reading the file.

I had figured about the stash command ('cos is what I used from the command line), and that there should be a way to choose the pipe's end, although the default name is fine. I also found the nomenclature inconsistent or at least confusing given the variable name.

What you propose is perfectly reasonable. i'll just add to consider to ( somehow ) use the configuration value, if present, as starting point for the place to drop the files when reading for the user. Ultimately just reading from the user will be fine.

**Comment by tarsius** [comment]
Does your workflow involve using these commands a lot and it is a constant source of frustration that they don't put the patches where you would like them to? Or do you just use them once in a while and the annoyance of the files being saved elsewhere is minimal?

If its the latter, then I would rather not add any complications and leave things as-is. If you do use these commands a lot, then please explain why they are useful. I can imagine why they might be useful once in a while but if someone is using them regularly, then I would imagine that a better workflow was overlooked. I might be wrong though, that's why I ask.

**Comment by muihlinn** [comment]
> I might be wrong though, that's why I ask

it will be useful to be able to choose where to put the stash patch from magit, but I can manage as it is using the command line or with a bit of custom code. Good to have, but not a top-priority.

The most common use case: I use syncthing to keep projects synchronized across the local network / VPN, keeping all files under vc in .stignore (updated automatically by a git hook), so the "important" files are managed directly by git, and the companion files can be synced automatically.

When I have to swap computers/locations (which happens quite often) inevitably some code not yet ready to commit needs to be synced, so stashing it and generating a patch is an easy way to have the needed code ready in the other computer to resume work. Obviously having all that stuff in a directory simplifies greatly the administrative tasks across the involved tools.

**Comment by tarsius** [comment]
> When I have to swap computers/locations (which happens quite often) inevitably some code not yet ready to commit needs to be synced, so stashing it and generating a patch is an easy way to have the needed code ready in the other computer to resume work. Obviously having all that stuff in a directory simplifies greatly the administrative tasks across the involved tools.

I would recommend using branches instead (maybe using prefix such as `temp/`). That way you can sync the unfinished work using just Git instead of having to rely on some custom scripts.

> it will be useful to be able to choose where to put the stash patch from magit, but I can manage as it is using the command line or with a bit of custom code. Good to have, but not a top-priority.

I think I'll leave things as they are for now.
