### ISSUE TITLE
Make it work without Emacs

### ISSUE THREAD

**Issue by sdegutis** [magit/magit#3961]
I know this sounds a bit crazy, because by definition Magit is an Emacs client for Git. But I don't see anything about it that can't be duplicated in a basic terminal app. Magit is useful enough that people should be able to use it who don't use Emacs. (For example, Magit is literally the only thing I use Emacs for anymore, and I'd like to finally abandon Emacs for good.)

**Comment by sdegutis** [comment]
I'm also aware of tig and lazygit, but those don't even come close to the usefulness of Magit in the 5 minute I've tried them.

**Comment by kyleam** [comment]
> But I don't see anything about it that can't be duplicated in a basic terminal app

I predict you're not going to get many volunteers for trying to rewrite Magit as a terminal app.  But you might be interested in [this post by Jonas][0] about promoting Magit as an interface for non-Emacs users, particularly the last bit about the command-line interface.

[0]: https://emacsair.me/2017/09/01/magit-for-non-emacs-users/

**Comment by tarsius** [comment]
The tools mention in that post demonstrate that something similar to Magit can be implemented for other editors and IDEs. But these tools implement only a fraction of the features that Magit provides because nobody has invested the time needed to do it all and because these editors are less suited to be extended than Emacs.

Also IMO something like Magit that isn't an extension to an editor isn't really like Magit at all. For example, the ability to quickly navigate between a diff and the respective file is extremely important and at least parts of that functionality has to be implemented as an extension to the used editor.

So sure someone™ could implement something™ like Magit but it won't be us and it will take a long time.

**Comment by sdegutis** [comment]
> For example, the ability to quickly navigate between a diff and the respective file is extremely important

Maybe I'm the odd one out, but the only things I use Magit for are staging (especially of hunks and regions) and committing. Even this small subset of Magit is miles better than anything else. You're right that it'll take a long time for one person with limited time to rewrite this functionality as a terminal app, but I'm starting to think it's worth it, so I may just take a shot at it. Thanks for the encouragement :) and thanks for making Magit so useful that I'd want something just like it outside of Emacs!

**Comment by sdegutis** [comment]
Also you may want to take a poll to see how popular each major Magit feature really is, because I've tried using it for many things but only found this small subset really useful, and other people might feel the same. The result of it could be pruning a few features nobody really uses. Just a thought.

**Comment by tbagrel1** [comment]
As a workaround, is there a shell command/alias that could launch emacs with just a magit window in the current directory?
I would like to use it instead of typing `git status`, `git commit`, ... in my terminal all the time.

**Comment by madscientist** [comment]
Well, you can always simply run:

```
emacs --eval '(magit-status "<path-to-repo>")'
```

**Comment by dangom** [comment]
Is there a way to ship this command as a standalone?

I tried

```sh
emacs -nw -q -L magit/lisp -l magit/lisp/magit.el --eval '(magit-status "repo")'
```

but that doesn't cut it because magit depends on other package like dash. Thinking on the best way to install this on a shared computer so that colleagues can try it out. Suggestions welcome.
Also, old CentOS ships with Emacs 24.3, so not even sure I could just pull latest and have it work.

**Comment by tarsius** [comment]
> Is there a way to ship this command as a standalone?

People have implemented that before and some those scripts might still be available on the interwebs.

I don't currently plan to add such a script to Magit. Writing a script that works for 95% of users shouldn't be too hard, but providing support for the other 5% would be a lot of never ending work over the coming years.

> that doesn't cut it because magit depends on other package like dash.

Look at Magit's `default.mk` and reimplement its logic in a shell script.

> Also, old CentOS ships with Emacs 24.3, so not even sure I could just pull latest and have it work.

You cannot have your cake and eat it too. You either stick to ancient software for stability or you get new features. (But since I won't include a script in Magit this doesn't make a difference. You have to ship the script separately anyway.)

**Comment by tarsius** [comment]
> `emacs -nw -q ...`

Or just drop the `-q`, but yeah, that might lead to issues.

**Comment by dangom** [comment]
Thanks for the quick reply!
And indeed.... https://github.com/alphapapa/magit.sh

**Comment by tarsius** [comment]
I should probably add this to the FAQ.
