### ISSUE TITLE
Support for git switch and git restore

### ISSUE THREAD

**Issue by vxid** [magit/magit#3963]
Git 2.23 introduces the [git restore](https://git-scm.com/docs/git-restore/2.23.0) and [git switch](https://git-scm.com/docs/git-switch) commands, as an attempt to split `git checkout`.

I have no need for these commands personally as they are still experimental but perhaps you would be interested in adding them to magit once they are stable enough.

**Comment by tarsius** [comment]
Magit commands do both more and less than `git` commands. A single `git` command can usually perform many variants of a single operation and/or many different but closely related operations. A Magit command on the other hand is intended to perform one action. That action however may be composed of many operations (often implemented using a `git` command) and depending on what the target of the action is the operations may vary greatly.

Like Git, Magit uses the term "checkout" to mean both "checkout a file" and "checkout a branch". However, it does not have a `checkout` command that checks out either a file or a branch depending on arguments. Instead it has different commands that perform different kinds of checkouts and while many of them have the term "checkout" in their name, they are not thought of as variants of the same command. There is no single popup from which all of these commands are available and there is not a single place in the documentation where they are all documented. So Magit already does not share the issue with Git that "the `checkout` command does too much.

At this time I would guess that more users know that one can "checkout" both files and branches than people know that "branches can be switched to" and "files can be restored". In a few years that will have changed, but until then having the term "checkout" appear in the names of these commands instead of either "switch" or "restore" actually increases the odds that user find them.

As for using the commands `git switch` and `git restore` in *code*, that won't happen for many years because we have to support old `git` versions for many years, and `git checkout` already allows us to do all the things that these two commands bring to the table.

----

Lets have a quick look at the Magit commands that ultimately call `git checkout`. They can be split into three groups.

1. Check out a branch, with or without creating it first:
   * magit-checkout
   * magit-branch-and-checkout
   * magit-branch-or-checkout
   * magit-visit-ref
2. Check out a branch, special variants:
   * magit-branch-orphan
3. Check out some version of some file:
   * magit-checkout-stage (usually not invoked as a command)
   * magit-file-checkout (so this is basically Magit's only `git restore` command)
4. May call `git checkout` but the user does not have to and usually does not know that:
   * magit-discard (<kbd>k</kbd>)
   * a few others that are not worth mentioning in this context
   
----

So I don't think that we should, much less have to, do anything soon with regards to these new `git` commands. Eventually we will probably end up renaming the commands in group (3) and sprinkle the terms "restore" and "switch" in a few places to increase searchability.

I am closing this but expect that you and others will want to further comment, which you are of course welcome to do.

**Comment by kyleam** [comment]
Well put.  I agree there's nothing for us to do right now.

FWIW I found [this cheatsheet][0] by Duy (the author of `switch` and `restore`) very helpful.  Here it is, with numbers added:

```
1| checkout <branch>          -> switch <branch> (same "dwim" behavior)
2| checkout <revision>        -> switch --detach <revision>
3| checkout -b <branch> <rev> -> switch -c <branch> <rev>
4| checkout <path>            -> restore [--worktree] <path>
5| checkout <rev> -- <path>   -> restore --source=<rev> --worktree --staged <path>
6| reset <path>               -> restore --staged <path>
7| reset <rev> -- <path>      -> restore --source=<rev> --staged <path>
8| reset --hard               -> restore --source=HEAD --staged --worktree :/
9| (not available now)        -> restore --source=<rev> [--worktree] <path>
```

7 and 9 provide functionality that's not available in Magit.  7 was discussed in gh-2184, but adding it was punted on until it was clear there was a demand, and there hasn't been yet.

Given that 7 isn't in high demand, I don't expect 9 to be either.  The closest we have to 9 is `magit-reset-worktree` [*], which is equivalent to `git restore --source=<rev> :/` (i.e. it's not restricted by a path).

[*] I think this command was added by Jonas without much fanfare, and I haven't seen it talked about much, but it's great and I use it frequently.  Thanks :>

[0]: https://public-inbox.org/git/20190515111647.GA31209@ash/#t

**Comment by vxid** [comment]
@tarsius Thank you very much for this detailed answer, and I agree with general sentiment that these commands are, at least for the time being, superfluous.

**Comment by acid-bong** [comment]
Btw, `git switch` has one good advantage over `git checkout`: when the new branch doesn't have some files that the old one has, with `git checkout` (default action of Magit's "b b") they become untracked, while with `git switch` (which i personally use in terminal) the switch goes cleanly and no artifacts remain.
