### ISSUE TITLE
magit-section-highlighted-sections is always nil in magit-diff buffer

### ISSUE THREAD

**Issue by politza** [magit/magit#3976]
### Reproduce
1. Open a magit-diff buffer.
2. Set a breakpoint (or use tracing or message) on the function `magit-section-update-highlight`, move point in the diff-buffer and observe that the value of `magit-section-highlighted-section` is always nil on entrance to this function.

As a consequence, the complete body of this function is executed after every command.

### Cause
I think this might as well be an Emacs bug (or feature) and I remember running into this some years ago:  The mentioned variable is defined with `defvar-local` in `magit-section.el`,  but it is also accessed from `magit-mode.el` and `magit-diff.el`.  At these other sites, `setq` and `add-to-list` is used.  I think this confuses Emacs and has the effect, that `setq`ing the variable, at least in the `magit-diff` buffer, has no effect.

### Workaround
Unintern `magit-section-highlighted-section` and `defvar-local` it again.

### Environment
GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.10) of 2019-08-29
Magit 20190928.1729, Git 2.23.0, Emacs 26.3, gnu/linux

**Comment by tarsius** [comment]
I don't think it has anything to do with variables being local.

`magit-unhighlight-region` is being called more often than is useful here. Maybe that's due to a change in Emacs or in Magit, or maybe it was always broken. Will have to investigate.

**Comment by politza** [comment]
Yes, that's right.  I think, I got tricked by the fact that this function runs on a redisplay-hook. That's why the variable always shows up as nil in edebug.

Actually, I was trying to investigate why navigating the staged/unstaged diffs in the status buffer has much better performance then working in the diff-buffer which opens from the log-buffer, which is unbearably slow.  I've noticed this at work, where I have to use that Windows OS.

Anyway, it seems to me that `magit-unhighlight-region` does not need to reset `magit-section-hightlighted-section` before every redisplay.

**Comment by tarsius** [comment]
> Anyway, it seems to me that `magit-unhighlight-region` does not need to reset `magit-section-hightlighted-section` before every redisplay.

Fixing this issue will almost certainly involve doing that. However this also results in the "multi-section-selection overlays" not being properly being discarded when appropriate. I now vaguely remember what happened. I implemented this *without* this part. I did test it and it worked except for this part. I added this part to fix this issue but did not test sufficiently again to realize that this completely defeated why we did all this in the first place. So this was broken from the start in 1301db2c2e6e21beac50fa215d543c09bb8516c5.

This needs to be fixed, but its not trivial and since I need to do other things right now and this has been broken for so long it probably will be a while until I get around to it.
