### ISSUE TITLE
Warning on installation: "the function ‘magit-rev-parse’ is not known to be defined."

### ISSUE THREAD

**Issue by jzohrab** [magit/magit#3990]
On installing magit fresh from MELPA-stable, I got the following warning:

    In end of data:
    git-commit.el:946:1:Warning: the function ‘magit-rev-parse’ is not known to be defined.

I didn't have magit installed prior to the installation.

I'm running GNU Emacs 26.2 (build 1, x86_64-apple-darwin18.2.0, NS appkit-1671.20 Version 10.14.3 (Build 18D109)) of 2019-04-12

Magit 2.90.1, Git 2.20.1 (Apple Git-117), Emacs 26.2, darwin [2 times]

This may or may not be an error/bug, but it's always concerning to me to see things like this.  Cheers and thank you! jz

**Comment by kyleam** [comment]
This sounds a lot like gh-3987 (both the warning and the MELPA-stable part).  Looking at git-commit.el on 2.90.1, it seems like most uses of `magit-rev-parse` are guarded except for the one in `git-commit-run-post-finish-hook`.  That spot is fixed with f6e04ddd (git-commit-run-post-finish-hook: Do nothing if magit isn't available, 2018-12-19), which will be included in the next release.

**Comment by jzohrab** [comment]
Thanks @kyleam, cheers.
