### ISSUE TITLE
(magit-stash-drop) asks with (y-or-n-p) instead of (yes-or-no-p)

### ISSUE THREAD

**Issue by danielmartin** [magit/magit#3995]
In Magit, if you want to discard a stash by pressing `k`, you get prompted with a `y-or-n-p` question instead of a `yes-or-no-p` question, which is the preferred Emacs style in destructive actions. Is it intended? I see that the `magit-slow-confirmation` variable contains `(drop-stashes)` by default so maybe this is intended to work but it's not working 100% in the current codebase.

**Comment by kyleam** [comment]
`y-or-n-p` vs `yes-or-no-p` was discussed in gh-2752.  One of the examples there was for dropping a stash (and recovering a dropped stash was touched on in gh-2383 and gh-2746).  gh-2752 led to the addition of `magit-slow-confirm`.  But note that `drop-stashes` in `magit-slow-confirm` only applies for dropping a selection of stashes.  Here's the description of `drop-stashes` (from `magit-no-confirm`s docstring):

    `drop-stashes' Dropping a stash is dangerous because Git stores
    stashes in the reflog.  Once a stash is removed, there is no
    going back without using low-level recovery tools provided by
    Git.  When a single stash is dropped, then the user always has
    to confirm by accepting the default (or selecting another).
    This action only concerns the deletion of multiple stashes at
    once.

That says that for a single stash the user has to confirm through completion.  So why do you see the `y-or-n-p` prompt?  Since fece098d0 (magit-stash-{drop,pop}: ask for confirmation, 2017-11-06), which was a response to gh-2916, `magit-stash-drop` has an entry in `magit-dwim-selection` that tells `magit-completing-read` to ask for confirmation about the default value rather than offering a list of candidates.  When a command in `magit-dwim-selection` has a value of `ask`, `magit-completing-read` always uses `y-or-n-p`.  A blanket switch over to `magit-y-or-n-p`, which would respect a `magit-slow-confirm` value of `t`, would be too aggressive because commands in `magit-dwim-selection` aren't necessarily destructive.

One option would be to add another value like `ask` that would trigger a `magit-y-or-n-p` call, though I don't know that that's worth doing.  The issues linked above are only some of the issues around completion/confirmation, but I think they provide some indication of the different and conflicting opinions users have about this topic.

---

Looking at this issue, though, I noticed that `drop-stashes` does not work as advertised for a selection of stashes.  `magit-stash-drop` passes `magit-confirm` an action of `t`, not `drop-stashes`, so the underlying `magit-y-or-n-p` call always uses `y-or-n-p` unless `magit-slow-confirm` is set to `t`.  Adjusting `magit-stash-drop` (and `magit-stash-clear`) to pass `drop-stashes` as the action to `magit-confirm` would lead to the expected `yes-or-no-p` prompt, though that might lead to some other undesirable behavior that I'm missing.

<details>
<summary>patch</summary>

```diff
diff --git a/lisp/magit-stash.el b/lisp/magit-stash.el
index 2f94de1bf..1eae3bbee 100644
--- a/lisp/magit-stash.el
+++ b/lisp/magit-stash.el
@@ -229,7 +229,8 @@ (defun magit-stash-drop (stash)
   "Remove a stash from the stash list.
 When the region is active offer to drop all contained stashes."
   (interactive (list (--if-let (magit-region-values 'stash)
-                         (magit-confirm t nil "Drop %i stashes" nil it)
+                         (magit-confirm 'drop-stashes nil
+                           "Drop %i stashes" nil it)
                        (magit-read-stash "Drop stash"))))
   (dolist (stash (if (listp stash)
                      (nreverse (prog1 stash (setq stash (car stash))))
@@ -250,7 +251,8 @@ (defun magit-stash-drop (stash)
 (defun magit-stash-clear (ref)
   "Remove all stashes saved in REF's reflog by deleting REF."
   (interactive (let ((ref (or (magit-section-value-if 'stashes) "refs/stash")))
-                 (magit-confirm t (format "Drop all stashes in %s" ref))
+                 (magit-confirm 'drop-stashes
+                   (format "Drop all stashes in %s" ref))
                  (list ref)))
   (magit-run-git "update-ref" "-d" ref))
 
```

</details>

**Comment by tarsius** [comment]
:fireworks: You have earned the `historian` badge. :fireworks: 

> Looking at this issue, though, I noticed that `drop-stashes` does not work as advertised for a selection of stashes.

That might be intentional. I would think that it is more likely that one invokes one of these commands unintentionally than it is that one first unintentionally marks some commits and then unintentionally invokes `magit-stash-drop`.

**Comment by kyleam** [comment]
> That might be intentional.

Hmm, then I'm missing something.  In what scenario does the default `magit-slow-confirm` value of `(drop-stashes)` have an effect?  I'm not spotting an action of `drop-stashes` used anywhere in the code base.

**Comment by tarsius** [comment]
`magit-drop-stashes` did until ed7d2277336468a34d10a0d5bf54158fffad885e and I think that change was unintentional. This should be fixed as you suggested.

But I still think that `magit-stash-clear` should continue to prompt even if `drop-stashes` is a member of the option.

**Comment by tarsius** [comment]
Done that. So I think we are done here.
