### ISSUE TITLE
magit-copy-buffer-revision: Wrong type argument: number-or-marker-p, nil

### ISSUE THREAD

**Issue by cpitclaudel** [magit/magit#4001]
### Scenario

I'm trying to copy multiple strings from a magit-status window, using `C-M-w M-w`.

### Expected result

Current selection is appended to top kill-ring entry.

### Actual result

An error is shown in the message window

### Steps to reproduce

Select some text from the `magit-status` window.  Press `C-M-w M-w`.

### Backtrace:

```
Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p nil)
  copy-region-as-kill(nil nil region)
  magit-copy-buffer-revision()
  funcall-interactively(magit-copy-buffer-revision)
  call-interactively(magit-copy-buffer-revision nil nil)
  command-execute(magit-copy-buffer-revision)
```

### Version

Magit 20191030.1315, Git 2.17.1, Emacs 27.0.50, gnu/linux
I double-checked on master in emacs -Q

**Comment by kyleam** [comment]
Hmm, so magit is calling `copy-region-as-kill` with nil for `BEG` and `END` and a non-nil value for `REGION`.  That seems in line with the documented usage (copied from the current Emacs master, 99271ea8de5):

```
When called from Lisp, save in the kill ring the stretch of text
between BEG and END, unless the optional argument REGION is
non-nil, in which case ignore BEG and END, and save the current
region instead.
```

We're supply `REGION` and expecting `BEG` and `END` to be ignored. But when you call `append-next-kill`, setting `last-command` to `kill-region`, that's not what `copy-region-as-kill` does:

```elisp
(let ((str (if region
                 (funcall region-extract-function nil)
               (filter-buffer-substring beg end))))
  (if (eq last-command 'kill-region)
        (kill-append str (< end beg))
      (kill-new str)))
```

The `(< end beg)` is triggering the type error.  We could work around this by explicitly passing the region bounds in for `BEG` and `END`, though I'd say this is a bug that should be addressed in Emacs.

**Comment by tarsius** [comment]
> I'd say this is a bug that should be addressed in Emacs.

But we should still add the kludge for released Emacsen.

**Comment by kyleam** [comment]
> But we should still add the kludge for released Emacsen.

The spots affected by this are addressed with [km/copy-append].  I'll merge that tomorrow unless there are objections.

[km/copy-append]: https://github.com/magit/magit/compare/km/copy-append

**Comment by kyleam** [comment]
[ Note: These details are reassessing my bug comment, but they aren't relevant to the patch I proposed. ]

I said:

> I'd say this is a bug that should be addressed in Emacs.

Looking at the history touching this function, I think I was mistaken.  It seems pretty clear that 3472b6c682 (2013-10-29) introduced it as a way to indicate that `BEG` and `END` represented the region.  At that time the docstring read: "The optional argument REGION if non-nil, indicates that we're not just copying some text between BEG and END, but we're copying the region."  And in terms of behavior, the result is the same today as it was then: instead of calling `(filter-buffer-substring beg end)`, call `region-extract-function`, which ends up calling `(filter-buffer-substring (region-beginning) (region-end))`.  As to why going through `region-extract-function` is worth doing, I'm at a loss.  Since `BEG` and `END` should be the region bounds, it seems it'd always be equivalent behavior-wise to calling `copy-region-as-kill` with a nil `REGION`.

With 86130adf1e (Improve documentation of kill commands, 2015-12-07), the docstring snippet above changed to

```
When called from Lisp, save in the kill ring the stretch of text
between BEG and END, unless the optional argument REGION is
non-nil, in which case ignore BEG and END, and save the current
region instead.
```

Technically, that's just saying `BEG` and `END` are not considered when extracting the text (i.e. `region-extract-function` is called, as described above), not that `BEG` and `END` can be nil. But I do think it'd be reasonable for a reader to see that and conclude, "oh, instead of passing BEG and END, I can just pass a non-nil value for REGION".

**Comment by cpitclaudel** [comment]
> Technically, that's just saying BEG and END are not considered when extracting the text (i.e. region-extract-function is called, as described above), not that BEG and END can be nil. But I do think it'd be reasonable for a reader to see that and conclude, "oh, instead of passing BEG and END, I can just pass a non-nil value for REGION".

Definitely a doc bug, if not a code one.  `ignore BEG and END` is pretty clearly saying that beg and end should not matter, nil or not.
