### ISSUE TITLE
Plausibility of dropping dash in favour of seq?

### ISSUE THREAD

**Issue by rnkn** [magit/magit#4005]
I was pleasantly surprised when following my [recent suggestion](https://github.com/magit/transient/issues/66) to drop dash in favour of seq in transient, Jonas made the change within hours. Thus I am now emboldened to make an even more outlandish suggestion... _that magit also drop dash..!_

With transient, save for a small bugfix, it was almost a 1:1 replacement. I don't expect magit will be such an painless undertaking, so for now I'm just posing the question: what's the plausibility of such a possibility?

The benefits I see are:
- one less external dependency
- ridding the user's global namespace of dash's prefix-less symbol names
- a small sense of accomplishment

**Comment by tarsius** [comment]
That however is unlikely.

I don't really care about any of the benefits you list. The reason I removed it from transient is that it is a library that I would like to one day add to gnu elpa and I feel that *such* libraries/packages should limit their dependencies to the minimum. For magit that makes much less sense I think.

**Comment by rnkn** [comment]
Would you welcome a PR, or would this be counter your design goals?

**Comment by tarsius** [comment]
It's not "counter my design goals", but its also not "pro-goals". I don't rule out doing this myself eventually, but `dash` has served as well so I am in no hurry at all to remove it. Also because I still might want to *eventually* get magit added to emacs I would want you to assign your copyright to the fsf before merging, while at the same time I do not want to bring this possibility to the attention of the emacs maintainers *at this time*.

What you could do at this time to slightly increase the odds of me doing this eventually is to compile a list of all `dash` functions that we currently use along with their `seq`, `cl` or other built-in counterpart(s). (For anaphoric functions you could just list the built-in non-anaphoric counterparts.)
