### ISSUE TITLE
interactive rebase should start one commit later

### ISSUE THREAD

**Issue by ensc** [magit/magit#4021]
When starting an interactive rebase (`r i`) the selected commit will be included.  This is very confusing and differs from command line `git` where `git rebase $branch` does not include `$branch`.

When working with merges, it becomes difficulty to select a good starting point with the actual behavior.  E.g. how can I do a `git rebase -i warrior` in magit with a commit tree

```
4d6fd51 *   warrior-next Merge branch 'master' into warrior-next
        |\  
439ac52 | * master master-next gitlab/master-next gitlab/master CI: lowered sstate lifetime
858e4dc | * updated submodules
bccfaa3 | * CI: switched to F31
1da732f | * make: ease changing oe-core layer
bacc733 | * updated submodules
60883fb * | warrior gitlab/warrior-next gitlab/warrior updated submodules
```

**Comment by tarsius** [comment]
This has come up before and I still think Magit's way is better. See #3380 for an explanation.

> E.g. how can I do a `git rebase -i warrior` in magit with a commit tree

Instead of `r i` use `r - i e` and then `RET` to confirm the commit at point.

**Comment by ensc** [comment]
I think, `git` way is better and more logical. It does not hurt very much when you start the rebase too late but starting it too early requires often a lot of manual work to fixup rewritten history.  I am using magit for several months now and still stumbling about this behavior.

The `r - i e` might be a workaround for now, but misses some cool features like navigating in the commit graph.

**Comment by tarsius** [comment]
Magit provides several "edit just this one commit" commands that are based on `git rebase`. (Of course technically subsequent commits also have to be written, but if a user e.g. rewords the message of that one commit, then that's the only commit that *the user* edits.)

It would be very strange if in order to edit that single commit one had to select the previous commit.

From editing "this command" it is not very fare to editing "this command any maybe subsequent ones too". It makes sense for all of these commands to behave consistently with regards how the beginning of the range is treated.

> It does not hurt very much when you start the rebase too late

If I want to edit a certain commit and select that commit to do so, and then I am only given the opportunity to edit the subsequent commits but not that commit itself, then that actually does hurt because I am not even able to do what I wanted to do.

> but starting it too early requires often a lot of manual work to fixup rewritten history.

Please provide examples, I don't think this has ever happened to me. And of course the solution that I suggest is not to endure that manual work, but to use `r e` instead of `r i`. 

You appear to be rebasing in different situations than I do. The need to rebase after I have merged already never seems to arise for me. That's why examples would help. Maybe be a bit verbose about what you are doing and why in any given example. Post before and after graphs. Try to use generic commits, so that I can more easily follow along. Maybe even post the setup shell script. Instead of your above example something like this might have been more useful:

```
46aa618 *   master Merge branch 'other'
        |\  
3cb2e1b | * other e
b28e18c | * d
0bc4934 * | c
        |/  
79c74d8 * b
9ca1b03 * a
```

> The `r - i e` might be a workaround for now, but misses some cool features like navigating in the commit graph.

I am not sure I understand. Are you talking about this: `r i` *without* a commit at point shows a log to let the user select a commit, while `r e` does not? It might be that just have to teach `r e` to do the same.

You are advocating for the behavior of `r i` to be changed, but maybe you should just use another command instead. And maybe that alternative command has to be improved to serve that role better or maybe a completely new command is needed.

Above I suggested that you use `r - i e`, but maybe `r e` is enough? I don't know because you never said what you want to do, just which commit you want to select. Based on what I *assume* your motivation is I think `--interactive` is not necessary and actually a bit of a distraction, so in a way you should have used `r e` instead of `r i` anyway, even if the latter did treated the selected commit the way you would want it to. I assumed you just want to flatten the merge.

**Comment by ensc** [comment]
> It would be very strange if in order to edit that single commit one
> had to select the previous commit.

When you modify a single commit, you operate on this commit.

But rebasing works on a range of commits. E.g.

```sh
git rebase --onto foo foo
```

(which is the long variant of `git rebase foo`) affects all commits of
`HEAD` being not in `foo`.

Implying `foo^..HEAD` (as done by magit) lowers flexibility and
immediately results into the question, why the first parent but not
the 2nd one.


> If I want to edit a certain commit and select that commit to do so,
> and then I am only given the opportunity to edit the subsequent
> commits but not that commit itself, then that actually does hurt
> because I am not even able to do what I wanted to do.

When I do a rebase, I want to normalize a range of commits and apply
them on top of another one (which is the start of this range in most
cases (no explicit `--onto`)..

I do **not** want work on a set of commits which might start 10 pages
(`git log` output) below the actually selected commit (which might be
the case for `foo^`).

Example:

```
00000 * [stable-next]
00001 *   Merge branch master
      |\
00001 * | some fix
00100 | * [master] some enhancement
00002 * | Merge branch master
      |\|
00101 | * foo
00102 | * bar
00003 * | [origin/stable] Merge branch 'master'    <<<<<<<<<<
      |\ \
      | |/
00103 | * baz
      ...
00199 | *
00004 *\| Merge branch master
00005 *
```

I am on `00000` (stable-next) and want to do a `git rebase -i
origin/stable`.  Within the todo list I add

```
x git merge master
```

on top.  Usually this is enough (merges and `master` commits are removed
automatically during the rebase because they are noops), sometimes I have
to remove (`k`) them manually (some visual support to identify them would
be nice but this is another story), in rare cases it is more complicated and
I have to use the CLI with `--rebase-merges`.

With magit I have to press `r i` at `00002` (!) which is completely
unintuitively.

Doing it on `00003` will give long list of commits between `00103` and
`00199` and will rewrite the history of `origin/stable`.

After the rebase, the graph might look like

```
01000 * [stable-next]
      |\
00001 * | some fix
01002 * | Merge branch master
      |\|
00100 | * [master] some enhancement
00101 | * foo
00102 | * bar
00003 * | [origin/stable] Merge branch 'master'
      |\ \
      | |/
00103 | * baz
```


> solution that I suggest is not to endure that manual work, but to
> use r e instead of r i.

1. I am using git to 50% on the commandline and 25% with magit. Because    `r i` spells somehow like `git rebase --interactive` I expect a    similar behavior as on the cli.

2. `r i` is an interactive rebase, `r e` a non-interactive.  I    definitively want an interactive todo list where I can insert    e.g. `x git merge master` at the top.


> Are you talking about this: r i without a commit at point shows a
> log to let the user select a commit, while r e does not

Yes; `r i` opens the "magit-log" where I can navigate up/down.  `r e`
prompts for "Rebase onto" in the minibuffer only (Magit 20191218.1258,
Git 2.23.0, Emacs 26.3, gnu/linux).


> You are advocating for the behavior of r i to be changed

yes; so that it does not contradict "git rebase --interactive".


> I don't know because you never said what you want to do just which
> commit you want to select

Selecting the commit whose history must not be rewritten (`origin/stable`)
is exactly what I want to do when starting a `git rebase -i`.

**Comment by tarsius** [comment]
> After the rebase, the graph might look like

I don't see how that is an improvement over what you started with. Actually it looks to me like you have replaced a merge that actually brings in changes with a merge that is completely pointless. (Situation after the rebase seems to be: Since you have merged `master` into `stable-next` with `01002` no new commits have been created on `stable-next`, so merging again is pointless.) This looks like a more desirable result to me:

```
00001 * [stable-next] some fix
01002 * Merge branch master
      |\
00100 | * [master] some enhancement
00101 | * foo
00102 | * bar
00003 * | [origin/stable] Merge branch 'master'
      |\ \
      | |/
00103 | * baz
```


>> I don't know because you never said what you want to do just which
>> commit you want to select

> Selecting the commit whose history must not be rewritten (`origin/stable`) is exactly what I want to do when starting a `git rebase -i`.

I got that. That's not really what you want to *achieve* but what *technique* you want to use in order to get there.

I think what you want to do is "rebase the current feature (?) branch onto its upstream branch". If so, then you should probably use `r u` instead.

---

All that being said I think I am open to the idea of adding an option to let users choose how they want to handle this. @kyleam and @npostavs, please give me some input on that.

**Comment by ensc** [comment]
yes; your result graph is correct.  The upper merge in mine is garbage.

**Comment by kyleam** [comment]
> All that being said I think I am open to the idea of adding an option to let users choose how they want to handle this. @kyleam and @npostavs, please give me some input on that.

The "all that being said" makes me uneasy.  It seems you're not entirely grokking the workflow and what the complaints about `r - i e` are.  Having tried to read this closely once and looking over it a few more times (admittedly with tired eyes), I'm not either.  I'd have guessed a workflow that executed `git merge ...` at the top of the to-do sequence starts to get in pretty unusual territory.  And at the same time many users rebase from magit, and it seems fair to say that a good number do not find the situation too confusing given the lack of regular issues about it.  

I don't think adding an option would add too much complexity, but I'd say it'd be good to have a clearer picture of the workflow/cases we're trying to support.

**Comment by Silex** [comment]
FWIW in the different workflows I used during my "git carreer" :smile:, I *always* used `git rebase -i foo~` (never `git rebase -i foo`).  That's because when you think in terms of rebasing you usually think "I want to rebase from this commit (including)". I believe that's the case for a lot of people. 

With magit I go on `foo` and press `r i`, and thus I think magit's default better suits my intentions.

**Comment by ensc** [comment]
> when you think in terms of rebasing you usually think "I want to rebase from this commit (including this commit)".

No; I never thought this and I can not remember when/whether I used ever `foo^` there.  Sense of `rebase` is to reapply some commits on top of another one (for me, this "another  one" has the focus because it usually must not be rewritten).

**Comment by Silex** [comment]
I mostly use rebase for sausage making. That means I often `!fixup` etc, and in that workflow you usually think in terms of "what are the commits that are untouchable and which ones can I still modify".

So if you have a log like this:

```
A HEAD master
B 
C
D
E origin/master
F
G
```

I know E and before are untouchable, and usually my mind is like "Ok I need to modify D before pushing". So in magit, I move to D and I press `r i` because that's from where I want to modify. In git I do `git rebase -i D`, then cancel because D is not included, then retype `git rebase -i D^` :wink:

**Comment by ensc** [comment]
> I know E and before are untouchable, and usually my mind is like "Ok
> I need to modify D before pushing".

I am thinking here: "cleanup everything after E".  There is too much
hassle to determine `D`...


> But coming from your workflow, I'd just use r e which is what I do
> when I want to move a bunch of commits to another branch

I do not want to move commits from another branch but merge it. My workflow
for e.g.  https://github.com/sigma-embedded/meta-de.sigma-chemnitz is:

1. there are `master` and several stables branches (e.g. `warrior`,
   `zeus`); these branches must not be rewritten/force-pushed

2. each of these stable branches have a `next` counterpart

3. development:

   - things are added to `next` (the devel branch of `master`)

   - after some changes / when needed, `next` is merged e.g. into
     `warrior-next`

   - perhaps do some other changes on `warrior-next` (e.g. `git revert`
     some of the `master` commits)

   - work with `warrior-next`

   - repeat these steps

   This results in multiple merges with `next` between `warrior` and
   `warrior-next` and perhaps additional commits

4. release

   - rebase `next`: `git rebase -i master` and make it the new `master`

   - normalize `warrior-next`: `git rebase -i warrior`

     - add an `x git merge master` on top of todo list

     - remove commits from merges or just run the rebase and skip them
       on conflicts

     - `warrior-next` becomes the new `warrior`

Yes; a `git cherry-pick master..next` might be better and more suitable.
But it is too difficulty to keep track of already merged commits.


> I'd just use r e

The `--onto` rebase option is useful but unneeded in 95% of my use
cases (rebase anchor is almost everytime the start of commits).  And I
need an interactive `i` to inject `git merge master` or just to squash
`fixup!`.


> By the way, isn't it easy to modify transient/magit

afais, it is very deep in the code

```lisp
(defun magit-rebase-interactive-1
      ...
      (if (magit-commit-parents commit)
          (setq commit (concat commit "^"))
```

I do not see an obvious way to hack around this.


> so r i does what you want? It's kinda bikeshedding no?

no; when anchor point is between merges

```
00001 *
      |\
00002 * |
00100 | *
      ...
00150 | *
      |/
00003 *    <<<<< git rebase -i 0003
      |\
00151 | *
      . .
00199 | *
      |/
00004 *
```

it is very difficult to find the `r i` location.

**Comment by tarsius** [comment]
It seems to me that your branching modal is overly complex but I don't understand the details so maybe I am missing some major benefit. I am going to assume that `zeus` and `warrior` are different boards you are supporting. I don't know anything about hardware development but I imagine it can make sense to maintain different long-living branches for different platforms. However the existence of `zeus` and its variants likce `zeus-next` relevant at all? Or could you reformulate the above for clarity of the relevant aspects by leaving out those branches? The relationship between `master`, `next`, `stable`, `stable-next` (and others?) is already complex enough.

But from what I believe to understand I have concluded that you usually rebase onto upstream. Is that correct?

It seems to me that you could benefit from *always* rebasing. I.e. don't merge upstream changes while working on a feature branch and then eventually when done rebase to remove the merges. Instead rebase onto the upstream whenever you feel the need to bring in changes from the upstream.

**Comment by ensc** [comment]
> I am going to assume that zeus and warrior are different boards

no; they are branches for [OE releases](https://wiki.yoctoproject.org/wiki/Releases).


> However the existence of zeus and its variants like zeus-next relevant at all.

It is the development model.  Locally I touch only the `next` branches.  Pushing to stable (e.g. this which corresponds to `git push . warrior-next:warrior` or `git push . next:master`) is done by merge requests on a gitlab server.


> But from what I believe to understand I have concluded that you usually rebase onto upstream

I rebase `next` branches to their stable variant.  E.g

```
git checkout warrior-next
git rebase -i origin/warrior
```

or

```
git checkout next
git rebase -i origin/master
```

> It seems to me that you could benefit from always rebasing

No; the stable branches (`warrior`, `zeus`, `master`, ...) must not be rewritten.

Cherry-picking woudl be possible but it is too difficult to keep track about the actual state.   With merging I can just  do `git merge master`  which will either merge the changes or will be a noop.

But `git cherry-pick A..B` (to add changes from `master` between `A` and `B`) requires bookkeeping about the last `A..B` range and usually conflicts when it is done a second time. Or (which is very likely), you will miss commits.

**Comment by tarsius** [comment]
> The "all that being said" makes me uneasy.

Yeah, Smells like Altersmilde :wink: 

While I have some vague idea, I don't really understand what Enrico is doing and why, and feel like he probably could benefit from tweaking his workflow. But I understand the central argument that in some cases it can be much more difficult to specify the beginning of the range as `M^` instead of `N`. This pretty much never happens to any of us it appears, which is why we are fine using `r e` in such cases. 

But if it happens constantly with your workflow its understandable that you want something done about it. How we feel about those workflows probably is not that important...

> I don't think adding an option would add too much complexity, but I'd say it'd be good to have a clearer picture of the workflow/cases we're trying to support.

...but yes, that would be nice anyway.

**Comment by tarsius** [comment]
>> However [is] the existence of zeus and its variants like zeus-next relevant at all[?]

> It is the development model.

But from the examples that follow I conclude that `zeus-next` is to `zeus` exactly what `next` is to `master`. We can therefore all the zeus stuff and only talk about the branches with well known names. Or maybe not, but lets stick to that for a while.

> But from what I believe to understand I have concluded that you usually rebase onto upstream

I rebase `next` branches to their stable variant.  E.g

```
git checkout next
git rebase -i origin/master
```

This actually *is* "rebasing onto upstream". Do you agree? If not, then please read [The Two Remotes](https://magit.vc/manual/magit/The-Two-Remotes.html) from the manual.

>> It seems to me that you could benefit from always rebasing

> No; the stable branches (`warrior`, `zeus`, `master`, ...) must not be rewritten.

I wasn't trying to suggest that. I believe what you are currently doing is this:

1. Occasionally merge `master` into `next`.
2. Eventually rebase `next` onto `master`.
3. Push `next` to `ensc/next` and ask for it to be merged into `orgin/master`.

And I suggest you do this instead.

1. Occasionally **rebase `next`** onto `master`.
2. Eventually rebase `next` onto `master`.
3. Push `next` to `ensc/next` and ask for it to be merged into `orgin/master`.

**Comment by ensc** [comment]
> > > However [is] the existence of zeus and its variants like zeus-next relevant at all[?]
> 
> > It is the development model.
> 
> But from the examples that follow I conclude that `zeus-next` is to `zeus` exactly what `next` is to `master`. We can therefore ignore all the zeus stuff

The stable, non-master branches are the interesting ones.   There you merge `next` several times (and finally `master`), add some fixups and do the rebase which is discussed in this issue.

**Comment by kyleam** [comment]
> > Are you talking about this: r i without a commit at point shows a
> > log to let the user select a commit, while r e does not
> 
> Yes; `r i` opens the "magit-log" where I can navigate up/down. `r e`
> prompts for "Rebase onto" in the minibuffer only

Given that it seems `r -i e` should mostly [*] support your workflow, I'm interested in why you view the `magit-log-select-mode` selection method as preferable to the minibuffer in this case.  Based on the examples you've given, you rebase onto a branch rather than a commit without an associated ref, so the `magit-rebase-branch` prompt with refnames looks like it'd be well suited for this.

---

[*] I say "mostly" because I noticed a couple of minor issues when I tried with a repository that looked like this:

```
c4cac8b *   Merge branch 'master' into stable-next    [stable-next]
        |\  
4877a20 | * baz                                       [master]
aeed58b * | fix
0171cd2 * |   Merge branch 'master' into stable-next
        |\ \  
        | |/  
bf259d6 | * bar
b7af01a | * foo
        |/  
ba6dabd * c5                                          [stable]
```

With "stable-next" checked out, I called `r -i e` and selected "stable".  In the to-do buffer I hit "x" and then entered `git merge --no-ff master`.

*Issue 1*: For this use case, the `exec` insertion is inconvenient because it enters the line _after_ the first entry.  So I needed to `C-p M-p` to get it to the top line (though the leading `C-p` is only needed if `git-rebase-auto-advance` is t).

At that point, executing the to-do list pops up the merge buffer.  I tweaked the message and continued.

*Issue 2*: Visiting the status buffer showed both the expected rebase section and a cherry-pick section.  I think we need to adjust `magit-cherry-pick-in-progress-p` to be more specific.  (I noticed this issue at least one point in the past but wasn't able to figure out how to trigger it again.)

After calling rebase continue (`rc`) three times, I ended up with:

```
52ae744 * fix                                         [stable-next]
3547260 *   Merge branch 'master'
        |\  
4877a20 | * baz                                       [master]
bf259d6 | * bar
b7af01a | * foo
        |/  
ba6dabd * c5                                          [stable]
```

**Comment by ensc** [comment]
> Given that it seems r -i e should mostly [*] support your workflow, 

Except that it does not spell like `(g)it (r)ebase --(i)interactively` and requires more typing than `r i`.

For me, implying `foo^` in `r i` makes no sense and illogical.  I do not find a single place where a CLI git user requested to change `git rebase -i foo` to behave like `git rebase -i foo^`.

Real fix would be the customization of `r i` behavior (with a customizable `defvar` but not some transient switch).

> I'm interested in why you view the magit-log-select-mode selection method as preferable to the minibuffer in this case. 

I work with 20-30 repository which all have different naming schemes for remotes and branches.  Sometimes, I want to rebase against `origin/master`, sometimes against `gitlab/master`, sometimes the branch is named `2019.01/master` (with different remote).   Visual support helps significantly to select the correct rebase anchor.

`r i` is perfect; except that it starts at the wrong position.


> Issue 1: For this use case, the exec insertion is inconvenient because it enters the line after the first entry.

Yes; it is a (minor) inconvenience.  Easy to workaround (in opposite to the `r i` start position) by moving it with `M-p`.

**Comment by tarsius** [comment]
> This actually *is* "rebasing onto upstream". Do you agree? If not, then please read [The Two Remotes](https://magit.vc/manual/magit/The-Two-Remotes.html) from the manual.

Well do you? Also, did you read that text?

I am asking because...

> Visual support helps significantly to select the correct rebase anchor.

... if it *is* the upstream and it is *configured* as such, then you don't have to do *any* selecting at all. Just type `r u` (rebase onto upstream). This is only one of the many benefits of properly configuring the upstream.

There is still the issue that you would have to use `r - i u`, but that you can easily fix by saving that argument as a default once: `r - i C-x C-s`.

**Comment by ensc** [comment]
> that you would have to use r - i u,

Why not just fix `r i` so that it works like `git rebase -i`?

**Comment by tarsius** [comment]
> Why not just fix `r i` so that it works like `git rebase -i`?

We believe that nothing needs fixing because nothing is broken. This should be clear to you by now, so please do not ask what we can only perceive as rhetorical questions. 

What we are currently trying to do is to understand your workflow. A possible outcome of such understanding might be that we end up adding an option, so that you can stick to your workflow and no longer have to deal with this inconvenience.

Its also possible that with a better understanding of what you are doing and why we might be able to advice you to improve your workflow and you might come to agree that the workflows you suggest actually are better.

Or not, but exploring that possibility is what three people beside you, including two maintainers, have already invested quite some time into. So I hope you do understand that we do not do that because we want to avoid the possibility of eventually having to admit you were right all along. We want to help you (and other people who might do things in a similar way) and we want to avoid having to add an option if we can help it, because while adding an option sounds harmless enough past experience has shown that reluctantly added options are never cost free and tend to cause issues over time.

Please also be open to the possibility that your workflows could be improved, and help us help you by answering these questions.

**Comment by tarsius** [comment]
Or you can just use this:

```emacs-lisp
(defun magit-rebase-interactive-1-my-way
    (fn commit args message &optional editor delay-edit-confirm noassert confirm)
  (if (eq this-command 'magit-rebase-interactive)
      (cl-letf (((symbol-function 'concat*)
                 (symbol-function 'concat))
                ((symbol-function 'concat)
                 (lambda (&rest sequences)
                   (if (equal (cadr sequences) "^")
                       (car sequences)
                     (apply 'concat* sequences)))))
        (funcall fn commit args message editor
                 delay-edit-confirm noassert confirm))
    (funcall fn commit args message editor
             delay-edit-confirm noassert confirm)))

(advice-add #'magit-rebase-interactive-1 :around
            #'magit-rebase-interactive-1-my-way)
```

**Comment by ensc** [comment]
My concerns about the broken (yes; it **is** broken) `r i` behavior are:

- it is unexpected; nobody who uses `git rebase -i foo` would expect that `r i` starts at `foo^`

- it is unpredictable; it is a wild guessing where `foo^` points when there are merges

It might be that my workflow can be improved by explicitly adding some configuration about upstream.  But I have just too much long and short living repositories to do such a configuration everytime.  It would be frustrating when `git rebase -i` works sometimes (when upstream is configured) but errors out in other situations.

I just do not want to do `r -i u` when configuration is there and `r i - e` when not.  A  `r i` is perfect when anchor point is within 1-2 screen pages reach.

Actual behavior might be caused because "(F)ixup" (where the commit is in focus) existed before the interactive rebase (where the anchor point is in focus).  But it is no excuse not to fix it.

**Comment by tarsius** [comment]
> My concerns about the broken (yes; it **is** broken) `r i` behavior are:

Doubling down I see. Well I already posted the fix for you to add to your init file, so there is nothing left here to do.

**Comment by ensc** [comment]
ok thx; I will change my setup and keep magit broken....

**Comment by ensc** [comment]
Just a note:  this issue is **not** solved.  The workaround does not work

**Comment by ensc** [comment]
@tarsius  please reopen it

**Comment by tarsius** [comment]
As I have said already I don't think anything is broken. But I believe I was open about the possibility of us having to make a change anyway. In order to decide whether that is so I tried to learn about your workflow. This effort was hindered by you answering questions only selectively.

I have closed this issue because it is not an effective use of our time to argue with you. Maybe you are right and something is broken, but if that is so, someone else will come along eventually and explain it to us in a more constructive fashion.

**Comment by ensc** [comment]
I am just tired of this meta discussion.  I gave enough reasons we `r i` behavior is broken but non of the arguments were considered or proven wrong.  Instead of, some hypothetical hello-world examples were discussed where it is easy to apply other workflows.

**Comment by tarsius** [comment]
> I am just tired of this meta discussion.

Me too. That's why I closed it.

> I gave enough reasons we `r i` behavior is broken

My impression is that you repeated the same argument over and over. But I am sure you feel the same way about what I have been saying.

> but non of the arguments were considered or proven wrong.

I think this is where things went wrong. I never tried to *win*. I tried to *understand* in order to make suggestions and/or changes. But indeed I was feeling that what *you* were trying to do is to win, e.g. I got the impression that you intentionally ignored my questions because you figured that doing so would "weaken your position".

> Instead of, some hypothetical hello-world examples were discussed where it is easy to apply other workflows.

I was trying to learn about your workflow but you kept ignoring my questions.

I would have liked to move on to more complex cases and follow-up complications. But it took me so long to just get you to finally reply that you are indeed rebasing on branches that could be considered the upstreams, that my interest in helping you was gone when you finally did. All the energy that it took me too get you to finally admit that, I would rather invested in teaching you to configure Magit so that it *automatically* sets the upstream for you.

**Comment by ensc** [comment]
> My impression is that you repeated the same argument over and over

I repeated the arguments because  they were never addressed.  Instead of the discussion went more and more away from the issue.


>>    but non of the arguments were considered or proven wrong.
> I think this is where things went wrong. I never tried to win. 

This has nothing to do with winning... I will accept "`git rebase -i foo^` is the better behavior because ..." when there are substantiated arguments.


> that you intentionally ignored my questions

I started to intentionally ignore the question in https://github.com/magit/magit/issues/4021#issuecomment-567909810 because there the bike shedding began (insisting on a discussion about the definition of "upstream").

I detail, there are three unanswered questions from you:

1. > This actually is "rebasing onto upstream". Do you agree? If not, then please read The Two Remotes from the manual.

2. > Well do you? Also, did you read that text?


> invested in teaching you to configure Magit so that it automatically sets the upstream for

magit provides a lot of useful features and when you work intensively with one or two repositories a full configuration and utilizing all the different `r ....` features might indeed safe a lot of time.

But I work with too much mixed and different environments and have the feeling that a `git rebase -i` directly on `foo` safes me more time than I need for the configuration.

**Comment by tarsius** [comment]
I have added `magit-rebase-interactive-include-selected`. It was likely that I would do so all along and I decided that I should not punish others for your refusal to cooperate.

**Comment by tarsius** [comment]
The core of your argument--that Magit's approach is less flexible--is sound.
