### ISSUE TITLE
Staging/unstaging hunks messes with the other hunks' visibility

### ISSUE THREAD

**Issue by TonCherAmi** [magit/magit#4024]
Context: I have a repository with a lot of changes made to a singe file resulting in quite a few hunks. To make the status buffer neat and  manageable, I collapse the hunks via `M-3 / magit-section-show-level-3-all`, then proceed to expand and stage them individually. That's where the issue appears - upon staging a hunk, all of the ones **below** it are expanded which changes my position in the buffer which in turn causes a lot of confusion and requires me to collapse everything anew via `M-3 / magit-section-show-level-3-all`.

One workaround I found is hiding hunk sections by default via `magit-section-initial-visibility-alist`, but that has a couple of drawbacks - it's not always desirable to have the hunks be hidden by default and it also causes hunks to be collapsed upon staging a region.

I'm not sure whether this is the intended behavior or not, but it is *really* frustrating. I'd appreciate it if you could at the very least point out the function responsible so I can attempt to patch it myself, thanks.

`magit-version` output - `Magit 20191229.1645, Git 2.24.1, Emacs 26.3, gnu/linux`

**Comment by tarsius** [comment]
This could be hard to address.  The problem is that when the contents of the buffer are recreated we have to somehow determine for each section if it is a "reincarnation" of a section from before the refresh.  This involved comparing the "identities" of the old and new sections, which derive from the type and value of the section and those of its parents.

This does not work in this case because the "value" changes.  For example if we start with three unstaged hunks whose values are `78,7 78,6`, `116,7 115,6` and `138,7 136,6`, and then we stage the first hunk, then that first section disappears and the values of the latter two change to `115,7 115,6` and `137,7 136,6`. `115,7 115,6` isn't the same as `116,7 115,6` and so we cannot tell that these two are "the same" section.

**Comment by TonCherAmi** [comment]
Yeah, I see, this is not a simple issue at all. Oh well.

**Comment by tarsius** [comment]
I've marked this issue as "take another look when you feel brave and have lots of time". :stuck_out_tongue_winking_eye:
