### ISSUE TITLE
Cannot stage individual parts of an untracked file

### ISSUE THREAD

**Issue by danielmartin** [magit/magit#4026]
**Magit version:** Magit 20200102.2204, Git 2.21.0, Emacs 26.3, darwin

Magit supports the `git add --intent-to-add` command via `C-u s` from the status buffer when the point is in an untracked file. The file won't be staged so that you can stage individual parts of the new file (and not the entire file). But this workflow (which is the main "selling point" of `--intent-to-add`) is not working correctly.

**Steps to reproduce the problem:**

1. Open a repository that contains an untracked file with a few lines of text.
2. From a Magit status buffer, press `C-u s` (`(magit-stage t)`).
3. The file is in the `Unstaged changes` section now.
4. Select a few lines of that file and press `s` (`(magit-stage)`).

**Expected result:** The selected files of the untracked file are now staged to be committed.
**Actual result:** An error `File: already exists in index` appears.

I could work around the issue by staging the whole untracked file and follow these steps: https://github.com/magit/magit/issues/2965#issuecomment-349778733.

**Comment by phil-s** [comment]
I cannot replicate that problem with Magit 20200102.2204, Git 2.8.3, Emacs 26.3, gnu/linux

**Comment by danielmartin** [comment]
Yes, I confirm this problem does not occur with git 2.8.1. So either it is a git bug, or an incompatible change in the git API in recent versions.

**Comment by kyleam** [comment]
This bisects to Git's 0231ae71d3 (diff: turn --ita-invisible-in-index on by default, 2018-05-26), which was part of the v2.19.0 release.  I haven't yet looked closely at that commit or the series that it was a part of.

**Comment by kyleam** [comment]
The series is ac997db0c1^- and the corresponding discussion and review is [here][0].  As of 0231ae71d3, by default `diff --cached` no longer shows intent-to-add files, while `diff` shows the entries as new files.  The relevant output for this failure is the latter (no `--cached`);  0231ae71d3 changed

```
diff --git a/f b/f
index e69de29..27a7ea6 100644      <-- empty file
--- a/f
+++ b/f
[...]
```

into

```
diff --git a/f b/f
new file mode 100644
index 0000000..27a7ea6
--- /dev/null
+++ b/f
[...]
```

When `magit-stage` derives a patch based on the latter and feeds it to `git apply --cached`, it fails because the intent-to-add file _is_ already in the index.

The main way I see to address this is to pass `--ita-visible-in-index` as a `diff` argument in `magit--insert-diff`.

<details>
<summary>patch</summary>

```diff
diff --git a/lisp/magit-diff.el b/lisp/magit-diff.el
index b3abb95d5..22d49fc70 100644
--- a/lisp/magit-diff.el
+++ b/lisp/magit-diff.el
@@ -1945,6 +1945,7 @@ (defun magit--insert-diff (&rest args)
   (let ((magit-git-global-arguments
          (remove "--literal-pathspecs" magit-git-global-arguments)))
     (setq args (-flatten args))
+    (push "--ita-visible-in-index" (cdr args))
     (when (cl-member-if (lambda (arg) (string-prefix-p "--color-moved" arg)) args)
       (push "--color=always" (cdr args))
       (setq magit-git-global-arguments
```

</details>

Unfortunately we'd need to check the git version before adding `--ita-visible-in-index` to the arguments because that argument wasn't added until v2.11.0, so that'd come with an expense of an added git call for each diff call.

One way to avoid the version check would be to replace `diff` with `diff-files --patch` in `magit-insert-unstaged-changes`.  The main downside is that this only fixes staging a region of an intent-to-add file _from the status buffer_; staging from a diff buffer (e.g., generated by `magit-diff-unstaged`) would still fail.  There'd also be some worry that, because we're using `diff-files` rather than `diff`, transient options that we offer for the porcelain `diff` (now or at a later point) wouldn't completely align with the options accepted by `diff-files`.

The `magit-insert-unstaged-changes`/`diff-files` approach would also mean that intent-to-add files wouldn't be shown as an entry in the staged files section.  Depending on how you look at it, that could be desirable or not, but it would mean that the output in the staged section would differ before and after v2.19.0, which could cause some confusion.

[0]: https://public-inbox.org/git/20180526120846.23663-1-pclouds@gmail.com/T/#u

**Comment by tarsius** [comment]
> an expense of an added git call for each diff call.

Or just one additional, cached call per Emacs session. Only very rarely that will lead to an issue, i.e. when someone actually uses this feature *and* for some reason crosses the v2.19.0 boarder during a session. That should be good enough I think.

**Comment by kyleam** [comment]
> That should be good enough I think.

Agreed.  Later today I can work on a patch, though I of course don't mind if you or someone else wants to handle it now.

**Comment by phil-s** [comment]
Perhaps `magit-repository-local-set`/`get` should be used to cache and read this value?

Especially when using Tramp, there might easily be multiple different versions of Git in use in a single Emacs session.

**Comment by kyleam** [comment]
@phil-s Thanks for bringing this up.  I should have thought about this more carefully.

> Especially when using Tramp, there might easily be multiple different versions of Git in use in a single Emacs session.

Hmm indeed.  The situation that I see as not unlikely and particularly problematic (because the consequence is more than just ita functionality not working): The user has Git 2.19.0 or later on their local machine.  This value is cached, and we pass `--ita-visible-in-index` when generating the diff.  On a remote machine the user visits later, the Git version is before 2.11.0, which doesn't have the `--ita-visible-in-index` option.  `magit--insert-diff` calls in that remote repository would fail.

I won't be free to address or think about this more until (my) tonight, though.

**Comment by kyleam** [comment]
> Perhaps `magit-repository-local-set`/`get` should be used to cache and read this value?

Done in f63077242.  Thanks.

**Comment by tarsius** [comment]
Thanks @kyleam!
Almost looks like "work more on Magit again" was one of your new years resolutions. :stuck_out_tongue_winking_eye:

**Comment by mateusfccp** [comment]
It still happens with me...

Magit 20200503.1905, Git 2.26.2, Emacs 26.3, darwin

**Comment by kyleam** [comment]
@mateusfccp I've just tried the steps in the opening message with the latest Magit and Git 2.26.1, and the parts are staged fine. The only thing I can think of is that you upgraded Git within this session, but that seems unlikely given it'd be a `<2.19 -> 2.26.2` jump.  So, I dunno.  I'd suggest stepping through `magit--insert-diff` and inspecting the `diff-ita-kludge-p` handling.
