### ISSUE TITLE
`format-patch`: new option for accessing to non-listed options

### ISSUE THREAD

**Issue by zimoun** [magit/magit#4028]
Dear,

Thank you for this awesome tool!

Currently, Magit provides `format-patch` and several options are controlled by `C-m <key>` (the main ones). However, if I understand correctly, it is not possible to use the other options of `format-patch` which are not listed. I am not convinced that all the options have to be accessible with `C-m <key>` but it appears to me really useful to add (let say) `C-m !` to authorize to type any arguments.

To be concrete, when I am on a branch, using the CLI, I run:
```
git format-patch --cover-letter --base=$(git merge-base --fork-point master)
```
to get `base-commit: <hash>` at the bottom of the cover letter where `<hash>` is the commit where the patches of the branch can straightforwardly be applied.

Using Magit, I would like to hit: `W c C-m l C-m !` and type `--base=$(git merge-base --fork-point master)` then end  `c`.

Obviously, sometime I need to use the option `--interdiff` or any other.

Let me know if it is already possible and/or I miss something.

What do you think?

All the best,
simon

**Comment by tarsius** [comment]
> I actually have a to-do to add it, but I haven't been in much of a hurry to get to it because I tend to call `format-patch` from the terminal (mostly because I'll end up there to call `send-email` anyway).

And I must even admit to not even using the patch and email functionality at all. (See e.g. the change I submitted to Org somewhat recently.) I should and want to but don't it often enough to remember how everything works and cannot tell whether things are harder than they should be because I don't remember how to do them properly other because the implementation is lacking. So I usually don't use it and the result is that this functionality does not improve.

Since you actually use this, could you please look into how it could be improved? And maybe write a tutorial even? No hurry at all though.

**Comment by kyleam** [comment]
> Since you actually use this, could you please look into how it could be improved?

Sure, I can certainly take a look some time soon-ish at updating the patch-create transient.  I think that is a place that good, straightforward improvements can be made without much of a vision or overarching workflow in mind.  On the other hand, send-email has of course come up a number of times before (gh-1756 and gh-1800 are the most relevant, I think), and tackling that requires a vision that I don't really have.  Perhaps due to a lack of imagination, I can't think of an implementation on Magit's side that would improve the simple send-email command that I run.  In terms of sending mail, the most involved thing that I need to do is get the `--to/--cc`s  and `--in-reply-to` from an existing thread, but in my view that's outside of Magit's scope.  (And, in my case, notmuch handles it very nicely with its `notmuch-show-stash-git-send-email` command.)

> And maybe write a tutorial even?

Perhaps, though I'm not sure I have anything valuable to add to the mail workflow tutorials that are already out there.

**Comment by zimoun** [comment]
Thank you for all the explanations and links.

I was not aware about `--base=auto`, thank you for the tips. I have never read all the Git manual. ;-)

I am giving a look to the `transient` manual to extend , but I am a bit lost...

Thank you if the integration with Magit of `format-patch` and `send-email` is improved. It would help with the Guix workflow. ;-)

**Comment by tarsius** [comment]
@kyleam Just a friendly ping in case you forgot about this.

**Comment by kyleam** [comment]
Didn't forget, just too many things competing for non-work time.  I'll bump this a bit up my to-do list.

**Comment by tarsius** [comment]
No hurry!

**Comment by kyleam** [comment]
I've put together a (very unpolished) [draft][0] of what I think is worth adding to the patch-create transient.  As I mention in the final commit, levels and keys weren't given too much thought at this point.  I should have time to wrap that into a proper PR by Friday night.

[0]: https://github.com/magit/magit/compare/km/patch-more-args

**Comment by zimoun** [comment]
@kyleam Thank you! 
Now let hope that the feature will be included soon in Guix. ;-)
