### ISSUE TITLE
What's magit's to blame a deleted file?

### ISSUE THREAD

**Issue by FirstLoveLife** [magit/magit#4036]
Say that we have a such commit:
``` diff
Move autoload.el => autoload/hlissner.el

I expect to add more files

2 files changed, 6 insertions(+), 6 deletions(-)
autoload.el          | 6 ------
autoload/hlissner.el | 6 ++++++

deleted    autoload.el
@@ -1,6 +0,0 @@
-;;; private/hlissner/autoload.el -*- lexical-binding: t; -*-
-
-;;;###autoload (autoload '+hlissner/find-in-dotfiles "private/hlissner/autoload/hlissner" nil t)
-(+default--def-find-in!   dotfiles (expand-file-name "~/.dotfiles") +hlissner)
-;;;###autoload (autoload '+hlissner/browse-dotfiles "private/hlissner/autoload/hlissner" nil t)
-(+default--def-browse-in! dotfiles (expand-file-name "~/.dotfiles") +hlissner)
new file   autoload/hlissner.el
@@ -0,0 +1,6 @@
+;;; private/hlissner/autoload.el -*- lexical-binding: t; -*-
+
+;;;###autoload (autoload '+hlissner/find-in-dotfiles "autoload/hlissner" nil t)
+(+default--def-find-in!   dotfiles (expand-file-name "~/.dotfiles") hlissner)
+;;;###autoload (autoload '+hlissner/browse-dotfiles "autoload/hlissner" nil t)
+(+default--def-browse-in! dotfiles (expand-file-name "~/.dotfiles") hlissner)
```

And I want to do more blame inside `autoload.el` to explore `~/.dotfiles`. what's proper way to do that in magit?

**Comment by kyleam** [comment]
I'm not sure I understand your question, but the (unconfigurable) behavior of `git blame` is to follow whole-file renames.  You should see the same behavior when running `magit-blame` on a file.   In the case you're showing, though, it wouldn't be surprising if it weren't detected as a rename because there are few lines and a couple are changing in the rename.

If you want to blame starting in the top-level, now-deleted autoload.el without checking out a working tree that has it, you can visit the file from a revision before it was deleted with `magit-find-file` and then call `magit-blame` from that file.
