### ISSUE TITLE
Allow suppression of hooks (--no-verify) when deleting remote branches?

### ISSUE THREAD

**Issue by alphapapa** [magit/magit#4041]
In some of my repos I use a pre-push hook to ensure that tests pass before pushing to `master`.  When I delete a remote branch, the pre-push hook runs first, which turns a quick operation into one that takes several seconds to complete.  Also, if I'm in a non-`master` branch, and the tests are not currently passing in it, the pre-push hook can prevent the deletion of remote branches.

The commit dispatcher allows using `-h` to disable hooks, but the branch dispatcher, in which I press `k` to delete a branch, doesn't offer that option.  So to delete a remote branch without running the pre-push hook, it seems that I have to resort to manually running `git push --no-verify origin --delete topic`.

Is there a way to handle this cleanly in Magit?  If there isn't already, could `--no-verify` be added to the branch dispatcher, perhaps at a higher Transient level so it doesn't clutter the display by default?

By the way, I searched the tracker and found this issue: https://github.com/magit/magit/issues/3861.  Of course, that is a possibility, but it would simpler and more flexible for the user if Magit offered the ability to use `--no-verify`.

Thanks for your work on Magit.

**Comment by tarsius** [comment]
`magit-branch-delete` already takes an (undocumented) prefix argument to mean that the deletion should be "forced". Currently that means "use `git branch -D` instead of `-d` if it comes to that". I'm thinking it should additionally mean "use `--no-verify` when pushing".

Adding `--no-verify` to the transient would be a bit confusing, even when hidden by default, because its meaningless to the other suffix commands. Also `magit-branch-delete` can be invoked directly. That's two arguments for going with the prefix argument instead.

**Comment by angerborn** [comment]
Third idea, make this customizable (not necessarily talking about the emacs-customize interface) via some variable.
That way it should be possible to have different settings per project using dir-locals.

I'm quite satisfied with the solution of modifying the hook specifically because it's set and forget, it just works. I don't have to remember setting `--no-verify` in the transient (that I rarely use, anyway) or use a prefix. In that way, a setting for it is similar but way easier to set than copy the part of my hook that ignores deletes.

I agree that of the other solutions, prefix is the better one since the transient isn't always shown.

**Comment by tarsius** [comment]
Implemented both @angerborn and my own suggestion.

**Comment by alphapapa** [comment]
Thanks, Jonas.
