### ISSUE TITLE
Per-project saved Transient arguments

### ISSUE THREAD

**Issue by jdormit** [magit/magit#4042]
I wasn't sure whether to put this here or in the Transient repo, but I think it is more or less Magit specific.

I want to be able to save certain argument values on a per-project basis - for example, a work project has some terrible auto-configured Git hooks that I'm not in a position to delete, so I'd like to always set the `--no-verify` flag when I `git push`.

Currently, I set the `-h` flag in the Magit push transient buffer and then use `C-x C-s` to save that flag. Unfortunately, this sets the flag for _all_ push buffers, not just the one for this problematic repository.

Is there a way to save transient arguments per-repository instead of globally?

**Comment by tarsius** [comment]
> Is there a way to save transient arguments per-repository instead of globally?

Not yet no. But there's a issue about that: #2993. I am closing this issue in favor of that, but am sure to come back here when I work on that. So some notes:

Normally I would recommend to "locally set the respective git variable instead", as a temporary workaround at least. In this case there is no such variable. I would argue that there should be one, but one could also argue that that is not necessary because one can just make the hooks non-executable. That makes them modified, but that one can work around using `git update-index --assume-unchanged`. I guess that's what I recommend you do for now.

Just to be clear I think it should be possible to control this from the popup per repository, but we are just not there yet.

This issue demonstrates that we cannot just assume that there's a variable for every setting; except for that it is basically a duplicate.

**Comment by tarsius** [comment]
`--[no-]verify` is more complicated than other settings for other reasons as well, e.g.  #4041.
