### ISSUE TITLE
More control over magit-blame-styles

### ISSUE THREAD

**Issue by toothbrush** [magit/magit#4057]
I've had a look at [the documentation](https://magit.vc/manual/2.11.0/magit/Blaming.html) and the doc string of the `magit-blame-styles` variable, and i still have a question.  My apologies if i'm misunderstanding something.

I have the following `magit-blame-styles`:

```elisp
     (setq magit-blame-styles
           '((margin
              (margin-format " %s%f" " %C %a" " %H")
              (margin-width . 42)
              (margin-face . magit-blame-margin)
              (margin-body-face magit-blame-dimmed)))
```

I would like to be able to specify to use a Git short hash instead of the full commit SHA (with `%H`), but it appears that this isn't possible.  Am i missing something?  Thanks! 🙌

**Comment by tarsius** [comment]
Magit only offers the pieces of information that are being printed by `git blame --incremental` and the abbreviated hash is not among them.

We could run `git rev-parse --short=N` on each commit but there could be many commits and that would be slow at least on Windows. We could also just chop of the hashes manually but then we risk printing hashes that are not actually unique.

Since I also think the hashes are not actually that useful (what's useful is pressing `RET` to visit the commit), I don't really want to do either of that. As a work around you can place the hash last in the format; that way it doesn't take space away from other information and if doesn't fit on the line itself, that does not really matter.

**Comment by toothbrush** [comment]
That makes perfect sense – thank you for taking the time to explain the complexity to me.

In fact, my issue was simply cosmetic, so i'll ignore it and close the issue – you're right that the main feature is being able to `RET` on a line and be taken to a commit, which is what i use, too.

Thanks for making great software! 🙏

**Comment by midenok** [comment]
Sorry, but it doesn't make any sense to me. What is the problem to cut down commit hash string to N chars and make it %h? Please, reopen! %H doesn't fit into margin-format. N should be configurable.

**Comment by tarsius** [comment]
> What is the problem to cut down commit hash string to N chars and make it %h?

This:

> We could run `git rev-parse --short=N` on each commit but there could be many commits and that would be slow at least on Windows. We could also just chop of the hashes manually but then we risk printing hashes that are not actually unique.

> Please, reopen!

Sorry but I don't plan to add support for abbreviated hashes here.

**Comment by midenok** [comment]
@tarsius, did you understand my question? To cut down string you don't need to run `git rev-parse`. You have string S of length 40, you can cut it to length N by the call `(substring S 0 N)`. What is the problem to do that?

**Comment by tarsius** [comment]
> What is the problem to do that?

This:

> but then we risk printing hashes that are **not actually unique**.

I.e., **invalid** abbreviations.

You could of course argue that that does not actually matter, but I am not sure you haven't been overlooking that part, so I figure I should repeat it one last time.

Okay, so I am adding this to the list of things to probably do once I find the time (please don't open a pull-request, I also do not have the time to review that right now). Instead of reopening this ancient feature-request, I am locally marking it as "consider again once there aren't so many more pressing things to attend to".

**Comment by tarsius** [comment]
It's supported now.

**Comment by midenok** [comment]
Great, thanks! The risk is not critical for UI where you copy&paste by hand, it is always under human control.
