### ISSUE TITLE
Add support for git-duet

### ISSUE THREAD

**Issue by viccuad** [magit/magit#4063]
Hello,

Many thanks for Magit! You can't believe how much daily joy it brings me.

When pairing with colleagues we use [git-duet](https://github.com/git-duet/git-duet).  Git-duet adds git commands to work in pairs:

```
Set two authors (pairing):
$ git duet jd fb

Set one author (soloing):
$ git solo jd

Committing (needed to set --signoff and export environment variables):
$ git duet-commit -v [any other git options]

Reverting (needed to set --signoff and export environment variables):
$ git duet-revert -v [any other git options]

Merging (needed to set --signoff and export environment variables):
$ git duet-merge -v [any other git options]

Rebasing (resets the committer to the committer of the current pair):
$ git rebase -i --exec 'git duet-commit --amend'
```

Some people have defined simple functions to [expose git duet-commit from inside magit](https://emacs.stackexchange.com/questions/51363/how-can-you-configure-magit-for-duet-commit).

It would be nice if it could have 1st world support in magit, particularly by adding support in popups, and showing the people currently selected for Duet mode in magit-status.

Cheers,
Victor

**Comment by tarsius** [comment]
As mentioned in #3040 and #2745 I don't want to add this Magit itself. I think supporting such tools is beyond the scope of Magit (gasp... there are git related things beyond the scope of Magit?!?).

Somebody™ should implement this as a separate package. That would be a good opportunity to learn about transients (i.e. the new popup implementation) and stuff.

Skimming past discussions I see that I suggested implementing this in elisp instead of wrapping around around a script. If someone went down that path, then the result *might* be a candidate for inclusion in Magit.
