### ISSUE TITLE
Add -t argument to magit-commit 

### ISSUE THREAD

**Issue by skrech** [magit/magit#4087]
Hello,

Firstly, I'd like to thank you for your effort supporting this great emacs package!

I think it would be great to add -t/--template argument to magit-commit. It would allow to use template message only when one needs it. Most of the time, such commit template message is needed when squashing the commits in a feature branch and issuing a merge request. 

Git allows to setting project-level template message in its .gitconfig or overriding it with "git commit -t <file>" swtich. The first option works with magit well, but for the override scenario I can't find an easy way to do it. With the cli commands I'd usually made an git commit alias to use the template file for when I need to use that message. However, I can't seem to find a way to supply custom arguments to magit-commit. Hence, it'll be great addition to have this option in the "Arguments" section of magit-commit.

Kristiyan

**Comment by kyleam** [comment]
> However, I can't seem to find a way to supply custom arguments to magit-commit.

You can add the switch to the `magit-commit` transient in your customization (see the [transient docs][0]).  Something like

```elisp
(transient-append-suffix 'magit-commit "-C"
  '("-t" "Template" "--template="
    (lambda (prompt _initial-input _history)
      (read-file-name prompt))))
```

Where to draw the line for including options in Magit itself has shifted because transient, unlike the older magit-popup implementation, supports hiding some things by default, but there is still a line, and I'm a poor judge of where it is.

[0]: https://magit.vc/manual/transient/Modifying-Existing-Transients.html#Modifying-Existing-Transients

**Comment by kyleam** [comment]
Okay, I'll consider the above good enough given it answers the main question of how to add custom arguments.  If others feel strongly that this particular option should be included by default, we can revisit this of course.
