### ISSUE TITLE
magit-am-apply-patches: Allow patches from anywhere in the filesystem

### ISSUE THREAD

**Issue by aurabindo** [magit/magit#4094]
**Use case**: Lots of patch files that needs to be applied but lying around somewhere outside of the git repository.

When `*.patch` is an entry in the `.gitignore`, copying the patches into the git does not make them show up in the magit status area as 'untracked' and hence cannot be conveniently selected from magit to initiate git am.

**Possible solution**: instead of taking one file as input, accept multiple selections

**Comment by kyleam** [comment]
So I guess the main thing here is what the multi-selection interface looks like.  And, then once that's defined, whether it make sense from Magit's perspective to maintain this code in order to support this particular workflow.

One thing worth considering is that Dired seems like a natural interface to use for this, and it doesn't take much to wire that up outside of Magit:

```emacs-lisp
(defun my/dired-apply-patches (repo &optional arg)
  (interactive
   (list
    (and (not (magit-toplevel))
         (magit-read-repository t))
    ;; Or, if you use projectile:
    ;; (and (not (projectile-project-p))
    ;;      (completing-read "Project: "
    ;;                       (projectile-relevant-known-projects)))
    (and current-prefix-arg
         (prefix-numeric-value current-prefix-arg))))
  (let ((files (or (dired-get-marked-files nil arg)
                   (user-error "No marked files"))))
    (magit-status-setup-buffer repo)
    (magit-am-apply-patches files)))
```

**Comment by tarsius** [comment]
I've added that with slight modifications.
