### ISSUE TITLE
Please cut a release

### ISSUE THREAD

**Issue by yarikoptic** [magit/magit#4095]
There is #3000 discussing the road map toward 3.0.0 but I didn't want to pollute it with a user feature request of having a new (3.0 or not) release out.  Current master is v2.90.1-961-g8e28a154 and 2.90.1 was released in Nov 16 2018, so over two years ago.  Many distributions (e.g. Debian) prefer to package/provide released versions, thus poor souls like yours truly me are stuck with 2.90.1 thus deprived of all bug fixes and new features since over two years ago.  E.g. in my case it was an ability to diff moved code which was added in #3782 a year ago but never released.

**Comment by phil-s** [comment]
Who/what is forcing you to use the Debian package?

**Comment by yarikoptic** [comment]
Demand for efficiency and stability.

**Comment by phil-s** [comment]
So in your quest for stability, you're asking for a public release to be made *before it's completed*?  That seems contradictory to me, and I don't think it really benefits anyone.

FWIW, I think that if you want to be running newer Magit code then you should simply install Magit from MELPA.

**Comment by yarikoptic** [comment]
ok, if you would like to pursue the "stability" line with Debian aspect: without testing of a package within Debian (where it first gets uploaded to "unstable") it lacks (wider) testing, thus avoiding possible bugs discovery/fixing.   If upload is rushed before next debian stable freeze point -- often it simply doesn't make it in a good shape to the next debian release.  That is why it is great to see new releases of packages coming out so they could get well tested in debian unstable and testing before becoming candidates for being included in the release.
Re stability of magit: [Milestone 3.0.0](https://github.com/magit/magit/milestone/22) as far as I see lists only additional new features, and not bug fixes.  I am nobody, but I would say -- why not to defer them to some ultimate 4.0.0 or 3.1.0?  So, if current master is indeed so unstable that it is not worthwhile upload to Debian unstable or experimental, then indeed I would rest my case.  But I do not think it is the case since you do recommend installing it from MELPA so it is presumably in "user consumable state". As any software it might have bugs which would resurface.  If 3.0.0 ultimate target is the "ultimately stable", there could as well be 2.99.999 and so on before that (or some other following e.g. semver) to signify that they are release candidates.  Altogether they could help to ensure better stability of magit whenever it matures to the ultimate 3.0.0.

Anyways, I am here not to rush the ultimate release, but rather to report that there are users who are waiting for it, and would appreciate it coming.game here.

**Comment by yarikoptic** [comment]
and 27 open (including this one) out of over 2k issues looks like an good indicator to me in terms of "stability" ;-)

**Comment by phil-s** [comment]
I see that Debian has "experimental", "unstable", and "testing".  Perhaps one of those would be appropriate for a "regularly built from the latest code" Magit package?  That might be worth exploring.

**Comment by tarsius** [comment]
If stability is the goal, then delaying it a bit more is a good thing because we are currently in a "fix bugs without adding new features or doing too many refactorings" phase.

I don't think Magit and Emacs packages in general are the sort of packages where a distribution's package maintainers can do much to improve stability.

**Comment by vanicat** [comment]
Furthermore, Debian try to add as little modification as possible to software it package, history prove that changing software can backfire... 

I don’t really follow the development of magit nowadays, but I would be interested by a commit id that would stable enough to be included in Debian unstable. Either in recent past, or when this " fix bugs without adding new features or doing too many refactorings" phase will end.

Thanks for your work here.

**Comment by tarsius** [comment]
Hey Rémi!

> I don’t really follow the development of magit nowadays, but I would be interested by a commit id that would stable enough to be included in Debian unstable. Either in recent past, or when this " fix bugs without adding new features or doing too many refactorings" phase will end.

Sounds like a good idea. Do you want me to just give you a hash or are you asking for a tag (`debian-unstable` maybe?). Once this phase is over I will probably release, so I suggest you update unstable now. Any recent commit should work, but lets ignore this weeks changes and go with e8c7bd0329194bf09d3e8992e78efbfcd2769f19.

**Comment by tarsius** [comment]
I am closing this now, but feel free to keep commenting.

**Comment by vanicat** [comment]
A hash is enough, for now it will be the version v2.90.1-957-ge8c7bd03  of the debian package.

**Comment by yarikoptic** [comment]
Fwiw for got snapshots I use following schema for version to make it clear where it comes from
2.90.1+git957-ge8c7bd03 .   Fwiw git understands it as well, since it only cares about that -g suffix

**Comment by vincentbernat** [comment]
This is also an issue for people using MELPA Stable (because I don't want to handle frequent configuration changes). Current version does not work out of the box for me, notably because of #3843. So, a release would be helpful. It's also unclear if 3.0.0 is right around the corner or is still several months away. If it's right around the corner, you could release a 2.99.1 (or nothing at all). Otherwise, a 2.10? Or a 3.0.0 and postpone remaining stuff to 3.1.0?

**Comment by sdhoward** [comment]
I concur with the OP yarikoptic, they want a tagged 2.something release that has some of the changes between 2018 and whenever 3.0 is released (2021?). Some people prefer not to use MELPA, which downloads lots of unsigned code to the user's system and runs it.

https://github.com/magit/magit/issues/3965
https://github.com/magit/magit/issues/3918

A release has been promised for over a year now, sometimes without mentioning that it would be a 3.0. Now I get that you're trying to deliver an exciting 3.0 release. I would rather have magit be extremely boring but still maintained in 15 years, than have it be exciting with each new release and burn out sooner.

**Comment by tarsius** [comment]
> (2021?)

2020!

**Comment by sdhoward** [comment]
It really is about to be another year without a release, isn't it?

**Comment by tarsius** [comment]
Yes, I should release more often and I should have released 3.0 long ago. I am not being sarcastic or anything just stating facts.

Unfortunately though I have not done it (and some prerequisites) and it has been so long by now that merely thinking about it makes my anxious. If I don't think about it for a while, then it gets better and I start believing in being able to do it again.

Unfortunately getting to that point takes a few months and every time I get there a few people who don't know about this decide that it has been a while since I was last pinged about making a release and that it is time to do it again. The consequence of that is that the anxiety is right back, especially because its usually not just one person who does it. This time around for example it was three people within less than a week.

So I would like to ask all of you to stop pinging me about this. Not pinging me about will drastically increase the likelihood of it happening soon.

It would also help if you did not take this to social media.
