### ISSUE TITLE
Expand shell variables in git config

### ISSUE THREAD

**Issue by jpprime** [magit/magit#4121]
On my git configuration I set the `--socket` option of the credential helper to use the variable `${XDG_CACHE_HOME:-${HOME}/.cache}/git/credential/socket` to store the it, but Magit doesn't seem to be able to expand the variable to the path since the variable `magit-credential-cache-daemon-socket` shows `"${XDG_CACHE_HOME:-${HOME}/.cache}/git/credential/socket"` and every time I do an operation it asks for my username and password, in contrast to doing the same operations on the terminal where it only asks for it once, only asking again after the timeout I've set runs out. This behaviour also happens if the `--socket` only uses the variable `$XDG_CACHE_HOME` instead of the parameter substitution.

**Comment by tarsius** [comment]
> On my git configuration I set the `--socket` option of the credential helper to use the variable `${XDG_CACHE_HOME:-${HOME}/.cache}/git/credential/socket` to store the it,

I don't understand what you are doing. Do you put these variables in some configuration file or pass them on the command line?

**Comment by jpprime** [comment]
> I don't understand what you are doing. Do you put these variables in some configuration file or pass them on the command line?

On my git configuration file. The lines on the configuration file are:
```conf
[credential]
	helper = cache --timeout=10800 --socket ${XDG_CACHE_HOME:-${HOME}/.cache}/git/credential/socket
```

**Comment by tarsius** [comment]
I wasn't aware that Git supports `${VARIABLE}` syntax and I am still not convinced that it does. If you could point me to documentation about this, I would appreciate it. It's possible that the value of this variable gets expanded by a shell before being passed to the helper command. I don't know.

However I do know that Magit does not deal with such variables at all. Magit just calls `git fetch/pull/push` and then `git` deals with collecting configuration like this variable.

So if this works on the command like but not from Magit, then this is likely just yet another instance of the shell and Magit having different environments. I.e. some relevant environment variables are probably configured in the shells init files but you click on an icon to start Emacs.

In this case the issue might even be that you use different `git` versions because of different values for `$PATH`. https://github.com/purcell/exec-path-from-shell might be useful here.

**Comment by jpprime** [comment]
It does appear that somehow my shell (and I've tried it with `ksh`, `zsh`, `dash` and `sh` and they all work in the same war, expanding the variable) is expanding the value of `${VARIABLE}` before executing the git command, although I'm not really sure why that is the since I don't have any extra steps on configuring git. I do have `$XDG_CACHE_HOME` configured on my shell configuration files (that are the same across all shells). For now I have set the value of `magit-credential-cache-daemon-socket` in my configuration to mimic the value in my git config and that works, I just thought that this is a behavior that git has that Magit wasn't making use of yet, so I guess this could be closed.
