### ISSUE TITLE
magit status keybind for jump to recent commits section

### ISSUE THREAD

**Issue by Lenbok** [magit/magit#4130]
Within the status buffer there are several shortcuts to jump to different sections (e.g. `j s` jump to staged, `j z` jump to stashes, etc).

However, there doesn't seem to be a shortcut for jumping to the "Recent commits" section. This would be quite handy to have.

**Comment by kyleam** [comment]
So, the recent commits section is a bit unusual.  936a211a (Treat recent commits as a variant of unpushed commits, 2018-07-16) nicely explains the details.  A consequence of that is that you _can_ actually jump to it by jumping to "unpushed to upstream" (<kbd>jpu</kbd>).

Of course that's not obvious, and at first glance I don't see an issue with adding a "Recent commits" entry to the `magit-status-jump` that would jump to the "unpushed to upstream" section.  I suppose it'd add a bit more potential for confusion because, if a user intended to jump to the recent commits but there are instead unpushed commits, they'd land on that.  But that's already the case in the reverse direction, so it doesn't seem worth avoiding.
