### ISSUE TITLE
unexpected behavior based on the value of "display-buffer-alist"

### ISSUE THREAD

**Issue by brandelune** [magit/magit#4132]
The code that is proposed here:
https://github.com/nex3/perspective-el#some-musings-on-emacs-window-layouts
to stabilize emacs Windows behavior severely conflicts with magit's basic behavior.

```
(setq display-buffer-alist
'((".*" (display-buffer-reuse-window display-buffer-same-window))))
```
The issue I registered there involves 2 frames:
https://github.com/nex3/perspective-el/issues/129

But even with one frame, magit's behavior is unsatisfactory.

With only one frame, here is the behavior:

c c  on staged contents → should display the commit message interface
instead, it reopens the diff display and then, a new c is required to access the commit message interface.

With 2 frames, the same c c kills the frame in which it was called and calls a diff on the front buffer of the other frame.

**Comment by tarsius** [comment]
```elisp
(setq magit-display-buffer-function magit-display-buffer-same-window-except-diff-v1)
```

might be all you need.

**Comment by brandelune** [comment]
Thank you. That was it. Shouldn't it be default behavior ?

**Comment by tarsius** [comment]
No but we should probably do the same as dd83d2dc2a3ab6492de471f2296078397bb0c75f for `magit-display-buffer-traditional` as well.

**Comment by brandelune** [comment]
Ok, thank you very much for the explanations.

**Comment by gcv** [comment]
@tarsius: I'm here because @brandelune used the `display-buffer-alist` setting above at my suggestion (https://github.com/nex3/perspective-el#some-musings-on-emacs-window-layouts), and has drawn my attention to its incompatibility with recent changes in Magit. I took the opportunity to re-read [The Zen of Buffer Display](https://www.gnu.org/software/emacs/manual/html_node/elisp/The-Zen-of-Buffer-Display.html).

Given that Magit now wants to display the diffs along with commit messages, and breaks under what I consider a necessary customization (and frankly, not at all drastic — especially considering that Magit has worked flawlessly with my settings for a decade, and I have not seen any other packages suffer), this seems like an appropriate time to use `display-buffer-overriding-action`. A little grepping suggests that `magit-diff.el` already uses it. And while the manual advises caution, given the critical nature of precise window control in this case, it seems like the right place to use it.

**Comment by tarsius** [comment]
I still consider it a radical customization to disallow packages from creating new windows by default. But lets agree to disagree. I just want to point out that Magit did not *break* due to this setting. It displayed the commit message in the selected window and then immediately displays the diff in the same window. With this setting you have to expect this sort of thing to happen in some contexts and learn how to quickly recover. In this case that can be done by pressing `q` to close the diff buffer.

I have adjusted `magit-commit-diff` and `transient-display-buffer-action` accordingly.

**Comment by gcv** [comment]
Perfect, thank you!

**Comment by tarsius** [comment]
Doing the "perfect" thing never comes without a price: https://www.reddit.com/r/emacs/comments/hllud/how_can_one_configure_magit_to_not_open_a_new/. I don't think I can work up the motivation to deal with that right now.

**Comment by acowley** [comment]
Yes, this change was certainly unwelcome for me. I never use more than one emacs frame, but this change leads to the creation of a new frame when committing, and that frame is not closed when finalizing or abandoning the commit. I use tiled window manager on my desktop, the new frame shuffles things around in an unpleasant way, and then I need to use window manager keys rather than emacs keys to clean up the extra frame.

I am fine with reverting the patch that did this for myself, but I'm also willing to put some effort into coming up a better solution. Would the addition of yet another configuration option to skip over the problematic line be okay, or is there still hope of finding something automatic that makes everyone happy?

**Comment by tarsius** [comment]
> Yes, this change was certainly unwelcome for me

Just to be clear: the observed behavior was in no way intended. There was an edge-case that didn't work as intended. We addressed that. That fix then broke something else. Creating a new frame for this is awful.

I don't quite understand why such breaking changes are assumed to be intentional, when really they are obvious regressions.

> I am fine with reverting the patch that did this for myself, but I'm also willing to put some effort into coming up with a better solution.

Wonderful. We don't want (1, see above) the diff buffer to "shadow" the git-commit buffer and (2) we don't want a second frame to pop up either. When the existing frame is small or the values of the "don't split frame if it is this small" variables are too small, then that is hard. The fix probably involves overriding these variables.

So we want to tell Emacs that we want to display these two buffers in the existing frame and two separate windows and we want that if we told it elsewhere that we don't like tiny windows. Something like that. :stuck_out_tongue_winking_eye:

**Comment by gcv** [comment]
I can't reproduce the frame-opening behavior described in the Reddit thread in a sandbox environment (i.e., just Magit with its dependencies installed, no user customizations at all), no matter how small I make the frames. Tried Emacs 26.3 and a (slightly old) build of 27 on Mac OS. Some people on the thread use tiling WMs, could this somehow be a contributing factor? (It shouldn't but you never know.)

**Comment by acowley** [comment]
@tarsius I'm glad to hear it's considered a regression! I did not mean to assume anything, but evidently misunderstood, "I don't think I can work up the motivation to deal with that right now." Apologies for jumping in.

**Comment by acowley** [comment]
Ah, sorry I didn't notice your response @gcv. I think you'd need to try a newer emacs. It's easy enough for users to work around, though, so not worth any more trouble.

**Comment by gcv** [comment]
Looks like Emacs versions 27.0.91 (and later) have this problem. `display-buffer` splitting behavior must have changed since 27.0.90. I can reproduce the problem with a tiny window, one shorter than `window-min-height`. This defaults to 4 (lines in height).

FWIW, undoing https://github.com/magit/magit/commit/035c24055c0e111187d554a0a214d6f0cbfb4bf1 still causes a crash when attempting to commit. In my case, the crash happens at the `transient-setup` level in `magit-commit`, before `magit-commit-diff` is ever called.

Setting `window-min-height` to 1 substantially reduces the impact, though the documentation says "Applications should never rebind this variable." :( It seems to me that small values of this variable impact everything using the `transient` framework.

@acowley, what is your `window-min-height` set to?

**Comment by acowley** [comment]
@gcv `window-min-height` is at the default of 4 for me. But neither I nor the other user on reddit reported any crashes, so you may be seeing something different. Also, reverting that commit does restore the previous behavior for both of us.

**Comment by gcv** [comment]
What happens if you set `window-min-height` and `window-min-width` to 1? (Just temporarily if course.) Also, would it be possible for you to try to reproduce the problem with a sandbox containing only magit (instructions: https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#test-your-recipe)?

**Comment by tarsius** [comment]
This is now controlled by an option: `magit-commit-diff-inhibit-same-window`. This is an opt-in option. If you used to rely on the `inhibit-same-window` behavior being forced while committing, then you now have to configure this option.
