### ISSUE TITLE
Magit always call tag --sign even if I choose the arguments

### ISSUE THREAD

**Issue by noloop** [magit/magit#4137]
Hi,

Version: Magit 20191128.1802, Git 2.24.1, Emacs 26.3, gnu/linux

When I do `t` and open the mini buffer below where I choose the arguments that I want:

![magit-tag-sign-bug](https://user-images.githubusercontent.com/25625276/83891489-9ee93900-a723-11ea-9bd6-bd4d1e7ce78c.png)

and I do `r`:

The magit did: `git … tag --annotate --sign -m Some\ 1.0.0 v1.0.0`

However I don't choice the `--sign` attribute as show the image above. Is it expected?

If yes, why? and how to I can use `git tag` command without `--sign` argument?

**Comment by tarsius** [comment]
> Is it expected?

As the doc-string says:

> Then call \"git tag --annotate --sign -m MSG TAG\" to create the,
> tag, regardless of whether these arguments are enabled in the
> popup.

> If yes, why?

Mostly historic reasons. Originally it was only intended for my own use and so I made it do what I wanted it to do. Maybe I now that someone doesn't like the hardcoded behavior I have to change it. Opinions?

**Comment by noloop** [comment]
I think that can leave as is, but with the user having the option of select and unselect arguments that he need.

**Comment by tarsius** [comment]
> I think that can leave as is, but with the user having the option of select and unselect arguments that he need.

"You don't have to change anything as long as you change it." :grin: 

----

I decided to not hardcode `--sign`.

If that isn't hardcoded, then `--annotate` should also not be hardcoded, so I don't do that either.

This will cause some existing users to create tags that are not annotated and not signed without noticing. It will also inconvenience users who previously used `t r` to created annotated signed release tags and `t t` to create tags to temporarily mark certain commits and which should therefore not be signed and usually also should not be annotated.

There's always a cost.

I have chosen to do it anyway because it increases consistency.

**Comment by noloop** [comment]
This was good. Thanks.

**Comment by georgek** [comment]
This change has just hit me... Fortunately I've just noticed because git, sensibly, doesn't push tags using `followTags` which aren't annotated. But it means I've also been creating unsigned tags without realising.

I do not understand the logic of removing `--annotate` from `t r`. Tags for releases should always be annotated. How can I revert to the previous behaviour?

**Comment by tarsius** [comment]
The infix arguments used by a certain transient popups can be [set/saved](https://magit.vc/manual/transient/Saving-Values.html) for future invocations.  TL;DR Enter the transient as usual, enable and/or disable arguments, and finally type <kbd>C-x s</kbd> or <kbd>C-x C-s</kbd>.

<sub>This is a [canned response](https://help.github.com/en/github/writing-on-github/working-with-saved-replies); it may not apply 100% in this case.</sub>

**Comment by georgek** [comment]
Thanks. I didn't know about saving infix arguments. That's very useful indeed. It's not quite the same behaviour as before, but it is an improvement in terms of consistency.
