### ISSUE TITLE
`magit-wip-mode` does not properly work when initialized from custom

### ISSUE THREAD

**Issue by sei-mwd** [magit/magit#4144]
# Expected behavior

After customising `magit-wip-mode` to `on`, saving the customization, and restarting Emacs, I expect that after running `M-x magit` within a git directory and editing files that these files (when saved, staged, etc.) would be checkpointed in the wip namespace.

# Actual behavior

After doing the above, changes are not checkpointed.  Running `M-x magit-wip-mode` says that it is toggling off the mode, and running `M-x magit-wip-mode` again causes checkpointing to work as expected.

# Testing methodology

I started a new emacs session using the following:
```
$ mkdir /tmp/testemacs
$ HOME=/tmp/testemacs emacs --no-site-file &
```
I then proceeded to use `M-x customize-group RET package RET` to add MELPA to `package-archives` and saved that customization.  After that I installed `magit` from `M-x package-list-packages`.  I then created a directory from dired and created a git-repository in it using `M-x magit`.  I checked in a file and verified that the log (`l a`) was clean and had no checkpoint entries.

Next I turned `magit-wip-mode` on using `M-x customize-group RET magit-wip RET`.  I saved setting.  I then edited the file in the repo, saved it, staged it, and committed it.  Using `l a` again I see the expected wip checkpoints.

Next I quit emacs and restarted it, again using:
```
$ HOME=/tmp/testemacs emacs --no-site-file &
```
I used `M-x magit-status` to view my repository.  The `Wip` lighter is on. I use `l a` to verify the log is unchanged.  I edit the file, save it, and stage it.  I then use `l a` again.  The changes to the file were not checkpointed.  Using `M-x magit-wip-mode` turns off the lighter and says, "Magit-Wip mode disabled".  Repeating that command turns `magit-wip-mode` back on.  Unstaging the staged file nd re-staging it then results in new commits being added to `index/refs/heads/master`.

**Comment by sei-mwd** [comment]
I forgot to include this.  After the previous test, this is the contents of `/tmp/testemacs/.emacs`:
```
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(magit-wip-mode t)
 '(package-archives
   '(("gnu" . "https://elpa.gnu.org/packages/")
     ("melpa" . "https://melpa.org/packages/")))
 '(package-selected-packages '(magit)))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
```

**Comment by tarsius** [comment]
Sadly global modes that have been defined using `define-minor-mode ... :global t` or `define-globalized-minor-mode` cannot actually be enabled using the Custom interface, if enabling the mode involves something other than `(setq the-mode t)`. That frankly is a long-standing bug in Emacs.

We ran into a similar issue with `magit-auto-revert-mode`. That case is slightly different because for that mode "on" is the default value. We therefore had no choice but to add a bunch of hacks to make it work anyway. Just look at [all the goo](https://github.com/magit/magit/blob/a1f8faaaebc5860e2f290cbcea76e4c114342a74/lisp/magit-autorevert.el#L137-L170) that follows the definition of the mode.

I don't intend to do that for `magit-wip-mode` or even pretty much every global mode I have implemented. Which leaves me with tree options:

1. Keep Emacs from making the false claim that the mode can be enabled using Custom. That would involve a lot of goo too.
2. Add "Despite the claim to the opposite elsewhere in this doc-string, this cannot actually be customized."
3. Get it fixed uptream.

1 and 2 suck and I don't have the energy for 3 right now. But in case I get around to it eventually here are some notes.

1. For global modes `define-minor-mode` should use `custom-initialize-set` as `initialize` function. That causes the `set` function to be used, by default `custom-set-minor-mode`.
2. `define-minor-mode` should define the mode function before the mode variable so that the function can be used while setting the variable.
