### ISSUE TITLE
Try to preserve point and mark when refreshing buffers

### ISSUE THREAD

**Issue by doublep** [magit/magit#4148]
My workflow when committing fixes for bugs is usually like this:

- commit;
- push with `P p`;
- while the push happens in background, go to the first line and copy commit hash with summary (`M-< M-f M-f M-b C-SPC C-e M-w`) so that I can paste it in an external issue tracking system.

The problem is that push sometimes finishes in the middle of the third step, so Magit refreshes its buffer, the point and mark get reset to the beginning of the buffer and I end up copying wrong text or have to restart it if I'm looking.

Request: when refreshing buffers, try to preserve point/mark positions if underlying text doesn't change. E.g. when pushing, most of the text in the buffer stays the same, only section "Unpushed to ..." disappears and contents of "Recent commits" changes slightly (branch head marks move around).

**Comment by tarsius** [comment]
> Request: when refreshing buffers, try to preserve point/mark positions if underlying text doesn't change.

Of course we already do that. Or more precisely we try to go to the "same" section as before (and then to the same position within that section). Because we recreate the complete buffer from scratch (yes I know; that will change eventually) we cannot actually go to the "same" section, instead we go to its "successor".

I suspect what happens in your case is that you are somewhere within the "Unpushed" section. Since that does not exist anymore after the refresh, we have to go somewhere else. A good fallback is to go to a parent or sibling (which we determine from the "pre-refresh" section tree). In this case that means ending up at the beginning of the buffer.

There's nothing we can do about it. We already lean heavily on the side of making sure what is being displayed is always up-to-date at the cost of performance. This is one of them edge-cases that slipped through anyway. The alternative would be to do everything synchronously, which .... would not be appreciated.

I recommend that you automate the work that you are currently doing manually. Maybe there is a suitable hook, otherwise you could advice the command or something like that.

**Comment by doublep** [comment]
> Of course we already do that.

Just went to position 3 in a buffer, typed `F p`. After it finished, point jumped to position 1, though nothing in the buffer changed (`master` was up-to-date with `origin/master`).

Maybe you only do it in trunk. I'm using the latest release stable version (2.90.1).

**Comment by tarsius** [comment]
> Just went to position 3 in a buffer

Please provide a self-contained description of that position or a screenshot. I had difficulties following the above description.

> Maybe you only do it in trunk. I'm using the latest release stable version (2.90.1).

It's possible there once was a bug that has been fixed by now. :stuck_out_tongue_winking_eye:

**Comment by doublep** [comment]
* `(progn (magit-given-directory "~/git/melpa") (goto-char 3))`
* Type `F p`.
* Wait a few seconds until it finishes.
* Point jumps to position 1.

**Comment by tarsius** [comment]
Ah I see.
There indeed seems some strangeness to be going on.

**Comment by doublep** [comment]
Forgot it's a function from my config.

* (progn (magit-status "~/git/melpa") (goto-char 3))
* Type F p.
* Wait a few seconds until it finishes.
* Point jumps to position 1.

**Comment by doublep** [comment]
Damn, sometimes notifications are sent too late.
