### ISSUE TITLE
Can not select arguments due to auto added blank space between "-" and "arg'

### ISSUE THREAD

**Issue by wztdream** [magit/magit#4177]
Here is the issue:
Suppose I want to run git push --force, so I need to choose -F argument, but after I type "-F" , the argument in minibuffer is always **"- F"**, note **there is a blank space between "-" and "F"**, so I can not select this argument, same issue for other commands.

Here is the version information:
M-x magit-version
**Magit 20200715.415, Git 2.17.1, Emacs 26.3, gnu/linux**

I installed magit from spacemacs using git layer.

I tried below debug method, **the issue still there**, except that **I can not find the ../ghub-xxx file**, so I omitted this setting when debugging. 

  $ cd ~/.emacs.d/elpa/magit-N
    $ emacs -Q --debug-init --eval '(setq debug-on-error t)' -L ../dash-N -L ../git-commit-N -L ../transient-N -L ../with-editor-N -L ../ghub-N -L . -l magit

**Comment by kyleam** [comment]
> the argument in minibuffer is always **"- F"**, note **there is a blank space between "-" and "F"**

That is also how things are displayed when things are working as intended (see image below)...

> so I can not select this argument, same issue for other commands.

... which means it's not clear to me that that's why you can't select an option.

Something as critical to Magit's operation as option selection would be generating lots of issues if it affected any sizable population of users, so my guess is that something pretty odd is happening on your end.

<details>
<summary>image: -F, vanilla config</summary>

magit (fccd3cff), transient (4d44d08)
Emacs 26.3, gnu/linux

![magit-opt-dispplay](https://user-images.githubusercontent.com/1297788/88754587-12f4fb80-d12d-11ea-8bae-6f778a1f5767.png)

</details>

**Comment by wztdream** [comment]
Thank you, I think this is my mistake. My issue should related with my repo and conflict between local and remote. I will closed it.
