### ISSUE TITLE
Update FAQ for A.2.11 git-commit-mode isn’t used when committing from the command-line

### ISSUE THREAD

**Issue by bitherder** [magit/magit#4178]
I wanted `git-commit-mode` active when I edit commit messages from the command line (via `git commit`), and found the [FAQ entry](https://magit.vc/manual/magit/git_002dcommit_002dmode-isn_0027t-used-when-committing-from-the-command_002dline.html#git_002dcommit_002dmode-isn_0027t-used-when-committing-from-the-command_002dline) indicating that special care is needed to make sure Emacs is started in daemon/server mode before using `emacsclient` to edit a commit message. At the same time, though, I noticed that emacsclient will now automatically start Emacs as a server if called with `--alternate-editor=""`. So, I messed around with the `use-package magit`, declaration in my `.emacs/init.el` and set the `core.editor` config for git and was able to get `git commit` to edit the commit message in `git-commit-mode` without having a daemon mode Emacs instance running beforehand.

Does it warrant updating the FAQ?

Magit version: Magit 20200728.45, Git 2.28.0, Emacs 26.3, gnu/linux

From `.emacs.d/init.el`
``` elisp
(use-package magit
  :ensure t
  :hook (after-save-hook . magit-after-save-refresh-status)
  :mode ("COMMIT_EDITMSG" . git-commit-mode)
  :bind (("C-x M-g" . magit-dispatch)
         ("C-x g" . magit-status)))
```

shell
``` bash
% git config core.editor
emacsclient --alternate-editor=''
```

**Comment by tarsius** [comment]
I would merge that, are you volunteering? :grinning: 

(Also fix s/then can still/then you can still/ please.)

**Comment by tarsius** [comment]
> (Also fix s/then can still/then you can still/ please.)

Done.

> Does it warrant updating the FAQ?

I have updated the FAQ myself but when I started to test it started to fail apart. So far I am dealing with issue that are particular to my setup (like most users would) but there might be fundamental issues that I just cannot experiment with because there are below a see of other issues.

I have written this FAQ entry so that I would have to spend less time helping users who have difficulties with this workflow and I don't really feel like invest time (beyond the two hours I just have) to document the optimal configuration, which as I have just figured out on myself can be problematic. Sorry.
