### ISSUE TITLE
Adding HEAD~ as a (default?) option when resetting

### ISSUE THREAD

**Issue by adamroyjones** [magit/magit#4189]
(I've had a brief dig around and I can't find a way to quickly add this feature myself; I barely know Emacs Lisp or how to develop "for" Emacs.)

When resetting in magit, a temporary buffer is created which is populated with commit references. Most of the time I find myself wanting to reset to HEAD~, but this commit reference is not in the list; it has to be written in full.

For me, the ideal situation would be that, not only were HEAD~ in the list, but HEAD~ were the default argument. I appreciate that my flow might be very different to what's typical (and that this is a kind of trivial thing to suggest).

What are your thoughts?

**Comment by kyleam** [comment]
As you suggest, I'd guess this is very workflow dependent.  A few thoughts:

  * You can spell "HEAD~" as "@~".

  * Rather than typing "HEAD~" (or even "@~"), you may find it more convenient to work with the log buffer to get point at the commit of interest (e.g. <kbd>llnx</kbd>).

  * If neither of those sounds appealing, you could get "HEAD~" as the default without any changes on Magit's end by doing something hacky but okay for personal configuration in my opinion:
  

    ```elisp
    (defun my/magit-read-branch-or-commit (fn prompt &optional secondary-default)
      (funcall fn prompt
               (if (string-match-p "\\`magit-reset" (symbol-name this-command))
                   "HEAD~"
                 secondary-default)))
    
    (advice-add 'magit-read-branch-or-commit :around
                #'my/magit-read-branch-or-commit)
    ```

**Comment by adamroyjones** [comment]
Thank you! I had no idea that @ was (generally) short for HEAD and I didn't know about `advice-add`, either. Your snippet works a treat.

Again—thanks.
