### ISSUE TITLE
Unable to commit changes

### ISSUE THREAD

**Issue by yevhenshymotiuk** [magit/magit#4209]
```
hint: Waiting for your editor to close the file... Waiting for Emacs...
*ERROR*: Unknown command: /Users/yevhenshymotiuk/.nixpkgs/.git/COMMIT_EDITMSG
error: There was a problem with the editor '/Users/yevhenshymotiuk/.nix-profile/bin/emacsclient --socket-name=/var/folders/c4/2s8rvbvj4djd7gl_ml8h98340000gn/T/emacs501/server'.
Please supply the message using either -m or -F option.
```

```
Magit 321214c3a2dd10fdf672ba96bd00703a51094bbe, Git 2.28.0, Emacs 27.1, darwin
```

Emacs is installed using [Nix](https://nixos.org/)(emacsMacport package)

**Comment by tarsius** [comment]
We don't use the issue tracker for support requests. Please use one of the options instead that are presented to you when you are about to create an issue.

**Comment by tarsius** [comment]
Actually in this case it might be better to discuss here. [Never-the-less, in the future please don't ignore the instructions.]

**Comment by yevhenshymotiuk** [comment]
Ok, understood

**Comment by tarsius** [comment]
> *ERROR*: Unknown command: /Users/yevhenshymotiuk/.nixpkgs/.git/COMMIT_EDITMSG

Somehow something along the way discards the actual command (something like `/path/to/emacsclient`). I suspect it has something to do with the indirections introduced by Nix.

**Comment by yevhenshymotiuk** [comment]
I've just tested it using ordinary emacs27 and everything works fine. Obviously, it in not related to magit itself

**Comment by fommil** [comment]
I see this with magit-2.90.1 when upgrading emacs27 to the `feature/native-comp` emacs28 branch described here: https://www.emacswiki.org/emacs/GccEmacs

(just noting this here for the next person who comes along, I wouldn't expect magit to support dev branches so I don't consider this a bug, although I'd love to hear about workarounds). Full output (which looks like there are really two issues) are

```
  1 git … commit --
hint: Waiting for your editor to close the file...
Waiting for Emacs...
*ERROR*: Wrong number of arguments: #<subr server-switch-buffer--with-editor-server-window-alist>, 5
error: There was a problem with the editor '/usr/bin/emacsclient --socket-name=/run/user/1000/emacs/server'.
Please supply the message using either -m or -F option.
```

**Comment by tarsius** [comment]
That's been fixed already, see https://github.com/magit/with-editor/issues/82. Just update `with-editor`.

**Comment by yevhenshymotiuk** [comment]
Issue remains the same in my case after update

**Comment by tarsius** [comment]
You additionally have to restart Emacs (or otherwise make sure the updated code is evaluated).

If that does not help; does the output really contain `*ERROR*: Wrong number of arguments: #<subr server-switch-buffer--with-editor-server-window-alist>, 5` in your case?

**Comment by tarsius** [comment]
Ah sorry, didn't see you are OP. So yeah, this is a different issue. (And @fommil hijacked your thread.)

**Comment by fommil** [comment]
(sorry, I thought it was the same thing)

**Comment by omidmnz** [comment]
I am commenting on a closed issue, since I had the same problem with newest versions of these packages and I digged deep:
I had the same problem, with latest packages on Emacs 29.1 on NixOS. The problem didn't occur on X.org, but it did when I used my configuration with `emacs-pgtk` on Plasma Wayland. However, it also didn't occur with vanilla Emacs using the same package, but with `emacs -Q`. One of my packages (which I didn't manage to pinpoint) sets the environment variable `TERM` to the empty string `""`, which messes with `emacsclient`.  For example, the following results in a similar error in my regular terminal environment:
```sh
export TERM=""
emacsclient /path/to/file
```
```
Waiting for Emacs...
*ERROR*: Unknown command: /path/to/file
```

If one unsets `TERM`, or sets it to `"dumb"` or `"xterm-256color"`, then `emacsclient` runs fine and Magit works as expected. I added the following to my configuration, which fixed the issue:
```elisp
(setenv "TERM" "dumb")
```

**Comment by tarsius** [comment]
This was a bug in `server.el`, fixed in https://github.com/emacsmirror/emacs/commit/68e337e630f8d0960cf971f066c27f315634bc39, which will be part of Emacs 31.1. (https://github.com/magit/with-editor/discussions/139 helped figuring that out.)

Also, it's surprising that TERM ends up being unset/empty when `with-editor` is involved, because `normal-top-level` does `(setenv "TERM" "dumb")`. Something else appears to undo the effect of that.

Never-the-less I've added a kludge to `with-editor--setup`. (Which won't help you if you use `emacsclient` from the command-line, so you should still update Emacs or backport the above commit.)
