### ISSUE TITLE
Keep remote branch tracking in sync with CLI

### ISSUE THREAD

**Issue by aiguofer** [magit/magit#4229]
I tried searching around but couldn't find anything, so forgive me if this has already been addressed.

One issue I have with magit is that I use both magit and CLI git, but the tracking of remote branches is not consistent between them. For example, if I run `git branch --set-upstream-to=origin/<branch> <local_branch>` in CLI, this doesn't affect magit. Similarly, if I push a branch to remote within magit, it asks me to select which remote branch to track and stores it for itself, but this doesn't have an effect on CLI git.

It'd be great if I only had to add that tracking info once in either magit or cli, and both respect it.

**Comment by tarsius** [comment]
That's not really possible because Magit uses the same `git` command to set the upstream that you use on the command line, e.g. `git branch --set-upstream-to origin/master master`.

It doing it inside Magit does not affect Git on the command line and vice-versa, then you most likely just aren't inside the same repository in Magit and the shell.

Or maybe you are confused about the difference between the upstream and the "push target". To pull from the upstream you need to use <kbd>F u</kbd> for example, <kbd>F p</kbd> acts on something else.

**Comment by aiguofer** [comment]
Yeah sorry... I just realized what's happening. Magit pushes by explicitly specifying the refs (`git push -v origin refs/heads/<branch>\:refs/heads/<branch>`). 

Since it only prompts you for source and target branch once, I assumed it was setting the tracking information, but I guess it's just storing that somewhere and re-using it on subsequent pushes.

IMO it would make sense if instead of storing the refs and explicitly specifying them, it actually set the tracking information and did a plain push. This would behave more like regular git workflows (at least from what I've seen).

**Comment by aiguofer** [comment]
Awesome, thanks a lot for all the explanations and that alternative!

**Comment by tarsius** [comment]
Made a small improvement and now you can use just:

```elisp
  (transient-insert-suffix 'magit-push "p"
    '("i" magit-push-implicitly))
```

**Comment by bersace** [comment]
> Made a small improvement and now you can use just:
> 
>   (transient-insert-suffix 'magit-push "p"
>     '("i" magit-push-implicitly))

Awesome. How to push implicitely current branch only ? Something like:

``` lisp
(use-package! magit
  :config
  (transient-insert-suffix 'magit-push "p"
    '("i" magit-push-implicitly (format "refs/heads/%s" (magit-get-current-branch)))))
```
