### ISSUE TITLE
Can't mark commit hashes, cursor cannot go everywhere

### ISSUE THREAD

**Issue by andreasabel** [magit/magit#4234]
Magit v2.90.1-1067-g2fb3bf78, Git 2.28.0, Emacs 27.1, darwin

I recently switched from magit-1 to magit-2 which introduced a ton of behavior changes.  (I like best so far the fine grained diff-display that highlights the changed code down to the character.)

What I am struggling with is the increase of _straitjacket_-style interaction.  By this I mean that I cannot arbitrarily move the cursor in a buffer, there are certain "no-go" areas.  As a consequence, I cannot mark e.g. a commit hash displayed in a `magit-revision` buffer, even if it is right before my eyes.  I cannot even mark it using the mouse.  This is very inconvenient if I e.g. want to use information I obtained from `magit-blame` and want to turn it into references in GitHub comment fields.  What I often want is to paste the commit hash there.

The free movement of the cursor is one of the great stengths of emacs.  E.g. in a `shell` buffer I can move everywhere, but only when I am back at the prompt my input is considered a command to be executed.  (I guess this applies more generally to `comint`-style interaction, but I am not an expert.)

Being able to mark _anything_ in a buffer is the great strength of textual user interaction (cf. shells) and this is why I prefer emacs over more graphical "windowsy" solutions.

Please bring back the free cursor movement!

(Suggestions for workarounds also welcome.)

**Comment by tarsius** [comment]
> The free movement of the cursor is one of the great stengths of emacs.
>
> Please_ bring back the free cursor movement!
>
> (Suggestions for workarounds also welcome.)

Magit does not actively prevent you from interacting with certain text. It just started to use some Emacs features that happen to do that. I too think that is very unfortunate but I cannot do anything about it except provide workarounds.

> I cannot mark e.g. a commit hash displayed in a magit-revision buffer,

Yes, you cannot copy text from the sticky header because Emacs does not allow you to do so. As a workaround Magit displays the hash a second time at the top of the buffer, but to access you have to scroll to the beginning (as you used to with previous Magit releases too).

> I e.g. want to use information I obtained from magit-blame 

This is implemented using overlays and Emacs does not allow copying text displayed using overlays. One workaround is to press `RET` to display the appropriate revision buffer and then copy information from there. You can also use `M-w` in the file-visiting buffer with the blame information to copy the hash of the commit concerning the current line.

**Comment by andreasabel** [comment]
One year later, I can only state how much I enjoy the new magit!  It is a huge productivity gain, I use it everyday and on all my projects.  Excellent work, @tarsius !
