### ISSUE TITLE
Allow marking a remote as "read-only" to avoid pushing to it

### ISSUE THREAD

**Issue by rswarbrick** [magit/magit#4242]
I use magit heavily and many projects that I contribute to use the GitHub "pull request development model". So I'll have a repository with two remotes (I tend to use `origin` and `rjs`; I think the GitHub tutorials usually suggest `upstream` and `origin`, respectively).

When I have some changes ready to push, I do something like `P e M-n` to push them "elsewhere" and then use `M-n` to guess a name based on the current branch. This is great! But it guesses `origin/my-branch` before `rjs/my-branch`. I can avoid embarrassing pushes to `origin` by using an `https://` URL there. However, if I get the wrong remote then I still get dropped in to the process buffer being asked for a username and password.

I'd love to be able to mark `origin` as being read-only so that magit didn't suggest it as a possible push target. Looking quickly at the code, I think the name suggestions are done in `magit-read-remote-branch`, which is used for both pushing and pulling, so I don't *think* I can do this with the current version of magit (well, not without some advice functions).

Maybe a nice way to do this would be to plumb a `:read` or `:write` keyword through `magit-read-remote-branch` and then filter the return value of `magit-list-remotes` in some way? Either a customisable "don't push to https" switch, or a user-supplied filter function that gets the flag there?

EDIT: Gah, I didn't say: Thank you very much for an absolutely brilliant git frontend.

**Comment by kyleam** [comment]
I'm not sure what I think of the idea, but in case you haven't considered it: I think this issue largely goes away if you configure your `@{upstream}` and `@{push}` remotes [1].  In particular, you can configure your feature branch to use a _local_ branch as the upstream and then use <kbd>P p</kbd> (`magit-push-current-to-pushremote`) to push to the intended target.  With that configuration, there is no risky of pushing to the unintended remote because 1) you're not selecting it from a list of candidates and 2) if you choose <kbd>P u</kbd> (`magit-push-current-to-upstream`) instead, it isn't wired up to a remote.

[1] https://magit.vc/manual/magit/The-Two-Remotes.html

**Comment by phil-s** [comment]
FWIW I personally still find this useful: https://github.com/magit/magit/issues/2589

**Comment by tarsius** [comment]
Still not a fan. Let's leave it as is.

**Comment by rswarbrick** [comment]
Thanks for the responses. It seems that `remote.pushdefault` is exactly what I needed to set. Brill!
