### ISSUE TITLE
Suggestion: Replace magit-maybe-save-repository-buffers etc. in magit-status with "Unsaved buffers" section

### ISSUE THREAD

**Issue by CyberShadow** [magit/magit#4285]
Hi @tarsius, and thank you for all your work on magit. I would like to make a suggestion which I hope is not too egregious.

Hopefully we can be agree that inserting modal prompts which appear only *sometimes* in the middle of a process which the user would otherwise do in seconds is not good UX. The "Save file" prompts are currently my #​1 annoyance with magit, and the most frequent cause for getting into a confused state where I have to hammer G-g and C-] to get out of. Though `magit-save-repository-buffers` exists, the options offered are to never save (which is desired rarely), always save (which is desired often but not always, and is not undoable), and the prompts.

I would like to suggest the following changes, which would be in my opinion an improvement:

- Only show the save prompts before operations where saving modified buffers would affect the outcome, such as staging files, pushing a stash, or diffing against the work tree in a context other than `magit-status`.
- In `magit-status`, add a section before "Unstaged changes" which enumerates modified buffers for files belonging to the current repository.
  - `k` (`magit-delete-thing`) would revert the buffer.
  - `C-x C-s` (`write-buffer`) with point on a file's entry would save it.
  - For bonus coolness, show the diff between the file on disk and the buffer contents, by piping the buffer contents into `git diff`'s standard input.

The new section should still clearly inform the user that they have unsaved buffers without interrupting them. Being able to see a diff between the buffer and the file could be a useful feature by itself.

I'm happy to attempt an implementation :)

**Comment by tarsius** [comment]
> always save (which is desired often but not always, and is not undoable)

Never-the-less that is what I use and recommend to others. Actually I don't remember the last time I felt that the automatic saving was a problem.

> Only show the save prompts before operations where saving modified buffers would affect the outcome, such as [...]

It would also mean that we should have to go through all operations we offer and determine whether it is one of those, and whenever we added a new operation we would have to think about again. And if we stop doing always, then we would probably end up having to do it by explicitly calling the "maybe save" function in a hundred or more places.

Since I think "everyone" would be best adviced to just go with the "always save" setting, I don't think this effort is justified.

> I'm happy to attempt an implementation :)

You could do so by advising `magit-maybe-save-repository-buffers` to only do anything if `this-command` is not one of a certain set of commands. Coming up with that set would constitute most of the work.

> add a section [...] which enumerates modified buffers for files belonging to the current repository. 

I would probably merge a pull-request that adds such a section inserter. It should not be used by default.

**Comment by CyberShadow** [comment]
> Never-the-less that is what I use and recommend to others. Actually I don't remember the last time I felt that the automatic saving was a problem.

OK, here are two circumstances where automatic saving is a problem for me:

1. I accidentally pressed a button in some buffer or made some other unintentional change
2. I started doing some edit but wish to run the application without that edit still applied

Going ahead with the save, realizing that the new on-disk state is not what I wanted, then spending time carefully undoing it is annoying and probably worse than the prompts. Some languages/projects have slow build times, which contributes to the frustration - unintentional edits invalidate the last cached build. I would have to change my workflow to actively avoid making changes which I did not want committed to disk, which I think would overall translate to negative productivity.

> It would also mean that we should have to go through all operations we offer and determine whether it is one of those, and whenever we added a new operation we would have to think about again. And if we stop doing always, then we would probably end up having to do it by explicitly calling the "maybe save" function in a hundred or more places.

Besides the additional work, is this not a good thing? It would more accurately describe the expected actions of the git commands that magit invokes, establishing a contract - perhaps it can be automatically verified in tests?

> Since I think "everyone" would be best adviced to just go with the "always save" setting, I don't think this effort is justified.

What makes you say that "everyone" would be best adviced to just go with the "always save" setting? I'm sorry to hear you say this, as it seems like a subpar compromise to me.

> You could do so by advising `magit-maybe-save-repository-buffers` to only do anything if `this-command` is not one of a certain set of commands. Coming up with that set would constitute most of the work.

Thanks for the pointer :)

**Comment by tarsius** [comment]
> OK, here are two circumstances where automatic saving is a problem for me:
> 
>     1. I accidentally pressed a button in some buffer or made some other unintentional change

In that case I find the automatic saving highly desirable because it allows you to immediately see when you messed up. If you become aware of that slip up later, then it can be harder to revert because you have lost context.

>     2. I started doing some edit but wish to run the application without that edit still applied

For that I use stashes.

> Some languages/projects have slow build times, which contributes to the frustration - unintentional edits invalidate the last cached build.

I can see how that would be annoying.

> I would have to change my workflow to actively avoid making changes which I did not want committed to disk, which I think would overall translate to negative productivity.

Yes. We don't want that.

> > It would also mean that we should have to go through all operations we offer and determine whether it is one of those, and whenever we added a new operation we would have to think about again. And if we stop doing always, then we would probably end up having to do it by explicitly calling the "maybe save" function in a hundred or more places.
> 
> Besides the additional work, is this not a good thing? It would more accurately describe the expected actions of the git commands that magit invokes, establishing a contract - perhaps it can be automatically verified in tests?

I think it would not work because there would be disagreement about which commands should save. For example I think that `magit-status` should definitely save, while you probably consider that a prime example of a command that should not do so.

> > Since I think "everyone" would be best adviced to just go with the "always save" setting, I don't think this effort is justified.
> 
> What makes you say that "everyone" would be best adviced to just go with the "always save" setting? I'm sorry to hear you say this, as it seems like a subpar compromise to me.

That's just my opinion. I do realize that this is not an objective truth.

> > You could do so by advising `magit-maybe-save-repository-buffers` to only do anything if `this-command` is not one of a certain set of commands. Coming up with that set would constitute most of the work.
> 
> Thanks for the pointer :)

On second thought, wouldn't the best option for you be to just disable this feature completely? Especially if you implement the "unsaved buffer" section that informs you when there are such buffers.

**Comment by CyberShadow** [comment]
> In that case I find the automatic saving highly desirable because it allows you to immediately see when you messed up. If you become aware of that slip up later, then it can be harder to revert because you have lost context.

This makes sense only in the context of there not being another mechanism to inform you of this slip up. This is why I think the magit-status section is an integral half of this proposal, and neither half makes much sense without the other.

> For that I use stashes.

That doesn't work very well if the working tree is already dirty :) And, it still invalidates the build cache.

> I think it would not work because there would be disagreement about which commands should save. For example I think that `magit-status` should definitely save, while you probably consider that a prime example of a command that should not do so.

`magit-status` should save if and only if the "unsaved changes" section is not enabled. The rationale is as follows. The condition I descibed remains the same: prompt to save before operations where doing / not doing so affects the outcome. Here, the outcome is that the user is informed of all changes, including unsaved ones, when viewing the `magit-status` buffer. If the "unsaved changes" section is disabled, then we must (prompt to) save so that the changes appear in the "*unstaged* changes" section. Otherwise, the changes will be visible in the "unsaved changes" section. Does that make sense to you?

> That's just my opinion. I do realize that this is not an objective truth.

I understand. I think we would reach a better outcome if we tried to analyze this objectively, but I don't know if we have sufficient data for this - e.g. how often do users attempt to perform git operations using magit but not going through `magit-status`.

> On second thought, wouldn't the best option for you be to just disable this feature completely? Especially if you implement the "unsaved buffer" section that informs you when there are such buffers.

It's a compromise to consider. The proposal above is directed towards all magit users, and I still earnestly believe it would be an unilateral improvement for them, which is why I'm sad that you disagree subjectively. If the effort of instrumenting all git operations is not deemed worthwhile, then this would be acceptable, but only personally - it would no longer be something that could be recommended to everyone.

**Comment by tarsius** [comment]
I understand your arguments and I am confident you are not the only who consider the proposed change an improvement.

> > On second thought, wouldn't the best option for you be to just disable this feature completely? Especially if you implement the "unsaved buffer" section that informs you when there are such buffers.
> 
> It's a compromise to consider. The proposal above is directed towards all magit users, and I still earnestly believe it would be an unilateral improvement for them. If the effort of annotating all git operations is not deemed worthwhile, then this would be acceptable, but only personally - it would no longer be something that could be recommended to everyone.

As a side-note, the current behavior is already a compromise. The previous behavior and my strong preference is to save without asking.

I have no intention to annotate all git operations. I suggest you implement this using advice and then use and fine-tune it over the next few months. If you still feel the same way after that period, then we can discuss again. Even if I rejected it then still, you could make it available to other users by releasing it as a separate package.

The work involved in this is just too much for something that I do not believe in. This is true even if you do all the initial work because this is something that would have to be kept up-to-date forever.

**Comment by CyberShadow** [comment]
Thank you for the consideration.

> I would probably merge a pull-request that adds such a section inserter. It should not be used by default.

Does this still apply?

**Comment by tarsius** [comment]
Yes.
