### ISSUE TITLE
The output directory of format-patch uses the remote directory

### ISSUE THREAD

**Issue by snogge** [magit/magit#4322]
When using magit over tramp, the `--output-directory` option of format-patches includes the remote-file prefix. Git quite naturally does nor know what to do with this. 
I'm not sure where the fix should be, `transient-read-directory` should probably not unconditionally assume that the local file path is what is wanted. Should a new transient directory reader be added? 

Magit 20210209.1110, Git 2.29.2, Emacs 28.0.50, gnu/linux

**Comment by tarsius** [comment]
> `transient-read-directory` should probably not unconditionally assume that the local file path is what is wanted.

I am leaning towards doing that anyway. I am confident that most callers expect that (i.e. all that pass arguments to some child process, and that is the original use-case after all). If it turns out that some callers need the remote part, then we can add new variants for that.

On the other hand, we should probably use `magit-convert-filename-for-git` instead of `file-local-name` but a function that is defined in `transient.el` cannot do that. So we might end up adjusting `transient`'s functions but also adding `magit`-specific variants.

Regardless what function we use we would end up prompting the user with `--arg=/ssh:host:/foo/bar` but actually use `/foo/bar` as the value and also display it as `--arg=/foo/bar` in the transient popup. That's a bit unfortunate but I am not aware of an alternative to `read-{directory,file}-name` that reads a remote file name while showing it as a "local" name while reading.

**Comment by snogge** [comment]
Maybe we could add some information to the prompt or a hint at the right side of the minibuffer?
The tab completion is invaluable, and I think most users that uses tramp like this will understand what is going on.

**Comment by tarsius** [comment]
> a hint at the right side of the minibuffer?

That's a new thing in Emacs 28, right? I haven't figured out how that works yet.

**Comment by snogge** [comment]
> > a hint at the right side of the minibuffer?
> 
> That's a new thing in Emacs 28, right? I haven't figured out how that works yet.

I'm not sure. I've only read about it myself.

**Comment by snogge** [comment]
Thank you!
