### ISSUE TITLE
Add support for an alternative magit-pop-revision-stack-format that is used when magit-pop-revision-stack is invoked with the universial-argument

### ISSUE THREAD

**Issue by Flowdalic** [magit/magit#4376]
I like the default value of magit-pop-revision-stack-format, but sometimes I want to use a briefer format, i.e. kernel-style git-revision references like  `48d75eafdf5b ("update aspell.en.pws")`. My idea would be to have another format specification, e.g. magit-pop-revision-stack-format-alternative that is used when magit-pop-revision-stack is invoked with the universial-argument (`C-u C-c C-w`).

**Comment by kyleam** [comment]
Also, `magit-pop-revision-stack` has already claimed `C-u` (and `C-u C-u`) for other things.

If setting a value at the project level doesn't work for you (because you want to use multiple formats within a project), another option is to use `magit-pop-revision-stack` for whatever you consider your primary format, and then define custom commands for the other styles (presumably just one or two) you'd like:

```elisp
(defun my/magit-insert-fixes-header ()
  (interactive)
  (let ((magit-pop-revision-stack-format '("Fixes: %h (\"%s\")")))
    (call-interactively #'magit-pop-revision-stack)))
```
