### ISSUE TITLE
Add option to disable file filter by default when using log with "limit to files"

### ISSUE THREAD

**Issue by prati0100** [magit/magit#4382]
Hello,

Currently when I run a log with `--`, opening a log diff with enter opens the diff limited to files specified to `--`. I have to press `DF` to see the full diff. I am usually more interested in seeing the full diff and would like to have the filter off by default, and I can turn it on by pressing `DF`. `man git-log` has the option `--full-diff` so that can be used as the option name I think.

**Comment by kyleam** [comment]
[ This is similar to the request in gh-3793. ]

I'm not convinced we should add an option, but you can almost get the behavior you want with

```elisp
(require 'magit)

(defun my/magit-diff-swap-file-restriction ()
  (when (local-variable-p 'magit-buffer-diff-files)
    (cl-rotatef magit-buffer-diff-files
                magit-buffer-diff-files-suspended)))
(add-hook 'magit-setup-buffer-hook #'my/magit-diff-swap-file-restriction)
```

The catch is that this brings an existing bug closer to the surface.  If you move to the next line, `DF` won't remember the log's filter.  That can be fixed with the below patch, but I haven't thought too deeply yet about whether that introduces other issues.

```diff
diff --git a/lisp/magit-log.el b/lisp/magit-log.el
index a07b7198..a8643f42 100644
--- a/lisp/magit-log.el
+++ b/lisp/magit-log.el
@@ -1364,9 +1364,8 @@ (defun magit--maybe-update-revision-buffer ()
       (setq magit--update-revision-buffer (list commit buffer))
       (run-with-idle-timer
        magit-update-other-window-delay nil
-       (let ((args (with-current-buffer buffer
-                     (let ((magit-direct-use-buffer-arguments 'selected))
-                       (magit-show-commit--arguments)))))
+       (let ((args (let ((magit-direct-use-buffer-arguments 'selected))
+                     (magit-show-commit--arguments))))
          (lambda ()
            (pcase-let ((`(,rev ,buf) magit--update-revision-buffer))
              (setq magit--update-revision-buffer nil)
```

**Comment by kyleam** [comment]
Following gh-4390, the snippet above should achieve the behavior you're after (file filter off by default).  I don't know how rare your preference is, but, at least until it becomes clear that it's a bit more common, I'm in favor of leaving this as is.

**Comment by prati0100** [comment]
> I don't know how rare your preference is, but, at least until it becomes clear that it's a bit more common, I'm in favor of leaving this as is.

:-(

Thanks for looking into it!

**Comment by aaronjensen** [comment]
I'll just say that this behavior caught me by surprise. So much so that my analysis of some history was flawed because I was under the impression that a commit only changed a single file. 

When I go to a commit, I have no expectation that that what I would be seeing would be anything but the commit. To see a commit that is filtered by the file I was looking at is a violation of expectation because it's not the thing that I thought I was navigating to.  

I could see having two options for navigation, but I would expect the default one to not include the file filter (perhaps it could have the current file expanded and everything else collapsed, but that's just a potentially unnecessary elaboration).

**Comment by tarsius** [comment]
> That wasn't at all discoverable,

At the top it says "commit abc limited to file foo".

**Comment by aaronjensen** [comment]
Yeah, I did eventually see that, but only after I saw the problem. I think the only way to make it discoverable would be to show it near the list of files. That's where I'm looking, I don't tend to read the full header, I only read enough to identify where I am.
