### ISSUE TITLE
Make revisions buffer truncate long lines.

### ISSUE THREAD

**Issue by antoineB** [magit/magit#4397]
In revision/status/diff buffers long lines (minified javascript for instance) make the buffer slow to load and slow to scroll.

It should be possible to remove the problematic text just after the result of the git command.

PS: Maybe there is a hook ?
PS: so-long.el is fine for displaying the content but it breaks the jump to file, folding etc...

**Comment by antoineB** [comment]
Is magit-diff-wash-diffs-hook the right way to go ?

**Comment by phil-s** [comment]
>  PS: so-long.el is fine for displaying the content but it breaks the jump to file, folding etc...

Untested, but is that still the case if you use `so-long-minor-mode` ?

**Comment by phil-s** [comment]
A quick test with the following seems functional to me:

```el
(add-hook 'magit-diff-mode-hook 'so-long-minor-mode)
(add-hook 'magit-status-mode-hook 'so-long-minor-mode)
```

Colours are obviously using text properties directly, so they're unaffected.

YMMV (not sure what sort of diffs you're actually dealing with), but perhaps that helps?

**Comment by phil-s** [comment]
I think you can simply use `string-match-p` instead of loading `s.el` just for `s-matches?` ?

> so-long-minor-mode remove fontification of hunks

I can't tell whether you think that's a good thing or a bad thing, but font-lock tends to be one of the biggest problems when it comes to long lines, so this is definitely expected -- it's usually one of the more important things that so-long does.

FWIW you can modify its behaviour using major mode hooks, like this:

```el
(add-hook 'magit-status-mode-hook #'my-magit-so-long-behaviours)
(add-hook 'magit-diff-mode-hook #'my-magit-so-long-behaviours)

(defun my-magit-so-long-behaviours ()
  "Use/customise `so-long-minor-mode' for Magit diff buffers."
  (setq-local so-long-minor-modes
              (remove 'font-lock-mode so-long-minor-modes))
  (so-long-minor-mode 1))
```

**Comment by tarsius** [comment]
Since this issue is not limited to Magit but affects all buffers that have exceptionally long lines I do not intend to add any magit-specific workarounds. My recommendation is to avoid using magit when adding minified javascript (which could be considered some form of binary data). Commit it on the command-line and if you *really* need to look at the diff, then use some other tool or follow @phil-s' advice.
