### ISSUE TITLE
line tracking not working

### ISSUE THREAD

**Issue by Lenic** [magit/magit#4426]
I find the line tracking command not working **above git 2.30.1**

## My opearation is

1. clone: https://github.com/Lenic/test-tailwindcss
2. open file: `src/App.vue`
2. execute in Emacs: M-x magit-log RET -L RET 2,5 RET l
3. result: `(empty)`

## My configuration

```lisp
(use-package magit
  :bind ("C-x m" . magit-status)
  :config
  (setq magit-diff-refine-hunk (quote all))
  :hook ((magit-post-commit-hook) . 'git-gutter:update-all-windows))
```

And the `magit-version` output:  `Magit 20210629.1917, Git 2.30.1 (Apple Git-130), Emacs 27.2, darwin`

## Important:

- Git 2.26.3 and below is normal: can see the line tracking history
- Git 2.30.1 and above is invalid: can not see the line tracking history
- Bug appear os: mac big sur 11.4 with git 2.30.1, alpine 3.13 in docker with git 2.30.2

**Comment by tarsius** [comment]
The problem is that when invoked like this we end up with all these arguments: `-L1,10:lisp/magit.el -- lisp/magit.el`. For now you can deal with this by explicitly removing the `--` argument and it's value. I'll look into automatically disabling `--` when adding `-L`.

But I recommend you use this alternative workflow: select the lines using the region, then press `C-c M-g l`.

**Comment by Lenic** [comment]
It's wonderful! Thanks!
