### ISSUE TITLE
Operations on commits (delete, squash) directly in a commit list

### ISSUE THREAD

**Issue by geza-herman** [magit/magit#4431]
Magit already supports some convenience things which use interactive rebase under the hood (for example, `magit-edit-line-commit`). There could be another convenience features related to commits: when the cursor is on a commit (in a commit list, like "Recent commits"), `magit-delete-thing` could delete the commit (instead of saying "There is no thing at point that could be deleted"). If a region is active, `magit-delete-thing` could delete all the commits in the region. Magit could also support squashing in a commit list right away (select the commits, and a new command would squash the selected commits).

Here's a use case for commit deleting: I executed a rebase, and unfortunately git chose the wrong commit as the merge base, and rebased more commits than I wanted. So I had to delete the extra commits. A commit list ("Recent commits", or any other log) has more context (branch labels, etc.) than the commit list in the rebase editor, so it would have been easier to delete the extra commits from the "Recent commits" list than the commit list of the rebase editor (I could have undo the rebase, and rebase `a subset`, but it was easier to just delete the extra commits).

**Comment by tarsius** [comment]
This has been suggested before but I still think this is too dangerous. What one currently has to do isn't too bad either: move to the commit (as with the proposed workflow) then <kbd>r k C-c C-c</kbd>. Sure that's more keys and the rebase menu pops up a long the way, but for removing commits, this seems okay.

> A commit list ("Recent commits", or any other log) has more context (branch labels, etc.) than the commit list in the rebase editor,

Since you can select the commit in the former list before initiating the action that seems okay. All you *have to* do in the rebase editor is to say "yes, that's the commit" by immediately typing <kbd>C-c C-c</kbd>.

If you add

```elisp
(define-key magit-commit-section-map [remap magit-delete-thing] 'magit-rebase-remove-commit)
```

then you get almost what you want, except you still have to confirm with <kbd>C-c C-c</kbd>.

Yes, deleting *multiple* commits still requires <kbd>r i ...</kbd>

**Comment by geza-herman** [comment]
Okay, this was just an idea, and it seems it's not a new one :)

Thanks for the mapping idea!

(A reflection that it is dangerous: if someone doesn't know about the reflog then yep, it's dangerous. But with the reflog, it's easy to undo an accidental remove. It would make sense that this feature would need an explicit enable by some variable. But I understand that this idea is just a minor convenience feature, not the most important thing)
