### ISSUE TITLE
Avoid loading magit when setting `magit-define-global-key-bindings`

### ISSUE THREAD

**Issue by phikal** [magit/magit#4446]
When I set `magit-define-global-key-bindings` to nil via customize, magit is always loaded when Emacs starts and slows down the entire configuration process. My understanding is that this is because

   (get 'magit-define-global-key-bindings 'custom-loads)

evaluates to `("magit")`. And if I take a look at `magit-autoloads.el`, I find

   (custom-autoload 'magit-define-global-key-bindings "magit" t)

which I guess was added because `magit-define-global-key-bindings` has an auto-load cookie.

My guess is that this issue could be solved by removing the auto-load cookie, but I am uncertain as to why it was added in the first place and what unintended side effects removing it would have.

**Comment by phil-s** [comment]
The side effects of removing the autoload cookie would be to prevent the option from having any effect at all, so that's not the solution (see the source code, and pay attention to the autoloaded form which follows the definition of that option, all of which runs at init time, and which is redundant if it runs *after* init time).

**Comment by phil-s** [comment]
I'm not familiar with the mechanism, but I see
```el
(custom-autoload 'magit-define-global-key-bindings "magit" t)
```
in my `magit-autoloads.el` and `custom-autoload` says:

> If NOSET is non-nil, don’t bother autoloading LOAD when setting the variable.

Which is that final `t` which is therefore non-nil, so feels like the *intention* is that no autoload happens in your scenario; so I'm not sure why that ends up happening.  I may be misunderstanding things though.

**Comment by tarsius** [comment]
> When I set `magit-define-global-key-bindings` to nil via customize,

I wasn't able to reproduce that. @phil-s you tried and failed too, right?

> "Setting this variable after [`after-init-hook`] has already been called has no effect." which isn't actually true (but may have been when that note was written).

Well, one could argue it isn't wrong since "hook" can also refer to the hook function and once that has run it really is too late, regardless of whether it was run as a member of the value of the hook variable. But yeah, its probably a good idea to word this more carefully here, so how does this sound?:

*Setting this variable to nil has no effect if that is done after the key bindings have already been added.*

**Comment by phil-s** [comment]
> I wasn't able to reproduce that. @phil-s you tried and failed too, right?

Not until now, actually; but now that I have, I get the same result as yourself -- I can't replicate the issue.

**Comment by phikal** [comment]
Hmm, the simplest code I need to reproduce this is to add 

```elisp
(customize-set-variable 'magit-define-global-key-bindings nil)
```

to my init.el, and it hangs for a little less then a second. When extracting the code and removing 

```
(custom-load-symbol variable)
```
the issues disappears.

This happens for both Emacs 27.2 and 28.0.5

> The side effects of removing the autoload cookie would be to prevent the option from having any effect at all, so that's not the solution

I see, but what other way would there be to avoid this issue (besides removing the automatic bindings, which I gather the magit team is not interested in)?

**Comment by tarsius** [comment]
Like that I can reproduce it too, I just tried `setq` and using the Custom interface.

I am not sure, but this might be considered a bug in `customize-set-variable`. After all `custom-set-variables` doesn't load the library, so why would the former [have to] do it?

I would appreciate it if you could discuss this on emacs-devel. Meanwhile we should extend the doc-string to say that one should use `setq` or click around in the Custom interface, but not use `customize-set-variable`. Even if this is a bug and it gets fixed, that won't affect older Emacsen so we have to do this anyway.

**Comment by phil-s** [comment]
> how does this sound?:
> 
> _Setting this variable to nil has no effect if that is done after the key bindings have already been added._

Yes, in context with the rest of the docstring I think that's good.

I think the two instances of `` `after-init-hook' is called `` ought to be changed to `` `after-init-hook' runs `` though.  Functions are "called"; hooks are "run".

**Comment by phikal** [comment]
> I am not sure, but this might be considered a bug in customize-set-variable.

I am not sure: It makes sense to load a library when configuring a autoloaded user options, because it might have a custom setter that depends on the library itself. What might make sense is to bring up the point of not autoloading the library when no explicit setter was declared.

**Comment by tarsius** [comment]
Yeah, it seems intentional that these functions behave differently as opposed of the only difference being that one acts on one variable and the other on many. This should be better documented though. And I expect that many people who use `customize-set-variable` actually wanted "`custom-set-variables` for a single variable".

But `customize-set-variable` doesn't do that so using it and expecting it do do that is a user mistake. I'll deal with it with documentation.
