### ISSUE TITLE
libgit ci targets fail due to glibc mismatch

### ISSUE THREAD

**Issue by tarsius** [magit/magit#4456]
```
Run make test-libgit DASH_DIR=$PWD
Error while loading ‘magit-libgit’: (module-open-failed \
  "/nix/store/q0km1xfg5s49arln7xynjxbmqbjkhs8v-emacs-packages-deps/share/emacs/site-lisp/elpa/libgit-20210620.2017/build/libegit2.so" \
  "/nix/store/ikl21vjfq900ccbqg1xasp83kadw6q8y-glibc-2.32-46/lib/libc.so.6: \
  version `GLIBC_2.33' not found (required by /nix/store/yk1a9cr0c9wiax1dkaz40xpil9g8g2il-libgit2-1.1.0/lib/libgit2.so.1.1)")
That is not fatal.  The ‘libegit2’ module just won’t be used.
libgit not available.
make: *** [Makefile:128: test-libgit] Error 1
Error: Process completed with exit code 2.
```

E.g.: https://github.com/magit/magit/runs/3170540769

Do you by any change know how to deal with that @cedarbaum ... and @lambdadog... well, based on the keywords in your profile I am pretty sure you do. :grinning: I would very much appreciate your help. Cheers!

**Comment by tarsius** [comment]
There's now a second issue that also makes the non-libgit tests fail:

```
error: attribute 'passthru' missing, at /nix/store/icxs86xpccp18v50y19ykyi8wa5v000n-nixexprs.tar.xz/pkgs/top-level/emacs-packages.nix:81:18
```

**Comment by lambdadog** [comment]
Sorry for the delay, I'll give a look to proposing a PR soon. Taking a cursory look, the big issue I see is that we're not pinning anything *anywhere*, so we're losing a lot of the benefits of nix/nixpkgs.

`<nixpkgs>` is provided by the [cachix install action, using a channel](https://github.com/magit/magit/blob/0348f1f87c9eb923a63aa6ca1d06af9093310409/.github/workflows/test.yml#L24), when channels are constantly being updated. The other inputs are provided using [fetchTarball on the `master` branch](https://github.com/magit/magit/blob/0348f1f87c9eb923a63aa6ca1d06af9093310409/t/default.nix#L2), which similarly offers a lot of CI inconsistency.

**Comment by lambdadog** [comment]
This brings two goals into conflict: 
  - we want CI to be running on the latest versions of everything as that's what users are likely to use and is the "gold standard", so to speak
  - we also want to be able to track when breaking changes happen to our upstreams (`nixpkgs`, `emacs-overlay`, and `emacs-ci`)

As a solution, I would use [niv](https://github.com/nmattia/niv), then have two separate CI actions:
 - one that regularly performs a `niv update`, ideally this is never done by hand
 - one that performs the currently existing CI tasks

One thing of note is that I'm not sure if GitHub Actions performs its actions in a "post-merge" state or actually on the PR branch (or if this is a choice to be made somewhere, I'm much less familiar with GH Actions than I am Nix), so I'll have to dig into that to write up the PR, since it's important PRs be evaluated on the same version of the pins that `master` is on.

**Comment by tarsius** [comment]
> This brings two goals into conflict:

As far as I can tell the breakage has nothing to do with the software we care about, so I would say my main goal is to not be affected by bugs in how software is packaged in nix. 

Thanks for explaining what you intend to do but I am afraid I understand to little about any of this to provide useful feedback at this point. Please do what you think is best.

**Comment by tarsius** [comment]
> Sorry for the delay, I'll give a look to proposing a PR soon.

Np. And thanks!

**Comment by tarsius** [comment]
We aren't using Nix anymore.

**Comment by akirak** [comment]
FYI: I managed to make the tests run on CI. https://github.com/akirak/magit/actions/runs/1490491954

It depends on an unmerged change to nix-emacs-ci (https://github.com/purcell/nix-emacs-ci/pull/53) to support Nix flakes, so it currently depends on my fork. I think I can adapt it to classic (non-flake) Nix if necessary.

**Comment by tarsius** [comment]
Thanks but I will stick with what we have for now. Once we start actually using libgit, I will revisit this though.
