### ISSUE TITLE
Default key binding for magit-toggle-buffer-lock

### ISSUE THREAD

**Issue by sergefdrv** [magit/magit#4510]
I find myself using `magit-toggle-buffer-lock` quite often and think it would be nice to introduce a default key binding for it.

**Comment by MatthewFluet** [comment]
I also use `magit-toggle-buffer-lock` frequently and have added it and `magit-toggle-margin` to my config via:
```
  (define-key magit-mode-map "@" 'magit-toggle-buffer-lock)
  (transient-append-suffix 'magit-dispatch "!"
    '("@" "Toggle buffer lock" magit-toggle-buffer-lock))
  (define-key magit-mode-map "#" 'magit-toggle-margin)
  (transient-append-suffix 'magit-dispatch "@"
    '("#" "Toggle margin" magit-toggle-margin))
```
No real mnemonic for `@`, just it is next to `!` which would have been my first choice for a "lock" operation where it not already bound to `magit-run`.

I'm neutral on whether or not to add a default key binding.

**Comment by sergefdrv** [comment]
@MatthewFluet Thanks for the snippet. I wonder if there is a nicer way to do that with `use-package`.

**Comment by sergefdrv** [comment]
Ended up with the following in my `.emacs`:
```elisp

(use-package magit
  :bind (("C-x g" . magit-status)
         :map magit-mode-map
         ("@" . magit-toggle-buffer-lock))
  :custom (global-magit-file-mode t)
  :init
  (transient-append-suffix 'magit-dispatch "!"
    '("@" "Toggle buffer lock" magit-toggle-buffer-lock)))
```

**Comment by MatthewFluet** [comment]
@sergefdrv Yes, my snippet is under the `:config` key of my `(use-package magit ...)`.  Moving portions of it to `:bind` would be possible, but I worry about the keys getting out of sync if they aren't near each other; I've got about 75 lines in my `(use-package magit ...)`.  I think it is slightly more efficient to put the code under `:config` than `:init`, since the former only runs when `magit` is actually loaded, while the latter is always run on emacs initialization.

**Comment by sergefdrv** [comment]
> I think it is slightly more efficient to put the code under `:config` than `:init`

:+1:

**Comment by tarsius** [comment]
The command is available from the log and diff "change arguments" prefixes, so `L b` or `D b`, in the respective buffers.

**Comment by sergefdrv** [comment]
Ah, sorry, somehow I missed it
