### ISSUE TITLE
magit-auto-revert-mode hangs when updating packages

### ISSUE THREAD

**Issue by tvraman** [magit/magit#4512]
title: magit-auto-revert-mode jank when updating packages 
name: Bug report
about: Jank when Updating Packages 
Description: When packages are updated via package.el, (whether or not
that list includes a magit update)
Emacs hangs for a while while displaying this message:
    Turning on magit-auto-revert-mode...done
    Is there any way this could be avoided?

**Comment by tarsius** [comment]
Once this global minor-mode is enabled every file-visiting buffer has to be checked, which takes time and cannot be avoided.

This happens when magit is loaded. So I suspect that some of the hanging is not actually due to that mode being activated but is due to magit and possibly some other stuff being loaded.

I don't know why for you that happens when packages are updated. If it didn't happen at that time, then it would happen at some other time, but no later than when you actually first use magit in an emacs session, obviously.

So one possible way to "avoid this" would be to explicitly require magit in your init file, making startup time slower but at least later there would be no hang.

`magit-auto-revert-mode` is an alternative to `global-auto-revert-mode`, which limits itself to files that are being tracked in a git repository. If, like me, you feel like it makes sense to auto-revert all file-visiting buffers, then you can turn on `global-auto-revert-mode` some time before loading magit and then loading magit won't turn on `magit-auto-revert-mode` anymore, as doing so would be redundant.
