### ISSUE TITLE
On branch deletion, support checking out merge head

### ISSUE THREAD

**Issue by jinnovation** [magit/magit#4549]
Apologies in advance if this is in fact already supported.

To my understanding (based on [somewhat cursory glances at Magit codebase](https://github.com/magit/magit/blob/master/lisp/magit-branch.el#L631-L633)), Magit currently supports the following two actions on branch deletion:
1. Check out detached HEAD;
2. Check out the main branch.

(Of course, there is also "abort," but that's beside the point here.)

However, I—and, presumably, many other full-time developers—often find ourselves working on long-lived feature branches; accordingly, branches oftentimes treat **these** feature branches as the merge head, rather than `main`. In such cases, when I'm done working on such a branch and delete it, I'd instead like to be able to immediately check out the feature branch in question, rather than `main`. Currently, this is not possible; I have to first check out `main` (through the interactive branch-deletion flow), and then check out `feature`.

As such, I'd like to request a third non-abort action for branch deletion, for the following complete set:
1. Check out detached HEAD;
2. Check out the merge target branch;
3. Check out the main branch.

@tarsius: Let me know your thoughts around this. Thanks.

**Comment by tarsius** [comment]
For context see the comment at the beginning of `magit-branch-delete`:

```
  ;; One would expect this to be a command as simple as, for example,
  ;; `magit-branch-rename'; but it turns out everyone wants to squeeze
  ;; a bit of extra functionality into this one, including myself.
```

The "offer to checkout another branch before deleting the current branch" special case is such a feature someone wanted to have squeezed in. I probably had reservations when that was proposed but added it anyway because sometimes it is less work to just add a feature than to resist it. If I remember correctly it originally only offered to detach head.

But such features have a cost. In this case one of those costs is that you and others run into it by accident and then end up assuming this how they are supposed to do it. I occasionally end up at this prompt myself, but I consider that a user error and would be fully satisfied with getting an error "the current branch cannot be deleted".

I don't fully understand your description of what you are trying to accomplish, but assume that you want to merge the current branch into its upstream and then delete the first branch. You can do that with `m i`, which merges the current branch into another branch, offering the upstream as the default choice. You can also merge another branch into the current branch into the current branch using `m a`. In both cases the merged branch is deleted and the branch into which it was merged is the current branch afterwards.

To just delete the current branch without merging it, checkout some other branch using `b b` and then delete the formerly current branch using `b k`.

**Comment by tarsius** [comment]
But please also try the `checkout-delete` branch.

**Comment by tarsius** [comment]
Merged it.

**Comment by jinnovation** [comment]
Thanks for the detailed response, and apologies for my delay.

> In this case one of those costs is that you and others run into it by accident and then end up assuming this how they are supposed to do it. I occasionally end up at this prompt myself, but I consider that a user error and would be fully satisfied with getting an error "the current branch cannot be deleted".

Fair; I appreciate the flexibility regardless.

> I don't fully understand your description of what you are trying to accomplish, but assume that you want to merge the current branch into its upstream and then delete the first branch.

This is generally correct, though I'll complicate things by pointing out that oftentimes the merge of the current branch into its upstream takes place remotely, e.g. in GitHub via the typical pull request flow. In this case, `magit-merge-into` (`m i`) would circumvent the typical pull-request code-review process and make my coworkers huffy :P 

> But please also try the `checkout-delete` branch.

Thanks for this. I appreciate the willingness to accommodate flexibility that you don't otherwise super agree with.

**Comment by tarsius** [comment]
You're welcome. I actually concluded it was an improvement! :smiley:
