### ISSUE TITLE
Use 'error' face instead of 'font-lock-warning-face' in magit-status.el

### ISSUE THREAD

**Issue by protesilaos** [magit/magit#4550]
Hello!

In magit-status.el the `font-lock-warning-face` is hardcoded for various types of error messages, such as "BRANCH does not exist on REMOTE" in `magit-insert-upstream-branch-header`.

By default, `font-lock-warning-face` inherits from the `error` face, however there is a slight semantic difference between the two: the former is used to highlight keywords such as `user-error` in Elisp buffers, which are technically not "errors", while the `error` face is intended for legitimate errors.  Put differently, a user/theme may add a bold weight to the `error` face but not do that for `font-lock-warning-face` (they may also use different styles altogether).

So how about applying the `error` face directly?  Or an altogether new face that inherits from `font-lock-warning-face`, thus making it backward-compatible while still giving users/themes the chance to style things consistently?

**Comment by tarsius** [comment]
`magit-insert-error-header` should use `error`.

In the other cases I consider `font-lock-warning-face` to be more appropriate.

You mention `magit-insert-upstream-branch-header` but let's consider `magit-insert-push-branch-header` first. If `remote.pushDefault` is set, then creating a new branch always results in a warning about that not having been pushed yet. There's nothing wrong with that, maybe this is just an experiment or maybe the user doesn't want to push until the changes on the branch are somewhat usable. The warning face is used as a friendly reminder that the branch hasn't been pushed yet, just in case the user actually intended to push but forgot to do so.

If the upstream branch is missing, then that could be due to an error. I.e. the user might have deleted the configured upstream branch. But depending on the workflow, one might end up with a configured but not *yet* fetched upstream. Maybe the error case is more common but even then the error is that the upstream was deleted not that the current branch uses that deleted branch as the upstream, the latter is more of a misconfiguration.

**Comment by protesilaos** [comment]
> `magit-insert-error-header` should use `error`.
> 
> In the other cases I consider `font-lock-warning-face` to be more appropriate.
>
> [...]
>
> Maybe it would make sense to use dedicated face anyway (`magit-status-branch-warning`?).

I am fine with whatever mapping you think makes more sense.  A dedicate face (or more than one for warnings VS errors) should suffice.  The naming scheme of `magit-status-branch-warning` seems appropriate.

> With the theme I am using for example even the warning face is bold red bam in your face, and I find that a bit annoying.

I believe you are using [Solarized](https://github.com/bbatsov/solarized-emacs)?  Its `warning` and `error` faces do not have a bold weight, so any new faces could inherit from those.

> Or maybe I should just change the theme, after all I have already forked that for other reasons.

Personally, I think `font-lock-warning-face` should use a bold weight optionally because it styles things like `user-error` and the autoload cookies which shouldn't really call too much attention to themselves.

**Comment by tarsius** [comment]
> The naming scheme of `magit-status-branch-warning` seems appropriate.

I dropped the `status-`.

> I believe you are using [Solarized](https://github.com/bbatsov/solarized-emacs)? Its `warning` and `error` faces do not have a bold weight, so any new faces could inherit from those.

At the time I was forced to fork it still did. But I fixed that in my fork now. https://github.com/tarsiiformes/solarized-theme

> Personally, I think `font-lock-warning-face` should use a bold weight optionally because it styles things like `user-error` and the autoload cookies which shouldn't really call too much attention to themselves.

With regards to the cookies I would go even further: https://github.com/tarsius/dim-autoload.

**Comment by protesilaos** [comment]
> I dropped the `status-`.

Thank you!  Will adapt my setup accordingly.

> At the time I was forced to fork it still did. But I fixed that in my fork now. https://github.com/tarsiiformes/solarized-theme

It is better that way.

> With regards to the cookies I would go even further: https://github.com/tarsius/dim-autoload.

Okay.  Then you know how I feel.

**Comment by tarsius** [comment]
> Add support for new magit-branch-warning face

Right... you mentioned `warning` before, but I ended up ignoring that until now. I just changed `magit-branch-warning` to inherit from that instead of from `font-lock-warning-face`.

**Comment by protesilaos** [comment]
All good.  Thanks!
