### ISSUE TITLE
Add support for `rebase --ignore-date`

### ISSUE THREAD

**Issue by gondalez** [magit/magit#4580]
Hi,

I quite often reorder commits during an interactive rebase.
Often I also want to reset the dates in the process so that they show up in order in pull requests on github.

I usually do this manually at the cli with `git rebase origin/something --ignore-date`.

I see that `--committer-date-is-author-date` is already supported, but that does not do what I want most times. 

It would make life easier if `--ignore-date` was also supported.

<img width="681" alt="CleanShot 2022-01-14 at 15 56 18@2x" src="https://user-images.githubusercontent.com/1468141/149471724-5c004897-4ccf-43be-9d9d-0b78cb3e778d.png">

Thank you for your work on magit 🙏

**Comment by kyleam** [comment]
I'd be in favor of adding it (and I've done so in my private config for a long time).

The main arguments against it that I can think of are

 * It's obscure and not frequently used

   This may be true.  I added `--ignore-date` to `magit-rebase-popup` in 2016 and I don't recall a person asking for it until now.

   However, following the move from magit-popup to transient (which supports hiding options), the approach has been to add most arguments and just hide the obscure ones.

 * For older Git versions that Magit still supports, only the `am` backend, not the merge/interactive one, accept `--ignore-date`

   But the same is true for `--committer-date-is-author-date`, so I don't think that's a compelling reason not to add it.

Just a note: while the synonym `--reset-author-date` is more clearly named, it's not supported until Git v2.25.0.

---

> Often I also want to reset the dates in the process so that they show up in order in pull requests on github.
> [...]
> I usually do this manually at the cli with git rebase origin/something --ignore-date.

Some ways to stay in Magit, regardless of the fate of this request:

  * While [not its original purpose](https://github.com/magit/magit/issues/4101#issuecomment-622412374), you could also use `magit-reshelve-since` to make the author dates sequential.  (It's bound to `t` in the rebase transient but hidden by default.)

  * You can extend the rebase transient yourself
    ```elisp
    (transient-append-suffix 'magit-rebase "-d"
      '("-D" "Ignore date" "--ignore-date"))
    ```

**Comment by tarsius** [comment]
I assume this argument didn't exist when I implemented the reshelve command (initially called "rockstar" or something). Probably would have used this argument otherwise.

I could reimplement this command using this argument but that would loose the ability to backdate commits, so let's keep the current command as-is. Since I started signing all my commits, backdating commits doesn't work so well anymore. Author and committer dates are changed but the date of the signature is not. So now that I am aware of it I am probably going to use something involving that argument.

So the question becomes whether we should just add the argument or implement a dedicated rebase variant, basically a less potent variant of the reshelve command. I have gotten used to using that command and don't mind having to rebase multiple times, once to reorder and then to change the dates. I actually prefer doing multiple rebase rounds (even multiple reordering rounds, to make it easier to reason about conflicts).

Gonna have to let it marinate a bit but am leaning towards adding a new command.

**Comment by tarsius** [comment]
I went with simply adding the argument. Using that (most often `r - a u`) actually takes viewer key strokes than using a dedicated command (in the best case `r t C-c C-c` but usually also involves some `n`).

**Comment by tarsius** [comment]
7f03f572d55400899d1e48cfc115e3baf5639021

**Comment by kyleam** [comment]
> I assume this argument didn't exist when I implemented the reshelve command

For the `am` backend, `git rebase` has accepted `--ignore-date` since 2009.

> Probably would have used this argument otherwise.

Interesting, I just assumed you wanted the specify date and tick-per-commit aspect of that command.

In any case, thanks for adding the argument.  

I'm guessing that you recall that `--ignore-date` is in the `magit-am` and bound to `D`, but decided that `c` was still the better choice for the key (perhaps because it doesn't involve shift or is more aligned with the description).  However, I thought I'd mention it in case you forgot and the desire for consistency changes your choice :)

**Comment by tarsius** [comment]
> Interesting, I just assumed you wanted the "specify date" and "tick per commit" aspects of that command.

That's probably right. Whether I knew about `--ignore-date` back then, we will never know. :zany_face: In any case, I think I am ready for using just `--ignore-date` now. Probably. We'll see.


> I'm guessing that you recall that `--ignore-date` is in the `magit-am` and bound to `D`, but decided that `c` was still the better choice for the key (perhaps because it doesn't involve shift or is more aligned with the description).  However, I thought I'd mention it in case you forgot and the desire for consistency changes your choice :)

Uhm, I didn't check whether it was already in use elsewhere. The descriptions are also not the same. But you are right about why I chose `c` this time around.

What do you think; which description and key should we use? They should probably be consistent.

**Comment by kyleam** [comment]
> What do you think; which description and key should we use? They should probably be consistent.

 * I think the description for the new rebase option is clearer, and it works for the `git am` transient as well.
 * `-c` seems better than `-D` in isolation, but I prefer `-D` to match the `am` transient.

So my vote would be

```diff
diff --git a/lisp/magit-sequence.el b/lisp/magit-sequence.el
index 434c0ffd..9b578a7f 100644
--- a/lisp/magit-sequence.el
+++ b/lisp/magit-sequence.el
@@ -426,7 +426,7 @@ (transient-define-prefix magit-am ()
    ("-k" "Inhibit removal of email cruft"    ("-k" "--keep"))
    ("-b" "Limit removal of email cruft"      "--keep-non-patch")
    ("-d" "Use author date as committer date" "--committer-date-is-author-date")
-   ("-D" "Use committer date as author date" "--ignore-date")
+   ("-D" "Use current time as author date"   "--ignore-date")
    ("-s" "Add Signed-off-by lines"           ("-s" "--signoff"))
    (5 magit:--gpg-sign)]
   ["Apply"
@@ -522,8 +522,8 @@ (transient-define-prefix magit-rebase ()
    (7 magit-merge:--strategy)
    (7 magit-merge:--strategy-option)
    (7 "=X" magit-diff:--diff-algorithm :argument "-Xdiff-algorithm=")
-   ("-c" "Use current time as author date"   "--ignore-date")
    ("-d" "Use author date as committer date" "--committer-date-is-author-date")
+   ("-D" "Use current time as author date"   "--ignore-date")
    ("-a" "Autosquash"               "--autosquash")
    ("-A" "Autostash"                "--autostash")
    ("-i" "Interactive"              ("-i" "--interactive"))
```

**Comment by tarsius** [comment]
What about `-t`? 

Or claim `-d` and move `--committer-date-is-author-date` to `-D`? That argument seems less useful.

**Comment by kyleam** [comment]
My starting point was avoiding any changes to existing keys, which locks the keys into `-d`/`-D` with `--ignore-date` on `-D`.  But, lifting that constraint ...

> What about `-t`?

... this sounds fine.

> Or claim `-d` and move `--committer-date-is-author-date` to `-D`? That argument seems less useful.

And I personally don't use `--c-d-i-a-d` (and in my personal config actually already rebind `--ignore-date` to `d`), so from that standpoint this also sounds fine.  But I imagine anyone that does use `--c-d-i-a-d` regularly enough to not need to peek at the transient will be unpleasantly surprised at having that swapped.

---

My take is that 1) consistency between the two transients would be good and 2) if `--ignore-date` is obscure enough that it took someone this long to ask for it, it's probably fine having it on `-D` and it doesn't seem worth breaking the keys for anyone that uses `--c-d-i-a-d` in either the rebase or am transient.

But it very well may be few people (perhaps even 0) that use `--c-d-i-a-d` regularly enough.  I'm of course okay with however you choose to weigh things.  Fwiw, of the options above that rewire existing keys, I slightly prefer the `-d = --ignore-date, -D = --c-d-i-a-d` route (not sure why, perhaps wanting to keep `-t` for the next great thing :]).

**Comment by tarsius** [comment]
I would prefer `-d` too, but to be safe I decided on `-t`.

**Comment by gondalez** [comment]
Thank you both for the informative responses and careful consideration on this. 
I have downloaded the latest release and can see the new option. Perfect! 😌

**Comment by tarsius** [comment]
> Probably would have used this argument otherwise.

>> Interesting, I just assumed you wanted the "specify date" and "tick per commit" aspects of that command.

Well, if you sign your commits and put the secret key material on a smartcard, then you get that with `--ignore-date` too. :grin:
