### ISSUE TITLE
add file path(s) argument to magit-stash

### ISSUE THREAD

**Issue by ericprud** [magit/magit#4583]
`magit-stash` menu includes arguments for a couple flags. If it also inluded a -f flag for file paths, that could be passed at the end of a stash a la:
``` shell
git stash push -m "my stash title" my/file1 my/file2
```
According to [SO](https://stackoverflow.com/a/5506483/1243605), this feature has been in git since 2.13. I have no idea how/if magit auto-adjusts menus to reflect features in old git versions.

**Comment by tarsius** [comment]
This is harder to do than one might expect because Magit has its own stash creation code, which doesn't use `git stash`.

Our implementation works a bit differently from `git stash`. If you want to stash only certain files, then you stage those and then invoke the "only staged files/changes" stash variant (or alternatively only the other files using the "only unstaged files/changes" variant).

Basically in Magit selective stashing works the same as selective committing: You select the files/hunks you want to commit/stash upfront and then you invoke "and now commit/stash what I have previously selected". This allows more granularity and is the reason why I decided to re-implement staging in Magit on top of low-level commands instead of `git stash`.

**Comment by ericprud** [comment]
Empirically, it seems that the "select" area is the working set, and there's only one of those. I can think of two work-arounds:

1. File stash is a separate porcelain for `magit-git-topdir`; seems kinda hacky and would inevitably lead to incompatibilities/inconsistencies.

2. Simulate a working set by keeping a separate list of diffs to be fed to a `git stash -p`-like function.

2 seems like a lot of work but as long as you limit it to the functionality of `stash -p`, it wouldn't need to persist state; it could be an interface that's initiated by a stash menu choice, selects stuff, and executes (or aborts).

Or, I can type `!!`

**Comment by tarsius** [comment]
I think its easiest if I just implement a new command that uses `git stash push` and accepts most of its arguments. (No plan to support `-p` though.) Actually I am mostly done with that but got stuck on a side-quest.

In related news, Git [finally](https://github.blog/2022-01-24-highlights-from-git-2-35/) gained `git stash push --staged`.

**Comment by tarsius** [comment]
I've add `magit-stash-push`. It's available from `magit-stash` but has to be enabled.

You also need to update `transient` *before* `magit`. If you get an error when invoking `magit-stash-push`, then reinstall `magit`.

**Comment by tarsius** [comment]
Certain transient popups hide some of their suffix commands by default. These additional suffixes can be [enabled interactively](https://magit.vc/manual/transient/Enabling-and-Disabling-Suffixes.html). TL;DR Enter the transient as usual and type <kbd>C-x l</kbd>.

<sub>This is a [canned response](https://help.github.com/en/github/writing-on-github/working-with-saved-replies); it may not apply 100% in this case.</sub>
