### ISSUE TITLE
magit-save-repository-buffers queries to save ignored files

### ISSUE THREAD

**Issue by aurajamming** [magit/magit#4610]
**To reproduce:**
Create a blank repository
Create a subdirectory called "ignored"
Create a file called "ignored/ignored.txt"
Create .gitignore and add "ignored/" to it
Open the magit status buffer (and refresh)
Open ignored/ignored.txt and make some change - without saving the buffer
Refresh the magit status buffer.

**What I expected:** Since the ignored.txt file is matched by a rule in .gitignore, it isn't needed for checking git status and I shouldn't be asked if I want to save it.

**What actually happens:** I'm prompted to save each and every file under my repository root even if ignored.

**Config data:**

Magit 20220203.2302 [>= 3.3.0-git], Git 2.21.0, Emacs 28.0.91, gnu/linux

My magit-save-repository-buffers is set to t

I realize setting this to nil would get rid of these prompts, but I do want to prompted for relevant changed buffers.

**Comment by aurajamming** [comment]
Ok, that makes sense. I'll keep this in a personal patch. 

(Irrelevant if you're not interested, but: It's surprisingly fast, actually - I usually have 400 to 800 files open, with one to two dozen modified files for my main project repo, and I can't notice any new lag. )

**Comment by tarsius** [comment]
Thanks for understanding.

> I usually have 400 to 800 files open, with one to two dozen modified files for my main project repo, and I can't notice any new lag.

The number of buffers is probably more relevant here, or not. In the past we had to optimize these checks numerous times, changing things that we originally felt should not make any difference because of very different usage patterns we did not anticipate. "I keep Emacs running for years and never close buffers" (okay maybe I am exaggerating a bit) was one of the usage patterns that caused major slowdowns. :wink:
