### ISSUE TITLE
Recent git version assert changes break byte compilation of packages depending on magit

### ISSUE THREAD

**Issue by sternenseemann** [magit/magit#4614]
After updating magit from f0296148a64f8058f920e3ae90c418087c966344 to 44c58868c997f0b86d66faeed2f0b29064f8d0b9 the byte compilation of a custom package with Emacs 28.0.91 started failing:

```
In toplevel form:
--


tvl.el:18:1:Error: Searching for program: No such file or directory, git
```

The location info pointed to a line that was simply `(require 'magit)`. Further investigation (thus build ran on CI in a headless emacs and I'm not sure if I can coerce it to print a full backtrace to stdout, I simply approximated what would happen on CI manually) showed that it hit the git version assert magit does at load time now — and I don't think we can avoid loading magit when byte compiling a package that depends on it. In this regard [the workaround for building magit without git installed](https://github.com/magit/magit/commit/6c4ff54a0836985fac6d72c7e4bfeff964775efe) is only of limited usefulness, as it still trips up reverse dependencies.

Other relevant commits seem to be 6c4ff54a0836985fac6d72c7e4bfeff964775efe and 8394f0d4ea5ffa6858db314efabe91d99f78e67a.

**Comment by tarsius** [comment]
I couldn't find a package named `tvl`. Please provide a link to it.

**Comment by tarsius** [comment]
It is important that we check that git is available and recent enough as soon as magit is loaded. We could delay those tests until `magit-status` is used, but users might use other commands first and we got confusing bug reports due to that in the past.

I am sticking to what we have for now. Maybe if there are other reports like this one, then I might have to change course.
