### ISSUE TITLE
`compat-28.1.0.4` was gone

### ISSUE THREAD

**Issue by condy0919** [magit/magit#4673]
Several files, e.g., `git-commit.el`, `magit.el`, and `magit-section.el` still depend on `compat-28.1.0.4`. Unfortunately the version was gone, See https://elpa.gnu.org/packages/compat.html

**Comment by tarsius** [comment]
Magit should indeed have depended on at least 28.1.1.0 from the start. I have bumped the dependency.

But I don't understand why it is relevant that 28.1.0.4 isn't available anymore. `package.el` will just install the latest available version, which currently is 28.1.1.0. (If it doesn't for you, then that's because you need to `M-x package-refresh-contents`.)

**Comment by condy0919** [comment]
`Cask` checks the version, `package.el` works well.

**Comment by tarsius** [comment]
I see. Well, the numbers have been bumped now.
