### ISSUE TITLE
Local checkout of remote branch with lfs fails to prompt for password

### ISSUE THREAD

**Issue by jefftrull** [magit/magit#4759]
### Expected behavior
`b l upstream/branch-name` creates local version of upstream branch and checks out the head

### Observed behavior
Command fails with `my/long/path/name: smudge filter lfs failed ... [Hit $ to see buffer magit-process: eve2 for details]`

The process buffer shows:

```
128 git … checkout -b branch-name upstream/branch-name
fatal: could not read Password for 'https://my-user-name@bitbucket.org': No such device or address`
Errors logged to /home/me/my-repo/.git/lfs/logs/20220916T120359.993299749.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
```

### How to reproduce
I assume it would be necessary to have a repo that uses LFS, and then do the above?

### Backtrace
There is none, because the error is handled.

### Version
20220914.2356 (although I've been seeing this for some time).

**Comment by jefftrull** [comment]
When run from the command line, the `git checkout -b` command prompts for a password and completes successfully.

**Comment by tarsius** [comment]
My guess is that the external filter used by `git-lfs filter-process` cannot be found in `exec-path`.

> Use `git lfs logs last` to view the log.

Anything useful there?

**Comment by jefftrull** [comment]
It looks like this:

```
git-lfs/3.0.2 (GitHub; linux amd64; go 1.17)
git version 2.34.1

$ git-lfs filter-process
Error downloading object: my_filename (e2cd1c6): Smudge error: Error downloading my_filename (my_uuid): batch response: Git credentials for https://me@bitbucket.org/org/repo.git not found.

Git credentials for https://me@bitbucket.org/org/repo.git not found.
```

**Comment by tarsius** [comment]
I don't see `git-lfs filter-process` prompting the user for any credentials. This looks to me like it thinks that it is being run non-interactively and therefore decides that it cannot prompt the user for input. So it just gives up.

Two way of addressing that would be to either make the credentials available to it without it having to ask the user for them every time, or alternatively to somehow teach it that it can in fact ask the user for credentials.

In any case, I don't think this is an issue in magit, and I am therefore closing this issue. If it turns out that magit *is* to blame for this, at least in part, then we can of course reopen. I don't have the bandwidth to deal with such reports, which aren't about an issue in magit per-se.
