### ISSUE TITLE
Checkout of remote branch fails to prompt for password

### ISSUE THREAD

**Issue by jefftrull** [magit/magit#4781]
This is a continuation of #4759 with additional debugging; please see that bug for checklist items.

I delved into the code a bit and think this is likely a magit issue having to do with the difference between regular and **async** forms of launching git.

When debugging I noticed that `git fetch origin` successfully prompts for a password, while `git checkout -b branch-name upstream/branch-name` fails to do so. I traced the calls and found that `fetch` uses `magit-git-run-async`, while the checkout (run from `magit-branch`) code uses the synchronous `magit-call-git`. I then verified that:

```
(magit-run-git "checkout" "-b" "branch-name" "upstream/branch-name")
```
fails with the reported error (no password prompt, failed checkout), while
```
(magit-run-git-async "checkout" "-b" "branch-name" "upstream/branch-name")
```
prompts for the password in the minibuffer as expected.

As a result I suspect that the branch code never envisioned that a password prompt would be required, and the synchronous API would be sufficient. It is likely that the presence of LFS in this repo is what makes the password necessary.

Can `magit-branch` be changed to use the async API - at least for remote branch checkouts? Thanks.

**Comment by tarsius** [comment]
Your absolutely right.

I'll have to think about whether to make this and similar command asynchronous, but most likely will. It is a bit more work than just dropping the `-async` in there because in some cases additional work has to happen after the checkout has completed.

Can you use another command until that has happened, or does `git-lfs` absolutely have to do the fetching of lfs data on *checkout*, i.e., can it not be done later or earlier, while git itself fetches?

**Comment by jefftrull** [comment]
I can just use the command line :) I don't know why it does that work on checkout. Thanks!

**Comment by tarsius** [comment]
Every improvement breaks someone else's workflow, here #4945. :(
