### ISSUE TITLE
Merge preview shows conflicts partially skipped/hidden

### ISSUE THREAD

**Issue by dadinn** [magit/magit#4799]
Looking at merge preview between 2 commits, when there are conflicts, longer segments are collapsed and not visible. This makes it hard to decipher what's changes were made, and what caused the conflicts.

In the below screenshot it can be seen how the first conflict (a shorter code segment) is clearly visible, while the second one is partially skipped/hidden:
![image](https://user-images.githubusercontent.com/521910/197355395-07299d5d-962a-44f7-aa38-bb8d7f78bf6b.png)

Pressing `+` doesn't expand the visibility of to uncover the hidden regions.

Also, selecting one of the conflict segments, and pressing Enter on it, does not jump to the commit where the side of the conflict is from, instead it always jumps to the content of the currently checked out commit.

This makes it impossible to investigate these conflicts.

I personally use the Merge Preview feature very often to understand how changes evolved between different branches, which I find crucial when reorganizing/merging feature branches.

Magit version: `Magit v3.3.0, Git 2.30.2, Emacs 27.1, gnu/linux`
Magit commit: `f44f6c14500476d918e9c01de8449edb20af4113`

**Comment by kyleam** [comment]
Note that this is closely tied to the recently opened gh-4887.  As I mentioned there, the merge-tree mode we use is deprecated as of Git 2.38.  We should be able to rewrite things to use the new mode, which performs an actual merge (without touching the working tree or index) and gives back a tree ID.

I can see that helping the case reported here in two ways: 1) the context of the diff could then because increased, because it's a diff Magit would generate with regular diff commands and 2) we'd have the tree ID, so we should be able to wire things up so that the blob that has the conflict markers can be visited.

**Comment by kyleam** [comment]
> How about both? ;)

I'm not sure what "both" is referring to.  The (single) proposal is to use the new mode; the 1 and 2 above are just explaining how doing so would allow `-U` to work and make it possible to visit a blob with markers.

> 1) increasing the diff context to a fixed value sounds arbitrary.

That wasn't what I was suggesting.  I just meant that `+/-` would then work (because a diff command would be generating it, and that would respect `-U`, which those commands rely on).

**Comment by tarsius** [comment]
I intend to keep the existing merge-preview feature as-is. In #4887 I explain why I think that a new implementation based on `git merge-tree`'s new mode would still be inferior to just initiating and later aborting a real merge. (While @kyleam explained why the implementation based on the old mode of `git merge-tree` cannot be improved to address the issue brought up here.
