### ISSUE TITLE
`magit` puts "deleted by" files into the staged section

### ISSUE THREAD

**Issue by x-yuri** [magit/magit#4804]
A script to create a repository with a conflict:

```sh
mkdir a
cd a
git init
echo a > a && git add a && git commit -m a
echo b > b && git add b && git commit -m b
echo c > c && git add c && git commit -m c
git rm b && echo a2 > a && git add a && git commit -m x
GIT_SEQUENCE_EDITOR="sed -ri '2s/pick/e/'" git rebase -i --root
git mv b b2 && echo a1 > a && git add a && EDITOR=: git commit --amend
git rebase --continue
```

And the way it looks in `magit`:

![][a]

When I resolve the conflict in `a` and try to continue:

![][b]

With more files it can be more tricky to figure out what's going on.

By the way, `k c` doesn't work with this kind of conflicts (a bug?):

![][f]

Not to mention that it's [tricky][h] to figure out what `[c]onflict` means.

<details>
  <summary>**On a side note**</summary>

  If I change the text between the conflict markers:
  ![][c]
  ![][d]
  I'd say the way it's shown in the status buffer is incorrect:
  ![][e]
  Do you consider this a bug? Need a bug report?
</details>

Magit version: `Magit 3.3.0, Git 2.37.3, Emacs 28.2, gnu/linux`.

[a]: https://i.imgur.com/hQBc1zb.png
[b]: https://i.imgur.com/1zJDHas.png
[c]: https://i.imgur.com/UkV4gHo.png
[d]: https://i.imgur.com/zfbntHr.png
[e]: https://i.imgur.com/KqPJ6ag.png
[f]: https://i.imgur.com/MsLCiXt.png
[h]: https://www.reddit.com/r/emacs/comments/yd6li0/what_does_the_conflict_option_means_when/

**Comment by tarsius** [comment]
> magit puts "deleted by" files into the staged section

That's just what Git does. I don't think it is a problem.

> By the way, `k c` doesn't work with this kind of conflicts (a bug?):

Well, it is difficult for a file to exit and not exist at the same time. But I guess it would be possible to detect this situation and not offer `c` in that case.

> Not to mention that it's [tricky](https://www.reddit.com/r/emacs/comments/yd6li0/what_does_the_conflict_option_means_when/) to figure out what `[c]onflict` means.

I would say it isn't terribly tricky. Could be changed to `restore [c]onflict`, but then the rest of the prompt would have to be reworded too, because grammar.

All in all, yeah, things could be tweaked. I'll leave this open and maybe make some improvements at some point, but I think there are many much more important things to do first.

**Comment by x-yuri** [comment]
I'm not saying that it's anything major, but that's not a reason to say that those are non-issues at all, I think.

> That's just what Git does. I don't think it is a problem.

It probably makes sense to briefly describe the conflict first:

```
them: rm b,    echo a2 > a
us:   mv b b2, echo a1 > a
```

```
$ git ls-files -s
100644 78981922613b2afb6025042ff6bd878ac1994e85 1	a
100644 da0f8ed91a8f2f0f067b3bdf26265d5ca48cf82c 2	a
100644 c1827f07e114c20547dc6a7296588870a4b5b62c 3	a
100644 61780798228d17af2d34fce4cfbdf35556832472 1	b2
100644 61780798228d17af2d34fce4cfbdf35556832472 2	b2
100644 f2ad6c76f0115a6ba5b00456a849810e7ec0af20 0	c

$ git show :1:a
a
$ git show :2:a
a1
$ git show :3:a
a2

$ git show :1:b2
b
$ git show :2:b2
b

$ git status
...
Unmerged paths:
  (use "git restore --staged <file>..." to unstage)
  (use "git add/rm <file>..." as appropriate to mark resolution)
	both modified:   a
	deleted by them: b2
...
```

At this point in `magit` `a` in both sections, `b2` in the staged section:

![][a]

`fugitive`:

![][c]

```
$ git checkout --theirs a && git add a
$ git rm b2
$ git status
...
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	modified:   a
	deleted:    b2
```

That is in `git` the files transitioned from "unmerged" to "to be committed." In `magit` we see a similar situation:

![][b]

`fugitive`:

![][d]

What I find confusing is that initially `b2` is in the staged section. And that `a` is in both sections, for that matter. Generally with `git` changes transition from the working directory, to the index, and then to the commit history. Staged changes are a diff between `HEAD` and the index. With a conflict things are more involved. In this case come into being three additional stages of an index (base, us, them), and stage 0 is apparently what generally considered an index. What are staged changes in this case?

> Well, it is difficult for a file to exit and not exist at the same time. But I guess it would be possible to detect this situation and not offer c in that case.

Are you sure the file exists when you're not looking at it? :) Joking aside, what's the point of `[o]urs [t]heirs [c]onflict`? It's a way to choose one of the sides, or reset it to the original state, am I wrong? You might say that `git checkout --merge FILE` also fails with deleted-by files, but do you want to replicate all the `git`'s quirks? In that case you might very well want to rename `[c]onflict` to `[m]erge`.

> I would say it isn't terribly tricky. Could be changed to restore [c]onflict, but then the rest of the prompt would have to be reworded too, because grammar.

Other option is `[r]eset`. Another, is this documented anywhere? Yet another one, add a `?`/`C-h` option (the [way it happens][e] when the status buffer is to be refreshed and there are unsaved files).

[a]: https://i.imgur.com/XrwuyH2.png
[b]: https://i.imgur.com/Ud8bVix.png
[c]: https://i.imgur.com/d6BuGoq.png
[d]: https://i.imgur.com/qLirs8D.png
[e]: https://github.com/emacs-mirror/emacs/blob/emacs-28.0.90/lisp/files.el#L5775-L5899

**Comment by tarsius** [comment]
I have added the a new option `magit-verbose-messages`. If you set that to t, the prompt will contain `restore [c]onflict` instead of just `[c]onflict`. In the future it will make other prompts and messages more verbose as well.

Regarding what files are being listed where: As I mentioned above Magit just does what the underlying Git command is doing. I know I have thought about that before and decided to stick to what they are doing. Unfortunately I did not write down the complete reasoning. I strongly suspect I would come to the same conclusion if I did it again, but it would take time to do it.

The steps and screenshots you provide unfortunately don't help much with that because they use rebase and non-descriptive filenames. So I would have to start with setting up my own conflicts first.

I don't feel like making that investment (again) and because this is not an issue that comes up again and again, I have decided to just leave things as they are and close this.
