### ISSUE TITLE
Graph lines in `magit-log` are misaligned if more chars needed in hash.

### ISSUE THREAD

**Issue by darkfeline** [magit/magit#4819]
Magit version: v3.3.0-518-g0429b16f (fork with trivial diff)

Graph lines in `magit-log` are misaligned if more chars needed in hash.

Can't share repo as it's private

```
376837b29 *   local Merge remote-tracking branch 'origin/master' into local
         |\  
3cd1f496e | * origin/master Freeze
```

I believe this happens when more chars are needed to resolve ambiguity, in long lived repos.

Updates: 

`(magit-abbrev-length)` returns `8` when it should be `9`.  Or rather, something is quirky about how Git calculates abbrev length.

In any case, `magit-log` should have access to the length of the hashes it gets, it's "just" a matter of refactoring the code to peek ahead and grab it before washing all of the output.

**Comment by tarsius** [comment]
Have a look at them implementation of `magit-abbrev-length`. It will almost always get it right--unless you have explicitly set `core.abbrev`.

**Comment by darkfeline** [comment]
I think the assumption that `git rev-parse` and `git log` will use the same length is wrong.  `core.abbrev` is set to `auto`.  In any case, it would be more robust if `magit-log` could check what the abbrev length actually is rather than assuming it will be the same as `git rev-parse`.

**Comment by kyleam** [comment]
> I think the assumption that `git rev-parse` and `git log` will use the same length is wrong.

For a given object ID, `git rev-parse --short` and abbreviation for the log both go through `repo_find_unique_abbrev_r`, as far as I can tell.

But that is not the assumption that `magit-abbrev-length` makes.  It tries to take a good guess at Git's auto-scaled length is by sampling two commits (the particular commits are not important) and taking the minimum.

> `core.abbrev` is set to `auto`.

In my experience, auto tends to give a good amount of padding and make conflicts rare.  If you're regularly seeing abbreviated object IDs that need to be extended, then perhaps some characteristics of the particular repo are making Git's guess fall short.  I'd take that good sign that the repo's core.abbrev should be set to a larger fixed value.

> In any case, it would be more robust if `magit-log` could check what the abbrev length actually is rather than assuming it will be the same as `git rev-parse`, since it appears that git has some special logic for `auto`.

The assumption isn't that Git will never need to extend a commit, leading to misalignment.  It's that it should be rare with Git's auto-scaled default.  `magit-abbrev-length` sampling of two values decreases the chances that it sees two abbreviated commits that needed to be extended beyond Git auto-scaled default.

There's past discussion on this in gh-3034 (and elsewhere).  I don't think the situation has changed since then.

**Comment by darkfeline** [comment]
Why should  `magit-abbrev-length` sample when the output of the log contains the length for that invocation?  That would also save two `git rev-parse` calls (albeit trivial in terms of time savings).

**Comment by kyleam** [comment]
> Why should magit-abbrev-length sample when the output of the log contains the length for that invocation?

The approximate history is "washer code uses hard-coded value" -> "washer code uses core.abbrev value falling back to 7 (before auto existed)" -> "washer code uses core.abbrev or looks at the output of one rev-parse call to guess a value" -> "... looks at the output of two rev-parse calls to guess a value".  That is, unsurprisingly the approach is incrementally refining the existing code.

Someone could rewrite it do an initial scan through all of the log lines and determine the maximum value, making the case that the change doesn't come with a performance hit and that the extra complexity is worth it to avoid cosmetic misalignment.  I personally am not signing up to review that and, as I said in gh-3034, don't think it's worth considering until a large rework like gh-2989.  Perhaps Jonas feels differently.

(If we were to make a change, I'd rather make it a non-issue by following Git and keeping the hash on the right side of the graph.)

**Comment by tarsius** [comment]
> Perhaps Jonas feels differently.

I don't. I very much agree.

The problem here is, that for some reason the alignment is wrong for @darkfeline. We have mentioned the likely cause and how we think it can be addressed. We are still waiting for a response to that. If it turns out that this doesn't work for some reason, then we can investigate further.

> Why should  `magit-abbrev-length` sample when the output of the log contains the length for that invocation?  That would also save two `git rev-parse` calls (albeit trivial in terms of time savings).

1. We need to know the length in other places as well. For simplicity sake we implemented one method of determining that value, this function, and use it everywhere. I do not think it makes sense to add another method in one case, just because we could do so. Performance could be an argument for why we should do it, but you are not making that argument.
2. The functions involved in "washing" log output are already too messy as it is. Let's not complicate them further by needlessly making them take on an additional responsibility.

**Comment by darkfeline** [comment]
I don't think there's much to say.  I don't think there's any disagreement that sometimes, `magit-log` doesn't align properly when `core.abbrev` is set to `auto` (that is, the default that 99.9% of people never touch and probably aren't even aware of).  That's the bug.

It's not high priority, and fixing it may be hard (or not).  If there's no interest in keeping this bug open, I'll copy the bug for my own tracking.
