### ISSUE TITLE
Invalid :extended version 28.1 for function string-lines

### ISSUE THREAD

**Issue by tarsius** [magit/magit#4858]
@minad, we get this error for Emacs 27.2 and older, and I don't understand what it means and what I am supposed to do about it.

```
Compiling git-commit.el
Eager macro-expansion failure: (error "Invalid :extended version 28.1 for function string-lines")
```

**Comment by minad** [comment]
Where do you get this error? This should only happen if `compat-strict` is non-nil during byte compilation. I have this enabled for additional CI checking, but it should never happen for the user.

**Comment by minad** [comment]
Also there is something wrong, since the error should obviously not occur. There is no such error on the Compat CI and there we also test 27.2 and older.

**Comment by tarsius** [comment]
Happens at https://github.com/magit/magit/actions/runs/3992425208, for example.

(Currently CI get dependencies from the Emacsmirror. So for Compat currently https://github.com/emacsmirror/compat/commit/ac471b9ccf821a421f61945c262c53a7a02006cd.)

**Comment by minad** [comment]
I think your CI setup is somehow broken, since the version check performed by Compat here just compares the version specified by `compat-declare-version` with the `:extended` version.

https://github.com/emacs-compat/compat/blob/e262be30f3216a42c41e26cb81d75e4b8c9b331d/compat-macs.el#L100-L102

The `:extended` flag specifies that a function got extended (behavior change, callconv change). If a version is specified for this flag, it is the version at which the function got originally introduced, which is 28.1 for `string-lines`. This version must be smaller than the declared version but larger than 24.4.

**Comment by minad** [comment]
@tarsius I looked again at your CI and many things seem to be wrong there. For example the "Testing using Emacs 26.3" run has many errors during compilation and during testing, which look as if Compat is not loaded or properly setup. Maybe some caching issue? I really have no idea. If you figure something out, please let me know. Maybe there is indeed something wrong on the side of Compat or something could be improved to make it more robust.

**Comment by tarsius** [comment]
> which look as if Compat is not loaded or properly setup.

Dependencies, including Compat, are not being compiled, they are just put on `load-path`. That didn't work for Compat in its early days, but it did work before you started refactoring. Does Compat need to be compiled again before use?

**Comment by tarsius** [comment]
Indeed, now that I have compiled emacs-27.2 locally, I can confirm that I can compile magit if compat has been compiled, but not if it hasn't. In the latter case I get the same :extended version error.

**Comment by minad** [comment]
For a while I had Compat also tested in interpreted form in CI, but I disabled that after a while. I will reenable the interpreter test to see if there are issues.

**Comment by tarsius** [comment]
After adding a special case the compile workflow to first compile Compat, everything is green again. (But that will change on that branch again, while I am investigating other warnings.)

**Comment by minad** [comment]
I have to think about this a little bit more, but it seems that I cannot make Compat work in interpreted form easily. I believe it has never worked before properly in interpreted form. It may have looked as if it worked, because the checks in place were not sufficiently strict.

**Comment by tarsius** [comment]
> I have to think about this a little bit more, but it seems that I cannot make Compat work in interpreted form easily.

It wasn't easy the first time around either, but it is necessary. After same failed attempts, this is what fixed it: https://lists.sr.ht/~pkal/compat-devel/patches/32625. I think, I first brought up the issue in https://lists.sr.ht/~pkal/compat-devel/%3C87mtgr4rjs.fsf%40bernoul.li%3E. Maybe this was also discussed in other threads.

We cannot assume that every user will always ensure that Compat has been compiled before trying to use or compile a package that depends on it.

**Comment by minad** [comment]
I disagree with the assumption that it is okay to use Compat in interpreted form. I almost always consider it a bug if users install a package without compiling it. This will only lead to performance issues and other problems later on. Nevertheless I agree that Compat should work nevertheless, but just out of principle, since we have to get the technical mechanisms right.

**Comment by minad** [comment]
@tarsius Please check if https://github.com/emacs-compat/compat/commit/c110db282978ccd65416d0afc987b4987245a115 fixes the issue. CI checks both interpreted and compiled Compat now.

**Comment by tarsius** [comment]
> Please check if https://github.com/emacs-compat/compat/commit/c110db282978ccd65416d0afc987b4987245a115 fixes the issue.

It does. Thanks!

> CI checks both interpreted and compiled Compat now.

Probably hard to test using CI, but maybe it is also worth that things still work after doing an `M-x eval-buffer` in a `compat*.el` file.

> I almost always consider it a user error if users install a package without compiling it. This will only lead to performance issues and other problems later on.

Not compiling a file (or later doing an `eval-buffer`) is useful to get a more meaningful backtrace when debugging some error.

And what about installing/compiling packages *out of order*, but later using them in their compiled form? Borg had the problem that it compiled all packages in alphabetic order.

[It cannot ensure dependencies are compiled before dependents because it does deal with dependencies at all. Sure it *should* handle dependencies, but then things become much more complicated, quickly. E.g., there are packages with circular dependencies.]

Currently Borg compiles Compat, Org (to avoid harmless but confusing warnings), and Borg (might as well), before compiling all other packages in alphabetic order.

It looks like `package-recompile-all` might also compile packages in alphabetic order.

**Comment by minad** [comment]
> Probably hard to test using CI, but maybe it is also worth that things still work after doing an M-x eval-buffer in a compat*.el file.

Sure. That's a huge advantage of Elisp development. However at this point it will get really brittle for Compat. In Compat it won't work to evaluate individual definitions since the definitions depend on `compat-declare-version` which must be evaluated before. But that is also a general problem. After some point, when many definitions have been evaluated in a live environment like Emacs the overall state will get really unclear and brittle.

> Not compiling a file (or later doing an eval-buffer) is useful to get a more meaningful backtrace when debugging some error.

Yes, the traces get a bit more meaningful. But I also had experiences, where the interpreter made things much worse. For example the interpreter didn't properly implement closures, such that the whole environment was captured. This led to memory leaks and an unbelievably bad debugging experience. Iirc this has been fixed in Emacs master or Emacs 29, such that a proper lexical analysis is performed when creating closures. The problems I had were reinforced by the heavy closure usage in my Consult package.

Furthermore byte compiling code does much more error checking, more warnings and so on. They are adding more and more useful warnings over time and static analysis, such that using interpreted Elisp will get less and less robust as a development environment. Ideally the interpreter should only be used for bootstrapping and eval. You can as well byte compile definitions right away in the scratch buffer for example.

On top of that, interpretation is so much slower that it can get even painful to use it. This depends on the package, but for UI features with some live computation in the background I find the difference very noticeable.

> And what about installing/compiling packages out of order, but later using them in their compiled form? Borg had the problem that it compiled all packages in alphabetic order.
> It looks like package-recompile-all might also compile packages in alphabetic order.

At least Compat comes early in the alphabet. ;)

The bootstrapping argument is certainly an argument that packages must work in interpreted form, which is already a necessity because of macros. But compiling alphabetically still doesn't sound like a great approach to me. 

If you relax the requirements even more then it may be even okay to compile packages with having some outdated dependency loaded, as we observed for Magit and Compat ;) I just believe it would be better if the package manager followed a more strict approach, compiling in topological order, ensuring that no outdated code is loaded, and so on.

But to be clear, what I meant above is that in the end a package should be used in compiled form by the end user - this also applies to Compat. If you consider bootstrapping or installing packages as "using a package", then we are getting into a gray zone.
