### ISSUE TITLE
Bury buffer does not restore treemacs window

### ISSUE THREAD

**Issue by goldfita** [magit/magit#4871]
### Expected Behavior

Bury diff window with 'q' should preserve window layout.

### Observed Behavior

Typing 'q' on diff window resizes treemacs window to fill half the screen when treemacs-width-is-initially-locked is nil.

### Reproduce

I have use-package installed, but everything else is removed from my init except for the treemacs setting that causes the problem.

```emacs
(use-package magit)
(use-package treemacs
  :custom
  (treemacs-width-is-initially-locked nil))
```

1. M-x treemacs
2. M-x magit-log-buffer-file (on version controlled file)
3. Ret (on commit hash)
4. Quit from log buffer
5. Quit from diff buffer

If you do the last two in reverse, it works correctly.

### Version

Magit 20230106.1930 [>= 3.3.0.50-git], Git 2.37.3, Emacs 28.2, windows-nt
[Treemacs] v3.0 (installed 2023.01.07) @ Emacs 28.2

**Comment by tarsius** [comment]
This is customizable. See https://magit.vc/manual/magit/Quitting-Windows.html.

**Comment by goldfita** [comment]
I read through the docs a few more times and still didn't fully understand what the expected behavior is for the different combos, so I just tried them all. Also, in my version, the default is `magit-mode-quit-window`, not `magit-restore-window-configuration` as it says in the docs. If I do 'C-u q' with restore configuration in the log buffer, it kills both buffers without messing up the treemacs window. I could also just as easily kill with good old 'C-x k'.

**Comment by tarsius** [comment]
> Also, in my version, the default is `magit-mode-quit-window`, not `magit-restore-window-configuration` as it says in the docs.

I've corrected that.

> I read through the docs a few more times and still didn't fully understand what the expected behavior is for the different combos, so I just tried them all.

I am afraid understanding it is just the first step. Making it work as you wish across all packages is a whole different story. Personally I am also very dissatisfied with how how Emacs manages windows, but I realize that improving that is very difficult and that it is impossible to do it in a way that would satisfy everyone. (I actually plan to tackle that eventually, in the sense that I want to make it work the way I, and hopefully a few others, want. But again, that is a major undertaking.)

What we are left with, for the time being, is a system that can be bend to more or less work as one wants, given some customization. And of course there's always the odd package that acts up because it wants to do things differently. For you that is Magit, when used in combination with Treemacs. That's not really Magit's fault though. What is different here from other packages that you have encountered is that it creates a new window and that you quit the windows not in the reverse order in which they were created.

The standard command for quitting a window is `quit-window` and if you use that as the value of the variable, then that is basically the same (except for the behavior with a prefix argument). Another alternative could be `bury-buffer`. Try that and if it works as expected, let me know and I will add it to the list of advertised values for the variable.

Magit has to provide some default behavior (whether that means not doing anything itself and just letting the thing happen that happens by default, or tweaking that somehow). But Magit also provides many nobs to tweak things. (E.g., `magit-display-buffer-function`, which controls how buffers are initially displayed, which does also affect what happens when they are ultimately buried and/or their window are "quit".)

I suggest you ask other Treemacs users or its author how they deal with this. They probably have similar expectations to you. I on the other hand do not use Treemacs. Never-the-less, I suspect the problem is that you shouldn't do that:

> when treemacs-width-is-initially-locked is nil.

**Comment by goldfita** [comment]
I'm satisfied with the behavior of 'C-u q' and quit-window. There may be other packages that cause problems, but usually the treemacs window is the only extra window I keep open when doing project work.
