### ISSUE TITLE
Please tag new lrelease to help packaging magit for Debian

### ISSUE THREAD

**Issue by dod38fr** [magit/magit#4872]
Hi

I've seen that Debian's magit package is still at version 3.3.0 that was released in 2021. 

Debian emacs packaging [policy](https://wiki.debian.org/Teams/DebianEmacsenTeam) mentions that:
> Versions should be based on those used by the upstream author, not e.g. MELPA
>    + Though if there is a discrepancy, try to get it resolved with upstream before uploading. 

Debian tools (like uscan) are able to track upstream release as tarball or git tags, but we cannot tracks individual commits.

So, could you please tag your releases ?

This would really help Debian packaging (hence Ubuntu and Mint as well).

All the best

Dod (for Debian)

**Comment by tarsius** [comment]
Yes. Soon.

**Comment by bignose-debian** [comment]
> So, could you please tag your releases?

I see that this issue has been closed, but it was not resolved.

Can you please re-open this issue (since it is not yet resolved), and give an update on how this will be resolved?

Also if you need some assistance, please let us know; we'd like to see proper stable releases with the recent improvements from the past couple of years.

**Comment by tarsius** [comment]
I plan to release in September.

I won't reopen because that encourages others to comment and I would like to avoid that because it makes my anxious and delays releases.
