### ISSUE TITLE
magit-diff-more context and magit-diff-less-context doesn't work in merge-preview mode

### ISSUE THREAD

**Issue by dadinn** [magit/magit#4887]
### problematic behaviour
I start a merge preview with the following steps:
- open git status buffer with `magit-status` command
- open current log from status buffer with `l l` key-chord
- navigate to a commit other than the current checked-out one, and open a merge-preview buffer with the `m p` key-chord

Inside the merge-preview buffer I would expect that the `+` and `-` keys to run the `magit-diff-more-context` and `magit-diff-less-context` commands. Instead nothing happens. When I try to manually run these commands with `M-x`, I get a message which says `You can run the command 'magit-diff-more/less-context' with -/+`, but otherwise nothing happens.

I would assume this is because the commands themselves don't work for some reason in the merge-preview buffer.

Otherwise the `+` and `-` keys work as expected in the status buffer, and in magit-diff buffers when reviewing individual commits.

### expected behaviour
I would expect the `+` and `-` keys to increase/decrease the context in the merge-preview buffers, just like in the normal diff buffers.

### version information

I am using magit version `v3.3.0`, more specifically commit `557ab2c0620930afc0b1da3453c42fa2b5d86145`.

Emacs version: `27.1`.
OS: Debian Bullseye.

**Comment by kyleam** [comment]
The reason that you can't increase the context is that `magit-merge-preview` relies on `git merge-tree` underneath, and merge-tree doesn't accept diff options like `-U` (nor does it consider the `diff.context` option).  So this is a general problem of the diff arguments not applying to `magit-merge-preview`.

For older Git versions, I'd say the best we can do on Magit's end is to make it clearer that merge previews don't support the diff arguments (e.g., by mentioning it in the docs, if it's not already, and making `magit-diff-more-context` and `magit-diff-less-context` abort with an informative message).

For Git v2.38.0 or later, the `git merge-tree` mode that we use is actually deprecated.  We should be able to switch to using the new mode (`git merge-tree --write-tree`) to do a "real" merge that gives us back a tree ID (and other info).  With that ID, it's up to us to generate the diff ourselves, so we can relay standard diff options.

**Comment by tarsius** [comment]
> For Git v2.38.0 or later, the `git merge-tree` mode that we use is actually deprecated.  We should be able to switch to using the new mode (`git merge-tree --write-tree`) to do a "real" merge that gives us back a tree ID (and other info).  With that ID, it's up to us to generate the diff ourselves, so we can relay standard diff options.

I have looked into it and think that would work.

We would have to

1. `git merge-tree this-branch other-branch` to get the tree hash and list of files with conflicts.
2. `git show HASH:FILE` for each of them. Parse the diffs, and probably do extra work to hook up things correctly. Some things probably cannot be implemented on top of these diffs, and others features we would forget about, setting us up for more work later on. Also, instead of one call to git we would have to do one per conflicting file, plus one.
3. The `git-merge-tree` manpage mentions that there are other kinds of conflicts that cannot be displayed as diffs. We could ignore those, resulting in about the same information being displayed as now; or we could try to figure out what all the various lines indicating some other type of kind of conflict are, and try to come up with a way to display them and associate useful actions with them. But note that this information is not being displayed when actually *doing* a merge, so it cannot be essential that it is being displayed, so ignoring it is likely what I would opt for.
4. ...

I don't think this would be worth the effort.

A user can get the same *and more* by simply doing a proper merge, interacting with the result as if they actually wanted to resolve the conflicts now, and then abort the merge.

This would have several benefits, including but not limited to:

1. If it turns out that there are not actually any conflicts, they do not have to do a preview and then an actual merge.
2. Likewise it turns out that the conflicts are much easier to reason about and resolve, they can just do that.
3. If the conflicts are difficult to investigate/resolve, then all the tools that magit offers to do so are available, instead of some subset, which has to painfully increases by us maintainers when a user discovers a hole, such as the one brought up here.


So what are the downsides?

- Maybe the user doesn't actually want to merge. But if there aren't any conflicts, then the merge would be performed without the user being able to abort. We can address that by using the `--no-commit` and `--no-ff` arguments. It's a bit more complicated than that, so we should probably provide a separate merge-with-intention-to-abort command to do it.
- Maybe the user wants to preview a merge into branch other than the current branch and they don't want to or cannot checkout that branch. We can deal with that by creating a new worktree. Again, there are complications, e.g., if the user wants to preview a merge into the current branch but cannot do so because of uncommitted changes, then we would have to check out the tip of that branch directly in the temporary worktree, instead of the branch by its name.
- The downside for the user is that they cannot just press `q` and be done with the preview. They would have to switch back to the main worktree and then delete the merge-preview worktree. Actually when we create a new worktree for the purpose of displaying a merge "preview" there, we could arrange for `q` in the resulting status buffer to prompt to not only quit the buffer but also cleanup the worktree.

So yes, there are still details to be worked out and implementing this approach results in quite a bit of work too, but IMO this would result in something more useful, than the current merge-preview or anything else we could come up with based on `git merge-tree`'s new mode.

I probably won't get to it soon. But I do intend to implement more useful errors for the issue with `magit-diff-{more,less}-context` as suggested, before closing this.
