### ISSUE TITLE
Magit reports changes are already unstaged when they are in fact still staged

### ISSUE THREAD

**Issue by rdeusser** [magit/magit#4916]
For some reason Magit doesn't seem to see whether or not changes are staged/unstaged in hunks. I'm going to try to explain this with screenshots.

I removed all packages from Emacs for a fresh start and so that no leftover packages from earlier versions were hanging around and reinstalled them. I then ran Emacs via `/Applications/Emacs.app/Contents/MacOS/Emacs -Q --eval \(setq\ debug-on-error\ t\) -L /Users/rdeusser/.emacs.d/straight/build/compat/ -L /Users/rdeusser/.emacs.d/straight/build/dash/ -L /Users/rdeusser/.emacs.d/straight/build/transient/ -L /Users/rdeusser/.emacs.d/straight/build/with-editor/ -L /Users/rdeusser/.emacs.d/straight/build/magit/ -L /Users/rdeusser/.emacs.d/straight/build/magit-section/ -L /Users/rdeusser/.emacs.d/straight/build/git-commit/ -l /Users/rdeusser/.emacs.d/straight/build/magit/magit`

Starting with a single change in the README.md - the buffer on the right is from just running `M-x magit` and the buffer on the left is run from `d w`:

![Screenshot 2023-04-04 at 12 57 31 PM](https://user-images.githubusercontent.com/5935071/229867271-d62c2edc-44cc-4f77-822b-c6da1cfc4640.png)

I can select the hunk and stage the change with `s`:

![Screenshot 2023-04-04 at 12 57 49 PM](https://user-images.githubusercontent.com/5935071/229867085-5cb04f72-b569-4902-98ba-99c58643f332.png)

Now if I try to unstage that hunk with `u`:

![Screenshot 2023-04-04 at 12 59 34 PM](https://user-images.githubusercontent.com/5935071/229868018-79774bfa-9c66-4a34-8c86-f6fb1c5c39c6.png)

I get `Already unstaged` when it's clearly not. Now I can unstage all changes with `U` and that works just fine.

* Git version: 2.40.0
* Emacs version: 30.0.50

I toggled git debug and here's the log for that:
```
128 git … rev-parse --verify --abbrev-ref main\@\{upstream\}
fatal: no upstream configured for branch 'main'

128 git … rev-parse --short HEAD\~
fatal: Needed a single revision

  0 git … reset HEAD --
Unstaged changes after reset:
M	README.md

128 git … rev-parse --verify --abbrev-ref main\@\{upstream\}
fatal: no upstream configured for branch 'main'

128 git … rev-parse --short HEAD\~
fatal: Needed a single revision

  0 git … apply --cached -p0 --ignore-space-change -
128 git … rev-parse --verify --abbrev-ref main\@\{upstream\}
fatal: no upstream configured for branch 'main'

128 git … rev-parse --short HEAD\~
fatal: Needed a single revision

  0 git … reset HEAD --
Unstaged changes after reset:
M	README.md

128 git … rev-parse --verify --abbrev-ref main\@\{upstream\}
fatal: no upstream configured for branch 'main'

128 git … rev-parse --short HEAD\~
fatal: Needed a single revision
```

Let me know if there's anything else I can provide or if I'm dumb.

**Comment by tarsius** [comment]
It is impossible to tell which changes are staged and which are unstaged, merely by looking at the left buffer (which shows the output of `git diff HEAD`). This makes that buffer unsuitable for selective staging and unstaging. Unlike when displaying staged and unstaged changes separately as in the status buffer, in this buffer the state that we are most interested in when un-/staging (which parts are staged and which are not) is not visualized at all.

There is a slight difference in how unsuitable it, depending on whether you want to stage or unstage. I feel it makes slightly more (but still little) sense to use it for staging than it does to use it for unstaging. This is why the low-level code that determines what kind of diff is being displayed, classifies this diff as `unstaged`. That way it is possible to stage at least. There is no `staged-or-unstaged` state, and while it would theoretically be possible to implement that, doing so would complicated a lot of code.

The only other, existing "diff type" that would make sense, is  `undefined`. If we used that, then it wouldn't be possible to unstage *or* stage. Because I feel it makes at least a little bit of sense to stage from this diff, I have chosen to allow that, instead of outright disallowing both.

**Comment by rdeusser** [comment]
So it's behaving as intended then. Well the inverse works quite well for me so I just wanted to make sure it wasn't a bug. Thanks for the quick response @tarsius! Feel free to close this.
