### ISSUE TITLE
Breaking change: some magit-branch function are not synchronous anymore

### ISSUE THREAD

**Issue by DamienCassou** [magit/magit#4945]
In commit 25dbf32d86eaf1ccb7b652b2de392d749c4c2186, some magit-branch.el functions where changed to be asynchronous. I have nothing against that in principle but this change breaks users of these (public) functions which were expecting that the branch would be created when the function finishes. Some ideas:

1. Revert the change (just a joke)
2. Add an optional `callback` argument (that would be called when the branch is created) to every function. This way users of these functions can plug behavior.
3. Add a general-purpose hook mechanism to plug behavior when something is finished

We might also consider adding a synchronous function with the former name for each asynchronous one (which would have to be renamed) to keep backward compatibility.

**Comment by tarsius** [comment]
It seems to me, it would be much easier if you just used:

```elisp
    (magit-call-git ...)
    (magit-branch-maybe-adjust-upstream branch start-point)
```

in your code. Granted these functions are not marked as "for interactive use only" and few are in Magit, but maybe I should start marking more as such. I have considered doing so before, but have shied away from doing so because many commands actually can be used non-interactively and/or are complex enough to make it undesirable to force third-party code to re-implement them just because. That being said, when I make a previously synchronous function/command asynchronous, then I should mark it as interactive-only.

**Comment by DamienCassou** [comment]
Thank you @tarsius.

**Comment by tarsius** [comment]
By the way, I *have* added one synchronous variant `magit--checkout`, because `magit-checkout` was used in quite a few places in `magit` and related packages.

**Comment by DamienCassou** [comment]
I noticed that, thank you.
