### ISSUE TITLE
Upon installing v. 20230520.2119 from MELPA, I receive this error: "https://melpa.org/packages/magit-section-20230428.1518.tar Not found"

### ISSUE THREAD

**Issue by tomdavey** [magit/magit#4948]
I have reproduced this error by trying to resolve the offending URL in my browser: https://melpa.org/packages/magit-section-20230428.1518.tar. The URL resolves to a 404 page from nginx.

However, despite this dependency error, the MELPA install aborts gracefully. It does not install any part of the new release. My existing Magit installation still works fine. 

Thanks for all the work on Magit, which is for me the most essential Emacs package of all.

**Comment by tarsius** [comment]
Run `M-x package-refresh-contents`. After that Package will install the version that is actually available on Melpa at this time, instead of a version that used to be available.

This is not a Magit issue. You will encounter that with other packages. If you do, then always refresh the list of available packages.
