### ISSUE TITLE
Cannot commit empty merge with unstaged changes

### ISSUE THREAD

**Issue by darkfeline** [magit/magit#4985]
Magit 2.8.0-4071-gb4a9fba2, Transient 0.3.7, Git 2.41.0, Emacs 28.2, gnu/linux

When merging with Magit, if the merge is empty (e.g., after resolving conflicts from merging a branch with commits cherrypicked from the current branch), trying to finish the merge prompts the user to commit all uncommitted changes (e.g., due to submodules on WIP commits).  Answering no aborts the operation.  Thus, there does not appear to be a way to finish/commit an empty merge (when there are unstaged changes) using the Magit UI.

Workaround is to drop to a shell and run `git commit`.

**Comment by tarsius** [comment]
> Thus, there does not appear to be a way to finish/commit an empty merge using the Magit UI.

You can use Magit's general purpose "create a commit" command to do so, but have to pass it the `--allow-empty` argument: `c` `- e` `c`.

While a merge is in progress, `m` `m` actually invokes the same command (`magit-commit-create`), but the `m` transient does not feature the `--allow-empty` argument, so you can not enable it here.

The "Commit merge" action in the merge transient has been bound to `magit-commit-create` for a long time, but this does seem a bit strange to me. But I don't actually merge often (since I prefer rebasing), so I have not run into this often, and don't know how someone who does a lot of merging would feel about it.

That being said, it would probably make sense if the merge transient offered all of `git merge --abort / --continue / --quit`.  Currently it only offers `--abort`. `--continue` should probably replace `magit-commit-create`. And additionally adding `--quit` would probably be useful in some cases too.

**Comment by kyleam** [comment]
> Thus, there does not appear to be a way to finish/commit an empty merge using the Magit UI.

Both the title and this concluding statement don't mention the key "unstaged changes" part.

If there aren't any unstaged changes, the `--allow-empty` isn't necessary because 1) `magit-commit-assert` is happy and 2) Git won't insist on the flag for merge commits:

https://github.com/git/git/blob/f1ed9d7dc0e49dc1a044941d821c9d2342313c26/builtin/commit.c#L1057-L1061

@tarsius, perhaps `magit-commit-assert` should allow  unstaged changes?

```diff
diff --git a/lisp/magit-commit.el b/lisp/magit-commit.el
index f6ee9ad5..e23a9ae7 100644
--- a/lisp/magit-commit.el
+++ b/lisp/magit-commit.el
@@ -368,8 +368,7 @@ (defun magit-commit-assert (args &optional strict)
     (setq this-command #'magit-rebase-continue)
     (magit-run-git-sequencer "rebase" "--continue")
     nil)
-   ((and (file-exists-p (expand-file-name "MERGE_MSG" (magit-gitdir)))
-         (not (magit-anything-unstaged-p)))
+   ((file-exists-p (expand-file-name "MERGE_MSG" (magit-gitdir)))
     (or args (list "--")))
    ((not (magit-anything-unstaged-p))
     (user-error "Nothing staged (or unstaged)"))
```

With that, I can use `m m` to create an empty merge case when there are other unstaged changes, at least for the below demo case.

<details>
<summary>demo</summary>

```sh
#!/bin/sh

set -eu

tdir=$(mktemp -d "${TMPDIR:-/tmp}"/magit-XXXXXXX)

git clone https://github.com/magit/magit "$tdir"

cd "$tdir"

c=48818355728c48d986d74dde8b1e9fba25f0fd53
git checkout "$c"
sed -i 's/magit-log-format-message-function/&1A/g' lisp/magit-log.el
git add lisp/magit-log.el
git commit --amend --no-edit

git merge "$c" || :
git checkout --ours lisp/magit-log.el
git add lisp/magit-log.el

echo other >>README.md
```

</details>

**Comment by darkfeline** [comment]
> Both the title and this concluding statement don't mention the key "unstaged changes" part.

My bad, I updated them.

**Comment by tarsius** [comment]
I went with signaling an error if there are unmerged changes, and prompting the user when there are unstaged changes.
