### ISSUE TITLE
Multiple commands crashes in Emacs 30.0.50

### ISSUE THREAD

**Issue by hankmander** [magit/magit#5018]
Hi! First bug report from long-time Magit fan. This started happening with the latest version or two of Magit and is discussed in this [Stackexchange thread](https://emacs.stackexchange.com/questions/78766/magit-error-wrong-type-argument-listp) too without a solution. This example is what happens when running `magit-log-current` (`l-l`) from the magit-status popup, but it happens with other commands like `magit-commit-create` as well, while some things like staging works as usual.

Here is the backtrace and Magit version outputs (I have tried this in an emacs instance with only magit and deps loaded):

`Debugger entered--Lisp error: (wrong-type-argument listp #f(compiled-function (spec) #<bytecode 0x95717c51a14913c>))
  command-execute(magit-log-current)`

`Magit 20230924.1834 [>= 3.3.0.50-git], Transient 0.4.3, Git 2.42.0, Emacs 30.0.50, gnu/linux`

**Comment by jnpn** [comment]
The same magit version `Magit 20231006.2318 [>= 3.3.0.50-git], Transient 0.4.3, Git 2.42.0`

fails under my local emacs 30.0.50 build, but runs fine with emacs 29.1

so yeah, we should investigate what's wrong in our build.

Thanks again @tarsius

**Comment by richard-hunter-hpe** [comment]
Hitting this as well, emacs 30.0.50, building magit from tip. Not expecting support seeing as I'm on bleeding edge, but just thought I'd warn others!

**Comment by tarsius** [comment]
Well, I kinda force users to use the bleeding edge of *Magit*, so that's on me. (I plan to release, but it is complicated.)

When it comes to Emacs `master`, I use that too and I only very seldomly have issues with it myself. But yes, if that does not work, then users should try the latest stable release, and if that works stick to it for a while. Or investigate the issue themselves, that would be very useful. Having to investigate alleged issues with the latest Emacs `master`, which they cannot reproduce themselves, is not very appealing to package maintainers in general. (Having a short *me too* is kinda useful though. That does provide a signal, that it's not just one users messed up system. It does not prove that the package, for which the issue is reported, is at fault either. It's a signal, but its a bit vague :stuck_out_tongue_winking_eye:.)

**Comment by tarsius** [comment]
Well, I kinda force users to use the bleeding edge of *Magit*, so that's on me. (I plan to release, but it is complicated.)

When it comes to Emacs `master`, I use that too and I only very seldomly have issues with it myself. But yes, if that does not work, then users should try the latest stable release, and if that works stick to it for a while. Or investigate the issue themselves, that would be very useful. Having to investigate alleged issues with the latest Emacs `master`, which they cannot reproduce themselves, is not very appealing to package maintainers in general. (Having a short *me too* is kinda useful though. That does provide a signal, that it's not just one users messed up system. It does not prove that the package, for which the issue is reported, is at fault either. It's a signal, but its a bit vague :stuck_out_tongue_winking_eye:.)

**Comment by richard-hunter-hpe** [comment]
Agree completely... generally a plus-1 type of message has little value in proving much with regards to an open issue other than what you say.

This morning I completely rebuild emacs from `master` and reloaded all packages and the issue resolved itself. Which probably hints to it being my "messed up system". Hoping the OP can resolve doing the same. Not seeing anything pointing to a problem with magit itself.

**Comment by hankmander** [comment]
I also rebuilt emacs from source today and and now everything works! I suppose something must have been wrong with my build even though it worked for at least 6 months. I did not check the AOT compile flag this time which I might have done last time. Anyway, thanks for all the tips and the great project that this is! Really missed it a lot when it didn't work for two weeks. Hated going back to the cli. <3

**Comment by tarsius** [comment]
> I suppose something must have been wrong with my build even though it worked for at least 6 months.

If you use the development branch, then you should rebuild regularly. Doesn't have to be every week, but six months is way too long. Many package authors support Emacs' `master` branch, but assume that users are on a fairly recent build.
