### ISSUE TITLE
Package-Requires header should be single line

### ISSUE THREAD

**Issue by raxod502** [magit/magit#5028]
Hi, as you may recall I maintain the package manager `straight.el`. I was looking into https://github.com/magit/magit/issues/5011#issuecomment-1751816660 for https://github.com/radian-software/straight.el/issues/964#issuecomment-1755840957 and I do not think there is an issue with either Magit or `straight.el`, rather `seq` is not installed because it is already built-in, which is fine and expected.

But what I did notice is that `straight.el` cannot parse the `Package-Requires` header of Magit:

https://github.com/magit/magit/blob/f59df798194d4213b5a2b2f43a2ee25b71cbbb90/lisp/magit.el#L21-L28

I at first thought this was an oversight on my part, but actually the [Emacs documentation says explicitly](https://www.gnu.org/software/emacs/manual/html_node/elisp/Library-Headers.html) that this header must be a single line. In fact, `package-lint` fails to parse the header as well.

I do agree it is nicer to have the header on multiple lines, but given that the spec explicitly says otherwise, I think it might be better to follow it.

(This isn't causing an issue for `straight.el` at present, because Magit also includes a well-formed `magit-pkg.el`, which is read instead. In fact, I think the `Package-Requires` headers on most of the individual files could be dropped entirely.)

**Comment by doolio** [comment]
> rather `seq` is not installed because it is already built-in, which is fine and expected

Except for some Emacsen the built-in version does not have the new `seq-keep` function now required by Magit. This is the issue I face with the comments you linked to. Should `straight` consider removing `seq` from `straight-recipes-gnu-elpa-ignored-packages`?

**Comment by tarsius** [comment]
I'm quite busy right now, so I won't look into this in depth until next week.

> I at first thought this was an oversight on my part, but actually the [Emacs documentation says explicitly](https://www.gnu.org/software/emacs/manual/html_node/elisp/Library-Headers.html) that this header must be a single line.

That documentation is outdated. Since https://github.com/emacsmirror/emacs/commit/e8c46c2b6f76cc055366041b6112d61dd5f2dcf4 (https://debbugs.gnu.org/cgi/bugreport.cgi?bug=36301), this can be split across multiple lines.

I have taught `package-build.el` to do this already.

Looks like I know have to get involved in `package-lint.el` as well.

It should be trivial to adjust Straight, if it currently uses `lm-header`. If, like `package-lint` it rolls its own, then it might only be simple and thus slightly more work. :grinning:

**Comment by tarsius** [comment]
> > rather `seq` is not installed because it is already built-in, which is fine and expected
> 
> Except for some Emacsen the built-in version does not have the new `seq-keep` function now required by Magit. This is the issue I face with the comments you linked to. Should `straight` consider removing `seq` from `straight-recipes-gnu-elpa-ignored-packages`?

Yes. Straight should respect the dependencies specified for a package.

Without having looked at how `straight-recipes-gnu-elpa-ignored-packages` is actually used, I do get a sense that it is a kludge. Straight should be able to determine what packages are built into Emacs without that information being hard-coded. If you need to continue to hard-code this, then please make it possible to specify the bundled version, so that an entry can mean "don't install PKG, unless the minimal version, specified in a packages dependency list, is greater than N".

**Comment by raxod502** [comment]
Ah, good to know the documentation has changed. That is fair enough. There is definitely not an issue with Magit then.

And yes, I agree that the behavior by `straight.el` is incorrect given how built-in dependencies have evolved. It's a little difficult though as I did not program in version constraint resolution in the first place because it makes everything much more complicated. Will address on my side, in any case.

**Comment by tarsius** [comment]
> Ah, good to know the documentation has changed.

The code has changed but unfortunately the documentation was *not* kept up-to-date. I've just reported that at https://debbugs.gnu.org/cgi/bugreport.cgi?bug=66677.

> Will address on my side, in any case.

Please keep me in the loop. Thanks!

**Comment by raxod502** [comment]
https://github.com/radian-software/straight.el/pull/1125 resolves this. There was a hardcoded way of handling the `seq.el` package in `straight.el` that was added years ago to work around an upstream bug in `seq.el` that has since been fixed, also years ago. So, nothing fancy in terms of correctly parsing dependencies, just needed to remove a hardcoded hack.

**Comment by tarsius** [comment]
Great, thanks!
