### ISSUE TITLE
completing-read-multiple is not supported by ivy and similar

### ISSUE THREAD

**Issue by RomanHargrave** [magit/magit#5035]
In df8095b4da310997242578559726a0870fd72738, support for (un)staging of multiple files in a single operation was introduced. This itself is a good thing; however, it was introduced using `completing-read-multiple` which is not supported by minibuffer completion packages like Ivy. Whilst this is technically more of a problem with Ivy and similar packages, it is worth pointing out here because magit does explicitly mention packages such as Ivy and Helm in its documentation (e.g. for `magit-completing-read-function`) due to the very strong likelihood that magit users will have one of these packages installed.

When using Ivy or similar, this leads to an inconsistent experience where magit functions which use `completing-read` do receive vertical completion, while functions which use `completing-read-multiple`, (e.g. `magit-stage-file`) do not.

Ivy and similar packages _do_ support multiple selection, by allowing the user to mark multiple entries in the completion list; however, this functionality is not exposed through an implementation of `completing-read-multiple`, requiring instead the use of package specific APIs. There is presently [an issue](https://github.com/abo-abo/swiper/issues/3014) proposing advice for `completing-read-multiple` which would enable Ivy support, though it does not appear to have traction and, as such, it is likely up to individual project maintainers to decide how to solve the problem.

I would be willing to add Ivy multiple selection support to magit if there is interest, though doing so would (in a way) pollute magit with knowledge of Ivy, so I am not sure that doing so would be the way forward. I may replace Ivy with Vertico over this, although I figured I would bring this up to see if there is any interest in solving the compatibility issue.

**Comment by tarsius** [comment]
Thanks for a thoughtful message!

Funny enough the last thing I did before going to be was to stumble into some compatibility code for Ivy in one of my packages and wondering how long it would be until I could remove that. And the first programming related thing I did after getting up, was reading your post.

I think Ivy's time has passed. I used it myself for a few years and it deserves a lot of credit for paving the way for the current crop of completion packages. That being said, it does not use Emacs' completion infrastructure and that is a fatal flaw.

Because of that alone, it will not survive for that much longer. The question isn't if it will cease to be framework that other packages will/should accommodate, but when. At this point in time, I personally am willing to preserve existing compatibility kludges but don't intend to merge any new ones.

Users should migrate to Vertico, the new built-in vertical completion setup, or some other package that builds on the built-in completion machinery. Coming from Ivy that should require minimal effort and would result in an improved experience.

By using compatibility code such as found in the issue you linked to, one can avoid making that step for a little longer, and doing that is okay. If you decide you go down that road, then I suggest that you begin by investigating how to best implement that outside of Ivy, as well as, outside all the packages you use, which use completing-read-multiple. The code you linked to, could be a suitable starting point, but its possible that there are other, potentially better, implementations or even extensions floating around. Eventually you should try to get that merged into Ivy itself.
