### ISSUE TITLE
magit-log-select-mode doesn't wash the log

### ISSUE THREAD

**Issue by geza-herman** [magit/magit#5037]
If `--color --graph` is specified for a `magit-log-select-mode` buffer, magit doesn't interpret ansi color sequences. For example, if you do an interactive rebase, then in the commit selector you press `L` (to go to the option setter), `-c` (to enable `--color`), `g` (to refresh the buffer), the log buffer will have ansi sequences around the graph.

The reason is this part of the code in `magit-log-wash-log`. `magit-log-select-mode` derives from `magit-log-mode`, but `magit-log--color-graph` isn't set, because `magit-log-select-refresh-buffer` doesn't set it (at least I suppose `magit-log-select-refresh-buffer` should set it, because looking at the symmetry, for `magit-log-mode`, `magit-log-refresh-buffer` sets this variable).

```elisp
(if (derived-mode-p 'magit-log-mode)
    magit-log--color-graph
  (and (member "--graph" args)
    (member "--color" args)))
```

magit-version is `Magit 20231028.959 [>= 3.3.0.50-git], Transient 0.4.3, Git 2.38.1, Emacs 30.0.50, gnu/linux`.

(I'm not sure what the proper fix is, that's why it's a bug report instead of a PR.)

**Comment by tarsius** [comment]
I think the simplicity of some `select-log` functions compared to the respective `log` functions is due to the assumptions that users would normally not have a need to change arguments in the select buffers.

But since it is actually *possible* to change the arguments, we should of course prevent such incompatibilities.

Would you be satisfied if we just made it impossible to enable the `--color` argument in such buffers?

**Comment by tarsius** [comment]
Never mind, it's simple enough to just support this.

**Comment by geza-herman** [comment]
Thank you!
