### ISSUE TITLE
 Warning (comp): magit-files.el:503:20: Warning: `sort' called with 1 argument, but requires 2

### ISSUE THREAD

**Issue by TriAttack238** [magit/magit#5174]
Hello, I am a new Emacs user who has installed Magit using Elpaca. I cannot currently run `M-x magit-version` due to the issue referenced [here](https://github.com/magit/magit/issues/2070#issuecomment-2223423256). Additionally, I cannot find where magit is installed so I can't run the isolated test, but the only two extra packages I have installed at the moment are Elpaca and Magit. Both packages work flawlessly, but Magit seems to be running into trouble with native compilation. Upon starting a new session, these two warnings are given:

```
 ■  Warning (comp): c:/Users/seank/.emacs.d/elpaca/builds/transient/transient.el: Error: Internal native compiler error failed to compile
 ■  Warning (comp): magit-files.el:503:20: Warning: `sort' called with 1 argument, but requires 2
``` 
I know that transient.el is used by Magit, so these two errors could be related. What might be the cause?

**Comment by tarsius** [comment]
The second error is due to a very short-lived bug. Updating magit fixes it and also allows you to use `magit-version`.

The first error doesn't provide enough information for me to go on. Because it is a built-in package, elpaca does not update transient automatically. You should force it to be updated by installing it explicitly (and before magit), by adding something like this to you init file:

```elisp
(elpaca transient)
(elpaca magit)
```
