### ISSUE TITLE
Stop opening a browser for "Untracked files" in magit-status

### ISSUE THREAD

**Issue by kohnish** [magit/magit#5245]
In the latest (magit-visit-thing) it falls back to url for unsupported overviews such as git untracked files. It used to just show `(user-error "There is no thing at point that could be visited")))`, but now it opens a browser with `untracked/` which isn't really a url.  
  
Either support listing utracked files like staged files or revert it to show user-error so that it won't open a browser.

**Comment by kohnish** [comment]
@tarsius 
I never call it manually. On "RET" on "Untracked files" on RET it opens the URL untracked/.

**Comment by tarsius** [comment]
As I have said, `RET` on "Untracked files" is supposed to invoke `magit-diff-visit-files` (and so it doesn't matter what `magit-visit-thing` would do in this place).

Since I have now adjusted `magit-visit-thing`, the effect for you will be that `RET` in that no longer tries to visit an invalid URL in a browser.

However it will still not visit the file as expected, but it appears that is due to some issue on your end. I.e., you probably changed relevant key bindings.

**Comment by kohnish** [comment]
Of course it doesn't visit the file. I'm not pressing ret on file but untracked. I reversed the commit locally to stop it from opening a browser.
