### ISSUE TITLE
stage/unstage one line of change

### ISSUE THREAD

**Issue by levindu** [magit/magit#649]
Sometimes, changes cannot be refined into different hunks.
Staging/unstaging line by line solves this.

**Comment by Glumanda99** [comment]
Is there any simpler way of doing this? I got used to `tig` an ncurses git client and shortcuts there are way simpler, e.g. pressing `v` to stage a single line or just press it multiple times for multiple lines, rather than selecting them first with `v` and then press `s` to stage them.

**Comment by tarsius** [comment]
Please do not re-purpose ancient issues.

> Is there any simpler way of doing this?

No. `C-SPC s` to stage one line or `C-SPC C-n C-n s` to stage three lines seems okay - basically it's one (or maybe two, I don't know what `v` does, I am guessing it is a Vim binding) more keystroke.

**Comment by Glumanda99** [comment]
> Please do not re-purpose ancient issues.

I'm sure if I would've opened a new issue, you would've told me, to not use an issue tracker to ask questions. It seems like you never can get it right.

I found a simpler way, instead of `C-SPC s` I just do `v s`, though it would be simpler to just press `v`. I don't know why you even want to select lines first and then stage them. What other things would someone want to do in magit-status-mode other than staging lines?

**Comment by tarsius** [comment]
> I don't know why you even want to select lines first and then stage them.

By first selecting more than one line and only then run `git apply` it is possible to run `git apply` once in total instead of once per line. That's important because it improves performance.

**Comment by tarsius** [comment]
What is `v` bound to in your configuration?

**Comment by jtpavlock** [comment]
I have the same and it is an evil thing. It's mapped to `evil-visual-line`
