### ISSUE TITLE
Cannot commit with new commit workflow: wrong-type-argument stringp, nil

### ISSUE THREAD

**Issue by zachallaun** [magit/magit#772]
Hi there,

I've just upgraded magit and am running into an error when trying to commit: wrong-type-argument stringp, nil. Everything was previously working with the old-style commit workflow (`c` immediately dropping you into a log buffer, etc). I've confirmed that committing also fails in a brand-new git repo, but I'm not sure where to go from here.

The exact operations that lead to the error:
1. `M-x magit-status`
2. `s` to stage a file
3. `c` to begin commit
4. `c` to commit without any options -- this causes the error

Backtrace:

``` lisp
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  file-name-directory(nil)
  magit-commit(nil)
  call-interactively(magit-commit)
  magit-key-mode-command(magit-commit)
  (lambda nil (interactive) (magit-key-mode-command (quote magit-commit)))()
  call-interactively((lambda nil (interactive) (magit-key-mode-command (quote magit-commit))) nil nil)
  command-execute((lambda nil (interactive) (magit-key-mode-command (quote magit-commit))))
```

**Comment by Apteryks** [comment]
For the record, I had this error as well, but not for the same reason: it was caused by the emacs-diff-hl package that I use. It has a magit hook that misbehaved before this commit: https://github.com/dgutov/diff-hl/commit/f8ce39d157144ee4b22d386dd40673ea7f87ecd7#diff-7f5249a920cb714b91e751d32b9dc9ef  (available as of version 1.8.5).
